using System.Text.RegularExpressions;

namespace Switch2Pro.Bridge;

/// <summary>Feste Texte Deutsch → Koreanisch. Schlüssel bleiben die deutschen Originaltexte.</summary>
internal static partial class Tr
{
    private static readonly Dictionary<string, string> TextsKo = new(StringComparer.Ordinal)
    {
        // ---------- Fenster, Reiter, Abschnitte ----------
        ["Controller"] = "컨트롤러",
        // ---------- Desktop-Modus, Testseite, Vorlagen, Diagnose ----------
        ["Einblendung beim Verbinden"] = "연결 시 알림 표시",
        ["Kurze Anzeige am Bildschirmrand mit Spieler, Controller und Akkustand."] = "화면 가장자리에 플레이어, 컨트롤러, 배터리 잔량을 잠깐 표시합니다.",
        ["Desktop-Modus"] = "데스크톱 모드",
        ["Läuft kein Spiel, steuert der Controller Windows: linker Stick = Maus, rechter Stick = Scrollen, A = Klick, B = Rechtsklick, X = Taskansicht, Y = Bildschirmtastatur, Steuerkreuz = Pfeiltasten, LB/RB = zurück/vor, Start = Enter, Back = Esc, HOME = Startmenü. Back + Start 1 Sekunde halten pausiert ihn. In Vollbildspielen und Programmen mit eigenem Profil ist er automatisch aus."] = "게임이 실행 중이 아니면 컨트롤러로 Windows를 조작합니다: 왼쪽 스틱 = 마우스, 오른쪽 스틱 = 스크롤, A = 클릭, B = 오른쪽 클릭, X = 작업 보기, Y = 화상 키보드, 방향 패드 = 화살표 키, LB/RB = 뒤로/앞으로, Start = Enter, Back = Esc, HOME = 시작 메뉴. Back + Start를 1초간 누르면 일시 중지됩니다. 전체 화면 게임과 전용 프로필이 있는 프로그램에서는 자동으로 꺼집니다.",
        ["Zeigergeschwindigkeit"] = "포인터 속도",
        ["RT gedrückt halten macht den Zeiger langsam und genau."] = "RT를 누르고 있으면 포인터가 느리고 정확하게 움직입니다.",
        ["Desktop-Steuerung pausiert – Back + Start halten zum Fortsetzen."] = "데스크톱 조작 일시 중지 – Back + Start를 길게 눌러 다시 시작합니다.",
        ["Desktop-Steuerung aktiv – der Controller steuert Maus und Tastatur."] = "데스크톱 조작 활성 – 컨트롤러로 마우스와 키보드를 조작합니다.",
        ["Test"] = "테스트",
        ["Trigger"] = "트리거",
        ["Bewegung"] = "모션",
        ["Rundheit"] = "원형도",
        ["Berichte/s"] = "보고/초",
        ["Vibration testen"] = "진동 테스트",
        ["Kreis zurücksetzen"] = "원 초기화",
        ["Controller testen"] = "컨트롤러 테스트",
        ["Sticks einmal langsam ganz im Kreis drehen – die Linie zeigt, wie rund sie laufen. Gedrückte Tasten erscheinen unten in der Anzeige."] = "각 스틱을 천천히 한 바퀴 돌려 보세요. 선이 얼마나 둥글게 움직이는지 보여 줍니다. 누른 버튼은 아래에 표시됩니다.",
        ["🔇  Ton aus/an"] = "🔇  음소거/해제",
        ["⏭  Nächster Titel"] = "⏭  다음 곡",
        ["⏮  Vorheriger Titel"] = "⏮  이전 곡",
        ["🎙  Mikrofon stumm (Win+Alt+K)"] = "🎙  마이크 음소거 (Win+Alt+K)",
        ["🎙  Discord: Mikrofon stumm (Strg+Umschalt+M)"] = "🎙  Discord: 마이크 음소거 (Ctrl+Shift+M)",
        ["🎧  Discord: Ton aus (Strg+Umschalt+D)"] = "🎧  Discord: 헤드셋 음소거 (Ctrl+Shift+D)",
        ["🖥  Desktop anzeigen (Win+D)"] = "🖥  바탕 화면 보기 (Win+D)",
        ["🗂  Taskansicht (Win+Tab)"] = "🗂  작업 보기 (Win+Tab)",
        ["↔  Zum letzten Fenster (Alt+Tab)"] = "↔  마지막 창 (Alt+Tab)",
        ["Diagnose exportieren"] = "진단 정보 내보내기",
        ["Protokoll, Einstellungen und Systeminfos als ZIP-Datei – zum Anhängen an eine Fehlermeldung. Enthält keine Kopplungsschlüssel."] = "로그, 설정, 시스템 정보를 ZIP 파일로 저장합니다. 문제 신고에 첨부하세요. 페어링 키는 포함되지 않습니다.",
        // ---------- Desktop-Widget ----------
        ["Desktop-Widget"] = "바탕 화면 위젯",
        ["Kleines Kärtchen auf dem Desktop: verbundene Controller, Akku, Verbindung und Ausgabe auf einen Blick. Mit der Maus verschieben, Rechtsklick für Optionen, Doppelklick öffnet N-Connect."] = "바탕 화면의 작은 카드: 연결된 컨트롤러, 배터리, 연결 방식과 출력을 한눈에 볼 수 있습니다. 마우스로 끌어 옮기고, 오른쪽 클릭으로 옵션, 두 번 클릭하면 N-Connect가 열립니다.",
        ["Immer im Vordergrund"] = "항상 위에 표시",
        ["Widget bleibt über allen Fenstern sichtbar (sonst nur auf dem Desktop)."] = "위젯이 모든 창 위에 표시됩니다(끄면 바탕 화면에만 표시).",
        ["Kompakte Ansicht"] = "간단히 보기",
        ["Eine Zeile je Controller: Spieler, Name und Akku."] = "컨트롤러마다 한 줄: 플레이어, 이름, 배터리.",
        ["Deckkraft"] = "불투명도",
        ["nativ"] = "네이티브",
        ["Controller einschalten oder SYNC drücken"] = "컨트롤러를 켜거나 SYNC를 누르세요",
        ["N-Connect öffnen"] = "N-Connect 열기",
        ["Position zurücksetzen"] = "위치 초기화",
        ["Widget ausblenden"] = "위젯 숨기기",
        // ---------- Status-Kopfzeile, Ansicht ----------
        ["Farbschema"] = "색 구성표",
        ["Farben für Akzente, Knöpfe, Flächen und Ränder."] = "강조색, 버튼, 배경, 테두리 색상.",
        ["bereit"] = "준비됨",
        ["nicht verfügbar"] = "사용할 수 없음",
        ["Niedrigster Akku"] = "최저 배터리",
        ["lädt"] = "충전 중",
        ["gemischt"] = "혼합",
        ["Original-Controller"] = "원래 컨트롤러",
        ["versteckt"] = "숨김",
        ["sichtbar"] = "표시됨",
        ["HidHide fehlt"] = "HidHide 없음",
        ["Groß"] = "크게",
        ["Kompakt"] = "간단히",
        ["Einstellungen (optional)"] = "설정(선택 사항)",
        ["1. Windows und Spiele sehen den Controller als …"] = "1. Windows와 게임에서 컨트롤러가 다음과 같이 인식됩니다 …",
        ["2. Tasten A/B/X/Y"] = "2. 버튼 A/B/X/Y",
        ["3. Vibration, Sticks, Verbinden, Gyro-Maus"] = "3. 진동, 스틱, 연결, 자이로 마우스",
        ["4. Joy-Con"] = "4. Joy-Con",
        ["4. Joy-Con und Wii"] = "4. Joy-Con 및 Wii",
        ["Wii-Fernbedienung: Zeiger (Sensorleiste) steuert die Maus"] = "Wii 리모컨: 포인터(센서 바)로 마우스 제어",
        ["Zeiger"] = "포인터",
        ["kein Zeiger – Sensorleiste nicht im Blick"] = "포인터 없음 – 센서 바가 시야 밖에 있습니다",
        ["5. Zielen, Sticks, Trigger, Turbo"] = "5. 조준, 스틱, 트리거, 터보",
        ["6. Tastenbelegung und Profile  (Taste → Gamepad, Tastatur, Maus, Gyro-Maus, Shift-Ebene)"] =
            "6. 버튼 매핑 및 프로필(버튼 → 게임패드, 키보드, 마우스, 자이로 마우스, Shift 레이어)",
        ["Xbox-360-Controller  (empfohlen – läuft mit fast allen Spielen)"] = "Xbox 360 컨트롤러(권장 – 거의 모든 게임에서 작동)",
        ["PlayStation DualShock 4  (mit Bewegungssteuerung/Gyro – für Steam && Emulatoren)"] =
            "PlayStation DualShock 4(모션 컨트롤/자이로 포함 – Steam 및 에뮬레이터용)",
        ["Xbox-Belegung  (nach Position: untere Taste = A)"] = "Xbox 배열(위치 기준: 아래 버튼 = A)",
        ["Nintendo-Belegung  (nach Beschriftung: A bleibt A)"] = "Nintendo 배열(표기 기준: A는 그대로 A)",
        ["Vibration"] = "진동",
        ["Stärke:"] = "강도:",
        ["Stick-Totzone (alle Controller):"] = "스틱 데드존(모든 컨트롤러):",
        ["Beim Verbinden kurz vibrieren"] = "연결 시 짧게 진동",
        ["Meldung bei Verbinden"] = "연결 알림",
        ["Wer meldet, wenn ein Controller verbunden oder getrennt wird."] = "컨트롤러가 연결되거나 끊길 때 알릴 대상을 선택합니다.",
        ["„N-Connect“ zeigt den echten Controller-Namen und schaltet die Gerätemeldungen von Windows ab."] = "\"N-Connect\"는 실제 컨트롤러 이름을 표시하고 Windows 장치 알림을 끕니다.",
        ["N-Connect (empfohlen)"] = "N-Connect(권장)",
        ["N-Connect und Windows"] = "N-Connect 및 Windows",
        ["Keine"] = "없음",
        ["Gekoppelte Controller per Tastendruck verbinden (ohne SYNC)"] = "페어링된 컨트롤러를 버튼 하나로 연결(SYNC 불필요)",
        ["Automatisch mit Windows starten"] = "Windows 시작 시 자동 실행",
        ["Gyro für Emulatoren bereitstellen (Cemuhook/DSU, Port 26760 – wirkt nach Neustart)"] =
            "에뮬레이터에 자이로 제공(Cemuhook/DSU, 포트 26760 – 재시작 후 적용)",
        ["Beim Start nach neuer Version suchen (GitHub)"] = "시작 시 새 버전 확인(GitHub)",
        ["Ohne Eingabe automatisch trennen nach:"] = "입력이 없으면 자동으로 연결 해제:",
        ["Gyro-Maus-Geschwindigkeit:"] = "자이로 마우스 속도:",
        ["Sprache / Language:"] = "언어 / Language:",
        ["Automatisch (wie Windows)"] = "자동(Windows와 동일)",
        ["nie"] = "안 함",
        ["Zwei Joy-Con automatisch zu einem Controller zusammenfassen"] = "두 개의 Joy-Con을 하나의 컨트롤러로 자동 결합",
        ["Gyro beim Paar vom:"] = "페어의 자이로 사용 위치:",
        ["rechter Joy-Con (wie Switch)"] = "오른쪽 Joy-Con(Switch와 동일)",
        ["linker Joy-Con"] = "왼쪽 Joy-Con",
        ["Joy-Con 2 als Maus, wenn er auf dem Tisch liegt"] = "Joy-Con 2를 책상에 놓으면 마우스로 사용",
        ["Mausgeschwindigkeit:"] = "마우스 속도:",
        ["Maus: links/rechts umkehren"] = "마우스: 좌우 반전",
        ["Maus: hoch/runter umkehren"] = "마우스: 상하 반전",
        ["Wie an der Switch: SL + SR eine Sekunde halten löst einen Joy-Con aus dem Paar. L am linken und R am rechten einzelnen Joy-Con gleichzeitig drücken verbindet sie wieder zum Paar. Die Wahl wird je Joy-Con gemerkt (auch nach dem nächsten Verbinden). Im Mausmodus: R/L = Linksklick, ZR/ZL = Rechtsklick, Stick drücken = Mittelklick, Stick hoch/runter = Scrollen."] =
            "Switch와 동일: SL + SR을 1초간 누르면 Joy-Con이 페어에서 분리됩니다. 왼쪽 Joy-Con의 L과 오른쪽 Joy-Con의 R을 동시에 누르면 다시 페어가 됩니다. 선택은 Joy-Con별로 기억됩니다(다음 연결 후에도). 마우스 모드: R/L = 왼쪽 클릭, ZR/ZL = 오른쪽 클릭, 스틱 누르기 = 가운데 클릭, 스틱 위/아래 = 스크롤.",
        ["Gyro als rechter Stick:"] = "자이로를 오른쪽 스틱으로:",
        ["aus (nur per Taste „Gyro-Stick“)"] = "끔(„자이로 스틱“ 버튼으로만)",
        ["immer"] = "항상",
        ["beim Zielen (solange ZL / linker Trigger gedrückt)"] = "조준 시(ZL / 왼쪽 트리거를 누르는 동안)",
        ["hoch/runter umkehren"] = "상하 반전",
        ["Empfindlichkeit:"] = "감도:",
        ["Mindestausschlag:"] = "최소 출력:",
        ["Stick-Kennlinie:"] = "스틱 응답 곡선:",
        ["Turbo (pro Sekunde):"] = "터보(초당):",
        ["Analoge Trigger (GameCube) – Totzone:"] = "아날로그 트리거(GameCube) – 데드존:",
        ["voll gedrückt ab:"] = "완전히 눌림 기준:",
        ["Profil:"] = "프로필:",
        ["Neu …"] = "새로 만들기 …",
        ["Umbenennen …"] = "이름 바꾸기 …",
        ["Löschen"] = "삭제",
        ["Exportieren …"] = "보내기 …",
        ["Importieren …"] = "가져오기 …",
        ["Aktiv bei Programm:"] = "다음 프로그램에서 활성화:",
        ["Programm wählen …"] = "프로그램 선택 …",
        ["Standard"] = "기본값",
        ["Standard gilt immer, wenn kein anderes Profil passt"] = "다른 프로필이 맞지 않으면 기본값이 적용됩니다",
        ["z. B. Cemu.exe, Ryujinx.exe"] = "예: Cemu.exe, Ryujinx.exe",
        ["Ein eigenes Profil wird automatisch aktiv, solange eines seiner Programme im Vordergrund ist (sonst gilt „Standard“). Im Infobereich-Menü lässt sich ein Profil auch fest wählen."] =
            "전용 프로필은 지정된 프로그램 중 하나가 전면에 있을 때 자동으로 활성화됩니다(그 외에는 „기본값“). 알림 영역 메뉴에서 프로필을 고정할 수도 있습니다.",
        ["Controller:"] = "컨트롤러:",
        ["Eigene Stick-Totzone für diesen Controller:"] = "이 컨트롤러 전용 스틱 데드존:",
        ["Normale Belegung"] = "일반 매핑",
        ["Shift-Ebene (gilt, solange eine Taste mit „Shift-Ebene“ gehalten wird)"] = "Shift 레이어(„Shift 레이어“로 설정된 버튼을 누르는 동안 적용)",
        ["Alles auf Standard"] = "모두 초기화",
        ["Schließen"] = "닫기",
        ["wie normale Belegung"] = "일반 매핑과 동일",

        // ---------- Belegungsziele und Vorlagen ----------
        ["— keine Funktion —"] = "— 기능 없음 —",
        ["A (Xbox) / Kreuz (PS)"] = "A(Xbox) / ✕(PS)",
        ["B (Xbox) / Kreis (PS)"] = "B(Xbox) / ○(PS)",
        ["X (Xbox) / Viereck (PS)"] = "X(Xbox) / □(PS)",
        ["Y (Xbox) / Dreieck (PS)"] = "Y(Xbox) / △(PS)",
        ["Ansicht (Back) / Share"] = "보기(Back) / Share",
        ["Menü (Start) / Options"] = "메뉴(Start) / Options",
        ["Xbox-Taste / PS-Taste"] = "Xbox 버튼 / PS 버튼",
        ["Linker Stick-Klick"] = "왼쪽 스틱 클릭",
        ["Rechter Stick-Klick"] = "오른쪽 스틱 클릭",
        ["Steuerkreuz hoch"] = "십자키 위",
        ["Steuerkreuz runter"] = "십자키 아래",
        ["Steuerkreuz links"] = "십자키 왼쪽",
        ["Steuerkreuz rechts"] = "십자키 오른쪽",
        ["Touchpad-Klick (nur DualShock 4)"] = "터치패드 클릭(DualShock 4만)",
        ["🖱  Maus: Linksklick"] = "🖱  마우스: 왼쪽 클릭",
        ["🖱  Maus: Rechtsklick"] = "🖱  마우스: 오른쪽 클릭",
        ["🖱  Maus: Mittelklick"] = "🖱  마우스: 가운데 클릭",
        ["🎯  Gyro-Maus (solange gehalten)"] = "🎯  자이로 마우스(누르는 동안)",
        ["🎯  Gyro-Maus ein/aus"] = "🎯  자이로 마우스 켜기/끄기",
        ["🎯  Gyro als rechter Stick (solange gehalten)"] = "🎯  자이로를 오른쪽 스틱으로(누르는 동안)",
        ["🎯  Gyro als rechter Stick ein/aus"] = "🎯  자이로를 오른쪽 스틱으로 켜기/끄기",
        ["⇧  Shift-Ebene (solange gehalten)"] = "⇧  Shift 레이어(누르는 동안)",
        ["🔁  Turbo / Dauerfeuer …"] = "🔁  터보 / 연속 입력 …",
        ["⏯  Makro (Tastenfolge) …"] = "⏯  매크로(버튼 시퀀스) …",
        ["📷  Bildschirmfoto speichern (Win+Druck)"] = "📷  스크린샷 저장(Win+Print)",
        ["📷  Bildschirmausschnitt (Win+Umschalt+S)"] = "📷  화면 캡처(Win+Shift+S)",
        ["⏺  Letzte 30 Sekunden aufnehmen (Win+Alt+G)"] = "⏺  지난 30초 녹화(Win+Alt+G)",
        ["⏺  Aufnahme starten/stoppen (Win+Alt+R)"] = "⏺  녹화 시작/중지(Win+Alt+R)",
        ["🎮  Xbox Game Bar (Win+G)"] = "🎮  Xbox Game Bar(Win+G)",
        ["🔊  Lauter"] = "🔊  볼륨 높이기",
        ["🔉  Leiser"] = "🔉  볼륨 낮추기",
        ["⏯  Wiedergabe/Pause"] = "⏯  재생/일시 정지",
        ["⌨  Andere Taste / Tastenkombination aufnehmen …"] = "⌨  다른 키 / 키 조합 기록 …",

        // ---------- Tastennamen ----------
        ["+ (Plus)"] = "+(플러스)",
        ["− (Minus)"] = "−(마이너스)",
        ["Aufnahme"] = "캡처",
        ["GL (Rücktaste links)"] = "GL(뒤쪽 버튼 왼쪽)",
        ["GR (Rücktaste rechts)"] = "GR(뒤쪽 버튼 오른쪽)",
        ["Linker Stick drücken"] = "왼쪽 스틱 누르기",
        ["Rechter Stick drücken"] = "오른쪽 스틱 누르기",
        ["Stick drücken"] = "스틱 누르기",
        ["A (groß, unten)"] = "A(큰 버튼, 아래)",
        ["B (links)"] = "B(왼쪽)",
        ["X (rechts)"] = "X(오른쪽)",
        ["Y (oben)"] = "Y(위쪽)",
        ["L (ganz durchgedrückt)"] = "L(완전히 누름)",
        ["R (ganz durchgedrückt)"] = "R(완전히 누름)",
        ["untere Taste (quer)"] = "아래 버튼(가로)",
        ["rechte Taste (quer)"] = "오른쪽 버튼(가로)",
        ["linke Taste (quer)"] = "왼쪽 버튼(가로)",
        ["obere Taste (quer)"] = "위 버튼(가로)",
        ["1 (quer) / Classic Y"] = "1(가로) / Classic Y",
        ["2 (quer) / Classic B"] = "2(가로) / Classic B",
        ["B (Abzug) / Classic ZR"] = "B(트리거) / Classic ZR",
        ["Kreuz (unten)"] = "✕(아래)",
        ["Kreis (rechts)"] = "○(오른쪽)",
        ["Viereck (links)"] = "□(왼쪽)",
        ["Dreieck (oben)"] = "△(위)",
        ["PS-Taste"] = "PS 버튼",
        ["Touchpad-Klick"] = "터치패드 클릭",
        ["Mikro stumm"] = "마이크 음소거",
        ["Fn links (Edge)"] = "Fn 왼쪽(Edge)",
        ["Rücktaste links (Edge)"] = "뒤쪽 버튼 왼쪽(Edge)",
        ["Rücktaste rechts (Edge)"] = "뒤쪽 버튼 오른쪽(Edge)",
        ["L3 (Stick drücken)"] = "L3(스틱 누르기)",
        ["R3 (Stick drücken)"] = "R3(스틱 누르기)",
        ["Ansicht/Zurück"] = "보기/뒤로",
        ["Menü/Start"] = "메뉴/시작",
        ["Xbox-Taste"] = "Xbox 버튼",

        // ---------- Controller-Namen ----------
        ["Wii-Fernbedienung"] = "Wii 리모컨",
        ["Xbox-Controller"] = "Xbox 컨트롤러",
        ["Xbox-Controller (Microsoft)"] = "Xbox 컨트롤러(Microsoft)",
        ["XInput (USB, Bluetooth oder Xbox-Adapter)"] = "XInput(USB, Bluetooth 또는 Xbox 어댑터)",

        // ---------- Übersicht / Karten ----------
        ["Trennen"] = "연결 해제",
        ["Vibrieren"] = "진동",
        ["Gyro kalibrieren"] = "자이로 보정",
        ["Ruhig liegen lassen …"] = "가만히 두세요 …",
        ["Kalibriert ✓"] = "보정됨 ✓",
        ["Hochkant halten"] = "세로로 들기",
        ["Quer halten"] = "가로로 들기",
        ["Joy-Con trennen"] = "Joy-Con 분리",
        ["Zum Paar verbinden"] = "페어로 결합",
        ["Joy-Con trennen – beide werden einzelne Controller"] = "Joy-Con 분리 – 둘 다 개별 컨트롤러가 됩니다",
        ["Zum Paar verbinden – sucht einen freien Joy-Con"] = "페어로 결합 – 사용 가능한 Joy-Con을 찾습니다",
        ["Doppelt angezeigt? Verstecken"] = "중복 표시? 숨기기",
        ["amiibo lesen"] = "amiibo 읽기",
        ["Ring-Con ein"] = "Ring-Con 켜기",
        ["Ring-Con aus"] = "Ring-Con 끄기",
        ["Ring-Con wird gesucht …"] = "Ring-Con 검색 중 …",
        ["IR-Kamera"] = "IR 카메라",
        ["Akku"] = "배터리",
        ["Verbindung"] = "연결",
        ["Adresse"] = "주소",
        ["Seriennummer"] = "일련 번호",
        ["Griff"] = "그립",
        ["Maus"] = "마우스",
        ["Gedrückt"] = "눌림",
        ["unbekannt"] = "알 수 없음",
        ["Charging Grip – GL/GR aktiv"] = "Charging Grip – GL/GR 활성",
        ["aktiv (liegt auf dem Tisch)"] = "활성(책상 위에 놓여 있음)",
        ["bereit – zum Benutzen auf den Tisch legen"] = "준비됨 – 책상에 놓으면 사용 가능",
        ["Bewegungssensor: keine Daten"] = "모션 센서: 데이터 없음",
        ["quer halten: Steuerkreuz links,\n1 und 2 rechts"] = "가로로 들기: 십자키 왼쪽,\n1과 2 오른쪽",

        // ---------- Tooltips ----------
        ["Verbindung trennen. Der Controller verbindet sich beim nächsten Tastendruck wieder."] =
            "연결을 해제합니다. 컨트롤러는 다음 버튼 입력 시 다시 연결됩니다.",
        ["Controller kurz vibrieren lassen – zeigt, welcher Controller dieser Spieler ist."] =
            "컨트롤러를 짧게 진동시킵니다 – 어떤 컨트롤러가 이 플레이어의 것인지 보여줍니다.",
        ["Controller ruhig auf den Tisch legen und klicken: misst den Gyro-Nullpunkt neu (gegen Abdriften)."] =
            "컨트롤러를 책상에 가만히 놓고 클릭: 자이로 영점을 다시 측정합니다(드리프트 방지).",
        ["Einzelnen Joy-Con quer (wie an der Switch) oder hochkant halten – wird je Joy-Con gemerkt. Hochkant gilt die Tastenbelegung von „Joy-Con-Paar“."] =
            "단독 Joy-Con을 가로(Switch처럼) 또는 세로로 들 수 있습니다 – Joy-Con별로 기억됩니다. 세로로 들면 „Joy-Con 페어“ 매핑이 적용됩니다.",
        ["Versteckt den per USB angeschlossenen Controller vor Spielen (HidHide), damit sie nur den virtuellen Xbox-Controller sehen."] =
            "USB로 연결된 컨트롤러를 게임에서 숨깁니다(HidHide). 게임은 가상 Xbox 컨트롤러만 보게 됩니다.",
        ["amiibo mit dem NFC-Leser lesen und als Datei (.bin) speichern – z. B. für Emulatoren."] =
            "NFC 리더로 amiibo를 읽어 파일(.bin)로 저장합니다 – 예: 에뮬레이터용.",
        ["Ring-Con am rechten Joy-Con ein-/ausschalten: zusammendrücken = rechter Trigger, auseinanderziehen = linker Trigger. Beim Einschalten den Ring nicht berühren."] =
            "오른쪽 Joy-Con의 Ring-Con을 켜거나 끕니다: 누르면 = 오른쪽 트리거, 당기면 = 왼쪽 트리거. 켤 때는 링을 만지지 마세요.",
        ["Live-Bild der IR-Kamera im rechten Joy-Con anzeigen."] = "오른쪽 Joy-Con의 IR 카메라 라이브 화면을 표시합니다.",
        ["Links = empfindlicher (kleine Drehung, großer Ausschlag), rechts = ruhiger."] = "왼쪽 = 더 민감(작은 회전으로 큰 출력), 오른쪽 = 더 차분.",
        ["Mindestausschlag des Sticks bei Bewegung – überwindet die Totzone des Spiels."] = "움직일 때 스틱의 최소 출력 – 게임의 데드존을 극복합니다.",
        ["Mitte = linear. Rechts = feiner um die Mitte (präzises Zielen), links = schneller."] = "중앙 = 리니어. 오른쪽 = 중앙 근처에서 더 세밀(정밀 조준), 왼쪽 = 더 빠름.",
        ["So weit lässt sich ein analoger Trigger drücken, bevor er wirkt."] = "아날로그 트리거가 반응하기까지 누를 수 있는 범위입니다.",
        ["Ab hier gilt der Trigger als ganz gedrückt (100 = erst am Anschlag)."] = "여기부터 트리거가 완전히 눌린 것으로 간주됩니다(100 = 끝까지 눌러야 함).",
        ["Wie oft pro Sekunde Tasten mit „Turbo“ auslösen."] = "„터보“ 버튼이 초당 발동되는 횟수입니다.",

        // ---------- Infobereich ----------
        ["ViGEmBus-Treiber fehlt"] = "ViGEmBus 드라이버가 없습니다",
        ["ViGEmBus herunterladen …"] = "ViGEmBus 다운로드 …",
        ["Verbinde …"] = "연결 중 …",
        ["Kein Controller – SYNC-Taste am Controller kurz drücken"] = "컨트롤러 없음 – 컨트롤러의 SYNC 버튼을 짧게 누르세요",
        ["Ausgabe als"] = "출력 형태",
        ["Xbox-360-Controller (empfohlen)"] = "Xbox 360 컨트롤러(권장)",
        ["DualShock 4 (mit Gyro für Steam/Emulatoren)"] = "DualShock 4(Steam/에뮬레이터용 자이로 포함)",
        ["Tastenbelegung"] = "버튼 매핑",
        ["Xbox-Belegung (untere Taste = A)"] = "Xbox 배열(아래 버튼 = A)",
        ["Switch-2-Pro-Belegung (A bleibt A)"] = "Nintendo 배열(A는 그대로 A)",
        ["Automatisch (nach Spiel/Programm)"] = "자동(게임/프로그램에 따라)",
        ["Mit Windows starten"] = "Windows 시작 시 실행",
        ["Einstellungen …"] = "설정 …",
        ["Kurzanleitung"] = "빠른 시작 가이드",
        ["Protokoll öffnen"] = "로그 열기",
        ["Beenden"] = "종료",
        ["N-Connect: warte auf Controller (SYNC drücken)"] = "N-Connect: 컨트롤러 대기 중(SYNC를 누르세요)",
        ["N-Connect: ViGEmBus fehlt"] = "N-Connect: ViGEmBus 없음",
        ["Neue Version verfügbar"] = "새 버전 사용 가능",
        ["Einstellungen fehlerhaft"] = "설정이 손상됨",
        ["settings.json konnte nicht gelesen werden – es gelten die Standardwerte."] = "settings.json을 읽을 수 없습니다 – 기본값이 적용됩니다.",
        ["Ohne ViGEmBus kann kein virtueller Controller erzeugt werden. Bitte das Setup erneut ausführen oder ViGEmBus installieren (Rechtsklick auf das Symbol → ViGEmBus herunterladen)."] =
            "ViGEmBus가 없으면 가상 컨트롤러를 생성할 수 없습니다. 설치 프로그램을 다시 실행하거나 ViGEmBus를 설치하세요(아이콘 우클릭 → ViGEmBus 다운로드).",

        // ---------- Dialoge ----------
        ["Tastatur-Taste festlegen"] = "키보드 키 설정",
        ["Übernehmen"] = "적용",
        ["Abbrechen"] = "취소",
        ["Ja"] = "예",
        ["Nein"] = "아니요",
        ["Turbo / Dauerfeuer"] = "터보 / 연속 입력",
        ["Tastatur-Taste aufnehmen …"] = "키보드 키 기록 …",
        ["Makro (Tastenfolge)"] = "매크로(버튼 시퀀스)",
        ["Ungültig – bitte Schreibweise prüfen (siehe oben)."] = "유효하지 않음 – 작성법을 확인하세요(위 참조).",
        ["Neues Profil"] = "새 프로필",
        ["Name des Profils (z. B. der Spielname):"] = "프로필 이름(예: 게임 이름):",
        ["Profil umbenennen"] = "프로필 이름 바꾸기",
        ["Neuer Name:"] = "새 이름:",
        ["Ein Profil mit diesem Namen gibt es schon."] = "이 이름의 프로필이 이미 있습니다.",
        ["Die Datei enthält kein gültiges Controller-Profil."] = "파일에 유효한 컨트롤러 프로필이 없습니다.",
        ["Alle Einstellungen und Tastenbelegungen auf Standard zurücksetzen?"] = "모든 설정과 버튼 매핑을 초기화하시겠습니까?",
        ["Suche …"] = "검색 중 …",
        ["Kein Bluetooth-Adapter gefunden."] = "Bluetooth 어댑터를 찾을 수 없습니다.",
        ["IR-Kamera (Joy-Con R)"] = "IR 카메라(Joy-Con 오른쪽)",
        ["Auflösung:"] = "해상도:",
        ["40 × 30 (schnell)"] = "40 × 30(빠름)",
        ["320 × 240 (langsam)"] = "320 × 240(느림)",
        ["Kamera startet …"] = "카메라 시작 중 …",
        ["läuft – Joy-Con auf eine Lichtquelle oder die Hand richten"] = "작동 중 – Joy-Con을 광원이나 손에 향하세요",
        ["Kamera startet nicht (Details im Protokoll)"] = "카메라가 시작되지 않습니다(자세한 내용은 로그 참조)",
        ["Kein Ring-Con gefunden. Den rechten Joy-Con (Switch 1) fest in den Ring-Con schieben und erneut versuchen."] =
            "Ring-Con을 찾을 수 없습니다. 오른쪽 Joy-Con(Switch 1)을 Ring-Con에 단단히 끼우고 다시 시도하세요.",
        ["Kein amiibo erkannt. Bitte das amiibo flach an den NFC-Leser halten (Joy-Con: auf den rechten Stick, Pro Controller: auf das NFC-Logo) und erneut versuchen."] =
            "amiibo가 인식되지 않습니다. amiibo를 NFC 리더에 평평하게 대세요(Joy-Con: 오른쪽 스틱, Pro Controller: NFC 로고) 후 다시 시도하세요.",
        ["NFC-Leser wird eingeschaltet …"] = "NFC 리더를 켜는 중 …",
        ["amiibo an den Leser halten (rechter Stick des Joy-Con bzw. NFC-Logo des Pro Controllers) …"] =
            "amiibo를 리더에 대주세요(Joy-Con 오른쪽 스틱 또는 Pro Controller의 NFC 로고) …",
        ["amiibo speichern"] = "amiibo 저장",
        ["Doppelte Controller verhindern"] = "컨트롤러 중복 방지",
        ["Dafür wird das kostenlose Programm HidHide gebraucht (von den Machern von ViGEmBus).\n\nJetzt die Download-Seite öffnen? Nach der Installation hier erneut klicken."] =
            "이를 위해 무료 프로그램 HidHide가 필요합니다(ViGEmBus 개발사).\n\n지금 다운로드 페이지를 여시겠습니까? 설치 후 여기를 다시 클릭하세요.",
        ["HidHide konnte nicht eingerichtet werden (abgebrochen oder fehlgeschlagen). Details im Protokoll."] =
            "HidHide를 설정할 수 없습니다(취소되었거나 실패). 자세한 내용은 로그를 참조하세요.",
        ["Der Controller hat sich bewegt oder keine Bewegungsdaten geliefert.\nBitte flach auf den Tisch legen, nicht berühren und erneut versuchen."] =
            "컨트롤러가 움직였거나 동작 데이터가 수신되지 않았습니다.\n책상에 평평하게 놓고 만지지 말고 다시 시도하세요.",
        ["Spiel oder Programm wählen"] = "게임 또는 프로그램 선택",
        ["Profil exportieren"] = "프로필보내기",
        ["Profil importieren"] = "프로필 가져오기",
        ["Verstanden"] = "확인",
        ["Einstellungen öffnen"] = "설정 열기",
        ["Willkommen"] = "환영합니다",

        // ---------- Neues Hauptfenster (Navigation, Seiten, Zeilen) ----------
        ["Allgemein"] = "일반",
        ["Sticks & Vibration"] = "스틱 및 진동",
        ["Gyro & Maus"] = "자이로 및 마우스",
        ["Joy-Con & Wii"] = "Joy-Con 및 Wii",
        ["Ein"] = "켜기",
        ["Aus"] = "끄기",
        ["Verbundene Controller mit Live-Anzeige. Über „Einstellungen“ an einem Controller passt du genau diesen an."] =
            "연결된 컨트롤러를 실시간으로 표시합니다. 컨트롤러의 „설정“에서 해당 컨트롤러만 조정할 수 있습니다.",
        ["Jede Taste kann ein Gamepad-Knopf, eine Tastaturtaste, ein Mausklick, Turbo oder ein Makro sein. " +
         "Tipp: Drückst du eine Taste am Controller, wird ihre Zeile hervorgehoben."] =
            "모든 버튼에 게임패드 버튼, 키보드 키, 마우스 클릭, 터보 또는 매크로를 지정할 수 있습니다. " +
            "팁: 컨트롤러의 버튼을 누르면 해당 줄이 강조됩니다.",
        ["Profil"] = "프로필",
        ["Neu"] = "새로 만들기",
        ["Umbenennen, löschen, exportieren, importieren"] = "이름 바꾸기, 삭제,보내기, 가져오기",
        ["Ein eigenes Profil gilt automatisch, solange eines seiner Programme im Vordergrund ist – sonst „Standard“."] =
            "전용 프로필은 지정된 프로그램 중 하나가 전면에 있을 때 자동으로 적용됩니다 – 그 외에는 „기본값“.",
        ["Aktiv bei Programm"] = "다음 프로그램에서 활성화",
        ["Programmdateien, bei denen dieses Profil gilt (mit Komma trennen)."] = "이 프로필이 적용되는 프로그램 파일(쉼표로 구분).",
        ["Standard gilt für alle Programme"] = "기본값은 모든 프로그램에 적용",
        ["Wählen …"] = "선택 …",
        ["Bearbeiten"] = "편집",
        ["Jeder Controller hat seine eigene Belegung."] = "각 컨트롤러마다 고유한 매핑이 있습니다.",
        ["Ebene"] = "레이어",
        ["Normal"] = "일반",
        ["Shift-Ebene"] = "Shift 레이어",
        ["Die Shift-Ebene gilt, solange eine Taste mit „Shift-Ebene“ gehalten wird."] = "„Shift 레이어“로 설정된 버튼을 누르는 동안 Shift 레이어가 적용됩니다.",
        ["Tasten"] = "버튼",
        ["Standardwerte für alle Controller. Eigene Werte für einzelne Controller stellst du unten oder in der Übersicht ein."] =
            "모든 컨트롤러의 기본값. 개별 컨트롤러의 값은 아래 또는 개요에서 설정할 수 있습니다.",
        ["Sticks"] = "스틱",
        ["Totzone"] = "데드존",
        ["So weit lässt sich ein Stick bewegen, bevor er wirkt (gegen Abdriften)."] = "스틱이 반응하기까지 움직일 수 있는 범위(드리프트 방지).",
        ["Kennlinie"] = "응답 곡선",
        ["„linear“ = gleichmäßig. Höher = feiner um die Mitte (präzises Zielen), niedriger = schneller."] =
            "„리니어“ = 균일. 높을수록 중앙 근처가 세밀(정밀 조준), 낮을수록 빠릅니다.",
        ["Analoge Trigger (GameCube)"] = "아날로그 트리거(GameCube)",
        ["So weit lässt sich ein Trigger drücken, bevor er wirkt."] = "트리거가 반응하기까지 누를 수 있는 범위입니다.",
        ["Voll gedrückt ab"] = "완전히 눌림 기준",
        ["Ab hier gilt der Trigger als ganz gedrückt (100 % = erst am Anschlag)."] = "여기부터 트리거가 완전히 눌린 것으로 간주됩니다(100 % = 끝까지 눌러야 함).",
        ["Spiele dürfen den Controller vibrieren lassen."] = "게임이 컨트롤러를 진동시킬 수 있습니다.",
        ["Stärke"] = "강도",
        ["Turbo-Geschwindigkeit"] = "터보 속도",
        ["Wie oft pro Sekunde Tasten mit „Turbo“ auslösen."] = "„터보“ 버튼이 초당 발동되는 횟수입니다.",
        ["Eigene Werte je Controller"] = "컨트롤러별 개별 값",
        ["Werte nur für diesen Controller – ohne eigenen Wert gilt der allgemeine."] = "이 컨트롤러만의 값 – 개별 값이 없으면 전체 값이 적용됩니다.",
        ["Bewegungssteuerung: Zielen per Gyro und den Controller als Maus nutzen."] = "모션 컨트롤: 자이로로 조준하고 컨트롤러를 마우스로 사용합니다.",
        ["Gyro als rechter Stick"] = "자이로를 오른쪽 스틱으로",
        ["Modus"] = "모드",
        ["Zum Zielen in Spielen ohne eigene Gyro-Steuerung. „Gyro-Stick“ kann auch einer Taste zugewiesen werden."] =
            "자이로 미지원 게임에서 조준하기 위한 기능입니다. „자이로 스틱“은 버튼에 할당할 수도 있습니다.",
        ["Aus (nur per Taste „Gyro-Stick“)"] = "끔(„자이로 스틱“ 버튼으로만)",
        ["Immer"] = "항상",
        ["Beim Zielen (solange ZL / LT gedrückt)"] = "조준 시(ZL / LT를 누르는 동안)",
        ["Empfindlichkeit"] = "감도",
        ["Drehgeschwindigkeit für vollen Stick-Ausschlag – kleiner = empfindlicher."] = "스틱 최대 출력에 필요한 회전 속도 – 낮을수록 민감합니다.",
        ["Mindestausschlag"] = "최소 출력",
        ["Überwindet die Stick-Totzone des Spiels bei kleinen Bewegungen."] = "작은 움직임에서 게임의 스틱 데드존을 극복합니다.",
        ["Hoch/runter umkehren"] = "상하 반전",
        ["Links/rechts umkehren"] = "좌우 반전",
        ["Gyro-Maus"] = "자이로 마우스",
        ["Geschwindigkeit"] = "속도",
        ["Mauszeiger per Bewegung – über eine Taste mit „Gyro-Maus“ (Tastenbelegung)."] = "동작으로 마우스 포인터 조작 – „자이로 마우스“ 버튼 사용(버튼 매핑).",
        ["Mausrichtung (Gyro-Maus und Joy-Con-Maus)"] = "마우스 방향(자이로 마우스 및 Joy-Con 마우스)",
        ["Gyro-Funktionen einer Taste zuweisen"] = "버튼에 자이로 기능 할당",
        ["Gyro-Maus oder Gyro-Stick ein/aus bzw. solange gehalten"] = "자이로 마우스 또는 자이로 스틱 켜기/끄기 또는 누르는 동안",
        ["Joy-Con als Paar oder einzeln, Joy-Con 2 als Maus und Wii-Controller."] = "Joy-Con 페어 또는 단독 사용, Joy-Con 2 마우스 및 Wii 컨트롤러.",
        ["Zu einem Controller zusammenfassen"] = "하나의 컨트롤러로 결합",
        ["Ein linker und ein rechter Joy-Con werden automatisch ein Paar."] = "왼쪽과 오른쪽 Joy-Con이 자동으로 페어가 됩니다.",
        ["Gyro beim Paar vom"] = "페어의 자이로 사용 위치",
        ["Rechter Joy-Con (wie Switch)"] = "오른쪽 Joy-Con(Switch와 동일)",
        ["Linker Joy-Con"] = "왼쪽 Joy-Con",
        ["Paar lösen oder verbinden"] = "페어 해제 또는 결합",
        ["Einen Joy-Con quer halten und SL oder SR drücken löst ihn aus dem Paar. L am linken und R am rechten Joy-Con gleichzeitig drücken verbindet sie wieder. Die Wahl wird je Joy-Con gemerkt."] =
            "Joy-Con을 가로로 들고 SL 또는 SR을 누르면 페어에서 분리됩니다. 왼쪽의 L과 오른쪽의 R을 동시에 누르면 다시 결합됩니다. 선택은 Joy-Con별로 기억됩니다.",
        ["Joy-Con 2 als Maus"] = "Joy-Con 2를 마우스로",
        ["Als Maus, wenn er auf dem Tisch liegt"] = "책상에 놓으면 마우스로 사용",
        ["Joy-Con 2 auf die Seite legen und wie eine Maus schieben."] = "Joy-Con 2를 옆으로 눕혀 마우스처럼 밉니다.",
        ["Mausgeschwindigkeit"] = "마우스 속도",
        ["Tasten im Mausmodus"] = "마우스 모드의 버튼",
        ["R/L = Linksklick, ZR/ZL = Rechtsklick, Stick drücken = Mittelklick, Stick hoch/runter = Scrollen."] =
            "R/L = 왼쪽 클릭, ZR/ZL = 오른쪽 클릭, 스틱 누르기 = 가운데 클릭, 스틱 위/아래 = 스크롤.",
        ["Zeiger steuert die Maus"] = "포인터로 마우스 제어",
        ["Wii-Fernbedienung auf die Sensorleiste richten, um den Mauszeiger zu bewegen."] = "Wii 리모컨을 센서 바에 향해 마우스 포인터를 움직입니다.",
        ["Wie Spiele die Controller sehen, Verbindung, Darstellung und Programm."] = "게임에서 보이는 컨트롤러, 연결, 디자인 및 프로그램 설정.",
        ["Ausgabe"] = "출력",
        ["Controller erscheint als"] = "컨트롤러 표시",
        ["Xbox 360 läuft mit fast allen Spielen. DualShock 4 bietet Bewegungssteuerung (Steam, Emulatoren)."] =
            "Xbox 360은 거의 모든 게임에서 작동합니다. DualShock 4는 모션 컨트롤을 제공합니다(Steam, 에뮬레이터).",
        ["Xbox 360 läuft mit fast allen Spielen und Steam. DualShock 4 bietet zusätzlich Bewegungssteuerung (Steam, Emulatoren). Gilt für alle Controller ohne eigene Einstellung (Karte → Einstellungen → Tasten)."] =
            "Xbox 360은 거의 모든 게임과 Steam에서 작동합니다. DualShock 4는 모션 컨트롤을 추가로 제공합니다(Steam, 에뮬레이터). 개별 설정이 없는 모든 컨트롤러에 적용됩니다(카드 → 설정 → 버튼).",
        ["Original-Controller verstecken"] = "원본 컨트롤러 숨기기",
        ["Controller verbinden"] = "컨트롤러 연결",
        ["SYNC-Taste am Controller drücken – N-Connect findet und koppelt ihn selbst. Danach reicht künftig ein Tastendruck."] =
            "컨트롤러의 SYNC 버튼을 누르세요 – N-Connect가 자동으로 찾아 페어링합니다. 이후에는 버튼 하나로 연결됩니다.",
        ["So kommt der Controller in den Kopplungsmodus"] = "컨트롤러를 페어링 모드로 만드는 방법",
        ["Kurz die kleine SYNC-Taste drücken."] = "작은 SYNC 버튼을 짧게 누릅니다.",
        ["SYNC-Taste drücken, bis die Lichter laufen."] = "LED가 흐를 때까지 SYNC 버튼을 누릅니다.",
        ["Batteriefach öffnen und die rote SYNC-Taste drücken."] = "배터리 커버를 열고 빨간 SYNC 버튼을 누릅니다.",
        ["Die SYNC-Taste auf der Unterseite drücken."] = "하단의 SYNC 버튼을 누릅니다.",
        ["PS + Teilen bzw. Create halten, bis die Lichtleiste schnell blinkt."] =
            "라이트 바가 빠르게 깜박일 때까지 PS + Share/Create를 누르고 있습니다.",
        ["Kopplungstaste oben halten, bis die Xbox-Taste blinkt."] = "Xbox 버튼이 깜박일 때까지 상단의 페어링 버튼을 누르고 있습니다.",
        ["Status"] = "상태",
        ["Suche läuft …"] = "검색 중 …",
        ["Suche läuft – jetzt SYNC drücken …"] = "검색 중 – 지금 SYNC를 누르세요 …",
        ["Weitere Controller? Einfach SYNC drücken."] = "다른 컨트롤러? SYNC를 누르기만 하면 됩니다.",
        ["Wartet auf einen Controller im Kopplungsmodus."] = "페어링 모드의 컨트롤러를 기다리는 중입니다.",
        ["Suche beendet"] = "검색 완료",
        ["Die Controller stehen in der Übersicht und verbinden sich künftig per Tastendruck."] =
            "컨트롤러가 개요에 표시되며 이후 버튼 하나로 연결됩니다.",
        ["Kein Controller im Kopplungsmodus gefunden. SYNC-Taste drücken und „Erneut suchen“ klicken."] =
            "페어링 모드의 컨트롤러를 찾지 못했습니다. SYNC를 누르고 „다시 검색“을 클릭하세요.",
        ["Verbunden"] = "연결됨",
        ["Erneut suchen"] = "다시 검색",
        ["Fertig"] = "완료",
        ["Im Spiel"] = "게임 내",
        ["Dreht …"] = "회전 중 …",
        ["Testdrehung (360°)"] = "테스트 회전(360°)",
        ["Testdrehung"] = "테스트 회전",
        ["aus"] = "끔",
        ["Gyro-Beschleunigung"] = "자이로 가속",
        ["Bei schneller Drehung"] = "빠른 회전 시",
        ["Langsame Bewegungen bleiben fein, schnelle drehen weiter (wie JoyShockMapper). Voll ab 120 °/s, unter 20 °/s normal. Gilt für Gyro-Stick und Gyro-Maus."] =
            "느린 움직임은 세밀하게 유지되고, 빠른 움직임은 더 멀리 회전합니다(JoyShockMapper와 동일). 120 °/s 이상에서 최대, 20 °/s 미만은 일반. 자이로 스틱과 자이로 마우스에 적용됩니다.",
        ["Flick-Stick (Spiele mit Maussteuerung)"] = "플릭 스틱(마우스 조작 게임용)",
        ["Flick-Stick"] = "플릭 스틱",
        ["Rechten Stick in eine Richtung schieben = Kamera dreht sofort dorthin; am Rand drehen = Kamera dreht mit. Zielen dann per Gyro. Der rechte Stick geht nicht mehr ans Spiel."] =
            "오른쪽 스틱을 밀면 카메라가 즉시 그 방향으로 돌아가고, 가장자리를 따라 돌리면 카메라가 회전합니다. 이후 자이로로 조준합니다. 오른쪽 스틱은 게임에 전달되지 않습니다.",
        ["Mausbewegung je Umdrehung"] = "회전당 마우스 이동량",
        ["Je Spiel einmal einstellen: „Testdrehung“ klicken, ins Spiel wechseln – nach 3 s dreht die Kamera einmal. Genau eine volle Drehung = richtig."] =
            "게임별로 한 번만 설정: „테스트 회전“을 클릭하고 게임으로 전환 – 3초 후 카메라가 한 바퀴 돕니다. 정확히 한 바퀴면 올바른 설정입니다.",
        ["Flick-Dauer"] = "플릭 시간",
        ["So lange dauert die Drehung beim Flick (0 = sofort)."] = "플릭 시 회전에 걸리는 시간(0 = 즉시).",
        ["Gyro-Maus oder Gyro-Stick ein/aus bzw. solange gehalten, „Gyro anhalten“ (Ratchet: Controller zurückführen, ohne dass sich das Ziel bewegt)"] =
            "자이로 마우스 또는 자이로 스틱 켜기/끄기 또는 누르는 동안, „자이로 일시 정지“(래칫: 조준점을 움직이지 않고 컨트롤러 되돌리기)",
        ["✋  Gyro anhalten (solange gehalten, „Ratchet“)"] = "✋  자이로 일시 정지(누르는 동안, „래칫“)",
        ["Spieler-LED und Lichtleiste vom Spiel"] = "플레이어 LED 및 게임 라이트 바",
        ["Die Spieler-LEDs zeigen den Xbox-Platz, den Windows vergibt. Bei DualShock 4 steuert die Lichtleiste des Spiels die HOME-LED (Switch 1 Pro Controller, rechter Joy-Con)."] =
            "플레이어 LED는 Windows가 할당한 Xbox 위치를 표시합니다. DualShock 4에서는 게임의 라이트 바가 HOME LED를 제어합니다(Switch 1 Pro Controller, 오른쪽 Joy-Con).",
        ["HidHide installieren …"] = "HidHide 설치 …",
        ["Empfohlen: Steam und viele Spiele kennen Switch-1-, NSO- und USB-Controller selbst und sähen sie sonst doppelt. Läuft nach der Installation ohne Rückfrage (sonst fragt Windows nach Adminrechten)."] =
            "권장: Steam과 많은 게임이 Switch 1, NSO, USB 컨트롤러를 자체 인식해 이중으로 표시합니다. 설치 후에는 확인 없이 작동합니다(그렇지 않으면 Windows가 관리자 권한을 요청합니다).",
        ["Steam und viele Spiele sehen Switch-1-, NSO- und USB-Controller sonst doppelt. Dafür wird das kostenlose HidHide gebraucht (bei der N-Connect-Installation dabei, hier nachträglich)."] =
            "이것이 없으면 Steam과 많은 게임에서 Switch 1, NSO, USB 컨트롤러가 이중으로 표시됩니다. 무료 HidHide가 필요합니다(N-Connect 설치에 포함, 여기서 나중에 설치 가능).",
        ["Erscheint als"] = "표시 형태",
        ["Wie allgemein"] = "일반 설정과 동일",
        ["Nur für diesen Controller. Xbox 360 läuft überall; DualShock 4 bringt zusätzlich Gyro nach Steam und in Emulatoren. „Wie allgemein“ folgt der Seite „Allgemein“."] =
            "이 컨트롤러만 적용됩니다. Xbox 360은 어디서나 작동하고, DualShock 4는 Steam과 에뮬레이터에 자이로를 추가합니다. „일반 설정과 동일“은 „일반“ 페이지를 따릅니다.",
        ["Der echte Xbox-Controller – Spiele sehen ihn von Windows aus direkt. Belegungen hier wirken auf Sonderaktionen (Tastatur, Makros, Gyro), nicht auf den Controller selbst."] =
            "실제 Xbox 컨트롤러 – 게임이 Windows를 통해 직접 인식합니다. 여기의 매핑은 특수 동작(키보드, 매크로, 자이로)에 작용하며 컨트롤러 자체에는 영향을 주지 않습니다.",
        ["Steam und manche Spiele sehen diesen Controller sonst doppelt. Abhilfe: HidHide installieren (Seite „Allgemein“ → „Original-Controller verstecken“)."] =
            "이것이 없으면 Steam과 일부 게임에서 이 컨트롤러가 이중으로 표시됩니다. 해결 방법: HidHide 설치(„일반“ 페이지 → „원본 컨트롤러 숨기기“).",
        ["Original-Controller vor Spielen versteckt. Steam bitte einmal neu starten – danach sieht es nur noch den virtuellen Controller."] =
            "원본 컨트롤러가 게임에서 숨겨졌습니다. Steam을 한 번 다시 시작하세요 – 이후 가상 컨트롤러만 표시됩니다.",
        ["Original-Controller vor Spielen versteckt – Steam und Spiele sehen nur noch den virtuellen Controller."] =
            "원본 컨트롤러가 게임에서 숨겨졌습니다 – Steam과 게임은 이제 가상 컨트롤러만 보게 됩니다.",
        ["Original-Controller nicht versteckt (Abfrage abgebrochen). Nachholen: Controller → Einstellungen → Extras → „Doppelt angezeigt?“."] =
            "원본 컨트롤러가 숨겨지지 않았습니다(확인 취소됨). 나중에: 컨트롤러 → 설정 → 기타 → „중복 표시?“.",
        ["Tastenanordnung A/B/X/Y"] = "버튼 배열 A/B/X/Y",
        ["Xbox: nach Position (untere Taste = A). Nintendo: nach Beschriftung (A bleibt A)."] = "Xbox: 위치 기준(아래 버튼 = A). Nintendo: 표기 기준(A는 그대로 A).",
        ["Verbinden"] = "연결",
        ["Per Tastendruck verbinden"] = "버튼 하나로 연결",
        ["Gekoppelte Controller verbinden sich ohne SYNC-Taste."] = "페어링된 컨트롤러는 SYNC 버튼 없이 연결됩니다.",
        ["Ohne Eingabe trennen nach"] = "입력이 없으면 연결 해제",
        ["Spart Akku, wenn ein Controller liegen bleibt."] = "컨트롤러를 놓아두면 배터리를 절약합니다.",
        ["N-Connect startet unsichtbar im Infobereich."] = "N-Connect가 알림 영역에서 조용히 시작됩니다.",
        ["Darstellung und Sprache"] = "디자인 및 언어",
        ["Farbmodus"] = "색상 모드",
        ["Mica-Effekt"] = "Mica 효과",
        ["Durchscheinende Titelleiste (ab Windows 11)."] = "반투명 제목 표시줄(Windows 11 이상).",
        ["Erweitert"] = "고급",
        ["Gyro für Emulatoren (DSU)"] = "에뮬레이터용 자이로(DSU)",
        ["Cemuhook-Server auf Port 26760 – wirkt nach einem Neustart von N-Connect."] = "포트 26760의 Cemuhook 서버 – N-Connect 재시작 후 적용됩니다.",
        ["Nach Updates suchen"] = "업데이트 확인",
        ["Beim Start auf GitHub nach einer neuen Version suchen."] = "시작 시 GitHub에서 새 버전을 확인합니다.",
        ["Tastenbelegungen und Werte zurücksetzen. Gekoppelte Controller bleiben erhalten."] = "버튼 매핑과 값을 초기화합니다. 페어링된 컨트롤러는 유지됩니다.",
        ["Zurücksetzen"] = "초기화",

        // ---------- Controller-Karte ----------
        ["Einstellungen"] = "설정",
        ["Tastenbelegung und Einstellungen nur für diesen Controller"] = "이 컨트롤러 전용 버튼 매핑 및 설정",
        ["Feineinstellung"] = "세부 조정",
        ["Gyro"] = "자이로",
        ["Extras"] = "기타",
        ["Belegung für alle Spiele (Standard) oder ein eigenes Profil."] = "모든 게임의 매핑(기본값) 또는 전용 프로필.",
        ["Profile"] = "프로필",
        ["Profile anlegen, umbenennen, exportieren …"] = "프로필 생성, 이름 변경,보내기 …",
        ["Drück eine Taste am Controller – ihre Zeile leuchtet auf. ⌨ weist eine Tastaturtaste zu, ↺ setzt zurück."] =
            "컨트롤러의 버튼을 누르면 해당 줄이 강조됩니다. ⌨로 키보드 키를 할당하고 ↺로 초기화합니다.",
        ["Tastatur-Taste zuweisen: klicken und die gewünschte Taste oder Kombination drücken."] = "키보드 키 할당: 클릭 후 원하는 키 또는 조합을 누르세요.",
        ["Zurück auf die Standardbelegung"] = "기본 매핑으로 되돌리기",
        ["Ohne eigenen Wert gilt der allgemeine Wert der Seite „Sticks & Vibration“."] = "개별 값이 없으면 „스틱 및 진동“ 페이지의 전체 값이 적용됩니다.",
        ["Stick-Totzone"] = "스틱 데드존",
        ["Stick-Kennlinie"] = "스틱 응답 곡선",
        ["Trigger-Totzone"] = "트리거 데드존",
        ["Trigger voll gedrückt ab"] = "트리거 완전히 눌림 기준",
        ["Vibrationsstärke"] = "진동 강도",
        ["Gyro-Maus-Geschwindigkeit"] = "자이로 마우스 속도",
        ["Eigenen Wert entfernen – es gilt wieder der allgemeine Wert"] = "개별 값 제거 – 전체 값이 다시 적용됩니다",
        ["Kalibrieren"] = "보정",
        ["Controller ruhig auf den Tisch legen und klicken: misst den Nullpunkt neu (gegen Abdriften)."] =
            "컨트롤러를 책상에 가만히 놓고 클릭: 영점을 다시 측정합니다(드리프트 방지).",
        ["Gyro als rechter Stick und Mausrichtung"] = "자이로를 오른쪽 스틱으로 / 마우스 방향",
        ["Gilt für alle Controller"] = "모든 컨트롤러에 적용",
        ["Paar"] = "페어",
        ["Joy-Con quer halten und SL oder SR drücken löst das Paar, L + R gleichzeitig verbindet es."] =
            "Joy-Con을 가로로 들고 SL 또는 SR을 누르면 페어가 해제되고, L + R을 동시에 누르면 다시 결합됩니다.",
        ["Haltung"] = "자세",
        ["Quer"] = "가로",
        ["Hochkant"] = "세로",
        ["Quer wie an der Switch oder hochkant – hochkant gilt die Belegung von „Joy-Con-Paar“."] =
            "Switch처럼 가로로 들거나 세로로 들 수 있습니다 – 세로일 때는 „Joy-Con 페어“ 매핑이 적용됩니다.",
        ["Mausmodus, Geschwindigkeit und Tasten"] = "마우스 모드, 속도 및 버튼",
        ["Lesen …"] = "읽기 …",
        ["Einschalten"] = "켜기",
        ["Ausschalten"] = "끄기",
        ["Wird gesucht …"] = "검색 중 …",
        ["Öffnen"] = "열기",
        ["Verstecken"] = "숨기기",
        ["amiibo an den NFC-Leser halten und als Datei (.bin) speichern – z. B. für Emulatoren."] =
            "amiibo를 NFC 리더에 대고 파일(.bin)로 저장 – 예: 에뮬레이터용.",
        ["Zusammendrücken = rechter Trigger, auseinanderziehen = linker Trigger. Beim Einschalten nicht berühren."] =
            "누르면 = 오른쪽 트리거, 당기면 = 왼쪽 트리거. 켤 때는 만지지 마세요.",
        ["Live-Bild der Infrarotkamera im rechten Joy-Con."] = "오른쪽 Joy-Con의 적외선 카메라 라이브 화면.",
        ["Doppelt angezeigt?"] = "중복 표시?",
        ["Versteckt den Original-Controller vor Steam und Spielen (HidHide) – sie sehen dann nur den virtuellen Controller."] =
            "원본 컨트롤러를 Steam과 게임에서 숨깁니다(HidHide) – 가상 컨트롤러만 보게 됩니다.",
        ["bereit (auf den Tisch legen)"] = "준비됨(책상에 놓으세요)",
        ["amiibo-Abbild (*.bin)|*.bin"] = "amiibo 이미지 (*.bin)|*.bin",
        ["Controller-Profil (*.ncprofile.json)|*.ncprofile.json|JSON (*.json)|*.json"] = "컨트롤러 프로필 (*.ncprofile.json)|*.ncprofile.json|JSON (*.json)|*.json",
        ["Programme (*.exe)|*.exe"] = "프로그램 (*.exe)|*.exe",
        ["Kein Controller verbunden\n\n" +
         "Switch-2-Controller: kurz die SYNC-Taste drücken – danach reicht ein beliebiger Tastendruck.\n" +
         "Switch-1-, NSO- und Wii-Controller: SYNC-Taste drücken – N-Connect koppelt sie selbst.\n" +
         "Oder hier gezielt suchen und koppeln:"] =
            "연결된 컨트롤러가 없습니다\n\n" +
            "Switch 2 컨트롤러: SYNC 버튼을 짧게 누르세요 – 이후 아무 버튼이나 누르면 됩니다.\n" +
            "Switch 1, NSO 및 Wii 컨트롤러: SYNC 버튼을 누르세요 – N-Connect가 자동으로 페어링합니다.\n" +
            "또는 여기에서 직접 검색 및 페어링:",
        ["Controller suchen …"] = "컨트롤러 검색 …",
        ["Kein Controller verbunden"] = "연결된 컨트롤러 없음",
        ["Switch-1-, NSO- und Wii-Controller suchen und koppeln (SYNC-Taste drücken)."] =
            "Switch 1, NSO 및 Wii 컨트롤러 검색 및 페어링(SYNC 버튼 누르기).",
        ["Neue Controller automatisch koppeln"] = "새 컨트롤러 자동 페어링",
        ["Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive, Wii und PlayStation: einfach SYNC " +
         "drücken – kein Umweg über die Windows-Bluetooth-Einstellungen. Gesucht wird nur, solange niemand spielt."] =
            "Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive, Wii, PlayStation: SYNC만 누르면 됩니다 – " +
            "Windows Bluetooth 설정을 거칠 필요가 없습니다. 검색은 누구도 플레이하지 않을 때만 진행됩니다.",
        ["Gezielt suchen"] = "직접 검색",
        ["Sucht eine Minute lang nach Controllern im Kopplungsmodus."] = "페어링 모드의 컨트롤러를 1분간 검색합니다.",
        ["Controller koppeln …"] = "컨트롤러 페어링 …",
        ["Controller koppeln"] = "컨트롤러 페어링",
        ["Linken Joy-Con umbenennen …"] = "왼쪽 Joy-Con 이름 바꾸기 …",
        ["Rechten Joy-Con umbenennen …"] = "오른쪽 Joy-Con 이름 바꾸기 …",
        ["Controller umbenennen"] = "컨트롤러 이름 바꾸기",
        ["Spielerplatz"] = "플레이어 위치",
        ["N-Connect aktualisieren"] = "N-Connect 업데이트",
        ["HidHide aktualisieren"] = "HidHide 업데이트",
        ["HidHide-Update verfügbar"] = "HidHide 업데이트 사용 가능",
        ["HidHide aktuell halten"] = "HidHide 최신 상태 유지",
        ["Beim Start nach einer neuen HidHide-Version suchen. Installiert wird nur nach Rückfrage (geprüfter Download vom Hersteller, Neustart nötig)."] =
            "시작 시 새 HidHide 버전을 확인합니다. 확인 후에만 설치됩니다(제조사의 검증된 다운로드, 재시작 필요).",
        ["Der Download hat nicht geklappt oder die Datei war fehlerhaft. Die Release-Seite im Browser öffnen?"] =
            "다운로드에 실패했거나 파일이 손상되었습니다. 브라우저에서 릴리스 페이지를 여시겠습니까?",
        ["Alle Controller trennen"] = "모든 컨트롤러 연결 해제",
        ["Sticks kalibrieren"] = "스틱 보정",
        ["Kalibrieren …"] = "보정 …",
        ["Gegen Drift oder zu kleinen Ausschlag: Mitte und Rand neu messen. Wird nur in N-Connect gespeichert, der Controller bleibt unverändert."] =
            "드리프트나 너무 작은 가동 범위에 대응: 중심과 가장자리를 다시 측정합니다. N-Connect에만 저장되며 컨트롤러는 변경되지 않습니다.",
        ["Linker Stick"] = "왼쪽 스틱",
        ["Rechter Stick"] = "오른쪽 스틱",
        ["Stick"] = "스틱",
        ["Stick (linker Joy-Con)"] = "스틱(왼쪽 Joy-Con)",
        ["Stick (rechter Joy-Con)"] = "스틱(오른쪽 Joy-Con)",
        ["Neu messen"] = "다시 측정",
        ["Werkswerte"] = "공장 설정값",
        ["Der Punkt zeigt, wo der Stick gerade steht. Steht er losgelassen nicht in der Mitte oder erreicht er den Kreis nicht, auf „Neu messen“ klicken."] =
            "점이 스틱의 현재 위치를 보여줍니다. 손을 뗐을 때 중앙에 있지 않거나 원에 닿지 않으면 „다시 측정“을 클릭하세요.",
        ["Gilt gerade: eigene Kalibrierung."] = "현재 사용 중: 사용자 보정.",
        ["Gilt gerade: Werkswerte des Controllers."] = "현재 사용 중: 컨트롤러의 공장 설정값.",
        ["1/2 – Stick loslassen und den Controller ruhig halten …"] = "1/2 – 스틱에서 손을 떼고 컨트롤러를 가만히 두세요 …",
        ["2/2 – Stick bis zum Anschlag drücken und langsam ein- bis zweimal im Kreis drehen."] =
            "2/2 – 스틱을 끝까지 밀고 천천히 한두 바퀴 돌리세요.",
        ["Fertig. „Übernehmen“ speichert die neue Kalibrierung für diesen Controller."] = "완료. „적용“을 누르면 이 컨트롤러의 새 보정이 저장됩니다.",
        ["Der Stick hat den Rand nicht erreicht. Bitte bis zum Anschlag drücken und erneut messen."] =
            "스틱이 가장자리에 닿지 않았습니다. 끝까지 밀고 다시 측정하세요.",
        ["Übernommen ✓ – gilt ab sofort."] = "적용됨 ✓ – 즉시 적용됩니다.",
        ["Werkswerte des Controllers gelten wieder."] = "컨트롤러의 공장 설정값이 다시 적용됩니다.",
        ["Gyro einrichten"] = "자이로 설정",
        ["Einrichten …"] = "설정 …",
        ["Zielen per Bewegung einrichten"] = "동작 조준 설정",
        ["Schritt für Schritt: Nullpunkt, wann der Gyro zielt, Empfindlichkeit – mit Vorschau."] =
            "단계별 안내: 영점, 자이로가 조준하는 시점, 감도 – 미리보기 포함.",
        ["1  Nullpunkt"] = "1  영점",
        ["Controller flach auf den Tisch legen, nicht berühren – verhindert, dass das Ziel von selbst wandert."] =
            "컨트롤러를 책상에 평평하게 놓고 만지지 마세요 – 조준점이 저절로 움직이는 것을 방지합니다.",
        ["Nullpunkt messen"] = "영점 측정",
        ["Der Controller hat sich bewegt – bitte flach hinlegen und erneut versuchen."] = "컨트롤러가 움직였습니다 – 평평하게 놓고 다시 시도하세요.",
        ["Nullpunkt gemessen ✓"] = "영점 측정 완료 ✓",
        ["2  Wann zielt der Gyro?"] = "2  자이로가 조준하는 시점",
        ["Nur per Taste"] = "버튼으로만",
        ["Beim Zielen (ZL/LT)"] = "조준 시(ZL/LT)",
        ["„Beim Zielen“: nur solange ZL (linker Trigger) gehalten wird – wie in vielen Shootern."] =
            "„조준 시“: ZL(왼쪽 트리거)을 누르는 동안만 – 많은 슈팅 게임과 동일합니다.",
        ["3  Empfindlichkeit"] = "3  감도",
        ["Voller Ausschlag ab"] = "최대 출력 기준 회전 속도",
        ["Kleinerer Wert bei „Voller Ausschlag ab“ = empfindlicher. „Mindestausschlag“ überwindet die Totzone des Spiels."] =
            "„최대 출력 기준 회전 속도“가 낮을수록 민감합니다. „최소 출력“은 게임의 데드존을 극복합니다.",
        ["Mitte"] = "중앙",
        ["Vorschau: Fadenkreuz folgt dem Controller (unabhängig von Schritt 2)."] = "미리보기: 조준점이 컨트롤러를 따라갑니다(2단계와 무관).",
        ["Keine Bewegungsdaten"] = "동작 데이터 없음",
        ["Controller gekoppelt"] = "컨트롤러 페어링됨",
        ["Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive: SYNC-Taste drücken, bis die Lichter laufen.\n" +
         "Wii-Fernbedienung: Batteriefach öffnen und die rote SYNC-Taste drücken.\n" +
         "Wii U Pro Controller: die SYNC-Taste auf der Unterseite drücken.\n" +
         "Danach verbindet sich der Controller künftig per Tastendruck."] =
            "Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive: LED가 흐를 때까지 SYNC 버튼을 누릅니다.\n" +
            "Wii 리모컨: 배터리 커버를 열고 빨간 SYNC 버튼을 누릅니다.\n" +
            "Wii U Pro Controller: 하단의 SYNC 버튼을 누릅니다.\n" +
            "이후 컨트롤러는 버튼 하나로 연결됩니다.",
        ["Suche … SYNC-Taste drücken (Xbox: Kopplungstaste oben halten, PlayStation: PS + Teilen/Create halten)."] =
            "검색 중 … SYNC 버튼을 누르세요(Xbox: 상단의 페어링 버튼을 길게 누르기, PlayStation: PS + Share/Create 길게 누르기).",
        ["Kein Controller im Kopplungsmodus gefunden. SYNC-Taste drücken und erneut versuchen."] =
            "페어링 모드의 컨트롤러를 찾지 못했습니다. SYNC를 누르고 다시 시도하세요.",
        ["Darstellung:"] = "디자인:",
        ["Dunkel"] = "다크",
        ["Hell"] = "라이트",
        ["Wie Windows"] = "Windows와 동일",
        ["Mica-Effekt in der Titelleiste (ab Windows 11)"] = "제목 표시줄 Mica 효과(Windows 11 이상)",

        // ---------- Fehlerfälle und Hinweise ----------
        ["Bluetooth ist ausgeschaltet."] = "Bluetooth가 꺼져 있습니다.",
        ["Dieser Bluetooth-Adapter unterstützt kein Bluetooth LE."] = "이 Bluetooth 어댑터는 Bluetooth LE를 지원하지 않습니다.",
        ["Bluetooth-Suche konnte nicht starten."] = "Bluetooth 검색을 시작할 수 없습니다.",
        ["Bluetooth in den Windows-Einstellungen einschalten."] = "Windows 설정에서 Bluetooth를 켜세요.",
        ["Controller per USB funktionieren weiterhin."] = "USB로 연결된 컨트롤러는 계속 사용할 수 있습니다.",
        ["Für Switch-2-Controller wird ein Adapter mit Bluetooth 4.0 oder neuer gebraucht."] = "Switch 2 컨트롤러에는 Bluetooth 4.0 이상의 어댑터가 필요합니다.",
        ["Andere Controller und USB funktionieren weiterhin."] = "다른 컨트롤러와 USB는 계속 사용할 수 있습니다.",
        ["Bluetooth-Adapter (z. B. USB-Stick) einstecken bzw. Bluetooth in Windows aktivieren."] =
            "Bluetooth 어댑터(예: USB 동글)를 연결하거나 Windows에서 Bluetooth를 활성화하세요.",
        ["Bluetooth ist bereit – Controller können verbunden werden."] = "Bluetooth가 준비되었습니다 – 컨트롤러를 연결할 수 있습니다.",
        ["Bluetooth-Einstellungen öffnen"] = "Bluetooth 설정 열기",
        ["ViGEmBus-Treiber fehlt – ohne ihn kann kein virtueller Controller erzeugt werden."] =
            "ViGEmBus 드라이버가 없습니다 – 이것 없이는 가상 컨트롤러를 생성할 수 없습니다.",
        ["Bitte das Setup erneut ausführen."] = "설치 프로그램을 다시 실행하세요.",
        ["Das Programm schließen oder in Steam die Nintendo-Unterstützung abschalten."] =
            "해당 프로그램을 종료하거나 Steam에서 Nintendo 지원을 끄세요.",
        ["Erst einen anderen trennen."] = "먼저 다른 컨트롤러의 연결을 해제하세요.",
        ["Tipp: Bluetooth-Stick per Verlängerung näher an den Controller, weg von USB-3-Anschlüssen und Funkkopfhörern."] =
            "팁: Bluetooth 동글을 연장 케이블로 컨트롤러 가까이 두고, USB 3 포트와 무선 헤드셋에서 멀리 두세요.",
        ["Controller mit dem PC gekoppelt – ab jetzt reicht ein Tastendruck."] = "컨트롤러가 PC와 페어링되었습니다 – 이제 버튼 하나로 연결됩니다.",
        ["Hinweis: Um ihn wieder an der Switch 2 zu nutzen, dort einmal kurz SYNC drücken."] =
            "참고: Switch 2에서 다시 사용하려면 본체에서 SYNC를 한 번 짧게 누르세요.",
        ["Dieser Bluetooth-Adapter unterstützt kein Bluetooth LE"] = "이 Bluetooth 어댑터는 Bluetooth LE를 지원하지 않습니다",
        ["Erst IR-Kamera bzw. Ring-Con ausschalten (sie nutzen denselben Zusatzprozessor wie der NFC-Leser)."] =
            "먼저 IR 카메라 또는 Ring-Con을 끄세요(NFC 리더와 같은 보조 프로세서를 사용합니다).",
        ["Erst die IR-Kamera schließen (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "먼저 IR 카메라를 닫으세요(Ring-Con과 IR 카메라는 같은 보조 프로세서를 사용합니다).",
        ["Erst den Ring-Con ausschalten (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "먼저 Ring-Con을 끄세요(Ring-Con과 IR 카메라는 같은 보조 프로세서를 사용합니다).",
        ["amiibo zu früh entfernt"] = "amiibo를 너무 일찍 뗐습니다",
        ["MCU startet nicht"] = "보조 프로세서가 시작되지 않습니다",
        ["NFC-Modus nicht aktiv"] = "NFC 모드가 활성화되지 않았습니다",
        ["Kopplung fehlgeschlagen – Details im Protokoll."] = "페어링 실패 – 자세한 내용은 로그를 참조하세요.",

        // ---------- Kopplungsdaten (Switch-SD-Karte, anderer PC) ----------
        ["Kopplungsdaten"] = "페어링 데이터",
        ["Kopplungen übernehmen oder weitergeben"] = "페어링 가져오기 또는 공유",
        ["Kopplungsdaten von der Switch übernehmen"] = "Switch에서 페어링 데이터 가져오기",
        ["Von der Switch-SD-Karte (Bluepick_RCM/hekate) oder von einem anderen PC übernehmen, oder für einen anderen PC exportieren."] =
            "Switch의 SD 카드(Bluepick_RCM/hekate)나 다른 PC에서 가져오거나, 다른 PC용으로보냅니다.",
        ["Bei Switch-SD-Karte nachfragen"] = "Switch SD 카드가 있으면 확인",
        ["Steckt eine SD-Karte der Switch im PC (Kartenleser oder hekate „USB Tools“), bietet N-Connect die Übernahme an. Die Karte wird nur gelesen."] =
            "Switch의 SD 카드가 PC에 삽입되어 있으면(카드 리더 또는 hekate „USB Tools“), N-Connect가 가져오기를 제안합니다. 카드는 읽기만 합니다.",
        ["Switch-SD-Karte erkannt"] = "Switch SD 카드 감지됨",
        ["Kopplungsdaten der Controller gefunden – klicken, um sie anzusehen und zu übernehmen."] =
            "컨트롤러의 페어링 데이터를 찾았습니다 – 클릭하여 확인하고 가져옵니다.",
        ["Klicken, um Kopplungsdaten der Controller zu übernehmen."] = "클릭하여 컨트롤러의 페어링 데이터를 가져옵니다.",
        ["Controller-Kopplungen von der Switch-SD-Karte oder von einem anderen PC übernehmen – oder für einen anderen PC exportieren. Es werden nur Einstellungen von N-Connect geändert; Windows und der Bluetooth-Adapter bleiben unverändert."] =
            "Switch의 SD 카드나 다른 PC에서 컨트롤러 페어링을 가져오거나, 다른 PC용으로보냅니다. N-Connect의 설정만 변경되며 Windows와 Bluetooth 어댑터는 변경되지 않습니다.",
        ["Spieler-Reihenfolge – Spieler 1 ist für Windows, Steam und Spiele der erste Controller. Mit ‹ › umsortieren."] =
            "플레이어 순서 – 플레이어 1은 Windows, Steam 및 게임에서 첫 번째 컨트롤러입니다. ‹ ›로 순서를 변경합니다.",
        ["Von der Switch-SD-Karte"] = "Switch의 SD 카드에서",
        ["Mit Bluepick_RCM oder hekate erstellte Kopplungsdaten (switchroot/joycon_mac.ini)"] =
            "Bluepick_RCM 또는 hekate로 생성된 페어링 데이터(switchroot/joycon_mac.ini)",
        ["Einlesen …"] = "읽어오기 …",
        ["Von einem anderen PC"] = "다른 PC에서",
        ["Mit N-Connect exportierte Datei (*.ncpair)"] = "N-Connect로보낸 파일(*.ncpair)",
        ["Datei öffnen …"] = "파일 열기 …",
        ["Inhalt"] = "내용",
        ["Weitergeben und sichern"] = "공유 및 백업",
        ["Für einen anderen PC exportieren"] = "다른 PC용으로보내기",
        ["Bekannte Controller und Einstellungen je Controller, optional mit Passwort"] =
            "알려진 컨트롤러 및 컨트롤러별 설정(비밀번호는 선택 사항)",
        ["Sicherung wiederherstellen"] = "백업 복원",
        ["Vor jedem „Übernehmen“ wird automatisch eine Sicherung angelegt"] = "„적용“ 전에 자동으로 백업이 생성됩니다",
        ["Wiederherstellen …"] = "복원 …",
        ["Bluetooth-Adapter dieses PCs"] = "이 PC의 Bluetooth 어댑터",
        ["wird ermittelt …"] = "확인 중 …",
        ["nicht gefunden"] = "찾을 수 없음",
        ["Quelle wählen: Switch-SD-Karte (mit Bluepick_RCM oder hekate erstellte Kopplungsdaten) oder eine Datei von einem anderen PC."] =
            "소스 선택: Switch의 SD 카드(Bluepick_RCM 또는 hekate로 생성된 페어링 데이터) 또는 다른 PC의 파일.",
        ["Keine Switch-SD-Karte gefunden. SD-Karte in den Kartenleser stecken oder die Switch per hekate („USB Tools“ → „SD Card“) als Laufwerk verbinden.\n\nOrdner selbst auswählen?"] =
            "Switch SD 카드를 찾을 수 없습니다. SD 카드를 카드 리더에 삽입하거나 hekate(„USB Tools“ → „SD Card“)로 Switch를 드라이브로 연결하세요.\n\n폴더를 직접 선택하시겠습니까?",
        ["Stammordner der Switch-SD-Karte wählen"] = "Switch SD 카드의 루트 폴더 선택",
        ["Switch-SD-Karte:"] = "Switch SD 카드:",
        ["Auf der Karte liegen keine Kopplungsdaten (switchroot/joycon_mac.ini)."] = "카드에 페어링 데이터(switchroot/joycon_mac.ini)가 없습니다.",
        ["So erstellst du sie: Joy-Con an die Switch stecken, Bluepick_RCM starten und „Dump Joy-Con BT pairing → SD“ (oder FULL AUTO) wählen. Alternativ in hekate: Nyx → Konsole → „Dump Joy-Con BT“."] =
            "생성 방법: Joy-Con을 Switch에 연결하고 Bluepick_RCM을 실행한 다음 „Dump Joy-Con BT pairing → SD“(또는 FULL AUTO)를 선택합니다. 또는 hekate에서: Nyx → Console → „Dump Joy-Con BT“.",
        ["Gefunden wurde eine Bluepick-Sicherung des Bluetooth-Speichers (8000000000000050.bin). Sie ist ein Switch-Speicherabbild und kann hier nicht ausgewertet werden."] =
            "Bluepick의 Bluetooth 메모리 백업(8000000000000050.bin)을 찾았습니다. 이는 Switch의 메모리 이미지로 여기서 분석할 수 없습니다.",
        ["Bluetooth-Adresse der Switch:"] = "Switch의 Bluetooth 주소:",
        ["Gefundene Controller:"] = "찾은 컨트롤러:",
        ["mit der Switch gekoppelt"] = "Switch와 페어링됨",
        ["zuletzt mit einem anderen Gerät gekoppelt (nicht der Switch)"] = "마지막으로 다른 기기와 페어링됨(Switch 아님)",
        ["Joy-Con (L)"] = "Joy-Con(왼쪽)",
        ["Joy-Con (R)"] = "Joy-Con(오른쪽)",
        ["HORI-Controller (links)"] = "HORI 컨트롤러(왼쪽)",
        ["HORI-Controller (rechts)"] = "HORI 컨트롤러(오른쪽)",
        ["Hinweis: Pro Controller stehen nur im Bluetooth-Speicher der Switch (8000000000000050.bin); dieses Speicherabbild kann N-Connect nicht auswerten."] =
            "참고: Pro Controller는 Switch의 Bluetooth 메모리(8000000000000050.bin)에만 기록됩니다. N-Connect는 이 메모리 이미지를 분석할 수 없습니다.",
        ["Was diese Daten können – und was nicht:"] = "이 데이터로 가능한 것 – 불가능한 것:",
        ["Die Daten zeigen, welche Controller mit deiner Switch gekoppelt sind und an welche Bluetooth-Adresse sie gebunden sind."] =
            "데이터는 어떤 컨트롤러가 Switch와 페어링되어 있는지, 어떤 Bluetooth 주소에 연결되어 있는지 보여줍니다.",
        ["Ein Switch-1-Controller verbindet sich auf Tastendruck nur mit dem Gerät, dessen Adresse er gespeichert hat – hier mit der Switch. Der Bluetooth-Adapter des PCs hat eine andere Adresse, deshalb kann Windows diese Kopplung nicht einfach weiterverwenden."] =
            "Switch 1 컨트롤러는 버튼 입력 시 저장된 주소의 기기(여기서는 Switch)에만 연결됩니다. PC의 Bluetooth 어댑터는 다른 주소를 가지므로 Windows가 이 페어링을 그대로 재사용할 수 없습니다.",
        ["Die Adresse des PC-Adapters zu ändern, unterstützt N-Connect bewusst nicht (herstellerabhängig, riskant und nicht vorgesehen)."] =
            "N-Connect는 PC 어댑터의 주소 변경을 의도적으로 지원하지 않습니다(제조사마다 다르고 위험하며 권장되지 않음).",
        ["Windows bietet keinen offiziellen Weg, fremde Kopplungsschlüssel einzutragen: Sie liegen in einem Teil der Registrierung, auf den nur das System zugreifen darf. N-Connect ändert dort nichts."] =
            "Windows는 외부 페어링 키를 등록하는 공식적인 방법을 제공하지 않습니다. 레지스트리의 시스템 전용 영역에 저장되므로 N-Connect는 이를 변경하지 않습니다.",
        ["So klappt der Wechsel am einfachsten: am PC den Controller einmal per SYNC-Taste in den Windows-Bluetooth-Einstellungen koppeln. Zurück an der Switch die Joy-Con an die Konsole stecken bzw. den Pro Controller per USB-Kabel anschließen – dann sind sie ohne Menü wieder mit der Switch gekoppelt."] =
            "가장 쉬운 전환 방법: PC에서 Windows Bluetooth 설정으로 SYNC 버튼을 사용해 한 번 페어링합니다. Switch로 돌아갈 때 Joy-Con을 본체에 끼우거나 Pro Controller를 USB 케이블로 연결하면 – 메뉴 없이 다시 Switch와 페어링됩니다.",
        ["„Übernehmen“ merkt sich diese Controller in N-Connect (Liste bekannter Controller, Zuordnung zur Switch). Kopplungsschlüssel werden nicht gespeichert."] =
            "„적용“은 이 컨트롤러들을 N-Connect에 기억합니다(알려진 컨트롤러 목록, Switch와의 연결). 페어링 키는 저장되지 않습니다.",
        ["N-Connect-Kopplungsdaten"] = "N-Connect 페어링 데이터",
        ["Kopplungsdaten von einem anderen PC öffnen"] = "다른 PC의 페어링 데이터 열기",
        ["Die Datei ist zu groß."] = "파일이 너무 큽니다.",
        ["Keine Kopplungsdaten-Datei."] = "페어링 데이터 파일이 아닙니다.",
        ["Die Datei stammt von einer neueren N-Connect-Version."] = "파일이 더 새로운 버전의 N-Connect에서 생성되었습니다.",
        ["Die Datei ist mit einem Passwort geschützt."] = "파일이 비밀번호로 보호되어 있습니다.",
        ["Falsches Passwort oder die Datei wurde verändert."] = "비밀번호가 틀렸거나 파일이 변경되었습니다.",
        ["Die Datei ist beschädigt."] = "파일이 손상되었습니다.",
        ["Datei von:"] = "파일 출처:",
        ["Bluetooth-Adapter dort:"] = "그쪽 Bluetooth 어댑터:",
        ["Bluetooth-Adapter hier:"] = "이쪽 Bluetooth 어댑터:",
        ["gekoppelt mit der Switch"] = "Switch와 페어링됨",
        ["gekoppelt mit dem anderen PC"] = "다른 PC와 페어링됨",
        ["Weitere Einstellungen je Controller:"] = "컨트롤러별 추가 설정:",
        ["Was du erwarten kannst:"] = "예상 결과:",
        ["Gleiche Adapter-Adresse (z. B. derselbe USB-Bluetooth-Stick umgesteckt): Switch-2-Controller verbinden sich hier auf Tastendruck wie am anderen PC."] =
            "동일한 어댑터 주소(예: 같은 USB Bluetooth 동글을 옮겨 꽂음): Switch 2 컨트롤러는 여기서도 다른 PC처럼 버튼 하나로 연결됩니다.",
        ["Switch-1-Controller (Pro Controller, Joy-Con) brauchen zusätzlich die Kopplung in Windows. Die kann N-Connect nicht übertragen – einmal per SYNC-Taste koppeln."] =
            "Switch 1 컨트롤러(Pro Controller, Joy-Con)는 추가로 Windows에서의 페어링이 필요합니다. N-Connect는 이를 전송할 수 없습니다 – SYNC 버튼으로 한 번 페어링하세요.",
        ["Anderer Bluetooth-Adapter: Controller verbinden sich auf Tastendruck nur mit dem Gerät, mit dem sie zuletzt gekoppelt wurden. Hier einmal SYNC drücken – danach verbinden sie sich mit diesem PC (am anderen PC dann wieder per SYNC)."] =
            "다른 Bluetooth 어댑터의 경우: 컨트롤러는 버튼 입력 시 마지막으로 페어링된 기기에만 연결됩니다. 여기서 한 번 SYNC를 누르세요 – 이후 이 PC에 연결됩니다(다른 PC에서는 다시 SYNC).",
        ["Tipp: Wer denselben USB-Bluetooth-Stick zwischen den PCs umsteckt, nimmt die Adresse mit – Switch-2-Controller verbinden sich dann an beiden PCs ohne SYNC."] =
            "팁: 같은 USB Bluetooth 동글을 PC 간에 옮겨 꽂으면 주소가 함께 이동합니다 – Switch 2 컨트롤러는 양쪽 PC에서 SYNC 없이 연결됩니다.",
        ["Übernommen werden die Einstellungen je Controller (Joy-Con einzeln/hochkant, Gyro-Kalibrierung) und die Liste bekannter Controller."] =
            "가져오는 항목은 컨트롤러별 설정(Joy-Con 단독/세로, 자이로 보정)과 알려진 컨트롤러 목록입니다.",
        ["Die Datei enthält Kopplungsschlüssel. Windows bietet keinen offiziellen Weg, sie einzutragen – N-Connect übernimmt sie deshalb nicht."] =
            "파일에 페어링 키가 포함되어 있습니다. Windows는 이를 등록하는 공식적인 방법을 제공하지 않으므로 N-Connect는 이를 가져오지 않습니다.",
        ["„Übernehmen“ ergänzt die Controller-Listen und Einstellungen von N-Connect (nichts wird gelöscht). Vorher wird eine Sicherung angelegt."] =
            "„적용“은 N-Connect의 컨트롤러 목록과 설정을 보완합니다(삭제되는 것은 없음). 사전에 백업이 생성됩니다.",
        ["Kopplungsdaten in N-Connect übernehmen? Vorher wird eine Sicherung der Einstellungen angelegt."] =
            "페어링 데이터를 N-Connect에 가져오시겠습니까? 사전에 설정 백업이 생성됩니다.",
        ["Nichts zu ändern – diese Daten sind schon übernommen."] = "변경할 내용이 없습니다 – 이 데이터는 이미 가져왔습니다.",
        ["Übernommen. Die Sicherung lässt sich hier über „Sicherung wiederherstellen“ zurückholen."] =
            "완료되었습니다. 백업은 여기서 „백업 복원“으로 되돌릴 수 있습니다.",
        ["Sicherung der Einstellungen"] = "설정 백업",
        ["Die Sicherung ist beschädigt und wurde nicht übernommen."] = "백업이 손상되어 적용되지 않았습니다.",
        ["Alle Einstellungen durch diese Sicherung ersetzen?"] = "모든 설정을 이 백업으로 교체하시겠습니까?",
        ["Sicherung wiederhergestellt."] = "백업이 복원되었습니다.",
        ["Kopplungsdaten für einen anderen PC speichern"] = "다른 PC용으로 페어링 데이터 저장",
        ["Gespeichert. Die Datei am anderen PC in N-Connect unter „Joy-Con & Wii“ → „Kopplungsdaten“ → „Von einem anderen PC“ öffnen."] =
            "저장되었습니다. 다른 PC의 N-Connect에서 „Joy-Con 및 Wii“ → „페어링 데이터“ → „다른 PC에서“로 파일을 여세요.",
        ["Kopplungsdaten exportieren"] = "페어링 데이터보내기",
        ["Passwort eingeben"] = "비밀번호 입력",
        ["Passwort (optional). Ohne Passwort steht der Inhalt lesbar in der Datei. Mit Kopplungsschlüsseln ist ein Passwort Pflicht."] =
            "비밀번호(선택 사항). 비밀번호가 없으면 파일 내용이 일반 텍스트로 저장됩니다. 페어링 키가 포함된 경우 비밀번호는 필수입니다.",
        ["Passwort"] = "비밀번호",
        ["Passwort wiederholen"] = "비밀번호 확인",
        ["Kopplungsschlüssel der Switch-Controller mitnehmen"] = "Switch 컨트롤러의 페어링 키 포함",
        ["Kopplungsschlüssel mitnehmen (erst Switch-SD-Karte einlesen)"] = "페어링 키 포함(먼저 Switch SD 카드를 읽으세요)",
        ["Die Passwörter stimmen nicht überein."] = "비밀번호가 일치하지 않습니다.",
        ["Mit Schlüsseln: Passwort mit mindestens 8 Zeichen."] = "키 포함 시: 비밀번호는 8자 이상이어야 합니다.",
        ["Mindestens 8 Zeichen."] = "최소 8자 이상.",
        ["Ohne Passwort."] = "비밀번호 없음.",
    };

    /// <summary>Meldungen mit Platzhaltern (Koreanisch).</summary>
    private static readonly (Regex Pattern, Func<Match, string> Replace)[] PatternsKo =
    [
        (Re(@"^Allgemeiner Wert \((?<v>.+)\) – Regler verschieben für einen eigenen$"), m => $"전체 값({m.Groups["v"]}) – 슬라이더를 움직여 개별 값 설정"),
        (Re(@"^Eigener Wert · allgemein: (?<v>.+)$"), m => $"개별 값 · 전체: {m.Groups["v"]}"),
        (Re(@"^Spieler (?<n>\d+)  ·  (?<k>.+?)(?<rest>(  ·  .*)?)$"), m => $"플레이어 {m.Groups["n"]}  ·  {N(m, "k")}{T(m.Groups["rest"].Value)}"),
        (Re(@"^  ·  Gyro-Maus(?<r>.*)$"), m => "  ·  자이로 마우스" + T(m.Groups["r"].Value)),
        (Re(@"^  ·  Gyro-Stick$"), _ => "  ·  자이로 스틱"),
        (Re(@"^Spieler (?<n>\d+) · (?<k>.+?) (?<b>\d+ %.*)?$"), m => $"플레이어 {m.Groups["n"]} · {N(m, "k")} {m.Groups["b"]}"),
        (Re(@"^(?<k>.+) verbunden \(Spieler (?<n>\d+)\)$"), m => $"{N(m, "k")} 연결됨(플레이어 {m.Groups["n"]})"),
        (Re(@"^Spieler (?<n>\d+) – tauschen mit (?<k>.+)$"), m => $"플레이어 {m.Groups["n"]} – {N(m, "k")}와 교체"),
        (Re(@"^Spieler (?<n>\d+) – frei$"), m => $"플레이어 {m.Groups["n"]} – 비어 있음"),
        (Re(@"^Spieler (?<n>\d+)$"), m => $"플레이어 {m.Groups["n"]}"),
        (Re(@"^Xbox 360 · Platz (?<n>\d+)$"), m => $"Xbox 360 · 슬롯 {m.Groups["n"]}"),
        (Re(@"^noch (?<n>\d+) s$"), m => $"남은 시간 {m.Groups["n"]}초"),
        (Re(@"^Fertig – (?<n>\d+) Controller verbunden$"), m => $"완료 – 컨트롤러 {m.Groups["n"]}대 연결됨"),
        (Re(@"^✓ (?<k>.+) verbunden – Spieler (?<n>\d+)$"), m => $"✓ {N(m, "k")} 연결됨 – 플레이어 {m.Groups["n"]}"),
        (Re(@"^Spieler (?<n>\d+)  ·  (?<v>.+)$"), m => $"플레이어 {m.Groups["n"]}  ·  {m.Groups["v"]}"),
        (Re(@"^Gekoppelt: (?<k>.+) – verbindet gleich …$"), m => $"페어링됨: {m.Groups["k"]} – 연결 중 …"),
        (Re(@"^Ins Spiel wechseln … (?<n>\d+)$"), m => $"게임으로 전환 … {m.Groups["n"]}"),
        (Re(@"^(?<k>.+) ist jetzt Spieler (?<n>\d+)$"), m => $"{N(m, "k")}이(가) 플레이어 {m.Groups["n"]}이(가) 되었습니다"),
        (Re(@"^Spieler (?<a>\d+) und (?<b>\d+) getauscht$"), m => $"플레이어 {m.Groups["a"]}과(와) {m.Groups["b"]}을(를) 교체했습니다"),
        (Re(@"^Name für (?<k>.+) \(leer = Standardname\):$"), m => $"{N(m, "k")}의 이름(비워두면 기본 이름):"),
        (Re(@"^(?<k>.+) \(Joy-Con-Paar\)$"), m => $"{m.Groups["k"]}(Joy-Con 페어)"),
        (Re(@"^Joy-Con zusammengefasst \(Spieler (?<n>\d+)\)$"), m => $"Joy-Con 결합됨(플레이어 {m.Groups["n"]})"),
        (Re(@"^Joy-Con getrennt – (?<k>.+) ist jetzt Spieler (?<n>\d+)$"), m => $"Joy-Con 분리됨 – {N(m, "k")}이(가) 플레이어 {m.Groups["n"]}이(가) 되었습니다"),
        (Re(@"^Spieler (?<n>\d+): Akku (?<k>.+) fast leer \((?<p>\d+) %\) – bitte aufladen$"),
            m => $"플레이어 {m.Groups["n"]}: {N(m, "k")} 배터리 부족({m.Groups["p"]} %) – 충전하세요"),
        (Re(@"^Spieler (?<n>\d+): nach (?<m>\d+) min ohne Eingabe getrennt$"),
            m => $"플레이어 {m.Groups["n"]}: {m.Groups["m"]}분간 입력이 없어 연결 해제됨"),
        (Re(@"^Profil „(?<p>.+)“ aktiv$"), m => $"프로필 „{ProfileName(m.Groups["p"].Value)}“ 활성화됨"),
        (Re(@"^Profil: (?<p>.+)$"), m => $"프로필: {ProfileName(m.Groups["p"].Value)}"),
        (Re(@"^Profil „(?<p>.+)“ löschen\?$"), m => $"프로필 „{m.Groups["p"]}“을(를) 삭제하시겠습니까?"),
        (Re(@"^Profil „(?<p>.+)“ importiert(?<r>.*)$"), m => $"프로필 „{m.Groups["p"]}“ 가져옴" + m.Groups["r"].Value.Replace("aktiv bei:", "활성 프로그램:")),
        (Re(@"^⬇ Neue Version (?<v>.+) herunterladen …$"), m => $"⬇ 새 버전 {m.Groups["v"]} 다운로드 …"),
        (Re(@"^Version (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Herunterladen\.$"),
            m => $"버전 {m.Groups["v"]}이(가) 출시되었습니다(설치됨: {m.Groups["i"]}). 클릭하여 다운로드."),
        (Re(@"^Version (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Installieren\.$"),
            m => $"버전 {m.Groups["v"]}이(가) 출시되었습니다(설치됨: {m.Groups["i"]}). 클릭하여 설치."),
        (Re(@"^⬇ Auf Version (?<v>.+) aktualisieren …$"), m => $"⬇ 버전 {m.Groups["v"]}(으)로 업데이트 …"),
        (Re(@"^Lade Version (?<v>.+) herunter …$"), m => $"버전 {m.Groups["v"]} 다운로드 중 …"),
        (Re(@"^HidHide (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Installieren\.$"),
            m => $"HidHide {m.Groups["v"]}이(가) 출시되었습니다(설치됨: {m.Groups["i"]}). 클릭하여 설치."),
        (Re(@"^Lade HidHide (?<v>.+) herunter …$"), m => $"HidHide {m.Groups["v"]} 다운로드 중 …"),
        (Re(@"^(?<t>.+) · (?<r>\d+) Berichte/s$"), m => $"{T(m.Groups["t"].Value)} · {m.Groups["r"]} 리포트/초"),
        (Re(@"^(?<p>\d+ %)(?<v>  \(.*\))?  ⚡ lädt$"), m => $"{m.Groups["p"]}{m.Groups["v"]}  ⚡ 충전 중"),
        (Re(@"^Speichern fehlgeschlagen: (?<e>.*)$"), m => $"저장 실패: {m.Groups["e"]}"),
        (Re(@"^Lesen fehlgeschlagen: (?<e>.*)$"), m => $"읽기 실패: {m.Groups["e"]}"),
        (Re(@"^amiibo konnte nicht gelesen werden: (?<e>.*)$"), m => $"amiibo를 읽을 수 없습니다: {T(m.Groups["e"].Value)}"),
        (Re(@"^Gekoppelt: (?<k>.+)$"), m => $"페어링됨: {m.Groups["k"]}"),
        (Re(@"^Gefunden: (?<k>.+) – kopple …$"), m => $"발견: {m.Groups["k"]} – 페어링 중 …"),
        (Re(@"^amiibo erkannt \((?<u>.+)\) – lese …$"), m => $"amiibo 감지됨({m.Groups["u"]}) – 읽는 중 …"),
        (Re(@"^(?<n>\d+) Minuten$"), m => $"{m.Groups["n"]}분"),
        (Re(@"^✓ (?<n>\d+) Schritte, Dauer (?<ms>\d+) ms$"), m => $"✓ {m.Groups["n"]}단계, 총 {m.Groups["ms"]}ms"),
        (Re(@"^Controller-Taste „(?<b>.+)“:\nJetzt die gewünschte Taste oder Tastenkombination drücken\.$"),
            m => $"컨트롤러 버튼 „{T(m.Groups["b"].Value)}“:\n이제 원하는 키 또는 키 조합을 누르세요."),
        (Re(@"^Solange „(?<b>.+)“ gehalten wird, wird diese Taste schnell wiederholt gedrückt\n\(Geschwindigkeit unter 5\. „Turbo“\):$"),
            m => $"„{T(m.Groups["b"].Value)}“을(를) 누르는 동안 이 버튼이 빠르게 반복됩니다\n(속도는 5. „터보“에서 설정):"),
        (Re(@"^Ring-Con: (?<e>.*)$"), m => $"Ring-Con: {T(m.Groups["e"].Value)}"),
        (Re(@"^⌨  Taste: (?<k>.+)$"), m => $"⌨  키: {m.Groups["k"]}"),
        (Re(@"^🔁  Turbo: Taste (?<k>.+)$"), m => $"🔁  터보: 키 {m.Groups["k"]}"),
        (Re(@"^🔁  Turbo: (?<k>.+)$"), m => $"🔁  터보: {T(m.Groups["k"].Value)}"),
        (Re(@"^⏯  Makro: (?<k>.+)$"), m => $"⏯  매크로: {m.Groups["k"]}"),
        (Re(@"^Tastatur: (?<k>.+)$"), m => $"키보드: {m.Groups["k"]}"),
        (Re(@"^Gamepad: (?<k>.+)$"), m => $"게임패드: {m.Groups["k"]}"),
        (Re(@"^(?<k>.+)  \(verbunden\)$"), m => $"{N(m, "k")}(연결됨)"),
        (Re(@"^Bluetooth nicht verfügbar: (?<e>.*)$"), m => $"Bluetooth 사용 불가: {m.Groups["e"]}"),
        (Re(@"^(?<k>.+) per USB ist von einem anderen Programm belegt \(z\. B\. Steam\)\.$"),
            m => $"{N(m, "k")}의 USB가 다른 프로그램(예: Steam)에서 사용 중입니다."),
        (Re(@"^Schon (?<n>\d+) Controller verbunden – (?<k>.+) wird nicht verwendet\.$"),
            m => $"이미 컨트롤러 {m.Groups["n"]}대가 연결되어 있습니다 – {N(m, "k")}은(는) 사용되지 않습니다."),
        (Re(@"^(?<k>.+): schwache Bluetooth-Verbindung \((?<r>\d+) statt 33–60 Berichte/s\)\.$"),
            m => $"{N(m, "k")}: Bluetooth 연결 불안정(33–60 대신 {m.Groups["r"]} 리포트/초)."),
        (Re(@"^(?<k>.+) getrennt$"), m => $"{N(m, "k")} 연결 해제됨"),
    ];
}
