using System.Text.RegularExpressions;

namespace Switch2Pro.Bridge;

/// <summary>Feste Texte Deutsch → Japanisch. Schlüssel bleiben die deutschen Originaltexte.</summary>
internal static partial class Tr
{
    private static readonly Dictionary<string, string> TextsJa = new(StringComparer.Ordinal)
    {
        // ---------- Fenster, Reiter, Abschnitte ----------
        ["Controller"] = "コントローラー",
        // ---------- Status-Kopfzeile, Ansicht ----------
        ["bereit"] = "準備完了",
        ["nicht verfügbar"] = "利用不可",
        ["Niedrigster Akku"] = "最低バッテリー",
        ["lädt"] = "充電中",
        ["gemischt"] = "混在",
        ["Original-Controller"] = "元のコントローラー",
        ["versteckt"] = "非表示",
        ["sichtbar"] = "表示",
        ["HidHide fehlt"] = "HidHide がありません",
        ["Groß"] = "大",
        ["Kompakt"] = "コンパクト",
        ["Einstellungen (optional)"] = "設定（任意）",
        ["1. Windows und Spiele sehen den Controller als …"] = "1. Windows とゲームからはこのように見えます …",
        ["2. Tasten A/B/X/Y"] = "2. ボタン A/B/X/Y",
        ["3. Vibration, Sticks, Verbinden, Gyro-Maus"] = "3. 振動、スティック、接続、ジャイロマウス",
        ["4. Joy-Con"] = "4. Joy-Con",
        ["4. Joy-Con und Wii"] = "4. Joy-Con と Wii",
        ["Wii-Fernbedienung: Zeiger (Sensorleiste) steuert die Maus"] = "Wiiリモコン：ポインター（センサーバー）でマウスを操作",
        ["Zeiger"] = "ポインター",
        ["kein Zeiger – Sensorleiste nicht im Blick"] = "ポインターなし – センサーバーが範囲外です",
        ["5. Zielen, Sticks, Trigger, Turbo"] = "5. エイム、スティック、トリガー、ターボ",
        ["6. Tastenbelegung und Profile  (Taste → Gamepad, Tastatur, Maus, Gyro-Maus, Shift-Ebene)"] =
            "6. ボタン割り当てとプロファイル（ボタン → ゲームパッド、キーボード、マウス、ジャイロマウス、Shiftレイヤー）",
        ["Xbox-360-Controller  (empfohlen – läuft mit fast allen Spielen)"] = "Xbox 360 コントローラー（推奨 – ほぼすべてのゲームで動作）",
        ["PlayStation DualShock 4  (mit Bewegungssteuerung/Gyro – für Steam && Emulatoren)"] =
            "PlayStation DualShock 4（モーション操作/ジャイロ対応 – Steam とエミュレーター向け）",
        ["Xbox-Belegung  (nach Position: untere Taste = A)"] = "Xbox 配置（位置で決定：下のボタン = A）",
        ["Nintendo-Belegung  (nach Beschriftung: A bleibt A)"] = "Nintendo 配置（表示どおり：A は A のまま）",
        ["Vibration"] = "振動",
        ["Stärke:"] = "強さ：",
        ["Stick-Totzone (alle Controller):"] = "スティックのデッドゾーン（全コントローラー）：",
        ["Beim Verbinden kurz vibrieren"] = "接続時に短く振動する",
        ["Meldung bei Verbinden"] = "接続時の通知",
        ["Wer meldet, wenn ein Controller verbunden oder getrennt wird."] = "コントローラーの接続・切断時に通知するものを選びます。",
        ["„N-Connect“ zeigt den echten Controller-Namen und schaltet die Gerätemeldungen von Windows ab."] = "「N-Connect」は実際のコントローラー名を表示し、Windowsのデバイス通知をオフにします。",
        ["N-Connect (empfohlen)"] = "N-Connect（推奨）",
        ["N-Connect und Windows"] = "N-Connect と Windows",
        ["Keine"] = "なし",
        ["Gekoppelte Controller per Tastendruck verbinden (ohne SYNC)"] = "ペアリング済みコントローラーをボタン一つで接続（SYNC 不要）",
        ["Automatisch mit Windows starten"] = "Windows と一緒に自動で起動",
        ["Gyro für Emulatoren bereitstellen (Cemuhook/DSU, Port 26760 – wirkt nach Neustart)"] =
            "エミュレーターにジャイロを提供（Cemuhook/DSU、ポート 26760 – 再起動後に有効）",
        ["Beim Start nach neuer Version suchen (GitHub)"] = "起動時に新しいバージョンを確認（GitHub）",
        ["Ohne Eingabe automatisch trennen nach:"] = "操作がない場合に自動で切断：",
        ["Gyro-Maus-Geschwindigkeit:"] = "ジャイロマウスの速度：",
        ["Sprache / Language:"] = "言語 / Language：",
        ["Automatisch (wie Windows)"] = "自動（Windows に合わせる）",
        ["nie"] = "しない",
        ["Zwei Joy-Con automatisch zu einem Controller zusammenfassen"] = "2 つの Joy-Con を自動で 1 つのコントローラーにまとめる",
        ["Gyro beim Paar vom:"] = "ペアのジャイロの取得元：",
        ["rechter Joy-Con (wie Switch)"] = "右 Joy-Con（Switch と同じ）",
        ["linker Joy-Con"] = "左 Joy-Con",
        ["Joy-Con 2 als Maus, wenn er auf dem Tisch liegt"] = "テーブルに置いた Joy-Con 2 をマウスとして使う",
        ["Mausgeschwindigkeit:"] = "マウス速度：",
        ["Maus: links/rechts umkehren"] = "マウス：左右を反転",
        ["Maus: hoch/runter umkehren"] = "マウス：上下を反転",
        ["Wie an der Switch: SL + SR eine Sekunde halten löst einen Joy-Con aus dem Paar. L am linken und R am rechten einzelnen Joy-Con gleichzeitig drücken verbindet sie wieder zum Paar. Die Wahl wird je Joy-Con gemerkt (auch nach dem nächsten Verbinden). Im Mausmodus: R/L = Linksklick, ZR/ZL = Rechtsklick, Stick drücken = Mittelklick, Stick hoch/runter = Scrollen."] =
            "Switch と同様：SL + SR を 1 秒押すと Joy-Con がペアから外れます。左 Joy-Con の L と右 Joy-Con の R を同時に押すと再度ペアになります。選択は Joy-Con ごとに記憶されます（次回接続時も）。マウスモード：R/L = 左クリック、ZR/ZL = 右クリック、スティック押し込み = 中クリック、スティック上下 = スクロール。",
        ["Gyro als rechter Stick:"] = "ジャイロを右スティックに：",
        ["aus (nur per Taste „Gyro-Stick“)"] = "オフ（「ジャイロスティック」ボタンでのみ）",
        ["immer"] = "常に",
        ["beim Zielen (solange ZL / linker Trigger gedrückt)"] = "エイム時（ZL / 左トリガー押下中）",
        ["hoch/runter umkehren"] = "上下を反転",
        ["Empfindlichkeit:"] = "感度：",
        ["Mindestausschlag:"] = "最小入力：",
        ["Stick-Kennlinie:"] = "スティック特性：",
        ["Turbo (pro Sekunde):"] = "ターボ（毎秒）：",
        ["Analoge Trigger (GameCube) – Totzone:"] = "アナログトリガー（GameCube）– デッドゾーン：",
        ["voll gedrückt ab:"] = "最大まで押し込み：",
        ["Profil:"] = "プロファイル：",
        ["Neu …"] = "新規 …",
        ["Umbenennen …"] = "名前を変更 …",
        ["Löschen"] = "削除",
        ["Exportieren …"] = "エクスポート …",
        ["Importieren …"] = "インポート …",
        ["Aktiv bei Programm:"] = "プログラムで有効：",
        ["Programm wählen …"] = "プログラムを選択 …",
        ["Standard"] = "標準",
        ["Standard gilt immer, wenn kein anderes Profil passt"] = "他のプロファイルが合わない場合は標準が適用されます",
        ["z. B. Cemu.exe, Ryujinx.exe"] = "例：Cemu.exe、Ryujinx.exe",
        ["Ein eigenes Profil wird automatisch aktiv, solange eines seiner Programme im Vordergrund ist (sonst gilt „Standard“). Im Infobereich-Menü lässt sich ein Profil auch fest wählen."] =
            "専用プロファイルは、そのプログラムのいずれかが前面にある間、自動で有効になります（それ以外は「標準」）。通知領域メニューからプロファイルを固定することもできます。",
        ["Controller:"] = "コントローラー：",
        ["Eigene Stick-Totzone für diesen Controller:"] = "このコントローラー専用のスティックデッドゾーン：",
        ["Normale Belegung"] = "通常の割り当て",
        ["Shift-Ebene (gilt, solange eine Taste mit „Shift-Ebene“ gehalten wird)"] = "Shift レイヤー（「Shift レイヤー」のボタン押下中有効）",
        ["Alles auf Standard"] = "すべてリセット",
        ["Schließen"] = "閉じる",
        ["wie normale Belegung"] = "通常の割り当てと同じ",

        // ---------- Belegungsziele und Vorlagen ----------
        ["— keine Funktion —"] = "— 機能なし —",
        ["A (Xbox) / Kreuz (PS)"] = "A (Xbox) / × (PS)",
        ["B (Xbox) / Kreis (PS)"] = "B (Xbox) / ○ (PS)",
        ["X (Xbox) / Viereck (PS)"] = "X (Xbox) / □ (PS)",
        ["Y (Xbox) / Dreieck (PS)"] = "Y (Xbox) / △ (PS)",
        ["Ansicht (Back) / Share"] = "表示 (Back) / Share",
        ["Menü (Start) / Options"] = "メニュー (Start) / Options",
        ["Xbox-Taste / PS-Taste"] = "Xbox ボタン / PS ボタン",
        ["Linker Stick-Klick"] = "左スティック押し込み",
        ["Rechter Stick-Klick"] = "右スティック押し込み",
        ["Steuerkreuz hoch"] = "十字キー上",
        ["Steuerkreuz runter"] = "十字キー下",
        ["Steuerkreuz links"] = "十字キー左",
        ["Steuerkreuz rechts"] = "十字キー右",
        ["Touchpad-Klick (nur DualShock 4)"] = "タッチパッド押し込み（DualShock 4 のみ）",
        ["🖱  Maus: Linksklick"] = "🖱  マウス：左クリック",
        ["🖱  Maus: Rechtsklick"] = "🖱  マウス：右クリック",
        ["🖱  Maus: Mittelklick"] = "🖱  マウス：中クリック",
        ["🎯  Gyro-Maus (solange gehalten)"] = "🎯  ジャイロマウス（押下中）",
        ["🎯  Gyro-Maus ein/aus"] = "🎯  ジャイロマウス オン/オフ",
        ["🎯  Gyro als rechter Stick (solange gehalten)"] = "🎯  ジャイロを右スティックに（押下中）",
        ["🎯  Gyro als rechter Stick ein/aus"] = "🎯  ジャイロを右スティックに オン/オフ",
        ["⇧  Shift-Ebene (solange gehalten)"] = "⇧  Shift レイヤー（押下中）",
        ["🔁  Turbo / Dauerfeuer …"] = "🔁  ターボ / 連射 …",
        ["⏯  Makro (Tastenfolge) …"] = "⏯  マクロ（ボタン連続操作）…",
        ["📷  Bildschirmfoto speichern (Win+Druck)"] = "📷  スクリーンショットを保存（Win+Print）",
        ["📷  Bildschirmausschnitt (Win+Umschalt+S)"] = "📷  範囲キャプチャ（Win+Shift+S）",
        ["⏺  Letzte 30 Sekunden aufnehmen (Win+Alt+G)"] = "⏺  直近 30 秒を録画（Win+Alt+G）",
        ["⏺  Aufnahme starten/stoppen (Win+Alt+R)"] = "⏺  録画の開始/停止（Win+Alt+R）",
        ["🎮  Xbox Game Bar (Win+G)"] = "🎮  Xbox Game Bar（Win+G）",
        ["🔊  Lauter"] = "🔊  音量を上げる",
        ["🔉  Leiser"] = "🔉  音量を下げる",
        ["⏯  Wiedergabe/Pause"] = "⏯  再生/一時停止",
        ["⌨  Andere Taste / Tastenkombination aufnehmen …"] = "⌨  別のキー / キーの組み合わせを記録 …",

        // ---------- Tastennamen ----------
        ["+ (Plus)"] = "+（プラス）",
        ["− (Minus)"] = "−（マイナス）",
        ["Aufnahme"] = "キャプチャ",
        ["GL (Rücktaste links)"] = "GL（背面ボタン左）",
        ["GR (Rücktaste rechts)"] = "GR（背面ボタン右）",
        ["Linker Stick drücken"] = "左スティック押し込み",
        ["Rechter Stick drücken"] = "右スティック押し込み",
        ["Stick drücken"] = "スティック押し込み",
        ["A (groß, unten)"] = "A（大、下）",
        ["B (links)"] = "B（左）",
        ["X (rechts)"] = "X（右）",
        ["Y (oben)"] = "Y（上）",
        ["L (ganz durchgedrückt)"] = "L（完全に押し込み）",
        ["R (ganz durchgedrückt)"] = "R（完全に押し込み）",
        ["untere Taste (quer)"] = "下ボタン（横向き）",
        ["rechte Taste (quer)"] = "右ボタン（横向き）",
        ["linke Taste (quer)"] = "左ボタン（横向き）",
        ["obere Taste (quer)"] = "上ボタン（横向き）",
        ["1 (quer) / Classic Y"] = "1（横向き）/ Classic Y",
        ["2 (quer) / Classic B"] = "2（横向き）/ Classic B",
        ["B (Abzug) / Classic ZR"] = "B（引き金）/ Classic ZR",
        ["Kreuz (unten)"] = "×（下）",
        ["Kreis (rechts)"] = "○（右）",
        ["Viereck (links)"] = "□（左）",
        ["Dreieck (oben)"] = "△（上）",
        ["PS-Taste"] = "PS ボタン",
        ["Touchpad-Klick"] = "タッチパッド押し込み",
        ["Mikro stumm"] = "マイクミュート",
        ["Fn links (Edge)"] = "Fn 左（Edge）",
        ["Rücktaste links (Edge)"] = "背面ボタン左（Edge）",
        ["Rücktaste rechts (Edge)"] = "背面ボタン右（Edge）",
        ["L3 (Stick drücken)"] = "L3（スティック押し込み）",
        ["R3 (Stick drücken)"] = "R3（スティック押し込み）",
        ["Ansicht/Zurück"] = "表示/戻る",
        ["Menü/Start"] = "メニュー/スタート",
        ["Xbox-Taste"] = "Xbox ボタン",

        // ---------- Controller-Namen ----------
        ["Wii-Fernbedienung"] = "Wiiリモコン",
        ["Xbox-Controller"] = "Xbox コントローラー",
        ["Xbox-Controller (Microsoft)"] = "Xbox コントローラー（Microsoft）",
        ["XInput (USB, Bluetooth oder Xbox-Adapter)"] = "XInput（USB、Bluetooth または Xbox アダプター）",

        // ---------- Übersicht / Karten ----------
        ["Trennen"] = "切断",
        ["Vibrieren"] = "振動",
        ["Gyro kalibrieren"] = "ジャイロをキャリブレーション",
        ["Ruhig liegen lassen …"] = "静かに置いてください …",
        ["Kalibriert ✓"] = "キャリブレーション済み ✓",
        ["Hochkant halten"] = "縦に持つ",
        ["Quer halten"] = "横に持つ",
        ["Joy-Con trennen"] = "Joy-Con を分離",
        ["Zum Paar verbinden"] = "ペアにする",
        ["Joy-Con trennen – beide werden einzelne Controller"] = "Joy-Con を分離 – 両方が単体のコントローラーになります",
        ["Zum Paar verbinden – sucht einen freien Joy-Con"] = "ペアにする – 空いている Joy-Con を探します",
        ["Doppelt angezeigt? Verstecken"] = "二重表示？非表示にする",
        ["amiibo lesen"] = "amiibo を読み取る",
        ["Ring-Con ein"] = "Ring-Con オン",
        ["Ring-Con aus"] = "Ring-Con オフ",
        ["Ring-Con wird gesucht …"] = "Ring-Con を検索中 …",
        ["IR-Kamera"] = "IR カメラ",
        ["Akku"] = "バッテリー",
        ["Verbindung"] = "接続",
        ["Adresse"] = "アドレス",
        ["Seriennummer"] = "シリアル番号",
        ["Griff"] = "グリップ",
        ["Maus"] = "マウス",
        ["Gedrückt"] = "押下中",
        ["unbekannt"] = "不明",
        ["Charging Grip – GL/GR aktiv"] = "Charging Grip – GL/GR 有効",
        ["aktiv (liegt auf dem Tisch)"] = "有効（テーブルに置かれています）",
        ["bereit – zum Benutzen auf den Tisch legen"] = "準備完了 – テーブルに置いて使用",
        ["Bewegungssensor: keine Daten"] = "モーションセンサー：データなし",
        ["quer halten: Steuerkreuz links,\n1 und 2 rechts"] = "横向き：十字キーが左、\n1 と 2 が右",

        // ---------- Tooltips ----------
        ["Verbindung trennen. Der Controller verbindet sich beim nächsten Tastendruck wieder."] =
            "切断します。コントローラーは次のボタン押下で再接続します。",
        ["Controller kurz vibrieren lassen – zeigt, welcher Controller dieser Spieler ist."] =
            "コントローラーを短く振動させます – どのコントローラーがこのプレイヤーのものか示します。",
        ["Controller ruhig auf den Tisch legen und klicken: misst den Gyro-Nullpunkt neu (gegen Abdriften)."] =
            "コントローラーをテーブルに静かに置いてクリック：ジャイロのゼロ点を再測定します（ドリフト対策）。",
        ["Einzelnen Joy-Con quer (wie an der Switch) oder hochkant halten – wird je Joy-Con gemerkt. Hochkant gilt die Tastenbelegung von „Joy-Con-Paar“."] =
            "単体の Joy-Con を横向き（Switch と同じ）または縦向きに持ちます – Joy-Con ごとに記憶されます。縦向きでは「Joy-Con ペア」の割り当てが適用されます。",
        ["Versteckt den per USB angeschlossenen Controller vor Spielen (HidHide), damit sie nur den virtuellen Xbox-Controller sehen."] =
            "USB 接続されたコントローラーをゲームから隠します（HidHide）。ゲームには仮想 Xbox コントローラーのみが見えます。",
        ["amiibo mit dem NFC-Leser lesen und als Datei (.bin) speichern – z. B. für Emulatoren."] =
            "NFC リーダーで amiibo を読み取り、ファイル（.bin）として保存 – 例：エミュレーター用。",
        ["Ring-Con am rechten Joy-Con ein-/ausschalten: zusammendrücken = rechter Trigger, auseinanderziehen = linker Trigger. Beim Einschalten den Ring nicht berühren."] =
            "右 Joy-Con の Ring-Con をオン/オフ：押し込み = 右トリガー、引き伸ばし = 左トリガー。オンにする際はリングに触れないでください。",
        ["Live-Bild der IR-Kamera im rechten Joy-Con anzeigen."] = "右 Joy-Con の IR カメラのライブ映像を表示します。",
        ["Links = empfindlicher (kleine Drehung, großer Ausschlag), rechts = ruhiger."] = "左 = 高感度（小さな回転で大きく動く）、右 = ゆったり。",
        ["Mindestausschlag des Sticks bei Bewegung – überwindet die Totzone des Spiels."] = "動作時のスティックの最小入力 – ゲームのデッドゾーンを克服します。",
        ["Mitte = linear. Rechts = feiner um die Mitte (präzises Zielen), links = schneller."] = "中央 = リニア。右 = 中央付近が繊細（精密エイム）、左 = 高速。",
        ["So weit lässt sich ein analoger Trigger drücken, bevor er wirkt."] = "アナログトリガーが反応するまでの押し込み量。",
        ["Ab hier gilt der Trigger als ganz gedrückt (100 = erst am Anschlag)."] = "ここからトリガーは完全に押し込まれたとみなされます（100 = 奥まで）。",
        ["Wie oft pro Sekunde Tasten mit „Turbo“ auslösen."] = "「ターボ」ボタンが 1 秒間に発動する回数。",

        // ---------- Infobereich ----------
        ["ViGEmBus-Treiber fehlt"] = "ViGEmBus ドライバーがありません",
        ["ViGEmBus herunterladen …"] = "ViGEmBus をダウンロード …",
        ["Verbinde …"] = "接続中 …",
        ["Kein Controller – SYNC-Taste am Controller kurz drücken"] = "コントローラーなし – コントローラーの SYNC ボタンを短く押してください",
        ["Ausgabe als"] = "出力先",
        ["Xbox-360-Controller (empfohlen)"] = "Xbox 360 コントローラー（推奨）",
        ["DualShock 4 (mit Gyro für Steam/Emulatoren)"] = "DualShock 4（Steam/エミュレーター向けジャイロ付き）",
        ["Tastenbelegung"] = "ボタン割り当て",
        ["Xbox-Belegung (untere Taste = A)"] = "Xbox 配置（下のボタン = A）",
        ["Switch-2-Pro-Belegung (A bleibt A)"] = "Nintendo 配置（A は A のまま）",
        ["Automatisch (nach Spiel/Programm)"] = "自動（ゲーム/プログラムに応じて）",
        ["Mit Windows starten"] = "Windows と一緒に起動",
        ["Einstellungen …"] = "設定 …",
        ["Kurzanleitung"] = "クイックガイド",
        ["Protokoll öffnen"] = "ログを開く",
        ["Beenden"] = "終了",
        ["N-Connect: warte auf Controller (SYNC drücken)"] = "N-Connect：コントローラー待機中（SYNC を押してください）",
        ["N-Connect: ViGEmBus fehlt"] = "N-Connect：ViGEmBus がありません",
        ["Neue Version verfügbar"] = "新しいバージョンがあります",
        ["Einstellungen fehlerhaft"] = "設定が壊れています",
        ["settings.json konnte nicht gelesen werden – es gelten die Standardwerte."] = "settings.json を読み取れませんでした – デフォルト値が適用されます。",
        ["Ohne ViGEmBus kann kein virtueller Controller erzeugt werden. Bitte das Setup erneut ausführen oder ViGEmBus installieren (Rechtsklick auf das Symbol → ViGEmBus herunterladen)."] =
            "ViGEmBus がないと仮想コントローラーを作成できません。セットアップを再実行するか、ViGEmBus をインストールしてください（アイコンを右クリック → ViGEmBus をダウンロード）。",

        // ---------- Dialoge ----------
        ["Tastatur-Taste festlegen"] = "キーボードキーを設定",
        ["Übernehmen"] = "適用",
        ["Abbrechen"] = "キャンセル",
        ["Ja"] = "はい",
        ["Nein"] = "いいえ",
        ["Turbo / Dauerfeuer"] = "ターボ / 連射",
        ["Tastatur-Taste aufnehmen …"] = "キーボードキーを記録 …",
        ["Makro (Tastenfolge)"] = "マクロ（ボタン連続操作）",
        ["Ungültig – bitte Schreibweise prüfen (siehe oben)."] = "無効です – 記述方法を確認してください（上記参照）。",
        ["Neues Profil"] = "新しいプロファイル",
        ["Name des Profils (z. B. der Spielname):"] = "プロファイル名（例：ゲーム名）：",
        ["Profil umbenennen"] = "プロファイル名を変更",
        ["Neuer Name:"] = "新しい名前：",
        ["Ein Profil mit diesem Namen gibt es schon."] = "この名前のプロファイルはすでに存在します。",
        ["Die Datei enthält kein gültiges Controller-Profil."] = "このファイルには有効なコントローラープロファイルが含まれていません。",
        ["Alle Einstellungen und Tastenbelegungen auf Standard zurücksetzen?"] = "すべての設定とボタン割り当てをリセットしますか？",
        ["Suche …"] = "検索中 …",
        ["Kein Bluetooth-Adapter gefunden."] = "Bluetooth アダプターが見つかりません。",
        ["IR-Kamera (Joy-Con R)"] = "IR カメラ（Joy-Con 右）",
        ["Auflösung:"] = "解像度：",
        ["40 × 30 (schnell)"] = "40 × 30（高速）",
        ["320 × 240 (langsam)"] = "320 × 240（低速）",
        ["Kamera startet …"] = "カメラ起動中 …",
        ["läuft – Joy-Con auf eine Lichtquelle oder die Hand richten"] = "動作中 – Joy-Con を光源または手に向けてください",
        ["Kamera startet nicht (Details im Protokoll)"] = "カメラが起動しません（詳細はログに）",
        ["Kein Ring-Con gefunden. Den rechten Joy-Con (Switch 1) fest in den Ring-Con schieben und erneut versuchen."] =
            "Ring-Con が見つかりません。右 Joy-Con（Switch 1）を Ring-Con にしっかり差し込んで再試行してください。",
        ["Kein amiibo erkannt. Bitte das amiibo flach an den NFC-Leser halten (Joy-Con: auf den rechten Stick, Pro Controller: auf das NFC-Logo) und erneut versuchen."] =
            "amiibo が認識されません。amiibo を NFC リーダーに平らに当ててください（Joy-Con：右スティック、Pro Controller：NFC ロゴ）。",
        ["NFC-Leser wird eingeschaltet …"] = "NFC リーダーを起動中 …",
        ["amiibo an den Leser halten (rechter Stick des Joy-Con bzw. NFC-Logo des Pro Controllers) …"] =
            "amiibo をリーダーに当ててください（Joy-Con の右スティックまたは Pro Controller の NFC ロゴ）…",
        ["amiibo speichern"] = "amiibo を保存",
        ["Doppelte Controller verhindern"] = "コントローラーの二重表示を防止",
        ["Dafür wird das kostenlose Programm HidHide gebraucht (von den Machern von ViGEmBus).\n\nJetzt die Download-Seite öffnen? Nach der Installation hier erneut klicken."] =
            "そのためには無料の HidHide が必要です（ViGEmBus の開発元）。\n\n今すぐダウンロードページを開きますか？インストール後にここを再度クリックしてください。",
        ["HidHide konnte nicht eingerichtet werden (abgebrochen oder fehlgeschlagen). Details im Protokoll."] =
            "HidHide を設定できませんでした（中断または失敗）。詳細はログに記録されています。",
        ["Der Controller hat sich bewegt oder keine Bewegungsdaten geliefert.\nBitte flach auf den Tisch legen, nicht berühren und erneut versuchen."] =
            "コントローラーが動いたか、動作データが取得できませんでした。\nテーブルに平置きし、触れずにもう一度お試しください。",
        ["Spiel oder Programm wählen"] = "ゲームまたはプログラムを選択",
        ["Profil exportieren"] = "プロファイルをエクスポート",
        ["Profil importieren"] = "プロファイルをインポート",
        ["Verstanden"] = "了解",
        ["Einstellungen öffnen"] = "設定を開く",
        ["Willkommen"] = "ようこそ",

        // ---------- Neues Hauptfenster (Navigation, Seiten, Zeilen) ----------
        ["Allgemein"] = "全般",
        ["Sticks & Vibration"] = "スティックと振動",
        ["Gyro & Maus"] = "ジャイロとマウス",
        ["Joy-Con & Wii"] = "Joy-Con と Wii",
        ["Ein"] = "オン",
        ["Aus"] = "オフ",
        ["Verbundene Controller mit Live-Anzeige. Über „Einstellungen“ an einem Controller passt du genau diesen an."] =
            "接続中のコントローラーをライブ表示。コントローラーの「設定」で個別に調整できます。",
        ["Jede Taste kann ein Gamepad-Knopf, eine Tastaturtaste, ein Mausklick, Turbo oder ein Makro sein. " +
         "Tipp: Drückst du eine Taste am Controller, wird ihre Zeile hervorgehoben."] =
            "すべてのボタンにゲームパッドボタン、キーボードキー、マウスクリック、ターボ、マクロを割り当てられます。" +
            "ヒント：コントローラーのボタンを押すと、その行がハイライトされます。",
        ["Profil"] = "プロファイル",
        ["Neu"] = "新規",
        ["Umbenennen, löschen, exportieren, importieren"] = "名前変更、削除、エクスポート、インポート",
        ["Ein eigenes Profil gilt automatisch, solange eines seiner Programme im Vordergrund ist – sonst „Standard“."] =
            "専用プロファイルは、そのプログラムのいずれかが前面にある間、自動で適用されます – それ以外は「標準」。",
        ["Aktiv bei Programm"] = "プログラムで有効",
        ["Programmdateien, bei denen dieses Profil gilt (mit Komma trennen)."] = "このプロファイルが適用されるプログラムファイル（カンマ区切り）。",
        ["Standard gilt für alle Programme"] = "標準はすべてのプログラムに適用",
        ["Wählen …"] = "選択 …",
        ["Bearbeiten"] = "編集",
        ["Jeder Controller hat seine eigene Belegung."] = "各コントローラーには独自の割り当てがあります。",
        ["Ebene"] = "レイヤー",
        ["Normal"] = "通常",
        ["Shift-Ebene"] = "Shift レイヤー",
        ["Die Shift-Ebene gilt, solange eine Taste mit „Shift-Ebene“ gehalten wird."] = "「Shift レイヤー」に設定されたボタンを押している間、Shift レイヤーが有効になります。",
        ["Tasten"] = "ボタン",
        ["Standardwerte für alle Controller. Eigene Werte für einzelne Controller stellst du unten oder in der Übersicht ein."] =
            "すべてのコントローラーのデフォルト値。個別の値は下または概要で設定できます。",
        ["Sticks"] = "スティック",
        ["Totzone"] = "デッドゾーン",
        ["So weit lässt sich ein Stick bewegen, bevor er wirkt (gegen Abdriften)."] = "スティックが反応するまでの動きの大きさ（ドリフト対策）。",
        ["Kennlinie"] = "応答カーブ",
        ["„linear“ = gleichmäßig. Höher = feiner um die Mitte (präzises Zielen), niedriger = schneller."] =
            "「リニア」= 均等。高いほど中央付近が繊細（精密エイム）、低いほど高速。",
        ["Analoge Trigger (GameCube)"] = "アナログトリガー（GameCube）",
        ["So weit lässt sich ein Trigger drücken, bevor er wirkt."] = "トリガーが反応するまでの押し込み量。",
        ["Voll gedrückt ab"] = "完全押し込み位置",
        ["Ab hier gilt der Trigger als ganz gedrückt (100 % = erst am Anschlag)."] = "ここからトリガーは完全に押し込まれたとみなされます（100 % = 奥まで）。",
        ["Spiele dürfen den Controller vibrieren lassen."] = "ゲームがコントローラーを振動させることを許可。",
        ["Stärke"] = "強さ",
        ["Turbo-Geschwindigkeit"] = "ターボ速度",
        ["Wie oft pro Sekunde Tasten mit „Turbo“ auslösen."] = "「ターボ」ボタンが 1 秒間に発動する回数。",
        ["Eigene Werte je Controller"] = "コントローラー別の設定値",
        ["Werte nur für diesen Controller – ohne eigenen Wert gilt der allgemeine."] = "このコントローラー専用の値 – 専用値がなければ全体の値が適用されます。",
        ["Bewegungssteuerung: Zielen per Gyro und den Controller als Maus nutzen."] = "モーション操作：ジャイロでエイムし、コントローラーをマウスとして使用。",
        ["Gyro als rechter Stick"] = "ジャイロを右スティックに",
        ["Modus"] = "モード",
        ["Zum Zielen in Spielen ohne eigene Gyro-Steuerung. „Gyro-Stick“ kann auch einer Taste zugewiesen werden."] =
            "ジャイロ非対応ゲームでエイムするために使用。「ジャイロスティック」はボタンに割り当てることも可能。",
        ["Aus (nur per Taste „Gyro-Stick“)"] = "オフ（「ジャイロスティック」ボタンでのみ）",
        ["Immer"] = "常に",
        ["Beim Zielen (solange ZL / LT gedrückt)"] = "エイム時（ZL / LT 押下中）",
        ["Empfindlichkeit"] = "感度",
        ["Drehgeschwindigkeit für vollen Stick-Ausschlag – kleiner = empfindlicher."] = "スティック全倒しに必要な回転速度 – 小さいほど高感度。",
        ["Mindestausschlag"] = "最小入力",
        ["Überwindet die Stick-Totzone des Spiels bei kleinen Bewegungen."] = "小さな動きでもゲームのスティックデッドゾーンを克服します。",
        ["Hoch/runter umkehren"] = "上下を反転",
        ["Links/rechts umkehren"] = "左右を反転",
        ["Gyro-Maus"] = "ジャイロマウス",
        ["Geschwindigkeit"] = "速度",
        ["Mauszeiger per Bewegung – über eine Taste mit „Gyro-Maus“ (Tastenbelegung)."] = "動きでマウスポインターを操作 – 「ジャイロマウス」ボタン経由（ボタン割り当て）。",
        ["Mausrichtung (Gyro-Maus und Joy-Con-Maus)"] = "マウスの方向（ジャイロマウスと Joy-Con マウス）",
        ["Gyro-Funktionen einer Taste zuweisen"] = "ジャイロ機能をボタンに割り当て",
        ["Gyro-Maus oder Gyro-Stick ein/aus bzw. solange gehalten"] = "ジャイロマウスまたはジャイロスティックのオン/オフ、または押下中",
        ["Joy-Con als Paar oder einzeln, Joy-Con 2 als Maus und Wii-Controller."] = "Joy-Con のペアまたは単体、Joy-Con 2 のマウス機能、Wii コントローラー。",
        ["Zu einem Controller zusammenfassen"] = "1 つのコントローラーにまとめる",
        ["Ein linker und ein rechter Joy-Con werden automatisch ein Paar."] = "左右の Joy-Con が自動でペアになります。",
        ["Gyro beim Paar vom"] = "ペアのジャイロの取得元",
        ["Rechter Joy-Con (wie Switch)"] = "右 Joy-Con（Switch と同じ）",
        ["Linker Joy-Con"] = "左 Joy-Con",
        ["Paar lösen oder verbinden"] = "ペアの解除または結合",
        ["Einen Joy-Con quer halten und SL oder SR drücken löst ihn aus dem Paar. L am linken und R am rechten Joy-Con gleichzeitig drücken verbindet sie wieder. Die Wahl wird je Joy-Con gemerkt."] =
            "Joy-Con を横向きに持ち SL または SR を押すとペアから外れます。左の L と右の R を同時に押すと再度ペアになります。選択は Joy-Con ごとに記憶されます。",
        ["Joy-Con 2 als Maus"] = "Joy-Con 2 をマウスとして",
        ["Als Maus, wenn er auf dem Tisch liegt"] = "テーブルに置いた場合にマウスとして",
        ["Joy-Con 2 auf die Seite legen und wie eine Maus schieben."] = "Joy-Con 2 を横に置き、マウスのように滑らせます。",
        ["Mausgeschwindigkeit"] = "マウス速度",
        ["Tasten im Mausmodus"] = "マウスモードのボタン",
        ["R/L = Linksklick, ZR/ZL = Rechtsklick, Stick drücken = Mittelklick, Stick hoch/runter = Scrollen."] =
            "R/L = 左クリック、ZR/ZL = 右クリック、スティック押し込み = 中クリック、スティック上下 = スクロール。",
        ["Zeiger steuert die Maus"] = "ポインターでマウスを操作",
        ["Wii-Fernbedienung auf die Sensorleiste richten, um den Mauszeiger zu bewegen."] = "Wiiリモコンをセンサーバーに向けてマウスポインターを動かします。",
        ["Wie Spiele die Controller sehen, Verbindung, Darstellung und Programm."] = "ゲームから見えるコントローラー、接続、外観、プログラム設定。",
        ["Ausgabe"] = "出力",
        ["Controller erscheint als"] = "コントローラーの表示",
        ["Xbox 360 läuft mit fast allen Spielen. DualShock 4 bietet Bewegungssteuerung (Steam, Emulatoren)."] =
            "Xbox 360 はほぼすべてのゲームで動作。DualShock 4 はモーション操作を提供（Steam、エミュレーター）。",
        ["Xbox 360 läuft mit fast allen Spielen und Steam. DualShock 4 bietet zusätzlich Bewegungssteuerung (Steam, Emulatoren). Gilt für alle Controller ohne eigene Einstellung (Karte → Einstellungen → Tasten)."] =
            "Xbox 360 はほぼすべてのゲームと Steam で動作。DualShock 4 はさらにモーション操作を追加（Steam、エミュレーター）。個別設定のないすべてのコントローラーに適用（カード → 設定 → ボタン）。",
        ["Original-Controller verstecken"] = "元のコントローラーを隠す",
        ["Controller verbinden"] = "コントローラーを接続",
        ["SYNC-Taste am Controller drücken – N-Connect findet und koppelt ihn selbst. Danach reicht künftig ein Tastendruck."] =
            "コントローラーの SYNC ボタンを押してください – N-Connect が自動で検出してペアリングします。以降はボタン一つで接続できます。",
        ["So kommt der Controller in den Kopplungsmodus"] = "コントローラーをペアリングモードにする方法",
        ["Kurz die kleine SYNC-Taste drücken."] = "小さな SYNC ボタンを短く押します。",
        ["SYNC-Taste drücken, bis die Lichter laufen."] = "ランプが流れるまで SYNC ボタンを押します。",
        ["Batteriefach öffnen und die rote SYNC-Taste drücken."] = "電池カバーを開けて赤い SYNC ボタンを押します。",
        ["Die SYNC-Taste auf der Unterseite drücken."] = "底面の SYNC ボタンを押します。",
        ["PS + Teilen bzw. Create halten, bis die Lichtleiste schnell blinkt."] =
            "ライトバーが高速点滅するまで PS + Share/Create を押し続けます。",
        ["Kopplungstaste oben halten, bis die Xbox-Taste blinkt."] = "Xbox ボタンが点滅するまで上部のペアリングボタンを押し続けます。",
        ["Status"] = "ステータス",
        ["Suche läuft …"] = "検索中 …",
        ["Suche läuft – jetzt SYNC drücken …"] = "検索中 – 今すぐ SYNC を押してください …",
        ["Weitere Controller? Einfach SYNC drücken."] = "他のコントローラー？ SYNC を押すだけです。",
        ["Wartet auf einen Controller im Kopplungsmodus."] = "ペアリングモードのコントローラーを待機中。",
        ["Suche beendet"] = "検索終了",
        ["Die Controller stehen in der Übersicht und verbinden sich künftig per Tastendruck."] =
            "コントローラーは概要に表示され、今後はボタン一つで接続します。",
        ["Kein Controller im Kopplungsmodus gefunden. SYNC-Taste drücken und „Erneut suchen“ klicken."] =
            "ペアリングモードのコントローラーが見つかりません。SYNC を押して「再検索」をクリックしてください。",
        ["Verbunden"] = "接続済み",
        ["Erneut suchen"] = "再検索",
        ["Fertig"] = "完了",
        ["Im Spiel"] = "ゲーム内",
        ["Dreht …"] = "回転中 …",
        ["Testdrehung (360°)"] = "テスト回転（360°）",
        ["Testdrehung"] = "テスト回転",
        ["aus"] = "オフ",
        ["Gyro-Beschleunigung"] = "ジャイロ加速度",
        ["Bei schneller Drehung"] = "高速回転時",
        ["Langsame Bewegungen bleiben fein, schnelle drehen weiter (wie JoyShockMapper). Voll ab 120 °/s, unter 20 °/s normal. Gilt für Gyro-Stick und Gyro-Maus."] =
            "ゆっくりした動きは繊細なまま、速い動きはより大きく回転します（JoyShockMapper と同様）。120 °/s 以上でフル、20 °/s 未満は通常。ジャイロスティックとジャイロマウスに適用。",
        ["Flick-Stick (Spiele mit Maussteuerung)"] = "フリックスティック（マウス操作のゲーム用）",
        ["Flick-Stick"] = "フリックスティック",
        ["Rechten Stick in eine Richtung schieben = Kamera dreht sofort dorthin; am Rand drehen = Kamera dreht mit. Zielen dann per Gyro. Der rechte Stick geht nicht mehr ans Spiel."] =
            "右スティックを倒す方向にカメラが即座に向き、縁に沿って回すとカメラが追従します。その後ジャイロでエイム。右スティックはゲームに送られなくなります。",
        ["Mausbewegung je Umdrehung"] = "1 回転あたりのマウス移動量",
        ["Je Spiel einmal einstellen: „Testdrehung“ klicken, ins Spiel wechseln – nach 3 s dreht die Kamera einmal. Genau eine volle Drehung = richtig."] =
            "ゲームごとに一度設定：「テスト回転」をクリックしてゲームに切り替え – 3 秒後にカメラが一回転します。ちょうど 1 回転なら正しい設定です。",
        ["Flick-Dauer"] = "フリック時間",
        ["So lange dauert die Drehung beim Flick (0 = sofort)."] = "フリック時の回転にかかる時間（0 = 即時）。",
        ["Gyro-Maus oder Gyro-Stick ein/aus bzw. solange gehalten, „Gyro anhalten“ (Ratchet: Controller zurückführen, ohne dass sich das Ziel bewegt)"] =
            "ジャイロマウスまたはジャイロスティックのオン/オフ、または押下中、「ジャイロ一時停止」（ラチェット：照準を動かさずにコントローラーを戻す）",
        ["✋  Gyro anhalten (solange gehalten, „Ratchet“)"] = "✋  ジャイロ一時停止（押下中、「ラチェット」）",
        ["Spieler-LED und Lichtleiste vom Spiel"] = "プレイヤー LED とゲームのライトバー",
        ["Die Spieler-LEDs zeigen den Xbox-Platz, den Windows vergibt. Bei DualShock 4 steuert die Lichtleiste des Spiels die HOME-LED (Switch 1 Pro Controller, rechter Joy-Con)."] =
            "プレイヤー LED は Windows が割り当てた Xbox の位置を示します。DualShock 4 ではゲームのライトバーが HOME LED を制御します（Switch 1 Pro Controller、右 Joy-Con）。",
        ["HidHide installieren …"] = "HidHide をインストール …",
        ["Empfohlen: Steam und viele Spiele kennen Switch-1-, NSO- und USB-Controller selbst und sähen sie sonst doppelt. Läuft nach der Installation ohne Rückfrage (sonst fragt Windows nach Adminrechten)."] =
            "推奨：Steam と多くのゲームは Switch 1、NSO、USB コントローラーを自動認識するため、二重表示になります。インストール後は確認なしで動作します（それ以外は Windows が管理者権限を求めます）。",
        ["Steam und viele Spiele sehen Switch-1-, NSO- und USB-Controller sonst doppelt. Dafür wird das kostenlose HidHide gebraucht (bei der N-Connect-Installation dabei, hier nachträglich)."] =
            "これがないと Steam と多くのゲームで Switch 1、NSO、USB コントローラーが二重表示されます。無料の HidHide が必要です（N-Connect のインストールに同梱、ここから後でインストール可能）。",
        ["Erscheint als"] = "表示名",
        ["Wie allgemein"] = "全般と同じ",
        ["Nur für diesen Controller. Xbox 360 läuft überall; DualShock 4 bringt zusätzlich Gyro nach Steam und in Emulatoren. „Wie allgemein“ folgt der Seite „Allgemein“."] =
            "このコントローラーのみ。Xbox 360 はどこでも動作し、DualShock 4 は Steam とエミュレーターにジャイロを追加します。「全般と同じ」は「全般」ページに従います。",
        ["Der echte Xbox-Controller – Spiele sehen ihn von Windows aus direkt. Belegungen hier wirken auf Sonderaktionen (Tastatur, Makros, Gyro), nicht auf den Controller selbst."] =
            "本物の Xbox コントローラー – ゲームは Windows から直接認識します。ここの割り当ては特別な操作（キーボード、マクロ、ジャイロ）に作用し、コントローラー自体には影響しません。",
        ["Steam und manche Spiele sehen diesen Controller sonst doppelt. Abhilfe: HidHide installieren (Seite „Allgemein“ → „Original-Controller verstecken“)."] =
            "これがないと Steam と一部のゲームでこのコントローラーが二重表示されます。対策：HidHide をインストール（「全般」ページ →「元のコントローラーを隠す」）。",
        ["Original-Controller vor Spielen versteckt. Steam bitte einmal neu starten – danach sieht es nur noch den virtuellen Controller."] =
            "元のコントローラーをゲームから隠しました。Steam を一度再起動してください – その後は仮想コントローラーのみが見えます。",
        ["Original-Controller vor Spielen versteckt – Steam und Spiele sehen nur noch den virtuellen Controller."] =
            "元のコントローラーをゲームから隠しました – Steam とゲームには仮想コントローラーのみが見えます。",
        ["Original-Controller nicht versteckt (Abfrage abgebrochen). Nachholen: Controller → Einstellungen → Extras → „Doppelt angezeigt?“."] =
            "元のコントローラーは隠されていません（確認をキャンセル）。後で行う場合：コントローラー → 設定 → その他 →「二重表示？」。",
        ["Tastenanordnung A/B/X/Y"] = "ボタン配置 A/B/X/Y",
        ["Xbox: nach Position (untere Taste = A). Nintendo: nach Beschriftung (A bleibt A)."] = "Xbox：位置で決定（下のボタン = A）。Nintendo：表示どおり（A は A のまま）。",
        ["Verbinden"] = "接続",
        ["Per Tastendruck verbinden"] = "ボタン一つで接続",
        ["Gekoppelte Controller verbinden sich ohne SYNC-Taste."] = "ペアリング済みコントローラーは SYNC ボタンなしで接続します。",
        ["Ohne Eingabe trennen nach"] = "操作がない場合に切断",
        ["Spart Akku, wenn ein Controller liegen bleibt."] = "コントローラーが放置されている場合にバッテリーを節約します。",
        ["N-Connect startet unsichtbar im Infobereich."] = "N-Connect は通知領域に最小化して起動します。",
        ["Darstellung und Sprache"] = "外観と言語",
        ["Farbmodus"] = "カラーモード",
        ["Mica-Effekt"] = "Mica エフェクト",
        ["Durchscheinende Titelleiste (ab Windows 11)."] = "半透明のタイトルバー（Windows 11 以降）。",
        ["Erweitert"] = "詳細",
        ["Gyro für Emulatoren (DSU)"] = "エミュレーター用ジャイロ（DSU）",
        ["Cemuhook-Server auf Port 26760 – wirkt nach einem Neustart von N-Connect."] = "ポート 26760 の Cemuhook サーバー – N-Connect の再起動後に有効。",
        ["Nach Updates suchen"] = "アップデートを確認",
        ["Beim Start auf GitHub nach einer neuen Version suchen."] = "起動時に GitHub で新しいバージョンを確認。",
        ["Tastenbelegungen und Werte zurücksetzen. Gekoppelte Controller bleiben erhalten."] = "ボタン割り当てと設定値をリセット。ペアリング済みコントローラーは保持されます。",
        ["Zurücksetzen"] = "リセット",

        // ---------- Controller-Karte ----------
        ["Einstellungen"] = "設定",
        ["Tastenbelegung und Einstellungen nur für diesen Controller"] = "このコントローラー専用のボタン割り当てと設定",
        ["Feineinstellung"] = "微調整",
        ["Gyro"] = "ジャイロ",
        ["Extras"] = "その他",
        ["Belegung für alle Spiele (Standard) oder ein eigenes Profil."] = "すべてのゲーム用（標準）または専用プロファイルの割り当て。",
        ["Profile"] = "プロファイル",
        ["Profile anlegen, umbenennen, exportieren …"] = "プロファイルの作成、名前変更、エクスポート …",
        ["Drück eine Taste am Controller – ihre Zeile leuchtet auf. ⌨ weist eine Tastaturtaste zu, ↺ setzt zurück."] =
            "コントローラーのボタンを押すと、その行がハイライトされます。⌨ でキーボードキーを割り当て、↺ でリセット。",
        ["Tastatur-Taste zuweisen: klicken und die gewünschte Taste oder Kombination drücken."] = "キーボードキーを割り当て：クリックして目的のキーまたは組み合わせを押します。",
        ["Zurück auf die Standardbelegung"] = "デフォルトの割り当てに戻す",
        ["Ohne eigenen Wert gilt der allgemeine Wert der Seite „Sticks & Vibration“."] = "専用値がなければ「スティックと振動」ページの全体値が適用されます。",
        ["Stick-Totzone"] = "スティックのデッドゾーン",
        ["Stick-Kennlinie"] = "スティック特性",
        ["Trigger-Totzone"] = "トリガーのデッドゾーン",
        ["Trigger voll gedrückt ab"] = "トリガー完全押し込み位置",
        ["Vibrationsstärke"] = "振動の強さ",
        ["Gyro-Maus-Geschwindigkeit"] = "ジャイロマウス速度",
        ["Eigenen Wert entfernen – es gilt wieder der allgemeine Wert"] = "専用値を削除 – 全体の値に戻ります",
        ["Kalibrieren"] = "キャリブレーション",
        ["Controller ruhig auf den Tisch legen und klicken: misst den Nullpunkt neu (gegen Abdriften)."] =
            "コントローラーをテーブルに静かに置いてクリック：ゼロ点を再測定します（ドリフト対策）。",
        ["Gyro als rechter Stick und Mausrichtung"] = "ジャイロを右スティックに / マウスの方向",
        ["Gilt für alle Controller"] = "すべてのコントローラーに適用",
        ["Paar"] = "ペア",
        ["Joy-Con quer halten und SL oder SR drücken löst das Paar, L + R gleichzeitig verbindet es."] =
            "Joy-Con を横向きに持ち SL または SR を押すとペアが解け、L + R を同時に押すと結合します。",
        ["Haltung"] = "持ち方",
        ["Quer"] = "横向き",
        ["Hochkant"] = "縦向き",
        ["Quer wie an der Switch oder hochkant – hochkant gilt die Belegung von „Joy-Con-Paar“."] =
            "Switch と同じ横向き、または縦向き – 縦向きでは「Joy-Con ペア」の割り当てが適用されます。",
        ["Mausmodus, Geschwindigkeit und Tasten"] = "マウスモード、速度、ボタン",
        ["Lesen …"] = "読み取る …",
        ["Einschalten"] = "オン",
        ["Ausschalten"] = "オフ",
        ["Wird gesucht …"] = "検索中 …",
        ["Öffnen"] = "開く",
        ["Verstecken"] = "非表示",
        ["amiibo an den NFC-Leser halten und als Datei (.bin) speichern – z. B. für Emulatoren."] =
            "amiibo を NFC リーダーに当ててファイル（.bin）として保存 – 例：エミュレーター用。",
        ["Zusammendrücken = rechter Trigger, auseinanderziehen = linker Trigger. Beim Einschalten nicht berühren."] =
            "押し込み = 右トリガー、引き伸ばし = 左トリガー。オンにする際は触れないでください。",
        ["Live-Bild der Infrarotkamera im rechten Joy-Con."] = "右 Joy-Con の赤外線カメラのライブ映像。",
        ["Doppelt angezeigt?"] = "二重表示？",
        ["Versteckt den Original-Controller vor Steam und Spielen (HidHide) – sie sehen dann nur den virtuellen Controller."] =
            "元のコントローラーを Steam とゲームから隠します（HidHide）– 仮想コントローラーのみが見えます。",
        ["bereit (auf den Tisch legen)"] = "準備完了（テーブルに置いてください）",
        ["amiibo-Abbild (*.bin)|*.bin"] = "amiibo イメージ (*.bin)|*.bin",
        ["Controller-Profil (*.ncprofile.json)|*.ncprofile.json|JSON (*.json)|*.json"] = "コントローラープロファイル (*.ncprofile.json)|*.ncprofile.json|JSON (*.json)|*.json",
        ["Programme (*.exe)|*.exe"] = "プログラム (*.exe)|*.exe",
        ["Kein Controller verbunden\n\n" +
         "Switch-2-Controller: kurz die SYNC-Taste drücken – danach reicht ein beliebiger Tastendruck.\n" +
         "Switch-1-, NSO- und Wii-Controller: SYNC-Taste drücken – N-Connect koppelt sie selbst.\n" +
         "Oder hier gezielt suchen und koppeln:"] =
            "コントローラーが接続されていません\n\n" +
            "Switch 2 コントローラー：SYNC ボタンを短く押す – 以降は任意のボタンで接続。\n" +
            "Switch 1、NSO、Wii コントローラー：SYNC ボタンを押す – N-Connect が自動でペアリング。\n" +
            "またはここで直接検索・ペアリング：",
        ["Controller suchen …"] = "コントローラーを検索 …",
        ["Kein Controller verbunden"] = "コントローラーが接続されていません",
        ["Switch-1-, NSO- und Wii-Controller suchen und koppeln (SYNC-Taste drücken)."] =
            "Switch 1、NSO、Wii コントローラーを検索・ペアリング（SYNC ボタンを押す）。",
        ["Neue Controller automatisch koppeln"] = "新しいコントローラーを自動でペアリング",
        ["Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive, Wii und PlayStation: einfach SYNC " +
         "drücken – kein Umweg über die Windows-Bluetooth-Einstellungen. Gesucht wird nur, solange niemand spielt."] =
            "Joy-Con、Pro Controller、NES/SNES/N64/Mega Drive、Wii、PlayStation：SYNC を押すだけ – " +
            "Windows の Bluetooth 設定を経由する必要はありません。検索は誰もプレイしていない間のみ行われます。",
        ["Gezielt suchen"] = "対象を絞って検索",
        ["Sucht eine Minute lang nach Controllern im Kopplungsmodus."] = "1 分間、ペアリングモードのコントローラーを検索します。",
        ["Controller koppeln …"] = "コントローラーをペアリング …",
        ["Controller koppeln"] = "コントローラーをペアリング",
        ["Linken Joy-Con umbenennen …"] = "左 Joy-Con の名前を変更 …",
        ["Rechten Joy-Con umbenennen …"] = "右 Joy-Con の名前を変更 …",
        ["Controller umbenennen"] = "コントローラーの名前を変更",
        ["Spielerplatz"] = "プレイヤー位置",
        ["N-Connect aktualisieren"] = "N-Connect を更新",
        ["HidHide aktualisieren"] = "HidHide を更新",
        ["HidHide-Update verfügbar"] = "HidHide のアップデートがあります",
        ["HidHide aktuell halten"] = "HidHide を最新に保つ",
        ["Beim Start nach einer neuen HidHide-Version suchen. Installiert wird nur nach Rückfrage (geprüfter Download vom Hersteller, Neustart nötig)."] =
            "起動時に HidHide の新しいバージョンを確認。確認後のみインストールします（メーカーからの検証済みダウンロード、再起動が必要）。",
        ["Der Download hat nicht geklappt oder die Datei war fehlerhaft. Die Release-Seite im Browser öffnen?"] =
            "ダウンロードに失敗したか、ファイルが破損していました。ブラウザでリリースページを開きますか？",
        ["Alle Controller trennen"] = "すべてのコントローラーを切断",
        ["Sticks kalibrieren"] = "スティックをキャリブレーション",
        ["Kalibrieren …"] = "キャリブレーション …",
        ["Gegen Drift oder zu kleinen Ausschlag: Mitte und Rand neu messen. Wird nur in N-Connect gespeichert, der Controller bleibt unverändert."] =
            "ドリフトや小さすぎる可動域に対処：中央と端を再測定。N-Connect のみに保存され、コントローラーは変更されません。",
        ["Linker Stick"] = "左スティック",
        ["Rechter Stick"] = "右スティック",
        ["Stick"] = "スティック",
        ["Stick (linker Joy-Con)"] = "スティック（左 Joy-Con）",
        ["Stick (rechter Joy-Con)"] = "スティック（右 Joy-Con）",
        ["Neu messen"] = "再測定",
        ["Werkswerte"] = "工場出荷値",
        ["Der Punkt zeigt, wo der Stick gerade steht. Steht er losgelassen nicht in der Mitte oder erreicht er den Kreis nicht, auf „Neu messen“ klicken."] =
            "点がスティックの現在位置を示します。離したときに中央にないか、円に届かない場合は「再測定」をクリックしてください。",
        ["Gilt gerade: eigene Kalibrierung."] = "現在使用中：独自キャリブレーション。",
        ["Gilt gerade: Werkswerte des Controllers."] = "現在使用中：コントローラーの工場出荷値。",
        ["1/2 – Stick loslassen und den Controller ruhig halten …"] = "1/2 – スティックを離し、コントローラーを動かさないでください …",
        ["2/2 – Stick bis zum Anschlag drücken und langsam ein- bis zweimal im Kreis drehen."] =
            "2/2 – スティックを奥まで倒し、ゆっくり 1〜2 回回してください。",
        ["Fertig. „Übernehmen“ speichert die neue Kalibrierung für diesen Controller."] = "完了。「適用」でこのコントローラーの新しいキャリブレーションを保存します。",
        ["Der Stick hat den Rand nicht erreicht. Bitte bis zum Anschlag drücken und erneut messen."] =
            "スティックが端に届いていません。奥まで押して再測定してください。",
        ["Übernommen ✓ – gilt ab sofort."] = "適用済み ✓ – すぐに有効になります。",
        ["Werkswerte des Controllers gelten wieder."] = "コントローラーの工場出荷値に戻りました。",
        ["Gyro einrichten"] = "ジャイロを設定",
        ["Einrichten …"] = "設定 …",
        ["Zielen per Bewegung einrichten"] = "モーションエイムを設定",
        ["Schritt für Schritt: Nullpunkt, wann der Gyro zielt, Empfindlichkeit – mit Vorschau."] =
            "ステップごとに：ゼロ点、ジャイロがエイムするタイミング、感度 – プレビュー付き。",
        ["1  Nullpunkt"] = "1  ゼロ点",
        ["Controller flach auf den Tisch legen, nicht berühren – verhindert, dass das Ziel von selbst wandert."] =
            "コントローラーをテーブルに平置きし、触れないでください – 照準が勝手に動くのを防ぎます。",
        ["Nullpunkt messen"] = "ゼロ点を測定",
        ["Der Controller hat sich bewegt – bitte flach hinlegen und erneut versuchen."] = "コントローラーが動きました – 平置きしてもう一度お試しください。",
        ["Nullpunkt gemessen ✓"] = "ゼロ点を測定しました ✓",
        ["2  Wann zielt der Gyro?"] = "2  ジャイロがエイムするタイミング",
        ["Nur per Taste"] = "ボタンのみ",
        ["Beim Zielen (ZL/LT)"] = "エイム時（ZL/LT）",
        ["„Beim Zielen“: nur solange ZL (linker Trigger) gehalten wird – wie in vielen Shootern."] =
            "「エイム時」：ZL（左トリガー）を押している間のみ – 多くのシューターと同様。",
        ["3  Empfindlichkeit"] = "3  感度",
        ["Voller Ausschlag ab"] = "全倒しになる回転速度",
        ["Kleinerer Wert bei „Voller Ausschlag ab“ = empfindlicher. „Mindestausschlag“ überwindet die Totzone des Spiels."] =
            "「全倒しになる回転速度」が小さいほど高感度。「最小入力」はゲームのデッドゾーンを克服します。",
        ["Mitte"] = "中央",
        ["Vorschau: Fadenkreuz folgt dem Controller (unabhängig von Schritt 2)."] = "プレビュー：照準がコントローラーに追従（ステップ 2 とは独立）。",
        ["Keine Bewegungsdaten"] = "動作データなし",
        ["Controller gekoppelt"] = "コントローラーがペアリングされました",
        ["Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive: SYNC-Taste drücken, bis die Lichter laufen.\n" +
         "Wii-Fernbedienung: Batteriefach öffnen und die rote SYNC-Taste drücken.\n" +
         "Wii U Pro Controller: die SYNC-Taste auf der Unterseite drücken.\n" +
         "Danach verbindet sich der Controller künftig per Tastendruck."] =
            "Joy-Con、Pro Controller、NES/SNES/N64/Mega Drive：ランプが流れるまで SYNC ボタンを押します。\n" +
            "Wiiリモコン：電池カバーを開けて赤い SYNC ボタンを押します。\n" +
            "Wii U Pro Controller：底面の SYNC ボタンを押します。\n" +
            "以降はボタン一つで接続します。",
        ["Suche … SYNC-Taste drücken (Xbox: Kopplungstaste oben halten, PlayStation: PS + Teilen/Create halten)."] =
            "検索中 … SYNC ボタンを押してください（Xbox：上部のペアリングボタンを長押し、PlayStation：PS + Share/Create を長押し）。",
        ["Kein Controller im Kopplungsmodus gefunden. SYNC-Taste drücken und erneut versuchen."] =
            "ペアリングモードのコントローラーが見つかりません。SYNC を押してもう一度お試しください。",
        ["Darstellung:"] = "外観：",
        ["Dunkel"] = "ダーク",
        ["Hell"] = "ライト",
        ["Wie Windows"] = "Windows に合わせる",
        ["Mica-Effekt in der Titelleiste (ab Windows 11)"] = "タイトルバーの Mica エフェクト（Windows 11 以降）",

        // ---------- Fehlerfälle und Hinweise ----------
        ["Bluetooth ist ausgeschaltet."] = "Bluetooth がオフになっています。",
        ["Dieser Bluetooth-Adapter unterstützt kein Bluetooth LE."] = "この Bluetooth アダプターは Bluetooth LE に対応していません。",
        ["Bluetooth-Suche konnte nicht starten."] = "Bluetooth 検索を開始できませんでした。",
        ["Bluetooth in den Windows-Einstellungen einschalten."] = "Windows の設定で Bluetooth をオンにしてください。",
        ["Controller per USB funktionieren weiterhin."] = "USB 接続のコントローラーは引き続き使用できます。",
        ["Für Switch-2-Controller wird ein Adapter mit Bluetooth 4.0 oder neuer gebraucht."] = "Switch 2 コントローラーには Bluetooth 4.0 以降のアダプターが必要です。",
        ["Andere Controller und USB funktionieren weiterhin."] = "他のコントローラーと USB は引き続き使用できます。",
        ["Bluetooth-Adapter (z. B. USB-Stick) einstecken bzw. Bluetooth in Windows aktivieren."] =
            "Bluetooth アダプター（例：USB ドングル）を接続するか、Windows で Bluetooth を有効にしてください。",
        ["Bluetooth ist bereit – Controller können verbunden werden."] = "Bluetooth の準備ができました – コントローラーを接続できます。",
        ["Bluetooth-Einstellungen öffnen"] = "Bluetooth 設定を開く",
        ["ViGEmBus-Treiber fehlt – ohne ihn kann kein virtueller Controller erzeugt werden."] =
            "ViGEmBus ドライバーがありません – これがないと仮想コントローラーを作成できません。",
        ["Bitte das Setup erneut ausführen."] = "セットアップを再実行してください。",
        ["Das Programm schließen oder in Steam die Nintendo-Unterstützung abschalten."] =
            "そのプログラムを終了するか、Steam で Nintendo サポートを無効にしてください。",
        ["Erst einen anderen trennen."] = "先に別のコントローラーを切断してください。",
        ["Tipp: Bluetooth-Stick per Verlängerung näher an den Controller, weg von USB-3-Anschlüssen und Funkkopfhörern."] =
            "ヒント：Bluetooth ドングルを延長ケーブルでコントローラーに近づけ、USB 3 ポートやワイヤレスヘッドセットから離してください。",
        ["Controller mit dem PC gekoppelt – ab jetzt reicht ein Tastendruck."] = "コントローラーが PC にペアリングされました – 以降はボタン一つで接続できます。",
        ["Hinweis: Um ihn wieder an der Switch 2 zu nutzen, dort einmal kurz SYNC drücken."] =
            "注意：Switch 2 で再度使用するには、本体で SYNC を一度短く押してください。",
        ["Dieser Bluetooth-Adapter unterstützt kein Bluetooth LE"] = "この Bluetooth アダプターは Bluetooth LE に対応していません",
        ["Erst IR-Kamera bzw. Ring-Con ausschalten (sie nutzen denselben Zusatzprozessor wie der NFC-Leser)."] =
            "先に IR カメラまたは Ring-Con をオフにしてください（NFC リーダーと同じサブプロセッサを使用しています）。",
        ["Erst die IR-Kamera schließen (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "先に IR カメラを閉じてください（Ring-Con と IR カメラは同じサブプロセッサを使用します）。",
        ["Erst den Ring-Con ausschalten (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "先に Ring-Con をオフにしてください（Ring-Con と IR カメラは同じサブプロセッサを使用します）。",
        ["amiibo zu früh entfernt"] = "amiibo が早く取り除かれすぎました",
        ["MCU startet nicht"] = "サブプロセッサが起動しません",
        ["NFC-Modus nicht aktiv"] = "NFC モードが有効ではありません",
        ["Kopplung fehlgeschlagen – Details im Protokoll."] = "ペアリングに失敗しました – 詳細はログに記録されています。",

        // ---------- Kopplungsdaten (Switch-SD-Karte, anderer PC) ----------
        ["Kopplungsdaten"] = "ペアリングデータ",
        ["Kopplungen übernehmen oder weitergeben"] = "ペアリングの引き継ぎまたは共有",
        ["Kopplungsdaten von der Switch übernehmen"] = "Switch からペアリングデータを引き継ぐ",
        ["Von der Switch-SD-Karte (Bluepick_RCM/hekate) oder von einem anderen PC übernehmen, oder für einen anderen PC exportieren."] =
            "Switch の SD カード（Bluepick_RCM/hekate）や別の PC から引き継ぐか、別の PC 用にエクスポートします。",
        ["Bei Switch-SD-Karte nachfragen"] = "Switch の SD カードが挿入されたら確認",
        ["Steckt eine SD-Karte der Switch im PC (Kartenleser oder hekate „USB Tools“), bietet N-Connect die Übernahme an. Die Karte wird nur gelesen."] =
            "Switch の SD カードが PC に挿入されている場合（カードリーダーまたは hekate「USB Tools」）、N-Connect が引き継ぎを提案します。カードは読み取りのみです。",
        ["Switch-SD-Karte erkannt"] = "Switch の SD カードを検出",
        ["Kopplungsdaten der Controller gefunden – klicken, um sie anzusehen und zu übernehmen."] =
            "コントローラーのペアリングデータが見つかりました – クリックして確認・引き継ぎます。",
        ["Klicken, um Kopplungsdaten der Controller zu übernehmen."] = "クリックしてコントローラーのペアリングデータを引き継ぎます。",
        ["Controller-Kopplungen von der Switch-SD-Karte oder von einem anderen PC übernehmen – oder für einen anderen PC exportieren. Es werden nur Einstellungen von N-Connect geändert; Windows und der Bluetooth-Adapter bleiben unverändert."] =
            "Switch の SD カードや別の PC からコントローラーのペアリングを引き継ぐか、別の PC 用にエクスポートします。変更されるのは N-Connect の設定のみで、Windows と Bluetooth アダプターは変更されません。",
        ["Spieler-Reihenfolge – Spieler 1 ist für Windows, Steam und Spiele der erste Controller. Mit ‹ › umsortieren."] =
            "プレイヤー順序 – プレイヤー 1 は Windows、Steam、ゲームで最初のコントローラーです。‹ › で並べ替えます。",
        ["Von der Switch-SD-Karte"] = "Switch の SD カードから",
        ["Mit Bluepick_RCM oder hekate erstellte Kopplungsdaten (switchroot/joycon_mac.ini)"] =
            "Bluepick_RCM または hekate で作成されたペアリングデータ（switchroot/joycon_mac.ini）",
        ["Einlesen …"] = "読み込む …",
        ["Von einem anderen PC"] = "別の PC から",
        ["Mit N-Connect exportierte Datei (*.ncpair)"] = "N-Connect でエクスポートされたファイル（*.ncpair）",
        ["Datei öffnen …"] = "ファイルを開く …",
        ["Inhalt"] = "内容",
        ["Weitergeben und sichern"] = "共有とバックアップ",
        ["Für einen anderen PC exportieren"] = "別の PC 用にエクスポート",
        ["Bekannte Controller und Einstellungen je Controller, optional mit Passwort"] =
            "既知のコントローラーとコントローラー別設定（パスワードは任意）",
        ["Sicherung wiederherstellen"] = "バックアップを復元",
        ["Vor jedem „Übernehmen“ wird automatisch eine Sicherung angelegt"] = "「適用」の前に自動でバックアップが作成されます",
        ["Wiederherstellen …"] = "復元 …",
        ["Bluetooth-Adapter dieses PCs"] = "この PC の Bluetooth アダプター",
        ["wird ermittelt …"] = "検出中 …",
        ["nicht gefunden"] = "見つかりません",
        ["Quelle wählen: Switch-SD-Karte (mit Bluepick_RCM oder hekate erstellte Kopplungsdaten) oder eine Datei von einem anderen PC."] =
            "ソースを選択：Switch の SD カード（Bluepick_RCM または hekate で作成されたペアリングデータ）または別の PC のファイル。",
        ["Keine Switch-SD-Karte gefunden. SD-Karte in den Kartenleser stecken oder die Switch per hekate („USB Tools“ → „SD Card“) als Laufwerk verbinden.\n\nOrdner selbst auswählen?"] =
            "Switch の SD カードが見つかりません。SD カードをカードリーダーに挿入するか、hekate（「USB Tools」→「SD Card」）で Switch をドライブとして接続してください。\n\nフォルダーを手動で選択しますか？",
        ["Stammordner der Switch-SD-Karte wählen"] = "Switch の SD カードのルートフォルダーを選択",
        ["Switch-SD-Karte:"] = "Switch の SD カード：",
        ["Auf der Karte liegen keine Kopplungsdaten (switchroot/joycon_mac.ini)."] = "カードにペアリングデータ（switchroot/joycon_mac.ini）がありません。",
        ["So erstellst du sie: Joy-Con an die Switch stecken, Bluepick_RCM starten und „Dump Joy-Con BT pairing → SD“ (oder FULL AUTO) wählen. Alternativ in hekate: Nyx → Konsole → „Dump Joy-Con BT“."] =
            "作成方法：Joy-Con を Switch に接続し、Bluepick_RCM を起動して「Dump Joy-Con BT pairing → SD」（または FULL AUTO）を選択。または hekate で：Nyx → Console →「Dump Joy-Con BT」。",
        ["Gefunden wurde eine Bluepick-Sicherung des Bluetooth-Speichers (8000000000000050.bin). Sie ist ein Switch-Speicherabbild und kann hier nicht ausgewertet werden."] =
            "Bluepick による Bluetooth メモリのバックアップ（8000000000000050.bin）が見つかりました。これは Switch のメモリイメージであり、ここでは解析できません。",
        ["Bluetooth-Adresse der Switch:"] = "Switch の Bluetooth アドレス：",
        ["Gefundene Controller:"] = "見つかったコントローラー：",
        ["mit der Switch gekoppelt"] = "Switch とペアリング済み",
        ["zuletzt mit einem anderen Gerät gekoppelt (nicht der Switch)"] = "最後に別のデバイスとペアリング（Switch ではない）",
        ["Joy-Con (L)"] = "Joy-Con（左）",
        ["Joy-Con (R)"] = "Joy-Con（右）",
        ["HORI-Controller (links)"] = "HORI コントローラー（左）",
        ["HORI-Controller (rechts)"] = "HORI コントローラー（右）",
        ["Hinweis: Pro Controller stehen nur im Bluetooth-Speicher der Switch (8000000000000050.bin); dieses Speicherabbild kann N-Connect nicht auswerten."] =
            "注意：Pro Controller は Switch の Bluetooth メモリ（8000000000000050.bin）にのみ記録されています。N-Connect はこのメモリイメージを解析できません。",
        ["Was diese Daten können – und was nicht:"] = "このデータでできること – できないこと：",
        ["Die Daten zeigen, welche Controller mit deiner Switch gekoppelt sind und an welche Bluetooth-Adresse sie gebunden sind."] =
            "データには、どのコントローラーが Switch とペアリングされているか、どの Bluetooth アドレスに紐付いているかが表示されます。",
        ["Ein Switch-1-Controller verbindet sich auf Tastendruck nur mit dem Gerät, dessen Adresse er gespeichert hat – hier mit der Switch. Der Bluetooth-Adapter des PCs hat eine andere Adresse, deshalb kann Windows diese Kopplung nicht einfach weiterverwenden."] =
            "Switch 1 コントローラーは、記憶したアドレスのデバイス（ここでは Switch）にのみボタン一つで再接続します。PC の Bluetooth アダプターは別のアドレスを持つため、Windows はこのペアリングをそのまま再利用できません。",
        ["Die Adresse des PC-Adapters zu ändern, unterstützt N-Connect bewusst nicht (herstellerabhängig, riskant und nicht vorgesehen)."] =
            "N-Connect は PC アダプターのアドレス変更を意図的にサポートしていません（メーカー依存、リスクあり、非推奨）。",
        ["Windows bietet keinen offiziellen Weg, fremde Kopplungsschlüssel einzutragen: Sie liegen in einem Teil der Registrierung, auf den nur das System zugreifen darf. N-Connect ändert dort nichts."] =
            "Windows には他デバイスのペアリングキーを登録する公式な方法はありません。レジストリのシステム専用領域に保存されるため、N-Connect はそこを変更しません。",
        ["So klappt der Wechsel am einfachsten: am PC den Controller einmal per SYNC-Taste in den Windows-Bluetooth-Einstellungen koppeln. Zurück an der Switch die Joy-Con an die Konsole stecken bzw. den Pro Controller per USB-Kabel anschließen – dann sind sie ohne Menü wieder mit der Switch gekoppelt."] =
            "最も簡単な切り替え方法：PC で Windows の Bluetooth 設定から SYNC ボタンで一度ペアリング。Switch に戻ったら Joy-Con を本体に取り付けるか、Pro Controller を USB ケーブルで接続 – メニューなしで再度ペアリングされます。",
        ["„Übernehmen“ merkt sich diese Controller in N-Connect (Liste bekannter Controller, Zuordnung zur Switch). Kopplungsschlüssel werden nicht gespeichert."] =
            "「適用」はこれらのコントローラーを N-Connect に記憶します（既知のコントローラーリスト、Switch への関連付け）。ペアリングキーは保存されません。",
        ["N-Connect-Kopplungsdaten"] = "N-Connect ペアリングデータ",
        ["Kopplungsdaten von einem anderen PC öffnen"] = "別の PC のペアリングデータを開く",
        ["Die Datei ist zu groß."] = "ファイルが大きすぎます。",
        ["Keine Kopplungsdaten-Datei."] = "ペアリングデータファイルではありません。",
        ["Die Datei stammt von einer neueren N-Connect-Version."] = "ファイルは新しいバージョンの N-Connect で作成されています。",
        ["Die Datei ist mit einem Passwort geschützt."] = "ファイルはパスワードで保護されています。",
        ["Falsches Passwort oder die Datei wurde verändert."] = "パスワードが間違っているか、ファイルが変更されています。",
        ["Die Datei ist beschädigt."] = "ファイルが破損しています。",
        ["Datei von:"] = "ファイルの送信元：",
        ["Bluetooth-Adapter dort:"] = "送信元の Bluetooth アダプター：",
        ["Bluetooth-Adapter hier:"] = "この PC の Bluetooth アダプター：",
        ["gekoppelt mit der Switch"] = "Switch とペアリング済み",
        ["gekoppelt mit dem anderen PC"] = "別の PC とペアリング済み",
        ["Weitere Einstellungen je Controller:"] = "コントローラー別のその他の設定：",
        ["Was du erwarten kannst:"] = "期待できること：",
        ["Gleiche Adapter-Adresse (z. B. derselbe USB-Bluetooth-Stick umgesteckt): Switch-2-Controller verbinden sich hier auf Tastendruck wie am anderen PC."] =
            "同じアダプターアドレス（例：同じ USB Bluetooth ドングルを差し替え）：Switch 2 コントローラーはここでもボタン一つで接続します。",
        ["Switch-1-Controller (Pro Controller, Joy-Con) brauchen zusätzlich die Kopplung in Windows. Die kann N-Connect nicht übertragen – einmal per SYNC-Taste koppeln."] =
            "Switch 1 コントローラー（Pro Controller、Joy-Con）は追加で Windows でのペアリングが必要です。N-Connect はこれを転送できません – SYNC ボタンで一度ペアリングしてください。",
        ["Anderer Bluetooth-Adapter: Controller verbinden sich auf Tastendruck nur mit dem Gerät, mit dem sie zuletzt gekoppelt wurden. Hier einmal SYNC drücken – danach verbinden sie sich mit diesem PC (am anderen PC dann wieder per SYNC)."] =
            "別の Bluetooth アダプターの場合：コントローラーは最後にペアリングしたデバイスにのみボタン一つで再接続します。ここで一度 SYNC を押す – その後この PC に接続します（もう一方の PC では再度 SYNC）。",
        ["Tipp: Wer denselben USB-Bluetooth-Stick zwischen den PCs umsteckt, nimmt die Adresse mit – Switch-2-Controller verbinden sich dann an beiden PCs ohne SYNC."] =
            "ヒント：同じ USB Bluetooth ドングルを PC 間で差し替えるとアドレスも移動します – Switch 2 コントローラーは両方の PC で SYNC なしで接続します。",
        ["Übernommen werden die Einstellungen je Controller (Joy-Con einzeln/hochkant, Gyro-Kalibrierung) und die Liste bekannter Controller."] =
            "引き継がれるのはコントローラー別設定（Joy-Con の単体/縦向き、ジャイロキャリブレーション）と既知のコントローラーリストです。",
        ["Die Datei enthält Kopplungsschlüssel. Windows bietet keinen offiziellen Weg, sie einzutragen – N-Connect übernimmt sie deshalb nicht."] =
            "ファイルにペアリングキーが含まれています。Windows には公式な登録方法がないため、N-Connect はそれらを引き継ぎません。",
        ["„Übernehmen“ ergänzt die Controller-Listen und Einstellungen von N-Connect (nichts wird gelöscht). Vorher wird eine Sicherung angelegt."] =
            "「適用」は N-Connect のコントローラーリストと設定を追加します（何も削除されません）。事前にバックアップが作成されます。",
        ["Kopplungsdaten in N-Connect übernehmen? Vorher wird eine Sicherung der Einstellungen angelegt."] =
            "ペアリングデータを N-Connect に引き継ぎますか？事前に設定のバックアップが作成されます。",
        ["Nichts zu ändern – diese Daten sind schon übernommen."] = "変更するものはありません – このデータはすでに引き継がれています。",
        ["Übernommen. Die Sicherung lässt sich hier über „Sicherung wiederherstellen“ zurückholen."] =
            "完了。「バックアップを復元」でここから復元できます。",
        ["Sicherung der Einstellungen"] = "設定のバックアップ",
        ["Die Sicherung ist beschädigt und wurde nicht übernommen."] = "バックアップが破損しており、適用されませんでした。",
        ["Alle Einstellungen durch diese Sicherung ersetzen?"] = "すべての設定をこのバックアップで置き換えますか？",
        ["Sicherung wiederhergestellt."] = "バックアップを復元しました。",
        ["Kopplungsdaten für einen anderen PC speichern"] = "別の PC 用にペアリングデータを保存",
        ["Gespeichert. Die Datei am anderen PC in N-Connect unter „Joy-Con & Wii“ → „Kopplungsdaten“ → „Von einem anderen PC“ öffnen."] =
            "保存しました。別の PC で N-Connect の「Joy-Con と Wii」→「ペアリングデータ」→「別の PC から」からファイルを開いてください。",
        ["Kopplungsdaten exportieren"] = "ペアリングデータをエクスポート",
        ["Passwort eingeben"] = "パスワードを入力",
        ["Passwort (optional). Ohne Passwort steht der Inhalt lesbar in der Datei. Mit Kopplungsschlüsseln ist ein Passwort Pflicht."] =
            "パスワード（任意）。パスワードなしでは内容がファイルに平文で保存されます。ペアリングキーを含める場合はパスワードが必須です。",
        ["Passwort"] = "パスワード",
        ["Passwort wiederholen"] = "パスワード（確認）",
        ["Kopplungsschlüssel der Switch-Controller mitnehmen"] = "Switch コントローラーのペアリングキーを含める",
        ["Kopplungsschlüssel mitnehmen (erst Switch-SD-Karte einlesen)"] = "ペアリングキーを含める（先に Switch の SD カードを読み込んでください）",
        ["Die Passwörter stimmen nicht überein."] = "パスワードが一致しません。",
        ["Mit Schlüsseln: Passwort mit mindestens 8 Zeichen."] = "キーあり：パスワードは 8 文字以上必要です。",
        ["Mindestens 8 Zeichen."] = "8 文字以上必要です。",
        ["Ohne Passwort."] = "パスワードなし。",
    };

    /// <summary>Meldungen mit Platzhaltern (Japanisch).</summary>
    private static readonly (Regex Pattern, Func<Match, string> Replace)[] PatternsJa =
    [
        (Re(@"^Allgemeiner Wert \((?<v>.+)\) – Regler verschieben für einen eigenen$"), m => $"全体の値（{m.Groups["v"]}）– スライダーを動かすと個別値になります"),
        (Re(@"^Eigener Wert · allgemein: (?<v>.+)$"), m => $"個別値 · 全体：{m.Groups["v"]}"),
        (Re(@"^Spieler (?<n>\d+)  ·  (?<k>.+?)(?<rest>(  ·  .*)?)$"), m => $"プレイヤー {m.Groups["n"]}  ·  {N(m, "k")}{T(m.Groups["rest"].Value)}"),
        (Re(@"^  ·  Gyro-Maus(?<r>.*)$"), m => "  ·  ジャイロマウス" + T(m.Groups["r"].Value)),
        (Re(@"^  ·  Gyro-Stick$"), _ => "  ·  ジャイロスティック"),
        (Re(@"^Spieler (?<n>\d+) · (?<k>.+?) (?<b>\d+ %.*)?$"), m => $"プレイヤー {m.Groups["n"]} · {N(m, "k")} {m.Groups["b"]}"),
        (Re(@"^(?<k>.+) verbunden \(Spieler (?<n>\d+)\)$"), m => $"{N(m, "k")} が接続されました（プレイヤー {m.Groups["n"]}）"),
        (Re(@"^Spieler (?<n>\d+) – tauschen mit (?<k>.+)$"), m => $"プレイヤー {m.Groups["n"]} – {N(m, "k")} と入れ替え"),
        (Re(@"^Spieler (?<n>\d+) – frei$"), m => $"プレイヤー {m.Groups["n"]} – 空き"),
        (Re(@"^Spieler (?<n>\d+)$"), m => $"プレイヤー {m.Groups["n"]}"),
        (Re(@"^Xbox 360 · Platz (?<n>\d+)$"), m => $"Xbox 360 · スロット {m.Groups["n"]}"),
        (Re(@"^noch (?<n>\d+) s$"), m => $"残り {m.Groups["n"]} 秒"),
        (Re(@"^Fertig – (?<n>\d+) Controller verbunden$"), m => $"完了 – {m.Groups["n"]} 台のコントローラーが接続されました"),
        (Re(@"^✓ (?<k>.+) verbunden – Spieler (?<n>\d+)$"), m => $"✓ {N(m, "k")} が接続されました – プレイヤー {m.Groups["n"]}"),
        (Re(@"^Spieler (?<n>\d+)  ·  (?<v>.+)$"), m => $"プレイヤー {m.Groups["n"]}  ·  {m.Groups["v"]}"),
        (Re(@"^Gekoppelt: (?<k>.+) – verbindet gleich …$"), m => $"ペアリング済み：{m.Groups["k"]} – 接続中 …"),
        (Re(@"^Ins Spiel wechseln … (?<n>\d+)$"), m => $"ゲームに切り替え … {m.Groups["n"]}"),
        (Re(@"^(?<k>.+) ist jetzt Spieler (?<n>\d+)$"), m => $"{N(m, "k")} はプレイヤー {m.Groups["n"]} になりました"),
        (Re(@"^Spieler (?<a>\d+) und (?<b>\d+) getauscht$"), m => $"プレイヤー {m.Groups["a"]} と {m.Groups["b"]} を入れ替えました"),
        (Re(@"^Name für (?<k>.+) \(leer = Standardname\):$"), m => $"{N(m, "k")} の名前（空欄 = デフォルト名）："),
        (Re(@"^(?<k>.+) \(Joy-Con-Paar\)$"), m => $"{m.Groups["k"]}（Joy-Con ペア）"),
        (Re(@"^Joy-Con zusammengefasst \(Spieler (?<n>\d+)\)$"), m => $"Joy-Con をまとめました（プレイヤー {m.Groups["n"]}）"),
        (Re(@"^Joy-Con getrennt – (?<k>.+) ist jetzt Spieler (?<n>\d+)$"), m => $"Joy-Con を分離 – {N(m, "k")} はプレイヤー {m.Groups["n"]} になりました"),
        (Re(@"^Spieler (?<n>\d+): Akku (?<k>.+) fast leer \((?<p>\d+) %\) – bitte aufladen$"),
            m => $"プレイヤー {m.Groups["n"]}：{N(m, "k")} のバッテリーが残りわずか（{m.Groups["p"]} %）– 充電してください"),
        (Re(@"^Spieler (?<n>\d+): nach (?<m>\d+) min ohne Eingabe getrennt$"),
            m => $"プレイヤー {m.Groups["n"]}：{m.Groups["m"]} 分間操作がなかったため切断しました"),
        (Re(@"^Profil „(?<p>.+)“ aktiv$"), m => $"プロファイル「{ProfileName(m.Groups["p"].Value)}」が有効です"),
        (Re(@"^Profil: (?<p>.+)$"), m => $"プロファイル：{ProfileName(m.Groups["p"].Value)}"),
        (Re(@"^Profil „(?<p>.+)“ löschen\?$"), m => $"プロファイル「{m.Groups["p"]}」を削除しますか？"),
        (Re(@"^Profil „(?<p>.+)“ importiert(?<r>.*)$"), m => $"プロファイル「{m.Groups["p"]}」をインポートしました" + m.Groups["r"].Value.Replace("aktiv bei:", "有効なプログラム：")),
        (Re(@"^⬇ Neue Version (?<v>.+) herunterladen …$"), m => $"⬇ 新しいバージョン {m.Groups["v"]} をダウンロード …"),
        (Re(@"^Version (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Herunterladen\.$"),
            m => $"バージョン {m.Groups["v"]} が公開されました（インストール済み：{m.Groups["i"]}）。クリックでダウンロード。"),
        (Re(@"^Version (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Installieren\.$"),
            m => $"バージョン {m.Groups["v"]} が公開されました（インストール済み：{m.Groups["i"]}）。クリックでインストール。"),
        (Re(@"^⬇ Auf Version (?<v>.+) aktualisieren …$"), m => $"⬇ バージョン {m.Groups["v"]} に更新 …"),
        (Re(@"^Lade Version (?<v>.+) herunter …$"), m => $"バージョン {m.Groups["v"]} をダウンロード中 …"),
        (Re(@"^HidHide (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Installieren\.$"),
            m => $"HidHide {m.Groups["v"]} が公開されました（インストール済み：{m.Groups["i"]}）。クリックでインストール。"),
        (Re(@"^Lade HidHide (?<v>.+) herunter …$"), m => $"HidHide {m.Groups["v"]} をダウンロード中 …"),
        (Re(@"^(?<t>.+) · (?<r>\d+) Berichte/s$"), m => $"{T(m.Groups["t"].Value)} · {m.Groups["r"]} レポート/秒"),
        (Re(@"^(?<p>\d+ %)(?<v>  \(.*\))?  ⚡ lädt$"), m => $"{m.Groups["p"]}{m.Groups["v"]}  ⚡ 充電中"),
        (Re(@"^Speichern fehlgeschlagen: (?<e>.*)$"), m => $"保存に失敗しました：{m.Groups["e"]}"),
        (Re(@"^Lesen fehlgeschlagen: (?<e>.*)$"), m => $"読み取りに失敗しました：{m.Groups["e"]}"),
        (Re(@"^amiibo konnte nicht gelesen werden: (?<e>.*)$"), m => $"amiibo を読み取れませんでした：{T(m.Groups["e"].Value)}"),
        (Re(@"^Gekoppelt: (?<k>.+)$"), m => $"ペアリング済み：{m.Groups["k"]}"),
        (Re(@"^Gefunden: (?<k>.+) – kopple …$"), m => $"検出：{m.Groups["k"]} – ペアリング中 …"),
        (Re(@"^amiibo erkannt \((?<u>.+)\) – lese …$"), m => $"amiibo を検出（{m.Groups["u"]}）– 読み取り中 …"),
        (Re(@"^(?<n>\d+) Minuten$"), m => $"{m.Groups["n"]} 分"),
        (Re(@"^✓ (?<n>\d+) Schritte, Dauer (?<ms>\d+) ms$"), m => $"✓ {m.Groups["n"]} ステップ、合計 {m.Groups["ms"]} ms"),
        (Re(@"^Controller-Taste „(?<b>.+)“:\nJetzt die gewünschte Taste oder Tastenkombination drücken\.$"),
            m => $"コントローラーボタン「{T(m.Groups["b"].Value)}」：\n使用するキーまたはキーの組み合わせを押してください。"),
        (Re(@"^Solange „(?<b>.+)“ gehalten wird, wird diese Taste schnell wiederholt gedrückt\n\(Geschwindigkeit unter 5\. „Turbo“\):$"),
            m => $"「{T(m.Groups["b"].Value)}」を押している間、このボタンが高速で繰り返されます\n（速度は 5.「ターボ」で設定）："),
        (Re(@"^Ring-Con: (?<e>.*)$"), m => $"Ring-Con：{T(m.Groups["e"].Value)}"),
        (Re(@"^⌨  Taste: (?<k>.+)$"), m => $"⌨  キー：{m.Groups["k"]}"),
        (Re(@"^🔁  Turbo: Taste (?<k>.+)$"), m => $"🔁  ターボ：キー {m.Groups["k"]}"),
        (Re(@"^🔁  Turbo: (?<k>.+)$"), m => $"🔁  ターボ：{T(m.Groups["k"].Value)}"),
        (Re(@"^⏯  Makro: (?<k>.+)$"), m => $"⏯  マクロ：{m.Groups["k"]}"),
        (Re(@"^Tastatur: (?<k>.+)$"), m => $"キーボード：{m.Groups["k"]}"),
        (Re(@"^Gamepad: (?<k>.+)$"), m => $"ゲームパッド：{m.Groups["k"]}"),
        (Re(@"^(?<k>.+)  \(verbunden\)$"), m => $"{N(m, "k")}（接続済み）"),
        (Re(@"^Bluetooth nicht verfügbar: (?<e>.*)$"), m => $"Bluetooth を利用できません：{m.Groups["e"]}"),
        (Re(@"^(?<k>.+) per USB ist von einem anderen Programm belegt \(z\. B\. Steam\)\.$"),
            m => $"{N(m, "k")} の USB は別のプログラム（例：Steam）が使用中です。"),
        (Re(@"^Schon (?<n>\d+) Controller verbunden – (?<k>.+) wird nicht verwendet\.$"),
            m => $"すでに {m.Groups["n"]} 台接続済み – {N(m, "k")} は使用されません。"),
        (Re(@"^(?<k>.+): schwache Bluetooth-Verbindung \((?<r>\d+) statt 33–60 Berichte/s\)\.$"),
            m => $"{N(m, "k")}：Bluetooth 接続が弱い（33–60 のところ {m.Groups["r"]} レポート/秒）。"),
        (Re(@"^(?<k>.+) getrennt$"), m => $"{N(m, "k")} が切断されました"),
    ];
}
