using System.Text.RegularExpressions;

namespace Switch2Pro.Bridge;

/// <summary>Feste Texte Deutsch → Italienisch. Schlüssel bleiben die deutschen Originaltexte.</summary>
internal static partial class Tr
{
    private static readonly Dictionary<string, string> TextsIt = new(StringComparer.Ordinal)
    {
        // ---------- Fenster, Reiter, Abschnitte ----------
        ["Controller"] = "Controller",
        ["Einstellungen (optional)"] = "Impostazioni (facoltative)",
        ["1. Windows und Spiele sehen den Controller als …"] = "1. Windows e i giochi vedono il controller come …",
        ["2. Tasten A/B/X/Y"] = "2. Pulsanti A/B/X/Y",
        ["3. Vibration, Sticks, Verbinden, Gyro-Maus"] = "3. Vibrazione, stick, connessione, mouse giroscopico",
        ["4. Joy-Con"] = "4. Joy-Con",
        ["4. Joy-Con und Wii"] = "4. Joy-Con e Wii",
        ["Wii-Fernbedienung: Zeiger (Sensorleiste) steuert die Maus"] = "Telecomando Wii: il puntatore (barra sensori) muove il mouse",
        ["Zeiger"] = "Puntatore",
        ["kein Zeiger – Sensorleiste nicht im Blick"] = "nessun puntatore – barra sensori non in vista",
        ["5. Zielen, Sticks, Trigger, Turbo"] = "5. Mira, stick, grilletti, turbo",
        ["6. Tastenbelegung und Profile  (Taste → Gamepad, Tastatur, Maus, Gyro-Maus, Shift-Ebene)"] =
            "6. Assegnazione dei pulsanti e profili  (pulsante → gamepad, tastiera, mouse, mouse giroscopico, livello Shift)",
        ["Xbox-360-Controller  (empfohlen – läuft mit fast allen Spielen)"] = "Controller Xbox 360  (consigliato – funziona con quasi tutti i giochi)",
        ["PlayStation DualShock 4  (mit Bewegungssteuerung/Gyro – für Steam && Emulatoren)"] =
            "PlayStation DualShock 4  (con controllo del movimento/giroscopio – per Steam ed emulatori)",
        ["Xbox-Belegung  (nach Position: untere Taste = A)"] = "Disposizione Xbox  (per posizione: pulsante in basso = A)",
        ["Nintendo-Belegung  (nach Beschriftung: A bleibt A)"] = "Disposizione Nintendo  (per etichetta: A resta A)",
        ["Vibration"] = "Vibrazione",
        ["Stärke:"] = "Intensità :",
        ["Stick-Totzone (alle Controller):"] = "Zona morta dello stick (tutti i controller) :",
        ["Beim Verbinden kurz vibrieren"] = "Vibra brevemente alla connessione",
        ["Gekoppelte Controller per Tastendruck verbinden (ohne SYNC)"] = "Connetti i controller associati con la pressione di un pulsante (senza SYNC)",
        ["Automatisch mit Windows starten"] = "Avvia automaticamente con Windows",
        ["Gyro für Emulatoren bereitstellen (Cemuhook/DSU, Port 26760 – wirkt nach Neustart)"] =
            "Fornisci il giroscopio agli emulatori (Cemuhook/DSU, porta 26760 – attivo dopo il riavvio)",
        ["Beim Start nach neuer Version suchen (GitHub)"] = "Cerca una nuova versione all'avvio (GitHub)",
        ["Ohne Eingabe automatisch trennen nach:"] = "Disconnetti automaticamente senza input dopo :",
        ["Gyro-Maus-Geschwindigkeit:"] = "Velocità del mouse giroscopico :",
        ["Sprache / Language:"] = "Lingua / Language :",
        ["Automatisch (wie Windows)"] = "Automatica (come Windows)",
        ["nie"] = "mai",
        ["Zwei Joy-Con automatisch zu einem Controller zusammenfassen"] = "Unisci automaticamente due Joy-Con in un solo controller",
        ["Gyro beim Paar vom:"] = "Giroscopio della coppia da :",
        ["rechter Joy-Con (wie Switch)"] = "Joy-Con destro (come su Switch)",
        ["linker Joy-Con"] = "Joy-Con sinistro",
        ["Joy-Con 2 als Maus, wenn er auf dem Tisch liegt"] = "Joy-Con 2 come mouse quando è sul tavolo",
        ["Mausgeschwindigkeit:"] = "Velocità del mouse :",
        ["Maus: links/rechts umkehren"] = "Mouse: inverti sinistra/destra",
        ["Maus: hoch/runter umkehren"] = "Mouse: inverti su/giù",
        ["Wie an der Switch: SL + SR eine Sekunde halten löst einen Joy-Con aus dem Paar. L am linken und R am rechten einzelnen Joy-Con gleichzeitig drücken verbindet sie wieder zum Paar. Die Wahl wird je Joy-Con gemerkt (auch nach dem nächsten Verbinden). Im Mausmodus: R/L = Linksklick, ZR/ZL = Rechtsklick, Stick drücken = Mittelklick, Stick hoch/runter = Scrollen."] =
            "Come su Switch: tenere SL + SR per un secondo stacca un Joy-Con dalla coppia. Premendo L sul sinistro e R sul destro insieme si riuniscono. La scelta è memorizzata per ogni Joy-Con (anche alla prossima connessione). In modalità mouse: R/L = clic sinistro, ZR/ZL = clic destro, premere lo stick = clic centrale, stick su/giù = scorrimento.",
        ["Gyro als rechter Stick:"] = "Giroscopio come stick destro :",
        ["aus (nur per Taste „Gyro-Stick“)"] = "disattivato (solo con un pulsante « stick giroscopico »)",
        ["immer"] = "sempre",
        ["beim Zielen (solange ZL / linker Trigger gedrückt)"] = "in mira (finché ZL / grilletto sinistro è premuto)",
        ["hoch/runter umkehren"] = "inverti su/giù",
        ["Empfindlichkeit:"] = "Sensibilità :",
        ["Mindestausschlag:"] = "Deflessione minima :",
        ["Stick-Kennlinie:"] = "Curva dello stick :",
        ["Turbo (pro Sekunde):"] = "Turbo (al secondo) :",
        ["Analoge Trigger (GameCube) – Totzone:"] = "Grilletti analogici (GameCube) – zona morta :",
        ["voll gedrückt ab:"] = "premuto a fondo da :",
        ["Profil:"] = "Profilo :",
        ["Neu …"] = "Nuovo …",
        ["Umbenennen …"] = "Rinomina …",
        ["Löschen"] = "Elimina",
        ["Exportieren …"] = "Esporta …",
        ["Importieren …"] = "Importa …",
        ["Aktiv bei Programm:"] = "Attivo con il programma :",
        ["Programm wählen …"] = "Scegli un programma …",
        ["Standard"] = "Predefinito",
        ["Standard gilt immer, wenn kein anderes Profil passt"] = "Il predefinito vale quando nessun altro profilo è adatto",
        ["z. B. Cemu.exe, Ryujinx.exe"] = "es. Cemu.exe, Ryujinx.exe",
        ["Ein eigenes Profil wird automatisch aktiv, solange eines seiner Programme im Vordergrund ist (sonst gilt „Standard“). Im Infobereich-Menü lässt sich ein Profil auch fest wählen."] =
            "Un profilo personalizzato si attiva automaticamente finché uno dei suoi programmi è in primo piano (altrimenti vale « Predefinito »). Un profilo si può anche fissare nel menu dell'area di notifica.",
        ["Controller:"] = "Controller :",
        ["Eigene Stick-Totzone für diesen Controller:"] = "Zona morta dello stick propria per questo controller :",
        ["Normale Belegung"] = "Assegnazione normale",
        ["Shift-Ebene (gilt, solange eine Taste mit „Shift-Ebene“ gehalten wird)"] = "Livello Shift (vale finché un pulsante « livello Shift » è tenuto premuto)",
        ["Alles auf Standard"] = "Ripristina tutto",
        ["Schließen"] = "Chiudi",
        ["wie normale Belegung"] = "come l'assegnazione normale",

        // ---------- Belegungsziele und Vorlagen ----------
        ["— keine Funktion —"] = "— nessuna funzione —",
        ["A (Xbox) / Kreuz (PS)"] = "A (Xbox) / Croce (PS)",
        ["B (Xbox) / Kreis (PS)"] = "B (Xbox) / Cerchio (PS)",
        ["X (Xbox) / Viereck (PS)"] = "X (Xbox) / Quadrato (PS)",
        ["Y (Xbox) / Dreieck (PS)"] = "Y (Xbox) / Triangolo (PS)",
        ["Ansicht (Back) / Share"] = "Visualizza (Back) / Share",
        ["Menü (Start) / Options"] = "Menu (Start) / Options",
        ["Xbox-Taste / PS-Taste"] = "Pulsante Xbox / pulsante PS",
        ["Linker Stick-Klick"] = "Clic dello stick sinistro",
        ["Rechter Stick-Klick"] = "Clic dello stick destro",
        ["Steuerkreuz hoch"] = "Croce direzionale su",
        ["Steuerkreuz runter"] = "Croce direzionale giù",
        ["Steuerkreuz links"] = "Croce direzionale sinistra",
        ["Steuerkreuz rechts"] = "Croce direzionale destra",
        ["Touchpad-Klick (nur DualShock 4)"] = "Clic del touchpad (solo DualShock 4)",
        ["🖱  Maus: Linksklick"] = "🖱  Mouse: clic sinistro",
        ["🖱  Maus: Rechtsklick"] = "🖱  Mouse: clic destro",
        ["🖱  Maus: Mittelklick"] = "🖱  Mouse: clic centrale",
        ["🎯  Gyro-Maus (solange gehalten)"] = "🎯  Mouse giroscopico (finché premuto)",
        ["🎯  Gyro-Maus ein/aus"] = "🎯  Mouse giroscopico attiva/disattiva",
        ["🎯  Gyro als rechter Stick (solange gehalten)"] = "🎯  Giroscopio come stick destro (finché premuto)",
        ["🎯  Gyro als rechter Stick ein/aus"] = "🎯  Giroscopio come stick destro attiva/disattiva",
        ["⇧  Shift-Ebene (solange gehalten)"] = "⇧  Livello Shift (finché premuto)",
        ["🔁  Turbo / Dauerfeuer …"] = "🔁  Turbo / fuoco rapido …",
        ["⏯  Makro (Tastenfolge) …"] = "⏯  Macro (sequenza di tasti) …",
        ["📷  Bildschirmfoto speichern (Win+Druck)"] = "📷  Salva screenshot (Win+Stamp)",
        ["📷  Bildschirmausschnitt (Win+Umschalt+S)"] = "📷  Cattura parziale (Win+Maiusc+S)",
        ["⏺  Letzte 30 Sekunden aufnehmen (Win+Alt+G)"] = "⏺  Registra gli ultimi 30 secondi (Win+Alt+G)",
        ["⏺  Aufnahme starten/stoppen (Win+Alt+R)"] = "⏺  Avvia/interrompi registrazione (Win+Alt+R)",
        ["🎮  Xbox Game Bar (Win+G)"] = "🎮  Xbox Game Bar (Win+G)",
        ["🔊  Lauter"] = "🔊  Alza volume",
        ["🔉  Leiser"] = "🔉  Abbassa volume",
        ["⏯  Wiedergabe/Pause"] = "⏯  Riproduci/Pausa",
        ["⌨  Andere Taste / Tastenkombination aufnehmen …"] = "⌨  Registra un altro tasto / combinazione di tasti …",

        // ---------- Tastennamen ----------
        ["+ (Plus)"] = "+ (Plus)",
        ["− (Minus)"] = "− (Meno)",
        ["Aufnahme"] = "Cattura",
        ["GL (Rücktaste links)"] = "GL (pulsante posteriore sinistro)",
        ["GR (Rücktaste rechts)"] = "GR (pulsante posteriore destro)",
        ["Linker Stick drücken"] = "Premi stick sinistro",
        ["Rechter Stick drücken"] = "Premi stick destro",
        ["Stick drücken"] = "Premi stick",
        ["A (groß, unten)"] = "A (grande, in basso)",
        ["B (links)"] = "B (sinistra)",
        ["X (rechts)"] = "X (destra)",
        ["Y (oben)"] = "Y (in alto)",
        ["L (ganz durchgedrückt)"] = "L (premuto a fondo)",
        ["R (ganz durchgedrückt)"] = "R (premuto a fondo)",
        ["untere Taste (quer)"] = "pulsante in basso (orizzontale)",
        ["rechte Taste (quer)"] = "pulsante destro (orizzontale)",
        ["linke Taste (quer)"] = "pulsante sinistro (orizzontale)",
        ["obere Taste (quer)"] = "pulsante in alto (orizzontale)",
        ["1 (quer) / Classic Y"] = "1 (orizzontale) / Classic Y",
        ["2 (quer) / Classic B"] = "2 (orizzontale) / Classic B",
        ["B (Abzug) / Classic ZR"] = "B (grilletto) / Classic ZR",
        ["Kreuz (unten)"] = "Croce (in basso)",
        ["Kreis (rechts)"] = "Cerchio (a destra)",
        ["Viereck (links)"] = "Quadrato (a sinistra)",
        ["Dreieck (oben)"] = "Triangolo (in alto)",
        ["PS-Taste"] = "Pulsante PS",
        ["Touchpad-Klick"] = "Clic del touchpad",
        ["Mikro stumm"] = "Microfono muto",
        ["Fn links (Edge)"] = "Fn sinistro (Edge)",
        ["Rücktaste links (Edge)"] = "Pulsante posteriore sinistro (Edge)",
        ["Rücktaste rechts (Edge)"] = "Pulsante posteriore destro (Edge)",
        ["L3 (Stick drücken)"] = "L3 (premere lo stick)",
        ["R3 (Stick drücken)"] = "R3 (premere lo stick)",
        ["Ansicht/Zurück"] = "Visualizza/Indietro",
        ["Menü/Start"] = "Menu/Start",
        ["Xbox-Taste"] = "Pulsante Xbox",

        // ---------- Controller-Namen ----------
        ["Wii-Fernbedienung"] = "Telecomando Wii",
        ["Xbox-Controller"] = "Controller Xbox",
        ["Xbox-Controller (Microsoft)"] = "Controller Xbox (Microsoft)",
        ["XInput (USB, Bluetooth oder Xbox-Adapter)"] = "XInput (USB, Bluetooth o adattatore Xbox)",

        // ---------- Übersicht / Karten ----------
        ["Trennen"] = "Disconnetti",
        ["Vibrieren"] = "Vibra",
        ["Gyro kalibrieren"] = "Calibra il giroscopio",
        ["Ruhig liegen lassen …"] = "Lascia immobile …",
        ["Kalibriert ✓"] = "Calibrato ✓",
        ["Hochkant halten"] = "Tieni in verticale",
        ["Quer halten"] = "Tieni orizzontale",
        ["Joy-Con trennen"] = "Separa i Joy-Con",
        ["Zum Paar verbinden"] = "Unisci in coppia",
        ["Doppelt angezeigt? Verstecken"] = "Visualizzato due volte? Nascondi",
        ["amiibo lesen"] = "Leggi amiibo",
        ["Ring-Con ein"] = "Attiva Ring-Con",
        ["Ring-Con aus"] = "Disattiva Ring-Con",
        ["Ring-Con wird gesucht …"] = "Ricerca del Ring-Con …",
        ["IR-Kamera"] = "Fotocamera IR",
        ["Akku"] = "Batteria",
        ["Verbindung"] = "Connessione",
        ["Adresse"] = "Indirizzo",
        ["Seriennummer"] = "Numero di serie",
        ["Griff"] = "Impugnatura",
        ["Maus"] = "Mouse",
        ["Gedrückt"] = "Premuto",
        ["unbekannt"] = "sconosciuto",
        ["Charging Grip – GL/GR aktiv"] = "Charging Grip – GL/GR attivi",
        ["aktiv (liegt auf dem Tisch)"] = "attivo (appoggiato sul tavolo)",
        ["bereit – zum Benutzen auf den Tisch legen"] = "pronto – appoggialo sul tavolo per usarlo",
        ["Bewegungssensor: keine Daten"] = "Sensore di movimento: nessun dato",
        ["quer halten: Steuerkreuz links,\n1 und 2 rechts"] = "orizzontale: croce direzionale a sinistra,\n1 e 2 a destra",

        // ---------- Tooltips ----------
        ["Verbindung trennen. Der Controller verbindet sich beim nächsten Tastendruck wieder."] =
            "Disconnetti. Il controller si riconnette alla prossima pressione di un pulsante.",
        ["Controller kurz vibrieren lassen – zeigt, welcher Controller dieser Spieler ist."] =
            "Fa vibrare brevemente il controller – mostra quale controller appartiene a questo giocatore.",
        ["Controller ruhig auf den Tisch legen und klicken: misst den Gyro-Nullpunkt neu (gegen Abdriften)."] =
            "Appoggia il controller sul tavolo e clicca: misura di nuovo il punto zero del giroscopio (contro la deriva).",
        ["Einzelnen Joy-Con quer (wie an der Switch) oder hochkant halten – wird je Joy-Con gemerkt. Hochkant gilt die Tastenbelegung von „Joy-Con-Paar“."] =
            "Tieni il Joy-Con singolo orizzontale (come su Switch) o verticale – memorizzato per ogni Joy-Con. In verticale vale l'assegnazione « coppia Joy-Con ».",
        ["Versteckt den per USB angeschlossenen Controller vor Spielen (HidHide), damit sie nur den virtuellen Xbox-Controller sehen."] =
            "Nasconde ai giochi il controller collegato via USB (HidHide), così vedono solo il controller Xbox virtuale.",
        ["amiibo mit dem NFC-Leser lesen und als Datei (.bin) speichern – z. B. für Emulatoren."] =
            "Leggi un amiibo con il lettore NFC e salvalo come file (.bin) – ad es. per gli emulatori.",
        ["Ring-Con am rechten Joy-Con ein-/ausschalten: zusammendrücken = rechter Trigger, auseinanderziehen = linker Trigger. Beim Einschalten den Ring nicht berühren."] =
            "Attiva/disattiva il Ring-Con del Joy-Con destro: premere = grilletto destro, allargare = grilletto sinistro. Non toccare l'anello durante l'attivazione.",
        ["Live-Bild der IR-Kamera im rechten Joy-Con anzeigen."] = "Mostra l'immagine in diretta della fotocamera IR del Joy-Con destro.",
        ["Links = empfindlicher (kleine Drehung, großer Ausschlag), rechts = ruhiger."] = "Sinistra = più sensibile (piccola rotazione, grande deflessione), destra = più calmo.",
        ["Mindestausschlag des Sticks bei Bewegung – überwindet die Totzone des Spiels."] = "Deflessione minima dello stick in movimento – supera la zona morta del gioco.",
        ["Mitte = linear. Rechts = feiner um die Mitte (präzises Zielen), links = schneller."] = "Centro = lineare. Destra = più fine al centro (mira precisa), sinistra = più veloce.",
        ["So weit lässt sich ein analoger Trigger drücken, bevor er wirkt."] = "Quanto può essere premuto un grilletto analogico prima che agisca.",
        ["Ab hier gilt der Trigger als ganz gedrückt (100 = erst am Anschlag)."] = "Da qui il grilletto conta come premuto a fondo (100 = solo a fine corsa).",
        ["Wie oft pro Sekunde Tasten mit „Turbo“ auslösen."] = "Quante volte al secondo si attivano i pulsanti « turbo ».",

        // ---------- Infobereich ----------
        ["ViGEmBus-Treiber fehlt"] = "Driver ViGEmBus mancante",
        ["ViGEmBus herunterladen …"] = "Scarica ViGEmBus …",
        ["Verbinde …"] = "Connessione …",
        ["Kein Controller – SYNC-Taste am Controller kurz drücken"] = "Nessun controller – premi brevemente il pulsante SYNC del controller",
        ["Ausgabe als"] = "Output come",
        ["Xbox-360-Controller (empfohlen)"] = "Controller Xbox 360 (consigliato)",
        ["DualShock 4 (mit Gyro für Steam/Emulatoren)"] = "DualShock 4 (con giroscopio per Steam/emulatori)",
        ["Tastenbelegung"] = "Assegnazione dei pulsanti",
        ["Xbox-Belegung (untere Taste = A)"] = "Disposizione Xbox (pulsante in basso = A)",
        ["Switch-2-Pro-Belegung (A bleibt A)"] = "Disposizione Nintendo (A resta A)",
        ["Automatisch (nach Spiel/Programm)"] = "Automatico (in base al gioco/programma)",
        ["Mit Windows starten"] = "Avvia con Windows",
        ["Einstellungen …"] = "Impostazioni …",
        ["Kurzanleitung"] = "Guida rapida",
        ["Protokoll öffnen"] = "Apri registro",
        ["Beenden"] = "Esci",
        ["N-Connect: warte auf Controller (SYNC drücken)"] = "N-Connect: in attesa di un controller (premi SYNC)",
        ["N-Connect: ViGEmBus fehlt"] = "N-Connect: ViGEmBus mancante",
        ["Neue Version verfügbar"] = "Nuova versione disponibile",
        ["Einstellungen fehlerhaft"] = "Impostazioni danneggiate",
        ["settings.json konnte nicht gelesen werden – es gelten die Standardwerte."] = "Impossibile leggere settings.json – si applicano i valori predefiniti.",
        ["Ohne ViGEmBus kann kein virtueller Controller erzeugt werden. Bitte das Setup erneut ausführen oder ViGEmBus installieren (Rechtsklick auf das Symbol → ViGEmBus herunterladen)."] =
            "Senza ViGEmBus non è possibile creare un controller virtuale. Esegui di nuovo l'installazione o installa ViGEmBus (tasto destro sull'icona → Scarica ViGEmBus).",

        // ---------- Dialoge ----------
        ["Tastatur-Taste festlegen"] = "Definisci un tasto della tastiera",
        ["Übernehmen"] = "Applica",
        ["Abbrechen"] = "Annulla",
        ["Ja"] = "Sì",
        ["Nein"] = "No",
        ["Turbo / Dauerfeuer"] = "Turbo / fuoco rapido",
        ["Tastatur-Taste aufnehmen …"] = "Registra un tasto della tastiera …",
        ["Makro (Tastenfolge)"] = "Macro (sequenza di tasti)",
        ["Ungültig – bitte Schreibweise prüfen (siehe oben)."] = "Non valido – controlla la sintassi (vedi sopra).",
        ["Neues Profil"] = "Nuovo profilo",
        ["Name des Profils (z. B. der Spielname):"] = "Nome del profilo (ad es. il nome del gioco) :",
        ["Profil umbenennen"] = "Rinomina il profilo",
        ["Neuer Name:"] = "Nuovo nome :",
        ["Ein Profil mit diesem Namen gibt es schon."] = "Esiste già un profilo con questo nome.",
        ["Die Datei enthält kein gültiges Controller-Profil."] = "Il file non contiene un profilo controller valido.",
        ["Alle Einstellungen und Tastenbelegungen auf Standard zurücksetzen?"] = "Ripristinare tutte le impostazioni e le assegnazioni dei pulsanti?",
        ["Suche …"] = "Ricerca …",
        ["Kein Bluetooth-Adapter gefunden."] = "Nessun adattatore Bluetooth trovato.",
        ["IR-Kamera (Joy-Con R)"] = "Fotocamera IR (Joy-Con D)",
        ["Auflösung:"] = "Risoluzione :",
        ["40 × 30 (schnell)"] = "40 × 30 (veloce)",
        ["320 × 240 (langsam)"] = "320 × 240 (lenta)",
        ["Kamera startet …"] = "Avvio della fotocamera …",
        ["läuft – Joy-Con auf eine Lichtquelle oder die Hand richten"] = "attiva – punta il Joy-Con verso una fonte di luce o la mano",
        ["Kamera startet nicht (Details im Protokoll)"] = "La fotocamera non si avvia (dettagli nel registro)",
        ["Kein Ring-Con gefunden. Den rechten Joy-Con (Switch 1) fest in den Ring-Con schieben und erneut versuchen."] =
            "Nessun Ring-Con trovato. Inserisci bene il Joy-Con destro (Switch 1) nel Ring-Con e riprova.",
        ["Kein amiibo erkannt. Bitte das amiibo flach an den NFC-Leser halten (Joy-Con: auf den rechten Stick, Pro Controller: auf das NFC-Logo) und erneut versuchen."] =
            "Nessun amiibo rilevato. Tieni l'amiibo piatto sul lettore NFC (Joy-Con: sullo stick destro; Pro Controller: sul logo NFC) e riprova.",
        ["NFC-Leser wird eingeschaltet …"] = "Attivazione del lettore NFC …",
        ["amiibo an den Leser halten (rechter Stick des Joy-Con bzw. NFC-Logo des Pro Controllers) …"] =
            "Tieni l'amiibo sul lettore (stick destro del Joy-Con o logo NFC del Pro Controller) …",
        ["amiibo speichern"] = "Salva amiibo",
        ["Doppelte Controller verhindern"] = "Evita controller doppi",
        ["Dafür wird das kostenlose Programm HidHide gebraucht (von den Machern von ViGEmBus).\n\nJetzt die Download-Seite öffnen? Nach der Installation hier erneut klicken."] =
            "Serve il programma gratuito HidHide (dagli autori di ViGEmBus).\n\nAprire ora la pagina di download? Dopo l'installazione clicca di nuovo qui.",
        ["HidHide konnte nicht eingerichtet werden (abgebrochen oder fehlgeschlagen). Details im Protokoll."] =
            "Impossibile configurare HidHide (annullato o non riuscito). Dettagli nel registro.",
        ["Der Controller hat sich bewegt oder keine Bewegungsdaten geliefert.\nBitte flach auf den Tisch legen, nicht berühren und erneut versuchen."] =
            "Il controller si è mosso o non ha inviato dati di movimento.\nAppoggialo sul tavolo senza toccarlo e riprova.",
        ["Spiel oder Programm wählen"] = "Scegli un gioco o un programma",
        ["Profil exportieren"] = "Esporta il profilo",
        ["Profil importieren"] = "Importa il profilo",
        ["Verstanden"] = "Capito",
        ["Einstellungen öffnen"] = "Apri impostazioni",
        ["Willkommen"] = "Benvenuto",

        // ---------- Neues Hauptfenster (Navigation, Seiten, Zeilen) ----------
        ["Allgemein"] = "Generale",
        ["Sticks & Vibration"] = "Stick e vibrazione",
        ["Gyro & Maus"] = "Giroscopio e mouse",
        ["Joy-Con & Wii"] = "Joy-Con e Wii",
        ["Ein"] = "Sì",
        ["Aus"] = "No",
        ["Verbundene Controller mit Live-Anzeige. Über „Einstellungen“ an einem Controller passt du genau diesen an."] =
            "Controller connessi con visualizzazione in diretta. Con « Impostazioni » su un controller regoli esattamente quello.",
        ["Jede Taste kann ein Gamepad-Knopf, eine Tastaturtaste, ein Mausklick, Turbo oder ein Makro sein. " +
         "Tipp: Drückst du eine Taste am Controller, wird ihre Zeile hervorgehoben."] =
            "Ogni pulsante può essere un pulsante del gamepad, un tasto, un clic del mouse, turbo o una macro. " +
            "Suggerimento: premi un pulsante del controller per evidenziarne la riga.",
        ["Profil"] = "Profilo",
        ["Neu"] = "Nuovo",
        ["Umbenennen, löschen, exportieren, importieren"] = "Rinomina, elimina, esporta, importa",
        ["Ein eigenes Profil gilt automatisch, solange eines seiner Programme im Vordergrund ist – sonst „Standard“."] =
            "Un profilo personalizzato vale automaticamente finché uno dei suoi programmi è in primo piano – altrimenti « Predefinito ».",
        ["Aktiv bei Programm"] = "Attivo con il programma",
        ["Programmdateien, bei denen dieses Profil gilt (mit Komma trennen)."] = "File dei programmi per cui vale questo profilo (separare con virgole).",
        ["Standard gilt für alle Programme"] = "Il predefinito vale per tutti i programmi",
        ["Wählen …"] = "Scegli …",
        ["Bearbeiten"] = "Modifica",
        ["Jeder Controller hat seine eigene Belegung."] = "Ogni controller ha la propria assegnazione.",
        ["Ebene"] = "Livello",
        ["Normal"] = "Normale",
        ["Shift-Ebene"] = "Livello Shift",
        ["Die Shift-Ebene gilt, solange eine Taste mit „Shift-Ebene“ gehalten wird."] = "Il livello Shift vale finché un pulsante impostato su « livello Shift » è tenuto premuto.",
        ["Tasten"] = "Pulsanti",
        ["Standardwerte für alle Controller. Eigene Werte für einzelne Controller stellst du unten oder in der Übersicht ein."] =
            "Valori predefiniti per tutti i controller. Imposta valori propri per singoli controller qui sotto o nella panoramica.",
        ["Sticks"] = "Stick",
        ["Totzone"] = "Zona morta",
        ["So weit lässt sich ein Stick bewegen, bevor er wirkt (gegen Abdriften)."] = "Quanto può muoversi uno stick prima di reagire (contro la deriva).",
        ["Kennlinie"] = "Curva di risposta",
        ["„linear“ = gleichmäßig. Höher = feiner um die Mitte (präzises Zielen), niedriger = schneller."] =
            "« lineare » = uniforme. Più alta = più fine al centro (mira precisa), più bassa = più veloce.",
        ["Analoge Trigger (GameCube)"] = "Grilletti analogici (GameCube)",
        ["So weit lässt sich ein Trigger drücken, bevor er wirkt."] = "Quanto può essere premuto un grilletto prima di reagire.",
        ["Voll gedrückt ab"] = "Premuto a fondo da",
        ["Ab hier gilt der Trigger als ganz gedrückt (100 % = erst am Anschlag)."] = "Da qui il grilletto conta come premuto a fondo (100 % = solo a fine corsa).",
        ["Spiele dürfen den Controller vibrieren lassen."] = "I giochi possono far vibrare il controller.",
        ["Stärke"] = "Intensità",
        ["Turbo-Geschwindigkeit"] = "Velocità del turbo",
        ["Wie oft pro Sekunde Tasten mit „Turbo“ auslösen."] = "Quante volte al secondo si attivano i pulsanti « turbo ».",
        ["Eigene Werte je Controller"] = "Valori propri per controller",
        ["Werte nur für diesen Controller – ohne eigenen Wert gilt der allgemeine."] = "Valori solo per questo controller – senza valore proprio vale quello generale.",
        ["Bewegungssteuerung: Zielen per Gyro und den Controller als Maus nutzen."] = "Controllo del movimento: mira con il giroscopio e usa il controller come mouse.",
        ["Gyro als rechter Stick"] = "Giroscopio come stick destro",
        ["Modus"] = "Modalità",
        ["Zum Zielen in Spielen ohne eigene Gyro-Steuerung. „Gyro-Stick“ kann auch einer Taste zugewiesen werden."] =
            "Per mirare in giochi senza controllo giroscopico proprio. « Stick giroscopico » può essere assegnato anche a un pulsante.",
        ["Aus (nur per Taste „Gyro-Stick“)"] = "Disattivato (solo con un pulsante « stick giroscopico »)",
        ["Immer"] = "Sempre",
        ["Beim Zielen (solange ZL / LT gedrückt)"] = "In mira (finché ZL / LT è premuto)",
        ["Empfindlichkeit"] = "Sensibilità",
        ["Drehgeschwindigkeit für vollen Stick-Ausschlag – kleiner = empfindlicher."] = "Velocità di rotazione per deflessione completa dello stick – più bassa = più sensibile.",
        ["Mindestausschlag"] = "Deflessione minima",
        ["Überwindet die Stick-Totzone des Spiels bei kleinen Bewegungen."] = "Supera la zona morta dello stick del gioco nei piccoli movimenti.",
        ["Hoch/runter umkehren"] = "Inverti su/giù",
        ["Links/rechts umkehren"] = "Inverti sinistra/destra",
        ["Gyro-Maus"] = "Mouse giroscopico",
        ["Geschwindigkeit"] = "Velocità",
        ["Mauszeiger per Bewegung – über eine Taste mit „Gyro-Maus“ (Tastenbelegung)."] = "Puntatore del mouse tramite movimento – con un pulsante « mouse giroscopico » (assegnazione dei pulsanti).",
        ["Mausrichtung (Gyro-Maus und Joy-Con-Maus)"] = "Direzione del mouse (mouse giroscopico e mouse Joy-Con)",
        ["Gyro-Funktionen einer Taste zuweisen"] = "Assegna funzioni giroscopiche a un pulsante",
        ["Gyro-Maus oder Gyro-Stick ein/aus bzw. solange gehalten"] = "Mouse giroscopico o stick giroscopico attiva/disattiva o finché premuto",
        ["Joy-Con als Paar oder einzeln, Joy-Con 2 als Maus und Wii-Controller."] = "Joy-Con in coppia o singoli, Joy-Con 2 come mouse e controller Wii.",
        ["Zu einem Controller zusammenfassen"] = "Unisci in un solo controller",
        ["Ein linker und ein rechter Joy-Con werden automatisch ein Paar."] = "Un Joy-Con sinistro e uno destro formano automaticamente una coppia.",
        ["Gyro beim Paar vom"] = "Giroscopio della coppia da",
        ["Rechter Joy-Con (wie Switch)"] = "Joy-Con destro (come su Switch)",
        ["Linker Joy-Con"] = "Joy-Con sinistro",
        ["Paar lösen oder verbinden"] = "Separa o unisci una coppia",
        ["Einen Joy-Con quer halten und SL oder SR drücken löst ihn aus dem Paar. L am linken und R am rechten Joy-Con gleichzeitig drücken verbindet sie wieder. Die Wahl wird je Joy-Con gemerkt."] =
            "Tieni un Joy-Con orizzontale e premi SL o SR per staccarlo dalla coppia. Premendo L sul sinistro e R sul destro insieme si riuniscono. La scelta è memorizzata per ogni Joy-Con.",
        ["Joy-Con 2 als Maus"] = "Joy-Con 2 come mouse",
        ["Als Maus, wenn er auf dem Tisch liegt"] = "Come mouse quando è sul tavolo",
        ["Joy-Con 2 auf die Seite legen und wie eine Maus schieben."] = "Appoggia il Joy-Con 2 sul fianco e fallo scorrere come un mouse.",
        ["Mausgeschwindigkeit"] = "Velocità del mouse",
        ["Tasten im Mausmodus"] = "Pulsanti in modalità mouse",
        ["R/L = Linksklick, ZR/ZL = Rechtsklick, Stick drücken = Mittelklick, Stick hoch/runter = Scrollen."] =
            "R/L = clic sinistro, ZR/ZL = clic destro, premere lo stick = clic centrale, stick su/giù = scorrimento.",
        ["Zeiger steuert die Maus"] = "Il puntatore muove il mouse",
        ["Wii-Fernbedienung auf die Sensorleiste richten, um den Mauszeiger zu bewegen."] = "Punta il telecomando Wii verso la barra sensori per muovere il puntatore.",
        ["Wie Spiele die Controller sehen, Verbindung, Darstellung und Programm."] = "Come i giochi vedono i controller, connessione, aspetto e programma.",
        ["Ausgabe"] = "Output",
        ["Controller erscheint als"] = "Il controller appare come",
        ["Xbox 360 läuft mit fast allen Spielen. DualShock 4 bietet Bewegungssteuerung (Steam, Emulatoren)."] =
            "Xbox 360 funziona con quasi tutti i giochi. DualShock 4 offre il controllo del movimento (Steam, emulatori).",
        ["Xbox 360 läuft mit fast allen Spielen und Steam. DualShock 4 bietet zusätzlich Bewegungssteuerung (Steam, Emulatoren). Gilt für alle Controller ohne eigene Einstellung (Karte → Einstellungen → Tasten)."] =
            "Xbox 360 funziona con quasi tutti i giochi e Steam. DualShock 4 aggiunge il controllo del movimento (Steam, emulatori). Vale per tutti i controller senza impostazione propria (scheda → Impostazioni → Pulsanti).",
        ["Original-Controller verstecken"] = "Nascondi i controller originali",
        ["Controller verbinden"] = "Connetti controller",
        ["SYNC-Taste am Controller drücken – N-Connect findet und koppelt ihn selbst. Danach reicht künftig ein Tastendruck."] =
            "Premi il pulsante SYNC del controller – N-Connect lo trova e lo associa da solo. Poi basta una pressione.",
        ["So kommt der Controller in den Kopplungsmodus"] = "Come mettere il controller in modalità di associazione",
        ["Kurz die kleine SYNC-Taste drücken."] = "Premi brevemente il piccolo pulsante SYNC.",
        ["SYNC-Taste drücken, bis die Lichter laufen."] = "Premi il pulsante SYNC finché le luci scorrono.",
        ["Batteriefach öffnen und die rote SYNC-Taste drücken."] = "Apri il vano batterie e premi il pulsante SYNC rosso.",
        ["Die SYNC-Taste auf der Unterseite drücken."] = "Premi il pulsante SYNC sul lato inferiore.",
        ["PS + Teilen bzw. Create halten, bis die Lichtleiste schnell blinkt."] =
            "Tieni premuto PS + Share/Create finché la barra luminosa lampeggia rapidamente.",
        ["Kopplungstaste oben halten, bis die Xbox-Taste blinkt."] = "Tieni premuto il pulsante di associazione in alto finché il pulsante Xbox lampeggia.",
        ["Status"] = "Stato",
        ["Suche läuft …"] = "Ricerca in corso …",
        ["Suche läuft – jetzt SYNC drücken …"] = "Ricerca in corso – premi SYNC ora …",
        ["Weitere Controller? Einfach SYNC drücken."] = "Altri controller? Premi semplicemente SYNC.",
        ["Wartet auf einen Controller im Kopplungsmodus."] = "In attesa di un controller in modalità di associazione.",
        ["Suche beendet"] = "Ricerca terminata",
        ["Die Controller stehen in der Übersicht und verbinden sich künftig per Tastendruck."] =
            "I controller sono nella panoramica e si collegheranno con una pressione.",
        ["Kein Controller im Kopplungsmodus gefunden. SYNC-Taste drücken und „Erneut suchen“ klicken."] =
            "Nessun controller in modalità di associazione trovato. Premi SYNC e clicca « Cerca di nuovo ».",
        ["Verbunden"] = "Connesso",
        ["Erneut suchen"] = "Cerca di nuovo",
        ["Fertig"] = "Fine",
        ["Im Spiel"] = "Nel gioco",
        ["Dreht …"] = "Rotazione …",
        ["Testdrehung (360°)"] = "Rotazione di prova (360°)",
        ["Testdrehung"] = "Rotazione di prova",
        ["aus"] = "disattivato",
        ["Gyro-Beschleunigung"] = "Accelerazione del giroscopio",
        ["Bei schneller Drehung"] = "Con rotazione rapida",
        ["Langsame Bewegungen bleiben fein, schnelle drehen weiter (wie JoyShockMapper). Voll ab 120 °/s, unter 20 °/s normal. Gilt für Gyro-Stick und Gyro-Maus."] =
            "I movimenti lenti restano precisi, quelli rapidi ruotano di più (come JoyShockMapper). Piena da 120 °/s, normale sotto 20 °/s. Vale per stick giroscopico e mouse giroscopico.",
        ["Flick-Stick (Spiele mit Maussteuerung)"] = "Flick stick (giochi con controllo mouse)",
        ["Flick-Stick"] = "Flick stick",
        ["Rechten Stick in eine Richtung schieben = Kamera dreht sofort dorthin; am Rand drehen = Kamera dreht mit. Zielen dann per Gyro. Der rechte Stick geht nicht mehr ans Spiel."] =
            "Spingi lo stick destro in una direzione = la camera ruota subito lì; ruotandolo sul bordo = la camera segue. Poi si mira con il giroscopio. Lo stick destro non viene più inviato al gioco.",
        ["Mausbewegung je Umdrehung"] = "Movimento del mouse per giro",
        ["Je Spiel einmal einstellen: „Testdrehung“ klicken, ins Spiel wechseln – nach 3 s dreht die Kamera einmal. Genau eine volle Drehung = richtig."] =
            "Da regolare una volta per gioco: clicca « Rotazione di prova », passa al gioco – dopo 3 s la camera ruota una volta. Esattamente un giro completo = corretto.",
        ["Flick-Dauer"] = "Durata del flick",
        ["So lange dauert die Drehung beim Flick (0 = sofort)."] = "Quanto dura la rotazione di un flick (0 = istantanea).",
        ["Gyro-Maus oder Gyro-Stick ein/aus bzw. solange gehalten, „Gyro anhalten“ (Ratchet: Controller zurückführen, ohne dass sich das Ziel bewegt)"] =
            "Mouse giroscopico o stick giroscopico attiva/disattiva o finché premuto, « sospendi giroscopio » (ratchet: riporta il controller senza muovere la mira)",
        ["✋  Gyro anhalten (solange gehalten, „Ratchet“)"] = "✋  Sospendi giroscopio (finché premuto, « ratchet »)",
        ["Spieler-LED und Lichtleiste vom Spiel"] = "LED giocatore e barra luminosa del gioco",
        ["Die Spieler-LEDs zeigen den Xbox-Platz, den Windows vergibt. Bei DualShock 4 steuert die Lichtleiste des Spiels die HOME-LED (Switch 1 Pro Controller, rechter Joy-Con)."] =
            "I LED giocatore indicano il posto Xbox assegnato da Windows. Su DualShock 4 la barra luminosa del gioco controlla il LED HOME (Pro Controller Switch 1, Joy-Con destro).",
        ["HidHide installieren …"] = "Installa HidHide …",
        ["Empfohlen: Steam und viele Spiele kennen Switch-1-, NSO- und USB-Controller selbst und sähen sie sonst doppelt. Läuft nach der Installation ohne Rückfrage (sonst fragt Windows nach Adminrechten)."] =
            "Consigliato: Steam e molti giochi riconoscono da soli i controller Switch 1, NSO e USB e li vedrebbero due volte. Dopo l'installazione funziona senza richieste (altrimenti Windows chiede i diritti di amministratore).",
        ["Steam und viele Spiele sehen Switch-1-, NSO- und USB-Controller sonst doppelt. Dafür wird das kostenlose HidHide gebraucht (bei der N-Connect-Installation dabei, hier nachträglich)."] =
            "Altrimenti Steam e molti giochi vedono i controller Switch 1, NSO e USB due volte. Serve il gratuito HidHide (incluso nell'installazione di N-Connect, installabile qui in seguito).",
        ["Erscheint als"] = "Appare come",
        ["Wie allgemein"] = "Come in Generale",
        ["Nur für diesen Controller. Xbox 360 läuft überall; DualShock 4 bringt zusätzlich Gyro nach Steam und in Emulatoren. „Wie allgemein“ folgt der Seite „Allgemein“."] =
            "Solo per questo controller. Xbox 360 funziona ovunque; DualShock 4 aggiunge il giroscopio in Steam e negli emulatori. « Come in Generale » segue la pagina « Generale ».",
        ["Der echte Xbox-Controller – Spiele sehen ihn von Windows aus direkt. Belegungen hier wirken auf Sonderaktionen (Tastatur, Makros, Gyro), nicht auf den Controller selbst."] =
            "Il vero controller Xbox – i giochi lo vedono già direttamente da Windows. Le assegnazioni qui agiscono sulle azioni speciali (tastiera, macro, giroscopio), non sul controller stesso.",
        ["Steam und manche Spiele sehen diesen Controller sonst doppelt. Abhilfe: HidHide installieren (Seite „Allgemein“ → „Original-Controller verstecken“)."] =
            "Altrimenti Steam e alcuni giochi vedono questo controller due volte. Soluzione: installa HidHide (pagina « Generale » → « Nascondi i controller originali »).",
        ["Original-Controller vor Spielen versteckt. Steam bitte einmal neu starten – danach sieht es nur noch den virtuellen Controller."] =
            "Controller originali nascosti ai giochi. Riavvia Steam una volta – poi vede solo il controller virtuale.",
        ["Original-Controller vor Spielen versteckt – Steam und Spiele sehen nur noch den virtuellen Controller."] =
            "Controller originali nascosti ai giochi – Steam e i giochi ora vedono solo il controller virtuale.",
        ["Original-Controller nicht versteckt (Abfrage abgebrochen). Nachholen: Controller → Einstellungen → Extras → „Doppelt angezeigt?“."] =
            "Controller originali non nascosti (richiesta annullata). Per dopo: controller → Impostazioni → Extra → « Visualizzato due volte? ».",
        ["Tastenanordnung A/B/X/Y"] = "Disposizione dei pulsanti A/B/X/Y",
        ["Xbox: nach Position (untere Taste = A). Nintendo: nach Beschriftung (A bleibt A)."] = "Xbox: per posizione (pulsante in basso = A). Nintendo: per etichetta (A resta A).",
        ["Verbinden"] = "Connessione",
        ["Per Tastendruck verbinden"] = "Connetti con una pressione",
        ["Gekoppelte Controller verbinden sich ohne SYNC-Taste."] = "I controller associati si connettono senza il pulsante SYNC.",
        ["Ohne Eingabe trennen nach"] = "Disconnetti senza input dopo",
        ["Spart Akku, wenn ein Controller liegen bleibt."] = "Risparmia batteria quando un controller resta appoggiato.",
        ["N-Connect startet unsichtbar im Infobereich."] = "N-Connect si avvia in modo discreto nell'area di notifica.",
        ["Darstellung und Sprache"] = "Aspetto e lingua",
        ["Farbmodus"] = "Modalità colore",
        ["Mica-Effekt"] = "Effetto Mica",
        ["Durchscheinende Titelleiste (ab Windows 11)."] = "Barra del titolo traslucida (da Windows 11).",
        ["Erweitert"] = "Avanzate",
        ["Gyro für Emulatoren (DSU)"] = "Giroscopio per emulatori (DSU)",
        ["Cemuhook-Server auf Port 26760 – wirkt nach einem Neustart von N-Connect."] = "Server Cemuhook sulla porta 26760 – attivo dopo un riavvio di N-Connect.",
        ["Nach Updates suchen"] = "Cerca aggiornamenti",
        ["Beim Start auf GitHub nach einer neuen Version suchen."] = "Cerca una nuova versione su GitHub all'avvio.",
        ["Tastenbelegungen und Werte zurücksetzen. Gekoppelte Controller bleiben erhalten."] = "Ripristina assegnazioni dei pulsanti e valori. I controller associati restano.",
        ["Zurücksetzen"] = "Ripristina",

        // ---------- Controller-Karte ----------
        ["Einstellungen"] = "Impostazioni",
        ["Tastenbelegung und Einstellungen nur für diesen Controller"] = "Assegnazione dei pulsanti e impostazioni solo per questo controller",
        ["Feineinstellung"] = "Regolazione fine",
        ["Gyro"] = "Giroscopio",
        ["Extras"] = "Extra",
        ["Belegung für alle Spiele (Standard) oder ein eigenes Profil."] = "Assegnazione per tutti i giochi (predefinito) o un profilo proprio.",
        ["Profile"] = "Profili",
        ["Profile anlegen, umbenennen, exportieren …"] = "Crea, rinomina, esporta profili …",
        ["Drück eine Taste am Controller – ihre Zeile leuchtet auf. ⌨ weist eine Tastaturtaste zu, ↺ setzt zurück."] =
            "Premi un pulsante del controller – la sua riga si illumina. ⌨ assegna un tasto della tastiera, ↺ ripristina.",
        ["Tastatur-Taste zuweisen: klicken und die gewünschte Taste oder Kombination drücken."] = "Assegna un tasto della tastiera: clicca e premi il tasto o la combinazione desiderata.",
        ["Zurück auf die Standardbelegung"] = "Torna all'assegnazione predefinita",
        ["Ohne eigenen Wert gilt der allgemeine Wert der Seite „Sticks & Vibration“."] = "Senza valore proprio vale quello generale della pagina « Stick e vibrazione ».",
        ["Stick-Totzone"] = "Zona morta dello stick",
        ["Stick-Kennlinie"] = "Curva dello stick",
        ["Trigger-Totzone"] = "Zona morta del grilletto",
        ["Trigger voll gedrückt ab"] = "Grilletto premuto a fondo da",
        ["Vibrationsstärke"] = "Intensità della vibrazione",
        ["Gyro-Maus-Geschwindigkeit"] = "Velocità del mouse giroscopico",
        ["Eigenen Wert entfernen – es gilt wieder der allgemeine Wert"] = "Rimuovi il valore proprio – torna a valere quello generale",
        ["Kalibrieren"] = "Calibra",
        ["Controller ruhig auf den Tisch legen und klicken: misst den Nullpunkt neu (gegen Abdriften)."] =
            "Appoggia il controller sul tavolo e clicca: misura di nuovo il punto zero (contro la deriva).",
        ["Gyro als rechter Stick und Mausrichtung"] = "Giroscopio come stick destro e direzione del mouse",
        ["Gilt für alle Controller"] = "Vale per tutti i controller",
        ["Paar"] = "Coppia",
        ["Joy-Con quer halten und SL oder SR drücken löst das Paar, L + R gleichzeitig verbindet es."] =
            "Tieni un Joy-Con orizzontale e premi SL o SR per separare la coppia; L + R insieme la riunisce.",
        ["Haltung"] = "Orientamento",
        ["Quer"] = "Orizzontale",
        ["Hochkant"] = "Verticale",
        ["Quer wie an der Switch oder hochkant – hochkant gilt die Belegung von „Joy-Con-Paar“."] =
            "Orizzontale come su Switch o verticale – in verticale vale l'assegnazione « coppia Joy-Con ».",
        ["Mausmodus, Geschwindigkeit und Tasten"] = "Modalità mouse, velocità e pulsanti",
        ["Lesen …"] = "Leggi …",
        ["Einschalten"] = "Attiva",
        ["Ausschalten"] = "Disattiva",
        ["Wird gesucht …"] = "Ricerca …",
        ["Öffnen"] = "Apri",
        ["Verstecken"] = "Nascondi",
        ["amiibo an den NFC-Leser halten und als Datei (.bin) speichern – z. B. für Emulatoren."] =
            "Tieni un amiibo sul lettore NFC e salvalo come file (.bin) – ad es. per gli emulatori.",
        ["Zusammendrücken = rechter Trigger, auseinanderziehen = linker Trigger. Beim Einschalten nicht berühren."] =
            "Premere = grilletto destro, allargare = grilletto sinistro. Non toccarlo durante l'attivazione.",
        ["Live-Bild der Infrarotkamera im rechten Joy-Con."] = "Immagine in diretta della fotocamera a infrarossi del Joy-Con destro.",
        ["Doppelt angezeigt?"] = "Visualizzato due volte?",
        ["Versteckt den Original-Controller vor Steam und Spielen (HidHide) – sie sehen dann nur den virtuellen Controller."] =
            "Nasconde il controller originale a Steam e ai giochi (HidHide) – vedono solo il controller virtuale.",
        ["bereit (auf den Tisch legen)"] = "pronto (appoggialo sul tavolo)",
        ["amiibo-Abbild (*.bin)|*.bin"] = "Immagine amiibo (*.bin)|*.bin",
        ["Controller-Profil (*.ncprofile.json)|*.ncprofile.json|JSON (*.json)|*.json"] = "Profilo controller (*.ncprofile.json)|*.ncprofile.json|JSON (*.json)|*.json",
        ["Programme (*.exe)|*.exe"] = "Programmi (*.exe)|*.exe",
        ["Kein Controller verbunden\n\n" +
         "Switch-2-Controller: kurz die SYNC-Taste drücken – danach reicht ein beliebiger Tastendruck.\n" +
         "Switch-1-, NSO- und Wii-Controller: SYNC-Taste drücken – N-Connect koppelt sie selbst.\n" +
         "Oder hier gezielt suchen und koppeln:"] =
            "Nessun controller connesso\n\n" +
            "Controller Switch 2: premi brevemente il pulsante SYNC – poi basta una pressione qualsiasi.\n" +
            "Controller Switch 1, NSO e Wii: premi il pulsante SYNC – N-Connect li associa da solo.\n" +
            "Oppure cerca e associa direttamente qui:",
        ["Controller suchen …"] = "Cerca controller …",
        ["Switch-1-, NSO- und Wii-Controller suchen und koppeln (SYNC-Taste drücken)."] =
            "Cerca e associa controller Switch 1, NSO e Wii (premi il pulsante SYNC).",
        ["Neue Controller automatisch koppeln"] = "Associa automaticamente i nuovi controller",
        ["Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive, Wii und PlayStation: einfach SYNC " +
         "drücken – kein Umweg über die Windows-Bluetooth-Einstellungen. Gesucht wird nur, solange niemand spielt."] =
            "Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive, Wii e PlayStation: premi semplicemente SYNC – " +
            "senza passare dalle impostazioni Bluetooth di Windows. La ricerca avviene solo mentre nessuno gioca.",
        ["Gezielt suchen"] = "Ricerca mirata",
        ["Sucht eine Minute lang nach Controllern im Kopplungsmodus."] = "Cerca controller in modalità di associazione per un minuto.",
        ["Controller koppeln …"] = "Associa controller …",
        ["Controller koppeln"] = "Associa controller",
        ["Linken Joy-Con umbenennen …"] = "Rinomina Joy-Con sinistro …",
        ["Rechten Joy-Con umbenennen …"] = "Rinomina Joy-Con destro …",
        ["Controller umbenennen"] = "Rinomina controller",
        ["Spielerplatz"] = "Posto del giocatore",
        ["N-Connect aktualisieren"] = "Aggiorna N-Connect",
        ["HidHide aktualisieren"] = "Aggiorna HidHide",
        ["HidHide-Update verfügbar"] = "Aggiornamento HidHide disponibile",
        ["HidHide aktuell halten"] = "Mantieni HidHide aggiornato",
        ["Beim Start nach einer neuen HidHide-Version suchen. Installiert wird nur nach Rückfrage (geprüfter Download vom Hersteller, Neustart nötig)."] =
            "Cerca una nuova versione di HidHide all'avvio. L'installazione avviene solo dopo conferma (download verificato dal produttore, riavvio necessario).",
        ["Der Download hat nicht geklappt oder die Datei war fehlerhaft. Die Release-Seite im Browser öffnen?"] =
            "Il download non è riuscito o il file era difettoso. Aprire la pagina della versione nel browser?",
        ["Alle Controller trennen"] = "Disconnetti tutti i controller",
        ["Sticks kalibrieren"] = "Calibra gli stick",
        ["Kalibrieren …"] = "Calibra …",
        ["Gegen Drift oder zu kleinen Ausschlag: Mitte und Rand neu messen. Wird nur in N-Connect gespeichert, der Controller bleibt unverändert."] =
            "Contro la deriva o la corsa troppo corta: misura di nuovo centro e bordo. Salvato solo in N-Connect, il controller resta invariato.",
        ["Linker Stick"] = "Stick sinistro",
        ["Rechter Stick"] = "Stick destro",
        ["Stick"] = "Stick",
        ["Stick (linker Joy-Con)"] = "Stick (Joy-Con sinistro)",
        ["Stick (rechter Joy-Con)"] = "Stick (Joy-Con destro)",
        ["Neu messen"] = "Misura di nuovo",
        ["Werkswerte"] = "Valori di fabbrica",
        ["Der Punkt zeigt, wo der Stick gerade steht. Steht er losgelassen nicht in der Mitte oder erreicht er den Kreis nicht, auf „Neu messen“ klicken."] =
            "Il punto indica dove si trova lo stick. Se non è centrato quando rilasciato o non raggiunge il cerchio, clicca « Misura di nuovo ».",
        ["Gilt gerade: eigene Kalibrierung."] = "Attualmente in uso: calibrazione propria.",
        ["Gilt gerade: Werkswerte des Controllers."] = "Attualmente in uso: valori di fabbrica del controller.",
        ["1/2 – Stick loslassen und den Controller ruhig halten …"] = "1/2 – rilascia lo stick e tieni fermo il controller …",
        ["2/2 – Stick bis zum Anschlag drücken und langsam ein- bis zweimal im Kreis drehen."] =
            "2/2 – spingi lo stick a fondo e ruotalo lentamente in cerchio una o due volte.",
        ["Fertig. „Übernehmen“ speichert die neue Kalibrierung für diesen Controller."] = "Fatto. « Applica » salva la nuova calibrazione per questo controller.",
        ["Der Stick hat den Rand nicht erreicht. Bitte bis zum Anschlag drücken und erneut messen."] =
            "Lo stick non ha raggiunto il bordo. Spingilo a fondo e misura di nuovo.",
        ["Übernommen ✓ – gilt ab sofort."] = "Applicato ✓ – attivo da subito.",
        ["Werkswerte des Controllers gelten wieder."] = "Valgono di nuovo i valori di fabbrica del controller.",
        ["Gyro einrichten"] = "Configura il giroscopio",
        ["Einrichten …"] = "Configura …",
        ["Zielen per Bewegung einrichten"] = "Configura la mira con il movimento",
        ["Schritt für Schritt: Nullpunkt, wann der Gyro zielt, Empfindlichkeit – mit Vorschau."] =
            "Passo dopo passo: punto zero, quando il giroscopio mira, sensibilità – con anteprima.",
        ["1  Nullpunkt"] = "1  Punto zero",
        ["Controller flach auf den Tisch legen, nicht berühren – verhindert, dass das Ziel von selbst wandert."] =
            "Appoggia il controller sul tavolo senza toccarlo – evita che la mira si sposti da sola.",
        ["Nullpunkt messen"] = "Misura il punto zero",
        ["Der Controller hat sich bewegt – bitte flach hinlegen und erneut versuchen."] = "Il controller si è mosso – appoggialo e riprova.",
        ["Nullpunkt gemessen ✓"] = "Punto zero misurato ✓",
        ["2  Wann zielt der Gyro?"] = "2  Quando mira il giroscopio?",
        ["Nur per Taste"] = "Solo con un pulsante",
        ["Beim Zielen (ZL/LT)"] = "In mira (ZL/LT)",
        ["„Beim Zielen“: nur solange ZL (linker Trigger) gehalten wird – wie in vielen Shootern."] =
            "« In mira »: solo finché ZL (grilletto sinistro) è premuto – come in molti sparatutto.",
        ["3  Empfindlichkeit"] = "3  Sensibilità",
        ["Voller Ausschlag ab"] = "Deflessione completa da",
        ["Kleinerer Wert bei „Voller Ausschlag ab“ = empfindlicher. „Mindestausschlag“ überwindet die Totzone des Spiels."] =
            "Un valore più basso a « Deflessione completa da » = più sensibile. « Deflessione minima » supera la zona morta del gioco.",
        ["Mitte"] = "Centro",
        ["Vorschau: Fadenkreuz folgt dem Controller (unabhängig von Schritt 2)."] = "Anteprima: il mirino segue il controller (indipendentemente dal passo 2).",
        ["Keine Bewegungsdaten"] = "Nessun dato di movimento",
        ["Controller gekoppelt"] = "Controller associato",
        ["Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive: SYNC-Taste drücken, bis die Lichter laufen.\n" +
         "Wii-Fernbedienung: Batteriefach öffnen und die rote SYNC-Taste drücken.\n" +
         "Wii U Pro Controller: die SYNC-Taste auf der Unterseite drücken.\n" +
         "Danach verbindet sich der Controller künftig per Tastendruck."] =
            "Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive: premi il pulsante SYNC finché le luci scorrono.\n" +
            "Telecomando Wii: apri il vano batterie e premi il pulsante SYNC rosso.\n" +
            "Wii U Pro Controller: premi il pulsante SYNC sul lato inferiore.\n" +
            "Poi il controller si connetterà con una pressione.",
        ["Suche … SYNC-Taste drücken (Xbox: Kopplungstaste oben halten, PlayStation: PS + Teilen/Create halten)."] =
            "Ricerca … premi il pulsante SYNC (Xbox: tieni premuto il pulsante di associazione in alto; PlayStation: tieni premuto PS + Share/Create).",
        ["Kein Controller im Kopplungsmodus gefunden. SYNC-Taste drücken und erneut versuchen."] =
            "Nessun controller in modalità di associazione trovato. Premi SYNC e riprova.",
        ["Darstellung:"] = "Aspetto :",
        ["Dunkel"] = "Scuro",
        ["Hell"] = "Chiaro",
        ["Wie Windows"] = "Come Windows",
        ["Mica-Effekt in der Titelleiste (ab Windows 11)"] = "Effetto Mica nella barra del titolo (da Windows 11)",

        // ---------- Fehlerfälle und Hinweise ----------
        ["Bluetooth ist ausgeschaltet."] = "Il Bluetooth è disattivato.",
        ["Dieser Bluetooth-Adapter unterstützt kein Bluetooth LE."] = "Questo adattatore Bluetooth non supporta Bluetooth LE.",
        ["Bluetooth-Suche konnte nicht starten."] = "Impossibile avviare la ricerca Bluetooth.",
        ["Bluetooth in den Windows-Einstellungen einschalten."] = "Attiva il Bluetooth nelle impostazioni di Windows.",
        ["Controller per USB funktionieren weiterhin."] = "I controller via USB continuano a funzionare.",
        ["Für Switch-2-Controller wird ein Adapter mit Bluetooth 4.0 oder neuer gebraucht."] = "I controller Switch 2 richiedono un adattatore con Bluetooth 4.0 o più recente.",
        ["Andere Controller und USB funktionieren weiterhin."] = "Gli altri controller e l'USB continuano a funzionare.",
        ["Bluetooth-Adapter (z. B. USB-Stick) einstecken bzw. Bluetooth in Windows aktivieren."] =
            "Collega un adattatore Bluetooth (ad es. una chiavetta USB) o attiva il Bluetooth in Windows.",
        ["Bluetooth ist bereit – Controller können verbunden werden."] = "Bluetooth pronto – è possibile connettere i controller.",
        ["Bluetooth-Einstellungen öffnen"] = "Apri impostazioni Bluetooth",
        ["ViGEmBus-Treiber fehlt – ohne ihn kann kein virtueller Controller erzeugt werden."] =
            "Driver ViGEmBus mancante – senza di esso non è possibile creare un controller virtuale.",
        ["Bitte das Setup erneut ausführen."] = "Esegui di nuovo l'installazione.",
        ["Das Programm schließen oder in Steam die Nintendo-Unterstützung abschalten."] =
            "Chiudi quel programma o disattiva il supporto Nintendo in Steam.",
        ["Erst einen anderen trennen."] = "Disconnetti prima un altro controller.",
        ["Tipp: Bluetooth-Stick per Verlängerung näher an den Controller, weg von USB-3-Anschlüssen und Funkkopfhörern."] =
            "Suggerimento: avvicina la chiavetta Bluetooth al controller con una prolunga, lontano da porte USB 3 e cuffie wireless.",
        ["Controller mit dem PC gekoppelt – ab jetzt reicht ein Tastendruck."] = "Controller associato al PC – d'ora in poi basta una pressione.",
        ["Hinweis: Um ihn wieder an der Switch 2 zu nutzen, dort einmal kurz SYNC drücken."] =
            "Nota: per usarlo di nuovo su Switch 2, premi una volta brevemente SYNC sulla console.",
        ["Dieser Bluetooth-Adapter unterstützt kein Bluetooth LE"] = "Questo adattatore Bluetooth non supporta Bluetooth LE",
        ["Erst IR-Kamera bzw. Ring-Con ausschalten (sie nutzen denselben Zusatzprozessor wie der NFC-Leser)."] =
            "Disattiva prima la fotocamera IR o il Ring-Con (usano lo stesso coprocessore del lettore NFC).",
        ["Erst die IR-Kamera schließen (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "Chiudi prima la fotocamera IR (Ring-Con e fotocamera IR usano lo stesso coprocessore).",
        ["Erst den Ring-Con ausschalten (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "Disattiva prima il Ring-Con (Ring-Con e fotocamera IR usano lo stesso coprocessore).",
        ["amiibo zu früh entfernt"] = "amiibo rimosso troppo presto",
        ["MCU startet nicht"] = "il coprocessore non si avvia",
        ["NFC-Modus nicht aktiv"] = "modalità NFC non attiva",
        ["Kopplung fehlgeschlagen – Details im Protokoll."] = "Associazione non riuscita – dettagli nel registro.",

        // ---------- Kopplungsdaten (Switch-SD-Karte, anderer PC) ----------
        ["Kopplungsdaten"] = "Dati di associazione",
        ["Kopplungen übernehmen oder weitergeben"] = "Riprendi o condividi associazioni",
        ["Kopplungsdaten von der Switch übernehmen"] = "Riprendi i dati di associazione dalla Switch",
        ["Von der Switch-SD-Karte (Bluepick_RCM/hekate) oder von einem anderen PC übernehmen, oder für einen anderen PC exportieren."] =
            "Riprendi dalla scheda SD della Switch (Bluepick_RCM/hekate) o da un altro PC, oppure esporta per un altro PC.",
        ["Bei Switch-SD-Karte nachfragen"] = "Chiedi quando viene inserita una scheda SD della Switch",
        ["Steckt eine SD-Karte der Switch im PC (Kartenleser oder hekate „USB Tools“), bietet N-Connect die Übernahme an. Die Karte wird nur gelesen."] =
            "Quando una scheda SD della Switch è nel PC (lettore di schede o hekate « USB Tools »), N-Connect propone la ripresa. La scheda viene solo letta.",
        ["Switch-SD-Karte erkannt"] = "Scheda SD della Switch rilevata",
        ["Kopplungsdaten der Controller gefunden – klicken, um sie anzusehen und zu übernehmen."] =
            "Dati di associazione dei controller trovati – clicca per vederli e riprenderli.",
        ["Klicken, um Kopplungsdaten der Controller zu übernehmen."] = "Clicca per riprendere i dati di associazione dei controller.",
        ["Controller-Kopplungen von der Switch-SD-Karte oder von einem anderen PC übernehmen – oder für einen anderen PC exportieren. Es werden nur Einstellungen von N-Connect geändert; Windows und der Bluetooth-Adapter bleiben unverändert."] =
            "Riprendi le associazioni dei controller dalla scheda SD della Switch o da un altro PC – o esportale per un altro PC. Vengono modificate solo le impostazioni di N-Connect; Windows e l'adattatore Bluetooth restano invariati.",
        ["Spieler-Reihenfolge – Spieler 1 ist für Windows, Steam und Spiele der erste Controller. Mit ‹ › umsortieren."] =
            "Ordine dei giocatori – il giocatore 1 è il primo controller per Windows, Steam e i giochi. Riordina con ‹ ›.",
        ["Von der Switch-SD-Karte"] = "Dalla scheda SD della Switch",
        ["Mit Bluepick_RCM oder hekate erstellte Kopplungsdaten (switchroot/joycon_mac.ini)"] =
            "Dati di associazione creati con Bluepick_RCM o hekate (switchroot/joycon_mac.ini)",
        ["Einlesen …"] = "Leggi …",
        ["Von einem anderen PC"] = "Da un altro PC",
        ["Mit N-Connect exportierte Datei (*.ncpair)"] = "File esportato da N-Connect (*.ncpair)",
        ["Datei öffnen …"] = "Apri file …",
        ["Inhalt"] = "Contenuto",
        ["Weitergeben und sichern"] = "Condividi e salva",
        ["Für einen anderen PC exportieren"] = "Esporta per un altro PC",
        ["Bekannte Controller und Einstellungen je Controller, optional mit Passwort"] =
            "Controller noti e impostazioni per controller, eventualmente con password",
        ["Sicherung wiederherstellen"] = "Ripristina un backup",
        ["Vor jedem „Übernehmen“ wird automatisch eine Sicherung angelegt"] = "Un backup viene creato automaticamente prima di ogni « Applica »",
        ["Wiederherstellen …"] = "Ripristina …",
        ["Bluetooth-Adapter dieses PCs"] = "Adattatore Bluetooth di questo PC",
        ["wird ermittelt …"] = "rilevamento …",
        ["nicht gefunden"] = "non trovato",
        ["Quelle wählen: Switch-SD-Karte (mit Bluepick_RCM oder hekate erstellte Kopplungsdaten) oder eine Datei von einem anderen PC."] =
            "Scegli una fonte: scheda SD della Switch (dati di associazione creati con Bluepick_RCM o hekate) o un file da un altro PC.",
        ["Keine Switch-SD-Karte gefunden. SD-Karte in den Kartenleser stecken oder die Switch per hekate („USB Tools“ → „SD Card“) als Laufwerk verbinden.\n\nOrdner selbst auswählen?"] =
            "Nessuna scheda SD della Switch trovata. Inserisci la scheda SD in un lettore o collega la Switch come unità tramite hekate (« USB Tools » → « SD Card »).\n\nScegliere la cartella manualmente?",
        ["Stammordner der Switch-SD-Karte wählen"] = "Scegli la cartella radice della scheda SD della Switch",
        ["Switch-SD-Karte:"] = "Scheda SD della Switch :",
        ["Auf der Karte liegen keine Kopplungsdaten (switchroot/joycon_mac.ini)."] = "La scheda non contiene dati di associazione (switchroot/joycon_mac.ini).",
        ["So erstellst du sie: Joy-Con an die Switch stecken, Bluepick_RCM starten und „Dump Joy-Con BT pairing → SD“ (oder FULL AUTO) wählen. Alternativ in hekate: Nyx → Konsole → „Dump Joy-Con BT“."] =
            "Per crearli: collega i Joy-Con alla Switch, avvia Bluepick_RCM e scegli « Dump Joy-Con BT pairing → SD » (o FULL AUTO). In alternativa in hekate: Nyx → Console → « Dump Joy-Con BT ».",
        ["Gefunden wurde eine Bluepick-Sicherung des Bluetooth-Speichers (8000000000000050.bin). Sie ist ein Switch-Speicherabbild und kann hier nicht ausgewertet werden."] =
            "È stato trovato un backup Bluepick della memoria Bluetooth (8000000000000050.bin). È un'immagine di memoria della Switch e non può essere analizzata qui.",
        ["Bluetooth-Adresse der Switch:"] = "Indirizzo Bluetooth della Switch :",
        ["Gefundene Controller:"] = "Controller trovati :",
        ["mit der Switch gekoppelt"] = "associato alla Switch",
        ["zuletzt mit einem anderen Gerät gekoppelt (nicht der Switch)"] = "ultima associazione con un altro dispositivo (non la Switch)",
        ["Joy-Con (L)"] = "Joy-Con (S)",
        ["Joy-Con (R)"] = "Joy-Con (D)",
        ["HORI-Controller (links)"] = "Controller HORI (sinistro)",
        ["HORI-Controller (rechts)"] = "Controller HORI (destro)",
        ["Hinweis: Pro Controller stehen nur im Bluetooth-Speicher der Switch (8000000000000050.bin); dieses Speicherabbild kann N-Connect nicht auswerten."] =
            "Nota: i Pro Controller figurano solo nella memoria Bluetooth della Switch (8000000000000050.bin); N-Connect non può analizzare questa immagine di memoria.",
        ["Was diese Daten können – und was nicht:"] = "Cosa permettono questi dati – e cosa no :",
        ["Die Daten zeigen, welche Controller mit deiner Switch gekoppelt sind und an welche Bluetooth-Adresse sie gebunden sind."] =
            "I dati mostrano quali controller sono associati alla tua Switch e a quale indirizzo Bluetooth sono legati.",
        ["Ein Switch-1-Controller verbindet sich auf Tastendruck nur mit dem Gerät, dessen Adresse er gespeichert hat – hier mit der Switch. Der Bluetooth-Adapter des PCs hat eine andere Adresse, deshalb kann Windows diese Kopplung nicht einfach weiterverwenden."] =
            "Un controller Switch 1 si riconnette con una pressione solo al dispositivo di cui ha memorizzato l'indirizzo – qui la Switch. L'adattatore Bluetooth del PC ha un altro indirizzo, quindi Windows non può riutilizzare questa associazione.",
        ["Die Adresse des PC-Adapters zu ändern, unterstützt N-Connect bewusst nicht (herstellerabhängig, riskant und nicht vorgesehen)."] =
            "N-Connect non supporta intenzionalmente il cambio di indirizzo dell'adattatore del PC (dipende dal produttore, rischioso e non previsto).",
        ["Windows bietet keinen offiziellen Weg, fremde Kopplungsschlüssel einzutragen: Sie liegen in einem Teil der Registrierung, auf den nur das System zugreifen darf. N-Connect ändert dort nichts."] =
            "Windows non offre un modo ufficiale per aggiungere chiavi di associazione esterne: si trovano in una parte del registro riservata al sistema. N-Connect non la modifica.",
        ["So klappt der Wechsel am einfachsten: am PC den Controller einmal per SYNC-Taste in den Windows-Bluetooth-Einstellungen koppeln. Zurück an der Switch die Joy-Con an die Konsole stecken bzw. den Pro Controller per USB-Kabel anschließen – dann sind sie ohne Menü wieder mit der Switch gekoppelt."] =
            "Il modo più semplice per cambiare: sul PC associa il controller una volta con il pulsante SYNC nelle impostazioni Bluetooth di Windows. Tornando sulla Switch, collega i Joy-Con alla console o collega il Pro Controller via cavo USB – saranno di nuovo associati senza menu.",
        ["„Übernehmen“ merkt sich diese Controller in N-Connect (Liste bekannter Controller, Zuordnung zur Switch). Kopplungsschlüssel werden nicht gespeichert."] =
            "« Applica » memorizza questi controller in N-Connect (elenco dei controller noti, associazione alla Switch). Le chiavi di associazione non vengono salvate.",
        ["N-Connect-Kopplungsdaten"] = "Dati di associazione N-Connect",
        ["Kopplungsdaten von einem anderen PC öffnen"] = "Apri dati di associazione da un altro PC",
        ["Die Datei ist zu groß."] = "Il file è troppo grande.",
        ["Keine Kopplungsdaten-Datei."] = "Non è un file di dati di associazione.",
        ["Die Datei stammt von einer neueren N-Connect-Version."] = "Il file proviene da una versione più recente di N-Connect.",
        ["Die Datei ist mit einem Passwort geschützt."] = "Il file è protetto da password.",
        ["Falsches Passwort oder die Datei wurde verändert."] = "Password errata o file modificato.",
        ["Die Datei ist beschädigt."] = "Il file è danneggiato.",
        ["Datei von:"] = "File da :",
        ["Bluetooth-Adapter dort:"] = "Adattatore Bluetooth lì :",
        ["Bluetooth-Adapter hier:"] = "Adattatore Bluetooth qui :",
        ["gekoppelt mit der Switch"] = "associato alla Switch",
        ["gekoppelt mit dem anderen PC"] = "associato all'altro PC",
        ["Weitere Einstellungen je Controller:"] = "Altre impostazioni per controller :",
        ["Was du erwarten kannst:"] = "Cosa aspettarsi :",
        ["Gleiche Adapter-Adresse (z. B. derselbe USB-Bluetooth-Stick umgesteckt): Switch-2-Controller verbinden sich hier auf Tastendruck wie am anderen PC."] =
            "Stesso indirizzo dell'adattatore (ad es. la stessa chiavetta USB Bluetooth spostata): i controller Switch 2 si connettono qui con una pressione come sull'altro PC.",
        ["Switch-1-Controller (Pro Controller, Joy-Con) brauchen zusätzlich die Kopplung in Windows. Die kann N-Connect nicht übertragen – einmal per SYNC-Taste koppeln."] =
            "I controller Switch 1 (Pro Controller, Joy-Con) necessitano inoltre dell'associazione in Windows. N-Connect non può trasferirla – associa una volta con il pulsante SYNC.",
        ["Anderer Bluetooth-Adapter: Controller verbinden sich auf Tastendruck nur mit dem Gerät, mit dem sie zuletzt gekoppelt wurden. Hier einmal SYNC drücken – danach verbinden sie sich mit diesem PC (am anderen PC dann wieder per SYNC)."] =
            "Altro adattatore Bluetooth: i controller si riconnettono con una pressione solo al dispositivo a cui sono stati associati per ultimi. Premi SYNC una volta qui – poi si connettono a questo PC (sull'altro PC usa di nuovo SYNC).",
        ["Tipp: Wer denselben USB-Bluetooth-Stick zwischen den PCs umsteckt, nimmt die Adresse mit – Switch-2-Controller verbinden sich dann an beiden PCs ohne SYNC."] =
            "Suggerimento: chi sposta la stessa chiavetta USB Bluetooth tra i PC porta con sé l'indirizzo – i controller Switch 2 si connettono su entrambi i PC senza SYNC.",
        ["Übernommen werden die Einstellungen je Controller (Joy-Con einzeln/hochkant, Gyro-Kalibrierung) und die Liste bekannter Controller."] =
            "Vengono ripresi le impostazioni per controller (Joy-Con singolo/verticale, calibrazione del giroscopio) e l'elenco dei controller noti.",
        ["Die Datei enthält Kopplungsschlüssel. Windows bietet keinen offiziellen Weg, sie einzutragen – N-Connect übernimmt sie deshalb nicht."] =
            "Il file contiene chiavi di associazione. Windows non offre un modo ufficiale per aggiungerle – N-Connect quindi non le riprende.",
        ["„Übernehmen“ ergänzt die Controller-Listen und Einstellungen von N-Connect (nichts wird gelöscht). Vorher wird eine Sicherung angelegt."] =
            "« Applica » integra gli elenchi dei controller e le impostazioni di N-Connect (nulla viene eliminato). Prima viene creato un backup.",
        ["Kopplungsdaten in N-Connect übernehmen? Vorher wird eine Sicherung der Einstellungen angelegt."] =
            "Riprendere i dati di associazione in N-Connect? Prima viene creato un backup delle impostazioni.",
        ["Nichts zu ändern – diese Daten sind schon übernommen."] = "Nulla da cambiare – questi dati sono già stati ripresi.",
        ["Übernommen. Die Sicherung lässt sich hier über „Sicherung wiederherstellen“ zurückholen."] =
            "Fatto. Il backup può essere ripristinato qui tramite « Ripristina un backup ».",
        ["Sicherung der Einstellungen"] = "Backup delle impostazioni",
        ["Die Sicherung ist beschädigt und wurde nicht übernommen."] = "Il backup è danneggiato e non è stato applicato.",
        ["Alle Einstellungen durch diese Sicherung ersetzen?"] = "Sostituire tutte le impostazioni con questo backup?",
        ["Sicherung wiederhergestellt."] = "Backup ripristinato.",
        ["Kopplungsdaten für einen anderen PC speichern"] = "Salva dati di associazione per un altro PC",
        ["Gespeichert. Die Datei am anderen PC in N-Connect unter „Joy-Con & Wii“ → „Kopplungsdaten“ → „Von einem anderen PC“ öffnen."] =
            "Salvato. Sull'altro PC apri il file in N-Connect sotto « Joy-Con e Wii » → « Dati di associazione » → « Da un altro PC ».",
        ["Kopplungsdaten exportieren"] = "Esporta dati di associazione",
        ["Passwort eingeben"] = "Inserisci la password",
        ["Passwort (optional). Ohne Passwort steht der Inhalt lesbar in der Datei. Mit Kopplungsschlüsseln ist ein Passwort Pflicht."] =
            "Password (facoltativa). Senza password il contenuto è leggibile nel file. Con le chiavi di associazione la password è obbligatoria.",
        ["Passwort"] = "Password",
        ["Passwort wiederholen"] = "Ripeti la password",
        ["Kopplungsschlüssel der Switch-Controller mitnehmen"] = "Includi le chiavi di associazione dei controller Switch",
        ["Kopplungsschlüssel mitnehmen (erst Switch-SD-Karte einlesen)"] = "Includi le chiavi di associazione (leggi prima una scheda SD della Switch)",
        ["Die Passwörter stimmen nicht überein."] = "Le password non corrispondono.",
        ["Mit Schlüsseln: Passwort mit mindestens 8 Zeichen."] = "Con le chiavi: password di almeno 8 caratteri.",
        ["Mindestens 8 Zeichen."] = "Almeno 8 caratteri.",
        ["Ohne Passwort."] = "Senza password.",
    };

    /// <summary>Meldungen mit Platzhaltern (Italienisch).</summary>
    private static readonly (Regex Pattern, Func<Match, string> Replace)[] PatternsIt =
    [
        (Re(@"^Allgemeiner Wert \((?<v>.+)\) – Regler verschieben für einen eigenen$"), m => $"Valore generale ({m.Groups["v"]}) – sposta il cursore per un valore proprio"),
        (Re(@"^Eigener Wert · allgemein: (?<v>.+)$"), m => $"Valore proprio · generale : {m.Groups["v"]}"),
        (Re(@"^Spieler (?<n>\d+)  ·  (?<k>.+?)(?<rest>(  ·  .*)?)$"), m => $"Giocatore {m.Groups["n"]}  ·  {N(m, "k")}{T(m.Groups["rest"].Value)}"),
        (Re(@"^  ·  Gyro-Maus(?<r>.*)$"), m => "  ·  Mouse giroscopico" + T(m.Groups["r"].Value)),
        (Re(@"^  ·  Gyro-Stick$"), _ => "  ·  Stick giroscopico"),
        (Re(@"^Spieler (?<n>\d+) · (?<k>.+?) (?<b>\d+ %.*)?$"), m => $"Giocatore {m.Groups["n"]} · {N(m, "k")} {m.Groups["b"]}"),
        (Re(@"^(?<k>.+) verbunden \(Spieler (?<n>\d+)\)$"), m => $"{N(m, "k")} connesso (giocatore {m.Groups["n"]})"),
        (Re(@"^Spieler (?<n>\d+) – tauschen mit (?<k>.+)$"), m => $"Giocatore {m.Groups["n"]} – scambia con {N(m, "k")}"),
        (Re(@"^Spieler (?<n>\d+) – frei$"), m => $"Giocatore {m.Groups["n"]} – libero"),
        (Re(@"^Spieler (?<n>\d+)$"), m => $"Giocatore {m.Groups["n"]}"),
        (Re(@"^Xbox 360 · Platz (?<n>\d+)$"), m => $"Xbox 360 · posto {m.Groups["n"]}"),
        (Re(@"^noch (?<n>\d+) s$"), m => $"ancora {m.Groups["n"]} s"),
        (Re(@"^Fertig – (?<n>\d+) Controller verbunden$"), m => $"Fatto – {m.Groups["n"]} controller connessi"),
        (Re(@"^✓ (?<k>.+) verbunden – Spieler (?<n>\d+)$"), m => $"✓ {N(m, "k")} connesso – giocatore {m.Groups["n"]}"),
        (Re(@"^Spieler (?<n>\d+)  ·  (?<v>.+)$"), m => $"Giocatore {m.Groups["n"]}  ·  {m.Groups["v"]}"),
        (Re(@"^Gekoppelt: (?<k>.+) – verbindet gleich …$"), m => $"Associato : {m.Groups["k"]} – connessione …"),
        (Re(@"^Ins Spiel wechseln … (?<n>\d+)$"), m => $"Passa al gioco … {m.Groups["n"]}"),
        (Re(@"^(?<k>.+) ist jetzt Spieler (?<n>\d+)$"), m => $"{N(m, "k")} è ora il giocatore {m.Groups["n"]}"),
        (Re(@"^Spieler (?<a>\d+) und (?<b>\d+) getauscht$"), m => $"Giocatori {m.Groups["a"]} e {m.Groups["b"]} scambiati"),
        (Re(@"^Name für (?<k>.+) \(leer = Standardname\):$"), m => $"Nome per {N(m, "k")} (vuoto = nome predefinito) :"),
        (Re(@"^(?<k>.+) \(Joy-Con-Paar\)$"), m => $"{m.Groups["k"]} (coppia Joy-Con)"),
        (Re(@"^Joy-Con zusammengefasst \(Spieler (?<n>\d+)\)$"), m => $"Joy-Con uniti (giocatore {m.Groups["n"]})"),
        (Re(@"^Joy-Con getrennt – (?<k>.+) ist jetzt Spieler (?<n>\d+)$"), m => $"Joy-Con separato – {N(m, "k")} è ora il giocatore {m.Groups["n"]}"),
        (Re(@"^Spieler (?<n>\d+): Akku (?<k>.+) fast leer \((?<p>\d+) %\) – bitte aufladen$"),
            m => $"Giocatore {m.Groups["n"]} : batteria di {N(m, "k")} quasi scarica ({m.Groups["p"]} %) – ricarica"),
        (Re(@"^Spieler (?<n>\d+): nach (?<m>\d+) min ohne Eingabe getrennt$"),
            m => $"Giocatore {m.Groups["n"]} : disconnesso dopo {m.Groups["m"]} min senza input"),
        (Re(@"^Profil „(?<p>.+)“ aktiv$"), m => $"Profilo « {ProfileName(m.Groups["p"].Value)} » attivo"),
        (Re(@"^Profil: (?<p>.+)$"), m => $"Profilo : {ProfileName(m.Groups["p"].Value)}"),
        (Re(@"^Profil „(?<p>.+)“ löschen\?$"), m => $"Eliminare il profilo « {m.Groups["p"]} » ?"),
        (Re(@"^Profil „(?<p>.+)“ importiert(?<r>.*)$"), m => $"Profilo « {m.Groups["p"]} » importato" + m.Groups["r"].Value.Replace("aktiv bei:", "attivo con :")),
        (Re(@"^⬇ Neue Version (?<v>.+) herunterladen …$"), m => $"⬇ Scarica la nuova versione {m.Groups["v"]} …"),
        (Re(@"^Version (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Herunterladen\.$"),
            m => $"La versione {m.Groups["v"]} è disponibile (installata : {m.Groups["i"]}). Clicca per scaricare."),
        (Re(@"^Version (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Installieren\.$"),
            m => $"La versione {m.Groups["v"]} è disponibile (installata : {m.Groups["i"]}). Clicca per installare."),
        (Re(@"^⬇ Auf Version (?<v>.+) aktualisieren …$"), m => $"⬇ Aggiorna alla versione {m.Groups["v"]} …"),
        (Re(@"^Lade Version (?<v>.+) herunter …$"), m => $"Download della versione {m.Groups["v"]} …"),
        (Re(@"^HidHide (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Installieren\.$"),
            m => $"HidHide {m.Groups["v"]} è disponibile (installata : {m.Groups["i"]}). Clicca per installare."),
        (Re(@"^Lade HidHide (?<v>.+) herunter …$"), m => $"Download di HidHide {m.Groups["v"]} …"),
        (Re(@"^(?<t>.+) · (?<r>\d+) Berichte/s$"), m => $"{T(m.Groups["t"].Value)} · {m.Groups["r"]} report/s"),
        (Re(@"^(?<p>\d+ %)(?<v>  \(.*\))?  ⚡ lädt$"), m => $"{m.Groups["p"]}{m.Groups["v"]}  ⚡ in carica"),
        (Re(@"^Speichern fehlgeschlagen: (?<e>.*)$"), m => $"Salvataggio non riuscito : {m.Groups["e"]}"),
        (Re(@"^Lesen fehlgeschlagen: (?<e>.*)$"), m => $"Lettura non riuscita : {m.Groups["e"]}"),
        (Re(@"^amiibo konnte nicht gelesen werden: (?<e>.*)$"), m => $"Impossibile leggere l'amiibo : {T(m.Groups["e"].Value)}"),
        (Re(@"^Gekoppelt: (?<k>.+)$"), m => $"Associato : {m.Groups["k"]}"),
        (Re(@"^Gefunden: (?<k>.+) – kopple …$"), m => $"Trovato : {m.Groups["k"]} – associazione …"),
        (Re(@"^amiibo erkannt \((?<u>.+)\) – lese …$"), m => $"amiibo rilevato ({m.Groups["u"]}) – lettura …"),
        (Re(@"^(?<n>\d+) Minuten$"), m => $"{m.Groups["n"]} minuti"),
        (Re(@"^✓ (?<n>\d+) Schritte, Dauer (?<ms>\d+) ms$"), m => $"✓ {m.Groups["n"]} passi, {m.Groups["ms"]} ms in totale"),
        (Re(@"^Controller-Taste „(?<b>.+)“:\nJetzt die gewünschte Taste oder Tastenkombination drücken\.$"),
            m => $"Pulsante del controller « {T(m.Groups["b"].Value)} » :\nOra premi il tasto o la combinazione desiderata."),
        (Re(@"^Solange „(?<b>.+)“ gehalten wird, wird diese Taste schnell wiederholt gedrückt\n\(Geschwindigkeit unter 5\. „Turbo“\):$"),
            m => $"Finché « {T(m.Groups["b"].Value)} » è premuto, questo pulsante si ripete rapidamente\n(velocità sotto 5. « Turbo ») :"),
        (Re(@"^Ring-Con: (?<e>.*)$"), m => $"Ring-Con : {T(m.Groups["e"].Value)}"),
        (Re(@"^⌨  Taste: (?<k>.+)$"), m => $"⌨  Tasto : {m.Groups["k"]}"),
        (Re(@"^🔁  Turbo: Taste (?<k>.+)$"), m => $"🔁  Turbo : tasto {m.Groups["k"]}"),
        (Re(@"^🔁  Turbo: (?<k>.+)$"), m => $"🔁  Turbo : {T(m.Groups["k"].Value)}"),
        (Re(@"^⏯  Makro: (?<k>.+)$"), m => $"⏯  Macro : {m.Groups["k"]}"),
        (Re(@"^Tastatur: (?<k>.+)$"), m => $"Tastiera : {m.Groups["k"]}"),
        (Re(@"^Gamepad: (?<k>.+)$"), m => $"Gamepad : {m.Groups["k"]}"),
        (Re(@"^(?<k>.+)  \(verbunden\)$"), m => $"{N(m, "k")}  (connesso)"),
        (Re(@"^Bluetooth nicht verfügbar: (?<e>.*)$"), m => $"Bluetooth non disponibile : {m.Groups["e"]}"),
        (Re(@"^(?<k>.+) per USB ist von einem anderen Programm belegt \(z\. B\. Steam\)\.$"),
            m => $"{N(m, "k")} via USB è occupato da un altro programma (ad es. Steam)."),
        (Re(@"^Schon (?<n>\d+) Controller verbunden – (?<k>.+) wird nicht verwendet\.$"),
            m => $"Già {m.Groups["n"]} controller connessi – {N(m, "k")} non viene usato."),
        (Re(@"^(?<k>.+): schwache Bluetooth-Verbindung \((?<r>\d+) statt 33–60 Berichte/s\)\.$"),
            m => $"{N(m, "k")} : connessione Bluetooth debole ({m.Groups["r"]} invece di 33–60 report/s)."),
        (Re(@"^(?<k>.+) getrennt$"), m => $"{N(m, "k")} disconnesso"),
    ];
}
