using System.Text.RegularExpressions;

namespace Switch2Pro.Bridge;

/// <summary>Feste Texte Deutsch → Spanisch. Schlüssel bleiben die deutschen Originaltexte.</summary>
internal static partial class Tr
{
    private static readonly Dictionary<string, string> TextsEs = new(StringComparer.Ordinal)
    {
        // ---------- Fenster, Reiter, Abschnitte ----------
        ["Controller"] = "Mandos",
        // ---------- Desktop-Modus, Testseite, Vorlagen, Diagnose ----------
        ["Einblendung beim Verbinden"] = "Aviso al conectar",
        ["Kurze Anzeige am Bildschirmrand mit Spieler, Controller und Akkustand."] = "Breve indicación en el borde de la pantalla con jugador, mando y batería.",
        ["Desktop-Modus"] = "Modo escritorio",
        ["Läuft kein Spiel, steuert der Controller Windows: linker Stick = Maus, rechter Stick = Scrollen, A = Klick, B = Rechtsklick, X = Taskansicht, Y = Bildschirmtastatur, Steuerkreuz = Pfeiltasten, LB/RB = zurück/vor, Start = Enter, Back = Esc, HOME = Startmenü. Back + Start 1 Sekunde halten pausiert ihn. In Vollbildspielen und Programmen mit eigenem Profil ist er automatisch aus."] = "Si no hay ningún juego abierto, el mando controla Windows: stick izquierdo = ratón, stick derecho = desplazar, A = clic, B = clic derecho, X = vista de tareas, Y = teclado en pantalla, cruceta = flechas, LB/RB = atrás/adelante, Start = Intro, Back = Esc, HOME = menú Inicio. Mantén Back + Start 1 segundo para pausarlo. Se desactiva solo en juegos a pantalla completa y en programas con perfil propio.",
        ["Zeigergeschwindigkeit"] = "Velocidad del puntero",
        ["RT gedrückt halten macht den Zeiger langsam und genau."] = "Mantén RT para un puntero lento y preciso.",
        ["Desktop-Steuerung pausiert – Back + Start halten zum Fortsetzen."] = "Control del escritorio en pausa: mantén Back + Start para reanudar.",
        ["Desktop-Steuerung aktiv – der Controller steuert Maus und Tastatur."] = "Control del escritorio activo: el mando controla ratón y teclado.",
        ["Test"] = "Prueba",
        ["Trigger"] = "Gatillos",
        ["Bewegung"] = "Movimiento",
        ["Rundheit"] = "Redondez",
        ["Berichte/s"] = "informes/s",
        ["Vibration testen"] = "Probar vibración",
        ["Kreis zurücksetzen"] = "Reiniciar círculo",
        ["Controller testen"] = "Probar mando",
        ["Sticks einmal langsam ganz im Kreis drehen – die Linie zeigt, wie rund sie laufen. Gedrückte Tasten erscheinen unten in der Anzeige."] = "Gira cada stick una vez despacio por todo el círculo: la línea muestra lo redondo que se mueve. Los botones pulsados aparecen abajo.",
        ["🔇  Ton aus/an"] = "🔇  Silenciar/activar sonido",
        ["⏭  Nächster Titel"] = "⏭  Pista siguiente",
        ["⏮  Vorheriger Titel"] = "⏮  Pista anterior",
        ["🎙  Mikrofon stumm (Win+Alt+K)"] = "🎙  Silenciar micrófono (Win+Alt+K)",
        ["🎙  Discord: Mikrofon stumm (Strg+Umschalt+M)"] = "🎙  Discord: silenciar micrófono (Ctrl+Mayús+M)",
        ["🎧  Discord: Ton aus (Strg+Umschalt+D)"] = "🎧  Discord: ensordecer (Ctrl+Mayús+D)",
        ["🖥  Desktop anzeigen (Win+D)"] = "🖥  Mostrar escritorio (Win+D)",
        ["🗂  Taskansicht (Win+Tab)"] = "🗂  Vista de tareas (Win+Tab)",
        ["↔  Zum letzten Fenster (Alt+Tab)"] = "↔  Última ventana (Alt+Tab)",
        ["Diagnose exportieren"] = "Exportar diagnóstico",
        ["Protokoll, Einstellungen und Systeminfos als ZIP-Datei – zum Anhängen an eine Fehlermeldung. Enthält keine Kopplungsschlüssel."] = "Registro, ajustes e información del sistema en un ZIP, para adjuntar a un informe de error. No contiene claves de emparejamiento.",
        // ---------- Desktop-Widget ----------
        ["Desktop-Widget"] = "Widget de escritorio",
        ["Kleines Kärtchen auf dem Desktop: verbundene Controller, Akku, Verbindung und Ausgabe auf einen Blick. Mit der Maus verschieben, Rechtsklick für Optionen, Doppelklick öffnet N-Connect."] = "Pequeña tarjeta en el escritorio: mandos conectados, batería, conexión y salida de un vistazo. Arrástrala con el ratón, clic derecho para opciones, doble clic abre N-Connect.",
        ["Immer im Vordergrund"] = "Siempre visible",
        ["Widget bleibt über allen Fenstern sichtbar (sonst nur auf dem Desktop)."] = "El widget permanece por encima de todas las ventanas (si no, solo en el escritorio).",
        ["Kompakte Ansicht"] = "Vista compacta",
        ["Eine Zeile je Controller: Spieler, Name und Akku."] = "Una línea por mando: jugador, nombre y batería.",
        ["Deckkraft"] = "Opacidad",
        ["nativ"] = "nativo",
        ["Controller einschalten oder SYNC drücken"] = "Enciende un mando o pulsa SYNC",
        ["N-Connect öffnen"] = "Abrir N-Connect",
        ["Position zurücksetzen"] = "Restablecer posición",
        ["Widget ausblenden"] = "Ocultar widget",
        // ---------- Status-Kopfzeile, Ansicht ----------
        ["Farbschema"] = "Esquema de colores",
        ["Farben für Akzente, Knöpfe, Flächen und Ränder."] = "Colores de acentos, botones, superficies y bordes.",
        ["bereit"] = "listo",
        ["nicht verfügbar"] = "no disponible",
        ["Niedrigster Akku"] = "Batería más baja",
        ["lädt"] = "cargando",
        ["gemischt"] = "mixto",
        ["Original-Controller"] = "Mandos originales",
        ["versteckt"] = "ocultos",
        ["sichtbar"] = "visibles",
        ["HidHide fehlt"] = "falta HidHide",
        ["Groß"] = "Grande",
        ["Kompakt"] = "Compacto",
        ["Einstellungen (optional)"] = "Ajustes (opcional)",
        ["1. Windows und Spiele sehen den Controller als …"] = "1. Windows y los juegos ven el mando como …",
        ["2. Tasten A/B/X/Y"] = "2. Botones A/B/X/Y",
        ["3. Vibration, Sticks, Verbinden, Gyro-Maus"] = "3. Vibración, sticks, conexión, ratón giroscópico",
        ["4. Joy-Con"] = "4. Joy-Con",
        ["4. Joy-Con und Wii"] = "4. Joy-Con y Wii",
        ["Wii-Fernbedienung: Zeiger (Sensorleiste) steuert die Maus"] = "Mando de Wii: el puntero (barra de sensores) mueve el ratón",
        ["Zeiger"] = "Puntero",
        ["kein Zeiger – Sensorleiste nicht im Blick"] = "sin puntero: la barra de sensores no está a la vista",
        ["5. Zielen, Sticks, Trigger, Turbo"] = "5. Apuntar, sticks, gatillos, turbo",
        ["6. Tastenbelegung und Profile  (Taste → Gamepad, Tastatur, Maus, Gyro-Maus, Shift-Ebene)"] =
            "6. Asignación de botones y perfiles  (botón → mando, teclado, ratón, ratón giroscópico, capa Shift)",
        ["Xbox-360-Controller  (empfohlen – läuft mit fast allen Spielen)"] = "Mando de Xbox 360  (recomendado: funciona con casi todos los juegos)",
        ["PlayStation DualShock 4  (mit Bewegungssteuerung/Gyro – für Steam && Emulatoren)"] =
            "PlayStation DualShock 4  (con control por movimiento/giroscopio, para Steam y emuladores)",
        ["Xbox-Belegung  (nach Position: untere Taste = A)"] = "Disposición Xbox  (por posición: botón inferior = A)",
        ["Nintendo-Belegung  (nach Beschriftung: A bleibt A)"] = "Disposición Nintendo  (por etiqueta: A sigue siendo A)",
        ["Vibration"] = "Vibración",
        ["Stärke:"] = "Intensidad:",
        ["Stick-Totzone (alle Controller):"] = "Zona muerta del stick (todos los mandos):",
        ["Beim Verbinden kurz vibrieren"] = "Vibrar brevemente al conectar",
        ["Meldung bei Verbinden"] = "Notificación al conectar",
        ["Wer meldet, wenn ein Controller verbunden oder getrennt wird."] = "Elige quién notifica cuando un mando se conecta o se desconecta.",
        ["„N-Connect“ zeigt den echten Controller-Namen und schaltet die Gerätemeldungen von Windows ab."] = "\"N-Connect\" muestra el nombre real del mando y desactiva las notificaciones de dispositivos de Windows.",
        ["N-Connect (empfohlen)"] = "N-Connect (recomendado)",
        ["N-Connect und Windows"] = "N-Connect y Windows",
        ["Keine"] = "Ninguna",
        ["Gekoppelte Controller per Tastendruck verbinden (ohne SYNC)"] = "Conectar mandos emparejados pulsando un botón (sin SYNC)",
        ["Automatisch mit Windows starten"] = "Iniciar automáticamente con Windows",
        ["Gyro für Emulatoren bereitstellen (Cemuhook/DSU, Port 26760 – wirkt nach Neustart)"] =
            "Proporcionar giroscopio para emuladores (Cemuhook/DSU, puerto 26760; se aplica tras reiniciar)",
        ["Beim Start nach neuer Version suchen (GitHub)"] = "Buscar una nueva versión al iniciar (GitHub)",
        ["Ohne Eingabe automatisch trennen nach:"] = "Desconectar automáticamente sin entrada tras:",
        ["Gyro-Maus-Geschwindigkeit:"] = "Velocidad del ratón giroscópico:",
        ["Sprache / Language:"] = "Idioma / Language:",
        ["Automatisch (wie Windows)"] = "Automático (como Windows)",
        ["nie"] = "nunca",
        ["Zwei Joy-Con automatisch zu einem Controller zusammenfassen"] = "Combinar dos Joy-Con en un solo mando automáticamente",
        ["Gyro beim Paar vom:"] = "Giroscopio del par desde:",
        ["rechter Joy-Con (wie Switch)"] = "Joy-Con derecho (como en Switch)",
        ["linker Joy-Con"] = "Joy-Con izquierdo",
        ["Joy-Con 2 als Maus, wenn er auf dem Tisch liegt"] = "Joy-Con 2 como ratón cuando está sobre la mesa",
        ["Mausgeschwindigkeit:"] = "Velocidad del ratón:",
        ["Maus: links/rechts umkehren"] = "Ratón: invertir izquierda/derecha",
        ["Maus: hoch/runter umkehren"] = "Ratón: invertir arriba/abajo",
        ["Wie an der Switch: SL + SR eine Sekunde halten löst einen Joy-Con aus dem Paar. L am linken und R am rechten einzelnen Joy-Con gleichzeitig drücken verbindet sie wieder zum Paar. Die Wahl wird je Joy-Con gemerkt (auch nach dem nächsten Verbinden). Im Mausmodus: R/L = Linksklick, ZR/ZL = Rechtsklick, Stick drücken = Mittelklick, Stick hoch/runter = Scrollen."] =
            "Como en Switch: mantener SL + SR un segundo separa un Joy-Con del par. Pulsar L en el izquierdo y R en el derecho a la vez los vuelve a unir. La elección se recuerda por Joy-Con (también tras reconectar). En modo ratón: R/L = clic izquierdo, ZR/ZL = clic derecho, pulsar el stick = clic central, stick arriba/abajo = desplazamiento.",
        ["Gyro als rechter Stick:"] = "Giroscopio como stick derecho:",
        ["aus (nur per Taste „Gyro-Stick“)"] = "desactivado (solo mediante un botón «stick giroscópico»)",
        ["immer"] = "siempre",
        ["beim Zielen (solange ZL / linker Trigger gedrückt)"] = "al apuntar (mientras se mantiene ZL / gatillo izquierdo)",
        ["hoch/runter umkehren"] = "invertir arriba/abajo",
        ["Empfindlichkeit:"] = "Sensibilidad:",
        ["Mindestausschlag:"] = "Deflexión mínima:",
        ["Stick-Kennlinie:"] = "Curva del stick:",
        ["Turbo (pro Sekunde):"] = "Turbo (por segundo):",
        ["Analoge Trigger (GameCube) – Totzone:"] = "Gatillos analógicos (GameCube): zona muerta:",
        ["voll gedrückt ab:"] = "pulsado al máximo desde:",
        ["Profil:"] = "Perfil:",
        ["Neu …"] = "Nuevo …",
        ["Umbenennen …"] = "Cambiar nombre …",
        ["Löschen"] = "Eliminar",
        ["Exportieren …"] = "Exportar …",
        ["Importieren …"] = "Importar …",
        ["Aktiv bei Programm:"] = "Activo con el programa:",
        ["Programm wählen …"] = "Elegir programa …",
        ["Standard"] = "Predeterminado",
        ["Standard gilt immer, wenn kein anderes Profil passt"] = "Predeterminado se aplica siempre que ningún otro perfil coincida",
        ["z. B. Cemu.exe, Ryujinx.exe"] = "p. ej. Cemu.exe, Ryujinx.exe",
        ["Ein eigenes Profil wird automatisch aktiv, solange eines seiner Programme im Vordergrund ist (sonst gilt „Standard“). Im Infobereich-Menü lässt sich ein Profil auch fest wählen."] =
            "Un perfil propio se activa automáticamente mientras uno de sus programas esté en primer plano (si no, se aplica «Predeterminado»). En el menú del área de notificación también se puede fijar un perfil.",
        ["Controller:"] = "Mando:",
        ["Eigene Stick-Totzone für diesen Controller:"] = "Zona muerta de stick propia para este mando:",
        ["Normale Belegung"] = "Asignación normal",
        ["Shift-Ebene (gilt, solange eine Taste mit „Shift-Ebene“ gehalten wird)"] = "Capa Shift (se aplica mientras se mantiene un botón con «capa Shift»)",
        ["Alles auf Standard"] = "Restablecer todo",
        ["Schließen"] = "Cerrar",
        ["wie normale Belegung"] = "como la asignación normal",

        // ---------- Belegungsziele und Vorlagen ----------
        ["— keine Funktion —"] = "— sin función —",
        ["A (Xbox) / Kreuz (PS)"] = "A (Xbox) / Cruz (PS)",
        ["B (Xbox) / Kreis (PS)"] = "B (Xbox) / Círculo (PS)",
        ["X (Xbox) / Viereck (PS)"] = "X (Xbox) / Cuadrado (PS)",
        ["Y (Xbox) / Dreieck (PS)"] = "Y (Xbox) / Triángulo (PS)",
        ["Ansicht (Back) / Share"] = "Ver (Back) / Share",
        ["Menü (Start) / Options"] = "Menú (Start) / Options",
        ["Xbox-Taste / PS-Taste"] = "Botón Xbox / botón PS",
        ["Linker Stick-Klick"] = "Clic del stick izquierdo",
        ["Rechter Stick-Klick"] = "Clic del stick derecho",
        ["Steuerkreuz hoch"] = "Cruceta arriba",
        ["Steuerkreuz runter"] = "Cruceta abajo",
        ["Steuerkreuz links"] = "Cruceta izquierda",
        ["Steuerkreuz rechts"] = "Cruceta derecha",
        ["Touchpad-Klick (nur DualShock 4)"] = "Clic del touchpad (solo DualShock 4)",
        ["🖱  Maus: Linksklick"] = "🖱  Ratón: clic izquierdo",
        ["🖱  Maus: Rechtsklick"] = "🖱  Ratón: clic derecho",
        ["🖱  Maus: Mittelklick"] = "🖱  Ratón: clic central",
        ["🎯  Gyro-Maus (solange gehalten)"] = "🎯  Ratón giroscópico (mientras se mantiene)",
        ["🎯  Gyro-Maus ein/aus"] = "🎯  Ratón giroscópico activar/desactivar",
        ["🎯  Gyro als rechter Stick (solange gehalten)"] = "🎯  Giroscopio como stick derecho (mientras se mantiene)",
        ["🎯  Gyro als rechter Stick ein/aus"] = "🎯  Giroscopio como stick derecho activar/desactivar",
        ["⇧  Shift-Ebene (solange gehalten)"] = "⇧  Capa Shift (mientras se mantiene)",
        ["🔁  Turbo / Dauerfeuer …"] = "🔁  Turbo / fuego rápido …",
        ["⏯  Makro (Tastenfolge) …"] = "⏯  Macro (secuencia de botones) …",
        ["📷  Bildschirmfoto speichern (Win+Druck)"] = "📷  Guardar captura de pantalla (Win+Impr Pant)",
        ["📷  Bildschirmausschnitt (Win+Umschalt+S)"] = "📷  Recorte de pantalla (Win+Mayús+S)",
        ["⏺  Letzte 30 Sekunden aufnehmen (Win+Alt+G)"] = "⏺  Grabar los últimos 30 segundos (Win+Alt+G)",
        ["⏺  Aufnahme starten/stoppen (Win+Alt+R)"] = "⏺  Iniciar/detener grabación (Win+Alt+R)",
        ["🎮  Xbox Game Bar (Win+G)"] = "🎮  Xbox Game Bar (Win+G)",
        ["🔊  Lauter"] = "🔊  Subir volumen",
        ["🔉  Leiser"] = "🔉  Bajar volumen",
        ["⏯  Wiedergabe/Pause"] = "⏯  Reproducir/pausar",
        ["⌨  Andere Taste / Tastenkombination aufnehmen …"] = "⌨  Registrar otra tecla / combinación de teclas …",

        // ---------- Tastennamen ----------
        ["+ (Plus)"] = "+ (Plus)",
        ["− (Minus)"] = "− (Minus)",
        ["Aufnahme"] = "Captura",
        ["GL (Rücktaste links)"] = "GL (botón trasero izquierdo)",
        ["GR (Rücktaste rechts)"] = "GR (botón trasero derecho)",
        ["Linker Stick drücken"] = "Pulsar stick izquierdo",
        ["Rechter Stick drücken"] = "Pulsar stick derecho",
        ["Stick drücken"] = "Pulsar stick",
        ["A (groß, unten)"] = "A (grande, abajo)",
        ["B (links)"] = "B (izquierda)",
        ["X (rechts)"] = "X (derecha)",
        ["Y (oben)"] = "Y (arriba)",
        ["L (ganz durchgedrückt)"] = "L (pulsado del todo)",
        ["R (ganz durchgedrückt)"] = "R (pulsado del todo)",
        ["untere Taste (quer)"] = "botón inferior (de lado)",
        ["rechte Taste (quer)"] = "botón derecho (de lado)",
        ["linke Taste (quer)"] = "botón izquierdo (de lado)",
        ["obere Taste (quer)"] = "botón superior (de lado)",
        ["1 (quer) / Classic Y"] = "1 (de lado) / Classic Y",
        ["2 (quer) / Classic B"] = "2 (de lado) / Classic B",
        ["B (Abzug) / Classic ZR"] = "B (gatillo) / Classic ZR",
        ["Kreuz (unten)"] = "Cruz (abajo)",
        ["Kreis (rechts)"] = "Círculo (derecha)",
        ["Viereck (links)"] = "Cuadrado (izquierda)",
        ["Dreieck (oben)"] = "Triángulo (arriba)",
        ["PS-Taste"] = "Botón PS",
        ["Touchpad-Klick"] = "Clic del touchpad",
        ["Mikro stumm"] = "Silenciar micro",
        ["Fn links (Edge)"] = "Fn izquierdo (Edge)",
        ["Rücktaste links (Edge)"] = "Botón trasero izquierdo (Edge)",
        ["Rücktaste rechts (Edge)"] = "Botón trasero derecho (Edge)",
        ["L3 (Stick drücken)"] = "L3 (pulsar stick)",
        ["R3 (Stick drücken)"] = "R3 (pulsar stick)",
        ["Ansicht/Zurück"] = "Ver/Atrás",
        ["Menü/Start"] = "Menú/Inicio",
        ["Xbox-Taste"] = "Botón Xbox",

        // ---------- Controller-Namen ----------
        ["Wii-Fernbedienung"] = "Mando de Wii",
        ["Xbox-Controller"] = "Mando de Xbox",
        ["Xbox-Controller (Microsoft)"] = "Mando de Xbox (Microsoft)",
        ["XInput (USB, Bluetooth oder Xbox-Adapter)"] = "XInput (USB, Bluetooth o adaptador Xbox)",

        // ---------- Übersicht / Karten ----------
        ["Trennen"] = "Desconectar",
        ["Vibrieren"] = "Vibrar",
        ["Gyro kalibrieren"] = "Calibrar giroscopio",
        ["Ruhig liegen lassen …"] = "Dejarlo quieto …",
        ["Kalibriert ✓"] = "Calibrado ✓",
        ["Hochkant halten"] = "Sostener vertical",
        ["Quer halten"] = "Sostener de lado",
        ["Joy-Con trennen"] = "Separar Joy-Con",
        ["Zum Paar verbinden"] = "Combinar en un par",
        ["Joy-Con trennen – beide werden einzelne Controller"] = "Separar Joy-Con – ambos pasan a ser mandos individuales",
        ["Zum Paar verbinden – sucht einen freien Joy-Con"] = "Combinar en un par – busca un Joy-Con libre",
        ["Doppelt angezeigt? Verstecken"] = "¿Se muestra dos veces? Ocultar",
        ["amiibo lesen"] = "Leer amiibo",
        ["Ring-Con ein"] = "Activar Ring-Con",
        ["Ring-Con aus"] = "Desactivar Ring-Con",
        ["Ring-Con wird gesucht …"] = "Buscando Ring-Con …",
        ["IR-Kamera"] = "Cámara IR",
        ["Akku"] = "Batería",
        ["Verbindung"] = "Conexión",
        ["Adresse"] = "Dirección",
        ["Seriennummer"] = "Número de serie",
        ["Griff"] = "Grip",
        ["Maus"] = "Ratón",
        ["Gedrückt"] = "Pulsado",
        ["unbekannt"] = "desconocido",
        ["Charging Grip – GL/GR aktiv"] = "Charging Grip: GL/GR activos",
        ["aktiv (liegt auf dem Tisch)"] = "activo (sobre la mesa)",
        ["bereit – zum Benutzen auf den Tisch legen"] = "listo: colócalo sobre la mesa para usarlo",
        ["Bluetooth LE"] = "Bluetooth LE",
        ["Bewegungssensor: keine Daten"] = "Sensor de movimiento: sin datos",
        ["quer halten: Steuerkreuz links,\n1 und 2 rechts"] = "de lado: cruceta a la izquierda,\n1 y 2 a la derecha",

        // ---------- Tooltips ----------
        ["Verbindung trennen. Der Controller verbindet sich beim nächsten Tastendruck wieder."] =
            "Desconectar. El mando se reconecta con la siguiente pulsación.",
        ["Controller kurz vibrieren lassen – zeigt, welcher Controller dieser Spieler ist."] =
            "Hacer vibrar el mando brevemente: muestra qué mando es de este jugador.",
        ["Controller ruhig auf den Tisch legen und klicken: misst den Gyro-Nullpunkt neu (gegen Abdriften)."] =
            "Dejar el mando quieto sobre la mesa y hacer clic: mide de nuevo el punto cero del giroscopio (contra la deriva).",
        ["Einzelnen Joy-Con quer (wie an der Switch) oder hochkant halten – wird je Joy-Con gemerkt. Hochkant gilt die Tastenbelegung von „Joy-Con-Paar“."] =
            "Sostener un Joy-Con suelto de lado (como en Switch) o vertical; se recuerda por Joy-Con. En vertical se usa la asignación de «par de Joy-Con».",
        ["Versteckt den per USB angeschlossenen Controller vor Spielen (HidHide), damit sie nur den virtuellen Xbox-Controller sehen."] =
            "Oculta el mando conectado por USB a los juegos (HidHide), para que solo vean el mando Xbox virtual.",
        ["amiibo mit dem NFC-Leser lesen und als Datei (.bin) speichern – z. B. für Emulatoren."] =
            "Leer un amiibo con el lector NFC y guardarlo como archivo (.bin), p. ej. para emuladores.",
        ["Ring-Con am rechten Joy-Con ein-/ausschalten: zusammendrücken = rechter Trigger, auseinanderziehen = linker Trigger. Beim Einschalten den Ring nicht berühren."] =
            "Activar/desactivar el Ring-Con del Joy-Con derecho: apretar = gatillo derecho, estirar = gatillo izquierdo. No tocar el aro al activarlo.",
        ["Live-Bild der IR-Kamera im rechten Joy-Con anzeigen."] = "Mostrar la imagen en vivo de la cámara IR del Joy-Con derecho.",
        ["Links = empfindlicher (kleine Drehung, großer Ausschlag), rechts = ruhiger."] = "Izquierda = más sensible (giro pequeño, gran deflexión), derecha = más suave.",
        ["Mindestausschlag des Sticks bei Bewegung – überwindet die Totzone des Spiels."] = "Deflexión mínima del stick al moverse: supera la zona muerta del juego.",
        ["Mitte = linear. Rechts = feiner um die Mitte (präzises Zielen), links = schneller."] = "Centro = lineal. Derecha = más fino cerca del centro (apuntar con precisión), izquierda = más rápido.",
        ["So weit lässt sich ein analoger Trigger drücken, bevor er wirkt."] = "Hasta dónde se puede pulsar un gatillo analógico antes de que actúe.",
        ["Ab hier gilt der Trigger als ganz gedrückt (100 = erst am Anschlag)."] = "Desde aquí el gatillo cuenta como pulsado al máximo (100 = solo al tope).",
        ["Wie oft pro Sekunde Tasten mit „Turbo“ auslösen."] = "Cuántas veces por segundo disparan los botones con «turbo».",

        // ---------- Infobereich ----------
        ["ViGEmBus-Treiber fehlt"] = "Falta el controlador ViGEmBus",
        ["ViGEmBus herunterladen …"] = "Descargar ViGEmBus …",
        ["Verbinde …"] = "Conectando …",
        ["Kein Controller – SYNC-Taste am Controller kurz drücken"] = "Ningún mando: pulsa brevemente el botón SYNC del mando",
        ["Ausgabe als"] = "Salida como",
        ["Xbox-360-Controller (empfohlen)"] = "Mando de Xbox 360 (recomendado)",
        ["DualShock 4 (mit Gyro für Steam/Emulatoren)"] = "DualShock 4 (con giroscopio para Steam/emuladores)",
        ["Tastenbelegung"] = "Asignación de botones",
        ["Xbox-Belegung (untere Taste = A)"] = "Disposición Xbox (botón inferior = A)",
        ["Switch-2-Pro-Belegung (A bleibt A)"] = "Disposición Nintendo (A sigue siendo A)",
        ["Automatisch (nach Spiel/Programm)"] = "Automático (según juego/programa)",
        ["Mit Windows starten"] = "Iniciar con Windows",
        ["Einstellungen …"] = "Ajustes …",
        ["Kurzanleitung"] = "Guía rápida",
        ["Protokoll öffnen"] = "Abrir registro",
        ["Beenden"] = "Salir",
        ["N-Connect: warte auf Controller (SYNC drücken)"] = "N-Connect: esperando un mando (pulsa SYNC)",
        ["N-Connect: ViGEmBus fehlt"] = "N-Connect: falta ViGEmBus",
        ["Neue Version verfügbar"] = "Nueva versión disponible",
        ["Einstellungen fehlerhaft"] = "Ajustes dañados",
        ["settings.json konnte nicht gelesen werden – es gelten die Standardwerte."] = "No se pudo leer settings.json; se aplican los valores predeterminados.",
        ["Ohne ViGEmBus kann kein virtueller Controller erzeugt werden. Bitte das Setup erneut ausführen oder ViGEmBus installieren (Rechtsklick auf das Symbol → ViGEmBus herunterladen)."] =
            "Sin ViGEmBus no se puede crear un mando virtual. Ejecuta de nuevo el instalador o instala ViGEmBus (clic derecho en el icono → Descargar ViGEmBus).",

        // ---------- Dialoge ----------
        ["Tastatur-Taste festlegen"] = "Asignar tecla del teclado",
        ["Übernehmen"] = "Aplicar",
        ["Abbrechen"] = "Cancelar",
        ["Ja"] = "Sí",
        ["Nein"] = "No",
        ["Turbo / Dauerfeuer"] = "Turbo / fuego rápido",
        ["Tastatur-Taste aufnehmen …"] = "Registrar tecla del teclado …",
        ["Makro (Tastenfolge)"] = "Macro (secuencia de botones)",
        ["Ungültig – bitte Schreibweise prüfen (siehe oben)."] = "No válido: revisa la sintaxis (ver arriba).",
        ["Neues Profil"] = "Nuevo perfil",
        ["Name des Profils (z. B. der Spielname):"] = "Nombre del perfil (p. ej. el nombre del juego):",
        ["Profil umbenennen"] = "Cambiar nombre del perfil",
        ["Neuer Name:"] = "Nuevo nombre:",
        ["Ein Profil mit diesem Namen gibt es schon."] = "Ya existe un perfil con este nombre.",
        ["Die Datei enthält kein gültiges Controller-Profil."] = "El archivo no contiene un perfil de mando válido.",
        ["Alle Einstellungen und Tastenbelegungen auf Standard zurücksetzen?"] = "¿Restablecer todos los ajustes y asignaciones de botones?",
        ["Suche …"] = "Buscando …",
        ["Kein Bluetooth-Adapter gefunden."] = "No se encontró ningún adaptador Bluetooth.",
        ["IR-Kamera (Joy-Con R)"] = "Cámara IR (Joy-Con D)",
        ["Auflösung:"] = "Resolución:",
        ["40 × 30 (schnell)"] = "40 × 30 (rápido)",
        ["320 × 240 (langsam)"] = "320 × 240 (lento)",
        ["Kamera startet …"] = "Iniciando cámara …",
        ["läuft – Joy-Con auf eine Lichtquelle oder die Hand richten"] = "en marcha: apunta el Joy-Con a una fuente de luz o a tu mano",
        ["Kamera startet nicht (Details im Protokoll)"] = "La cámara no arranca (detalles en el registro)",
        ["Kein Ring-Con gefunden. Den rechten Joy-Con (Switch 1) fest in den Ring-Con schieben und erneut versuchen."] =
            "No se encontró ningún Ring-Con. Inserta firmemente el Joy-Con derecho (Switch 1) en el Ring-Con e inténtalo de nuevo.",
        ["Kein amiibo erkannt. Bitte das amiibo flach an den NFC-Leser halten (Joy-Con: auf den rechten Stick, Pro Controller: auf das NFC-Logo) und erneut versuchen."] =
            "No se detectó ningún amiibo. Acerca el amiibo al lector NFC (Joy-Con: sobre el stick derecho; Pro Controller: sobre el logotipo NFC) e inténtalo de nuevo.",
        ["NFC-Leser wird eingeschaltet …"] = "Activando el lector NFC …",
        ["amiibo an den Leser halten (rechter Stick des Joy-Con bzw. NFC-Logo des Pro Controllers) …"] =
            "Acerca el amiibo al lector (stick derecho del Joy-Con o logotipo NFC del Pro Controller) …",
        ["amiibo speichern"] = "Guardar amiibo",
        ["Doppelte Controller verhindern"] = "Evitar mandos duplicados",
        ["Dafür wird das kostenlose Programm HidHide gebraucht (von den Machern von ViGEmBus).\n\nJetzt die Download-Seite öffnen? Nach der Installation hier erneut klicken."] =
            "Para ello se necesita el programa gratuito HidHide (de los creadores de ViGEmBus).\n\n¿Abrir la página de descarga ahora? Vuelve a hacer clic aquí tras instalarlo.",
        ["HidHide konnte nicht eingerichtet werden (abgebrochen oder fehlgeschlagen). Details im Protokoll."] =
            "No se pudo configurar HidHide (cancelado o fallido). Detalles en el registro.",
        ["Der Controller hat sich bewegt oder keine Bewegungsdaten geliefert.\nBitte flach auf den Tisch legen, nicht berühren und erneut versuchen."] =
            "El mando se movió o no envió datos de movimiento.\nDéjalo plano sobre la mesa, no lo toques e inténtalo de nuevo.",
        ["Spiel oder Programm wählen"] = "Elegir juego o programa",
        ["Profil exportieren"] = "Exportar perfil",
        ["Profil importieren"] = "Importar perfil",
        ["Verstanden"] = "Entendido",
        ["Einstellungen öffnen"] = "Abrir ajustes",
        ["Willkommen"] = "Bienvenido",

        // ---------- Neues Hauptfenster (Navigation, Seiten, Zeilen) ----------
        ["Allgemein"] = "General",
        ["Sticks & Vibration"] = "Sticks y vibración",
        ["Gyro & Maus"] = "Giroscopio y ratón",
        ["Joy-Con & Wii"] = "Joy-Con y Wii",
        ["Ein"] = "Sí",
        ["Aus"] = "No",
        ["Verbundene Controller mit Live-Anzeige. Über „Einstellungen“ an einem Controller passt du genau diesen an."] =
            "Mandos conectados con vista en vivo. Con «Ajustes» en un mando configuras exactamente ese.",
        ["Jede Taste kann ein Gamepad-Knopf, eine Tastaturtaste, ein Mausklick, Turbo oder ein Makro sein. " +
         "Tipp: Drückst du eine Taste am Controller, wird ihre Zeile hervorgehoben."] =
            "Cada botón puede ser un botón de mando, una tecla, un clic de ratón, turbo o una macro. " +
            "Consejo: pulsa un botón en el mando para resaltar su fila.",
        ["Profil"] = "Perfil",
        ["Neu"] = "Nuevo",
        ["Umbenennen, löschen, exportieren, importieren"] = "Cambiar nombre, eliminar, exportar, importar",
        ["Ein eigenes Profil gilt automatisch, solange eines seiner Programme im Vordergrund ist – sonst „Standard“."] =
            "Un perfil propio se aplica automáticamente mientras uno de sus programas esté en primer plano; si no, «Predeterminado».",
        ["Aktiv bei Programm"] = "Activo con el programa",
        ["Programmdateien, bei denen dieses Profil gilt (mit Komma trennen)."] = "Archivos de programa para los que se aplica este perfil (separar con comas).",
        ["Standard gilt für alle Programme"] = "Predeterminado se aplica a todos los programas",
        ["Wählen …"] = "Elegir …",
        ["Bearbeiten"] = "Editar",
        ["Jeder Controller hat seine eigene Belegung."] = "Cada mando tiene su propia asignación.",
        ["Ebene"] = "Capa",
        ["Normal"] = "Normal",
        ["Shift-Ebene"] = "Capa Shift",
        ["Die Shift-Ebene gilt, solange eine Taste mit „Shift-Ebene“ gehalten wird."] = "La capa Shift se aplica mientras se mantiene un botón configurado como «capa Shift».",
        ["Tasten"] = "Botones",
        ["Standardwerte für alle Controller. Eigene Werte für einzelne Controller stellst du unten oder in der Übersicht ein."] =
            "Valores predeterminados para todos los mandos. Define valores propios para mandos concretos abajo o en la vista general.",
        ["Sticks"] = "Sticks",
        ["Totzone"] = "Zona muerta",
        ["So weit lässt sich ein Stick bewegen, bevor er wirkt (gegen Abdriften)."] = "Hasta dónde puede moverse un stick antes de responder (contra la deriva).",
        ["Kennlinie"] = "Curva de respuesta",
        ["„linear“ = gleichmäßig. Höher = feiner um die Mitte (präzises Zielen), niedriger = schneller."] =
            "«lineal» = uniforme. Más alto = más fino cerca del centro (apuntar con precisión), más bajo = más rápido.",
        ["Analoge Trigger (GameCube)"] = "Gatillos analógicos (GameCube)",
        ["So weit lässt sich ein Trigger drücken, bevor er wirkt."] = "Hasta dónde se puede pulsar un gatillo antes de que responda.",
        ["Voll gedrückt ab"] = "Pulsado al máximo desde",
        ["Ab hier gilt der Trigger als ganz gedrückt (100 % = erst am Anschlag)."] = "Desde aquí el gatillo cuenta como pulsado del todo (100 % = solo al tope).",
        ["Spiele dürfen den Controller vibrieren lassen."] = "Los juegos pueden hacer vibrar el mando.",
        ["Stärke"] = "Intensidad",
        ["Turbo-Geschwindigkeit"] = "Velocidad de turbo",
        ["Wie oft pro Sekunde Tasten mit „Turbo“ auslösen."] = "Cuántas veces por segundo disparan los botones configurados como «turbo».",
        ["Eigene Werte je Controller"] = "Valores propios por mando",
        ["Werte nur für diesen Controller – ohne eigenen Wert gilt der allgemeine."] = "Valores solo para este mando; sin valor propio se aplica el general.",
        ["Bewegungssteuerung: Zielen per Gyro und den Controller als Maus nutzen."] = "Controles por movimiento: apuntar con el giroscopio y usar el mando como ratón.",
        ["Gyro als rechter Stick"] = "Giroscopio como stick derecho",
        ["Modus"] = "Modo",
        ["Zum Zielen in Spielen ohne eigene Gyro-Steuerung. „Gyro-Stick“ kann auch einer Taste zugewiesen werden."] =
            "Para apuntar en juegos sin control giroscópico propio. «Stick giroscópico» también se puede asignar a un botón.",
        ["Aus (nur per Taste „Gyro-Stick“)"] = "Desactivado (solo mediante un botón «stick giroscópico»)",
        ["Immer"] = "Siempre",
        ["Beim Zielen (solange ZL / LT gedrückt)"] = "Al apuntar (mientras se mantiene ZL / LT)",
        ["Empfindlichkeit"] = "Sensibilidad",
        ["Drehgeschwindigkeit für vollen Stick-Ausschlag – kleiner = empfindlicher."] = "Velocidad de giro para una deflexión completa del stick: más bajo = más sensible.",
        ["Mindestausschlag"] = "Deflexión mínima",
        ["Überwindet die Stick-Totzone des Spiels bei kleinen Bewegungen."] = "Supera la zona muerta del stick del juego en movimientos pequeños.",
        ["Hoch/runter umkehren"] = "Invertir arriba/abajo",
        ["Links/rechts umkehren"] = "Invertir izquierda/derecha",
        ["Gyro-Maus"] = "Ratón giroscópico",
        ["Geschwindigkeit"] = "Velocidad",
        ["Mauszeiger per Bewegung – über eine Taste mit „Gyro-Maus“ (Tastenbelegung)."] = "Puntero del ratón por movimiento, mediante un botón configurado como «ratón giroscópico» (asignación de botones).",
        ["Mausrichtung (Gyro-Maus und Joy-Con-Maus)"] = "Dirección del ratón (ratón giroscópico y ratón Joy-Con)",
        ["Gyro-Funktionen einer Taste zuweisen"] = "Asignar funciones del giroscopio a un botón",
        ["Gyro-Maus oder Gyro-Stick ein/aus bzw. solange gehalten"] = "Ratón giroscópico o stick giroscópico activar/desactivar o mientras se mantiene",
        ["Joy-Con als Paar oder einzeln, Joy-Con 2 als Maus und Wii-Controller."] = "Joy-Con en par o por separado, Joy-Con 2 como ratón y mandos de Wii.",
        ["Zu einem Controller zusammenfassen"] = "Combinar en un solo mando",
        ["Ein linker und ein rechter Joy-Con werden automatisch ein Paar."] = "Un Joy-Con izquierdo y uno derecho forman un par automáticamente.",
        ["Gyro beim Paar vom"] = "Giroscopio del par desde",
        ["Rechter Joy-Con (wie Switch)"] = "Joy-Con derecho (como en Switch)",
        ["Linker Joy-Con"] = "Joy-Con izquierdo",
        ["Paar lösen oder verbinden"] = "Separar o unir un par",
        ["Einen Joy-Con quer halten und SL oder SR drücken löst ihn aus dem Paar. L am linken und R am rechten Joy-Con gleichzeitig drücken verbindet sie wieder. Die Wahl wird je Joy-Con gemerkt."] =
            "Sostener un Joy-Con de lado y pulsar SL o SR lo separa del par. Pulsar L en el izquierdo y R en el derecho a la vez los vuelve a unir. La elección se recuerda por Joy-Con.",
        ["Joy-Con 2 als Maus"] = "Joy-Con 2 como ratón",
        ["Als Maus, wenn er auf dem Tisch liegt"] = "Como ratón cuando está sobre la mesa",
        ["Joy-Con 2 auf die Seite legen und wie eine Maus schieben."] = "Coloca el Joy-Con 2 de lado y deslízalo como un ratón.",
        ["Mausgeschwindigkeit"] = "Velocidad del ratón",
        ["Tasten im Mausmodus"] = "Botones en modo ratón",
        ["R/L = Linksklick, ZR/ZL = Rechtsklick, Stick drücken = Mittelklick, Stick hoch/runter = Scrollen."] =
            "R/L = clic izquierdo, ZR/ZL = clic derecho, pulsar stick = clic central, stick arriba/abajo = desplazamiento.",
        ["Zeiger steuert die Maus"] = "El puntero mueve el ratón",
        ["Wii-Fernbedienung auf die Sensorleiste richten, um den Mauszeiger zu bewegen."] = "Apunta el mando de Wii a la barra de sensores para mover el puntero del ratón.",
        ["Wie Spiele die Controller sehen, Verbindung, Darstellung und Programm."] = "Cómo ven los juegos los mandos, conexión, apariencia y programa.",
        ["Ausgabe"] = "Salida",
        ["Controller erscheint als"] = "El mando aparece como",
        ["Xbox 360 läuft mit fast allen Spielen. DualShock 4 bietet Bewegungssteuerung (Steam, Emulatoren)."] =
            "Xbox 360 funciona con casi todos los juegos. DualShock 4 ofrece control por movimiento (Steam, emuladores).",
        ["Xbox 360 läuft mit fast allen Spielen und Steam. DualShock 4 bietet zusätzlich Bewegungssteuerung (Steam, Emulatoren). Gilt für alle Controller ohne eigene Einstellung (Karte → Einstellungen → Tasten)."] =
            "Xbox 360 funciona con casi todos los juegos y Steam. DualShock 4 añade control por movimiento (Steam, emuladores). Se aplica a todos los mandos sin ajuste propio (tarjeta → Ajustes → Botones).",
        ["Original-Controller verstecken"] = "Ocultar mandos originales",
        ["Controller verbinden"] = "Conectar mandos",
        ["SYNC-Taste am Controller drücken – N-Connect findet und koppelt ihn selbst. Danach reicht künftig ein Tastendruck."] =
            "Pulsa el botón SYNC del mando: N-Connect lo encuentra y lo empareja por sí mismo. A partir de entonces basta una pulsación.",
        ["So kommt der Controller in den Kopplungsmodus"] = "Cómo poner el mando en modo de emparejamiento",
        ["Switch 2: Pro Controller, Joy-Con 2, GameCube"] = "Switch 2: Pro Controller, Joy-Con 2, GameCube",
        ["Kurz die kleine SYNC-Taste drücken."] = "Pulsa brevemente el pequeño botón SYNC.",
        ["Switch 1: Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive"] = "Switch 1: Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive",
        ["SYNC-Taste drücken, bis die Lichter laufen."] = "Pulsa el botón SYNC hasta que las luces se muevan.",
        ["Batteriefach öffnen und die rote SYNC-Taste drücken."] = "Abre el compartimento de las pilas y pulsa el botón SYNC rojo.",
        ["Die SYNC-Taste auf der Unterseite drücken."] = "Pulsa el botón SYNC de la parte inferior.",
        ["PlayStation: DualShock 4, DualSense"] = "PlayStation: DualShock 4, DualSense",
        ["PS + Teilen bzw. Create halten, bis die Lichtleiste schnell blinkt."] =
            "Mantén PS + Share/Create hasta que la barra luminosa parpadee rápidamente.",
        ["Xbox über Bluetooth: One S, Series X|S, Elite"] = "Xbox por Bluetooth: One S, Series X|S, Elite",
        ["Kopplungstaste oben halten, bis die Xbox-Taste blinkt."] = "Mantén el botón de emparejamiento superior hasta que el botón Xbox parpadee.",
        ["Status"] = "Estado",
        ["Suche läuft …"] = "Buscando …",
        ["Suche läuft – jetzt SYNC drücken …"] = "Buscando: pulsa SYNC ahora …",
        ["Weitere Controller? Einfach SYNC drücken."] = "¿Más mandos? Solo pulsa SYNC.",
        ["Wartet auf einen Controller im Kopplungsmodus."] = "Esperando un mando en modo de emparejamiento.",
        ["Suche beendet"] = "Búsqueda finalizada",
        ["Die Controller stehen in der Übersicht und verbinden sich künftig per Tastendruck."] =
            "Los mandos aparecen en la vista general y se conectarán con una pulsación.",
        ["Kein Controller im Kopplungsmodus gefunden. SYNC-Taste drücken und „Erneut suchen“ klicken."] =
            "No se encontró ningún mando en modo de emparejamiento. Pulsa SYNC y haz clic en «Buscar de nuevo».",
        ["Verbunden"] = "Conectado",
        ["Erneut suchen"] = "Buscar de nuevo",
        ["Fertig"] = "Hecho",
        ["Im Spiel"] = "En el juego",
        ["Dreht …"] = "Girando …",
        ["Testdrehung (360°)"] = "Giro de prueba (360°)",
        ["Testdrehung"] = "Giro de prueba",
        ["aus"] = "desactivado",
        ["Gyro-Beschleunigung"] = "Aceleración del giroscopio",
        ["Bei schneller Drehung"] = "En giros rápidos",
        ["Langsame Bewegungen bleiben fein, schnelle drehen weiter (wie JoyShockMapper). Voll ab 120 °/s, unter 20 °/s normal. Gilt für Gyro-Stick und Gyro-Maus."] =
            "Los movimientos lentos siguen siendo precisos, los rápidos giran más (como JoyShockMapper). Máximo desde 120 °/s, normal por debajo de 20 °/s. Se aplica al stick giroscópico y al ratón giroscópico.",
        ["Flick-Stick (Spiele mit Maussteuerung)"] = "Flick stick (juegos con control de ratón)",
        ["Flick-Stick"] = "Flick stick",
        ["Rechten Stick in eine Richtung schieben = Kamera dreht sofort dorthin; am Rand drehen = Kamera dreht mit. Zielen dann per Gyro. Der rechte Stick geht nicht mehr ans Spiel."] =
            "Empujar el stick derecho en una dirección = la cámara gira allí al instante; girarlo por el borde = la cámara sigue. Luego apunta con el giroscopio. El stick derecho ya no se envía al juego.",
        ["Mausbewegung je Umdrehung"] = "Movimiento de ratón por vuelta",
        ["Je Spiel einmal einstellen: „Testdrehung“ klicken, ins Spiel wechseln – nach 3 s dreht die Kamera einmal. Genau eine volle Drehung = richtig."] =
            "Ajustar una vez por juego: haz clic en «Giro de prueba», cambia al juego; tras 3 s la cámara gira una vez. Exactamente una vuelta completa = correcto.",
        ["Flick-Dauer"] = "Duración del flick",
        ["So lange dauert die Drehung beim Flick (0 = sofort)."] = "Cuánto dura el giro de un flick (0 = instantáneo).",
        ["Gyro-Maus oder Gyro-Stick ein/aus bzw. solange gehalten, „Gyro anhalten“ (Ratchet: Controller zurückführen, ohne dass sich das Ziel bewegt)"] =
            "Ratón giroscópico o stick giroscópico activar/desactivar o mientras se mantiene, «pausar giroscopio» (ratchet: volver el mando a su sitio sin mover el objetivo)",
        ["✋  Gyro anhalten (solange gehalten, „Ratchet“)"] = "✋  Pausar giroscopio (mientras se mantiene, «ratchet»)",
        ["Spieler-LED und Lichtleiste vom Spiel"] = "LED de jugador y barra luminosa del juego",
        ["Die Spieler-LEDs zeigen den Xbox-Platz, den Windows vergibt. Bei DualShock 4 steuert die Lichtleiste des Spiels die HOME-LED (Switch 1 Pro Controller, rechter Joy-Con)."] =
            "Los LED de jugador muestran la posición Xbox que asigna Windows. En DualShock 4, la barra luminosa del juego controla el LED HOME (Pro Controller de Switch 1, Joy-Con derecho).",
        ["HidHide installieren …"] = "Instalar HidHide …",
        ["Empfohlen: Steam und viele Spiele kennen Switch-1-, NSO- und USB-Controller selbst und sähen sie sonst doppelt. Läuft nach der Installation ohne Rückfrage (sonst fragt Windows nach Adminrechten)."] =
            "Recomendado: Steam y muchos juegos reconocen por sí mismos mandos de Switch 1, NSO y USB y los verían dos veces. Funciona sin preguntas tras la instalación (si no, Windows pedirá derechos de administrador).",
        ["Steam und viele Spiele sehen Switch-1-, NSO- und USB-Controller sonst doppelt. Dafür wird das kostenlose HidHide gebraucht (bei der N-Connect-Installation dabei, hier nachträglich)."] =
            "Si no, Steam y muchos juegos verán dos veces los mandos de Switch 1, NSO y USB. Para ello se necesita el gratuito HidHide (incluido en la instalación de N-Connect, instálalo aquí después).",
        ["Erscheint als"] = "Aparece como",
        ["Wie allgemein"] = "Como en General",
        ["Nur für diesen Controller. Xbox 360 läuft überall; DualShock 4 bringt zusätzlich Gyro nach Steam und in Emulatoren. „Wie allgemein“ folgt der Seite „Allgemein“."] =
            "Solo para este mando. Xbox 360 funciona en todas partes; DualShock 4 añade giroscopio en Steam y emuladores. «Como en General» sigue la página «General».",
        ["Der echte Xbox-Controller – Spiele sehen ihn von Windows aus direkt. Belegungen hier wirken auf Sonderaktionen (Tastatur, Makros, Gyro), nicht auf den Controller selbst."] =
            "El mando Xbox real: los juegos ya lo ven directamente desde Windows. Las asignaciones aquí se aplican a acciones especiales (teclado, macros, giroscopio), no al mando en sí.",
        ["Steam und manche Spiele sehen diesen Controller sonst doppelt. Abhilfe: HidHide installieren (Seite „Allgemein“ → „Original-Controller verstecken“)."] =
            "Si no, Steam y algunos juegos verán este mando dos veces. Solución: instalar HidHide (página «General» → «Ocultar mandos originales»).",
        ["Original-Controller vor Spielen versteckt. Steam bitte einmal neu starten – danach sieht es nur noch den virtuellen Controller."] =
            "Mandos originales ocultos a los juegos. Reinicia Steam una vez; después solo verá el mando virtual.",
        ["Original-Controller vor Spielen versteckt – Steam und Spiele sehen nur noch den virtuellen Controller."] =
            "Mandos originales ocultos a los juegos: Steam y los juegos ahora solo ven el mando virtual.",
        ["Original-Controller nicht versteckt (Abfrage abgebrochen). Nachholen: Controller → Einstellungen → Extras → „Doppelt angezeigt?“."] =
            "Mandos originales no ocultados (pregunta cancelada). Para hacerlo luego: mando → Ajustes → Extras → «¿Se muestra dos veces?».",
        ["Xbox-360-Controller (empfohlen)"] = "Mando de Xbox 360 (recomendado)",
        ["Tastenanordnung A/B/X/Y"] = "Disposición de botones A/B/X/Y",
        ["Xbox: nach Position (untere Taste = A). Nintendo: nach Beschriftung (A bleibt A)."] = "Xbox: por posición (botón inferior = A). Nintendo: por etiqueta (A sigue siendo A).",
        ["Verbinden"] = "Conectando",
        ["Per Tastendruck verbinden"] = "Conectar con una pulsación",
        ["Gekoppelte Controller verbinden sich ohne SYNC-Taste."] = "Los mandos emparejados se conectan sin el botón SYNC.",
        ["Ohne Eingabe trennen nach"] = "Desconectar sin entrada tras",
        ["Spart Akku, wenn ein Controller liegen bleibt."] = "Ahorra batería cuando un mando queda sin usarse.",
        ["N-Connect startet unsichtbar im Infobereich."] = "N-Connect se inicia oculto en el área de notificación.",
        ["Darstellung und Sprache"] = "Apariencia e idioma",
        ["Farbmodus"] = "Modo de color",
        ["Mica-Effekt"] = "Efecto Mica",
        ["Durchscheinende Titelleiste (ab Windows 11)."] = "Barra de título translúcida (Windows 11 y posteriores).",
        ["Erweitert"] = "Avanzado",
        ["Gyro für Emulatoren (DSU)"] = "Giroscopio para emuladores (DSU)",
        ["Cemuhook-Server auf Port 26760 – wirkt nach einem Neustart von N-Connect."] = "Servidor Cemuhook en el puerto 26760: se aplica tras reiniciar N-Connect.",
        ["Nach Updates suchen"] = "Buscar actualizaciones",
        ["Beim Start auf GitHub nach einer neuen Version suchen."] = "Buscar una nueva versión en GitHub al iniciar.",
        ["Tastenbelegungen und Werte zurücksetzen. Gekoppelte Controller bleiben erhalten."] = "Restablecer asignaciones de botones y valores. Los mandos emparejados se conservan.",
        ["Zurücksetzen"] = "Restablecer",

        // ---------- Controller-Karte ----------
        ["Einstellungen"] = "Ajustes",
        ["Tastenbelegung und Einstellungen nur für diesen Controller"] = "Asignación de botones y ajustes solo para este mando",
        ["Feineinstellung"] = "Ajuste fino",
        ["Gyro"] = "Giroscopio",
        ["Extras"] = "Extras",
        ["Belegung für alle Spiele (Standard) oder ein eigenes Profil."] = "Asignación para todos los juegos (predeterminado) o un perfil propio.",
        ["Profile"] = "Perfiles",
        ["Profile anlegen, umbenennen, exportieren …"] = "Crear, renombrar, exportar perfiles …",
        ["Drück eine Taste am Controller – ihre Zeile leuchtet auf. ⌨ weist eine Tastaturtaste zu, ↺ setzt zurück."] =
            "Pulsa un botón en el mando: su fila se ilumina. ⌨ asigna una tecla del teclado, ↺ restablece.",
        ["Tastatur-Taste zuweisen: klicken und die gewünschte Taste oder Kombination drücken."] = "Asignar una tecla del teclado: haz clic y pulsa la tecla o combinación deseada.",
        ["Zurück auf die Standardbelegung"] = "Volver a la asignación predeterminada",
        ["Ohne eigenen Wert gilt der allgemeine Wert der Seite „Sticks & Vibration“."] = "Sin valor propio se aplica el valor general de la página «Sticks y vibración».",
        ["Stick-Totzone"] = "Zona muerta del stick",
        ["Stick-Kennlinie"] = "Curva del stick",
        ["Trigger-Totzone"] = "Zona muerta del gatillo",
        ["Trigger voll gedrückt ab"] = "Gatillo pulsado al máximo desde",
        ["Vibrationsstärke"] = "Intensidad de vibración",
        ["Gyro-Maus-Geschwindigkeit"] = "Velocidad del ratón giroscópico",
        ["Eigenen Wert entfernen – es gilt wieder der allgemeine Wert"] = "Quitar el valor propio: vuelve a aplicarse el general",
        ["Kalibrieren"] = "Calibrar",
        ["Controller ruhig auf den Tisch legen und klicken: misst den Nullpunkt neu (gegen Abdriften)."] =
            "Dejar el mando quieto sobre la mesa y hacer clic: mide de nuevo el punto cero (contra la deriva).",
        ["Gyro als rechter Stick und Mausrichtung"] = "Giroscopio como stick derecho y dirección del ratón",
        ["Gilt für alle Controller"] = "Se aplica a todos los mandos",
        ["Paar"] = "Par",
        ["Joy-Con quer halten und SL oder SR drücken löst das Paar, L + R gleichzeitig verbindet es."] =
            "Sostener un Joy-Con de lado y pulsar SL o SR separa el par; L + R a la vez lo une.",
        ["Haltung"] = "Orientación",
        ["Quer"] = "De lado",
        ["Hochkant"] = "Vertical",
        ["Quer wie an der Switch oder hochkant – hochkant gilt die Belegung von „Joy-Con-Paar“."] =
            "De lado como en Switch o vertical; en vertical se usa la asignación de «par de Joy-Con».",
        ["Mausmodus, Geschwindigkeit und Tasten"] = "Modo ratón, velocidad y botones",
        ["Lesen …"] = "Leer …",
        ["Einschalten"] = "Activar",
        ["Ausschalten"] = "Desactivar",
        ["Wird gesucht …"] = "Buscando …",
        ["Öffnen"] = "Abrir",
        ["Verstecken"] = "Ocultar",
        ["amiibo an den NFC-Leser halten und als Datei (.bin) speichern – z. B. für Emulatoren."] =
            "Acerca un amiibo al lector NFC y guárdalo como archivo (.bin), p. ej. para emuladores.",
        ["Zusammendrücken = rechter Trigger, auseinanderziehen = linker Trigger. Beim Einschalten nicht berühren."] =
            "Apretar = gatillo derecho, estirar = gatillo izquierdo. No tocarlo al activarlo.",
        ["Live-Bild der Infrarotkamera im rechten Joy-Con."] = "Imagen en vivo de la cámara infrarroja del Joy-Con derecho.",
        ["Doppelt angezeigt?"] = "¿Se muestra dos veces?",
        ["Versteckt den Original-Controller vor Steam und Spielen (HidHide) – sie sehen dann nur den virtuellen Controller."] =
            "Oculta el mando original a Steam y a los juegos (HidHide): entonces solo ven el mando virtual.",
        ["bereit (auf den Tisch legen)"] = "listo (colócalo sobre la mesa)",
        ["amiibo-Abbild (*.bin)|*.bin"] = "Imagen amiibo (*.bin)|*.bin",
        ["Controller-Profil (*.ncprofile.json)|*.ncprofile.json|JSON (*.json)|*.json"] = "Perfil de mando (*.ncprofile.json)|*.ncprofile.json|JSON (*.json)|*.json",
        ["Programme (*.exe)|*.exe"] = "Programas (*.exe)|*.exe",
        ["Kein Controller verbunden\n\n" +
         "Switch-2-Controller: kurz die SYNC-Taste drücken – danach reicht ein beliebiger Tastendruck.\n" +
         "Switch-1-, NSO- und Wii-Controller: SYNC-Taste drücken – N-Connect koppelt sie selbst.\n" +
         "Oder hier gezielt suchen und koppeln:"] =
            "Ningún mando conectado\n\n" +
            "Mandos de Switch 2: pulsa brevemente el botón SYNC; después basta cualquier pulsación.\n" +
            "Mandos de Switch 1, NSO y Wii: pulsa el botón SYNC; N-Connect los empareja por sí mismo.\n" +
            "O busca y empareja aquí directamente:",
        ["Controller suchen …"] = "Buscar mandos …",
        ["Kein Controller verbunden"] = "Ningún mando conectado",
        ["Switch-1-, NSO- und Wii-Controller suchen und koppeln (SYNC-Taste drücken)."] =
            "Buscar y emparejar mandos de Switch 1, NSO y Wii (pulsa el botón SYNC).",
        ["Neue Controller automatisch koppeln"] = "Emparejar nuevos mandos automáticamente",
        ["Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive, Wii und PlayStation: einfach SYNC " +
         "drücken – kein Umweg über die Windows-Bluetooth-Einstellungen. Gesucht wird nur, solange niemand spielt."] =
            "Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive, Wii y PlayStation: solo pulsa SYNC, sin pasar por los " +
            "ajustes de Bluetooth de Windows. Solo se busca mientras nadie juega.",
        ["Gezielt suchen"] = "Búsqueda dirigida",
        ["Sucht eine Minute lang nach Controllern im Kopplungsmodus."] = "Busca mandos en modo de emparejamiento durante un minuto.",
        ["Controller koppeln …"] = "Emparejar mando …",
        ["Controller koppeln"] = "Emparejar mando",
        ["Linken Joy-Con umbenennen …"] = "Renombrar Joy-Con izquierdo …",
        ["Rechten Joy-Con umbenennen …"] = "Renombrar Joy-Con derecho …",
        ["Controller umbenennen"] = "Renombrar mando",
        ["Spielerplatz"] = "Posición de jugador",
        ["N-Connect aktualisieren"] = "Actualizar N-Connect",
        ["HidHide aktualisieren"] = "Actualizar HidHide",
        ["HidHide-Update verfügbar"] = "Actualización de HidHide disponible",
        ["HidHide aktuell halten"] = "Mantener HidHide actualizado",
        ["Beim Start nach einer neuen HidHide-Version suchen. Installiert wird nur nach Rückfrage (geprüfter Download vom Hersteller, Neustart nötig)."] =
            "Buscar una nueva versión de HidHide al iniciar. Solo se instala tras confirmación (descarga verificada del fabricante, requiere reinicio).",
        ["Der Download hat nicht geklappt oder die Datei war fehlerhaft. Die Release-Seite im Browser öffnen?"] =
            "La descarga falló o el archivo estaba dañado. ¿Abrir la página de la versión en el navegador?",
        ["Alle Controller trennen"] = "Desconectar todos los mandos",
        ["Sticks kalibrieren"] = "Calibrar sticks",
        ["Kalibrieren …"] = "Calibrar …",
        ["Gegen Drift oder zu kleinen Ausschlag: Mitte und Rand neu messen. Wird nur in N-Connect gespeichert, der Controller bleibt unverändert."] =
            "Contra la deriva o un recorrido demasiado corto: medir de nuevo el centro y el borde. Solo se guarda en N-Connect, el mando no cambia.",
        ["Linker Stick"] = "Stick izquierdo",
        ["Rechter Stick"] = "Stick derecho",
        ["Stick"] = "Stick",
        ["Stick (linker Joy-Con)"] = "Stick (Joy-Con izquierdo)",
        ["Stick (rechter Joy-Con)"] = "Stick (Joy-Con derecho)",
        ["Neu messen"] = "Medir de nuevo",
        ["Werkswerte"] = "Valores de fábrica",
        ["Der Punkt zeigt, wo der Stick gerade steht. Steht er losgelassen nicht in der Mitte oder erreicht er den Kreis nicht, auf „Neu messen“ klicken."] =
            "El punto muestra dónde está el stick. Si al soltarlo no queda centrado o no alcanza el círculo, haz clic en «Medir de nuevo».",
        ["Gilt gerade: eigene Kalibrierung."] = "En uso: calibración propia.",
        ["Gilt gerade: Werkswerte des Controllers."] = "En uso: valores de fábrica del mando.",
        ["1/2 – Stick loslassen und den Controller ruhig halten …"] = "1/2: suelta el stick y mantén el mando quieto …",
        ["2/2 – Stick bis zum Anschlag drücken und langsam ein- bis zweimal im Kreis drehen."] =
            "2/2: empuja el stick hasta el tope y gíralo lentamente en círculo una o dos veces.",
        ["Fertig. „Übernehmen“ speichert die neue Kalibrierung für diesen Controller."] = "Listo. «Aplicar» guarda la nueva calibración para este mando.",
        ["Der Stick hat den Rand nicht erreicht. Bitte bis zum Anschlag drücken und erneut messen."] =
            "El stick no alcanzó el borde. Empújalo hasta el tope y mide de nuevo.",
        ["Übernommen ✓ – gilt ab sofort."] = "Aplicado ✓: en vigor desde ahora.",
        ["Werkswerte des Controllers gelten wieder."] = "Vuelven a aplicarse los valores de fábrica del mando.",
        ["Gyro einrichten"] = "Configurar giroscopio",
        ["Einrichten …"] = "Configurar …",
        ["Zielen per Bewegung einrichten"] = "Configurar el apuntado por movimiento",
        ["Schritt für Schritt: Nullpunkt, wann der Gyro zielt, Empfindlichkeit – mit Vorschau."] =
            "Paso a paso: punto cero, cuándo apunta el giroscopio, sensibilidad, con vista previa.",
        ["1  Nullpunkt"] = "1  Punto cero",
        ["Controller flach auf den Tisch legen, nicht berühren – verhindert, dass das Ziel von selbst wandert."] =
            "Coloca el mando plano sobre la mesa y no lo toques: evita que el objetivo se mueva solo.",
        ["Nullpunkt messen"] = "Medir punto cero",
        ["Der Controller hat sich bewegt – bitte flach hinlegen und erneut versuchen."] = "El mando se movió: déjalo plano e inténtalo de nuevo.",
        ["Nullpunkt gemessen ✓"] = "Punto cero medido ✓",
        ["2  Wann zielt der Gyro?"] = "2  ¿Cuándo apunta el giroscopio?",
        ["Nur per Taste"] = "Solo con botón",
        ["Beim Zielen (ZL/LT)"] = "Al apuntar (ZL/LT)",
        ["„Beim Zielen“: nur solange ZL (linker Trigger) gehalten wird – wie in vielen Shootern."] =
            "«Al apuntar»: solo mientras se mantiene ZL (gatillo izquierdo), como en muchos shooters.",
        ["3  Empfindlichkeit"] = "3  Sensibilidad",
        ["Voller Ausschlag ab"] = "Deflexión completa desde",
        ["Kleinerer Wert bei „Voller Ausschlag ab“ = empfindlicher. „Mindestausschlag“ überwindet die Totzone des Spiels."] =
            "Un valor menor en «Deflexión completa desde» = más sensible. «Deflexión mínima» supera la zona muerta del juego.",
        ["Mitte"] = "Centro",
        ["Vorschau: Fadenkreuz folgt dem Controller (unabhängig von Schritt 2)."] = "Vista previa: la retícula sigue al mando (independiente del paso 2).",
        ["Keine Bewegungsdaten"] = "Sin datos de movimiento",
        ["Controller gekoppelt"] = "Mando emparejado",
        ["Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive: SYNC-Taste drücken, bis die Lichter laufen.\n" +
         "Wii-Fernbedienung: Batteriefach öffnen und die rote SYNC-Taste drücken.\n" +
         "Wii U Pro Controller: die SYNC-Taste auf der Unterseite drücken.\n" +
         "Danach verbindet sich der Controller künftig per Tastendruck."] =
            "Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive: pulsa el botón SYNC hasta que las luces se muevan.\n" +
            "Mando de Wii: abre el compartimento de las pilas y pulsa el botón SYNC rojo.\n" +
            "Wii U Pro Controller: pulsa el botón SYNC de la parte inferior.\n" +
            "A partir de entonces el mando se conecta con una pulsación.",
        ["Suche … SYNC-Taste drücken (Xbox: Kopplungstaste oben halten, PlayStation: PS + Teilen/Create halten)."] =
            "Buscando … pulsa el botón SYNC (Xbox: mantén el botón de emparejamiento superior; PlayStation: mantén PS + Share/Create).",
        ["Kein Controller im Kopplungsmodus gefunden. SYNC-Taste drücken und erneut versuchen."] =
            "No se encontró ningún mando en modo de emparejamiento. Pulsa SYNC e inténtalo de nuevo.",
        ["Darstellung:"] = "Apariencia:",
        ["Dunkel"] = "Oscuro",
        ["Hell"] = "Claro",
        ["Wie Windows"] = "Como Windows",
        ["Mica-Effekt in der Titelleiste (ab Windows 11)"] = "Efecto Mica en la barra de título (Windows 11 y posteriores)",

        // ---------- Fehlerfälle und Hinweise ----------
        ["Bluetooth ist ausgeschaltet."] = "El Bluetooth está desactivado.",
        ["Dieser Bluetooth-Adapter unterstützt kein Bluetooth LE."] = "Este adaptador Bluetooth no admite Bluetooth LE.",
        ["Bluetooth-Suche konnte nicht starten."] = "No se pudo iniciar la búsqueda Bluetooth.",
        ["Bluetooth in den Windows-Einstellungen einschalten."] = "Activa el Bluetooth en la configuración de Windows.",
        ["Controller per USB funktionieren weiterhin."] = "Los mandos por USB siguen funcionando.",
        ["Für Switch-2-Controller wird ein Adapter mit Bluetooth 4.0 oder neuer gebraucht."] = "Los mandos de Switch 2 necesitan un adaptador con Bluetooth 4.0 o superior.",
        ["Andere Controller und USB funktionieren weiterhin."] = "Otros mandos y USB siguen funcionando.",
        ["Bluetooth-Adapter (z. B. USB-Stick) einstecken bzw. Bluetooth in Windows aktivieren."] =
            "Conecta un adaptador Bluetooth (p. ej. un dongle USB) o activa el Bluetooth en Windows.",
        ["Bluetooth ist bereit – Controller können verbunden werden."] = "El Bluetooth está listo: se pueden conectar mandos.",
        ["Bluetooth-Einstellungen öffnen"] = "Abrir ajustes de Bluetooth",
        ["ViGEmBus-Treiber fehlt – ohne ihn kann kein virtueller Controller erzeugt werden."] =
            "Falta el controlador ViGEmBus: sin él no se puede crear un mando virtual.",
        ["Bitte das Setup erneut ausführen."] = "Ejecuta de nuevo el instalador.",
        ["Das Programm schließen oder in Steam die Nintendo-Unterstützung abschalten."] =
            "Cierra ese programa o desactiva la compatibilidad con Nintendo en Steam.",
        ["Erst einen anderen trennen."] = "Desconecta primero otro.",
        ["Tipp: Bluetooth-Stick per Verlängerung näher an den Controller, weg von USB-3-Anschlüssen und Funkkopfhörern."] =
            "Consejo: acerca el dongle Bluetooth al mando con un cable alargador, lejos de puertos USB 3 y auriculares inalámbricos.",
        ["Controller mit dem PC gekoppelt – ab jetzt reicht ein Tastendruck."] = "Mando emparejado con el PC: a partir de ahora basta una pulsación.",
        ["Hinweis: Um ihn wieder an der Switch 2 zu nutzen, dort einmal kurz SYNC drücken."] =
            "Nota: para volver a usarlo en la Switch 2, pulsa SYNC una vez allí.",
        ["Dieser Bluetooth-Adapter unterstützt kein Bluetooth LE"] = "Este adaptador Bluetooth no admite Bluetooth LE",
        ["Erst IR-Kamera bzw. Ring-Con ausschalten (sie nutzen denselben Zusatzprozessor wie der NFC-Leser)."] =
            "Desactiva primero la cámara IR o el Ring-Con (usan el mismo coprocesador que el lector NFC).",
        ["Erst die IR-Kamera schließen (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "Cierra primero la cámara IR (Ring-Con y cámara IR usan el mismo coprocesador).",
        ["Erst den Ring-Con ausschalten (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "Desactiva primero el Ring-Con (Ring-Con y cámara IR usan el mismo coprocesador).",
        ["amiibo zu früh entfernt"] = "amiibo retirado demasiado pronto",
        ["MCU startet nicht"] = "el coprocesador no arranca",
        ["NFC-Modus nicht aktiv"] = "modo NFC no activo",
        ["Kopplung fehlgeschlagen – Details im Protokoll."] = "Emparejamiento fallido: detalles en el registro.",

        // ---------- Kopplungsdaten (Switch-SD-Karte, anderer PC) ----------
        ["Kopplungsdaten"] = "Datos de emparejamiento",
        ["Kopplungen übernehmen oder weitergeben"] = "Adoptar o compartir emparejamientos",
        ["Kopplungsdaten von der Switch übernehmen"] = "Adoptar datos de emparejamiento de la Switch",
        ["Von der Switch-SD-Karte (Bluepick_RCM/hekate) oder von einem anderen PC übernehmen, oder für einen anderen PC exportieren."] =
            "Adoptar desde la tarjeta SD de la Switch (Bluepick_RCM/hekate) o desde otro PC, o exportar para otro PC.",
        ["Bei Switch-SD-Karte nachfragen"] = "Preguntar al insertar una tarjeta SD de Switch",
        ["Steckt eine SD-Karte der Switch im PC (Kartenleser oder hekate „USB Tools“), bietet N-Connect die Übernahme an. Die Karte wird nur gelesen."] =
            "Cuando hay una tarjeta SD de la Switch en el PC (lector de tarjetas o hekate «USB Tools»), N-Connect ofrece adoptar los datos. La tarjeta solo se lee.",
        ["Switch-SD-Karte erkannt"] = "Tarjeta SD de Switch detectada",
        ["Kopplungsdaten der Controller gefunden – klicken, um sie anzusehen und zu übernehmen."] =
            "Datos de emparejamiento de mandos encontrados: haz clic para verlos y adoptarlos.",
        ["Klicken, um Kopplungsdaten der Controller zu übernehmen."] = "Haz clic para adoptar los datos de emparejamiento de los mandos.",
        ["Controller-Kopplungen von der Switch-SD-Karte oder von einem anderen PC übernehmen – oder für einen anderen PC exportieren. Es werden nur Einstellungen von N-Connect geändert; Windows und der Bluetooth-Adapter bleiben unverändert."] =
            "Adopta emparejamientos de mandos desde la tarjeta SD de la Switch o desde otro PC, o expórtalos para otro PC. Solo se modifican ajustes de N-Connect; Windows y el adaptador Bluetooth quedan intactos.",
        ["Spieler-Reihenfolge – Spieler 1 ist für Windows, Steam und Spiele der erste Controller. Mit ‹ › umsortieren."] =
            "Orden de jugadores: el jugador 1 es el primer mando para Windows, Steam y los juegos. Reordena con ‹ ›.",
        ["Von der Switch-SD-Karte"] = "Desde la tarjeta SD de la Switch",
        ["Mit Bluepick_RCM oder hekate erstellte Kopplungsdaten (switchroot/joycon_mac.ini)"] =
            "Datos de emparejamiento creados con Bluepick_RCM o hekate (switchroot/joycon_mac.ini)",
        ["Einlesen …"] = "Leer …",
        ["Von einem anderen PC"] = "Desde otro PC",
        ["Mit N-Connect exportierte Datei (*.ncpair)"] = "Archivo exportado por N-Connect (*.ncpair)",
        ["Datei öffnen …"] = "Abrir archivo …",
        ["Inhalt"] = "Contenido",
        ["Weitergeben und sichern"] = "Compartir y hacer copia",
        ["Für einen anderen PC exportieren"] = "Exportar para otro PC",
        ["Bekannte Controller und Einstellungen je Controller, optional mit Passwort"] =
            "Mandos conocidos y ajustes por mando, opcionalmente con contraseña",
        ["Sicherung wiederherstellen"] = "Restaurar copia de seguridad",
        ["Vor jedem „Übernehmen“ wird automatisch eine Sicherung angelegt"] = "Antes de cada «Aplicar» se crea automáticamente una copia de seguridad",
        ["Wiederherstellen …"] = "Restaurar …",
        ["Bluetooth-Adapter dieses PCs"] = "Adaptador Bluetooth de este PC",
        ["wird ermittelt …"] = "detectando …",
        ["nicht gefunden"] = "no encontrado",
        ["Quelle wählen: Switch-SD-Karte (mit Bluepick_RCM oder hekate erstellte Kopplungsdaten) oder eine Datei von einem anderen PC."] =
            "Elige una fuente: tarjeta SD de Switch (datos de emparejamiento creados con Bluepick_RCM o hekate) o un archivo de otro PC.",
        ["Keine Switch-SD-Karte gefunden. SD-Karte in den Kartenleser stecken oder die Switch per hekate („USB Tools“ → „SD Card“) als Laufwerk verbinden.\n\nOrdner selbst auswählen?"] =
            "No se encontró ninguna tarjeta SD de Switch. Inserta la tarjeta en un lector o conecta la Switch como unidad con hekate («USB Tools» → «SD Card»).\n\n¿Elegir la carpeta manualmente?",
        ["Stammordner der Switch-SD-Karte wählen"] = "Elegir la carpeta raíz de la tarjeta SD de Switch",
        ["Switch-SD-Karte:"] = "Tarjeta SD de Switch:",
        ["Auf der Karte liegen keine Kopplungsdaten (switchroot/joycon_mac.ini)."] = "La tarjeta no contiene datos de emparejamiento (switchroot/joycon_mac.ini).",
        ["So erstellst du sie: Joy-Con an die Switch stecken, Bluepick_RCM starten und „Dump Joy-Con BT pairing → SD“ (oder FULL AUTO) wählen. Alternativ in hekate: Nyx → Konsole → „Dump Joy-Con BT“."] =
            "Cómo crearlos: conecta los Joy-Con a la Switch, inicia Bluepick_RCM y elige «Dump Joy-Con BT pairing → SD» (o FULL AUTO). Alternativa en hekate: Nyx → Consola → «Dump Joy-Con BT».",
        ["Gefunden wurde eine Bluepick-Sicherung des Bluetooth-Speichers (8000000000000050.bin). Sie ist ein Switch-Speicherabbild und kann hier nicht ausgewertet werden."] =
            "Se encontró una copia Bluepick de la memoria Bluetooth (8000000000000050.bin). Es una imagen de memoria de la Switch y no se puede evaluar aquí.",
        ["Bluetooth-Adresse der Switch:"] = "Dirección Bluetooth de la Switch:",
        ["Gefundene Controller:"] = "Mandos encontrados:",
        ["mit der Switch gekoppelt"] = "emparejado con la Switch",
        ["zuletzt mit einem anderen Gerät gekoppelt (nicht der Switch)"] = "último emparejamiento con otro dispositivo (no la Switch)",
        ["Joy-Con (L)"] = "Joy-Con (I)",
        ["Joy-Con (R)"] = "Joy-Con (D)",
        ["HORI-Controller (links)"] = "Mando HORI (izquierdo)",
        ["HORI-Controller (rechts)"] = "Mando HORI (derecho)",
        ["Hinweis: Pro Controller stehen nur im Bluetooth-Speicher der Switch (8000000000000050.bin); dieses Speicherabbild kann N-Connect nicht auswerten."] =
            "Nota: los Pro Controller solo figuran en la memoria Bluetooth de la Switch (8000000000000050.bin); N-Connect no puede evaluar esa imagen de memoria.",
        ["Was diese Daten können – und was nicht:"] = "Qué pueden hacer estos datos, y qué no:",
        ["Die Daten zeigen, welche Controller mit deiner Switch gekoppelt sind und an welche Bluetooth-Adresse sie gebunden sind."] =
            "Los datos muestran qué mandos están emparejados con tu Switch y a qué dirección Bluetooth están vinculados.",
        ["Ein Switch-1-Controller verbindet sich auf Tastendruck nur mit dem Gerät, dessen Adresse er gespeichert hat – hier mit der Switch. Der Bluetooth-Adapter des PCs hat eine andere Adresse, deshalb kann Windows diese Kopplung nicht einfach weiterverwenden."] =
            "Un mando de Switch 1 se reconecta con una pulsación solo al dispositivo cuya dirección tiene guardada: aquí la Switch. El adaptador Bluetooth del PC tiene otra dirección, por lo que Windows no puede reutilizar este emparejamiento.",
        ["Die Adresse des PC-Adapters zu ändern, unterstützt N-Connect bewusst nicht (herstellerabhängig, riskant und nicht vorgesehen)."] =
            "N-Connect no permite cambiar la dirección del adaptador del PC a propósito (depende del fabricante, es arriesgado y no está previsto).",
        ["Windows bietet keinen offiziellen Weg, fremde Kopplungsschlüssel einzutragen: Sie liegen in einem Teil der Registrierung, auf den nur das System zugreifen darf. N-Connect ändert dort nichts."] =
            "Windows no ofrece una vía oficial para añadir claves de emparejamiento ajenas: se guardan en una parte del registro a la que solo puede acceder el sistema. N-Connect no cambia nada ahí.",
        ["So klappt der Wechsel am einfachsten: am PC den Controller einmal per SYNC-Taste in den Windows-Bluetooth-Einstellungen koppeln. Zurück an der Switch die Joy-Con an die Konsole stecken bzw. den Pro Controller per USB-Kabel anschließen – dann sind sie ohne Menü wieder mit der Switch gekoppelt."] =
            "La forma más fácil de cambiar: en el PC, empareja el mando una vez con el botón SYNC en los ajustes de Bluetooth de Windows. De vuelta en la Switch, acopla los Joy-Con a la consola o conecta el Pro Controller por USB: quedan emparejados de nuevo sin menú.",
        ["„Übernehmen“ merkt sich diese Controller in N-Connect (Liste bekannter Controller, Zuordnung zur Switch). Kopplungsschlüssel werden nicht gespeichert."] =
            "«Aplicar» recuerda estos mandos en N-Connect (lista de mandos conocidos, asignación a la Switch). Las claves de emparejamiento no se guardan.",
        ["N-Connect-Kopplungsdaten"] = "Datos de emparejamiento de N-Connect",
        ["Kopplungsdaten von einem anderen PC öffnen"] = "Abrir datos de emparejamiento de otro PC",
        ["Die Datei ist zu groß."] = "El archivo es demasiado grande.",
        ["Keine Kopplungsdaten-Datei."] = "No es un archivo de datos de emparejamiento.",
        ["Die Datei stammt von einer neueren N-Connect-Version."] = "El archivo proviene de una versión más reciente de N-Connect.",
        ["Die Datei ist mit einem Passwort geschützt."] = "El archivo está protegido con contraseña.",
        ["Falsches Passwort oder die Datei wurde verändert."] = "Contraseña incorrecta o el archivo fue modificado.",
        ["Die Datei ist beschädigt."] = "El archivo está dañado.",
        ["Datei von:"] = "Archivo de:",
        ["Bluetooth-Adapter dort:"] = "Adaptador Bluetooth allí:",
        ["Bluetooth-Adapter hier:"] = "Adaptador Bluetooth aquí:",
        ["gekoppelt mit der Switch"] = "emparejado con la Switch",
        ["gekoppelt mit dem anderen PC"] = "emparejado con el otro PC",
        ["Weitere Einstellungen je Controller:"] = "Otros ajustes por mando:",
        ["Was du erwarten kannst:"] = "Qué puedes esperar:",
        ["Gleiche Adapter-Adresse (z. B. derselbe USB-Bluetooth-Stick umgesteckt): Switch-2-Controller verbinden sich hier auf Tastendruck wie am anderen PC."] =
            "Misma dirección de adaptador (p. ej. el mismo dongle USB Bluetooth cambiado de PC): los mandos de Switch 2 se conectan aquí con una pulsación como en el otro PC.",
        ["Switch-1-Controller (Pro Controller, Joy-Con) brauchen zusätzlich die Kopplung in Windows. Die kann N-Connect nicht übertragen – einmal per SYNC-Taste koppeln."] =
            "Los mandos de Switch 1 (Pro Controller, Joy-Con) además necesitan el emparejamiento en Windows. N-Connect no puede transferirlo: empareja una vez con el botón SYNC.",
        ["Anderer Bluetooth-Adapter: Controller verbinden sich auf Tastendruck nur mit dem Gerät, mit dem sie zuletzt gekoppelt wurden. Hier einmal SYNC drücken – danach verbinden sie sich mit diesem PC (am anderen PC dann wieder per SYNC)."] =
            "Otro adaptador Bluetooth: los mandos se reconectan con una pulsación solo al dispositivo con el que se emparejaron por última vez. Pulsa SYNC aquí una vez; después se conectan a este PC (en el otro PC, usa SYNC de nuevo).",
        ["Tipp: Wer denselben USB-Bluetooth-Stick zwischen den PCs umsteckt, nimmt die Adresse mit – Switch-2-Controller verbinden sich dann an beiden PCs ohne SYNC."] =
            "Consejo: quien cambia el mismo dongle USB Bluetooth entre los PC se lleva la dirección consigo: los mandos de Switch 2 se conectan en ambos PC sin SYNC.",
        ["Übernommen werden die Einstellungen je Controller (Joy-Con einzeln/hochkant, Gyro-Kalibrierung) und die Liste bekannter Controller."] =
            "Se adoptan los ajustes por mando (Joy-Con suelto/vertical, calibración del giroscopio) y la lista de mandos conocidos.",
        ["Die Datei enthält Kopplungsschlüssel. Windows bietet keinen offiziellen Weg, sie einzutragen – N-Connect übernimmt sie deshalb nicht."] =
            "El archivo contiene claves de emparejamiento. Windows no ofrece una vía oficial para añadirlas, por eso N-Connect no las adopta.",
        ["„Übernehmen“ ergänzt die Controller-Listen und Einstellungen von N-Connect (nichts wird gelöscht). Vorher wird eine Sicherung angelegt."] =
            "«Aplicar» añade a las listas de mandos y ajustes de N-Connect (nada se borra). Antes se crea una copia de seguridad.",
        ["Kopplungsdaten in N-Connect übernehmen? Vorher wird eine Sicherung der Einstellungen angelegt."] =
            "¿Adoptar los datos de emparejamiento en N-Connect? Antes se crea una copia de seguridad de los ajustes.",
        ["Nichts zu ändern – diese Daten sind schon übernommen."] = "Nada que cambiar: estos datos ya están adoptados.",
        ["Übernommen. Die Sicherung lässt sich hier über „Sicherung wiederherstellen“ zurückholen."] =
            "Hecho. La copia de seguridad se puede restaurar aquí con «Restaurar copia de seguridad».",
        ["Sicherung der Einstellungen"] = "Copia de seguridad de los ajustes",
        ["Die Sicherung ist beschädigt und wurde nicht übernommen."] = "La copia de seguridad está dañada y no se aplicó.",
        ["Alle Einstellungen durch diese Sicherung ersetzen?"] = "¿Reemplazar todos los ajustes con esta copia de seguridad?",
        ["Sicherung wiederhergestellt."] = "Copia de seguridad restaurada.",
        ["Kopplungsdaten für einen anderen PC speichern"] = "Guardar datos de emparejamiento para otro PC",
        ["Gespeichert. Die Datei am anderen PC in N-Connect unter „Joy-Con & Wii“ → „Kopplungsdaten“ → „Von einem anderen PC“ öffnen."] =
            "Guardado. En el otro PC, abre el archivo en N-Connect en «Joy-Con y Wii» → «Datos de emparejamiento» → «Desde otro PC».",
        ["Kopplungsdaten exportieren"] = "Exportar datos de emparejamiento",
        ["Passwort eingeben"] = "Introducir contraseña",
        ["Passwort (optional). Ohne Passwort steht der Inhalt lesbar in der Datei. Mit Kopplungsschlüsseln ist ein Passwort Pflicht."] =
            "Contraseña (opcional). Sin contraseña el contenido queda legible en el archivo. Con claves de emparejamiento la contraseña es obligatoria.",
        ["Passwort"] = "Contraseña",
        ["Passwort wiederholen"] = "Repetir contraseña",
        ["Kopplungsschlüssel der Switch-Controller mitnehmen"] = "Incluir las claves de emparejamiento de los mandos de Switch",
        ["Kopplungsschlüssel mitnehmen (erst Switch-SD-Karte einlesen)"] = "Incluir claves de emparejamiento (lee primero una tarjeta SD de Switch)",
        ["Die Passwörter stimmen nicht überein."] = "Las contraseñas no coinciden.",
        ["Mit Schlüsseln: Passwort mit mindestens 8 Zeichen."] = "Con claves: contraseña de al menos 8 caracteres.",
        ["Mindestens 8 Zeichen."] = "Al menos 8 caracteres.",
        ["Ohne Passwort."] = "Sin contraseña.",
    };

    /// <summary>Meldungen mit Platzhaltern (Spanisch).</summary>
    private static readonly (Regex Pattern, Func<Match, string> Replace)[] PatternsEs =
    [
        (Re(@"^Allgemeiner Wert \((?<v>.+)\) – Regler verschieben für einen eigenen$"), m => $"Valor general ({m.Groups["v"]}): mueve el control para definir uno propio"),
        (Re(@"^Eigener Wert · allgemein: (?<v>.+)$"), m => $"Valor propio · general: {m.Groups["v"]}"),
        (Re(@"^Spieler (?<n>\d+)  ·  (?<k>.+?)(?<rest>(  ·  .*)?)$"), m => $"Jugador {m.Groups["n"]}  ·  {N(m, "k")}{T(m.Groups["rest"].Value)}"),
        (Re(@"^  ·  Gyro-Maus(?<r>.*)$"), m => "  ·  Ratón giroscópico" + T(m.Groups["r"].Value)),
        (Re(@"^  ·  Gyro-Stick$"), _ => "  ·  Stick giroscópico"),
        (Re(@"^Spieler (?<n>\d+) · (?<k>.+?) (?<b>\d+ %.*)?$"), m => $"Jugador {m.Groups["n"]} · {N(m, "k")} {m.Groups["b"]}"),
        (Re(@"^(?<k>.+) verbunden \(Spieler (?<n>\d+)\)$"), m => $"{N(m, "k")} conectado (jugador {m.Groups["n"]})"),
        (Re(@"^Spieler (?<n>\d+) – tauschen mit (?<k>.+)$"), m => $"Jugador {m.Groups["n"]}: cambiar con {N(m, "k")}"),
        (Re(@"^Spieler (?<n>\d+) – frei$"), m => $"Jugador {m.Groups["n"]}: libre"),
        (Re(@"^Spieler (?<n>\d+)$"), m => $"Jugador {m.Groups["n"]}"),
        (Re(@"^Xbox 360 · Platz (?<n>\d+)$"), m => $"Xbox 360 · posición {m.Groups["n"]}"),
        (Re(@"^noch (?<n>\d+) s$"), m => $"quedan {m.Groups["n"]} s"),
        (Re(@"^Fertig – (?<n>\d+) Controller verbunden$"), m => $"Hecho: {m.Groups["n"]} mando(s) conectado(s)"),
        (Re(@"^✓ (?<k>.+) verbunden – Spieler (?<n>\d+)$"), m => $"✓ {N(m, "k")} conectado: jugador {m.Groups["n"]}"),
        (Re(@"^Spieler (?<n>\d+)  ·  (?<v>.+)$"), m => $"Jugador {m.Groups["n"]}  ·  {m.Groups["v"]}"),
        (Re(@"^Gekoppelt: (?<k>.+) – verbindet gleich …$"), m => $"Emparejado: {m.Groups["k"]}: conectando …"),
        (Re(@"^Ins Spiel wechseln … (?<n>\d+)$"), m => $"Cambia al juego … {m.Groups["n"]}"),
        (Re(@"^(?<k>.+) ist jetzt Spieler (?<n>\d+)$"), m => $"{N(m, "k")} ahora es el jugador {m.Groups["n"]}"),
        (Re(@"^Spieler (?<a>\d+) und (?<b>\d+) getauscht$"), m => $"Jugadores {m.Groups["a"]} y {m.Groups["b"]} intercambiados"),
        (Re(@"^Name für (?<k>.+) \(leer = Standardname\):$"), m => $"Nombre para {N(m, "k")} (vacío = nombre predeterminado):"),
        (Re(@"^(?<k>.+) \(Joy-Con-Paar\)$"), m => $"{m.Groups["k"]} (par de Joy-Con)"),
        (Re(@"^Joy-Con zusammengefasst \(Spieler (?<n>\d+)\)$"), m => $"Joy-Con combinados (jugador {m.Groups["n"]})"),
        (Re(@"^Joy-Con getrennt – (?<k>.+) ist jetzt Spieler (?<n>\d+)$"), m => $"Joy-Con separado: {N(m, "k")} ahora es el jugador {m.Groups["n"]}"),
        (Re(@"^Spieler (?<n>\d+): Akku (?<k>.+) fast leer \((?<p>\d+) %\) – bitte aufladen$"),
            m => $"Jugador {m.Groups["n"]}: batería de {N(m, "k")} casi agotada ({m.Groups["p"]} %): cárgala"),
        (Re(@"^Spieler (?<n>\d+): nach (?<m>\d+) min ohne Eingabe getrennt$"),
            m => $"Jugador {m.Groups["n"]}: desconectado tras {m.Groups["m"]} min sin entrada"),
        (Re(@"^Profil „(?<p>.+)“ aktiv$"), m => $"Perfil «{ProfileName(m.Groups["p"].Value)}» activo"),
        (Re(@"^Profil: (?<p>.+)$"), m => $"Perfil: {ProfileName(m.Groups["p"].Value)}"),
        (Re(@"^Profil „(?<p>.+)“ löschen\?$"), m => $"¿Eliminar el perfil «{m.Groups["p"]}»?"),
        (Re(@"^Profil „(?<p>.+)“ importiert(?<r>.*)$"), m => $"Perfil «{m.Groups["p"]}» importado" + m.Groups["r"].Value.Replace("aktiv bei:", "activo con:")),
        (Re(@"^⬇ Neue Version (?<v>.+) herunterladen …$"), m => $"⬇ Descargar nueva versión {m.Groups["v"]} …"),
        (Re(@"^Version (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Herunterladen\.$"),
            m => $"La versión {m.Groups["v"]} está disponible (instalada: {m.Groups["i"]}). Haz clic para descargar."),
        (Re(@"^Version (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Installieren\.$"),
            m => $"La versión {m.Groups["v"]} está disponible (instalada: {m.Groups["i"]}). Haz clic para instalar."),
        (Re(@"^⬇ Auf Version (?<v>.+) aktualisieren …$"), m => $"⬇ Actualizar a la versión {m.Groups["v"]} …"),
        (Re(@"^Lade Version (?<v>.+) herunter …$"), m => $"Descargando versión {m.Groups["v"]} …"),
        (Re(@"^HidHide (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Installieren\.$"),
            m => $"HidHide {m.Groups["v"]} está disponible (instalado: {m.Groups["i"]}). Haz clic para instalar."),
        (Re(@"^Lade HidHide (?<v>.+) herunter …$"), m => $"Descargando HidHide {m.Groups["v"]} …"),
        (Re(@"^(?<t>.+) · (?<r>\d+) Berichte/s$"), m => $"{T(m.Groups["t"].Value)} · {m.Groups["r"]} informes/s"),
        (Re(@"^(?<p>\d+ %)(?<v>  \(.*\))?  ⚡ lädt$"), m => $"{m.Groups["p"]}{m.Groups["v"]}  ⚡ cargando"),
        (Re(@"^Speichern fehlgeschlagen: (?<e>.*)$"), m => $"Error al guardar: {m.Groups["e"]}"),
        (Re(@"^Lesen fehlgeschlagen: (?<e>.*)$"), m => $"Error al leer: {m.Groups["e"]}"),
        (Re(@"^amiibo konnte nicht gelesen werden: (?<e>.*)$"), m => $"No se pudo leer el amiibo: {T(m.Groups["e"].Value)}"),
        (Re(@"^Gekoppelt: (?<k>.+)$"), m => $"Emparejado: {m.Groups["k"]}"),
        (Re(@"^Gefunden: (?<k>.+) – kopple …$"), m => $"Encontrado: {m.Groups["k"]}: emparejando …"),
        (Re(@"^amiibo erkannt \((?<u>.+)\) – lese …$"), m => $"amiibo detectado ({m.Groups["u"]}): leyendo …"),
        (Re(@"^(?<n>\d+) Minuten$"), m => $"{m.Groups["n"]} minutos"),
        (Re(@"^✓ (?<n>\d+) Schritte, Dauer (?<ms>\d+) ms$"), m => $"✓ {m.Groups["n"]} pasos, {m.Groups["ms"]} ms en total"),
        (Re(@"^Controller-Taste „(?<b>.+)“:\nJetzt die gewünschte Taste oder Tastenkombination drücken\.$"),
            m => $"Botón del mando «{T(m.Groups["b"].Value)}»:\nAhora pulsa la tecla o combinación deseada."),
        (Re(@"^Solange „(?<b>.+)“ gehalten wird, wird diese Taste schnell wiederholt gedrückt\n\(Geschwindigkeit unter 5\. „Turbo“\):$"),
            m => $"Mientras se mantiene «{T(m.Groups["b"].Value)}», este botón se pulsa rápidamente\n(velocidad en 5. «Turbo»):"),
        (Re(@"^Ring-Con: (?<e>.*)$"), m => $"Ring-Con: {T(m.Groups["e"].Value)}"),
        (Re(@"^⌨  Taste: (?<k>.+)$"), m => $"⌨  Tecla: {m.Groups["k"]}"),
        (Re(@"^🔁  Turbo: Taste (?<k>.+)$"), m => $"🔁  Turbo: tecla {m.Groups["k"]}"),
        (Re(@"^🔁  Turbo: (?<k>.+)$"), m => $"🔁  Turbo: {T(m.Groups["k"].Value)}"),
        (Re(@"^⏯  Makro: (?<k>.+)$"), m => $"⏯  Macro: {m.Groups["k"]}"),
        (Re(@"^Tastatur: (?<k>.+)$"), m => $"Teclado: {m.Groups["k"]}"),
        (Re(@"^Gamepad: (?<k>.+)$"), m => $"Mando: {m.Groups["k"]}"),
        (Re(@"^(?<k>.+)  \(verbunden\)$"), m => $"{N(m, "k")}  (conectado)"),
        (Re(@"^Bluetooth nicht verfügbar: (?<e>.*)$"), m => $"Bluetooth no disponible: {m.Groups["e"]}"),
        (Re(@"^(?<k>.+) per USB ist von einem anderen Programm belegt \(z\. B\. Steam\)\.$"),
            m => $"{N(m, "k")} por USB está en uso por otro programa (p. ej. Steam)."),
        (Re(@"^Schon (?<n>\d+) Controller verbunden – (?<k>.+) wird nicht verwendet\.$"),
            m => $"Ya hay {m.Groups["n"]} mandos conectados: {N(m, "k")} no se usa."),
        (Re(@"^(?<k>.+): schwache Bluetooth-Verbindung \((?<r>\d+) statt 33–60 Berichte/s\)\.$"),
            m => $"{N(m, "k")}: conexión Bluetooth débil ({m.Groups["r"]} en lugar de 33–60 informes/s)."),
        (Re(@"^(?<k>.+) getrennt$"), m => $"{N(m, "k")} desconectado"),
    ];
}
