using System.Text.RegularExpressions;

namespace Switch2Pro.Bridge;

/// <summary>Feste Texte Deutsch → Niederländisch. Schlüssel bleiben die deutschen Originaltexte.</summary>
internal static partial class Tr
{
    private static readonly Dictionary<string, string> TextsNl = new(StringComparer.Ordinal)
    {
        // ---------- Fenster, Reiter, Abschnitte ----------
        ["Controller"] = "Controllers",
        // ---------- Desktop-Modus, Testseite, Vorlagen, Diagnose ----------
        ["Einblendung beim Verbinden"] = "Melding bij verbinden",
        ["Kurze Anzeige am Bildschirmrand mit Spieler, Controller und Akkustand."] = "Korte weergave aan de schermrand met speler, controller en batterij.",
        ["Desktop-Modus"] = "Bureaubladmodus",
        ["Läuft kein Spiel, steuert der Controller Windows: linker Stick = Maus, rechter Stick = Scrollen, A = Klick, B = Rechtsklick, X = Taskansicht, Y = Bildschirmtastatur, Steuerkreuz = Pfeiltasten, LB/RB = zurück/vor, Start = Enter, Back = Esc, HOME = Startmenü. Back + Start 1 Sekunde halten pausiert ihn. In Vollbildspielen und Programmen mit eigenem Profil ist er automatisch aus."] = "Zonder spel bestuurt de controller Windows: linkerstick = muis, rechterstick = scrollen, A = klik, B = rechtsklik, X = taakweergave, Y = schermtoetsenbord, D-pad = pijltjestoetsen, LB/RB = terug/vooruit, Start = Enter, Back = Esc, HOME = Startmenu. Houd Back + Start 1 seconde vast om te pauzeren. In schermvullende spellen en programma's met een eigen profiel staat hij automatisch uit.",
        ["Zeigergeschwindigkeit"] = "Aanwijzersnelheid",
        ["RT gedrückt halten macht den Zeiger langsam und genau."] = "Houd RT ingedrukt voor een langzame, precieze aanwijzer.",
        ["Desktop-Steuerung pausiert – Back + Start halten zum Fortsetzen."] = "Bureaubladbesturing gepauzeerd – houd Back + Start vast om verder te gaan.",
        ["Desktop-Steuerung aktiv – der Controller steuert Maus und Tastatur."] = "Bureaubladbesturing actief – de controller bestuurt muis en toetsenbord.",
        ["Test"] = "Test",
        ["Trigger"] = "Triggers",
        ["Bewegung"] = "Beweging",
        ["Rundheit"] = "Rondheid",
        ["Berichte/s"] = "rapporten/s",
        ["Vibration testen"] = "Trillen testen",
        ["Kreis zurücksetzen"] = "Cirkel resetten",
        ["Controller testen"] = "Controller testen",
        ["Sticks einmal langsam ganz im Kreis drehen – die Linie zeigt, wie rund sie laufen. Gedrückte Tasten erscheinen unten in der Anzeige."] = "Draai elke stick één keer langzaam helemaal rond – de lijn laat zien hoe rond hij beweegt. Ingedrukte knoppen verschijnen onderaan.",
        ["🔇  Ton aus/an"] = "🔇  Geluid uit/aan",
        ["⏭  Nächster Titel"] = "⏭  Volgend nummer",
        ["⏮  Vorheriger Titel"] = "⏮  Vorig nummer",
        ["🎙  Mikrofon stumm (Win+Alt+K)"] = "🎙  Microfoon dempen (Win+Alt+K)",
        ["🎙  Discord: Mikrofon stumm (Strg+Umschalt+M)"] = "🎙  Discord: microfoon dempen (Ctrl+Shift+M)",
        ["🎧  Discord: Ton aus (Strg+Umschalt+D)"] = "🎧  Discord: doof (Ctrl+Shift+D)",
        ["🖥  Desktop anzeigen (Win+D)"] = "🖥  Bureaublad tonen (Win+D)",
        ["🗂  Taskansicht (Win+Tab)"] = "🗂  Taakweergave (Win+Tab)",
        ["↔  Zum letzten Fenster (Alt+Tab)"] = "↔  Laatste venster (Alt+Tab)",
        ["Diagnose exportieren"] = "Diagnose exporteren",
        ["Protokoll, Einstellungen und Systeminfos als ZIP-Datei – zum Anhängen an eine Fehlermeldung. Enthält keine Kopplungsschlüssel."] = "Logboek, instellingen en systeeminfo als ZIP-bestand – om bij een probleemmelding te voegen. Bevat geen koppelsleutels.",
        // ---------- Desktop-Widget ----------
        ["Desktop-Widget"] = "Bureaubladwidget",
        ["Kleines Kärtchen auf dem Desktop: verbundene Controller, Akku, Verbindung und Ausgabe auf einen Blick. Mit der Maus verschieben, Rechtsklick für Optionen, Doppelklick öffnet N-Connect."] = "Klein kaartje op het bureaublad: verbonden controllers, accu, verbinding en uitvoer in één oogopslag. Versleep het met de muis, rechtsklik voor opties, dubbelklik opent N-Connect.",
        ["Immer im Vordergrund"] = "Altijd op voorgrond",
        ["Widget bleibt über allen Fenstern sichtbar (sonst nur auf dem Desktop)."] = "De widget blijft boven alle vensters zichtbaar (anders alleen op het bureaublad).",
        ["Kompakte Ansicht"] = "Compacte weergave",
        ["Eine Zeile je Controller: Spieler, Name und Akku."] = "Eén regel per controller: speler, naam en accu.",
        ["Deckkraft"] = "Dekking",
        ["nativ"] = "native",
        ["Controller einschalten oder SYNC drücken"] = "Zet een controller aan of druk op SYNC",
        ["N-Connect öffnen"] = "N-Connect openen",
        ["Position zurücksetzen"] = "Positie herstellen",
        ["Widget ausblenden"] = "Widget verbergen",
        // ---------- ESP32-Export ----------
        ["Für ESP32 exportieren"] = "Exporteren voor ESP32",
        ["Adresse dieses Bluetooth-Adapters und die Switch-2-Controller für einen ESP32-S3, der sich als dieser PC ausgibt – Controller verbinden sich dann ohne neues SYNC (Anleitung im ZIP)"] = "Adres van deze Bluetooth-adapter en de Switch 2-controllers voor een ESP32-S3 die zich voordoet als deze pc – controllers verbinden dan zonder nieuwe SYNC (uitleg in de ZIP)",
        ["ESP32-Export …"] = "ESP32-export …",
        ["Die Adresse des Bluetooth-Adapters ist nicht bekannt. Bluetooth einschalten und das Fenster neu öffnen."] = "Het adres van de Bluetooth-adapter is onbekend. Zet Bluetooth aan en open dit venster opnieuw.",
        ["ZIP-Datei"] = "ZIP-bestand",
        ["ESP32-Export speichern"] = "ESP32-export opslaan",
        ["ESP32-Export gespeichert:"] = "ESP32-export opgeslagen:",
        ["Adresse für den ESP32"] = "Adres voor de ESP32",
        ["übernehmbar"] = "overdraagbaar",
        ["nicht übernehmbar"] = "niet overdraagbaar",
        ["Noch kein Switch-2-Controller bekannt: einmal per SYNC mit N-Connect koppeln und neu exportieren."] = "Nog geen Switch 2-controller bekend: koppel er één keer een met N-Connect via SYNC en exporteer opnieuw.",
        ["Für nRF52840 exportieren"] = "Exporteren voor nRF52840",
        ["Dieselben Daten für einen Nordic-nRF52840-Dongle (nRF Connect SDK/Zephyr oder Adafruit Bluefruit) – auch er gibt sich als dieser PC aus (Anleitung im ZIP)"] = "Dezelfde gegevens voor een Nordic nRF52840-dongle (nRF Connect SDK/Zephyr of Adafruit Bluefruit) – ook die doet zich voor als deze pc (uitleg in de ZIP)",
        ["nRF52840-Export …"] = "nRF52840-export …",
        ["nRF52840-Export speichern"] = "nRF52840-export opslaan",
        ["nRF52840-Export gespeichert:"] = "nRF52840-export opgeslagen:",
        ["Adresse für den nRF52840"] = "Adres voor de nRF52840",
        // ---------- Status-Kopfzeile, Ansicht ----------
        ["Farbschema"] = "Kleurenschema",
        ["Farben für Akzente, Knöpfe, Flächen und Ränder."] = "Kleuren voor accenten, knoppen, vlakken en randen.",
        ["bereit"] = "gereed",
        ["nicht verfügbar"] = "niet beschikbaar",
        ["Niedrigster Akku"] = "Laagste accu",
        ["lädt"] = "laadt op",
        ["gemischt"] = "gemengd",
        ["Original-Controller"] = "Originele controllers",
        ["versteckt"] = "verborgen",
        ["sichtbar"] = "zichtbaar",
        ["HidHide fehlt"] = "HidHide ontbreekt",
        ["Groß"] = "Groot",
        ["Kompakt"] = "Compact",
        ["Einstellungen (optional)"] = "Instellingen (optioneel)",
        ["1. Windows und Spiele sehen den Controller als …"] = "1. Windows en games zien de controller als …",
        ["2. Tasten A/B/X/Y"] = "2. Knoppen A/B/X/Y",
        ["3. Vibration, Sticks, Verbinden, Gyro-Maus"] = "3. Trilling, sticks, verbinden, gyro-muis",
        ["4. Joy-Con"] = "4. Joy-Con",
        ["4. Joy-Con und Wii"] = "4. Joy-Con en Wii",
        ["Wii-Fernbedienung: Zeiger (Sensorleiste) steuert die Maus"] = "Wii-afstandsbediening: de pointer (sensorbalk) beweegt de muis",
        ["Zeiger"] = "Pointer",
        ["kein Zeiger – Sensorleiste nicht im Blick"] = "geen pointer – sensorbalk niet in beeld",
        ["5. Zielen, Sticks, Trigger, Turbo"] = "5. Richten, sticks, triggers, turbo",
        ["6. Tastenbelegung und Profile  (Taste → Gamepad, Tastatur, Maus, Gyro-Maus, Shift-Ebene)"] =
            "6. Knoptoewijzing en profielen  (knop → gamepad, toetsenbord, muis, gyro-muis, Shift-laag)",
        ["Xbox-360-Controller  (empfohlen – läuft mit fast allen Spielen)"] = "Xbox 360-controller  (aanbevolen – werkt met bijna alle games)",
        ["PlayStation DualShock 4  (mit Bewegungssteuerung/Gyro – für Steam && Emulatoren)"] =
            "PlayStation DualShock 4  (met bewegingsbesturing/gyro – voor Steam en emulators)",
        ["Xbox-Belegung  (nach Position: untere Taste = A)"] = "Xbox-indeling  (op positie: onderste knop = A)",
        ["Nintendo-Belegung  (nach Beschriftung: A bleibt A)"] = "Nintendo-indeling  (op opschrift: A blijft A)",
        ["Vibration"] = "Trilling",
        ["Stärke:"] = "Sterkte:",
        ["Stick-Totzone (alle Controller):"] = "Stick-dode zone (alle controllers):",
        ["Beim Verbinden kurz vibrieren"] = "Kort trillen bij verbinden",
        ["Meldung bei Verbinden"] = "Melding bij verbinden",
        ["Wer meldet, wenn ein Controller verbunden oder getrennt wird."] = "Kies wie meldt wanneer een controller verbinding maakt of verbreekt.",
        ["„N-Connect“ zeigt den echten Controller-Namen und schaltet die Gerätemeldungen von Windows ab."] = "\"N-Connect\" toont de echte naam van de controller en schakelt de apparaatmeldings van Windows uit.",
        ["N-Connect (empfohlen)"] = "N-Connect (aanbevolen)",
        ["N-Connect und Windows"] = "N-Connect en Windows",
        ["Keine"] = "Geen",
        ["Gekoppelte Controller per Tastendruck verbinden (ohne SYNC)"] = "Gekoppelde controllers verbinden met een knopdruk (zonder SYNC)",
        ["Automatisch mit Windows starten"] = "Automatisch starten met Windows",
        ["Gyro für Emulatoren bereitstellen (Cemuhook/DSU, Port 26760 – wirkt nach Neustart)"] =
            "Gyroscoop beschikbaar stellen voor emulators (Cemuhook/DSU, poort 26760 – actief na herstart)",
        ["Beim Start nach neuer Version suchen (GitHub)"] = "Bij het starten naar een nieuwe versie zoeken (GitHub)",
        ["Ohne Eingabe automatisch trennen nach:"] = "Automatisch verbreken zonder invoer na:",
        ["Gyro-Maus-Geschwindigkeit:"] = "Snelheid gyro-muis:",
        ["Sprache / Language:"] = "Taal / Language:",
        ["Automatisch (wie Windows)"] = "Automatisch (zoals Windows)",
        ["nie"] = "nooit",
        ["Zwei Joy-Con automatisch zu einem Controller zusammenfassen"] = "Twee Joy-Con automatisch combineren tot één controller",
        ["Gyro beim Paar vom:"] = "Gyroscoop van het paar van:",
        ["rechter Joy-Con (wie Switch)"] = "rechter Joy-Con (zoals op de Switch)",
        ["linker Joy-Con"] = "linker Joy-Con",
        ["Joy-Con 2 als Maus, wenn er auf dem Tisch liegt"] = "Joy-Con 2 als muis wanneer hij op tafel ligt",
        ["Mausgeschwindigkeit:"] = "Muissnelheid:",
        ["Maus: links/rechts umkehren"] = "Muis: links/rechts omkeren",
        ["Maus: hoch/runter umkehren"] = "Muis: omhoog/omlaag omkeren",
        ["Wie an der Switch: SL + SR eine Sekunde halten löst einen Joy-Con aus dem Paar. L am linken und R am rechten einzelnen Joy-Con gleichzeitig drücken verbindet sie wieder zum Paar. Die Wahl wird je Joy-Con gemerkt (auch nach dem nächsten Verbinden). Im Mausmodus: R/L = Linksklick, ZR/ZL = Rechtsklick, Stick drücken = Mittelklick, Stick hoch/runter = Scrollen."] =
            "Zoals op de Switch: SL + SR een seconde vasthouden haalt een Joy-Con uit het paar. L op de linker en R op de rechter losse Joy-Con tegelijk indrukken voegt ze weer samen. De keuze wordt per Joy-Con onthouden (ook bij de volgende verbinding). In muisstand: R/L = linkermuisklik, ZR/ZL = rechtermuisklik, stick indrukken = middelklik, stick omhoog/omlaag = scrollen.",
        ["Gyro als rechter Stick:"] = "Gyroscoop als rechter stick:",
        ["aus (nur per Taste „Gyro-Stick“)"] = "uit (alleen via knop „gyro-stick“)",
        ["immer"] = "altijd",
        ["beim Zielen (solange ZL / linker Trigger gedrückt)"] = "bij richten (zolang ZL / linker trigger is ingedrukt)",
        ["hoch/runter umkehren"] = "omhoog/omlaag omkeren",
        ["Empfindlichkeit:"] = "Gevoeligheid:",
        ["Mindestausschlag:"] = "Minimale uitslag:",
        ["Stick-Kennlinie:"] = "Stick-karakteristiek:",
        ["Turbo (pro Sekunde):"] = "Turbo (per seconde):",
        ["Analoge Trigger (GameCube) – Totzone:"] = "Analoge triggers (GameCube) – dode zone:",
        ["voll gedrückt ab:"] = "volledig ingedrukt vanaf:",
        ["Profil:"] = "Profiel:",
        ["Neu …"] = "Nieuw …",
        ["Umbenennen …"] = "Hernoemen …",
        ["Löschen"] = "Verwijderen",
        ["Exportieren …"] = "Exporteren …",
        ["Importieren …"] = "Importeren …",
        ["Aktiv bei Programm:"] = "Actief bij programma:",
        ["Programm wählen …"] = "Programma kiezen …",
        ["Standard"] = "Standaard",
        ["Standard gilt immer, wenn kein anderes Profil passt"] = "Standaard geldt als geen ander profiel past",
        ["z. B. Cemu.exe, Ryujinx.exe"] = "bijv. Cemu.exe, Ryujinx.exe",
        ["Ein eigenes Profil wird automatisch aktiv, solange eines seiner Programme im Vordergrund ist (sonst gilt „Standard“). Im Infobereich-Menü lässt sich ein Profil auch fest wählen."] =
            "Een eigen profiel wordt automatisch actief zolang een van zijn programma's op de voorgrond staat (anders geldt „Standaard“). Een profiel kan ook vast worden gekozen in het systeemvakmenu.",
        ["Controller:"] = "Controller:",
        ["Eigene Stick-Totzone für diesen Controller:"] = "Eigen stick-dode zone voor deze controller:",
        ["Normale Belegung"] = "Normale toewijzing",
        ["Shift-Ebene (gilt, solange eine Taste mit „Shift-Ebene“ gehalten wird)"] = "Shift-laag (geldt zolang een knop met „Shift-laag“ is ingedrukt)",
        ["Alles auf Standard"] = "Alles resetten",
        ["Schließen"] = "Sluiten",
        ["wie normale Belegung"] = "zoals normale toewijzing",

        // ---------- Belegungsziele und Vorlagen ----------
        ["— keine Funktion —"] = "— geen functie —",
        ["A (Xbox) / Kreuz (PS)"] = "A (Xbox) / Kruis (PS)",
        ["B (Xbox) / Kreis (PS)"] = "B (Xbox) / Cirkel (PS)",
        ["X (Xbox) / Viereck (PS)"] = "X (Xbox) / Vierkant (PS)",
        ["Y (Xbox) / Dreieck (PS)"] = "Y (Xbox) / Driehoek (PS)",
        ["Ansicht (Back) / Share"] = "Weergave (Back) / Share",
        ["Menü (Start) / Options"] = "Menu (Start) / Options",
        ["Xbox-Taste / PS-Taste"] = "Xbox-knop / PS-knop",
        ["Linker Stick-Klick"] = "Klik linker stick",
        ["Rechter Stick-Klick"] = "Klik rechter stick",
        ["Steuerkreuz hoch"] = "D-pad omhoog",
        ["Steuerkreuz runter"] = "D-pad omlaag",
        ["Steuerkreuz links"] = "D-pad links",
        ["Steuerkreuz rechts"] = "D-pad rechts",
        ["Touchpad-Klick (nur DualShock 4)"] = "Touchpad-klik (alleen DualShock 4)",
        ["🖱  Maus: Linksklick"] = "🖱  Muis: linkermuisklik",
        ["🖱  Maus: Rechtsklick"] = "🖱  Muis: rechtermuisklik",
        ["🖱  Maus: Mittelklick"] = "🖱  Muis: middelklik",
        ["🎯  Gyro-Maus (solange gehalten)"] = "🎯  Gyro-muis (zolang ingedrukt)",
        ["🎯  Gyro-Maus ein/aus"] = "🎯  Gyro-muis aan/uit",
        ["🎯  Gyro als rechter Stick (solange gehalten)"] = "🎯  Gyroscoop als rechter stick (zolang ingedrukt)",
        ["🎯  Gyro als rechter Stick ein/aus"] = "🎯  Gyroscoop als rechter stick aan/uit",
        ["⇧  Shift-Ebene (solange gehalten)"] = "⇧  Shift-laag (zolang ingedrukt)",
        ["🔁  Turbo / Dauerfeuer …"] = "🔁  Turbo / snelvuur …",
        ["⏯  Makro (Tastenfolge) …"] = "⏯  Macro (knopvolgorde) …",
        ["📷  Bildschirmfoto speichern (Win+Druck)"] = "📷  Schermafbeelding opslaan (Win+Print)",
        ["📷  Bildschirmausschnitt (Win+Umschalt+S)"] = "📷  Schermfragment (Win+Shift+S)",
        ["⏺  Letzte 30 Sekunden aufnehmen (Win+Alt+G)"] = "⏺  Laatste 30 seconden opnemen (Win+Alt+G)",
        ["⏺  Aufnahme starten/stoppen (Win+Alt+R)"] = "⏺  Opname starten/stoppen (Win+Alt+R)",
        ["🎮  Xbox Game Bar (Win+G)"] = "🎮  Xbox Game Bar (Win+G)",
        ["🔊  Lauter"] = "🔊  Harder",
        ["🔉  Leiser"] = "🔉  Zachter",
        ["⏯  Wiedergabe/Pause"] = "⏯  Afspelen/Pauzeren",
        ["⌨  Andere Taste / Tastenkombination aufnehmen …"] = "⌨  Andere toets / toetscombinatie opnemen …",

        // ---------- Tastennamen ----------
        ["+ (Plus)"] = "+ (Plus)",
        ["− (Minus)"] = "− (Min)",
        ["Aufnahme"] = "Capture",
        ["GL (Rücktaste links)"] = "GL (rugknop links)",
        ["GR (Rücktaste rechts)"] = "GR (rugknop rechts)",
        ["Linker Stick drücken"] = "Linker stick indrukken",
        ["Rechter Stick drücken"] = "Rechter stick indrukken",
        ["Stick drücken"] = "Stick indrukken",
        ["A (groß, unten)"] = "A (groot, onder)",
        ["B (links)"] = "B (links)",
        ["X (rechts)"] = "X (rechts)",
        ["Y (oben)"] = "Y (boven)",
        ["L (ganz durchgedrückt)"] = "L (helemaal ingedrukt)",
        ["R (ganz durchgedrückt)"] = "R (helemaal ingedrukt)",
        ["untere Taste (quer)"] = "onderste knop (liggend)",
        ["rechte Taste (quer)"] = "rechter knop (liggend)",
        ["linke Taste (quer)"] = "linker knop (liggend)",
        ["obere Taste (quer)"] = "bovenste knop (liggend)",
        ["1 (quer) / Classic Y"] = "1 (liggend) / Classic Y",
        ["2 (quer) / Classic B"] = "2 (liggend) / Classic B",
        ["B (Abzug) / Classic ZR"] = "B (trekker) / Classic ZR",
        ["Kreuz (unten)"] = "Kruis (onder)",
        ["Kreis (rechts)"] = "Cirkel (rechts)",
        ["Viereck (links)"] = "Vierkant (links)",
        ["Dreieck (oben)"] = "Driehoek (boven)",
        ["PS-Taste"] = "PS-knop",
        ["Touchpad-Klick"] = "Touchpad-klik",
        ["Mikro stumm"] = "Microfoon dempen",
        ["Fn links (Edge)"] = "Fn links (Edge)",
        ["Rücktaste links (Edge)"] = "Rugknop links (Edge)",
        ["Rücktaste rechts (Edge)"] = "Rugknop rechts (Edge)",
        ["L3 (Stick drücken)"] = "L3 (stick indrukken)",
        ["R3 (Stick drücken)"] = "R3 (stick indrukken)",
        ["Ansicht/Zurück"] = "Weergave/Terug",
        ["Menü/Start"] = "Menu/Start",
        ["Xbox-Taste"] = "Xbox-knop",

        // ---------- Controller-Namen ----------
        ["Wii-Fernbedienung"] = "Wii-afstandsbediening",
        ["Xbox-Controller"] = "Xbox-controller",
        ["Xbox-Controller (Microsoft)"] = "Xbox-controller (Microsoft)",
        ["XInput (USB, Bluetooth oder Xbox-Adapter)"] = "XInput (USB, Bluetooth of Xbox-adapter)",

        // ---------- Übersicht / Karten ----------
        ["Trennen"] = "Verbreken",
        ["Vibrieren"] = "Trillen",
        ["Gyro kalibrieren"] = "Gyroscoop kalibreren",
        ["Ruhig liegen lassen …"] = "Rustig laten liggen …",
        ["Kalibriert ✓"] = "Gekalibreerd ✓",
        ["Hochkant halten"] = "Verticaal vasthouden",
        ["Quer halten"] = "Horizontaal vasthouden",
        ["Joy-Con trennen"] = "Joy-Con scheiden",
        ["Zum Paar verbinden"] = "Als paar verbinden",
        ["Joy-Con trennen – beide werden einzelne Controller"] = "Joy-Con scheiden – beide worden aparte controllers",
        ["Zum Paar verbinden – sucht einen freien Joy-Con"] = "Als paar verbinden – zoekt een vrije Joy-Con",
        ["Doppelt angezeigt? Verstecken"] = "Dubbel weergegeven? Verbergen",
        ["amiibo lesen"] = "amiibo lezen",
        ["Ring-Con ein"] = "Ring-Con aan",
        ["Ring-Con aus"] = "Ring-Con uit",
        ["Ring-Con wird gesucht …"] = "Ring-Con wordt gezocht …",
        ["IR-Kamera"] = "IR-camera",
        ["Akku"] = "Accu",
        ["Verbindung"] = "Verbinding",
        ["Adresse"] = "Adres",
        ["Seriennummer"] = "Serienummer",
        ["Griff"] = "Grip",
        ["Maus"] = "Muis",
        ["Gedrückt"] = "Ingedrukt",
        ["unbekannt"] = "onbekend",
        ["Charging Grip – GL/GR aktiv"] = "Charging Grip – GL/GR actief",
        ["aktiv (liegt auf dem Tisch)"] = "actief (ligt op tafel)",
        ["bereit – zum Benutzen auf den Tisch legen"] = "klaar – leg op tafel om te gebruiken",
        ["Bewegungssensor: keine Daten"] = "Bewegingssensor: geen gegevens",
        ["quer halten: Steuerkreuz links,\n1 und 2 rechts"] = "horizontaal: d-pad links,\n1 en 2 rechts",

        // ---------- Tooltips ----------
        ["Verbindung trennen. Der Controller verbindet sich beim nächsten Tastendruck wieder."] =
            "Verbinding verbreken. De controller verbindt bij de volgende knopdruk weer.",
        ["Controller kurz vibrieren lassen – zeigt, welcher Controller dieser Spieler ist."] =
            "Laat de controller kort trillen – laat zien welke controller bij deze speler hoort.",
        ["Controller ruhig auf den Tisch legen und klicken: misst den Gyro-Nullpunkt neu (gegen Abdriften)."] =
            "Leg de controller rustig op tafel en klik: meet het gyroscoop-nulpunt opnieuw (tegen drift).",
        ["Einzelnen Joy-Con quer (wie an der Switch) oder hochkant halten – wird je Joy-Con gemerkt. Hochkant gilt die Tastenbelegung von „Joy-Con-Paar“."] =
            "Houd een losse Joy-Con horizontaal (zoals op de Switch) of verticaal – wordt per Joy-Con onthouden. Verticaal geldt de toewijzing van „Joy-Con-paar“.",
        ["Versteckt den per USB angeschlossenen Controller vor Spielen (HidHide), damit sie nur den virtuellen Xbox-Controller sehen."] =
            "Verbergt de via USB aangesloten controller voor games (HidHide), zodat ze alleen de virtuele Xbox-controller zien.",
        ["amiibo mit dem NFC-Leser lesen und als Datei (.bin) speichern – z. B. für Emulatoren."] =
            "Lees een amiibo met de NFC-lezer en sla hem op als bestand (.bin) – bijv. voor emulators.",
        ["Ring-Con am rechten Joy-Con ein-/ausschalten: zusammendrücken = rechter Trigger, auseinanderziehen = linker Trigger. Beim Einschalten den Ring nicht berühren."] =
            "Schakel de Ring-Con van de rechter Joy-Con aan/uit: samenknijpen = rechter trigger, uitrekken = linker trigger. Raak de ring niet aan bij het inschakelen.",
        ["Live-Bild der IR-Kamera im rechten Joy-Con anzeigen."] = "Toon het livebeeld van de IR-camera in de rechter Joy-Con.",
        ["Links = empfindlicher (kleine Drehung, großer Ausschlag), rechts = ruhiger."] = "Links = gevoeliger (kleine draai, grote uitslag), rechts = rustiger.",
        ["Mindestausschlag des Sticks bei Bewegung – überwindet die Totzone des Spiels."] = "Minimale uitslag van de stick bij beweging – overwint de dode zone van de game.",
        ["Mitte = linear. Rechts = feiner um die Mitte (präzises Zielen), links = schneller."] = "Midden = lineair. Rechts = fijner rond het midden (precies richten), links = sneller.",
        ["So weit lässt sich ein analoger Trigger drücken, bevor er wirkt."] = "Hoe ver een analoge trigger kan worden ingedrukt voordat hij werkt.",
        ["Ab hier gilt der Trigger als ganz gedrückt (100 = erst am Anschlag)."] = "Vanaf hier geldt de trigger als volledig ingedrukt (100 = pas aan het einde).",
        ["Wie oft pro Sekunde Tasten mit „Turbo“ auslösen."] = "Hoe vaak per seconde „turbo“-knoppen worden geactiveerd.",

        // ---------- Infobereich ----------
        ["ViGEmBus-Treiber fehlt"] = "ViGEmBus-stuurprogramma ontbreekt",
        ["ViGEmBus herunterladen …"] = "ViGEmBus downloaden …",
        ["Verbinde …"] = "Verbinden …",
        ["Kein Controller – SYNC-Taste am Controller kurz drücken"] = "Geen controller – druk kort op de SYNC-knop van de controller",
        ["Ausgabe als"] = "Uitvoer als",
        ["Xbox-360-Controller (empfohlen)"] = "Xbox 360-controller (aanbevolen)",
        ["DualShock 4 (mit Gyro für Steam/Emulatoren)"] = "DualShock 4 (met gyro voor Steam/emulators)",
        ["Tastenbelegung"] = "Knoptoewijzing",
        ["Xbox-Belegung (untere Taste = A)"] = "Xbox-indeling (onderste knop = A)",
        ["Switch-2-Pro-Belegung (A bleibt A)"] = "Nintendo-indeling (A blijft A)",
        ["Automatisch (nach Spiel/Programm)"] = "Automatisch (naar spel/programma)",
        ["Mit Windows starten"] = "Starten met Windows",
        ["Einstellungen …"] = "Instellingen …",
        ["Kurzanleitung"] = "Snelstartgids",
        ["Protokoll öffnen"] = "Logboek openen",
        ["Beenden"] = "Afsluiten",
        ["N-Connect: warte auf Controller (SYNC drücken)"] = "N-Connect: wachten op controller (druk op SYNC)",
        ["N-Connect: ViGEmBus fehlt"] = "N-Connect: ViGEmBus ontbreekt",
        ["Neue Version verfügbar"] = "Nieuwe versie beschikbaar",
        ["Einstellungen fehlerhaft"] = "Instellingen beschadigd",
        ["settings.json konnte nicht gelesen werden – es gelten die Standardwerte."] = "settings.json kon niet worden gelezen – de standaardwaarden gelden.",
        ["Ohne ViGEmBus kann kein virtueller Controller erzeugt werden. Bitte das Setup erneut ausführen oder ViGEmBus installieren (Rechtsklick auf das Symbol → ViGEmBus herunterladen)."] =
            "Zonder ViGEmBus kan geen virtuele controller worden gemaakt. Voer de installatie opnieuw uit of installeer ViGEmBus (rechtermuisklik op het pictogram → ViGEmBus downloaden).",

        // ---------- Dialoge ----------
        ["Tastatur-Taste festlegen"] = "Toetsenbordtoets instellen",
        ["Übernehmen"] = "Toepassen",
        ["Abbrechen"] = "Annuleren",
        ["Ja"] = "Ja",
        ["Nein"] = "Nee",
        ["Turbo / Dauerfeuer"] = "Turbo / snelvuur",
        ["Tastatur-Taste aufnehmen …"] = "Toetsenbordtoets opnemen …",
        ["Makro (Tastenfolge)"] = "Macro (knopvolgorde)",
        ["Ungültig – bitte Schreibweise prüfen (siehe oben)."] = "Ongeldig – controleer de schrijfwijze (zie hierboven).",
        ["Neues Profil"] = "Nieuw profiel",
        ["Name des Profils (z. B. der Spielname):"] = "Naam van het profiel (bijv. de naam van het spel):",
        ["Profil umbenennen"] = "Profiel hernoemen",
        ["Neuer Name:"] = "Nieuwe naam:",
        ["Ein Profil mit diesem Namen gibt es schon."] = "Er bestaat al een profiel met deze naam.",
        ["Die Datei enthält kein gültiges Controller-Profil."] = "Het bestand bevat geen geldig controllerprofiel.",
        ["Alle Einstellungen und Tastenbelegungen auf Standard zurücksetzen?"] = "Alle instellingen en knoptoewijzingen resetten?",
        ["Suche …"] = "Zoeken …",
        ["Kein Bluetooth-Adapter gefunden."] = "Geen Bluetooth-adapter gevonden.",
        ["IR-Kamera (Joy-Con R)"] = "IR-camera (Joy-Con R)",
        ["Auflösung:"] = "Resolutie:",
        ["40 × 30 (schnell)"] = "40 × 30 (snel)",
        ["320 × 240 (langsam)"] = "320 × 240 (langzaam)",
        ["Kamera startet …"] = "Camera start …",
        ["läuft – Joy-Con auf eine Lichtquelle oder die Hand richten"] = "actief – richt de Joy-Con op een lichtbron of je hand",
        ["Kamera startet nicht (Details im Protokoll)"] = "Camera start niet (details in het logboek)",
        ["Kein Ring-Con gefunden. Den rechten Joy-Con (Switch 1) fest in den Ring-Con schieben und erneut versuchen."] =
            "Geen Ring-Con gevonden. Schuif de rechter Joy-Con (Switch 1) stevig in de Ring-Con en probeer opnieuw.",
        ["Kein amiibo erkannt. Bitte das amiibo flach an den NFC-Leser halten (Joy-Con: auf den rechten Stick, Pro Controller: auf das NFC-Logo) und erneut versuchen."] =
            "Geen amiibo herkend. Houd de amiibo plat tegen de NFC-lezer (Joy-Con: op de rechter stick; Pro Controller: op het NFC-logo) en probeer opnieuw.",
        ["NFC-Leser wird eingeschaltet …"] = "NFC-lezer wordt ingeschakeld …",
        ["amiibo an den Leser halten (rechter Stick des Joy-Con bzw. NFC-Logo des Pro Controllers) …"] =
            "Houd de amiibo tegen de lezer (rechter stick van de Joy-Con of NFC-logo van de Pro Controller) …",
        ["amiibo speichern"] = "amiibo opslaan",
        ["Doppelte Controller verhindern"] = "Dubbele controllers voorkomen",
        ["Dafür wird das kostenlose Programm HidHide gebraucht (von den Machern von ViGEmBus).\n\nJetzt die Download-Seite öffnen? Nach der Installation hier erneut klicken."] =
            "Daarvoor is het gratis programma HidHide nodig (van de makers van ViGEmBus).\n\nNu de downloadpagina openen? Klik hier na de installatie opnieuw.",
        ["HidHide konnte nicht eingerichtet werden (abgebrochen oder fehlgeschlagen). Details im Protokoll."] =
            "HidHide kon niet worden ingesteld (afgebroken of mislukt). Details in het logboek.",
        ["Der Controller hat sich bewegt oder keine Bewegungsdaten geliefert.\nBitte flach auf den Tisch legen, nicht berühren und erneut versuchen."] =
            "De controller heeft bewogen of geen bewegingsgegevens geleverd.\nLeg hem plat op tafel zonder aan te raken en probeer opnieuw.",
        ["Spiel oder Programm wählen"] = "Spel of programma kiezen",
        ["Profil exportieren"] = "Profiel exporteren",
        ["Profil importieren"] = "Profiel importeren",
        ["Verstanden"] = "Begrepen",
        ["Einstellungen öffnen"] = "Instellingen openen",
        ["Willkommen"] = "Welkom",

        // ---------- Neues Hauptfenster (Navigation, Seiten, Zeilen) ----------
        ["Allgemein"] = "Algemeen",
        ["Sticks & Vibration"] = "Sticks en trilling",
        ["Gyro & Maus"] = "Gyroscoop en muis",
        ["Joy-Con & Wii"] = "Joy-Con en Wii",
        ["Ein"] = "Aan",
        ["Aus"] = "Uit",
        ["Verbundene Controller mit Live-Anzeige. Über „Einstellungen“ an einem Controller passt du genau diesen an."] =
            "Verbonden controllers met liveweergave. Met „Instellingen“ bij een controller pas je precies die aan.",
        ["Jede Taste kann ein Gamepad-Knopf, eine Tastaturtaste, ein Mausklick, Turbo oder ein Makro sein. " +
         "Tipp: Drückst du eine Taste am Controller, wird ihre Zeile hervorgehoben."] =
            "Elke knop kan een gamepadknop, een toets, een muisklik, turbo of macro zijn. " +
            "Tip: druk een knop op de controller in om de rij te markeren.",
        ["Profil"] = "Profiel",
        ["Neu"] = "Nieuw",
        ["Umbenennen, löschen, exportieren, importieren"] = "Hernoemen, verwijderen, exporteren, importeren",
        ["Ein eigenes Profil gilt automatisch, solange eines seiner Programme im Vordergrund ist – sonst „Standard“."] =
            "Een eigen profiel geldt automatisch zolang een van zijn programma's op de voorgrond staat – anders „Standaard“.",
        ["Aktiv bei Programm"] = "Actief bij programma",
        ["Programmdateien, bei denen dieses Profil gilt (mit Komma trennen)."] = "Programmabestanden waarvoor dit profiel geldt (scheiden met komma's).",
        ["Standard gilt für alle Programme"] = "Standaard geldt voor alle programma's",
        ["Wählen …"] = "Kiezen …",
        ["Bearbeiten"] = "Bewerken",
        ["Jeder Controller hat seine eigene Belegung."] = "Elke controller heeft zijn eigen toewijzing.",
        ["Ebene"] = "Laag",
        ["Normal"] = "Normaal",
        ["Shift-Ebene"] = "Shift-laag",
        ["Die Shift-Ebene gilt, solange eine Taste mit „Shift-Ebene“ gehalten wird."] = "De Shift-laag geldt zolang een knop op „Shift-laag“ is ingedrukt.",
        ["Tasten"] = "Knoppen",
        ["Standardwerte für alle Controller. Eigene Werte für einzelne Controller stellst du unten oder in der Übersicht ein."] =
            "Standaardwaarden voor alle controllers. Eigen waarden per controller stel je hieronder of in het overzicht in.",
        ["Sticks"] = "Sticks",
        ["Totzone"] = "Dode zone",
        ["So weit lässt sich ein Stick bewegen, bevor er wirkt (gegen Abdriften)."] = "Hoe ver een stick kan bewegen voordat hij reageert (tegen drift).",
        ["Kennlinie"] = "Karakteristiek",
        ["„linear“ = gleichmäßig. Höher = feiner um die Mitte (präzises Zielen), niedriger = schneller."] =
            "„lineair“ = gelijkmatig. Hoger = fijner rond het midden (precies richten), lager = sneller.",
        ["Analoge Trigger (GameCube)"] = "Analoge triggers (GameCube)",
        ["So weit lässt sich ein Trigger drücken, bevor er wirkt."] = "Hoe ver een trigger kan worden ingedrukt voordat hij reageert.",
        ["Voll gedrückt ab"] = "Volledig ingedrukt vanaf",
        ["Ab hier gilt der Trigger als ganz gedrückt (100 % = erst am Anschlag)."] = "Vanaf hier geldt de trigger als volledig ingedrukt (100 % = pas aan het einde).",
        ["Spiele dürfen den Controller vibrieren lassen."] = "Games mogen de controller laten trillen.",
        ["Stärke"] = "Sterkte",
        ["Turbo-Geschwindigkeit"] = "Turbosnelheid",
        ["Wie oft pro Sekunde Tasten mit „Turbo“ auslösen."] = "Hoe vaak per seconde „turbo“-knoppen worden geactiveerd.",
        ["Eigene Werte je Controller"] = "Eigen waarden per controller",
        ["Werte nur für diesen Controller – ohne eigenen Wert gilt der allgemeine."] = "Waarden alleen voor deze controller – zonder eigen waarde geldt de algemene.",
        ["Bewegungssteuerung: Zielen per Gyro und den Controller als Maus nutzen."] = "Bewegingsbesturing: richten met de gyroscoop en de controller als muis gebruiken.",
        ["Gyro als rechter Stick"] = "Gyroscoop als rechter stick",
        ["Modus"] = "Modus",
        ["Zum Zielen in Spielen ohne eigene Gyro-Steuerung. „Gyro-Stick“ kann auch einer Taste zugewiesen werden."] =
            "Om te richten in games zonder eigen gyro-besturing. „Gyro-stick“ kan ook aan een knop worden toegewezen.",
        ["Aus (nur per Taste „Gyro-Stick“)"] = "Uit (alleen via knop „gyro-stick“)",
        ["Immer"] = "Altijd",
        ["Beim Zielen (solange ZL / LT gedrückt)"] = "Bij richten (zolang ZL / LT is ingedrukt)",
        ["Empfindlichkeit"] = "Gevoeligheid",
        ["Drehgeschwindigkeit für vollen Stick-Ausschlag – kleiner = empfindlicher."] = "Draaisnelheid voor volledige stickuitslag – lager = gevoeliger.",
        ["Mindestausschlag"] = "Minimale uitslag",
        ["Überwindet die Stick-Totzone des Spiels bei kleinen Bewegungen."] = "Overwint de stick-dode zone van de game bij kleine bewegingen.",
        ["Hoch/runter umkehren"] = "Omhoog/omlaag omkeren",
        ["Links/rechts umkehren"] = "Links/rechts omkeren",
        ["Gyro-Maus"] = "Gyro-muis",
        ["Geschwindigkeit"] = "Snelheid",
        ["Mauszeiger per Bewegung – über eine Taste mit „Gyro-Maus“ (Tastenbelegung)."] = "Muisaanwijzer via beweging – met een knop „gyro-muis“ (knoptoewijzing).",
        ["Mausrichtung (Gyro-Maus und Joy-Con-Maus)"] = "Muisrichting (gyro-muis en Joy-Con-muis)",
        ["Gyro-Funktionen einer Taste zuweisen"] = "Gyro-functies aan een knop toewijzen",
        ["Gyro-Maus oder Gyro-Stick ein/aus bzw. solange gehalten"] = "Gyro-muis of gyro-stick aan/uit of zolang ingedrukt",
        ["Joy-Con als Paar oder einzeln, Joy-Con 2 als Maus und Wii-Controller."] = "Joy-Con als paar of los, Joy-Con 2 als muis en Wii-controllers.",
        ["Zu einem Controller zusammenfassen"] = "Combineren tot één controller",
        ["Ein linker und ein rechter Joy-Con werden automatisch ein Paar."] = "Een linker en rechter Joy-Con vormen automatisch een paar.",
        ["Gyro beim Paar vom"] = "Gyroscoop van het paar van",
        ["Rechter Joy-Con (wie Switch)"] = "Rechter Joy-Con (zoals op de Switch)",
        ["Linker Joy-Con"] = "Linker Joy-Con",
        ["Paar lösen oder verbinden"] = "Paar scheiden of verbinden",
        ["Einen Joy-Con quer halten und SL oder SR drücken löst ihn aus dem Paar. L am linken und R am rechten Joy-Con gleichzeitig drücken verbindet sie wieder. Die Wahl wird je Joy-Con gemerkt."] =
            "Houd een Joy-Con horizontaal en druk op SL of SR om hem uit het paar te halen. L op de linker en R op de rechter tegelijk indrukken voegt ze weer samen. De keuze wordt per Joy-Con onthouden.",
        ["Joy-Con 2 als Maus"] = "Joy-Con 2 als muis",
        ["Als Maus, wenn er auf dem Tisch liegt"] = "Als muis wanneer hij op tafel ligt",
        ["Joy-Con 2 auf die Seite legen und wie eine Maus schieben."] = "Leg de Joy-Con 2 op zijn kant en schuif hem als een muis.",
        ["Mausgeschwindigkeit"] = "Muissnelheid",
        ["Tasten im Mausmodus"] = "Knoppen in muisstand",
        ["R/L = Linksklick, ZR/ZL = Rechtsklick, Stick drücken = Mittelklick, Stick hoch/runter = Scrollen."] =
            "R/L = linkermuisklik, ZR/ZL = rechtermuisklik, stick indrukken = middelklik, stick omhoog/omlaag = scrollen.",
        ["Zeiger steuert die Maus"] = "Pointer bestuurt de muis",
        ["Wii-Fernbedienung auf die Sensorleiste richten, um den Mauszeiger zu bewegen."] = "Richt de Wii-afstandsbediening op de sensorbalk om de muisaanwijzer te bewegen.",
        ["Wie Spiele die Controller sehen, Verbindung, Darstellung und Programm."] = "Hoe games de controllers zien, verbinding, weergave en programma.",
        ["Ausgabe"] = "Uitvoer",
        ["Controller erscheint als"] = "Controller verschijnt als",
        ["Xbox 360 läuft mit fast allen Spielen. DualShock 4 bietet Bewegungssteuerung (Steam, Emulatoren)."] =
            "Xbox 360 werkt met bijna alle games. DualShock 4 biedt bewegingsbesturing (Steam, emulators).",
        ["Xbox 360 läuft mit fast allen Spielen und Steam. DualShock 4 bietet zusätzlich Bewegungssteuerung (Steam, Emulatoren). Gilt für alle Controller ohne eigene Einstellung (Karte → Einstellungen → Tasten)."] =
            "Xbox 360 werkt met bijna alle games en Steam. DualShock 4 voegt bewegingsbesturing toe (Steam, emulators). Geldt voor alle controllers zonder eigen instelling (kaart → Instellingen → Knoppen).",
        ["Original-Controller verstecken"] = "Originele controllers verbergen",
        ["Controller verbinden"] = "Controllers verbinden",
        ["SYNC-Taste am Controller drücken – N-Connect findet und koppelt ihn selbst. Danach reicht künftig ein Tastendruck."] =
            "Druk op de SYNC-knop van de controller – N-Connect vindt en koppelt hem zelf. Daarna volstaat een knopdruk.",
        ["So kommt der Controller in den Kopplungsmodus"] = "Zo komt de controller in koppelmodus",
        ["Kurz die kleine SYNC-Taste drücken."] = "Druk kort op de kleine SYNC-knop.",
        ["SYNC-Taste drücken, bis die Lichter laufen."] = "Druk op de SYNC-knop tot de lampjes lopen.",
        ["Batteriefach öffnen und die rote SYNC-Taste drücken."] = "Open het batterijvak en druk op de rode SYNC-knop.",
        ["Die SYNC-Taste auf der Unterseite drücken."] = "Druk op de SYNC-knop aan de onderkant.",
        ["PS + Teilen bzw. Create halten, bis die Lichtleiste schnell blinkt."] =
            "Houd PS + Share/Create ingedrukt tot de lichtbalk snel knippert.",
        ["Kopplungstaste oben halten, bis die Xbox-Taste blinkt."] = "Houd de koppelknop bovenop ingedrukt tot de Xbox-knop knippert.",
        ["Status"] = "Status",
        ["Suche läuft …"] = "Zoeken …",
        ["Suche läuft – jetzt SYNC drücken …"] = "Bezig met zoeken – druk nu op SYNC …",
        ["Weitere Controller? Einfach SYNC drücken."] = "Meer controllers? Druk gewoon op SYNC.",
        ["Wartet auf einen Controller im Kopplungsmodus."] = "Wacht op een controller in koppelmodus.",
        ["Suche beendet"] = "Zoeken beëindigd",
        ["Die Controller stehen in der Übersicht und verbinden sich künftig per Tastendruck."] =
            "De controllers staan in het overzicht en verbinden voortaan met een knopdruk.",
        ["Kein Controller im Kopplungsmodus gefunden. SYNC-Taste drücken und „Erneut suchen“ klicken."] =
            "Geen controller in koppelmodus gevonden. Druk op SYNC en klik op „Opnieuw zoeken“.",
        ["Verbunden"] = "Verbonden",
        ["Erneut suchen"] = "Opnieuw zoeken",
        ["Fertig"] = "Klaar",
        ["Im Spiel"] = "In het spel",
        ["Dreht …"] = "Draait …",
        ["Testdrehung (360°)"] = "Testdraai (360°)",
        ["Testdrehung"] = "Testdraai",
        ["aus"] = "uit",
        ["Gyro-Beschleunigung"] = "Gyro-versnelling",
        ["Bei schneller Drehung"] = "Bij snelle draai",
        ["Langsame Bewegungen bleiben fein, schnelle drehen weiter (wie JoyShockMapper). Voll ab 120 °/s, unter 20 °/s normal. Gilt für Gyro-Stick und Gyro-Maus."] =
            "Langzame bewegingen blijven fijn, snelle draaien verder (zoals JoyShockMapper). Volledig vanaf 120 °/s, normaal onder 20 °/s. Geldt voor gyro-stick en gyro-muis.",
        ["Flick-Stick (Spiele mit Maussteuerung)"] = "Flick stick (games met muisbesturing)",
        ["Flick-Stick"] = "Flick stick",
        ["Rechten Stick in eine Richtung schieben = Kamera dreht sofort dorthin; am Rand drehen = Kamera dreht mit. Zielen dann per Gyro. Der rechte Stick geht nicht mehr ans Spiel."] =
            "Rechter stick in een richting duwen = camera draait meteen die kant op; langs de rand draaien = camera draait mee. Daarna richten met gyro. De rechter stick gaat niet meer naar de game.",
        ["Mausbewegung je Umdrehung"] = "Muisbeweging per omwenteling",
        ["Je Spiel einmal einstellen: „Testdrehung“ klicken, ins Spiel wechseln – nach 3 s dreht die Kamera einmal. Genau eine volle Drehung = richtig."] =
            "Eenmalig per spel instellen: klik op „Testdraai“, wissel naar de game – na 3 s draait de camera eenmaal. Precies één volle draai = goed.",
        ["Flick-Dauer"] = "Flick-duur",
        ["So lange dauert die Drehung beim Flick (0 = sofort)."] = "Hoe lang de draai van een flick duurt (0 = meteen).",
        ["Gyro-Maus oder Gyro-Stick ein/aus bzw. solange gehalten, „Gyro anhalten“ (Ratchet: Controller zurückführen, ohne dass sich das Ziel bewegt)"] =
            "Gyro-muis of gyro-stick aan/uit of zolang ingedrukt, „gyro pauzeren“ (ratchet: controller terugvoeren zonder dat het vizier beweegt)",
        ["✋  Gyro anhalten (solange gehalten, „Ratchet“)"] = "✋  Gyro pauzeren (zolang ingedrukt, „ratchet“)",
        ["Spieler-LED und Lichtleiste vom Spiel"] = "Speler-LED en lichtbalk van het spel",
        ["Die Spieler-LEDs zeigen den Xbox-Platz, den Windows vergibt. Bei DualShock 4 steuert die Lichtleiste des Spiels die HOME-LED (Switch 1 Pro Controller, rechter Joy-Con)."] =
            "De speler-LED's tonen de Xbox-plek die Windows toewijst. Bij DualShock 4 stuurt de lichtbalk van het spel de HOME-LED (Switch 1 Pro Controller, rechter Joy-Con).",
        ["HidHide installieren …"] = "HidHide installeren …",
        ["Empfohlen: Steam und viele Spiele kennen Switch-1-, NSO- und USB-Controller selbst und sähen sie sonst doppelt. Läuft nach der Installation ohne Rückfrage (sonst fragt Windows nach Adminrechten)."] =
            "Aanbevolen: Steam en veel games herkennen Switch 1-, NSO- en USB-controllers zelf en zouden ze anders dubbel zien. Werkt na installatie zonder te vragen (anders vraagt Windows om beheerdersrechten).",
        ["Steam und viele Spiele sehen Switch-1-, NSO- und USB-Controller sonst doppelt. Dafür wird das kostenlose HidHide gebraucht (bei der N-Connect-Installation dabei, hier nachträglich)."] =
            "Anders zien Steam en veel games Switch 1-, NSO- en USB-controllers dubbel. Daarvoor is de gratis HidHide nodig (meegeleverd bij de N-Connect-installatie, hier achteraf).",
        ["Erscheint als"] = "Verschijnt als",
        ["Wie allgemein"] = "Zoals in Algemeen",
        ["Nur für diesen Controller. Xbox 360 läuft überall; DualShock 4 bringt zusätzlich Gyro nach Steam und in Emulatoren. „Wie allgemein“ folgt der Seite „Allgemein“."] =
            "Alleen voor deze controller. Xbox 360 werkt overal; DualShock 4 voegt gyro toe in Steam en emulators. „Zoals in Algemeen“ volgt de pagina „Algemeen“.",
        ["Der echte Xbox-Controller – Spiele sehen ihn von Windows aus direkt. Belegungen hier wirken auf Sonderaktionen (Tastatur, Makros, Gyro), nicht auf den Controller selbst."] =
            "De echte Xbox-controller – games zien hem al direct vanuit Windows. Toewijzingen hier werken op speciale acties (toetsenbord, macro's, gyro), niet op de controller zelf.",
        ["Steam und manche Spiele sehen diesen Controller sonst doppelt. Abhilfe: HidHide installieren (Seite „Allgemein“ → „Original-Controller verstecken“)."] =
            "Anders zien Steam en sommige games deze controller dubbel. Oplossing: HidHide installeren (pagina „Algemeen“ → „Originele controllers verbergen“).",
        ["Original-Controller vor Spielen versteckt. Steam bitte einmal neu starten – danach sieht es nur noch den virtuellen Controller."] =
            "Originele controllers verborgen voor games. Start Steam eenmaal opnieuw – daarna ziet het alleen de virtuele controller.",
        ["Original-Controller vor Spielen versteckt – Steam und Spiele sehen nur noch den virtuellen Controller."] =
            "Originele controllers verborgen voor games – Steam en games zien voortaan alleen de virtuele controller.",
        ["Original-Controller nicht versteckt (Abfrage abgebrochen). Nachholen: Controller → Einstellungen → Extras → „Doppelt angezeigt?“."] =
            "Originele controllers niet verborgen (vraag afgebroken). Inhalen: controller → Instellingen → Extra's → „Dubbel weergegeven?“.",
        ["Tastenanordnung A/B/X/Y"] = "Knopindeling A/B/X/Y",
        ["Xbox: nach Position (untere Taste = A). Nintendo: nach Beschriftung (A bleibt A)."] = "Xbox: op positie (onderste knop = A). Nintendo: op opschrift (A blijft A).",
        ["Verbinden"] = "Verbinden",
        ["Per Tastendruck verbinden"] = "Verbinden met een knopdruk",
        ["Gekoppelte Controller verbinden sich ohne SYNC-Taste."] = "Gekoppelde controllers verbinden zonder SYNC-knop.",
        ["Ohne Eingabe trennen nach"] = "Verbreken zonder invoer na",
        ["Spart Akku, wenn ein Controller liegen bleibt."] = "Bespaart accu als een controller blijft liggen.",
        ["N-Connect startet unsichtbar im Infobereich."] = "N-Connect start onzichtbaar in het systeemvak.",
        ["Darstellung und Sprache"] = "Weergave en taal",
        ["Farbmodus"] = "Kleurmodus",
        ["Mica-Effekt"] = "Mica-effect",
        ["Durchscheinende Titelleiste (ab Windows 11)."] = "Doorschijnende titelbalk (vanaf Windows 11).",
        ["Erweitert"] = "Geavanceerd",
        ["Gyro für Emulatoren (DSU)"] = "Gyroscoop voor emulators (DSU)",
        ["Cemuhook-Server auf Port 26760 – wirkt nach einem Neustart von N-Connect."] = "Cemuhook-server op poort 26760 – actief na een herstart van N-Connect.",
        ["Nach Updates suchen"] = "Naar updates zoeken",
        ["Beim Start auf GitHub nach einer neuen Version suchen."] = "Bij het starten op GitHub naar een nieuwe versie zoeken.",
        ["Tastenbelegungen und Werte zurücksetzen. Gekoppelte Controller bleiben erhalten."] = "Knoptoewijzingen en waarden resetten. Gekoppelde controllers blijven behouden.",
        ["Zurücksetzen"] = "Resetten",

        // ---------- Controller-Karte ----------
        ["Einstellungen"] = "Instellingen",
        ["Tastenbelegung und Einstellungen nur für diesen Controller"] = "Knoptoewijzing en instellingen alleen voor deze controller",
        ["Feineinstellung"] = "Fijnafstelling",
        ["Gyro"] = "Gyroscoop",
        ["Extras"] = "Extra's",
        ["Belegung für alle Spiele (Standard) oder ein eigenes Profil."] = "Toewijzing voor alle games (standaard) of een eigen profiel.",
        ["Profile"] = "Profielen",
        ["Profile anlegen, umbenennen, exportieren …"] = "Profielen aanmaken, hernoemen, exporteren …",
        ["Drück eine Taste am Controller – ihre Zeile leuchtet auf. ⌨ weist eine Tastaturtaste zu, ↺ setzt zurück."] =
            "Druk een knop op de controller in – de rij licht op. ⌨ wijst een toetsenbordtoets toe, ↺ reset.",
        ["Tastatur-Taste zuweisen: klicken und die gewünschte Taste oder Kombination drücken."] = "Toetsenbordtoets toewijzen: klik en druk de gewenste toets of combinatie in.",
        ["Zurück auf die Standardbelegung"] = "Terug naar de standaardtoewijzing",
        ["Ohne eigenen Wert gilt der allgemeine Wert der Seite „Sticks & Vibration“."] = "Zonder eigen waarde geldt de algemene van de pagina „Sticks en trilling“.",
        ["Stick-Totzone"] = "Stick-dode zone",
        ["Stick-Kennlinie"] = "Stick-karakteristiek",
        ["Trigger-Totzone"] = "Trigger-dode zone",
        ["Trigger voll gedrückt ab"] = "Trigger volledig ingedrukt vanaf",
        ["Vibrationsstärke"] = "Trilsterkte",
        ["Gyro-Maus-Geschwindigkeit"] = "Snelheid gyro-muis",
        ["Eigenen Wert entfernen – es gilt wieder der allgemeine Wert"] = "Eigen waarde verwijderen – de algemene waarde geldt weer",
        ["Kalibrieren"] = "Kalibreren",
        ["Controller ruhig auf den Tisch legen und klicken: misst den Nullpunkt neu (gegen Abdriften)."] =
            "Leg de controller rustig op tafel en klik: meet het nulpunt opnieuw (tegen drift).",
        ["Gyro als rechter Stick und Mausrichtung"] = "Gyroscoop als rechter stick en muisrichting",
        ["Gilt für alle Controller"] = "Geldt voor alle controllers",
        ["Paar"] = "Paar",
        ["Joy-Con quer halten und SL oder SR drücken löst das Paar, L + R gleichzeitig verbindet es."] =
            "Houd een Joy-Con horizontaal en druk op SL of SR om het paar te scheiden; L + R tegelijk verbindt het weer.",
        ["Haltung"] = "Houding",
        ["Quer"] = "Horizontaal",
        ["Hochkant"] = "Verticaal",
        ["Quer wie an der Switch oder hochkant – hochkant gilt die Belegung von „Joy-Con-Paar“."] =
            "Horizontaal zoals op de Switch of verticaal – verticaal geldt de toewijzing van „Joy-Con-paar“.",
        ["Mausmodus, Geschwindigkeit und Tasten"] = "Muisstand, snelheid en knoppen",
        ["Lesen …"] = "Lezen …",
        ["Einschalten"] = "Inschakelen",
        ["Ausschalten"] = "Uitschakelen",
        ["Wird gesucht …"] = "Zoeken …",
        ["Öffnen"] = "Openen",
        ["Verstecken"] = "Verbergen",
        ["amiibo an den NFC-Leser halten und als Datei (.bin) speichern – z. B. für Emulatoren."] =
            "Houd een amiibo tegen de NFC-lezer en sla hem op als bestand (.bin) – bijv. voor emulators.",
        ["Zusammendrücken = rechter Trigger, auseinanderziehen = linker Trigger. Beim Einschalten nicht berühren."] =
            "Samenknijpen = rechter trigger, uitrekken = linker trigger. Niet aanraken bij het inschakelen.",
        ["Live-Bild der Infrarotkamera im rechten Joy-Con."] = "Livebeeld van de infraroodcamera in de rechter Joy-Con.",
        ["Doppelt angezeigt?"] = "Dubbel weergegeven?",
        ["Versteckt den Original-Controller vor Steam und Spielen (HidHide) – sie sehen dann nur den virtuellen Controller."] =
            "Verbergt de originele controller voor Steam en games (HidHide) – ze zien dan alleen de virtuele controller.",
        ["bereit (auf den Tisch legen)"] = "klaar (leg op tafel)",
        ["amiibo-Abbild (*.bin)|*.bin"] = "amiibo-afbeelding (*.bin)|*.bin",
        ["Controller-Profil (*.ncprofile.json)|*.ncprofile.json|JSON (*.json)|*.json"] = "Controllerprofiel (*.ncprofile.json)|*.ncprofile.json|JSON (*.json)|*.json",
        ["Programme (*.exe)|*.exe"] = "Programma's (*.exe)|*.exe",
        ["Kein Controller verbunden\n\n" +
         "Switch-2-Controller: kurz die SYNC-Taste drücken – danach reicht ein beliebiger Tastendruck.\n" +
         "Switch-1-, NSO- und Wii-Controller: SYNC-Taste drücken – N-Connect koppelt sie selbst.\n" +
         "Oder hier gezielt suchen und koppeln:"] =
            "Geen controller verbonden\n\n" +
            "Switch 2-controllers: druk kort op de SYNC-knop – daarna volstaat elke knopdruk.\n" +
            "Switch 1-, NSO- en Wii-controllers: druk op de SYNC-knop – N-Connect koppelt ze zelf.\n" +
            "Of hier gericht zoeken en koppelen:",
        ["Controller suchen …"] = "Controllers zoeken …",
        ["Kein Controller verbunden"] = "Geen controller verbonden",
        ["Switch-1-, NSO- und Wii-Controller suchen und koppeln (SYNC-Taste drücken)."] =
            "Switch 1-, NSO- en Wii-controllers zoeken en koppelen (druk op de SYNC-knop).",
        ["Neue Controller automatisch koppeln"] = "Nieuwe controllers automatisch koppelen",
        ["Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive, Wii und PlayStation: einfach SYNC " +
         "drücken – kein Umweg über die Windows-Bluetooth-Einstellungen. Gesucht wird nur, solange niemand spielt."] =
            "Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive, Wii en PlayStation: druk gewoon op SYNC – " +
            "geen omweg via de Windows-Bluetooth-instellingen. Er wordt alleen gezocht als niemand speelt.",
        ["Gezielt suchen"] = "Gericht zoeken",
        ["Sucht eine Minute lang nach Controllern im Kopplungsmodus."] = "Zoekt een minuut lang naar controllers in koppelmodus.",
        ["Controller koppeln …"] = "Controller koppelen …",
        ["Controller koppeln"] = "Controller koppelen",
        ["Linken Joy-Con umbenennen …"] = "Linker Joy-Con hernoemen …",
        ["Rechten Joy-Con umbenennen …"] = "Rechter Joy-Con hernoemen …",
        ["Controller umbenennen"] = "Controller hernoemen",
        ["Spielerplatz"] = "Spelerplek",
        ["N-Connect aktualisieren"] = "N-Connect bijwerken",
        ["HidHide aktualisieren"] = "HidHide bijwerken",
        ["HidHide-Update verfügbar"] = "HidHide-update beschikbaar",
        ["HidHide aktuell halten"] = "HidHide actueel houden",
        ["Beim Start nach einer neuen HidHide-Version suchen. Installiert wird nur nach Rückfrage (geprüfter Download vom Hersteller, Neustart nötig)."] =
            "Bij het starten naar een nieuwe HidHide-versie zoeken. Geïnstalleerd wordt alleen na overleg (gecontroleerde download van de fabrikant, herstart nodig).",
        ["Der Download hat nicht geklappt oder die Datei war fehlerhaft. Die Release-Seite im Browser öffnen?"] =
            "De download is mislukt of het bestand was defect. De releasepagina in de browser openen?",
        ["Alle Controller trennen"] = "Alle controllers verbreken",
        ["Sticks kalibrieren"] = "Sticks kalibreren",
        ["Kalibrieren …"] = "Kalibreren …",
        ["Gegen Drift oder zu kleinen Ausschlag: Mitte und Rand neu messen. Wird nur in N-Connect gespeichert, der Controller bleibt unverändert."] =
            "Tegen drift of te kleine uitslag: midden en rand opnieuw meten. Wordt alleen in N-Connect opgeslagen, de controller blijft onveranderd.",
        ["Linker Stick"] = "Linker stick",
        ["Rechter Stick"] = "Rechter stick",
        ["Stick"] = "Stick",
        ["Stick (linker Joy-Con)"] = "Stick (linker Joy-Con)",
        ["Stick (rechter Joy-Con)"] = "Stick (rechter Joy-Con)",
        ["Neu messen"] = "Opnieuw meten",
        ["Werkswerte"] = "Fabriekswaarden",
        ["Der Punkt zeigt, wo der Stick gerade steht. Steht er losgelassen nicht in der Mitte oder erreicht er den Kreis nicht, auf „Neu messen“ klicken."] =
            "De stip toont waar de stick staat. Staat hij losgelaten niet in het midden of bereikt hij de cirkel niet, klik op „Opnieuw meten“.",
        ["Gilt gerade: eigene Kalibrierung."] = "Momenteel in gebruik: eigen kalibratie.",
        ["Gilt gerade: Werkswerte des Controllers."] = "Momenteel in gebruik: fabriekswaarden van de controller.",
        ["1/2 – Stick loslassen und den Controller ruhig halten …"] = "1/2 – laat de stick los en houd de controller stil …",
        ["2/2 – Stick bis zum Anschlag drücken und langsam ein- bis zweimal im Kreis drehen."] =
            "2/2 – druk de stick tot de aanslag en draai langzaam een tot twee keer rond.",
        ["Fertig. „Übernehmen“ speichert die neue Kalibrierung für diesen Controller."] = "Klaar. „Toepassen“ slaat de nieuwe kalibratie voor deze controller op.",
        ["Der Stick hat den Rand nicht erreicht. Bitte bis zum Anschlag drücken und erneut messen."] =
            "De stick heeft de rand niet bereikt. Druk hem tot de aanslag en meet opnieuw.",
        ["Übernommen ✓ – gilt ab sofort."] = "Toegepast ✓ – direct actief.",
        ["Werkswerte des Controllers gelten wieder."] = "De fabriekswaarden van de controller gelden weer.",
        ["Gyro einrichten"] = "Gyroscoop instellen",
        ["Einrichten …"] = "Instellen …",
        ["Zielen per Bewegung einrichten"] = "Richten met beweging instellen",
        ["Schritt für Schritt: Nullpunkt, wann der Gyro zielt, Empfindlichkeit – mit Vorschau."] =
            "Stap voor stap: nulpunt, wanneer de gyro richt, gevoeligheid – met voorbeeld.",
        ["1  Nullpunkt"] = "1  Nulpunt",
        ["Controller flach auf den Tisch legen, nicht berühren – verhindert, dass das Ziel von selbst wandert."] =
            "Leg de controller plat op tafel zonder aan te raken – voorkomt dat het vizier vanzelf wegdrijft.",
        ["Nullpunkt messen"] = "Nulpunt meten",
        ["Der Controller hat sich bewegt – bitte flach hinlegen und erneut versuchen."] = "De controller heeft bewogen – leg hem plat neer en probeer opnieuw.",
        ["Nullpunkt gemessen ✓"] = "Nulpunt gemeten ✓",
        ["2  Wann zielt der Gyro?"] = "2  Wanneer richt de gyro?",
        ["Nur per Taste"] = "Alleen per knop",
        ["Beim Zielen (ZL/LT)"] = "Bij richten (ZL/LT)",
        ["„Beim Zielen“: nur solange ZL (linker Trigger) gehalten wird – wie in vielen Shootern."] =
            "„Bij richten“: alleen zolang ZL (linker trigger) is ingedrukt – zoals in veel shooters.",
        ["3  Empfindlichkeit"] = "3  Gevoeligheid",
        ["Voller Ausschlag ab"] = "Volledige uitslag vanaf",
        ["Kleinerer Wert bei „Voller Ausschlag ab“ = empfindlicher. „Mindestausschlag“ überwindet die Totzone des Spiels."] =
            "Kleinere waarde bij „Volledige uitslag vanaf“ = gevoeliger. „Minimale uitslag“ overwint de dode zone van de game.",
        ["Mitte"] = "Midden",
        ["Vorschau: Fadenkreuz folgt dem Controller (unabhängig von Schritt 2)."] = "Voorbeeld: het vizier volgt de controller (onafhankelijk van stap 2).",
        ["Keine Bewegungsdaten"] = "Geen bewegingsgegevens",
        ["Controller gekoppelt"] = "Controller gekoppeld",
        ["Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive: SYNC-Taste drücken, bis die Lichter laufen.\n" +
         "Wii-Fernbedienung: Batteriefach öffnen und die rote SYNC-Taste drücken.\n" +
         "Wii U Pro Controller: die SYNC-Taste auf der Unterseite drücken.\n" +
         "Danach verbindet sich der Controller künftig per Tastendruck."] =
            "Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive: druk op de SYNC-knop tot de lampjes lopen.\n" +
            "Wii-afstandsbediening: open het batterijvak en druk op de rode SYNC-knop.\n" +
            "Wii U Pro Controller: druk op de SYNC-knop aan de onderkant.\n" +
            "Daarna verbindt de controller met een knopdruk.",
        ["Suche … SYNC-Taste drücken (Xbox: Kopplungstaste oben halten, PlayStation: PS + Teilen/Create halten)."] =
            "Zoeken … druk op de SYNC-knop (Xbox: houd de koppelknop bovenop ingedrukt; PlayStation: houd PS + Share/Create ingedrukt).",
        ["Kein Controller im Kopplungsmodus gefunden. SYNC-Taste drücken und erneut versuchen."] =
            "Geen controller in koppelmodus gevonden. Druk op SYNC en probeer opnieuw.",
        ["Darstellung:"] = "Weergave:",
        ["Dunkel"] = "Donker",
        ["Hell"] = "Licht",
        ["Wie Windows"] = "Zoals Windows",
        ["Mica-Effekt in der Titelleiste (ab Windows 11)"] = "Mica-effect in de titelbalk (vanaf Windows 11)",

        // ---------- Fehlerfälle und Hinweise ----------
        ["Bluetooth ist ausgeschaltet."] = "Bluetooth is uitgeschakeld.",
        ["Dieser Bluetooth-Adapter unterstützt kein Bluetooth LE."] = "Deze Bluetooth-adapter ondersteunt geen Bluetooth LE.",
        ["Bluetooth-Suche konnte nicht starten."] = "Bluetooth-zoeken kon niet starten.",
        ["Bluetooth in den Windows-Einstellungen einschalten."] = "Schakel Bluetooth in bij de Windows-instellingen.",
        ["Controller per USB funktionieren weiterhin."] = "Controllers via USB blijven werken.",
        ["Für Switch-2-Controller wird ein Adapter mit Bluetooth 4.0 oder neuer gebraucht."] = "Voor Switch 2-controllers is een adapter met Bluetooth 4.0 of nieuwer nodig.",
        ["Andere Controller und USB funktionieren weiterhin."] = "Andere controllers en USB blijven werken.",
        ["Bluetooth-Adapter (z. B. USB-Stick) einstecken bzw. Bluetooth in Windows aktivieren."] =
            "Sluit een Bluetooth-adapter aan (bijv. een USB-dongle) of activeer Bluetooth in Windows.",
        ["Bluetooth ist bereit – Controller können verbunden werden."] = "Bluetooth is gereed – controllers kunnen worden verbonden.",
        ["Bluetooth-Einstellungen öffnen"] = "Bluetooth-instellingen openen",
        ["ViGEmBus-Treiber fehlt – ohne ihn kann kein virtueller Controller erzeugt werden."] =
            "ViGEmBus-stuurprogramma ontbreekt – zonder kan geen virtuele controller worden gemaakt.",
        ["Bitte das Setup erneut ausführen."] = "Voer de installatie opnieuw uit.",
        ["Das Programm schließen oder in Steam die Nintendo-Unterstützung abschalten."] =
            "Sluit dat programma of schakel de Nintendo-ondersteuning in Steam uit.",
        ["Erst einen anderen trennen."] = "Verbreek eerst een andere.",
        ["Tipp: Bluetooth-Stick per Verlängerung näher an den Controller, weg von USB-3-Anschlüssen und Funkkopfhörern."] =
            "Tip: breng de Bluetooth-dongle met een verlengkabel dichter bij de controller, weg van USB 3-poorten en draadloze headsets.",
        ["Controller mit dem PC gekoppelt – ab jetzt reicht ein Tastendruck."] = "Controller gekoppeld aan de pc – voortaan volstaat een knopdruk.",
        ["Hinweis: Um ihn wieder an der Switch 2 zu nutzen, dort einmal kurz SYNC drücken."] =
            "Let op: om hem weer op de Switch 2 te gebruiken, druk daar eenmaal kort op SYNC.",
        ["Dieser Bluetooth-Adapter unterstützt kein Bluetooth LE"] = "Deze Bluetooth-adapter ondersteunt geen Bluetooth LE",
        ["Erst IR-Kamera bzw. Ring-Con ausschalten (sie nutzen denselben Zusatzprozessor wie der NFC-Leser)."] =
            "Schakel eerst de IR-camera of de Ring-Con uit (ze gebruiken dezelfde coprocessor als de NFC-lezer).",
        ["Erst die IR-Kamera schließen (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "Sluit eerst de IR-camera (Ring-Con en IR-camera gebruiken dezelfde coprocessor).",
        ["Erst den Ring-Con ausschalten (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "Schakel eerst de Ring-Con uit (Ring-Con en IR-camera gebruiken dezelfde coprocessor).",
        ["amiibo zu früh entfernt"] = "amiibo te vroeg weggehaald",
        ["MCU startet nicht"] = "de coprocessor start niet",
        ["NFC-Modus nicht aktiv"] = "NFC-modus niet actief",
        ["Kopplung fehlgeschlagen – Details im Protokoll."] = "Koppelen mislukt – details in het logboek.",

        // ---------- Kopplungsdaten (Switch-SD-Karte, anderer PC) ----------
        ["Kopplungsdaten"] = "Koppelgegevens",
        ["Kopplungen übernehmen oder weitergeben"] = "Koppelingen overnemen of delen",
        ["Kopplungsdaten von der Switch übernehmen"] = "Koppelgegevens van de Switch overnemen",
        ["Von der Switch-SD-Karte (Bluepick_RCM/hekate) oder von einem anderen PC übernehmen, oder für einen anderen PC exportieren."] =
            "Overnemen van de SD-kaart van de Switch (Bluepick_RCM/hekate) of van een andere pc, of exporteren voor een andere pc.",
        ["Bei Switch-SD-Karte nachfragen"] = "Vragen bij een SD-kaart van de Switch",
        ["Steckt eine SD-Karte der Switch im PC (Kartenleser oder hekate „USB Tools“), bietet N-Connect die Übernahme an. Die Karte wird nur gelesen."] =
            "Zit er een SD-kaart van de Switch in de pc (kaartlezer of hekate „USB Tools“), dan biedt N-Connect de overname aan. De kaart wordt alleen gelezen.",
        ["Switch-SD-Karte erkannt"] = "SD-kaart van de Switch herkend",
        ["Kopplungsdaten der Controller gefunden – klicken, um sie anzusehen und zu übernehmen."] =
            "Koppelgegevens van controllers gevonden – klik om ze te bekijken en over te nemen.",
        ["Klicken, um Kopplungsdaten der Controller zu übernehmen."] = "Klik om de koppelgegevens van controllers over te nemen.",
        ["Controller-Kopplungen von der Switch-SD-Karte oder von einem anderen PC übernehmen – oder für einen anderen PC exportieren. Es werden nur Einstellungen von N-Connect geändert; Windows und der Bluetooth-Adapter bleiben unverändert."] =
            "Neem controller-koppelingen over van de SD-kaart van de Switch of van een andere pc – of exporteer ze voor een andere pc. Alleen instellingen van N-Connect worden gewijzigd; Windows en de Bluetooth-adapter blijven onveranderd.",
        ["Spieler-Reihenfolge – Spieler 1 ist für Windows, Steam und Spiele der erste Controller. Mit ‹ › umsortieren."] =
            "Spelervolgorde – speler 1 is voor Windows, Steam en games de eerste controller. Herschik met ‹ ›.",
        ["Von der Switch-SD-Karte"] = "Van de SD-kaart van de Switch",
        ["Mit Bluepick_RCM oder hekate erstellte Kopplungsdaten (switchroot/joycon_mac.ini)"] =
            "Koppelgegevens gemaakt met Bluepick_RCM of hekate (switchroot/joycon_mac.ini)",
        ["Einlesen …"] = "Inlezen …",
        ["Von einem anderen PC"] = "Van een andere pc",
        ["Mit N-Connect exportierte Datei (*.ncpair)"] = "Door N-Connect geëxporteerd bestand (*.ncpair)",
        ["Datei öffnen …"] = "Bestand openen …",
        ["Inhalt"] = "Inhoud",
        ["Weitergeben und sichern"] = "Delen en beveiligen",
        ["Für einen anderen PC exportieren"] = "Exporteren voor een andere pc",
        ["Bekannte Controller und Einstellungen je Controller, optional mit Passwort"] =
            "Bekende controllers en instellingen per controller, eventueel met wachtwoord",
        ["Sicherung wiederherstellen"] = "Back-up terugzetten",
        ["Vor jedem „Übernehmen“ wird automatisch eine Sicherung angelegt"] = "Voor elke „Toepassen“ wordt automatisch een back-up gemaakt",
        ["Wiederherstellen …"] = "Terugzetten …",
        ["Bluetooth-Adapter dieses PCs"] = "Bluetooth-adapter van deze pc",
        ["wird ermittelt …"] = "wordt bepaald …",
        ["nicht gefunden"] = "niet gevonden",
        ["Quelle wählen: Switch-SD-Karte (mit Bluepick_RCM oder hekate erstellte Kopplungsdaten) oder eine Datei von einem anderen PC."] =
            "Kies een bron: SD-kaart van de Switch (koppelgegevens gemaakt met Bluepick_RCM of hekate) of een bestand van een andere pc.",
        ["Keine Switch-SD-Karte gefunden. SD-Karte in den Kartenleser stecken oder die Switch per hekate („USB Tools“ → „SD Card“) als Laufwerk verbinden.\n\nOrdner selbst auswählen?"] =
            "Geen SD-kaart van de Switch gevonden. Plaats de SD-kaart in een kaartlezer of verbind de Switch als schijf via hekate („USB Tools“ → „SD Card“).\n\nZelf een map kiezen?",
        ["Stammordner der Switch-SD-Karte wählen"] = "Kies de hoofdmap van de SD-kaart van de Switch",
        ["Switch-SD-Karte:"] = "SD-kaart van de Switch:",
        ["Auf der Karte liegen keine Kopplungsdaten (switchroot/joycon_mac.ini)."] = "De kaart bevat geen koppelgegevens (switchroot/joycon_mac.ini).",
        ["So erstellst du sie: Joy-Con an die Switch stecken, Bluepick_RCM starten und „Dump Joy-Con BT pairing → SD“ (oder FULL AUTO) wählen. Alternativ in hekate: Nyx → Konsole → „Dump Joy-Con BT“."] =
            "Zo maak je ze: sluit de Joy-Con aan op de Switch, start Bluepick_RCM en kies „Dump Joy-Con BT pairing → SD“ (of FULL AUTO). Anders in hekate: Nyx → Console → „Dump Joy-Con BT“.",
        ["Gefunden wurde eine Bluepick-Sicherung des Bluetooth-Speichers (8000000000000050.bin). Sie ist ein Switch-Speicherabbild und kann hier nicht ausgewertet werden."] =
            "Er is een Bluepick-back-up van het Bluetooth-geheugen gevonden (8000000000000050.bin). Dat is een geheugenafbeelding van de Switch en kan hier niet worden uitgelezen.",
        ["Bluetooth-Adresse der Switch:"] = "Bluetooth-adres van de Switch:",
        ["Gefundene Controller:"] = "Gevonden controllers:",
        ["mit der Switch gekoppelt"] = "gekoppeld aan de Switch",
        ["zuletzt mit einem anderen Gerät gekoppelt (nicht der Switch)"] = "laatst gekoppeld aan een ander apparaat (niet de Switch)",
        ["Joy-Con (L)"] = "Joy-Con (L)",
        ["Joy-Con (R)"] = "Joy-Con (R)",
        ["HORI-Controller (links)"] = "HORI-controller (links)",
        ["HORI-Controller (rechts)"] = "HORI-controller (rechts)",
        ["Hinweis: Pro Controller stehen nur im Bluetooth-Speicher der Switch (8000000000000050.bin); dieses Speicherabbild kann N-Connect nicht auswerten."] =
            "Let op: Pro Controllers staan alleen in het Bluetooth-geheugen van de Switch (8000000000000050.bin); N-Connect kan deze geheugenafbeelding niet uitlezen.",
        ["Was diese Daten können – und was nicht:"] = "Wat deze gegevens kunnen – en wat niet:",
        ["Die Daten zeigen, welche Controller mit deiner Switch gekoppelt sind und an welche Bluetooth-Adresse sie gebunden sind."] =
            "De gegevens tonen welke controllers aan je Switch gekoppeld zijn en aan welk Bluetooth-adres ze gebonden zijn.",
        ["Ein Switch-1-Controller verbindet sich auf Tastendruck nur mit dem Gerät, dessen Adresse er gespeichert hat – hier mit der Switch. Der Bluetooth-Adapter des PCs hat eine andere Adresse, deshalb kann Windows diese Kopplung nicht einfach weiterverwenden."] =
            "Een Switch 1-controller verbindt met een knopdruk alleen met het apparaat waarvan hij het adres heeft opgeslagen – hier de Switch. De Bluetooth-adapter van de pc heeft een ander adres, dus Windows kan deze koppeling niet zomaar hergebruiken.",
        ["Die Adresse des PC-Adapters zu ändern, unterstützt N-Connect bewusst nicht (herstellerabhängig, riskant und nicht vorgesehen)."] =
            "N-Connect ondersteunt bewust geen adreswijziging van de pc-adapter (fabrikantafhankelijk, riskant en niet voorzien).",
        ["Windows bietet keinen offiziellen Weg, fremde Kopplungsschlüssel einzutragen: Sie liegen in einem Teil der Registrierung, auf den nur das System zugreifen darf. N-Connect ändert dort nichts."] =
            "Windows biedt geen officiële manier om externe koppelsleutels toe te voegen: ze staan in een deel van het register dat alleen voor het systeem toegankelijk is. N-Connect wijzigt daar niets.",
        ["So klappt der Wechsel am einfachsten: am PC den Controller einmal per SYNC-Taste in den Windows-Bluetooth-Einstellungen koppeln. Zurück an der Switch die Joy-Con an die Konsole stecken bzw. den Pro Controller per USB-Kabel anschließen – dann sind sie ohne Menü wieder mit der Switch gekoppelt."] =
            "Zo werkt wisselen het makkelijkst: koppel de controller op de pc eenmalig met de SYNC-knop in de Windows-Bluetooth-instellingen. Terug op de Switch: plaats de Joy-Con op de console of sluit de Pro Controller aan met een usb-kabel – dan zijn ze zonder menu weer gekoppeld.",
        ["„Übernehmen“ merkt sich diese Controller in N-Connect (Liste bekannter Controller, Zuordnung zur Switch). Kopplungsschlüssel werden nicht gespeichert."] =
            "„Toepassen“ onthoudt deze controllers in N-Connect (lijst met bekende controllers, toewijzing aan de Switch). Koppelsleutels worden niet opgeslagen.",
        ["N-Connect-Kopplungsdaten"] = "N-Connect-koppelgegevens",
        ["Kopplungsdaten von einem anderen PC öffnen"] = "Koppelgegevens van een andere pc openen",
        ["Die Datei ist zu groß."] = "Het bestand is te groot.",
        ["Keine Kopplungsdaten-Datei."] = "Geen koppelgegevensbestand.",
        ["Die Datei stammt von einer neueren N-Connect-Version."] = "Het bestand komt van een nieuwere N-Connect-versie.",
        ["Die Datei ist mit einem Passwort geschützt."] = "Het bestand is met een wachtwoord beveiligd.",
        ["Falsches Passwort oder die Datei wurde verändert."] = "Onjuist wachtwoord of het bestand is gewijzigd.",
        ["Die Datei ist beschädigt."] = "Het bestand is beschadigd.",
        ["Datei von:"] = "Bestand van:",
        ["Bluetooth-Adapter dort:"] = "Bluetooth-adapter daar:",
        ["Bluetooth-Adapter hier:"] = "Bluetooth-adapter hier:",
        ["gekoppelt mit der Switch"] = "gekoppeld aan de Switch",
        ["gekoppelt mit dem anderen PC"] = "gekoppeld aan de andere pc",
        ["Weitere Einstellungen je Controller:"] = "Verdere instellingen per controller:",
        ["Was du erwarten kannst:"] = "Wat je kunt verwachten:",
        ["Gleiche Adapter-Adresse (z. B. derselbe USB-Bluetooth-Stick umgesteckt): Switch-2-Controller verbinden sich hier auf Tastendruck wie am anderen PC."] =
            "Zelfde adapteradres (bijv. dezelfde Bluetooth-usb-dongle overgezet): Switch 2-controllers verbinden hier met een knopdruk zoals op de andere pc.",
        ["Switch-1-Controller (Pro Controller, Joy-Con) brauchen zusätzlich die Kopplung in Windows. Die kann N-Connect nicht übertragen – einmal per SYNC-Taste koppeln."] =
            "Switch 1-controllers (Pro Controller, Joy-Con) hebben daarnaast de koppeling in Windows nodig. Die kan N-Connect niet overdragen – koppel eenmaal met de SYNC-knop.",
        ["Anderer Bluetooth-Adapter: Controller verbinden sich auf Tastendruck nur mit dem Gerät, mit dem sie zuletzt gekoppelt wurden. Hier einmal SYNC drücken – danach verbinden sie sich mit diesem PC (am anderen PC dann wieder per SYNC)."] =
            "Andere Bluetooth-adapter: controllers verbinden met een knopdruk alleen met het apparaat waarmee ze als laatste gekoppeld zijn. Druk hier eenmaal op SYNC – daarna verbinden ze met deze pc (op de andere pc weer via SYNC).",
        ["Tipp: Wer denselben USB-Bluetooth-Stick zwischen den PCs umsteckt, nimmt die Adresse mit – Switch-2-Controller verbinden sich dann an beiden PCs ohne SYNC."] =
            "Tip: wie dezelfde Bluetooth-usb-dongle tussen pc's verplaatst, neemt het adres mee – Switch 2-controllers verbinden dan op beide pc's zonder SYNC.",
        ["Übernommen werden die Einstellungen je Controller (Joy-Con einzeln/hochkant, Gyro-Kalibrierung) und die Liste bekannter Controller."] =
            "Overgenomen worden de instellingen per controller (Joy-Con los/verticaal, gyro-kalibratie) en de lijst met bekende controllers.",
        ["Die Datei enthält Kopplungsschlüssel. Windows bietet keinen offiziellen Weg, sie einzutragen – N-Connect übernimmt sie deshalb nicht."] =
            "Het bestand bevat koppelsleutels. Windows biedt geen officiële manier om ze toe te voegen – N-Connect neemt ze daarom niet over.",
        ["„Übernehmen“ ergänzt die Controller-Listen und Einstellungen von N-Connect (nichts wird gelöscht). Vorher wird eine Sicherung angelegt."] =
            "„Toepassen“ vult de controllerlijsten en instellingen van N-Connect aan (niets wordt verwijderd). Vooraf wordt een back-up gemaakt.",
        ["Kopplungsdaten in N-Connect übernehmen? Vorher wird eine Sicherung der Einstellungen angelegt."] =
            "Koppelgegevens in N-Connect overnemen? Vooraf wordt een back-up van de instellingen gemaakt.",
        ["Nichts zu ändern – diese Daten sind schon übernommen."] = "Niets te wijzigen – deze gegevens zijn al overgenomen.",
        ["Übernommen. Die Sicherung lässt sich hier über „Sicherung wiederherstellen“ zurückholen."] =
            "Overgenomen. De back-up is hier terug te halen via „Back-up terugzetten“.",
        ["Sicherung der Einstellungen"] = "Back-up van de instellingen",
        ["Die Sicherung ist beschädigt und wurde nicht übernommen."] = "De back-up is beschadigd en niet overgenomen.",
        ["Alle Einstellungen durch diese Sicherung ersetzen?"] = "Alle instellingen vervangen door deze back-up?",
        ["Sicherung wiederhergestellt."] = "Back-up teruggezet.",
        ["Kopplungsdaten für einen anderen PC speichern"] = "Koppelgegevens opslaan voor een andere pc",
        ["Gespeichert. Die Datei am anderen PC in N-Connect unter „Joy-Con & Wii“ → „Kopplungsdaten“ → „Von einem anderen PC“ öffnen."] =
            "Opgeslagen. Open het bestand op de andere pc in N-Connect onder „Joy-Con en Wii“ → „Koppelgegevens“ → „Van een andere pc“.",
        ["Kopplungsdaten exportieren"] = "Koppelgegevens exporteren",
        ["Passwort eingeben"] = "Wachtwoord invoeren",
        ["Passwort (optional). Ohne Passwort steht der Inhalt lesbar in der Datei. Mit Kopplungsschlüsseln ist ein Passwort Pflicht."] =
            "Wachtwoord (optioneel). Zonder wachtwoord is de inhoud leesbaar in het bestand. Met koppelsleutels is een wachtwoord verplicht.",
        ["Passwort"] = "Wachtwoord",
        ["Passwort wiederholen"] = "Wachtwoord herhalen",
        ["Kopplungsschlüssel der Switch-Controller mitnehmen"] = "Koppelsleutels van de Switch-controllers meenemen",
        ["Kopplungsschlüssel mitnehmen (erst Switch-SD-Karte einlesen)"] = "Koppelsleutels meenemen (lees eerst een SD-kaart van de Switch in)",
        ["Die Passwörter stimmen nicht überein."] = "De wachtwoorden komen niet overeen.",
        ["Mit Schlüsseln: Passwort mit mindestens 8 Zeichen."] = "Met sleutels: wachtwoord van minstens 8 tekens.",
        ["Mindestens 8 Zeichen."] = "Minstens 8 tekens.",
        ["Ohne Passwort."] = "Zonder wachtwoord.",
    };

    /// <summary>Meldungen mit Platzhaltern (Niederländisch).</summary>
    private static readonly (Regex Pattern, Func<Match, string> Replace)[] PatternsNl =
    [
        (Re(@"^Allgemeiner Wert \((?<v>.+)\) – Regler verschieben für einen eigenen$"), m => $"Algemene waarde ({m.Groups["v"]}) – schuif de regelaar voor een eigen waarde"),
        (Re(@"^Eigener Wert · allgemein: (?<v>.+)$"), m => $"Eigen waarde · algemeen: {m.Groups["v"]}"),
        (Re(@"^Spieler (?<n>\d+)  ·  (?<k>.+?)(?<rest>(  ·  .*)?)$"), m => $"Speler {m.Groups["n"]}  ·  {N(m, "k")}{T(m.Groups["rest"].Value)}"),
        (Re(@"^  ·  Gyro-Maus(?<r>.*)$"), m => "  ·  Gyro-muis" + T(m.Groups["r"].Value)),
        (Re(@"^  ·  Gyro-Stick$"), _ => "  ·  Gyro-stick"),
        (Re(@"^Spieler (?<n>\d+) · (?<k>.+?) (?<b>\d+ %.*)?$"), m => $"Speler {m.Groups["n"]} · {N(m, "k")} {m.Groups["b"]}"),
        (Re(@"^(?<k>.+) verbunden \(Spieler (?<n>\d+)\)$"), m => $"{N(m, "k")} verbonden (speler {m.Groups["n"]})"),
        (Re(@"^Spieler (?<n>\d+) – tauschen mit (?<k>.+)$"), m => $"Speler {m.Groups["n"]} – wisselen met {N(m, "k")}"),
        (Re(@"^Spieler (?<n>\d+) – frei$"), m => $"Speler {m.Groups["n"]} – vrij"),
        (Re(@"^Spieler (?<n>\d+)$"), m => $"Speler {m.Groups["n"]}"),
        (Re(@"^Xbox 360 · Platz (?<n>\d+)$"), m => $"Xbox 360 · plek {m.Groups["n"]}"),
        (Re(@"^noch (?<n>\d+) s$"), m => $"nog {m.Groups["n"]} s"),
        (Re(@"^Fertig – (?<n>\d+) Controller verbunden$"), m => $"Klaar – {m.Groups["n"]} controller(s) verbonden"),
        (Re(@"^✓ (?<k>.+) verbunden – Spieler (?<n>\d+)$"), m => $"✓ {N(m, "k")} verbonden – speler {m.Groups["n"]}"),
        (Re(@"^Spieler (?<n>\d+)  ·  (?<v>.+)$"), m => $"Speler {m.Groups["n"]}  ·  {m.Groups["v"]}"),
        (Re(@"^Gekoppelt: (?<k>.+) – verbindet gleich …$"), m => $"Gekoppeld: {m.Groups["k"]} – verbindt zo …"),
        (Re(@"^Ins Spiel wechseln … (?<n>\d+)$"), m => $"Wissel naar de game … {m.Groups["n"]}"),
        (Re(@"^(?<k>.+) ist jetzt Spieler (?<n>\d+)$"), m => $"{N(m, "k")} is nu speler {m.Groups["n"]}"),
        (Re(@"^Spieler (?<a>\d+) und (?<b>\d+) getauscht$"), m => $"Spelers {m.Groups["a"]} en {m.Groups["b"]} gewisseld"),
        (Re(@"^Name für (?<k>.+) \(leer = Standardname\):$"), m => $"Naam voor {N(m, "k")} (leeg = standaardnaam):"),
        (Re(@"^(?<k>.+) \(Joy-Con-Paar\)$"), m => $"{m.Groups["k"]} (Joy-Con-paar)"),
        (Re(@"^Joy-Con zusammengefasst \(Spieler (?<n>\d+)\)$"), m => $"Joy-Con gecombineerd (speler {m.Groups["n"]})"),
        (Re(@"^Joy-Con getrennt – (?<k>.+) ist jetzt Spieler (?<n>\d+)$"), m => $"Joy-Con gescheiden – {N(m, "k")} is nu speler {m.Groups["n"]}"),
        (Re(@"^Spieler (?<n>\d+): Akku (?<k>.+) fast leer \((?<p>\d+) %\) – bitte aufladen$"),
            m => $"Speler {m.Groups["n"]}: accu van {N(m, "k")} bijna leeg ({m.Groups["p"]} %) – opladen"),
        (Re(@"^Spieler (?<n>\d+): nach (?<m>\d+) min ohne Eingabe getrennt$"),
            m => $"Speler {m.Groups["n"]}: verbroken na {m.Groups["m"]} min zonder invoer"),
        (Re(@"^Profil „(?<p>.+)“ aktiv$"), m => $"Profiel „{ProfileName(m.Groups["p"].Value)}“ actief"),
        (Re(@"^Profil: (?<p>.+)$"), m => $"Profiel: {ProfileName(m.Groups["p"].Value)}"),
        (Re(@"^Profil „(?<p>.+)“ löschen\?$"), m => $"Profiel „{m.Groups["p"]}“ verwijderen?"),
        (Re(@"^Profil „(?<p>.+)“ importiert(?<r>.*)$"), m => $"Profiel „{m.Groups["p"]}“ geïmporteerd" + m.Groups["r"].Value.Replace("aktiv bei:", "actief bij:")),
        (Re(@"^⬇ Neue Version (?<v>.+) herunterladen …$"), m => $"⬇ Nieuwe versie {m.Groups["v"]} downloaden …"),
        (Re(@"^Version (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Herunterladen\.$"),
            m => $"Versie {m.Groups["v"]} is verschenen (geïnstalleerd: {m.Groups["i"]}). Klik om te downloaden."),
        (Re(@"^Version (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Installieren\.$"),
            m => $"Versie {m.Groups["v"]} is verschenen (geïnstalleerd: {m.Groups["i"]}). Klik om te installeren."),
        (Re(@"^⬇ Auf Version (?<v>.+) aktualisieren …$"), m => $"⬇ Bijwerken naar versie {m.Groups["v"]} …"),
        (Re(@"^Lade Version (?<v>.+) herunter …$"), m => $"Versie {m.Groups["v"]} downloaden …"),
        (Re(@"^HidHide (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Installieren\.$"),
            m => $"HidHide {m.Groups["v"]} is verschenen (geïnstalleerd: {m.Groups["i"]}). Klik om te installeren."),
        (Re(@"^Lade HidHide (?<v>.+) herunter …$"), m => $"HidHide {m.Groups["v"]} downloaden …"),
        (Re(@"^(?<t>.+) · (?<r>\d+) Berichte/s$"), m => $"{T(m.Groups["t"].Value)} · {m.Groups["r"]} rapporten/s"),
        (Re(@"^(?<p>\d+ %)(?<v>  \(.*\))?  ⚡ lädt$"), m => $"{m.Groups["p"]}{m.Groups["v"]}  ⚡ aan het laden"),
        (Re(@"^Speichern fehlgeschlagen: (?<e>.*)$"), m => $"Opslaan mislukt: {m.Groups["e"]}"),
        (Re(@"^Lesen fehlgeschlagen: (?<e>.*)$"), m => $"Lezen mislukt: {m.Groups["e"]}"),
        (Re(@"^amiibo konnte nicht gelesen werden: (?<e>.*)$"), m => $"amiibo kon niet worden gelezen: {T(m.Groups["e"].Value)}"),
        (Re(@"^Gekoppelt: (?<k>.+)$"), m => $"Gekoppeld: {m.Groups["k"]}"),
        (Re(@"^Gefunden: (?<k>.+) – kopple …$"), m => $"Gevonden: {m.Groups["k"]} – koppelen …"),
        (Re(@"^amiibo erkannt \((?<u>.+)\) – lese …$"), m => $"amiibo herkend ({m.Groups["u"]}) – lezen …"),
        (Re(@"^(?<n>\d+) Minuten$"), m => $"{m.Groups["n"]} minuten"),
        (Re(@"^✓ (?<n>\d+) Schritte, Dauer (?<ms>\d+) ms$"), m => $"✓ {m.Groups["n"]} stappen, {m.Groups["ms"]} ms totaal"),
        (Re(@"^Controller-Taste „(?<b>.+)“:\nJetzt die gewünschte Taste oder Tastenkombination drücken\.$"),
            m => $"Controllerknop „{T(m.Groups["b"].Value)}“:\nDruk nu de gewenste toets of toetscombinatie in."),
        (Re(@"^Solange „(?<b>.+)“ gehalten wird, wird diese Taste schnell wiederholt gedrückt\n\(Geschwindigkeit unter 5\. „Turbo“\):$"),
            m => $"Zolang „{T(m.Groups["b"].Value)}“ is ingedrukt, wordt deze knop snel herhaald\n(snelheid onder 5. „Turbo“):"),
        (Re(@"^Ring-Con: (?<e>.*)$"), m => $"Ring-Con: {T(m.Groups["e"].Value)}"),
        (Re(@"^⌨  Taste: (?<k>.+)$"), m => $"⌨  Toets: {m.Groups["k"]}"),
        (Re(@"^🔁  Turbo: Taste (?<k>.+)$"), m => $"🔁  Turbo: toets {m.Groups["k"]}"),
        (Re(@"^🔁  Turbo: (?<k>.+)$"), m => $"🔁  Turbo: {T(m.Groups["k"].Value)}"),
        (Re(@"^⏯  Makro: (?<k>.+)$"), m => $"⏯  Macro: {m.Groups["k"]}"),
        (Re(@"^Tastatur: (?<k>.+)$"), m => $"Toetsenbord: {m.Groups["k"]}"),
        (Re(@"^Gamepad: (?<k>.+)$"), m => $"Gamepad: {m.Groups["k"]}"),
        (Re(@"^(?<k>.+)  \(verbunden\)$"), m => $"{N(m, "k")}  (verbonden)"),
        (Re(@"^Bluetooth nicht verfügbar: (?<e>.*)$"), m => $"Bluetooth niet beschikbaar: {m.Groups["e"]}"),
        (Re(@"^(?<k>.+) per USB ist von einem anderen Programm belegt \(z\. B\. Steam\)\.$"),
            m => $"{N(m, "k")} via USB is in gebruik door een ander programma (bijv. Steam)."),
        (Re(@"^Schon (?<n>\d+) Controller verbunden – (?<k>.+) wird nicht verwendet\.$"),
            m => $"Al {m.Groups["n"]} controllers verbonden – {N(m, "k")} wordt niet gebruikt."),
        (Re(@"^(?<k>.+): schwache Bluetooth-Verbindung \((?<r>\d+) statt 33–60 Berichte/s\)\.$"),
            m => $"{N(m, "k")}: zwakke Bluetooth-verbinding ({m.Groups["r"]} in plaats van 33–60 rapporten/s)."),
        (Re(@"^(?<k>.+) getrennt$"), m => $"{N(m, "k")} verbroken"),
    ];
}
