using System.Text.RegularExpressions;

namespace Switch2Pro.Bridge;

/// <summary>Feste Texte Deutsch → Polnisch. Schlüssel bleiben die deutschen Originaltexte.</summary>
internal static partial class Tr
{
    private static readonly Dictionary<string, string> TextsPl = new(StringComparer.Ordinal)
    {
        // ---------- Fenster, Reiter, Abschnitte ----------
        ["Controller"] = "Kontrolery",
        // ---------- Desktop-Modus, Testseite, Vorlagen, Diagnose ----------
        ["Einblendung beim Verbinden"] = "Powiadomienie przy połączeniu",
        ["Kurze Anzeige am Bildschirmrand mit Spieler, Controller und Akkustand."] = "Krótki komunikat przy krawędzi ekranu z graczem, kontrolerem i baterią.",
        ["Desktop-Modus"] = "Tryb pulpitu",
        ["Läuft kein Spiel, steuert der Controller Windows: linker Stick = Maus, rechter Stick = Scrollen, A = Klick, B = Rechtsklick, X = Taskansicht, Y = Bildschirmtastatur, Steuerkreuz = Pfeiltasten, LB/RB = zurück/vor, Start = Enter, Back = Esc, HOME = Startmenü. Back + Start 1 Sekunde halten pausiert ihn. In Vollbildspielen und Programmen mit eigenem Profil ist er automatisch aus."] = "Gdy nie działa żadna gra, kontroler steruje systemem Windows: lewa gałka = mysz, prawa gałka = przewijanie, A = klik, B = prawy klik, X = widok zadań, Y = klawiatura ekranowa, krzyżak = strzałki, LB/RB = wstecz/dalej, Start = Enter, Back = Esc, HOME = menu Start. Przytrzymaj Back + Start przez 1 sekundę, aby wstrzymać. W grach pełnoekranowych i programach z własnym profilem wyłącza się automatycznie.",
        ["Zeigergeschwindigkeit"] = "Szybkość wskaźnika",
        ["RT gedrückt halten macht den Zeiger langsam und genau."] = "Przytrzymaj RT, aby wskaźnik był wolny i precyzyjny.",
        ["Desktop-Steuerung pausiert – Back + Start halten zum Fortsetzen."] = "Sterowanie pulpitem wstrzymane – przytrzymaj Back + Start, aby wznowić.",
        ["Desktop-Steuerung aktiv – der Controller steuert Maus und Tastatur."] = "Sterowanie pulpitem aktywne – kontroler steruje myszą i klawiaturą.",
        ["Test"] = "Test",
        ["Trigger"] = "Spusty",
        ["Bewegung"] = "Ruch",
        ["Rundheit"] = "Okrągłość",
        ["Berichte/s"] = "raportów/s",
        ["Vibration testen"] = "Testuj wibracje",
        ["Kreis zurücksetzen"] = "Zresetuj okrąg",
        ["Controller testen"] = "Testuj kontroler",
        ["Sticks einmal langsam ganz im Kreis drehen – die Linie zeigt, wie rund sie laufen. Gedrückte Tasten erscheinen unten in der Anzeige."] = "Obróć każdą gałkę raz powoli po pełnym okręgu – linia pokazuje, jak okrągło się porusza. Naciśnięte przyciski widać na dole.",
        ["🔇  Ton aus/an"] = "🔇  Wycisz/włącz dźwięk",
        ["⏭  Nächster Titel"] = "⏭  Następny utwór",
        ["⏮  Vorheriger Titel"] = "⏮  Poprzedni utwór",
        ["🎙  Mikrofon stumm (Win+Alt+K)"] = "🎙  Wycisz mikrofon (Win+Alt+K)",
        ["🎙  Discord: Mikrofon stumm (Strg+Umschalt+M)"] = "🎙  Discord: wycisz mikrofon (Ctrl+Shift+M)",
        ["🎧  Discord: Ton aus (Strg+Umschalt+D)"] = "🎧  Discord: wyłącz dźwięk (Ctrl+Shift+D)",
        ["🖥  Desktop anzeigen (Win+D)"] = "🖥  Pokaż pulpit (Win+D)",
        ["🗂  Taskansicht (Win+Tab)"] = "🗂  Widok zadań (Win+Tab)",
        ["↔  Zum letzten Fenster (Alt+Tab)"] = "↔  Ostatnie okno (Alt+Tab)",
        ["Diagnose exportieren"] = "Eksportuj diagnostykę",
        ["Protokoll, Einstellungen und Systeminfos als ZIP-Datei – zum Anhängen an eine Fehlermeldung. Enthält keine Kopplungsschlüssel."] = "Dziennik, ustawienia i informacje o systemie w pliku ZIP – do dołączenia do zgłoszenia problemu. Nie zawiera kluczy parowania.",
        // ---------- Status-Kopfzeile, Ansicht ----------
        ["Farbschema"] = "Schemat kolorów",
        ["Farben für Akzente, Knöpfe, Flächen und Ränder."] = "Kolory akcentów, przycisków, powierzchni i obramowań.",
        ["bereit"] = "gotowy",
        ["nicht verfügbar"] = "niedostępny",
        ["Niedrigster Akku"] = "Najniższa bateria",
        ["lädt"] = "ładuje",
        ["gemischt"] = "mieszane",
        ["Original-Controller"] = "Oryginalne kontrolery",
        ["versteckt"] = "ukryte",
        ["sichtbar"] = "widoczne",
        ["HidHide fehlt"] = "brak HidHide",
        ["Groß"] = "Duży",
        ["Kompakt"] = "Kompaktowy",
        ["Einstellungen (optional)"] = "Ustawienia (opcjonalne)",
        ["1. Windows und Spiele sehen den Controller als …"] = "1. Windows i gry widzą kontroler jako …",
        ["2. Tasten A/B/X/Y"] = "2. Przyciski A/B/X/Y",
        ["3. Vibration, Sticks, Verbinden, Gyro-Maus"] = "3. Wibracje, gałki, łączenie, mysz żyroskopowa",
        ["4. Joy-Con"] = "4. Joy-Con",
        ["4. Joy-Con und Wii"] = "4. Joy-Con i Wii",
        ["Wii-Fernbedienung: Zeiger (Sensorleiste) steuert die Maus"] = "Pilot Wii: wskaźnik (pasek sensorów) steruje myszą",
        ["Zeiger"] = "Wskaźnik",
        ["kein Zeiger – Sensorleiste nicht im Blick"] = "brak wskaźnika – pasek sensorów poza zasięgiem",
        ["5. Zielen, Sticks, Trigger, Turbo"] = "5. Celowanie, gałki, spusty, turbo",
        ["6. Tastenbelegung und Profile  (Taste → Gamepad, Tastatur, Maus, Gyro-Maus, Shift-Ebene)"] =
            "6. Przypisanie przycisków i profile  (przycisk → gamepad, klawiatura, mysz, mysz żyroskopowa, warstwa Shift)",
        ["Xbox-360-Controller  (empfohlen – läuft mit fast allen Spielen)"] = "Kontroler Xbox 360  (zalecany – działa z niemal wszystkimi grami)",
        ["PlayStation DualShock 4  (mit Bewegungssteuerung/Gyro – für Steam && Emulatoren)"] =
            "PlayStation DualShock 4  (ze sterowaniem ruchem/żyroskopem – dla Steam i emulatorów)",
        ["Xbox-Belegung  (nach Position: untere Taste = A)"] = "Układ Xbox  (według pozycji: dolny przycisk = A)",
        ["Nintendo-Belegung  (nach Beschriftung: A bleibt A)"] = "Układ Nintendo  (według oznaczenia: A pozostaje A)",
        ["Vibration"] = "Wibracje",
        ["Stärke:"] = "Siła:",
        ["Stick-Totzone (alle Controller):"] = "Martwa strefa gałki (wszystkie kontrolery):",
        ["Beim Verbinden kurz vibrieren"] = "Krótko wibruj przy połączeniu",
        ["Meldung bei Verbinden"] = "Powiadomienie o połączeniu",
        ["Wer meldet, wenn ein Controller verbunden oder getrennt wird."] = "Wybierz, kto powiadamia o podłączeniu lub odłączeniu kontrolera.",
        ["„N-Connect“ zeigt den echten Controller-Namen und schaltet die Gerätemeldungen von Windows ab."] = "\"N-Connect\" pokazuje prawdziwą nazwę kontrolera i wyłącza powiadomienia urządzeń Windows.",
        ["N-Connect (empfohlen)"] = "N-Connect (zalecane)",
        ["N-Connect und Windows"] = "N-Connect i Windows",
        ["Keine"] = "Brak",
        ["Gekoppelte Controller per Tastendruck verbinden (ohne SYNC)"] = "Łącz sparowane kontrolery naciśnięciem przycisku (bez SYNC)",
        ["Automatisch mit Windows starten"] = "Uruchamiaj automatycznie z Windows",
        ["Gyro für Emulatoren bereitstellen (Cemuhook/DSU, Port 26760 – wirkt nach Neustart)"] =
            "Udostępniaj żyroskop emulatorom (Cemuhook/DSU, port 26760 – aktywne po restarcie)",
        ["Beim Start nach neuer Version suchen (GitHub)"] = "Szukaj nowej wersji przy starcie (GitHub)",
        ["Ohne Eingabe automatisch trennen nach:"] = "Rozłącz automatycznie bez czynności po:",
        ["Gyro-Maus-Geschwindigkeit:"] = "Prędkość myszy żyroskopowej:",
        ["Sprache / Language:"] = "Język / Language:",
        ["Automatisch (wie Windows)"] = "Automatyczny (jak Windows)",
        ["nie"] = "nigdy",
        ["Zwei Joy-Con automatisch zu einem Controller zusammenfassen"] = "Automatycznie łącz dwa Joy-Con w jeden kontroler",
        ["Gyro beim Paar vom:"] = "Żyroskop pary z:",
        ["rechter Joy-Con (wie Switch)"] = "prawy Joy-Con (jak na Switch)",
        ["linker Joy-Con"] = "lewy Joy-Con",
        ["Joy-Con 2 als Maus, wenn er auf dem Tisch liegt"] = "Joy-Con 2 jako mysz, gdy leży na stole",
        ["Mausgeschwindigkeit:"] = "Prędkość myszy:",
        ["Maus: links/rechts umkehren"] = "Mysz: odwróć lewo/prawo",
        ["Maus: hoch/runter umkehren"] = "Mysz: odwróć góra/dół",
        ["Wie an der Switch: SL + SR eine Sekunde halten löst einen Joy-Con aus dem Paar. L am linken und R am rechten einzelnen Joy-Con gleichzeitig drücken verbindet sie wieder zum Paar. Die Wahl wird je Joy-Con gemerkt (auch nach dem nächsten Verbinden). Im Mausmodus: R/L = Linksklick, ZR/ZL = Rechtsklick, Stick drücken = Mittelklick, Stick hoch/runter = Scrollen."] =
            "Jak na Switch: przytrzymanie SL + SR przez sekundę odłącza Joy-Con od pary. Jednoczesne naciśnięcie L na lewym i R na prawym pojedynczym Joy-Con łączy je z powrotem. Wybór jest zapamiętywany dla każdego Joy-Con (także przy następnym połączeniu). W trybie myszy: R/L = lewy przycisk, ZR/ZL = prawy przycisk, wciśnięcie gałki = środkowy przycisk, gałka góra/dół = przewijanie.",
        ["Gyro als rechter Stick:"] = "Żyroskop jako prawa gałka:",
        ["aus (nur per Taste „Gyro-Stick“)"] = "wyłączony (tylko przyciskiem „gałka żyroskopowa”)",
        ["immer"] = "zawsze",
        ["beim Zielen (solange ZL / linker Trigger gedrückt)"] = "przy celowaniu (dopóki ZL / lewy spust jest wciśnięty)",
        ["hoch/runter umkehren"] = "odwróć góra/dół",
        ["Empfindlichkeit:"] = "Czułość:",
        ["Mindestausschlag:"] = "Minimalne wychylenie:",
        ["Stick-Kennlinie:"] = "Charakterystyka gałki:",
        ["Turbo (pro Sekunde):"] = "Turbo (na sekundę):",
        ["Analoge Trigger (GameCube) – Totzone:"] = "Spusty analogowe (GameCube) – martwa strefa:",
        ["voll gedrückt ab:"] = "wciśnięty do końca od:",
        ["Profil:"] = "Profil:",
        ["Neu …"] = "Nowy …",
        ["Umbenennen …"] = "Zmień nazwę …",
        ["Löschen"] = "Usuń",
        ["Exportieren …"] = "Eksportuj …",
        ["Importieren …"] = "Importuj …",
        ["Aktiv bei Programm:"] = "Aktywny przy programie:",
        ["Programm wählen …"] = "Wybierz program …",
        ["Standard"] = "Domyślny",
        ["Standard gilt immer, wenn kein anderes Profil passt"] = "Domyślny obowiązuje, gdy żaden inny profil nie pasuje",
        ["z. B. Cemu.exe, Ryujinx.exe"] = "np. Cemu.exe, Ryujinx.exe",
        ["Ein eigenes Profil wird automatisch aktiv, solange eines seiner Programme im Vordergrund ist (sonst gilt „Standard“). Im Infobereich-Menü lässt sich ein Profil auch fest wählen."] =
            "Własny profil aktywuje się automatycznie, gdy jeden z jego programów jest na pierwszym planie (inaczej obowiązuje „Domyślny”). Profil można też wybrać na stałe w menu zasobnika.",
        ["Controller:"] = "Kontroler:",
        ["Eigene Stick-Totzone für diesen Controller:"] = "Własna martwa strefa gałki dla tego kontrolera:",
        ["Normale Belegung"] = "Normalne przypisanie",
        ["Shift-Ebene (gilt, solange eine Taste mit „Shift-Ebene“ gehalten wird)"] = "Warstwa Shift (obowiązuje, dopóki przycisk „warstwa Shift” jest wciśnięty)",
        ["Alles auf Standard"] = "Resetuj wszystko",
        ["Schließen"] = "Zamknij",
        ["wie normale Belegung"] = "jak normalne przypisanie",

        // ---------- Belegungsziele und Vorlagen ----------
        ["— keine Funktion —"] = "— brak funkcji —",
        ["A (Xbox) / Kreuz (PS)"] = "A (Xbox) / Krzyżyk (PS)",
        ["B (Xbox) / Kreis (PS)"] = "B (Xbox) / Kółko (PS)",
        ["X (Xbox) / Viereck (PS)"] = "X (Xbox) / Kwadrat (PS)",
        ["Y (Xbox) / Dreieck (PS)"] = "Y (Xbox) / Trójkąt (PS)",
        ["Ansicht (Back) / Share"] = "Podgląd (Back) / Share",
        ["Menü (Start) / Options"] = "Menu (Start) / Options",
        ["Xbox-Taste / PS-Taste"] = "Przycisk Xbox / przycisk PS",
        ["Linker Stick-Klick"] = "Kliknięcie lewej gałki",
        ["Rechter Stick-Klick"] = "Kliknięcie prawej gałki",
        ["Steuerkreuz hoch"] = "Krzyżak w górę",
        ["Steuerkreuz runter"] = "Krzyżak w dół",
        ["Steuerkreuz links"] = "Krzyżak w lewo",
        ["Steuerkreuz rechts"] = "Krzyżak w prawo",
        ["Touchpad-Klick (nur DualShock 4)"] = "Kliknięcie touchpada (tylko DualShock 4)",
        ["🖱  Maus: Linksklick"] = "🖱  Mysz: lewy przycisk",
        ["🖱  Maus: Rechtsklick"] = "🖱  Mysz: prawy przycisk",
        ["🖱  Maus: Mittelklick"] = "🖱  Mysz: środkowy przycisk",
        ["🎯  Gyro-Maus (solange gehalten)"] = "🎯  Mysz żyroskopowa (dopóki wciśnięte)",
        ["🎯  Gyro-Maus ein/aus"] = "🎯  Mysz żyroskopowa wł./wył.",
        ["🎯  Gyro als rechter Stick (solange gehalten)"] = "🎯  Żyroskop jako prawa gałka (dopóki wciśnięte)",
        ["🎯  Gyro als rechter Stick ein/aus"] = "🎯  Żyroskop jako prawa gałka wł./wył.",
        ["⇧  Shift-Ebene (solange gehalten)"] = "⇧  Warstwa Shift (dopóki wciśnięte)",
        ["🔁  Turbo / Dauerfeuer …"] = "🔁  Turbo / ogień ciągły …",
        ["⏯  Makro (Tastenfolge) …"] = "⏯  Makro (sekwencja przycisków) …",
        ["📷  Bildschirmfoto speichern (Win+Druck)"] = "📷  Zapisz zrzut ekranu (Win+Print)",
        ["📷  Bildschirmausschnitt (Win+Umschalt+S)"] = "📷  Fragment ekranu (Win+Shift+S)",
        ["⏺  Letzte 30 Sekunden aufnehmen (Win+Alt+G)"] = "⏺  Nagraj ostatnie 30 sekund (Win+Alt+G)",
        ["⏺  Aufnahme starten/stoppen (Win+Alt+R)"] = "⏺  Rozpocznij/zatrzymaj nagrywanie (Win+Alt+R)",
        ["🎮  Xbox Game Bar (Win+G)"] = "🎮  Xbox Game Bar (Win+G)",
        ["🔊  Lauter"] = "🔊  Głośniej",
        ["🔉  Leiser"] = "🔉  Ciszej",
        ["⏯  Wiedergabe/Pause"] = "⏯  Odtwarzaj/Pauza",
        ["⌨  Andere Taste / Tastenkombination aufnehmen …"] = "⌨  Zapisz inny klawisz / skrót klawiszowy …",

        // ---------- Tastennamen ----------
        ["+ (Plus)"] = "+ (Plus)",
        ["− (Minus)"] = "− (Minus)",
        ["Aufnahme"] = "Przechwytywanie",
        ["GL (Rücktaste links)"] = "GL (tylny przycisk lewy)",
        ["GR (Rücktaste rechts)"] = "GR (tylny przycisk prawy)",
        ["Linker Stick drücken"] = "Wciśnij lewą gałkę",
        ["Rechter Stick drücken"] = "Wciśnij prawą gałkę",
        ["Stick drücken"] = "Wciśnij gałkę",
        ["A (groß, unten)"] = "A (duży, na dole)",
        ["B (links)"] = "B (lewy)",
        ["X (rechts)"] = "X (prawy)",
        ["Y (oben)"] = "Y (górny)",
        ["L (ganz durchgedrückt)"] = "L (wciśnięty do końca)",
        ["R (ganz durchgedrückt)"] = "R (wciśnięty do końca)",
        ["untere Taste (quer)"] = "dolny przycisk (poziomo)",
        ["rechte Taste (quer)"] = "prawy przycisk (poziomo)",
        ["linke Taste (quer)"] = "lewy przycisk (poziomo)",
        ["obere Taste (quer)"] = "górny przycisk (poziomo)",
        ["1 (quer) / Classic Y"] = "1 (poziomo) / Classic Y",
        ["2 (quer) / Classic B"] = "2 (poziomo) / Classic B",
        ["B (Abzug) / Classic ZR"] = "B (spust) / Classic ZR",
        ["Kreuz (unten)"] = "Krzyżyk (dół)",
        ["Kreis (rechts)"] = "Kółko (prawo)",
        ["Viereck (links)"] = "Kwadrat (lewo)",
        ["Dreieck (oben)"] = "Trójkąt (góra)",
        ["PS-Taste"] = "Przycisk PS",
        ["Touchpad-Klick"] = "Kliknięcie touchpada",
        ["Mikro stumm"] = "Wycisz mikrofon",
        ["Fn links (Edge)"] = "Fn lewy (Edge)",
        ["Rücktaste links (Edge)"] = "Tylny przycisk lewy (Edge)",
        ["Rücktaste rechts (Edge)"] = "Tylny przycisk prawy (Edge)",
        ["L3 (Stick drücken)"] = "L3 (wciśnij gałkę)",
        ["R3 (Stick drücken)"] = "R3 (wciśnij gałkę)",
        ["Ansicht/Zurück"] = "Podgląd/Wstecz",
        ["Menü/Start"] = "Menu/Start",
        ["Xbox-Taste"] = "Przycisk Xbox",

        // ---------- Controller-Namen ----------
        ["Wii-Fernbedienung"] = "Pilot Wii",
        ["Xbox-Controller"] = "Kontroler Xbox",
        ["Xbox-Controller (Microsoft)"] = "Kontroler Xbox (Microsoft)",
        ["XInput (USB, Bluetooth oder Xbox-Adapter)"] = "XInput (USB, Bluetooth lub adapter Xbox)",

        // ---------- Übersicht / Karten ----------
        ["Trennen"] = "Rozłącz",
        ["Vibrieren"] = "Wibruj",
        ["Gyro kalibrieren"] = "Kalibruj żyroskop",
        ["Ruhig liegen lassen …"] = "Połóż nieruchomo …",
        ["Kalibriert ✓"] = "Skalibrowano ✓",
        ["Hochkant halten"] = "Trzymaj pionowo",
        ["Quer halten"] = "Trzymaj poziomo",
        ["Joy-Con trennen"] = "Rozdziel Joy-Con",
        ["Zum Paar verbinden"] = "Połącz w parę",
        ["Joy-Con trennen – beide werden einzelne Controller"] = "Rozdziel Joy-Con – oba staną się osobnymi kontrolerami",
        ["Zum Paar verbinden – sucht einen freien Joy-Con"] = "Połącz w parę – szuka wolnego Joy-Cona",
        ["Doppelt angezeigt? Verstecken"] = "Wyświetlany podwójnie? Ukryj",
        ["amiibo lesen"] = "Odczytaj amiibo",
        ["Ring-Con ein"] = "Włącz Ring-Con",
        ["Ring-Con aus"] = "Wyłącz Ring-Con",
        ["Ring-Con wird gesucht …"] = "Szukanie Ring-Con …",
        ["IR-Kamera"] = "Kamera IR",
        ["Akku"] = "Bateria",
        ["Verbindung"] = "Połączenie",
        ["Adresse"] = "Adres",
        ["Seriennummer"] = "Numer seryjny",
        ["Griff"] = "Uchwyt",
        ["Maus"] = "Mysz",
        ["Gedrückt"] = "Wciśnięty",
        ["unbekannt"] = "nieznany",
        ["Charging Grip – GL/GR aktiv"] = "Charging Grip – GL/GR aktywne",
        ["aktiv (liegt auf dem Tisch)"] = "aktywny (leży na stole)",
        ["bereit – zum Benutzen auf den Tisch legen"] = "gotowy – połóż na stole, aby używać",
        ["Bewegungssensor: keine Daten"] = "Czujnik ruchu: brak danych",
        ["quer halten: Steuerkreuz links,\n1 und 2 rechts"] = "poziomo: krzyżak po lewej,\n1 i 2 po prawej",

        // ---------- Tooltips ----------
        ["Verbindung trennen. Der Controller verbindet sich beim nächsten Tastendruck wieder."] =
            "Rozłącz. Kontroler połączy się ponownie przy następnym naciśnięciu przycisku.",
        ["Controller kurz vibrieren lassen – zeigt, welcher Controller dieser Spieler ist."] =
            "Sprawia, że kontroler krótko wibruje – pokazuje, który kontroler należy do tego gracza.",
        ["Controller ruhig auf den Tisch legen und klicken: misst den Gyro-Nullpunkt neu (gegen Abdriften)."] =
            "Połóż kontroler nieruchomo na stole i kliknij: ponownie mierzy punkt zerowy żyroskopu (przeciw dryfowi).",
        ["Einzelnen Joy-Con quer (wie an der Switch) oder hochkant halten – wird je Joy-Con gemerkt. Hochkant gilt die Tastenbelegung von „Joy-Con-Paar“."] =
            "Trzymaj pojedynczy Joy-Con poziomo (jak na Switch) lub pionowo – zapamiętywane dla każdego Joy-Con. Pionowo obowiązuje przypisanie „pary Joy-Con”.",
        ["Versteckt den per USB angeschlossenen Controller vor Spielen (HidHide), damit sie nur den virtuellen Xbox-Controller sehen."] =
            "Ukrywa przed grami kontroler podłączony przez USB (HidHide), aby widziały tylko wirtualny kontroler Xbox.",
        ["amiibo mit dem NFC-Leser lesen und als Datei (.bin) speichern – z. B. für Emulatoren."] =
            "Odczytuje amiibo czytnikiem NFC i zapisuje jako plik (.bin) – np. dla emulatorów.",
        ["Ring-Con am rechten Joy-Con ein-/ausschalten: zusammendrücken = rechter Trigger, auseinanderziehen = linker Trigger. Beim Einschalten den Ring nicht berühren."] =
            "Włącza/wyłącza Ring-Con prawego Joy-Con: ściśnięcie = prawy spust, rozciągnięcie = lewy spust. Nie dotykaj pierścienia przy włączaniu.",
        ["Live-Bild der IR-Kamera im rechten Joy-Con anzeigen."] = "Pokazuje obraz na żywo z kamery IR prawego Joy-Con.",
        ["Links = empfindlicher (kleine Drehung, großer Ausschlag), rechts = ruhiger."] = "Lewo = czułeś (mały obrót, duże wychylenie), prawo = spokojniej.",
        ["Mindestausschlag des Sticks bei Bewegung – überwindet die Totzone des Spiels."] = "Minimalne wychylenie gałki w ruchu – pokonuje martwą strefę gry.",
        ["Mitte = linear. Rechts = feiner um die Mitte (präzises Zielen), links = schneller."] = "Środek = liniowo. Prawo = dokładniej wokół środka (precyzyjne celowanie), lewo = szybciej.",
        ["So weit lässt sich ein analoger Trigger drücken, bevor er wirkt."] = "Jak głęboko można wcisnąć spust analogowy, zanim zadziała.",
        ["Ab hier gilt der Trigger als ganz gedrückt (100 = erst am Anschlag)."] = "Od tego miejsca spust liczy się jako wciśnięty do końca (100 = dopiero na oporze).",
        ["Wie oft pro Sekunde Tasten mit „Turbo“ auslösen."] = "Ile razy na sekundę uruchamiają się przyciski „turbo”.",

        // ---------- Infobereich ----------
        ["ViGEmBus-Treiber fehlt"] = "Brak sterownika ViGEmBus",
        ["ViGEmBus herunterladen …"] = "Pobierz ViGEmBus …",
        ["Verbinde …"] = "Łączenie …",
        ["Kein Controller – SYNC-Taste am Controller kurz drücken"] = "Brak kontrolera – naciśnij krótko przycisk SYNC na kontrolerze",
        ["Ausgabe als"] = "Wyjście jako",
        ["Xbox-360-Controller (empfohlen)"] = "Kontroler Xbox 360 (zalecany)",
        ["DualShock 4 (mit Gyro für Steam/Emulatoren)"] = "DualShock 4 (z żyroskopem dla Steam/emulatorów)",
        ["Tastenbelegung"] = "Przypisanie przycisków",
        ["Xbox-Belegung (untere Taste = A)"] = "Układ Xbox (dolny przycisk = A)",
        ["Switch-2-Pro-Belegung (A bleibt A)"] = "Układ Nintendo (A pozostaje A)",
        ["Automatisch (nach Spiel/Programm)"] = "Automatycznie (wg gry/programu)",
        ["Mit Windows starten"] = "Uruchamiaj z Windows",
        ["Einstellungen …"] = "Ustawienia …",
        ["Kurzanleitung"] = "Skrócona instrukcja",
        ["Protokoll öffnen"] = "Otwórz dziennik",
        ["Beenden"] = "Zakończ",
        ["N-Connect: warte auf Controller (SYNC drücken)"] = "N-Connect: oczekiwanie na kontroler (naciśnij SYNC)",
        ["N-Connect: ViGEmBus fehlt"] = "N-Connect: brak ViGEmBus",
        ["Neue Version verfügbar"] = "Dostępna nowa wersja",
        ["Einstellungen fehlerhaft"] = "Uszkodzone ustawienia",
        ["settings.json konnte nicht gelesen werden – es gelten die Standardwerte."] = "Nie można odczytać settings.json – obowiązują wartości domyślne.",
        ["Ohne ViGEmBus kann kein virtueller Controller erzeugt werden. Bitte das Setup erneut ausführen oder ViGEmBus installieren (Rechtsklick auf das Symbol → ViGEmBus herunterladen)."] =
            "Bez ViGEmBus nie można utworzyć wirtualnego kontrolera. Uruchom ponownie instalator lub zainstaluj ViGEmBus (kliknij ikonę prawym przyciskiem → Pobierz ViGEmBus).",

        // ---------- Dialoge ----------
        ["Tastatur-Taste festlegen"] = "Ustaw klawisz klawiatury",
        ["Übernehmen"] = "Zastosuj",
        ["Abbrechen"] = "Anuluj",
        ["Ja"] = "Tak",
        ["Nein"] = "Nie",
        ["Turbo / Dauerfeuer"] = "Turbo / ogień ciągły",
        ["Tastatur-Taste aufnehmen …"] = "Zapisz klawisz klawiatury …",
        ["Makro (Tastenfolge)"] = "Makro (sekwencja przycisków)",
        ["Ungültig – bitte Schreibweise prüfen (siehe oben)."] = "Nieprawidłowe – sprawdź składnię (patrz wyżej).",
        ["Neues Profil"] = "Nowy profil",
        ["Name des Profils (z. B. der Spielname):"] = "Nazwa profilu (np. nazwa gry):",
        ["Profil umbenennen"] = "Zmień nazwę profilu",
        ["Neuer Name:"] = "Nowa nazwa:",
        ["Ein Profil mit diesem Namen gibt es schon."] = "Profil o tej nazwie już istnieje.",
        ["Die Datei enthält kein gültiges Controller-Profil."] = "Plik nie zawiera prawidłowego profilu kontrolera.",
        ["Alle Einstellungen und Tastenbelegungen auf Standard zurücksetzen?"] = "Zresetować wszystkie ustawienia i przypisania przycisków?",
        ["Suche …"] = "Szukanie …",
        ["Kein Bluetooth-Adapter gefunden."] = "Nie znaleziono adaptera Bluetooth.",
        ["IR-Kamera (Joy-Con R)"] = "Kamera IR (Joy-Con P)",
        ["Auflösung:"] = "Rozdzielczość:",
        ["40 × 30 (schnell)"] = "40 × 30 (szybka)",
        ["320 × 240 (langsam)"] = "320 × 240 (wolna)",
        ["Kamera startet …"] = "Uruchamianie kamery …",
        ["läuft – Joy-Con auf eine Lichtquelle oder die Hand richten"] = "działa – skieruj Joy-Con na źródło światła lub dłoń",
        ["Kamera startet nicht (Details im Protokoll)"] = "Kamera nie uruchamia się (szczegóły w dzienniku)",
        ["Kein Ring-Con gefunden. Den rechten Joy-Con (Switch 1) fest in den Ring-Con schieben und erneut versuchen."] =
            "Nie znaleziono Ring-Con. Wsuń mocno prawy Joy-Con (Switch 1) do Ring-Con i spróbuj ponownie.",
        ["Kein amiibo erkannt. Bitte das amiibo flach an den NFC-Leser halten (Joy-Con: auf den rechten Stick, Pro Controller: auf das NFC-Logo) und erneut versuchen."] =
            "Nie wykryto amiibo. Przyłóż amiibo płasko do czytnika NFC (Joy-Con: na prawą gałkę; Pro Controller: na logo NFC) i spróbuj ponownie.",
        ["NFC-Leser wird eingeschaltet …"] = "Włączanie czytnika NFC …",
        ["amiibo an den Leser halten (rechter Stick des Joy-Con bzw. NFC-Logo des Pro Controllers) …"] =
            "Przyłóż amiibo do czytnika (prawa gałka Joy-Con lub logo NFC Pro Controllera) …",
        ["amiibo speichern"] = "Zapisz amiibo",
        ["Doppelte Controller verhindern"] = "Zapobiegaj podwójnym kontrolerom",
        ["Dafür wird das kostenlose Programm HidHide gebraucht (von den Machern von ViGEmBus).\n\nJetzt die Download-Seite öffnen? Nach der Installation hier erneut klicken."] =
            "Potrzebny jest bezpłatny program HidHide (od twórców ViGEmBus).\n\nOtworzyć teraz stronę pobierania? Po instalacji kliknij tu ponownie.",
        ["HidHide konnte nicht eingerichtet werden (abgebrochen oder fehlgeschlagen). Details im Protokoll."] =
            "Nie udało się skonfigurować HidHide (anulowano lub niepowodzenie). Szczegóły w dzienniku.",
        ["Der Controller hat sich bewegt oder keine Bewegungsdaten geliefert.\nBitte flach auf den Tisch legen, nicht berühren und erneut versuchen."] =
            "Kontroler się poruszył lub nie wysłał danych ruchu.\nPołóż go płasko na stole, nie dotykaj i spróbuj ponownie.",
        ["Spiel oder Programm wählen"] = "Wybierz grę lub program",
        ["Profil exportieren"] = "Eksportuj profil",
        ["Profil importieren"] = "Importuj profil",
        ["Verstanden"] = "Rozumiem",
        ["Einstellungen öffnen"] = "Otwórz ustawienia",
        ["Willkommen"] = "Witamy",

        // ---------- Neues Hauptfenster (Navigation, Seiten, Zeilen) ----------
        ["Allgemein"] = "Ogólne",
        ["Sticks & Vibration"] = "Gałki i wibracje",
        ["Gyro & Maus"] = "Żyroskop i mysz",
        ["Joy-Con & Wii"] = "Joy-Con i Wii",
        ["Ein"] = "Wł.",
        ["Aus"] = "Wył.",
        ["Verbundene Controller mit Live-Anzeige. Über „Einstellungen“ an einem Controller passt du genau diesen an."] =
            "Połączone kontrolery z podglądem na żywo. Przez „Ustawienia” przy kontrolerze dostosujesz dokładnie ten.",
        ["Jede Taste kann ein Gamepad-Knopf, eine Tastaturtaste, ein Mausklick, Turbo oder ein Makro sein. " +
         "Tipp: Drückst du eine Taste am Controller, wird ihre Zeile hervorgehoben."] =
            "Każdy przycisk może być przyciskiem gamepada, klawiszem, kliknięciem myszy, turbo lub makrem. " +
            "Wskazówka: naciśnij przycisk na kontrolerze, aby podświetlić jego wiersz.",
        ["Profil"] = "Profil",
        ["Neu"] = "Nowy",
        ["Umbenennen, löschen, exportieren, importieren"] = "Zmień nazwę, usuń, eksportuj, importuj",
        ["Ein eigenes Profil gilt automatisch, solange eines seiner Programme im Vordergrund ist – sonst „Standard“."] =
            "Własny profil obowiązuje automatycznie, gdy jeden z jego programów jest na pierwszym planie – inaczej „Domyślny”.",
        ["Aktiv bei Programm"] = "Aktywny przy programie",
        ["Programmdateien, bei denen dieses Profil gilt (mit Komma trennen)."] = "Pliki programów, przy których obowiązuje ten profil (oddziel przecinkami).",
        ["Standard gilt für alle Programme"] = "Domyślny obowiązuje dla wszystkich programów",
        ["Wählen …"] = "Wybierz …",
        ["Bearbeiten"] = "Edytuj",
        ["Jeder Controller hat seine eigene Belegung."] = "Każdy kontroler ma własne przypisanie.",
        ["Ebene"] = "Warstwa",
        ["Normal"] = "Normalna",
        ["Shift-Ebene"] = "Warstwa Shift",
        ["Die Shift-Ebene gilt, solange eine Taste mit „Shift-Ebene“ gehalten wird."] = "Warstwa Shift obowiązuje, dopóki przycisk ustawiony na „warstwę Shift” jest wciśnięty.",
        ["Tasten"] = "Przyciski",
        ["Standardwerte für alle Controller. Eigene Werte für einzelne Controller stellst du unten oder in der Übersicht ein."] =
            "Wartości domyślne dla wszystkich kontrolerów. Własne wartości dla poszczególnych kontrolerów ustawisz poniżej lub w przeglądzie.",
        ["Sticks"] = "Gałki",
        ["Totzone"] = "Martwa strefa",
        ["So weit lässt sich ein Stick bewegen, bevor er wirkt (gegen Abdriften)."] = "Jak daleko gałka może się poruszyć, zanim zareaguje (przeciw dryfowi).",
        ["Kennlinie"] = "Charakterystyka",
        ["„linear“ = gleichmäßig. Höher = feiner um die Mitte (präzises Zielen), niedriger = schneller."] =
            "„liniowa” = równomierna. Wyższa = dokładniejsza wokół środka (precyzyjne celowanie), niższa = szybsza.",
        ["Analoge Trigger (GameCube)"] = "Spusty analogowe (GameCube)",
        ["So weit lässt sich ein Trigger drücken, bevor er wirkt."] = "Jak głęboko można wcisnąć spust, zanim zareaguje.",
        ["Voll gedrückt ab"] = "Wciśnięty do końca od",
        ["Ab hier gilt der Trigger als ganz gedrückt (100 % = erst am Anschlag)."] = "Od tego miejsca spust liczy się jako wciśnięty do końca (100 % = dopiero na oporze).",
        ["Spiele dürfen den Controller vibrieren lassen."] = "Gry mogą wibrować kontrolerem.",
        ["Stärke"] = "Siła",
        ["Turbo-Geschwindigkeit"] = "Prędkość turbo",
        ["Wie oft pro Sekunde Tasten mit „Turbo“ auslösen."] = "Ile razy na sekundę uruchamiają się przyciski „turbo”.",
        ["Eigene Werte je Controller"] = "Własne wartości na kontroler",
        ["Werte nur für diesen Controller – ohne eigenen Wert gilt der allgemeine."] = "Wartości tylko dla tego kontrolera – bez własnej wartości obowiązuje ogólna.",
        ["Bewegungssteuerung: Zielen per Gyro und den Controller als Maus nutzen."] = "Sterowanie ruchem: celowanie żyroskopem i używanie kontrolera jako myszy.",
        ["Gyro als rechter Stick"] = "Żyroskop jako prawa gałka",
        ["Modus"] = "Tryb",
        ["Zum Zielen in Spielen ohne eigene Gyro-Steuerung. „Gyro-Stick“ kann auch einer Taste zugewiesen werden."] =
            "Do celowania w grach bez własnego sterowania żyroskopem. „Gałka żyroskopowa” może być też przypisana do przycisku.",
        ["Aus (nur per Taste „Gyro-Stick“)"] = "Wyłączony (tylko przyciskiem „gałka żyroskopowa”)",
        ["Immer"] = "Zawsze",
        ["Beim Zielen (solange ZL / LT gedrückt)"] = "Przy celowaniu (dopóki ZL / LT jest wciśnięty)",
        ["Empfindlichkeit"] = "Czułość",
        ["Drehgeschwindigkeit für vollen Stick-Ausschlag – kleiner = empfindlicher."] = "Prędkość obrotu dla pełnego wychylenia gałki – niższa = czułeś.",
        ["Mindestausschlag"] = "Minimalne wychylenie",
        ["Überwindet die Stick-Totzone des Spiels bei kleinen Bewegungen."] = "Pokonuje martwą strefę gałki gry przy małych ruchach.",
        ["Hoch/runter umkehren"] = "Odwróć góra/dół",
        ["Links/rechts umkehren"] = "Odwróć lewo/prawo",
        ["Gyro-Maus"] = "Mysz żyroskopowa",
        ["Geschwindigkeit"] = "Prędkość",
        ["Mauszeiger per Bewegung – über eine Taste mit „Gyro-Maus“ (Tastenbelegung)."] = "Kursor myszy przez ruch – przez przycisk „mysz żyroskopowa” (przypisanie przycisków).",
        ["Mausrichtung (Gyro-Maus und Joy-Con-Maus)"] = "Kierunek myszy (mysz żyroskopowa i mysz Joy-Con)",
        ["Gyro-Funktionen einer Taste zuweisen"] = "Przypisz funkcje żyroskopu do przycisku",
        ["Gyro-Maus oder Gyro-Stick ein/aus bzw. solange gehalten"] = "Mysz żyroskopowa lub gałka żyroskopowa wł./wył. albo dopóki wciśnięte",
        ["Joy-Con als Paar oder einzeln, Joy-Con 2 als Maus und Wii-Controller."] = "Joy-Con w parze lub pojedynczo, Joy-Con 2 jako mysz i kontrolery Wii.",
        ["Zu einem Controller zusammenfassen"] = "Połącz w jeden kontroler",
        ["Ein linker und ein rechter Joy-Con werden automatisch ein Paar."] = "Lewy i prawy Joy-Con automatycznie tworzą parę.",
        ["Gyro beim Paar vom"] = "Żyroskop pary z",
        ["Rechter Joy-Con (wie Switch)"] = "Prawy Joy-Con (jak na Switch)",
        ["Linker Joy-Con"] = "Lewy Joy-Con",
        ["Paar lösen oder verbinden"] = "Rozdziel lub połącz parę",
        ["Einen Joy-Con quer halten und SL oder SR drücken löst ihn aus dem Paar. L am linken und R am rechten Joy-Con gleichzeitig drücken verbindet sie wieder. Die Wahl wird je Joy-Con gemerkt."] =
            "Trzymaj Joy-Con poziomo i naciśnij SL lub SR, aby odłączyć go od pary. Jednoczesne naciśnięcie L na lewym i R na prawym łączy je z powrotem. Wybór jest zapamiętywany dla każdego Joy-Con.",
        ["Joy-Con 2 als Maus"] = "Joy-Con 2 jako mysz",
        ["Als Maus, wenn er auf dem Tisch liegt"] = "Jako mysz, gdy leży na stole",
        ["Joy-Con 2 auf die Seite legen und wie eine Maus schieben."] = "Połóż Joy-Con 2 na boku i przesuwaj jak mysz.",
        ["Mausgeschwindigkeit"] = "Prędkość myszy",
        ["Tasten im Mausmodus"] = "Przyciski w trybie myszy",
        ["R/L = Linksklick, ZR/ZL = Rechtsklick, Stick drücken = Mittelklick, Stick hoch/runter = Scrollen."] =
            "R/L = lewy przycisk, ZR/ZL = prawy przycisk, wciśnięcie gałki = środkowy przycisk, gałka góra/dół = przewijanie.",
        ["Zeiger steuert die Maus"] = "Wskaźnik steruje myszą",
        ["Wii-Fernbedienung auf die Sensorleiste richten, um den Mauszeiger zu bewegen."] = "Skieruj pilota Wii na pasek sensorów, aby poruszać kursorem.",
        ["Wie Spiele die Controller sehen, Verbindung, Darstellung und Programm."] = "Jak gry widzą kontrolery, połączenie, wygląd i program.",
        ["Ausgabe"] = "Wyjście",
        ["Controller erscheint als"] = "Kontroler pojawia się jako",
        ["Xbox 360 läuft mit fast allen Spielen. DualShock 4 bietet Bewegungssteuerung (Steam, Emulatoren)."] =
            "Xbox 360 działa z niemal wszystkimi grami. DualShock 4 oferuje sterowanie ruchem (Steam, emulatory).",
        ["Xbox 360 läuft mit fast allen Spielen und Steam. DualShock 4 bietet zusätzlich Bewegungssteuerung (Steam, Emulatoren). Gilt für alle Controller ohne eigene Einstellung (Karte → Einstellungen → Tasten)."] =
            "Xbox 360 działa z niemal wszystkimi grami i Steam. DualShock 4 dodaje sterowanie ruchem (Steam, emulatory). Dotyczy wszystkich kontrolerów bez własnego ustawienia (karta → Ustawienia → Przyciski).",
        ["Original-Controller verstecken"] = "Ukryj oryginalne kontrolery",
        ["Controller verbinden"] = "Połącz kontrolery",
        ["SYNC-Taste am Controller drücken – N-Connect findet und koppelt ihn selbst. Danach reicht künftig ein Tastendruck."] =
            "Naciśnij przycisk SYNC na kontrolerze – N-Connect znajdzie go i sparuje sam. Potem wystarczy jedno naciśnięcie.",
        ["So kommt der Controller in den Kopplungsmodus"] = "Jak włączyć tryb parowania kontrolera",
        ["Kurz die kleine SYNC-Taste drücken."] = "Naciśnij krótko mały przycisk SYNC.",
        ["SYNC-Taste drücken, bis die Lichter laufen."] = "Naciśnij przycisk SYNC, aż światełka zaczną biec.",
        ["Batteriefach öffnen und die rote SYNC-Taste drücken."] = "Otwórz schowek na baterie i naciśnij czerwony przycisk SYNC.",
        ["Die SYNC-Taste auf der Unterseite drücken."] = "Naciśnij przycisk SYNC na spodzie.",
        ["PS + Teilen bzw. Create halten, bis die Lichtleiste schnell blinkt."] =
            "Przytrzymaj PS + Share/Create, aż pasek świetlny zacznie szybko migać.",
        ["Kopplungstaste oben halten, bis die Xbox-Taste blinkt."] = "Przytrzymaj górny przycisk parowania, aż przycisk Xbox zacznie migać.",
        ["Status"] = "Stan",
        ["Suche läuft …"] = "Szukanie …",
        ["Suche läuft – jetzt SYNC drücken …"] = "Trwa szukanie – naciśnij teraz SYNC …",
        ["Weitere Controller? Einfach SYNC drücken."] = "Kolejne kontrolery? Po prostu naciśnij SYNC.",
        ["Wartet auf einen Controller im Kopplungsmodus."] = "Oczekiwanie na kontroler w trybie parowania.",
        ["Suche beendet"] = "Szukanie zakończone",
        ["Die Controller stehen in der Übersicht und verbinden sich künftig per Tastendruck."] =
            "Kontrolery są w przeglądzie i będą się łączyć jednym naciśnięciem.",
        ["Kein Controller im Kopplungsmodus gefunden. SYNC-Taste drücken und „Erneut suchen“ klicken."] =
            "Nie znaleziono kontrolera w trybie parowania. Naciśnij SYNC i kliknij „Szukaj ponownie”.",
        ["Verbunden"] = "Połączono",
        ["Erneut suchen"] = "Szukaj ponownie",
        ["Fertig"] = "Gotowe",
        ["Im Spiel"] = "W grze",
        ["Dreht …"] = "Obrót …",
        ["Testdrehung (360°)"] = "Obrót testowy (360°)",
        ["Testdrehung"] = "Obrót testowy",
        ["aus"] = "wył.",
        ["Gyro-Beschleunigung"] = "Przyspieszenie żyroskopu",
        ["Bei schneller Drehung"] = "Przy szybkim obrocie",
        ["Langsame Bewegungen bleiben fein, schnelle drehen weiter (wie JoyShockMapper). Voll ab 120 °/s, unter 20 °/s normal. Gilt für Gyro-Stick und Gyro-Maus."] =
            "Wolne ruchy pozostają precyzyjne, szybkie obracają dalej (jak JoyShockMapper). Pełne od 120 °/s, normalne poniżej 20 °/s. Dotyczy gałki i myszy żyroskopowej.",
        ["Flick-Stick (Spiele mit Maussteuerung)"] = "Flick stick (gry ze sterowaniem myszą)",
        ["Flick-Stick"] = "Flick stick",
        ["Rechten Stick in eine Richtung schieben = Kamera dreht sofort dorthin; am Rand drehen = Kamera dreht mit. Zielen dann per Gyro. Der rechte Stick geht nicht mehr ans Spiel."] =
            "Pchnięcie prawej gałki w kierunku = kamera natychmiast tam się obraca; obracanie przy krawędzi = kamera podąża. Potem celuje się żyroskopem. Prawa gałka nie trafia już do gry.",
        ["Mausbewegung je Umdrehung"] = "Ruch myszy na obrót",
        ["Je Spiel einmal einstellen: „Testdrehung“ klicken, ins Spiel wechseln – nach 3 s dreht die Kamera einmal. Genau eine volle Drehung = richtig."] =
            "Do ustawienia raz na grę: kliknij „Obrót testowy”, przejdź do gry – po 3 s kamera obróci się raz. Dokładnie jeden pełny obrót = poprawnie.",
        ["Flick-Dauer"] = "Czas flicka",
        ["So lange dauert die Drehung beim Flick (0 = sofort)."] = "Jak długo trwa obrót flicka (0 = natychmiast).",
        ["Gyro-Maus oder Gyro-Stick ein/aus bzw. solange gehalten, „Gyro anhalten“ (Ratchet: Controller zurückführen, ohne dass sich das Ziel bewegt)"] =
            "Mysz żyroskopowa lub gałka żyroskopowa wł./wył. albo dopóki wciśnięte, „wstrzymaj żyroskop” (ratchet: cofnij kontroler bez poruszania celownikiem)",
        ["✋  Gyro anhalten (solange gehalten, „Ratchet“)"] = "✋  Wstrzymaj żyroskop (dopóki wciśnięte, „ratchet”)",
        ["Spieler-LED und Lichtleiste vom Spiel"] = "LED gracza i pasek świetlny z gry",
        ["Die Spieler-LEDs zeigen den Xbox-Platz, den Windows vergibt. Bei DualShock 4 steuert die Lichtleiste des Spiels die HOME-LED (Switch 1 Pro Controller, rechter Joy-Con)."] =
            "Diody LED gracza pokazują miejsce Xbox przydzielone przez Windows. W DualShock 4 pasek świetlny gry steruje diodą HOME (Pro Controller Switch 1, prawy Joy-Con).",
        ["HidHide installieren …"] = "Zainstaluj HidHide …",
        ["Empfohlen: Steam und viele Spiele kennen Switch-1-, NSO- und USB-Controller selbst und sähen sie sonst doppelt. Läuft nach der Installation ohne Rückfrage (sonst fragt Windows nach Adminrechten)."] =
            "Zalecane: Steam i wiele gier samo rozpoznaje kontrolery Switch 1, NSO i USB i widziałoby je podwójnie. Po instalacji działa bez pytań (inaczej Windows prosi o uprawnienia administratora).",
        ["Steam und viele Spiele sehen Switch-1-, NSO- und USB-Controller sonst doppelt. Dafür wird das kostenlose HidHide gebraucht (bei der N-Connect-Installation dabei, hier nachträglich)."] =
            "W przeciwnym razie Steam i wiele gier widzi kontrolery Switch 1, NSO i USB podwójnie. Potrzebny jest bezpłatny HidHide (dołączony do instalacji N-Connect, do zainstalowania tutaj).",
        ["Erscheint als"] = "Pojawia się jako",
        ["Wie allgemein"] = "Jak w Ogólne",
        ["Nur für diesen Controller. Xbox 360 läuft überall; DualShock 4 bringt zusätzlich Gyro nach Steam und in Emulatoren. „Wie allgemein“ folgt der Seite „Allgemein“."] =
            "Tylko dla tego kontrolera. Xbox 360 działa wszędzie; DualShock 4 dodaje żyroskop w Steam i emulatorach. „Jak w Ogólne” podąża za stroną „Ogólne”.",
        ["Der echte Xbox-Controller – Spiele sehen ihn von Windows aus direkt. Belegungen hier wirken auf Sonderaktionen (Tastatur, Makros, Gyro), nicht auf den Controller selbst."] =
            "Prawdziwy kontroler Xbox – gry widzą go już bezpośrednio z Windows. Przypisania tutaj działają na akcje specjalne (klawiatura, makra, żyroskop), nie na sam kontroler.",
        ["Steam und manche Spiele sehen diesen Controller sonst doppelt. Abhilfe: HidHide installieren (Seite „Allgemein“ → „Original-Controller verstecken“)."] =
            "W przeciwnym razie Steam i niektóre gry widzą ten kontroler podwójnie. Rozwiązanie: zainstaluj HidHide (strona „Ogólne” → „Ukryj oryginalne kontrolery”).",
        ["Original-Controller vor Spielen versteckt. Steam bitte einmal neu starten – danach sieht es nur noch den virtuellen Controller."] =
            "Oryginalne kontrolery ukryte przed grami. Uruchom Steam raz ponownie – wtedy widzi już tylko wirtualny kontroler.",
        ["Original-Controller vor Spielen versteckt – Steam und Spiele sehen nur noch den virtuellen Controller."] =
            "Oryginalne kontrolery ukryte przed grami – Steam i gry widzą już tylko wirtualny kontroler.",
        ["Original-Controller nicht versteckt (Abfrage abgebrochen). Nachholen: Controller → Einstellungen → Extras → „Doppelt angezeigt?“."] =
            "Oryginalne kontrolery nie ukryte (przerwano zapytanie). Później: kontroler → Ustawienia → Dodatki → „Wyświetlany podwójnie?”.",
        ["Tastenanordnung A/B/X/Y"] = "Układ przycisków A/B/X/Y",
        ["Xbox: nach Position (untere Taste = A). Nintendo: nach Beschriftung (A bleibt A)."] = "Xbox: wg pozycji (dolny przycisk = A). Nintendo: wg oznaczenia (A pozostaje A).",
        ["Verbinden"] = "Połączenie",
        ["Per Tastendruck verbinden"] = "Łącz jednym naciśnięciem",
        ["Gekoppelte Controller verbinden sich ohne SYNC-Taste."] = "Sparowane kontrolery łączą się bez przycisku SYNC.",
        ["Ohne Eingabe trennen nach"] = "Rozłącz bez czynności po",
        ["Spart Akku, wenn ein Controller liegen bleibt."] = "Oszczędza baterię, gdy kontroler leży bezczynnie.",
        ["N-Connect startet unsichtbar im Infobereich."] = "N-Connect uruchamia się dyskretnie w zasobniku.",
        ["Darstellung und Sprache"] = "Wygląd i język",
        ["Farbmodus"] = "Tryb koloru",
        ["Mica-Effekt"] = "Efekt Mica",
        ["Durchscheinende Titelleiste (ab Windows 11)."] = "Półprzezroczysty pasek tytułu (od Windows 11).",
        ["Erweitert"] = "Zaawansowane",
        ["Gyro für Emulatoren (DSU)"] = "Żyroskop dla emulatorów (DSU)",
        ["Cemuhook-Server auf Port 26760 – wirkt nach einem Neustart von N-Connect."] = "Serwer Cemuhook na porcie 26760 – aktywny po restarcie N-Connect.",
        ["Nach Updates suchen"] = "Szukaj aktualizacji",
        ["Beim Start auf GitHub nach einer neuen Version suchen."] = "Szukaj nowej wersji na GitHub przy starcie.",
        ["Tastenbelegungen und Werte zurücksetzen. Gekoppelte Controller bleiben erhalten."] = "Resetuj przypisania przycisków i wartości. Sparowane kontrolery pozostają.",
        ["Zurücksetzen"] = "Resetuj",

        // ---------- Controller-Karte ----------
        ["Einstellungen"] = "Ustawienia",
        ["Tastenbelegung und Einstellungen nur für diesen Controller"] = "Przypisanie przycisków i ustawienia tylko dla tego kontrolera",
        ["Feineinstellung"] = "Regulacja precyzyjna",
        ["Gyro"] = "Żyroskop",
        ["Extras"] = "Dodatki",
        ["Belegung für alle Spiele (Standard) oder ein eigenes Profil."] = "Przypisanie dla wszystkich gier (domyślne) lub własny profil.",
        ["Profile"] = "Profile",
        ["Profile anlegen, umbenennen, exportieren …"] = "Twórz, zmieniaj nazwę, eksportuj profile …",
        ["Drück eine Taste am Controller – ihre Zeile leuchtet auf. ⌨ weist eine Tastaturtaste zu, ↺ setzt zurück."] =
            "Naciśnij przycisk na kontrolerze – jego wiersz się podświetli. ⌨ przypisuje klawisz, ↺ resetuje.",
        ["Tastatur-Taste zuweisen: klicken und die gewünschte Taste oder Kombination drücken."] = "Przypisz klawisz: kliknij i naciśnij żądany klawisz lub skrót.",
        ["Zurück auf die Standardbelegung"] = "Wróć do przypisania domyślnego",
        ["Ohne eigenen Wert gilt der allgemeine Wert der Seite „Sticks & Vibration“."] = "Bez własnej wartości obowiązuje ogólna ze strony „Gałki i wibracje”.",
        ["Stick-Totzone"] = "Martwa strefa gałki",
        ["Stick-Kennlinie"] = "Charakterystyka gałki",
        ["Trigger-Totzone"] = "Martwa strefa spustu",
        ["Trigger voll gedrückt ab"] = "Spust wciśnięty do końca od",
        ["Vibrationsstärke"] = "Siła wibracji",
        ["Gyro-Maus-Geschwindigkeit"] = "Prędkość myszy żyroskopowej",
        ["Eigenen Wert entfernen – es gilt wieder der allgemeine Wert"] = "Usuń własną wartość – znów obowiązuje ogólna",
        ["Kalibrieren"] = "Kalibruj",
        ["Controller ruhig auf den Tisch legen und klicken: misst den Nullpunkt neu (gegen Abdriften)."] =
            "Połóż kontroler nieruchomo na stole i kliknij: ponownie mierzy punkt zerowy (przeciw dryfowi).",
        ["Gyro als rechter Stick und Mausrichtung"] = "Żyroskop jako prawa gałka i kierunek myszy",
        ["Gilt für alle Controller"] = "Dotyczy wszystkich kontrolerów",
        ["Paar"] = "Para",
        ["Joy-Con quer halten und SL oder SR drücken löst das Paar, L + R gleichzeitig verbindet es."] =
            "Trzymaj Joy-Con poziomo i naciśnij SL lub SR, aby rozdzielić parę; L + R jednocześnie łączy ją.",
        ["Haltung"] = "Orientacja",
        ["Quer"] = "Poziomo",
        ["Hochkant"] = "Pionowo",
        ["Quer wie an der Switch oder hochkant – hochkant gilt die Belegung von „Joy-Con-Paar“."] =
            "Poziomo jak na Switch lub pionowo – pionowo obowiązuje przypisanie „pary Joy-Con”.",
        ["Mausmodus, Geschwindigkeit und Tasten"] = "Tryb myszy, prędkość i przyciski",
        ["Lesen …"] = "Odczytaj …",
        ["Einschalten"] = "Włącz",
        ["Ausschalten"] = "Wyłącz",
        ["Wird gesucht …"] = "Szukanie …",
        ["Öffnen"] = "Otwórz",
        ["Verstecken"] = "Ukryj",
        ["amiibo an den NFC-Leser halten und als Datei (.bin) speichern – z. B. für Emulatoren."] =
            "Przyłóż amiibo do czytnika NFC i zapisz jako plik (.bin) – np. dla emulatorów.",
        ["Zusammendrücken = rechter Trigger, auseinanderziehen = linker Trigger. Beim Einschalten nicht berühren."] =
            "Ściśnięcie = prawy spust, rozciągnięcie = lewy spust. Nie dotykaj przy włączaniu.",
        ["Live-Bild der Infrarotkamera im rechten Joy-Con."] = "Obraz na żywo z kamery podczerwieni prawego Joy-Con.",
        ["Doppelt angezeigt?"] = "Wyświetlany podwójnie?",
        ["Versteckt den Original-Controller vor Steam und Spielen (HidHide) – sie sehen dann nur den virtuellen Controller."] =
            "Ukrywa oryginalny kontroler przed Steam i grami (HidHide) – widzą wtedy tylko wirtualny kontroler.",
        ["bereit (auf den Tisch legen)"] = "gotowy (połóż na stole)",
        ["amiibo-Abbild (*.bin)|*.bin"] = "Obraz amiibo (*.bin)|*.bin",
        ["Controller-Profil (*.ncprofile.json)|*.ncprofile.json|JSON (*.json)|*.json"] = "Profil kontrolera (*.ncprofile.json)|*.ncprofile.json|JSON (*.json)|*.json",
        ["Programme (*.exe)|*.exe"] = "Programy (*.exe)|*.exe",
        ["Kein Controller verbunden\n\n" +
         "Switch-2-Controller: kurz die SYNC-Taste drücken – danach reicht ein beliebiger Tastendruck.\n" +
         "Switch-1-, NSO- und Wii-Controller: SYNC-Taste drücken – N-Connect koppelt sie selbst.\n" +
         "Oder hier gezielt suchen und koppeln:"] =
            "Brak połączonego kontrolera\n\n" +
            "Kontrolery Switch 2: naciśnij krótko przycisk SYNC – potem wystarczy dowolne naciśnięcie.\n" +
            "Kontrolery Switch 1, NSO i Wii: naciśnij przycisk SYNC – N-Connect paruje je sam.\n" +
            "Albo wyszukaj i sparuj bezpośrednio tutaj:",
        ["Controller suchen …"] = "Szukaj kontrolerów …",
        ["Kein Controller verbunden"] = "Brak połączonego kontrolera",
        ["Switch-1-, NSO- und Wii-Controller suchen und koppeln (SYNC-Taste drücken)."] =
            "Wyszukaj i sparuj kontrolery Switch 1, NSO i Wii (naciśnij przycisk SYNC).",
        ["Neue Controller automatisch koppeln"] = "Automatycznie paruj nowe kontrolery",
        ["Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive, Wii und PlayStation: einfach SYNC " +
         "drücken – kein Umweg über die Windows-Bluetooth-Einstellungen. Gesucht wird nur, solange niemand spielt."] =
            "Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive, Wii i PlayStation: po prostu naciśnij SYNC – " +
            "bez omijania ustawień Bluetooth Windows. Szukanie odbywa się tylko, gdy nikt nie gra.",
        ["Gezielt suchen"] = "Wyszukiwanie ukierunkowane",
        ["Sucht eine Minute lang nach Controllern im Kopplungsmodus."] = "Szuka kontrolerów w trybie parowania przez minutę.",
        ["Controller koppeln …"] = "Sparuj kontroler …",
        ["Controller koppeln"] = "Sparuj kontroler",
        ["Linken Joy-Con umbenennen …"] = "Zmień nazwę lewego Joy-Con …",
        ["Rechten Joy-Con umbenennen …"] = "Zmień nazwę prawego Joy-Con …",
        ["Controller umbenennen"] = "Zmień nazwę kontrolera",
        ["Spielerplatz"] = "Miejsce gracza",
        ["N-Connect aktualisieren"] = "Aktualizuj N-Connect",
        ["HidHide aktualisieren"] = "Aktualizuj HidHide",
        ["HidHide-Update verfügbar"] = "Dostępna aktualizacja HidHide",
        ["HidHide aktuell halten"] = "Utrzymuj HidHide aktualny",
        ["Beim Start nach einer neuen HidHide-Version suchen. Installiert wird nur nach Rückfrage (geprüfter Download vom Hersteller, Neustart nötig)."] =
            "Szukaj nowej wersji HidHide przy starcie. Instalacja tylko po potwierdzeniu (zweryfikowane pobieranie od producenta, wymagany restart).",
        ["Der Download hat nicht geklappt oder die Datei war fehlerhaft. Die Release-Seite im Browser öffnen?"] =
            "Pobieranie nie powiodło się lub plik był wadliwy. Otworzyć stronę wydania w przeglądarce?",
        ["Alle Controller trennen"] = "Rozłącz wszystkie kontrolery",
        ["Sticks kalibrieren"] = "Kalibruj gałki",
        ["Kalibrieren …"] = "Kalibruj …",
        ["Gegen Drift oder zu kleinen Ausschlag: Mitte und Rand neu messen. Wird nur in N-Connect gespeichert, der Controller bleibt unverändert."] =
            "Przeciw dryfowi lub zbyt małemu zakresowi: zmierz ponownie środek i krawędź. Zapisane tylko w N-Connect, kontroler pozostaje bez zmian.",
        ["Linker Stick"] = "Lewa gałka",
        ["Rechter Stick"] = "Prawa gałka",
        ["Stick"] = "Gałka",
        ["Stick (linker Joy-Con)"] = "Gałka (lewy Joy-Con)",
        ["Stick (rechter Joy-Con)"] = "Gałka (prawy Joy-Con)",
        ["Neu messen"] = "Zmierz ponownie",
        ["Werkswerte"] = "Wartości fabryczne",
        ["Der Punkt zeigt, wo der Stick gerade steht. Steht er losgelassen nicht in der Mitte oder erreicht er den Kreis nicht, auf „Neu messen“ klicken."] =
            "Kropka pokazuje, gdzie jest gałka. Jeśli po puszczeniu nie jest na środku lub nie sięga okręgu, kliknij „Zmierz ponownie”.",
        ["Gilt gerade: eigene Kalibrierung."] = "Obecnie używana: własna kalibracja.",
        ["Gilt gerade: Werkswerte des Controllers."] = "Obecnie używane: wartości fabryczne kontrolera.",
        ["1/2 – Stick loslassen und den Controller ruhig halten …"] = "1/2 – puść gałkę i trzymaj kontroler nieruchomo …",
        ["2/2 – Stick bis zum Anschlag drücken und langsam ein- bis zweimal im Kreis drehen."] =
            "2/2 – wciśnij gałkę do oporu i powoli obróć ją w kółko raz lub dwa razy.",
        ["Fertig. „Übernehmen“ speichert die neue Kalibrierung für diesen Controller."] = "Gotowe. „Zastosuj” zapisuje nową kalibrację dla tego kontrolera.",
        ["Der Stick hat den Rand nicht erreicht. Bitte bis zum Anschlag drücken und erneut messen."] =
            "Gałka nie osiągnęła krawędzi. Wciśnij ją do oporu i zmierz ponownie.",
        ["Übernommen ✓ – gilt ab sofort."] = "Zastosowano ✓ – aktywne od razu.",
        ["Werkswerte des Controllers gelten wieder."] = "Znów obowiązują wartości fabryczne kontrolera.",
        ["Gyro einrichten"] = "Skonfiguruj żyroskop",
        ["Einrichten …"] = "Skonfiguruj …",
        ["Zielen per Bewegung einrichten"] = "Skonfiguruj celowanie ruchem",
        ["Schritt für Schritt: Nullpunkt, wann der Gyro zielt, Empfindlichkeit – mit Vorschau."] =
            "Krok po kroku: punkt zerowy, kiedy żyroskop celuje, czułość – z podglądem.",
        ["1  Nullpunkt"] = "1  Punkt zerowy",
        ["Controller flach auf den Tisch legen, nicht berühren – verhindert, dass das Ziel von selbst wandert."] =
            "Połóż kontroler płasko na stole, nie dotykaj – zapobiega samoczynnemu dryfowi celownika.",
        ["Nullpunkt messen"] = "Zmierz punkt zerowy",
        ["Der Controller hat sich bewegt – bitte flach hinlegen und erneut versuchen."] = "Kontroler się poruszył – połóż go płasko i spróbuj ponownie.",
        ["Nullpunkt gemessen ✓"] = "Punkt zerowy zmierzony ✓",
        ["2  Wann zielt der Gyro?"] = "2  Kiedy żyroskop celuje?",
        ["Nur per Taste"] = "Tylko przyciskiem",
        ["Beim Zielen (ZL/LT)"] = "Przy celowaniu (ZL/LT)",
        ["„Beim Zielen“: nur solange ZL (linker Trigger) gehalten wird – wie in vielen Shootern."] =
            "„Przy celowaniu”: tylko dopóki ZL (lewy spust) jest wciśnięty – jak w wielu strzelankach.",
        ["3  Empfindlichkeit"] = "3  Czułość",
        ["Voller Ausschlag ab"] = "Pełne wychylenie od",
        ["Kleinerer Wert bei „Voller Ausschlag ab“ = empfindlicher. „Mindestausschlag“ überwindet die Totzone des Spiels."] =
            "Niższa wartość przy „Pełne wychylenie od” = czułeś. „Minimalne wychylenie” pokonuje martwą strefę gry.",
        ["Mitte"] = "Środek",
        ["Vorschau: Fadenkreuz folgt dem Controller (unabhängig von Schritt 2)."] = "Podgląd: celownik podąża za kontrolerem (niezależnie od kroku 2).",
        ["Keine Bewegungsdaten"] = "Brak danych ruchu",
        ["Controller gekoppelt"] = "Kontroler sparowany",
        ["Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive: SYNC-Taste drücken, bis die Lichter laufen.\n" +
         "Wii-Fernbedienung: Batteriefach öffnen und die rote SYNC-Taste drücken.\n" +
         "Wii U Pro Controller: die SYNC-Taste auf der Unterseite drücken.\n" +
         "Danach verbindet sich der Controller künftig per Tastendruck."] =
            "Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive: naciśnij przycisk SYNC, aż światełka zaczną biec.\n" +
            "Pilot Wii: otwórz schowek na baterie i naciśnij czerwony przycisk SYNC.\n" +
            "Wii U Pro Controller: naciśnij przycisk SYNC na spodzie.\n" +
            "Potem kontroler łączy się jednym naciśnięciem.",
        ["Suche … SYNC-Taste drücken (Xbox: Kopplungstaste oben halten, PlayStation: PS + Teilen/Create halten)."] =
            "Szukanie … naciśnij przycisk SYNC (Xbox: przytrzymaj górny przycisk parowania; PlayStation: przytrzymaj PS + Share/Create).",
        ["Kein Controller im Kopplungsmodus gefunden. SYNC-Taste drücken und erneut versuchen."] =
            "Nie znaleziono kontrolera w trybie parowania. Naciśnij SYNC i spróbuj ponownie.",
        ["Darstellung:"] = "Wygląd:",
        ["Dunkel"] = "Ciemny",
        ["Hell"] = "Jasny",
        ["Wie Windows"] = "Jak Windows",
        ["Mica-Effekt in der Titelleiste (ab Windows 11)"] = "Efekt Mica na pasku tytułu (od Windows 11)",

        // ---------- Fehlerfälle und Hinweise ----------
        ["Bluetooth ist ausgeschaltet."] = "Bluetooth jest wyłączony.",
        ["Dieser Bluetooth-Adapter unterstützt kein Bluetooth LE."] = "Ten adapter Bluetooth nie obsługuje Bluetooth LE.",
        ["Bluetooth-Suche konnte nicht starten."] = "Nie można rozpocząć wyszukiwania Bluetooth.",
        ["Bluetooth in den Windows-Einstellungen einschalten."] = "Włącz Bluetooth w ustawieniach Windows.",
        ["Controller per USB funktionieren weiterhin."] = "Kontrolery przez USB nadal działają.",
        ["Für Switch-2-Controller wird ein Adapter mit Bluetooth 4.0 oder neuer gebraucht."] = "Kontrolery Switch 2 wymagają adaptera z Bluetooth 4.0 lub nowszym.",
        ["Andere Controller und USB funktionieren weiterhin."] = "Inne kontrolery i USB nadal działają.",
        ["Bluetooth-Adapter (z. B. USB-Stick) einstecken bzw. Bluetooth in Windows aktivieren."] =
            "Podłącz adapter Bluetooth (np. dongle USB) lub włącz Bluetooth w Windows.",
        ["Bluetooth ist bereit – Controller können verbunden werden."] = "Bluetooth gotowy – można łączyć kontrolery.",
        ["Bluetooth-Einstellungen öffnen"] = "Otwórz ustawienia Bluetooth",
        ["ViGEmBus-Treiber fehlt – ohne ihn kann kein virtueller Controller erzeugt werden."] =
            "Brak sterownika ViGEmBus – bez niego nie można utworzyć wirtualnego kontrolera.",
        ["Bitte das Setup erneut ausführen."] = "Uruchom ponownie instalator.",
        ["Das Programm schließen oder in Steam die Nintendo-Unterstützung abschalten."] =
            "Zamknij ten program lub wyłącz obsługę Nintendo w Steam.",
        ["Erst einen anderen trennen."] = "Najpierw rozłącz inny.",
        ["Tipp: Bluetooth-Stick per Verlängerung näher an den Controller, weg von USB-3-Anschlüssen und Funkkopfhörern."] =
            "Wskazówka: przybliż dongle Bluetooth do kontrolera przedłużaczem, z dala od portów USB 3 i słuchawek bezprzewodowych.",
        ["Controller mit dem PC gekoppelt – ab jetzt reicht ein Tastendruck."] = "Kontroler sparowany z komputerem – od teraz wystarczy jedno naciśnięcie.",
        ["Hinweis: Um ihn wieder an der Switch 2 zu nutzen, dort einmal kurz SYNC drücken."] =
            "Uwaga: aby znów używać go na Switch 2, naciśnij raz krótko SYNC na konsoli.",
        ["Dieser Bluetooth-Adapter unterstützt kein Bluetooth LE"] = "Ten adapter Bluetooth nie obsługuje Bluetooth LE",
        ["Erst IR-Kamera bzw. Ring-Con ausschalten (sie nutzen denselben Zusatzprozessor wie der NFC-Leser)."] =
            "Najpierw wyłącz kamerę IR lub Ring-Con (używają tego samego koprocesora co czytnik NFC).",
        ["Erst die IR-Kamera schließen (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "Najpierw zamknij kamerę IR (Ring-Con i kamera IR używają tego samego koprocesora).",
        ["Erst den Ring-Con ausschalten (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "Najpierw wyłącz Ring-Con (Ring-Con i kamera IR używają tego samego koprocesora).",
        ["amiibo zu früh entfernt"] = "amiibo odsunięte zbyt wcześnie",
        ["MCU startet nicht"] = "koprocesor nie uruchamia się",
        ["NFC-Modus nicht aktiv"] = "tryb NFC nieaktywny",
        ["Kopplung fehlgeschlagen – Details im Protokoll."] = "Parowanie nie powiodło się – szczegóły w dzienniku.",

        // ---------- Kopplungsdaten (Switch-SD-Karte, anderer PC) ----------
        ["Kopplungsdaten"] = "Dane parowania",
        ["Kopplungen übernehmen oder weitergeben"] = "Przejmij lub udostępnij parowania",
        ["Kopplungsdaten von der Switch übernehmen"] = "Przejmij dane parowania ze Switcha",
        ["Von der Switch-SD-Karte (Bluepick_RCM/hekate) oder von einem anderen PC übernehmen, oder für einen anderen PC exportieren."] =
            "Przejmij z karty SD Switcha (Bluepick_RCM/hekate) lub z innego komputera, albo wyeksportuj dla innego komputera.",
        ["Bei Switch-SD-Karte nachfragen"] = "Pytaj przy włożonej karcie SD Switcha",
        ["Steckt eine SD-Karte der Switch im PC (Kartenleser oder hekate „USB Tools“), bietet N-Connect die Übernahme an. Die Karte wird nur gelesen."] =
            "Gdy karta SD Switcha jest w komputerze (czytnik kart lub hekate „USB Tools”), N-Connect proponuje przejęcie. Karta jest tylko odczytywana.",
        ["Switch-SD-Karte erkannt"] = "Wykryto kartę SD Switcha",
        ["Kopplungsdaten der Controller gefunden – klicken, um sie anzusehen und zu übernehmen."] =
            "Znaleziono dane parowania kontrolerów – kliknij, aby je zobaczyć i przejąć.",
        ["Klicken, um Kopplungsdaten der Controller zu übernehmen."] = "Kliknij, aby przejąć dane parowania kontrolerów.",
        ["Controller-Kopplungen von der Switch-SD-Karte oder von einem anderen PC übernehmen – oder für einen anderen PC exportieren. Es werden nur Einstellungen von N-Connect geändert; Windows und der Bluetooth-Adapter bleiben unverändert."] =
            "Przejmij parowania kontrolerów z karty SD Switcha lub z innego komputera – albo wyeksportuj je dla innego komputera. Zmieniane są tylko ustawienia N-Connect; Windows i adapter Bluetooth pozostają bez zmian.",
        ["Spieler-Reihenfolge – Spieler 1 ist für Windows, Steam und Spiele der erste Controller. Mit ‹ › umsortieren."] =
            "Kolejność graczy – gracz 1 jest pierwszym kontrolerem dla Windows, Steam i gier. Zmień kolejność za pomocą ‹ ›.",
        ["Von der Switch-SD-Karte"] = "Z karty SD Switcha",
        ["Mit Bluepick_RCM oder hekate erstellte Kopplungsdaten (switchroot/joycon_mac.ini)"] =
            "Dane parowania utworzone przez Bluepick_RCM lub hekate (switchroot/joycon_mac.ini)",
        ["Einlesen …"] = "Wczytaj …",
        ["Von einem anderen PC"] = "Z innego komputera",
        ["Mit N-Connect exportierte Datei (*.ncpair)"] = "Plik wyeksportowany przez N-Connect (*.ncpair)",
        ["Datei öffnen …"] = "Otwórz plik …",
        ["Inhalt"] = "Zawartość",
        ["Weitergeben und sichern"] = "Udostępnij i zabezpiecz",
        ["Für einen anderen PC exportieren"] = "Eksportuj dla innego komputera",
        ["Bekannte Controller und Einstellungen je Controller, optional mit Passwort"] =
            "Znane kontrolery i ustawienia na kontroler, opcjonalnie z hasłem",
        ["Sicherung wiederherstellen"] = "Przywróć kopię zapasową",
        ["Vor jedem „Übernehmen“ wird automatisch eine Sicherung angelegt"] = "Przed każdym „Zastosuj” automatycznie tworzona jest kopia zapasowa",
        ["Wiederherstellen …"] = "Przywróć …",
        ["Bluetooth-Adapter dieses PCs"] = "Adapter Bluetooth tego komputera",
        ["wird ermittelt …"] = "wykrywanie …",
        ["nicht gefunden"] = "nie znaleziono",
        ["Quelle wählen: Switch-SD-Karte (mit Bluepick_RCM oder hekate erstellte Kopplungsdaten) oder eine Datei von einem anderen PC."] =
            "Wybierz źródło: karta SD Switcha (dane parowania utworzone przez Bluepick_RCM lub hekate) albo plik z innego komputera.",
        ["Keine Switch-SD-Karte gefunden. SD-Karte in den Kartenleser stecken oder die Switch per hekate („USB Tools“ → „SD Card“) als Laufwerk verbinden.\n\nOrdner selbst auswählen?"] =
            "Nie znaleziono karty SD Switcha. Włóż kartę SD do czytnika lub podłącz Switcha jako dysk przez hekate („USB Tools” → „SD Card”).\n\nWybrać folder ręcznie?",
        ["Stammordner der Switch-SD-Karte wählen"] = "Wybierz folder główny karty SD Switcha",
        ["Switch-SD-Karte:"] = "Karta SD Switcha:",
        ["Auf der Karte liegen keine Kopplungsdaten (switchroot/joycon_mac.ini)."] = "Karta nie zawiera danych parowania (switchroot/joycon_mac.ini).",
        ["So erstellst du sie: Joy-Con an die Switch stecken, Bluepick_RCM starten und „Dump Joy-Con BT pairing → SD“ (oder FULL AUTO) wählen. Alternativ in hekate: Nyx → Konsole → „Dump Joy-Con BT“."] =
            "Aby je utworzyć: podłącz Joy-Con do Switcha, uruchom Bluepick_RCM i wybierz „Dump Joy-Con BT pairing → SD” (lub FULL AUTO). Alternatywnie w hekate: Nyx → Console → „Dump Joy-Con BT”.",
        ["Gefunden wurde eine Bluepick-Sicherung des Bluetooth-Speichers (8000000000000050.bin). Sie ist ein Switch-Speicherabbild und kann hier nicht ausgewertet werden."] =
            "Znaleziono kopię zapasową Bluepick pamięci Bluetooth (8000000000000050.bin). To obraz pamięci Switcha i nie może zostać tutaj odczytany.",
        ["Bluetooth-Adresse der Switch:"] = "Adres Bluetooth Switcha:",
        ["Gefundene Controller:"] = "Znalezione kontrolery:",
        ["mit der Switch gekoppelt"] = "sparowany ze Switchem",
        ["zuletzt mit einem anderen Gerät gekoppelt (nicht der Switch)"] = "ostatnio sparowany z innym urządzeniem (nie ze Switchem)",
        ["Joy-Con (L)"] = "Joy-Con (L)",
        ["Joy-Con (R)"] = "Joy-Con (P)",
        ["HORI-Controller (links)"] = "Kontroler HORI (lewy)",
        ["HORI-Controller (rechts)"] = "Kontroler HORI (prawy)",
        ["Hinweis: Pro Controller stehen nur im Bluetooth-Speicher der Switch (8000000000000050.bin); dieses Speicherabbild kann N-Connect nicht auswerten."] =
            "Uwaga: Pro Controllery widnieją tylko w pamięci Bluetooth Switcha (8000000000000050.bin); N-Connect nie może odczytać tego obrazu pamięci.",
        ["Was diese Daten können – und was nicht:"] = "Co te dane umożliwiają – a czego nie:",
        ["Die Daten zeigen, welche Controller mit deiner Switch gekoppelt sind und an welche Bluetooth-Adresse sie gebunden sind."] =
            "Dane pokazują, które kontrolery są sparowane z twoim Switchem i z jakim adresem Bluetooth są powiązane.",
        ["Ein Switch-1-Controller verbindet sich auf Tastendruck nur mit dem Gerät, dessen Adresse er gespeichert hat – hier mit der Switch. Der Bluetooth-Adapter des PCs hat eine andere Adresse, deshalb kann Windows diese Kopplung nicht einfach weiterverwenden."] =
            "Kontroler Switch 1 łączy się jednym naciśnięciem tylko z urządzeniem, którego adres zapamiętał – tutaj ze Switchem. Adapter Bluetooth komputera ma inny adres, więc Windows nie może po prostu ponownie użyć tego parowania.",
        ["Die Adresse des PC-Adapters zu ändern, unterstützt N-Connect bewusst nicht (herstellerabhängig, riskant und nicht vorgesehen)."] =
            "N-Connect celowo nie obsługuje zmiany adresu adaptera komputera (zależy od producenta, ryzykowne i nieprzewidziane).",
        ["Windows bietet keinen offiziellen Weg, fremde Kopplungsschlüssel einzutragen: Sie liegen in einem Teil der Registrierung, auf den nur das System zugreifen darf. N-Connect ändert dort nichts."] =
            "Windows nie oferuje oficjalnego sposobu dodawania obcych kluczy parowania: znajdują się w części rejestru zarezerwowanej dla systemu. N-Connect niczego tam nie zmienia.",
        ["So klappt der Wechsel am einfachsten: am PC den Controller einmal per SYNC-Taste in den Windows-Bluetooth-Einstellungen koppeln. Zurück an der Switch die Joy-Con an die Konsole stecken bzw. den Pro Controller per USB-Kabel anschließen – dann sind sie ohne Menü wieder mit der Switch gekoppelt."] =
            "Najprostszy sposób na zmianę: na komputerze sparuj kontroler raz przyciskiem SYNC w ustawieniach Bluetooth Windows. Wracając do Switcha, włóż Joy-Con do konsoli lub podłącz Pro Controllera kablem USB – będą ponownie sparowane bez menu.",
        ["„Übernehmen“ merkt sich diese Controller in N-Connect (Liste bekannter Controller, Zuordnung zur Switch). Kopplungsschlüssel werden nicht gespeichert."] =
            "„Zastosuj” zapamiętuje te kontrolery w N-Connect (lista znanych kontrolerów, powiązanie ze Switchem). Klucze parowania nie są zapisywane.",
        ["N-Connect-Kopplungsdaten"] = "Dane parowania N-Connect",
        ["Kopplungsdaten von einem anderen PC öffnen"] = "Otwórz dane parowania z innego komputera",
        ["Die Datei ist zu groß."] = "Plik jest zbyt duży.",
        ["Keine Kopplungsdaten-Datei."] = "To nie jest plik danych parowania.",
        ["Die Datei stammt von einer neueren N-Connect-Version."] = "Plik pochodzi z nowszej wersji N-Connect.",
        ["Die Datei ist mit einem Passwort geschützt."] = "Plik jest zabezpieczony hasłem.",
        ["Falsches Passwort oder die Datei wurde verändert."] = "Błędne hasło lub plik został zmieniony.",
        ["Die Datei ist beschädigt."] = "Plik jest uszkodzony.",
        ["Datei von:"] = "Plik od:",
        ["Bluetooth-Adapter dort:"] = "Adapter Bluetooth tam:",
        ["Bluetooth-Adapter hier:"] = "Adapter Bluetooth tutaj:",
        ["gekoppelt mit der Switch"] = "sparowany ze Switchem",
        ["gekoppelt mit dem anderen PC"] = "sparowany z innym komputerem",
        ["Weitere Einstellungen je Controller:"] = "Dalsze ustawienia na kontroler:",
        ["Was du erwarten kannst:"] = "Czego się spodziewać:",
        ["Gleiche Adapter-Adresse (z. B. derselbe USB-Bluetooth-Stick umgesteckt): Switch-2-Controller verbinden sich hier auf Tastendruck wie am anderen PC."] =
            "Ten sam adres adaptera (np. ta sama przełożona przejściówka Bluetooth USB): kontrolery Switch 2 łączą się tutaj jednym naciśnięciem jak na drugim komputerze.",
        ["Switch-1-Controller (Pro Controller, Joy-Con) brauchen zusätzlich die Kopplung in Windows. Die kann N-Connect nicht übertragen – einmal per SYNC-Taste koppeln."] =
            "Kontrolery Switch 1 (Pro Controller, Joy-Con) potrzebują dodatkowo parowania w Windows. N-Connect nie może go przenieść – sparuj raz przyciskiem SYNC.",
        ["Anderer Bluetooth-Adapter: Controller verbinden sich auf Tastendruck nur mit dem Gerät, mit dem sie zuletzt gekoppelt wurden. Hier einmal SYNC drücken – danach verbinden sie sich mit diesem PC (am anderen PC dann wieder per SYNC)."] =
            "Inny adapter Bluetooth: kontrolery łączą się jednym naciśnięciem tylko z urządzeniem, z którym ostatnio były sparowane. Naciśnij raz SYNC tutaj – potem łączą się z tym komputerem (na drugim komputerze znów przez SYNC).",
        ["Tipp: Wer denselben USB-Bluetooth-Stick zwischen den PCs umsteckt, nimmt die Adresse mit – Switch-2-Controller verbinden sich dann an beiden PCs ohne SYNC."] =
            "Wskazówka: kto przekłada ten sam dongle Bluetooth USB między komputerami, zabiera adres ze sobą – kontrolery Switch 2 łączą się wtedy na obu komputerach bez SYNC.",
        ["Übernommen werden die Einstellungen je Controller (Joy-Con einzeln/hochkant, Gyro-Kalibrierung) und die Liste bekannter Controller."] =
            "Przenoszone są ustawienia na kontroler (Joy-Con pojedynczo/pionowo, kalibracja żyroskopu) oraz lista znanych kontrolerów.",
        ["Die Datei enthält Kopplungsschlüssel. Windows bietet keinen offiziellen Weg, sie einzutragen – N-Connect übernimmt sie deshalb nicht."] =
            "Plik zawiera klucze parowania. Windows nie oferuje oficjalnego sposobu ich dodania – N-Connect ich więc nie przejmuje.",
        ["„Übernehmen“ ergänzt die Controller-Listen und Einstellungen von N-Connect (nichts wird gelöscht). Vorher wird eine Sicherung angelegt."] =
            "„Zastosuj” uzupełnia listy kontrolerów i ustawienia N-Connect (nic nie jest usuwane). Wcześniej tworzona jest kopia zapasowa.",
        ["Kopplungsdaten in N-Connect übernehmen? Vorher wird eine Sicherung der Einstellungen angelegt."] =
            "Przejąć dane parowania do N-Connect? Wcześniej zostanie utworzona kopia zapasowa ustawień.",
        ["Nichts zu ändern – diese Daten sind schon übernommen."] = "Nic do zmiany – te dane zostały już przejęte.",
        ["Übernommen. Die Sicherung lässt sich hier über „Sicherung wiederherstellen“ zurückholen."] =
            "Przejęto. Kopię zapasową można przywrócić tutaj przez „Przywróć kopię zapasową”.",
        ["Sicherung der Einstellungen"] = "Kopia zapasowa ustawień",
        ["Die Sicherung ist beschädigt und wurde nicht übernommen."] = "Kopia zapasowa jest uszkodzona i nie została zastosowana.",
        ["Alle Einstellungen durch diese Sicherung ersetzen?"] = "Zastąpić wszystkie ustawienia tą kopią zapasową?",
        ["Sicherung wiederhergestellt."] = "Kopia zapasowa przywrócona.",
        ["Kopplungsdaten für einen anderen PC speichern"] = "Zapisz dane parowania dla innego komputera",
        ["Gespeichert. Die Datei am anderen PC in N-Connect unter „Joy-Con & Wii“ → „Kopplungsdaten“ → „Von einem anderen PC“ öffnen."] =
            "Zapisano. Na drugim komputerze otwórz plik w N-Connect w „Joy-Con i Wii” → „Dane parowania” → „Z innego komputera”.",
        ["Kopplungsdaten exportieren"] = "Eksportuj dane parowania",
        ["Passwort eingeben"] = "Wprowadź hasło",
        ["Passwort (optional). Ohne Passwort steht der Inhalt lesbar in der Datei. Mit Kopplungsschlüsseln ist ein Passwort Pflicht."] =
            "Hasło (opcjonalne). Bez hasła zawartość jest czytelna w pliku. Przy kluczach parowania hasło jest wymagane.",
        ["Passwort"] = "Hasło",
        ["Passwort wiederholen"] = "Powtórz hasło",
        ["Kopplungsschlüssel der Switch-Controller mitnehmen"] = "Dołącz klucze parowania kontrolerów Switch",
        ["Kopplungsschlüssel mitnehmen (erst Switch-SD-Karte einlesen)"] = "Dołącz klucze parowania (najpierw wczytaj kartę SD Switcha)",
        ["Die Passwörter stimmen nicht überein."] = "Hasła nie są zgodne.",
        ["Mit Schlüsseln: Passwort mit mindestens 8 Zeichen."] = "Z kluczami: hasło co najmniej 8-znakowe.",
        ["Mindestens 8 Zeichen."] = "Co najmniej 8 znaków.",
        ["Ohne Passwort."] = "Bez hasła.",
    };

    /// <summary>Meldungen mit Platzhaltern (Polnisch).</summary>
    private static readonly (Regex Pattern, Func<Match, string> Replace)[] PatternsPl =
    [
        (Re(@"^Allgemeiner Wert \((?<v>.+)\) – Regler verschieben für einen eigenen$"), m => $"Wartość ogólna ({m.Groups["v"]}) – przesuń suwak dla własnej"),
        (Re(@"^Eigener Wert · allgemein: (?<v>.+)$"), m => $"Wartość własna · ogólna: {m.Groups["v"]}"),
        (Re(@"^Spieler (?<n>\d+)  ·  (?<k>.+?)(?<rest>(  ·  .*)?)$"), m => $"Gracz {m.Groups["n"]}  ·  {N(m, "k")}{T(m.Groups["rest"].Value)}"),
        (Re(@"^  ·  Gyro-Maus(?<r>.*)$"), m => "  ·  Mysz żyroskopowa" + T(m.Groups["r"].Value)),
        (Re(@"^  ·  Gyro-Stick$"), _ => "  ·  Gałka żyroskopowa"),
        (Re(@"^Spieler (?<n>\d+) · (?<k>.+?) (?<b>\d+ %.*)?$"), m => $"Gracz {m.Groups["n"]} · {N(m, "k")} {m.Groups["b"]}"),
        (Re(@"^(?<k>.+) verbunden \(Spieler (?<n>\d+)\)$"), m => $"{N(m, "k")} połączony (gracz {m.Groups["n"]})"),
        (Re(@"^Spieler (?<n>\d+) – tauschen mit (?<k>.+)$"), m => $"Gracz {m.Groups["n"]} – zamień z {N(m, "k")}"),
        (Re(@"^Spieler (?<n>\d+) – frei$"), m => $"Gracz {m.Groups["n"]} – wolne"),
        (Re(@"^Spieler (?<n>\d+)$"), m => $"Gracz {m.Groups["n"]}"),
        (Re(@"^Xbox 360 · Platz (?<n>\d+)$"), m => $"Xbox 360 · miejsce {m.Groups["n"]}"),
        (Re(@"^noch (?<n>\d+) s$"), m => $"jeszcze {m.Groups["n"]} s"),
        (Re(@"^Fertig – (?<n>\d+) Controller verbunden$"), m => $"Gotowe – połączono {m.Groups["n"]} kontroler(y/ów)"),
        (Re(@"^✓ (?<k>.+) verbunden – Spieler (?<n>\d+)$"), m => $"✓ {N(m, "k")} połączony – gracz {m.Groups["n"]}"),
        (Re(@"^Spieler (?<n>\d+)  ·  (?<v>.+)$"), m => $"Gracz {m.Groups["n"]}  ·  {m.Groups["v"]}"),
        (Re(@"^Gekoppelt: (?<k>.+) – verbindet gleich …$"), m => $"Sparowano: {m.Groups["k"]} – łączenie …"),
        (Re(@"^Ins Spiel wechseln … (?<n>\d+)$"), m => $"Przejdź do gry … {m.Groups["n"]}"),
        (Re(@"^(?<k>.+) ist jetzt Spieler (?<n>\d+)$"), m => $"{N(m, "k")} jest teraz graczem {m.Groups["n"]}"),
        (Re(@"^Spieler (?<a>\d+) und (?<b>\d+) getauscht$"), m => $"Gracze {m.Groups["a"]} i {m.Groups["b"]} zamienieni"),
        (Re(@"^Name für (?<k>.+) \(leer = Standardname\):$"), m => $"Nazwa dla {N(m, "k")} (puste = nazwa domyślna):"),
        (Re(@"^(?<k>.+) \(Joy-Con-Paar\)$"), m => $"{m.Groups["k"]} (para Joy-Con)"),
        (Re(@"^Joy-Con zusammengefasst \(Spieler (?<n>\d+)\)$"), m => $"Joy-Con połączone (gracz {m.Groups["n"]})"),
        (Re(@"^Joy-Con getrennt – (?<k>.+) ist jetzt Spieler (?<n>\d+)$"), m => $"Joy-Con rozdzielony – {N(m, "k")} jest teraz graczem {m.Groups["n"]}"),
        (Re(@"^Spieler (?<n>\d+): Akku (?<k>.+) fast leer \((?<p>\d+) %\) – bitte aufladen$"),
            m => $"Gracz {m.Groups["n"]}: bateria {N(m, "k")} prawie pusta ({m.Groups["p"]} %) – naładuj"),
        (Re(@"^Spieler (?<n>\d+): nach (?<m>\d+) min ohne Eingabe getrennt$"),
            m => $"Gracz {m.Groups["n"]}: rozłączono po {m.Groups["m"]} min bez czynności"),
        (Re(@"^Profil „(?<p>.+)“ aktiv$"), m => $"Profil „{ProfileName(m.Groups["p"].Value)}” aktywny"),
        (Re(@"^Profil: (?<p>.+)$"), m => $"Profil: {ProfileName(m.Groups["p"].Value)}"),
        (Re(@"^Profil „(?<p>.+)“ löschen\?$"), m => $"Usunąć profil „{m.Groups["p"]}”?"),
        (Re(@"^Profil „(?<p>.+)“ importiert(?<r>.*)$"), m => $"Profil „{m.Groups["p"]}” zaimportowany" + m.Groups["r"].Value.Replace("aktiv bei:", "aktywny przy:")),
        (Re(@"^⬇ Neue Version (?<v>.+) herunterladen …$"), m => $"⬇ Pobierz nową wersję {m.Groups["v"]} …"),
        (Re(@"^Version (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Herunterladen\.$"),
            m => $"Wersja {m.Groups["v"]} jest dostępna (zainstalowana: {m.Groups["i"]}). Kliknij, aby pobrać."),
        (Re(@"^Version (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Installieren\.$"),
            m => $"Wersja {m.Groups["v"]} jest dostępna (zainstalowana: {m.Groups["i"]}). Kliknij, aby zainstalować."),
        (Re(@"^⬇ Auf Version (?<v>.+) aktualisieren …$"), m => $"⬇ Aktualizuj do wersji {m.Groups["v"]} …"),
        (Re(@"^Lade Version (?<v>.+) herunter …$"), m => $"Pobieranie wersji {m.Groups["v"]} …"),
        (Re(@"^HidHide (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Installieren\.$"),
            m => $"HidHide {m.Groups["v"]} jest dostępny (zainstalowany: {m.Groups["i"]}). Kliknij, aby zainstalować."),
        (Re(@"^Lade HidHide (?<v>.+) herunter …$"), m => $"Pobieranie HidHide {m.Groups["v"]} …"),
        (Re(@"^(?<t>.+) · (?<r>\d+) Berichte/s$"), m => $"{T(m.Groups["t"].Value)} · {m.Groups["r"]} raportów/s"),
        (Re(@"^(?<p>\d+ %)(?<v>  \(.*\))?  ⚡ lädt$"), m => $"{m.Groups["p"]}{m.Groups["v"]}  ⚡ ładowanie"),
        (Re(@"^Speichern fehlgeschlagen: (?<e>.*)$"), m => $"Zapisywanie nie powiodło się: {m.Groups["e"]}"),
        (Re(@"^Lesen fehlgeschlagen: (?<e>.*)$"), m => $"Odczyt nie powiódł się: {m.Groups["e"]}"),
        (Re(@"^amiibo konnte nicht gelesen werden: (?<e>.*)$"), m => $"Nie można odczytać amiibo: {T(m.Groups["e"].Value)}"),
        (Re(@"^Gekoppelt: (?<k>.+)$"), m => $"Sparowano: {m.Groups["k"]}"),
        (Re(@"^Gefunden: (?<k>.+) – kopple …$"), m => $"Znaleziono: {m.Groups["k"]} – parowanie …"),
        (Re(@"^amiibo erkannt \((?<u>.+)\) – lese …$"), m => $"Wykryto amiibo ({m.Groups["u"]}) – odczyt …"),
        (Re(@"^(?<n>\d+) Minuten$"), m => $"{m.Groups["n"]} minut"),
        (Re(@"^✓ (?<n>\d+) Schritte, Dauer (?<ms>\d+) ms$"), m => $"✓ {m.Groups["n"]} kroków, razem {m.Groups["ms"]} ms"),
        (Re(@"^Controller-Taste „(?<b>.+)“:\nJetzt die gewünschte Taste oder Tastenkombination drücken\.$"),
            m => $"Przycisk kontrolera „{T(m.Groups["b"].Value)}”:\nNaciśnij teraz żądany klawisz lub skrót."),
        (Re(@"^Solange „(?<b>.+)“ gehalten wird, wird diese Taste schnell wiederholt gedrückt\n\(Geschwindigkeit unter 5\. „Turbo“\):$"),
            m => $"Dopóki „{T(m.Groups["b"].Value)}” jest wciśnięty, ten przycisk powtarza się szybko\n(prędkość w pkt 5. „Turbo”):"),
        (Re(@"^Ring-Con: (?<e>.*)$"), m => $"Ring-Con: {T(m.Groups["e"].Value)}"),
        (Re(@"^⌨  Taste: (?<k>.+)$"), m => $"⌨  Klawisz: {m.Groups["k"]}"),
        (Re(@"^🔁  Turbo: Taste (?<k>.+)$"), m => $"🔁  Turbo: klawisz {m.Groups["k"]}"),
        (Re(@"^🔁  Turbo: (?<k>.+)$"), m => $"🔁  Turbo: {T(m.Groups["k"].Value)}"),
        (Re(@"^⏯  Makro: (?<k>.+)$"), m => $"⏯  Makro: {m.Groups["k"]}"),
        (Re(@"^Tastatur: (?<k>.+)$"), m => $"Klawiatura: {m.Groups["k"]}"),
        (Re(@"^Gamepad: (?<k>.+)$"), m => $"Gamepad: {m.Groups["k"]}"),
        (Re(@"^(?<k>.+)  \(verbunden\)$"), m => $"{N(m, "k")}  (połączony)"),
        (Re(@"^Bluetooth nicht verfügbar: (?<e>.*)$"), m => $"Bluetooth niedostępny: {m.Groups["e"]}"),
        (Re(@"^(?<k>.+) per USB ist von einem anderen Programm belegt \(z\. B\. Steam\)\.$"),
            m => $"{N(m, "k")} przez USB jest zajęty przez inny program (np. Steam)."),
        (Re(@"^Schon (?<n>\d+) Controller verbunden – (?<k>.+) wird nicht verwendet\.$"),
            m => $"Już {m.Groups["n"]} kontrolerów połączonych – {N(m, "k")} nie jest używany."),
        (Re(@"^(?<k>.+): schwache Bluetooth-Verbindung \((?<r>\d+) statt 33–60 Berichte/s\)\.$"),
            m => $"{N(m, "k")}: słabe połączenie Bluetooth ({m.Groups["r"]} zamiast 33–60 raportów/s)."),
        (Re(@"^(?<k>.+) getrennt$"), m => $"{N(m, "k")} rozłączony"),
    ];
}
