using System.Text.RegularExpressions;

namespace Switch2Pro.Bridge;

/// <summary>Feste Texte Deutsch → Französisch. Schlüssel bleiben die deutschen Originaltexte.</summary>
internal static partial class Tr
{
    private static readonly Dictionary<string, string> TextsFr = new(StringComparer.Ordinal)
    {
        // ---------- Fenster, Reiter, Abschnitte ----------
        ["Controller"] = "Manettes",
        ["Einstellungen (optional)"] = "Paramètres (facultatif)",
        ["1. Windows und Spiele sehen den Controller als …"] = "1. Windows et les jeux voient la manette comme …",
        ["2. Tasten A/B/X/Y"] = "2. Boutons A/B/X/Y",
        ["3. Vibration, Sticks, Verbinden, Gyro-Maus"] = "3. Vibration, sticks, connexion, souris gyro",
        ["4. Joy-Con"] = "4. Joy-Con",
        ["4. Joy-Con und Wii"] = "4. Joy-Con et Wii",
        ["Wii-Fernbedienung: Zeiger (Sensorleiste) steuert die Maus"] = "Télécommande Wii : le pointeur (barre de détection) déplace la souris",
        ["Zeiger"] = "Pointeur",
        ["kein Zeiger – Sensorleiste nicht im Blick"] = "pas de pointeur : barre de détection hors de vue",
        ["5. Zielen, Sticks, Trigger, Turbo"] = "5. Visée, sticks, gâchettes, turbo",
        ["6. Tastenbelegung und Profile  (Taste → Gamepad, Tastatur, Maus, Gyro-Maus, Shift-Ebene)"] =
            "6. Attribution des boutons et profils  (bouton → manette, clavier, souris, souris gyro, couche Shift)",
        ["Xbox-360-Controller  (empfohlen – läuft mit fast allen Spielen)"] = "Manette Xbox 360  (recommandée – fonctionne avec presque tous les jeux)",
        ["PlayStation DualShock 4  (mit Bewegungssteuerung/Gyro – für Steam && Emulatoren)"] =
            "PlayStation DualShock 4  (avec contrôle gyroscopique – pour Steam et les émulateurs)",
        ["Xbox-Belegung  (nach Position: untere Taste = A)"] = "Disposition Xbox  (par position : bouton du bas = A)",
        ["Nintendo-Belegung  (nach Beschriftung: A bleibt A)"] = "Disposition Nintendo  (par libellé : A reste A)",
        ["Vibration"] = "Vibration",
        ["Stärke:"] = "Intensité :",
        ["Stick-Totzone (alle Controller):"] = "Zone morte du stick (toutes les manettes) :",
        ["Beim Verbinden kurz vibrieren"] = "Vibrer brièvement à la connexion",
        ["Meldung bei Verbinden"] = "Notification de connexion",
        ["Wer meldet, wenn ein Controller verbunden oder getrennt wird."] = "Choisissez qui notifie lorsqu’une manette se connecte ou se déconnecte.",
        ["„N-Connect“ zeigt den echten Controller-Namen und schaltet die Gerätemeldungen von Windows ab."] = "\"N-Connect\" affiche le vrai nom de la manette et désactive les notifications de périphériques de Windows.",
        ["N-Connect (empfohlen)"] = "N-Connect (recommandé)",
        ["N-Connect und Windows"] = "N-Connect et Windows",
        ["Keine"] = "Aucune",
        ["Gekoppelte Controller per Tastendruck verbinden (ohne SYNC)"] = "Connecter les manettes appairées d'une pression sur un bouton (sans SYNC)",
        ["Automatisch mit Windows starten"] = "Démarrer automatiquement avec Windows",
        ["Gyro für Emulatoren bereitstellen (Cemuhook/DSU, Port 26760 – wirkt nach Neustart)"] =
            "Fournir le gyroscope aux émulateurs (Cemuhook/DSU, port 26760 – actif après redémarrage)",
        ["Beim Start nach neuer Version suchen (GitHub)"] = "Rechercher une nouvelle version au démarrage (GitHub)",
        ["Ohne Eingabe automatisch trennen nach:"] = "Déconnecter automatiquement sans action après :",
        ["Gyro-Maus-Geschwindigkeit:"] = "Vitesse de la souris gyro :",
        ["Sprache / Language:"] = "Langue / Language :",
        ["Automatisch (wie Windows)"] = "Automatique (comme Windows)",
        ["nie"] = "jamais",
        ["Zwei Joy-Con automatisch zu einem Controller zusammenfassen"] = "Combiner automatiquement deux Joy-Con en une seule manette",
        ["Gyro beim Paar vom:"] = "Gyroscope de la paire depuis :",
        ["rechter Joy-Con (wie Switch)"] = "Joy-Con droit (comme sur Switch)",
        ["linker Joy-Con"] = "Joy-Con gauche",
        ["Joy-Con 2 als Maus, wenn er auf dem Tisch liegt"] = "Joy-Con 2 comme souris posé sur la table",
        ["Mausgeschwindigkeit:"] = "Vitesse de la souris :",
        ["Maus: links/rechts umkehren"] = "Souris : inverser gauche/droite",
        ["Maus: hoch/runter umkehren"] = "Souris : inverser haut/bas",
        ["Wie an der Switch: SL + SR eine Sekunde halten löst einen Joy-Con aus dem Paar. L am linken und R am rechten einzelnen Joy-Con gleichzeitig drücken verbindet sie wieder zum Paar. Die Wahl wird je Joy-Con gemerkt (auch nach dem nächsten Verbinden). Im Mausmodus: R/L = Linksklick, ZR/ZL = Rechtsklick, Stick drücken = Mittelklick, Stick hoch/runter = Scrollen."] =
            "Comme sur Switch : maintenir SL + SR une seconde détache un Joy-Con de la paire. Appuyer en même temps sur L à gauche et R à droite les réunit. Le choix est mémorisé par Joy-Con (aussi à la prochaine connexion). En mode souris : R/L = clic gauche, ZR/ZL = clic droit, presser le stick = clic central, stick haut/bas = défilement.",
        ["Gyro als rechter Stick:"] = "Gyroscope comme stick droit :",
        ["aus (nur per Taste „Gyro-Stick“)"] = "désactivé (seulement via un bouton « stick gyro »)",
        ["immer"] = "toujours",
        ["beim Zielen (solange ZL / linker Trigger gedrückt)"] = "en visant (tant que ZL / gâchette gauche est maintenu)",
        ["hoch/runter umkehren"] = "inverser haut/bas",
        ["Empfindlichkeit:"] = "Sensibilité :",
        ["Mindestausschlag:"] = "Déflexion minimale :",
        ["Stick-Kennlinie:"] = "Courbe du stick :",
        ["Turbo (pro Sekunde):"] = "Turbo (par seconde) :",
        ["Analoge Trigger (GameCube) – Totzone:"] = "Gâchettes analogiques (GameCube) – zone morte :",
        ["voll gedrückt ab:"] = "enfoncé à fond à partir de :",
        ["Profil:"] = "Profil :",
        ["Neu …"] = "Nouveau …",
        ["Umbenennen …"] = "Renommer …",
        ["Löschen"] = "Supprimer",
        ["Exportieren …"] = "Exporter …",
        ["Importieren …"] = "Importer …",
        ["Aktiv bei Programm:"] = "Actif avec le programme :",
        ["Programm wählen …"] = "Choisir un programme …",
        ["Standard"] = "Par défaut",
        ["Standard gilt immer, wenn kein anderes Profil passt"] = "Par défaut s'applique quand aucun autre profil ne convient",
        ["z. B. Cemu.exe, Ryujinx.exe"] = "p. ex. Cemu.exe, Ryujinx.exe",
        ["Ein eigenes Profil wird automatisch aktiv, solange eines seiner Programme im Vordergrund ist (sonst gilt „Standard“). Im Infobereich-Menü lässt sich ein Profil auch fest wählen."] =
            "Un profil personnalisé devient actif automatiquement tant qu'un de ses programmes est au premier plan (sinon « Par défaut » s'applique). Un profil peut aussi être fixé dans le menu de la zone de notification.",
        ["Controller:"] = "Manette :",
        ["Eigene Stick-Totzone für diesen Controller:"] = "Zone morte de stick propre à cette manette :",
        ["Normale Belegung"] = "Attribution normale",
        ["Shift-Ebene (gilt, solange eine Taste mit „Shift-Ebene“ gehalten wird)"] = "Couche Shift (s'applique tant qu'un bouton « couche Shift » est maintenu)",
        ["Alles auf Standard"] = "Tout réinitialiser",
        ["Schließen"] = "Fermer",
        ["wie normale Belegung"] = "comme l'attribution normale",

        // ---------- Belegungsziele und Vorlagen ----------
        ["— keine Funktion —"] = "— aucune fonction —",
        ["A (Xbox) / Kreuz (PS)"] = "A (Xbox) / Croix (PS)",
        ["B (Xbox) / Kreis (PS)"] = "B (Xbox) / Rond (PS)",
        ["X (Xbox) / Viereck (PS)"] = "X (Xbox) / Carré (PS)",
        ["Y (Xbox) / Dreieck (PS)"] = "Y (Xbox) / Triangle (PS)",
        ["Ansicht (Back) / Share"] = "Affichage (Back) / Share",
        ["Menü (Start) / Options"] = "Menu (Start) / Options",
        ["Xbox-Taste / PS-Taste"] = "Bouton Xbox / bouton PS",
        ["Linker Stick-Klick"] = "Clic du stick gauche",
        ["Rechter Stick-Klick"] = "Clic du stick droit",
        ["Steuerkreuz hoch"] = "Croix directionnelle haut",
        ["Steuerkreuz runter"] = "Croix directionnelle bas",
        ["Steuerkreuz links"] = "Croix directionnelle gauche",
        ["Steuerkreuz rechts"] = "Croix directionnelle droite",
        ["Touchpad-Klick (nur DualShock 4)"] = "Clic du pavé tactile (DualShock 4 uniquement)",
        ["🖱  Maus: Linksklick"] = "🖱  Souris : clic gauche",
        ["🖱  Maus: Rechtsklick"] = "🖱  Souris : clic droit",
        ["🖱  Maus: Mittelklick"] = "🖱  Souris : clic central",
        ["🎯  Gyro-Maus (solange gehalten)"] = "🎯  Souris gyro (tant que maintenu)",
        ["🎯  Gyro-Maus ein/aus"] = "🎯  Souris gyro activer/désactiver",
        ["🎯  Gyro als rechter Stick (solange gehalten)"] = "🎯  Gyroscope comme stick droit (tant que maintenu)",
        ["🎯  Gyro als rechter Stick ein/aus"] = "🎯  Gyroscope comme stick droit activer/désactiver",
        ["⇧  Shift-Ebene (solange gehalten)"] = "⇧  Couche Shift (tant que maintenu)",
        ["🔁  Turbo / Dauerfeuer …"] = "🔁  Turbo / tir rapide …",
        ["⏯  Makro (Tastenfolge) …"] = "⏯  Macro (séquence de boutons) …",
        ["📷  Bildschirmfoto speichern (Win+Druck)"] = "📷  Enregistrer une capture d'écran (Win+Impr. écran)",
        ["📷  Bildschirmausschnitt (Win+Umschalt+S)"] = "📷  Capture partielle (Win+Maj+S)",
        ["⏺  Letzte 30 Sekunden aufnehmen (Win+Alt+G)"] = "⏺  Enregistrer les 30 dernières secondes (Win+Alt+G)",
        ["⏺  Aufnahme starten/stoppen (Win+Alt+R)"] = "⏺  Démarrer/arrêter l'enregistrement (Win+Alt+R)",
        ["🎮  Xbox Game Bar (Win+G)"] = "🎮  Xbox Game Bar (Win+G)",
        ["🔊  Lauter"] = "🔊  Augmenter le volume",
        ["🔉  Leiser"] = "🔉  Baisser le volume",
        ["⏯  Wiedergabe/Pause"] = "⏯  Lecture/pause",
        ["⌨  Andere Taste / Tastenkombination aufnehmen …"] = "⌨  Enregistrer une autre touche / combinaison de touches …",

        // ---------- Tastennamen ----------
        ["+ (Plus)"] = "+ (Plus)",
        ["− (Minus)"] = "− (Moins)",
        ["Aufnahme"] = "Capture",
        ["GL (Rücktaste links)"] = "GL (bouton arrière gauche)",
        ["GR (Rücktaste rechts)"] = "GR (bouton arrière droit)",
        ["Linker Stick drücken"] = "Presser le stick gauche",
        ["Rechter Stick drücken"] = "Presser le stick droit",
        ["Stick drücken"] = "Presser le stick",
        ["A (groß, unten)"] = "A (grand, en bas)",
        ["B (links)"] = "B (gauche)",
        ["X (rechts)"] = "X (droite)",
        ["Y (oben)"] = "Y (haut)",
        ["L (ganz durchgedrückt)"] = "L (enfoncé à fond)",
        ["R (ganz durchgedrückt)"] = "R (enfoncé à fond)",
        ["untere Taste (quer)"] = "bouton du bas (à plat)",
        ["rechte Taste (quer)"] = "bouton droit (à plat)",
        ["linke Taste (quer)"] = "bouton gauche (à plat)",
        ["obere Taste (quer)"] = "bouton du haut (à plat)",
        ["1 (quer) / Classic Y"] = "1 (à plat) / Classic Y",
        ["2 (quer) / Classic B"] = "2 (à plat) / Classic B",
        ["B (Abzug) / Classic ZR"] = "B (gâchette) / Classic ZR",
        ["Kreuz (unten)"] = "Croix (bas)",
        ["Kreis (rechts)"] = "Rond (droite)",
        ["Viereck (links)"] = "Carré (gauche)",
        ["Dreieck (oben)"] = "Triangle (haut)",
        ["PS-Taste"] = "Bouton PS",
        ["Touchpad-Klick"] = "Clic du pavé tactile",
        ["Mikro stumm"] = "Micro muet",
        ["Fn links (Edge)"] = "Fn gauche (Edge)",
        ["Rücktaste links (Edge)"] = "Bouton arrière gauche (Edge)",
        ["Rücktaste rechts (Edge)"] = "Bouton arrière droit (Edge)",
        ["L3 (Stick drücken)"] = "L3 (presser le stick)",
        ["R3 (Stick drücken)"] = "R3 (presser le stick)",
        ["Ansicht/Zurück"] = "Affichage/Retour",
        ["Menü/Start"] = "Menu/Start",
        ["Xbox-Taste"] = "Bouton Xbox",

        // ---------- Controller-Namen ----------
        ["Wii-Fernbedienung"] = "Télécommande Wii",
        ["Xbox-Controller"] = "Manette Xbox",
        ["Xbox-Controller (Microsoft)"] = "Manette Xbox (Microsoft)",
        ["XInput (USB, Bluetooth oder Xbox-Adapter)"] = "XInput (USB, Bluetooth ou adaptateur Xbox)",

        // ---------- Übersicht / Karten ----------
        ["Trennen"] = "Déconnecter",
        ["Vibrieren"] = "Vibrer",
        ["Gyro kalibrieren"] = "Étalonner le gyroscope",
        ["Ruhig liegen lassen …"] = "Laisser immobile …",
        ["Kalibriert ✓"] = "Étalonné ✓",
        ["Hochkant halten"] = "Tenir à la verticale",
        ["Quer halten"] = "Tenir à plat",
        ["Joy-Con trennen"] = "Séparer les Joy-Con",
        ["Zum Paar verbinden"] = "Combiner en paire",
        ["Joy-Con trennen – beide werden einzelne Controller"] = "Séparer les Joy-Con – les deux deviennent des manettes individuelles",
        ["Zum Paar verbinden – sucht einen freien Joy-Con"] = "Combiner en paire – cherche un Joy-Con libre",
        ["Doppelt angezeigt? Verstecken"] = "Affiché en double ? Masquer",
        ["amiibo lesen"] = "Lire un amiibo",
        ["Ring-Con ein"] = "Activer le Ring-Con",
        ["Ring-Con aus"] = "Désactiver le Ring-Con",
        ["Ring-Con wird gesucht …"] = "Recherche du Ring-Con …",
        ["IR-Kamera"] = "Caméra IR",
        ["Akku"] = "Batterie",
        ["Verbindung"] = "Connexion",
        ["Adresse"] = "Adresse",
        ["Seriennummer"] = "Numéro de série",
        ["Griff"] = "Support",
        ["Maus"] = "Souris",
        ["Gedrückt"] = "Enfoncé",
        ["unbekannt"] = "inconnu",
        ["Charging Grip – GL/GR aktiv"] = "Charging Grip – GL/GR actifs",
        ["aktiv (liegt auf dem Tisch)"] = "actif (posé sur la table)",
        ["bereit – zum Benutzen auf den Tisch legen"] = "prêt – posez-le sur la table pour l'utiliser",
        ["Bewegungssensor: keine Daten"] = "Capteur de mouvement : aucune donnée",
        ["quer halten: Steuerkreuz links,\n1 und 2 rechts"] = "à plat : croix directionnelle à gauche,\n1 et 2 à droite",

        // ---------- Tooltips ----------
        ["Verbindung trennen. Der Controller verbindet sich beim nächsten Tastendruck wieder."] =
            "Déconnecter. La manette se reconnecte à la prochaine pression.",
        ["Controller kurz vibrieren lassen – zeigt, welcher Controller dieser Spieler ist."] =
            "Faire vibrer brièvement la manette – montre quelle manette appartient à ce joueur.",
        ["Controller ruhig auf den Tisch legen und klicken: misst den Gyro-Nullpunkt neu (gegen Abdriften)."] =
            "Poser la manette immobile sur la table et cliquer : mesure à nouveau le point zéro du gyroscope (contre la dérive).",
        ["Einzelnen Joy-Con quer (wie an der Switch) oder hochkant halten – wird je Joy-Con gemerkt. Hochkant gilt die Tastenbelegung von „Joy-Con-Paar“."] =
            "Tenir un Joy-Con seul à plat (comme sur Switch) ou à la verticale – mémorisé par Joy-Con. À la verticale, l'attribution « paire Joy-Con » s'applique.",
        ["Versteckt den per USB angeschlossenen Controller vor Spielen (HidHide), damit sie nur den virtuellen Xbox-Controller sehen."] =
            "Masque la manette branchée en USB aux jeux (HidHide) pour qu'ils ne voient que la manette Xbox virtuelle.",
        ["amiibo mit dem NFC-Leser lesen und als Datei (.bin) speichern – z. B. für Emulatoren."] =
            "Lire un amiibo avec le lecteur NFC et l'enregistrer en fichier (.bin) – p. ex. pour les émulateurs.",
        ["Ring-Con am rechten Joy-Con ein-/ausschalten: zusammendrücken = rechter Trigger, auseinanderziehen = linker Trigger. Beim Einschalten den Ring nicht berühren."] =
            "Activer/désactiver le Ring-Con du Joy-Con droit : presser = gâchette droite, écarter = gâchette gauche. Ne pas toucher l'anneau en l'activant.",
        ["Live-Bild der IR-Kamera im rechten Joy-Con anzeigen."] = "Afficher l'image en direct de la caméra IR du Joy-Con droit.",
        ["Links = empfindlicher (kleine Drehung, großer Ausschlag), rechts = ruhiger."] = "Gauche = plus sensible (petite rotation, grande déflexion), droite = plus calme.",
        ["Mindestausschlag des Sticks bei Bewegung – überwindet die Totzone des Spiels."] = "Déflexion minimale du stick en mouvement – dépasse la zone morte du jeu.",
        ["Mitte = linear. Rechts = feiner um die Mitte (präzises Zielen), links = schneller."] = "Milieu = linéaire. Droite = plus fin autour du centre (visée précise), gauche = plus rapide.",
        ["So weit lässt sich ein analoger Trigger drücken, bevor er wirkt."] = "Jusqu'où une gâchette analogique peut être enfoncée avant d'agir.",
        ["Ab hier gilt der Trigger als ganz gedrückt (100 = erst am Anschlag)."] = "À partir d'ici, la gâchette compte comme enfoncée à fond (100 = seulement en butée).",
        ["Wie oft pro Sekunde Tasten mit „Turbo“ auslösen."] = "Combien de fois par seconde les boutons « turbo » se déclenchent.",

        // ---------- Infobereich ----------
        ["ViGEmBus-Treiber fehlt"] = "Pilote ViGEmBus manquant",
        ["ViGEmBus herunterladen …"] = "Télécharger ViGEmBus …",
        ["Verbinde …"] = "Connexion …",
        ["Kein Controller – SYNC-Taste am Controller kurz drücken"] = "Aucune manette – appuyez brièvement sur le bouton SYNC de la manette",
        ["Ausgabe als"] = "Sortie en tant que",
        ["Xbox-360-Controller (empfohlen)"] = "Manette Xbox 360 (recommandée)",
        ["DualShock 4 (mit Gyro für Steam/Emulatoren)"] = "DualShock 4 (avec gyro pour Steam/émulateurs)",
        ["Tastenbelegung"] = "Attribution des boutons",
        ["Xbox-Belegung (untere Taste = A)"] = "Disposition Xbox (bouton du bas = A)",
        ["Switch-2-Pro-Belegung (A bleibt A)"] = "Disposition Nintendo (A reste A)",
        ["Automatisch (nach Spiel/Programm)"] = "Automatique (selon le jeu/programme)",
        ["Mit Windows starten"] = "Démarrer avec Windows",
        ["Einstellungen …"] = "Paramètres …",
        ["Kurzanleitung"] = "Guide rapide",
        ["Protokoll öffnen"] = "Ouvrir le journal",
        ["Beenden"] = "Quitter",
        ["N-Connect: warte auf Controller (SYNC drücken)"] = "N-Connect : en attente d'une manette (appuyez sur SYNC)",
        ["N-Connect: ViGEmBus fehlt"] = "N-Connect : ViGEmBus manquant",
        ["Neue Version verfügbar"] = "Nouvelle version disponible",
        ["Einstellungen fehlerhaft"] = "Paramètres endommagés",
        ["settings.json konnte nicht gelesen werden – es gelten die Standardwerte."] = "settings.json n'a pas pu être lu – les valeurs par défaut s'appliquent.",
        ["Ohne ViGEmBus kann kein virtueller Controller erzeugt werden. Bitte das Setup erneut ausführen oder ViGEmBus installieren (Rechtsklick auf das Symbol → ViGEmBus herunterladen)."] =
            "Sans ViGEmBus, aucune manette virtuelle ne peut être créée. Relancez l'installation ou installez ViGEmBus (clic droit sur l'icône → Télécharger ViGEmBus).",

        // ---------- Dialoge ----------
        ["Tastatur-Taste festlegen"] = "Définir une touche du clavier",
        ["Übernehmen"] = "Appliquer",
        ["Abbrechen"] = "Annuler",
        ["Ja"] = "Oui",
        ["Nein"] = "Non",
        ["Turbo / Dauerfeuer"] = "Turbo / tir rapide",
        ["Tastatur-Taste aufnehmen …"] = "Enregistrer une touche du clavier …",
        ["Makro (Tastenfolge)"] = "Macro (séquence de boutons)",
        ["Ungültig – bitte Schreibweise prüfen (siehe oben)."] = "Non valide – vérifiez la syntaxe (voir ci-dessus).",
        ["Neues Profil"] = "Nouveau profil",
        ["Name des Profils (z. B. der Spielname):"] = "Nom du profil (p. ex. le nom du jeu) :",
        ["Profil umbenennen"] = "Renommer le profil",
        ["Neuer Name:"] = "Nouveau nom :",
        ["Ein Profil mit diesem Namen gibt es schon."] = "Un profil avec ce nom existe déjà.",
        ["Die Datei enthält kein gültiges Controller-Profil."] = "Le fichier ne contient pas de profil de manette valide.",
        ["Alle Einstellungen und Tastenbelegungen auf Standard zurücksetzen?"] = "Réinitialiser tous les paramètres et attributions de boutons ?",
        ["Suche …"] = "Recherche …",
        ["Kein Bluetooth-Adapter gefunden."] = "Aucun adaptateur Bluetooth trouvé.",
        ["IR-Kamera (Joy-Con R)"] = "Caméra IR (Joy-Con D)",
        ["Auflösung:"] = "Résolution :",
        ["40 × 30 (schnell)"] = "40 × 30 (rapide)",
        ["320 × 240 (langsam)"] = "320 × 240 (lent)",
        ["Kamera startet …"] = "Démarrage de la caméra …",
        ["läuft – Joy-Con auf eine Lichtquelle oder die Hand richten"] = "en marche – dirigez le Joy-Con vers une source de lumière ou votre main",
        ["Kamera startet nicht (Details im Protokoll)"] = "La caméra ne démarre pas (détails dans le journal)",
        ["Kein Ring-Con gefunden. Den rechten Joy-Con (Switch 1) fest in den Ring-Con schieben und erneut versuchen."] =
            "Aucun Ring-Con trouvé. Insérez fermement le Joy-Con droit (Switch 1) dans le Ring-Con et réessayez.",
        ["Kein amiibo erkannt. Bitte das amiibo flach an den NFC-Leser halten (Joy-Con: auf den rechten Stick, Pro Controller: auf das NFC-Logo) und erneut versuchen."] =
            "Aucun amiibo détecté. Tenez l'amiibo à plat contre le lecteur NFC (Joy-Con : sur le stick droit ; Pro Controller : sur le logo NFC) et réessayez.",
        ["NFC-Leser wird eingeschaltet …"] = "Activation du lecteur NFC …",
        ["amiibo an den Leser halten (rechter Stick des Joy-Con bzw. NFC-Logo des Pro Controllers) …"] =
            "Tenez l'amiibo contre le lecteur (stick droit du Joy-Con ou logo NFC du Pro Controller) …",
        ["amiibo speichern"] = "Enregistrer l'amiibo",
        ["Doppelte Controller verhindern"] = "Éviter les manettes en double",
        ["Dafür wird das kostenlose Programm HidHide gebraucht (von den Machern von ViGEmBus).\n\nJetzt die Download-Seite öffnen? Nach der Installation hier erneut klicken."] =
            "Le programme gratuit HidHide est nécessaire pour cela (des créateurs de ViGEmBus).\n\nOuvrir la page de téléchargement maintenant ? Cliquez ici à nouveau après l'installation.",
        ["HidHide konnte nicht eingerichtet werden (abgebrochen oder fehlgeschlagen). Details im Protokoll."] =
            "HidHide n'a pas pu être configuré (annulé ou échoué). Détails dans le journal.",
        ["Der Controller hat sich bewegt oder keine Bewegungsdaten geliefert.\nBitte flach auf den Tisch legen, nicht berühren und erneut versuchen."] =
            "La manette a bougé ou n'a pas fourni de données de mouvement.\nPosez-la à plat sur la table sans la toucher et réessayez.",
        ["Spiel oder Programm wählen"] = "Choisir un jeu ou un programme",
        ["Profil exportieren"] = "Exporter le profil",
        ["Profil importieren"] = "Importer le profil",
        ["Verstanden"] = "Compris",
        ["Einstellungen öffnen"] = "Ouvrir les paramètres",
        ["Willkommen"] = "Bienvenue",

        // ---------- Neues Hauptfenster (Navigation, Seiten, Zeilen) ----------
        ["Allgemein"] = "Général",
        ["Sticks & Vibration"] = "Sticks et vibration",
        ["Gyro & Maus"] = "Gyroscope et souris",
        ["Joy-Con & Wii"] = "Joy-Con et Wii",
        ["Ein"] = "Oui",
        ["Aus"] = "Non",
        ["Verbundene Controller mit Live-Anzeige. Über „Einstellungen“ an einem Controller passt du genau diesen an."] =
            "Manettes connectées avec affichage en direct. Avec « Paramètres » sur une manette, vous ajustez exactement celle-ci.",
        ["Jede Taste kann ein Gamepad-Knopf, eine Tastaturtaste, ein Mausklick, Turbo oder ein Makro sein. " +
         "Tipp: Drückst du eine Taste am Controller, wird ihre Zeile hervorgehoben."] =
            "Chaque bouton peut être un bouton de manette, une touche, un clic de souris, un turbo ou une macro. " +
            "Astuce : appuyez sur un bouton de la manette pour mettre sa ligne en surbrillance.",
        ["Profil"] = "Profil",
        ["Neu"] = "Nouveau",
        ["Umbenennen, löschen, exportieren, importieren"] = "Renommer, supprimer, exporter, importer",
        ["Ein eigenes Profil gilt automatisch, solange eines seiner Programme im Vordergrund ist – sonst „Standard“."] =
            "Un profil personnalisé s'applique automatiquement tant qu'un de ses programmes est au premier plan – sinon « Par défaut ».",
        ["Aktiv bei Programm"] = "Actif avec le programme",
        ["Programmdateien, bei denen dieses Profil gilt (mit Komma trennen)."] = "Fichiers de programme pour lesquels ce profil s'applique (séparer par des virgules).",
        ["Standard gilt für alle Programme"] = "Par défaut s'applique à tous les programmes",
        ["Wählen …"] = "Choisir …",
        ["Bearbeiten"] = "Modifier",
        ["Jeder Controller hat seine eigene Belegung."] = "Chaque manette a sa propre attribution.",
        ["Ebene"] = "Couche",
        ["Normal"] = "Normal",
        ["Shift-Ebene"] = "Couche Shift",
        ["Die Shift-Ebene gilt, solange eine Taste mit „Shift-Ebene“ gehalten wird."] = "La couche Shift s'applique tant qu'un bouton réglé sur « couche Shift » est maintenu.",
        ["Tasten"] = "Boutons",
        ["Standardwerte für alle Controller. Eigene Werte für einzelne Controller stellst du unten oder in der Übersicht ein."] =
            "Valeurs par défaut pour toutes les manettes. Définissez des valeurs propres par manette ci-dessous ou dans la vue d'ensemble.",
        ["Sticks"] = "Sticks",
        ["Totzone"] = "Zone morte",
        ["So weit lässt sich ein Stick bewegen, bevor er wirkt (gegen Abdriften)."] = "Jusqu'où un stick peut bouger avant de réagir (contre la dérive).",
        ["Kennlinie"] = "Courbe de réponse",
        ["„linear“ = gleichmäßig. Höher = feiner um die Mitte (präzises Zielen), niedriger = schneller."] =
            "« linéaire » = uniforme. Plus haut = plus fin autour du centre (visée précise), plus bas = plus rapide.",
        ["Analoge Trigger (GameCube)"] = "Gâchettes analogiques (GameCube)",
        ["So weit lässt sich ein Trigger drücken, bevor er wirkt."] = "Jusqu'où une gâchette peut être enfoncée avant de réagir.",
        ["Voll gedrückt ab"] = "Enfoncée à fond à partir de",
        ["Ab hier gilt der Trigger als ganz gedrückt (100 % = erst am Anschlag)."] = "À partir d'ici, la gâchette compte comme enfoncée à fond (100 % = seulement en butée).",
        ["Spiele dürfen den Controller vibrieren lassen."] = "Les jeux peuvent faire vibrer la manette.",
        ["Stärke"] = "Intensité",
        ["Turbo-Geschwindigkeit"] = "Vitesse du turbo",
        ["Wie oft pro Sekunde Tasten mit „Turbo“ auslösen."] = "Combien de fois par seconde les boutons « turbo » se déclenchent.",
        ["Eigene Werte je Controller"] = "Valeurs propres par manette",
        ["Werte nur für diesen Controller – ohne eigenen Wert gilt der allgemeine."] = "Valeurs pour cette manette uniquement – sans valeur propre, la valeur générale s'applique.",
        ["Bewegungssteuerung: Zielen per Gyro und den Controller als Maus nutzen."] = "Contrôle par mouvement : viser avec le gyroscope et utiliser la manette comme souris.",
        ["Gyro als rechter Stick"] = "Gyroscope comme stick droit",
        ["Modus"] = "Mode",
        ["Zum Zielen in Spielen ohne eigene Gyro-Steuerung. „Gyro-Stick“ kann auch einer Taste zugewiesen werden."] =
            "Pour viser dans les jeux sans contrôle gyro propre. « Stick gyro » peut aussi être assigné à un bouton.",
        ["Aus (nur per Taste „Gyro-Stick“)"] = "Désactivé (seulement via un bouton « stick gyro »)",
        ["Immer"] = "Toujours",
        ["Beim Zielen (solange ZL / LT gedrückt)"] = "En visant (tant que ZL / LT est maintenu)",
        ["Empfindlichkeit"] = "Sensibilité",
        ["Drehgeschwindigkeit für vollen Stick-Ausschlag – kleiner = empfindlicher."] = "Vitesse de rotation pour une déflexion complète du stick – plus bas = plus sensible.",
        ["Mindestausschlag"] = "Déflexion minimale",
        ["Überwindet die Stick-Totzone des Spiels bei kleinen Bewegungen."] = "Dépasse la zone morte du stick du jeu pour les petits mouvements.",
        ["Hoch/runter umkehren"] = "Inverser haut/bas",
        ["Links/rechts umkehren"] = "Inverser gauche/droite",
        ["Gyro-Maus"] = "Souris gyro",
        ["Geschwindigkeit"] = "Vitesse",
        ["Mauszeiger per Bewegung – über eine Taste mit „Gyro-Maus“ (Tastenbelegung)."] = "Pointeur de souris par le mouvement – via un bouton « souris gyro » (attribution des boutons).",
        ["Mausrichtung (Gyro-Maus und Joy-Con-Maus)"] = "Direction de la souris (souris gyro et souris Joy-Con)",
        ["Gyro-Funktionen einer Taste zuweisen"] = "Assigner des fonctions gyro à un bouton",
        ["Gyro-Maus oder Gyro-Stick ein/aus bzw. solange gehalten"] = "Souris gyro ou stick gyro activer/désactiver ou tant que maintenu",
        ["Joy-Con als Paar oder einzeln, Joy-Con 2 als Maus und Wii-Controller."] = "Joy-Con en paire ou seuls, Joy-Con 2 comme souris et manettes Wii.",
        ["Zu einem Controller zusammenfassen"] = "Combiner en une seule manette",
        ["Ein linker und ein rechter Joy-Con werden automatisch ein Paar."] = "Un Joy-Con gauche et un droit forment automatiquement une paire.",
        ["Gyro beim Paar vom"] = "Gyroscope de la paire depuis",
        ["Rechter Joy-Con (wie Switch)"] = "Joy-Con droit (comme sur Switch)",
        ["Linker Joy-Con"] = "Joy-Con gauche",
        ["Paar lösen oder verbinden"] = "Séparer ou réunir une paire",
        ["Einen Joy-Con quer halten und SL oder SR drücken löst ihn aus dem Paar. L am linken und R am rechten Joy-Con gleichzeitig drücken verbindet sie wieder. Die Wahl wird je Joy-Con gemerkt."] =
            "Tenir un Joy-Con à plat et appuyer sur SL ou SR le détache de la paire. Appuyer sur L à gauche et R à droite en même temps les réunit. Le choix est mémorisé par Joy-Con.",
        ["Joy-Con 2 als Maus"] = "Joy-Con 2 comme souris",
        ["Als Maus, wenn er auf dem Tisch liegt"] = "Comme souris posé sur la table",
        ["Joy-Con 2 auf die Seite legen und wie eine Maus schieben."] = "Posez le Joy-Con 2 sur le côté et faites-le glisser comme une souris.",
        ["Mausgeschwindigkeit"] = "Vitesse de la souris",
        ["Tasten im Mausmodus"] = "Boutons en mode souris",
        ["R/L = Linksklick, ZR/ZL = Rechtsklick, Stick drücken = Mittelklick, Stick hoch/runter = Scrollen."] =
            "R/L = clic gauche, ZR/ZL = clic droit, presser le stick = clic central, stick haut/bas = défilement.",
        ["Zeiger steuert die Maus"] = "Le pointeur déplace la souris",
        ["Wii-Fernbedienung auf die Sensorleiste richten, um den Mauszeiger zu bewegen."] = "Pointez la télécommande Wii vers la barre de détection pour déplacer le pointeur.",
        ["Wie Spiele die Controller sehen, Verbindung, Darstellung und Programm."] = "Comment les jeux voient les manettes, connexion, apparence et programme.",
        ["Ausgabe"] = "Sortie",
        ["Controller erscheint als"] = "La manette apparaît comme",
        ["Xbox 360 läuft mit fast allen Spielen. DualShock 4 bietet Bewegungssteuerung (Steam, Emulatoren)."] =
            "Xbox 360 fonctionne avec presque tous les jeux. DualShock 4 offre le contrôle par mouvement (Steam, émulateurs).",
        ["Xbox 360 läuft mit fast allen Spielen und Steam. DualShock 4 bietet zusätzlich Bewegungssteuerung (Steam, Emulatoren). Gilt für alle Controller ohne eigene Einstellung (Karte → Einstellungen → Tasten)."] =
            "Xbox 360 fonctionne avec presque tous les jeux et Steam. DualShock 4 ajoute le contrôle par mouvement (Steam, émulateurs). S'applique à toutes les manettes sans réglage propre (carte → Paramètres → Boutons).",
        ["Original-Controller verstecken"] = "Masquer les manettes d'origine",
        ["Controller verbinden"] = "Connecter des manettes",
        ["SYNC-Taste am Controller drücken – N-Connect findet und koppelt ihn selbst. Danach reicht künftig ein Tastendruck."] =
            "Appuyez sur le bouton SYNC de la manette – N-Connect la trouve et l'appaire tout seul. Ensuite, une pression suffit.",
        ["So kommt der Controller in den Kopplungsmodus"] = "Comment mettre la manette en mode appairage",
        ["Kurz die kleine SYNC-Taste drücken."] = "Appuyez brièvement sur le petit bouton SYNC.",
        ["SYNC-Taste drücken, bis die Lichter laufen."] = "Appuyez sur le bouton SYNC jusqu'à ce que les lumières défilent.",
        ["Batteriefach öffnen und die rote SYNC-Taste drücken."] = "Ouvrez le compartiment à piles et appuyez sur le bouton SYNC rouge.",
        ["Die SYNC-Taste auf der Unterseite drücken."] = "Appuyez sur le bouton SYNC en dessous.",
        ["PS + Teilen bzw. Create halten, bis die Lichtleiste schnell blinkt."] =
            "Maintenez PS + Share/Create jusqu'à ce que la barre lumineuse clignote rapidement.",
        ["Kopplungstaste oben halten, bis die Xbox-Taste blinkt."] = "Maintenez le bouton d'appairage du dessus jusqu'à ce que le bouton Xbox clignote.",
        ["Status"] = "État",
        ["Suche läuft …"] = "Recherche en cours …",
        ["Suche läuft – jetzt SYNC drücken …"] = "Recherche en cours – appuyez sur SYNC maintenant …",
        ["Weitere Controller? Einfach SYNC drücken."] = "D'autres manettes ? Appuyez simplement sur SYNC.",
        ["Wartet auf einen Controller im Kopplungsmodus."] = "En attente d'une manette en mode appairage.",
        ["Suche beendet"] = "Recherche terminée",
        ["Die Controller stehen in der Übersicht und verbinden sich künftig per Tastendruck."] =
            "Les manettes apparaissent dans la vue d'ensemble et se connecteront d'une pression.",
        ["Kein Controller im Kopplungsmodus gefunden. SYNC-Taste drücken und „Erneut suchen“ klicken."] =
            "Aucune manette en mode appairage trouvée. Appuyez sur SYNC et cliquez sur « Chercher à nouveau ».",
        ["Verbunden"] = "Connectée",
        ["Erneut suchen"] = "Chercher à nouveau",
        ["Fertig"] = "Terminé",
        ["Im Spiel"] = "Dans le jeu",
        ["Dreht …"] = "Rotation …",
        ["Testdrehung (360°)"] = "Rotation test (360°)",
        ["Testdrehung"] = "Rotation test",
        ["aus"] = "désactivé",
        ["Gyro-Beschleunigung"] = "Accélération gyro",
        ["Bei schneller Drehung"] = "En rotation rapide",
        ["Langsame Bewegungen bleiben fein, schnelle drehen weiter (wie JoyShockMapper). Voll ab 120 °/s, unter 20 °/s normal. Gilt für Gyro-Stick und Gyro-Maus."] =
            "Les mouvements lents restent précis, les rapides tournent plus (comme JoyShockMapper). Plein à partir de 120 °/s, normal sous 20 °/s. S'applique au stick gyro et à la souris gyro.",
        ["Flick-Stick (Spiele mit Maussteuerung)"] = "Flick stick (jeux avec contrôle souris)",
        ["Flick-Stick"] = "Flick stick",
        ["Rechten Stick in eine Richtung schieben = Kamera dreht sofort dorthin; am Rand drehen = Kamera dreht mit. Zielen dann per Gyro. Der rechte Stick geht nicht mehr ans Spiel."] =
            "Pousser le stick droit dans une direction = la caméra y tourne immédiatement ; le tourner sur le bord = la caméra suit. Viser ensuite au gyro. Le stick droit n'est plus envoyé au jeu.",
        ["Mausbewegung je Umdrehung"] = "Mouvement de souris par tour",
        ["Je Spiel einmal einstellen: „Testdrehung“ klicken, ins Spiel wechseln – nach 3 s dreht die Kamera einmal. Genau eine volle Drehung = richtig."] =
            "À régler une fois par jeu : cliquez sur « Rotation test », passez au jeu – après 3 s la caméra tourne une fois. Exactement un tour complet = correct.",
        ["Flick-Dauer"] = "Durée du flick",
        ["So lange dauert die Drehung beim Flick (0 = sofort)."] = "Durée de la rotation d'un flick (0 = instantané).",
        ["Gyro-Maus oder Gyro-Stick ein/aus bzw. solange gehalten, „Gyro anhalten“ (Ratchet: Controller zurückführen, ohne dass sich das Ziel bewegt)"] =
            "Souris gyro ou stick gyro activer/désactiver ou tant que maintenu, « suspendre le gyro » (ratchet : ramener la manette sans bouger la visée)",
        ["✋  Gyro anhalten (solange gehalten, „Ratchet“)"] = "✋  Suspendre le gyro (tant que maintenu, « ratchet »)",
        ["Spieler-LED und Lichtleiste vom Spiel"] = "LED joueur et barre lumineuse du jeu",
        ["Die Spieler-LEDs zeigen den Xbox-Platz, den Windows vergibt. Bei DualShock 4 steuert die Lichtleiste des Spiels die HOME-LED (Switch 1 Pro Controller, rechter Joy-Con)."] =
            "Les LED joueur indiquent la place Xbox attribuée par Windows. Sur DualShock 4, la barre lumineuse du jeu pilote la LED HOME (Pro Controller Switch 1, Joy-Con droit).",
        ["HidHide installieren …"] = "Installer HidHide …",
        ["Empfohlen: Steam und viele Spiele kennen Switch-1-, NSO- und USB-Controller selbst und sähen sie sonst doppelt. Läuft nach der Installation ohne Rückfrage (sonst fragt Windows nach Adminrechten)."] =
            "Recommandé : Steam et beaucoup de jeux reconnaissent eux-mêmes les manettes Switch 1, NSO et USB et les verraient sinon en double. Fonctionne sans demande après l'installation (sinon Windows demande les droits d'administrateur).",
        ["Steam und viele Spiele sehen Switch-1-, NSO- und USB-Controller sonst doppelt. Dafür wird das kostenlose HidHide gebraucht (bei der N-Connect-Installation dabei, hier nachträglich)."] =
            "Sinon, Steam et beaucoup de jeux voient les manettes Switch 1, NSO et USB en double. Il faut pour cela le gratuit HidHide (inclus dans l'installation de N-Connect, à installer ici après coup).",
        ["Erscheint als"] = "Apparaît comme",
        ["Wie allgemein"] = "Comme dans Général",
        ["Nur für diesen Controller. Xbox 360 läuft überall; DualShock 4 bringt zusätzlich Gyro nach Steam und in Emulatoren. „Wie allgemein“ folgt der Seite „Allgemein“."] =
            "Seulement pour cette manette. Xbox 360 fonctionne partout ; DualShock 4 ajoute le gyro dans Steam et les émulateurs. « Comme dans Général » suit la page « Général ».",
        ["Der echte Xbox-Controller – Spiele sehen ihn von Windows aus direkt. Belegungen hier wirken auf Sonderaktionen (Tastatur, Makros, Gyro), nicht auf den Controller selbst."] =
            "La vraie manette Xbox – les jeux la voient déjà directement depuis Windows. Les attributions ici agissent sur les actions spéciales (clavier, macros, gyro), pas sur la manette elle-même.",
        ["Steam und manche Spiele sehen diesen Controller sonst doppelt. Abhilfe: HidHide installieren (Seite „Allgemein“ → „Original-Controller verstecken“)."] =
            "Sinon, Steam et certains jeux voient cette manette en double. Solution : installer HidHide (page « Général » → « Masquer les manettes d'origine »).",
        ["Original-Controller vor Spielen versteckt. Steam bitte einmal neu starten – danach sieht es nur noch den virtuellen Controller."] =
            "Manettes d'origine masquées aux jeux. Redémarrez Steam une fois – ensuite il ne voit que la manette virtuelle.",
        ["Original-Controller vor Spielen versteckt – Steam und Spiele sehen nur noch den virtuellen Controller."] =
            "Manettes d'origine masquées aux jeux – Steam et les jeux ne voient désormais que la manette virtuelle.",
        ["Original-Controller nicht versteckt (Abfrage abgebrochen). Nachholen: Controller → Einstellungen → Extras → „Doppelt angezeigt?“."] =
            "Manettes d'origine non masquées (demande annulée). Pour plus tard : manette → Paramètres → Extras → « Affiché en double ? ».",
        ["Tastenanordnung A/B/X/Y"] = "Disposition des boutons A/B/X/Y",
        ["Xbox: nach Position (untere Taste = A). Nintendo: nach Beschriftung (A bleibt A)."] = "Xbox : par position (bouton du bas = A). Nintendo : par libellé (A reste A).",
        ["Verbinden"] = "Connexion",
        ["Per Tastendruck verbinden"] = "Connecter d'une pression",
        ["Gekoppelte Controller verbinden sich ohne SYNC-Taste."] = "Les manettes appairées se connectent sans le bouton SYNC.",
        ["Ohne Eingabe trennen nach"] = "Déconnecter sans action après",
        ["Spart Akku, wenn ein Controller liegen bleibt."] = "Économise la batterie quand une manette reste posée.",
        ["N-Connect startet unsichtbar im Infobereich."] = "N-Connect démarre discrètement dans la zone de notification.",
        ["Darstellung und Sprache"] = "Apparence et langue",
        ["Farbmodus"] = "Mode couleur",
        ["Mica-Effekt"] = "Effet Mica",
        ["Durchscheinende Titelleiste (ab Windows 11)."] = "Barre de titre translucide (Windows 11 et ultérieur).",
        ["Erweitert"] = "Avancé",
        ["Gyro für Emulatoren (DSU)"] = "Gyroscope pour émulateurs (DSU)",
        ["Cemuhook-Server auf Port 26760 – wirkt nach einem Neustart von N-Connect."] = "Serveur Cemuhook sur le port 26760 – actif après un redémarrage de N-Connect.",
        ["Nach Updates suchen"] = "Rechercher des mises à jour",
        ["Beim Start auf GitHub nach einer neuen Version suchen."] = "Rechercher une nouvelle version sur GitHub au démarrage.",
        ["Tastenbelegungen und Werte zurücksetzen. Gekoppelte Controller bleiben erhalten."] = "Réinitialiser les attributions et les valeurs. Les manettes appairées sont conservées.",
        ["Zurücksetzen"] = "Réinitialiser",

        // ---------- Controller-Karte ----------
        ["Einstellungen"] = "Paramètres",
        ["Tastenbelegung und Einstellungen nur für diesen Controller"] = "Attribution des boutons et paramètres pour cette manette uniquement",
        ["Feineinstellung"] = "Réglage fin",
        ["Gyro"] = "Gyroscope",
        ["Extras"] = "Extras",
        ["Belegung für alle Spiele (Standard) oder ein eigenes Profil."] = "Attribution pour tous les jeux (par défaut) ou un profil personnalisé.",
        ["Profile"] = "Profils",
        ["Profile anlegen, umbenennen, exportieren …"] = "Créer, renommer, exporter des profils …",
        ["Drück eine Taste am Controller – ihre Zeile leuchtet auf. ⌨ weist eine Tastaturtaste zu, ↺ setzt zurück."] =
            "Appuyez sur un bouton de la manette – sa ligne s'illumine. ⌨ assigne une touche du clavier, ↺ réinitialise.",
        ["Tastatur-Taste zuweisen: klicken und die gewünschte Taste oder Kombination drücken."] = "Assigner une touche du clavier : cliquez et appuyez sur la touche ou combinaison voulue.",
        ["Zurück auf die Standardbelegung"] = "Revenir à l'attribution par défaut",
        ["Ohne eigenen Wert gilt der allgemeine Wert der Seite „Sticks & Vibration“."] = "Sans valeur propre, la valeur générale de la page « Sticks et vibration » s'applique.",
        ["Stick-Totzone"] = "Zone morte du stick",
        ["Stick-Kennlinie"] = "Courbe du stick",
        ["Trigger-Totzone"] = "Zone morte de la gâchette",
        ["Trigger voll gedrückt ab"] = "Gâchette enfoncée à fond à partir de",
        ["Vibrationsstärke"] = "Intensité de la vibration",
        ["Gyro-Maus-Geschwindigkeit"] = "Vitesse de la souris gyro",
        ["Eigenen Wert entfernen – es gilt wieder der allgemeine Wert"] = "Supprimer la valeur propre – la valeur générale s'applique à nouveau",
        ["Kalibrieren"] = "Étalonner",
        ["Controller ruhig auf den Tisch legen und klicken: misst den Nullpunkt neu (gegen Abdriften)."] =
            "Poser la manette immobile sur la table et cliquer : mesure à nouveau le point zéro (contre la dérive).",
        ["Gyro als rechter Stick und Mausrichtung"] = "Gyroscope comme stick droit et direction de la souris",
        ["Gilt für alle Controller"] = "S'applique à toutes les manettes",
        ["Paar"] = "Paire",
        ["Joy-Con quer halten und SL oder SR drücken löst das Paar, L + R gleichzeitig verbindet es."] =
            "Tenir un Joy-Con à plat et appuyer sur SL ou SR sépare la paire ; L + R en même temps la réunit.",
        ["Haltung"] = "Orientation",
        ["Quer"] = "À plat",
        ["Hochkant"] = "À la verticale",
        ["Quer wie an der Switch oder hochkant – hochkant gilt die Belegung von „Joy-Con-Paar“."] =
            "À plat comme sur Switch ou à la verticale – à la verticale, l'attribution « paire Joy-Con » s'applique.",
        ["Mausmodus, Geschwindigkeit und Tasten"] = "Mode souris, vitesse et boutons",
        ["Lesen …"] = "Lire …",
        ["Einschalten"] = "Activer",
        ["Ausschalten"] = "Désactiver",
        ["Wird gesucht …"] = "Recherche …",
        ["Öffnen"] = "Ouvrir",
        ["Verstecken"] = "Masquer",
        ["amiibo an den NFC-Leser halten und als Datei (.bin) speichern – z. B. für Emulatoren."] =
            "Tenez un amiibo contre le lecteur NFC et enregistrez-le en fichier (.bin) – p. ex. pour les émulateurs.",
        ["Zusammendrücken = rechter Trigger, auseinanderziehen = linker Trigger. Beim Einschalten nicht berühren."] =
            "Presser = gâchette droite, écarter = gâchette gauche. Ne pas le toucher en l'activant.",
        ["Live-Bild der Infrarotkamera im rechten Joy-Con."] = "Image en direct de la caméra infrarouge du Joy-Con droit.",
        ["Doppelt angezeigt?"] = "Affiché en double ?",
        ["Versteckt den Original-Controller vor Steam und Spielen (HidHide) – sie sehen dann nur den virtuellen Controller."] =
            "Masque la manette d'origine à Steam et aux jeux (HidHide) – ils ne voient alors que la manette virtuelle.",
        ["bereit (auf den Tisch legen)"] = "prêt (posez-le sur la table)",
        ["amiibo-Abbild (*.bin)|*.bin"] = "Image amiibo (*.bin)|*.bin",
        ["Controller-Profil (*.ncprofile.json)|*.ncprofile.json|JSON (*.json)|*.json"] = "Profil de manette (*.ncprofile.json)|*.ncprofile.json|JSON (*.json)|*.json",
        ["Programme (*.exe)|*.exe"] = "Programmes (*.exe)|*.exe",
        ["Kein Controller verbunden\n\n" +
         "Switch-2-Controller: kurz die SYNC-Taste drücken – danach reicht ein beliebiger Tastendruck.\n" +
         "Switch-1-, NSO- und Wii-Controller: SYNC-Taste drücken – N-Connect koppelt sie selbst.\n" +
         "Oder hier gezielt suchen und koppeln:"] =
            "Aucune manette connectée\n\n" +
            "Manettes Switch 2 : appuyez brièvement sur le bouton SYNC – ensuite une pression suffit.\n" +
            "Manettes Switch 1, NSO et Wii : appuyez sur le bouton SYNC – N-Connect les appaire tout seul.\n" +
            "Ou cherchez et appairez directement ici :",
        ["Controller suchen …"] = "Chercher des manettes …",
        ["Kein Controller verbunden"] = "Aucune manette connectée",
        ["Switch-1-, NSO- und Wii-Controller suchen und koppeln (SYNC-Taste drücken)."] =
            "Chercher et appairer des manettes Switch 1, NSO et Wii (appuyez sur le bouton SYNC).",
        ["Neue Controller automatisch koppeln"] = "Appairer automatiquement les nouvelles manettes",
        ["Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive, Wii und PlayStation: einfach SYNC " +
         "drücken – kein Umweg über die Windows-Bluetooth-Einstellungen. Gesucht wird nur, solange niemand spielt."] =
            "Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive, Wii et PlayStation : appuyez simplement sur SYNC – " +
            "sans passer par les paramètres Bluetooth de Windows. La recherche n'a lieu que lorsque personne ne joue.",
        ["Gezielt suchen"] = "Recherche ciblée",
        ["Sucht eine Minute lang nach Controllern im Kopplungsmodus."] = "Cherche des manettes en mode appairage pendant une minute.",
        ["Controller koppeln …"] = "Appairer une manette …",
        ["Controller koppeln"] = "Appairer une manette",
        ["Linken Joy-Con umbenennen …"] = "Renommer le Joy-Con gauche …",
        ["Rechten Joy-Con umbenennen …"] = "Renommer le Joy-Con droit …",
        ["Controller umbenennen"] = "Renommer la manette",
        ["Spielerplatz"] = "Place du joueur",
        ["N-Connect aktualisieren"] = "Mettre à jour N-Connect",
        ["HidHide aktualisieren"] = "Mettre à jour HidHide",
        ["HidHide-Update verfügbar"] = "Mise à jour HidHide disponible",
        ["HidHide aktuell halten"] = "Garder HidHide à jour",
        ["Beim Start nach einer neuen HidHide-Version suchen. Installiert wird nur nach Rückfrage (geprüfter Download vom Hersteller, Neustart nötig)."] =
            "Rechercher une nouvelle version de HidHide au démarrage. Installation seulement après confirmation (téléchargement vérifié de l'éditeur, redémarrage requis).",
        ["Der Download hat nicht geklappt oder die Datei war fehlerhaft. Die Release-Seite im Browser öffnen?"] =
            "Le téléchargement a échoué ou le fichier était défectueux. Ouvrir la page de la version dans le navigateur ?",
        ["Alle Controller trennen"] = "Déconnecter toutes les manettes",
        ["Sticks kalibrieren"] = "Étalonner les sticks",
        ["Kalibrieren …"] = "Étalonner …",
        ["Gegen Drift oder zu kleinen Ausschlag: Mitte und Rand neu messen. Wird nur in N-Connect gespeichert, der Controller bleibt unverändert."] =
            "Contre la dérive ou une course trop courte : mesurer à nouveau le centre et le bord. Enregistré seulement dans N-Connect, la manette reste inchangée.",
        ["Linker Stick"] = "Stick gauche",
        ["Rechter Stick"] = "Stick droit",
        ["Stick"] = "Stick",
        ["Stick (linker Joy-Con)"] = "Stick (Joy-Con gauche)",
        ["Stick (rechter Joy-Con)"] = "Stick (Joy-Con droit)",
        ["Neu messen"] = "Mesurer à nouveau",
        ["Werkswerte"] = "Valeurs d'usine",
        ["Der Punkt zeigt, wo der Stick gerade steht. Steht er losgelassen nicht in der Mitte oder erreicht er den Kreis nicht, auf „Neu messen“ klicken."] =
            "Le point indique où se trouve le stick. S'il n'est pas centré une fois relâché ou n'atteint pas le cercle, cliquez sur « Mesurer à nouveau ».",
        ["Gilt gerade: eigene Kalibrierung."] = "Actuellement utilisé : étalonnage propre.",
        ["Gilt gerade: Werkswerte des Controllers."] = "Actuellement utilisé : valeurs d'usine de la manette.",
        ["1/2 – Stick loslassen und den Controller ruhig halten …"] = "1/2 – relâchez le stick et tenez la manette immobile …",
        ["2/2 – Stick bis zum Anschlag drücken und langsam ein- bis zweimal im Kreis drehen."] =
            "2/2 – poussez le stick à fond et tournez-le lentement en cercle une à deux fois.",
        ["Fertig. „Übernehmen“ speichert die neue Kalibrierung für diesen Controller."] = "Terminé. « Appliquer » enregistre le nouvel étalonnage pour cette manette.",
        ["Der Stick hat den Rand nicht erreicht. Bitte bis zum Anschlag drücken und erneut messen."] =
            "Le stick n'a pas atteint le bord. Poussez-le à fond et mesurez à nouveau.",
        ["Übernommen ✓ – gilt ab sofort."] = "Appliqué ✓ – actif dès maintenant.",
        ["Werkswerte des Controllers gelten wieder."] = "Les valeurs d'usine de la manette s'appliquent à nouveau.",
        ["Gyro einrichten"] = "Configurer le gyroscope",
        ["Einrichten …"] = "Configurer …",
        ["Zielen per Bewegung einrichten"] = "Configurer la visée par mouvement",
        ["Schritt für Schritt: Nullpunkt, wann der Gyro zielt, Empfindlichkeit – mit Vorschau."] =
            "Pas à pas : point zéro, quand le gyro vise, sensibilité – avec aperçu.",
        ["1  Nullpunkt"] = "1  Point zéro",
        ["Controller flach auf den Tisch legen, nicht berühren – verhindert, dass das Ziel von selbst wandert."] =
            "Posez la manette à plat sur la table sans la toucher – empêche la visée de dériver toute seule.",
        ["Nullpunkt messen"] = "Mesurer le point zéro",
        ["Der Controller hat sich bewegt – bitte flach hinlegen und erneut versuchen."] = "La manette a bougé – posez-la à plat et réessayez.",
        ["Nullpunkt gemessen ✓"] = "Point zéro mesuré ✓",
        ["2  Wann zielt der Gyro?"] = "2  Quand le gyro vise-t-il ?",
        ["Nur per Taste"] = "Bouton uniquement",
        ["Beim Zielen (ZL/LT)"] = "En visant (ZL/LT)",
        ["„Beim Zielen“: nur solange ZL (linker Trigger) gehalten wird – wie in vielen Shootern."] =
            "« En visant » : seulement tant que ZL (gâchette gauche) est maintenu – comme dans beaucoup de jeux de tir.",
        ["3  Empfindlichkeit"] = "3  Sensibilité",
        ["Voller Ausschlag ab"] = "Déflexion complète à partir de",
        ["Kleinerer Wert bei „Voller Ausschlag ab“ = empfindlicher. „Mindestausschlag“ überwindet die Totzone des Spiels."] =
            "Une valeur plus petite à « Déflexion complète à partir de » = plus sensible. « Déflexion minimale » dépasse la zone morte du jeu.",
        ["Mitte"] = "Centre",
        ["Vorschau: Fadenkreuz folgt dem Controller (unabhängig von Schritt 2)."] = "Aperçu : le réticule suit la manette (indépendamment de l'étape 2).",
        ["Keine Bewegungsdaten"] = "Aucune donnée de mouvement",
        ["Controller gekoppelt"] = "Manette appairée",
        ["Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive: SYNC-Taste drücken, bis die Lichter laufen.\n" +
         "Wii-Fernbedienung: Batteriefach öffnen und die rote SYNC-Taste drücken.\n" +
         "Wii U Pro Controller: die SYNC-Taste auf der Unterseite drücken.\n" +
         "Danach verbindet sich der Controller künftig per Tastendruck."] =
            "Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive : appuyez sur le bouton SYNC jusqu'à ce que les lumières défilent.\n" +
            "Télécommande Wii : ouvrez le compartiment à piles et appuyez sur le bouton SYNC rouge.\n" +
            "Wii U Pro Controller : appuyez sur le bouton SYNC en dessous.\n" +
            "Ensuite, la manette se connecte d'une pression.",
        ["Suche … SYNC-Taste drücken (Xbox: Kopplungstaste oben halten, PlayStation: PS + Teilen/Create halten)."] =
            "Recherche … appuyez sur le bouton SYNC (Xbox : maintenez le bouton d'appairage du dessus ; PlayStation : maintenez PS + Share/Create).",
        ["Kein Controller im Kopplungsmodus gefunden. SYNC-Taste drücken und erneut versuchen."] =
            "Aucune manette en mode appairage trouvée. Appuyez sur SYNC et réessayez.",
        ["Darstellung:"] = "Apparence :",
        ["Dunkel"] = "Sombre",
        ["Hell"] = "Clair",
        ["Wie Windows"] = "Comme Windows",
        ["Mica-Effekt in der Titelleiste (ab Windows 11)"] = "Effet Mica dans la barre de titre (Windows 11 et ultérieur)",

        // ---------- Fehlerfälle und Hinweise ----------
        ["Bluetooth ist ausgeschaltet."] = "Le Bluetooth est désactivé.",
        ["Dieser Bluetooth-Adapter unterstützt kein Bluetooth LE."] = "Cet adaptateur Bluetooth ne prend pas en charge Bluetooth LE.",
        ["Bluetooth-Suche konnte nicht starten."] = "La recherche Bluetooth n'a pas pu démarrer.",
        ["Bluetooth in den Windows-Einstellungen einschalten."] = "Activez le Bluetooth dans les paramètres Windows.",
        ["Controller per USB funktionieren weiterhin."] = "Les manettes en USB continuent de fonctionner.",
        ["Für Switch-2-Controller wird ein Adapter mit Bluetooth 4.0 oder neuer gebraucht."] = "Les manettes Switch 2 nécessitent un adaptateur Bluetooth 4.0 ou plus récent.",
        ["Andere Controller und USB funktionieren weiterhin."] = "Les autres manettes et l'USB continuent de fonctionner.",
        ["Bluetooth-Adapter (z. B. USB-Stick) einstecken bzw. Bluetooth in Windows aktivieren."] =
            "Branchez un adaptateur Bluetooth (p. ex. une clé USB) ou activez le Bluetooth dans Windows.",
        ["Bluetooth ist bereit – Controller können verbunden werden."] = "Le Bluetooth est prêt – des manettes peuvent être connectées.",
        ["Bluetooth-Einstellungen öffnen"] = "Ouvrir les paramètres Bluetooth",
        ["ViGEmBus-Treiber fehlt – ohne ihn kann kein virtueller Controller erzeugt werden."] =
            "Pilote ViGEmBus manquant – sans lui aucune manette virtuelle ne peut être créée.",
        ["Bitte das Setup erneut ausführen."] = "Relancez l'installation.",
        ["Das Programm schließen oder in Steam die Nintendo-Unterstützung abschalten."] =
            "Fermez ce programme ou désactivez la prise en charge Nintendo dans Steam.",
        ["Erst einen anderen trennen."] = "Déconnectez d'abord une autre manette.",
        ["Tipp: Bluetooth-Stick per Verlängerung näher an den Controller, weg von USB-3-Anschlüssen und Funkkopfhörern."] =
            "Astuce : rapprochez la clé Bluetooth de la manette avec une rallonge, loin des ports USB 3 et des casques sans fil.",
        ["Controller mit dem PC gekoppelt – ab jetzt reicht ein Tastendruck."] = "Manette appairée au PC – désormais une pression suffit.",
        ["Hinweis: Um ihn wieder an der Switch 2 zu nutzen, dort einmal kurz SYNC drücken."] =
            "Remarque : pour l'utiliser à nouveau sur Switch 2, appuyez une fois brièvement sur SYNC sur la console.",
        ["Dieser Bluetooth-Adapter unterstützt kein Bluetooth LE"] = "Cet adaptateur Bluetooth ne prend pas en charge Bluetooth LE",
        ["Erst IR-Kamera bzw. Ring-Con ausschalten (sie nutzen denselben Zusatzprozessor wie der NFC-Leser)."] =
            "Désactivez d'abord la caméra IR ou le Ring-Con (ils utilisent le même coprocesseur que le lecteur NFC).",
        ["Erst die IR-Kamera schließen (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "Fermez d'abord la caméra IR (le Ring-Con et la caméra IR utilisent le même coprocesseur).",
        ["Erst den Ring-Con ausschalten (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "Désactivez d'abord le Ring-Con (le Ring-Con et la caméra IR utilisent le même coprocesseur).",
        ["amiibo zu früh entfernt"] = "amiibo retiré trop tôt",
        ["MCU startet nicht"] = "le coprocesseur ne démarre pas",
        ["NFC-Modus nicht aktiv"] = "mode NFC inactif",
        ["Kopplung fehlgeschlagen – Details im Protokoll."] = "Appairage échoué – détails dans le journal.",

        // ---------- Kopplungsdaten (Switch-SD-Karte, anderer PC) ----------
        ["Kopplungsdaten"] = "Données d'appairage",
        ["Kopplungen übernehmen oder weitergeben"] = "Reprendre ou partager des appairages",
        ["Kopplungsdaten von der Switch übernehmen"] = "Reprendre les données d'appairage de la Switch",
        ["Von der Switch-SD-Karte (Bluepick_RCM/hekate) oder von einem anderen PC übernehmen, oder für einen anderen PC exportieren."] =
            "Reprendre depuis la carte SD de la Switch (Bluepick_RCM/hekate) ou d'un autre PC, ou exporter pour un autre PC.",
        ["Bei Switch-SD-Karte nachfragen"] = "Proposer lorsqu'une carte SD de Switch est insérée",
        ["Steckt eine SD-Karte der Switch im PC (Kartenleser oder hekate „USB Tools“), bietet N-Connect die Übernahme an. Die Karte wird nur gelesen."] =
            "Quand une carte SD de Switch est dans le PC (lecteur de carte ou hekate « USB Tools »), N-Connect propose la reprise. La carte est seulement lue.",
        ["Switch-SD-Karte erkannt"] = "Carte SD de Switch détectée",
        ["Kopplungsdaten der Controller gefunden – klicken, um sie anzusehen und zu übernehmen."] =
            "Données d'appairage de manettes trouvées – cliquez pour les voir et les reprendre.",
        ["Klicken, um Kopplungsdaten der Controller zu übernehmen."] = "Cliquez pour reprendre les données d'appairage des manettes.",
        ["Controller-Kopplungen von der Switch-SD-Karte oder von einem anderen PC übernehmen – oder für einen anderen PC exportieren. Es werden nur Einstellungen von N-Connect geändert; Windows und der Bluetooth-Adapter bleiben unverändert."] =
            "Reprenez les appairages de manettes depuis la carte SD de la Switch ou d'un autre PC – ou exportez-les pour un autre PC. Seuls les paramètres de N-Connect sont modifiés ; Windows et l'adaptateur Bluetooth restent inchangés.",
        ["Spieler-Reihenfolge – Spieler 1 ist für Windows, Steam und Spiele der erste Controller. Mit ‹ › umsortieren."] =
            "Ordre des joueurs – le joueur 1 est la première manette pour Windows, Steam et les jeux. Réordonnez avec ‹ ›.",
        ["Von der Switch-SD-Karte"] = "Depuis la carte SD de la Switch",
        ["Mit Bluepick_RCM oder hekate erstellte Kopplungsdaten (switchroot/joycon_mac.ini)"] =
            "Données d'appairage créées avec Bluepick_RCM ou hekate (switchroot/joycon_mac.ini)",
        ["Einlesen …"] = "Lire …",
        ["Von einem anderen PC"] = "D'un autre PC",
        ["Mit N-Connect exportierte Datei (*.ncpair)"] = "Fichier exporté par N-Connect (*.ncpair)",
        ["Datei öffnen …"] = "Ouvrir un fichier …",
        ["Inhalt"] = "Contenu",
        ["Weitergeben und sichern"] = "Partager et sauvegarder",
        ["Für einen anderen PC exportieren"] = "Exporter pour un autre PC",
        ["Bekannte Controller und Einstellungen je Controller, optional mit Passwort"] =
            "Manettes connues et paramètres par manette, éventuellement avec mot de passe",
        ["Sicherung wiederherstellen"] = "Restaurer une sauvegarde",
        ["Vor jedem „Übernehmen“ wird automatisch eine Sicherung angelegt"] = "Une sauvegarde est créée automatiquement avant chaque « Appliquer »",
        ["Wiederherstellen …"] = "Restaurer …",
        ["Bluetooth-Adapter dieses PCs"] = "Adaptateur Bluetooth de ce PC",
        ["wird ermittelt …"] = "détection …",
        ["nicht gefunden"] = "introuvable",
        ["Quelle wählen: Switch-SD-Karte (mit Bluepick_RCM oder hekate erstellte Kopplungsdaten) oder eine Datei von einem anderen PC."] =
            "Choisissez une source : carte SD de Switch (données d'appairage créées avec Bluepick_RCM ou hekate) ou un fichier d'un autre PC.",
        ["Keine Switch-SD-Karte gefunden. SD-Karte in den Kartenleser stecken oder die Switch per hekate („USB Tools“ → „SD Card“) als Laufwerk verbinden.\n\nOrdner selbst auswählen?"] =
            "Aucune carte SD de Switch trouvée. Insérez la carte SD dans un lecteur ou connectez la Switch comme lecteur via hekate (« USB Tools » → « SD Card »).\n\nChoisir le dossier vous-même ?",
        ["Stammordner der Switch-SD-Karte wählen"] = "Choisir le dossier racine de la carte SD de Switch",
        ["Switch-SD-Karte:"] = "Carte SD de Switch :",
        ["Auf der Karte liegen keine Kopplungsdaten (switchroot/joycon_mac.ini)."] = "La carte ne contient pas de données d'appairage (switchroot/joycon_mac.ini).",
        ["So erstellst du sie: Joy-Con an die Switch stecken, Bluepick_RCM starten und „Dump Joy-Con BT pairing → SD“ (oder FULL AUTO) wählen. Alternativ in hekate: Nyx → Konsole → „Dump Joy-Con BT“."] =
            "Pour les créer : connectez les Joy-Con à la Switch, lancez Bluepick_RCM et choisissez « Dump Joy-Con BT pairing → SD » (ou FULL AUTO). Sinon dans hekate : Nyx → Console → « Dump Joy-Con BT ».",
        ["Gefunden wurde eine Bluepick-Sicherung des Bluetooth-Speichers (8000000000000050.bin). Sie ist ein Switch-Speicherabbild und kann hier nicht ausgewertet werden."] =
            "Une sauvegarde Bluepick de la mémoire Bluetooth (8000000000000050.bin) a été trouvée. C'est une image mémoire de la Switch et elle ne peut pas être exploitée ici.",
        ["Bluetooth-Adresse der Switch:"] = "Adresse Bluetooth de la Switch :",
        ["Gefundene Controller:"] = "Manettes trouvées :",
        ["mit der Switch gekoppelt"] = "appairée à la Switch",
        ["zuletzt mit einem anderen Gerät gekoppelt (nicht der Switch)"] = "dernier appairage avec un autre appareil (pas la Switch)",
        ["Joy-Con (L)"] = "Joy-Con (G)",
        ["Joy-Con (R)"] = "Joy-Con (D)",
        ["HORI-Controller (links)"] = "Manette HORI (gauche)",
        ["HORI-Controller (rechts)"] = "Manette HORI (droite)",
        ["Hinweis: Pro Controller stehen nur im Bluetooth-Speicher der Switch (8000000000000050.bin); dieses Speicherabbild kann N-Connect nicht auswerten."] =
            "Remarque : les Pro Controller ne figurent que dans la mémoire Bluetooth de la Switch (8000000000000050.bin) ; N-Connect ne peut pas exploiter cette image mémoire.",
        ["Was diese Daten können – und was nicht:"] = "Ce que ces données permettent – et ce qu'elles ne permettent pas :",
        ["Die Daten zeigen, welche Controller mit deiner Switch gekoppelt sind und an welche Bluetooth-Adresse sie gebunden sind."] =
            "Les données montrent quelles manettes sont appairées à votre Switch et à quelle adresse Bluetooth elles sont liées.",
        ["Ein Switch-1-Controller verbindet sich auf Tastendruck nur mit dem Gerät, dessen Adresse er gespeichert hat – hier mit der Switch. Der Bluetooth-Adapter des PCs hat eine andere Adresse, deshalb kann Windows diese Kopplung nicht einfach weiterverwenden."] =
            "Une manette Switch 1 ne se reconnecte d'une pression qu'à l'appareil dont elle a mémorisé l'adresse – ici la Switch. L'adaptateur Bluetooth du PC a une autre adresse, Windows ne peut donc pas réutiliser cet appairage.",
        ["Die Adresse des PC-Adapters zu ändern, unterstützt N-Connect bewusst nicht (herstellerabhängig, riskant und nicht vorgesehen)."] =
            "N-Connect ne prend volontairement pas en charge le changement d'adresse de l'adaptateur du PC (dépend du fabricant, risqué et non prévu).",
        ["Windows bietet keinen offiziellen Weg, fremde Kopplungsschlüssel einzutragen: Sie liegen in einem Teil der Registrierung, auf den nur das System zugreifen darf. N-Connect ändert dort nichts."] =
            "Windows n'offre aucun moyen officiel d'ajouter des clés d'appairage étrangères : elles se trouvent dans une partie du registre réservée au système. N-Connect n'y change rien.",
        ["So klappt der Wechsel am einfachsten: am PC den Controller einmal per SYNC-Taste in den Windows-Bluetooth-Einstellungen koppeln. Zurück an der Switch die Joy-Con an die Konsole stecken bzw. den Pro Controller per USB-Kabel anschließen – dann sind sie ohne Menü wieder mit der Switch gekoppelt."] =
            "Le plus simple pour changer : sur le PC, appairez la manette une fois avec le bouton SYNC dans les paramètres Bluetooth de Windows. De retour sur la Switch, connectez les Joy-Con à la console ou branchez le Pro Controller en USB – ils sont de nouveau appairés sans menu.",
        ["„Übernehmen“ merkt sich diese Controller in N-Connect (Liste bekannter Controller, Zuordnung zur Switch). Kopplungsschlüssel werden nicht gespeichert."] =
            "« Appliquer » mémorise ces manettes dans N-Connect (liste des manettes connues, association à la Switch). Les clés d'appairage ne sont pas enregistrées.",
        ["N-Connect-Kopplungsdaten"] = "Données d'appairage N-Connect",
        ["Kopplungsdaten von einem anderen PC öffnen"] = "Ouvrir des données d'appairage d'un autre PC",
        ["Die Datei ist zu groß."] = "Le fichier est trop volumineux.",
        ["Keine Kopplungsdaten-Datei."] = "Pas un fichier de données d'appairage.",
        ["Die Datei stammt von einer neueren N-Connect-Version."] = "Le fichier provient d'une version plus récente de N-Connect.",
        ["Die Datei ist mit einem Passwort geschützt."] = "Le fichier est protégé par un mot de passe.",
        ["Falsches Passwort oder die Datei wurde verändert."] = "Mot de passe incorrect ou fichier modifié.",
        ["Die Datei ist beschädigt."] = "Le fichier est endommagé.",
        ["Datei von:"] = "Fichier de :",
        ["Bluetooth-Adapter dort:"] = "Adaptateur Bluetooth là-bas :",
        ["Bluetooth-Adapter hier:"] = "Adaptateur Bluetooth ici :",
        ["gekoppelt mit der Switch"] = "appairée à la Switch",
        ["gekoppelt mit dem anderen PC"] = "appairée à l'autre PC",
        ["Weitere Einstellungen je Controller:"] = "Autres paramètres par manette :",
        ["Was du erwarten kannst:"] = "À quoi vous attendre :",
        ["Gleiche Adapter-Adresse (z. B. derselbe USB-Bluetooth-Stick umgesteckt): Switch-2-Controller verbinden sich hier auf Tastendruck wie am anderen PC."] =
            "Même adresse d'adaptateur (p. ex. la même clé USB Bluetooth rebranchée) : les manettes Switch 2 se connectent ici d'une pression comme sur l'autre PC.",
        ["Switch-1-Controller (Pro Controller, Joy-Con) brauchen zusätzlich die Kopplung in Windows. Die kann N-Connect nicht übertragen – einmal per SYNC-Taste koppeln."] =
            "Les manettes Switch 1 (Pro Controller, Joy-Con) ont en plus besoin de l'appairage dans Windows. N-Connect ne peut pas le transférer – appairez une fois avec le bouton SYNC.",
        ["Anderer Bluetooth-Adapter: Controller verbinden sich auf Tastendruck nur mit dem Gerät, mit dem sie zuletzt gekoppelt wurden. Hier einmal SYNC drücken – danach verbinden sie sich mit diesem PC (am anderen PC dann wieder per SYNC)."] =
            "Autre adaptateur Bluetooth : les manettes ne se reconnectent d'une pression qu'à l'appareil auquel elles ont été appairées en dernier. Appuyez une fois sur SYNC ici – ensuite elles se connectent à ce PC (sur l'autre PC, utilisez SYNC à nouveau).",
        ["Tipp: Wer denselben USB-Bluetooth-Stick zwischen den PCs umsteckt, nimmt die Adresse mit – Switch-2-Controller verbinden sich dann an beiden PCs ohne SYNC."] =
            "Astuce : qui rebranche la même clé USB Bluetooth entre les PC emporte l'adresse – les manettes Switch 2 se connectent alors sur les deux PC sans SYNC.",
        ["Übernommen werden die Einstellungen je Controller (Joy-Con einzeln/hochkant, Gyro-Kalibrierung) und die Liste bekannter Controller."] =
            "Sont repris les paramètres par manette (Joy-Con seul/vertical, étalonnage du gyroscope) et la liste des manettes connues.",
        ["Die Datei enthält Kopplungsschlüssel. Windows bietet keinen offiziellen Weg, sie einzutragen – N-Connect übernimmt sie deshalb nicht."] =
            "Le fichier contient des clés d'appairage. Windows n'offre aucun moyen officiel de les ajouter – N-Connect ne les reprend donc pas.",
        ["„Übernehmen“ ergänzt die Controller-Listen und Einstellungen von N-Connect (nichts wird gelöscht). Vorher wird eine Sicherung angelegt."] =
            "« Appliquer » complète les listes de manettes et les paramètres de N-Connect (rien n'est supprimé). Une sauvegarde est créée avant.",
        ["Kopplungsdaten in N-Connect übernehmen? Vorher wird eine Sicherung der Einstellungen angelegt."] =
            "Reprendre les données d'appairage dans N-Connect ? Une sauvegarde des paramètres est créée avant.",
        ["Nichts zu ändern – diese Daten sind schon übernommen."] = "Rien à changer – ces données ont déjà été reprises.",
        ["Übernommen. Die Sicherung lässt sich hier über „Sicherung wiederherstellen“ zurückholen."] =
            "Terminé. La sauvegarde peut être restaurée ici via « Restaurer une sauvegarde ».",
        ["Sicherung der Einstellungen"] = "Sauvegarde des paramètres",
        ["Die Sicherung ist beschädigt und wurde nicht übernommen."] = "La sauvegarde est endommagée et n'a pas été appliquée.",
        ["Alle Einstellungen durch diese Sicherung ersetzen?"] = "Remplacer tous les paramètres par cette sauvegarde ?",
        ["Sicherung wiederhergestellt."] = "Sauvegarde restaurée.",
        ["Kopplungsdaten für einen anderen PC speichern"] = "Enregistrer les données d'appairage pour un autre PC",
        ["Gespeichert. Die Datei am anderen PC in N-Connect unter „Joy-Con & Wii“ → „Kopplungsdaten“ → „Von einem anderen PC“ öffnen."] =
            "Enregistré. Sur l'autre PC, ouvrez le fichier dans N-Connect sous « Joy-Con et Wii » → « Données d'appairage » → « D'un autre PC ».",
        ["Kopplungsdaten exportieren"] = "Exporter les données d'appairage",
        ["Passwort eingeben"] = "Saisir le mot de passe",
        ["Passwort (optional). Ohne Passwort steht der Inhalt lesbar in der Datei. Mit Kopplungsschlüsseln ist ein Passwort Pflicht."] =
            "Mot de passe (facultatif). Sans mot de passe, le contenu est lisible dans le fichier. Avec des clés d'appairage, le mot de passe est obligatoire.",
        ["Passwort"] = "Mot de passe",
        ["Passwort wiederholen"] = "Répéter le mot de passe",
        ["Kopplungsschlüssel der Switch-Controller mitnehmen"] = "Inclure les clés d'appairage des manettes Switch",
        ["Kopplungsschlüssel mitnehmen (erst Switch-SD-Karte einlesen)"] = "Inclure les clés d'appairage (lire d'abord une carte SD de Switch)",
        ["Die Passwörter stimmen nicht überein."] = "Les mots de passe ne correspondent pas.",
        ["Mit Schlüsseln: Passwort mit mindestens 8 Zeichen."] = "Avec les clés : mot de passe d'au moins 8 caractères.",
        ["Mindestens 8 Zeichen."] = "Au moins 8 caractères.",
        ["Ohne Passwort."] = "Sans mot de passe.",
    };

    /// <summary>Meldungen mit Platzhaltern (Französisch).</summary>
    private static readonly (Regex Pattern, Func<Match, string> Replace)[] PatternsFr =
    [
        (Re(@"^Allgemeiner Wert \((?<v>.+)\) – Regler verschieben für einen eigenen$"), m => $"Valeur générale ({m.Groups["v"]}) – déplacez le curseur pour une valeur propre"),
        (Re(@"^Eigener Wert · allgemein: (?<v>.+)$"), m => $"Valeur propre · générale : {m.Groups["v"]}"),
        (Re(@"^Spieler (?<n>\d+)  ·  (?<k>.+?)(?<rest>(  ·  .*)?)$"), m => $"Joueur {m.Groups["n"]}  ·  {N(m, "k")}{T(m.Groups["rest"].Value)}"),
        (Re(@"^  ·  Gyro-Maus(?<r>.*)$"), m => "  ·  Souris gyro" + T(m.Groups["r"].Value)),
        (Re(@"^  ·  Gyro-Stick$"), _ => "  ·  Stick gyro"),
        (Re(@"^Spieler (?<n>\d+) · (?<k>.+?) (?<b>\d+ %.*)?$"), m => $"Joueur {m.Groups["n"]} · {N(m, "k")} {m.Groups["b"]}"),
        (Re(@"^(?<k>.+) verbunden \(Spieler (?<n>\d+)\)$"), m => $"{N(m, "k")} connectée (joueur {m.Groups["n"]})"),
        (Re(@"^Spieler (?<n>\d+) – tauschen mit (?<k>.+)$"), m => $"Joueur {m.Groups["n"]} – échanger avec {N(m, "k")}"),
        (Re(@"^Spieler (?<n>\d+) – frei$"), m => $"Joueur {m.Groups["n"]} – libre"),
        (Re(@"^Spieler (?<n>\d+)$"), m => $"Joueur {m.Groups["n"]}"),
        (Re(@"^Xbox 360 · Platz (?<n>\d+)$"), m => $"Xbox 360 · place {m.Groups["n"]}"),
        (Re(@"^noch (?<n>\d+) s$"), m => $"encore {m.Groups["n"]} s"),
        (Re(@"^Fertig – (?<n>\d+) Controller verbunden$"), m => $"Terminé – {m.Groups["n"]} manette(s) connectée(s)"),
        (Re(@"^✓ (?<k>.+) verbunden – Spieler (?<n>\d+)$"), m => $"✓ {N(m, "k")} connectée – joueur {m.Groups["n"]}"),
        (Re(@"^Spieler (?<n>\d+)  ·  (?<v>.+)$"), m => $"Joueur {m.Groups["n"]}  ·  {m.Groups["v"]}"),
        (Re(@"^Gekoppelt: (?<k>.+) – verbindet gleich …$"), m => $"Appairée : {m.Groups["k"]} – connexion …"),
        (Re(@"^Ins Spiel wechseln … (?<n>\d+)$"), m => $"Passez au jeu … {m.Groups["n"]}"),
        (Re(@"^(?<k>.+) ist jetzt Spieler (?<n>\d+)$"), m => $"{N(m, "k")} est maintenant le joueur {m.Groups["n"]}"),
        (Re(@"^Spieler (?<a>\d+) und (?<b>\d+) getauscht$"), m => $"Joueurs {m.Groups["a"]} et {m.Groups["b"]} échangés"),
        (Re(@"^Name für (?<k>.+) \(leer = Standardname\):$"), m => $"Nom pour {N(m, "k")} (vide = nom par défaut) :"),
        (Re(@"^(?<k>.+) \(Joy-Con-Paar\)$"), m => $"{m.Groups["k"]} (paire Joy-Con)"),
        (Re(@"^Joy-Con zusammengefasst \(Spieler (?<n>\d+)\)$"), m => $"Joy-Con combinés (joueur {m.Groups["n"]})"),
        (Re(@"^Joy-Con getrennt – (?<k>.+) ist jetzt Spieler (?<n>\d+)$"), m => $"Joy-Con séparé – {N(m, "k")} est maintenant le joueur {m.Groups["n"]}"),
        (Re(@"^Spieler (?<n>\d+): Akku (?<k>.+) fast leer \((?<p>\d+) %\) – bitte aufladen$"),
            m => $"Joueur {m.Groups["n"]} : batterie de {N(m, "k")} presque vide ({m.Groups["p"]} %) – chargez-la"),
        (Re(@"^Spieler (?<n>\d+): nach (?<m>\d+) min ohne Eingabe getrennt$"),
            m => $"Joueur {m.Groups["n"]} : déconnecté après {m.Groups["m"]} min sans action"),
        (Re(@"^Profil „(?<p>.+)“ aktiv$"), m => $"Profil « {ProfileName(m.Groups["p"].Value)} » actif"),
        (Re(@"^Profil: (?<p>.+)$"), m => $"Profil : {ProfileName(m.Groups["p"].Value)}"),
        (Re(@"^Profil „(?<p>.+)“ löschen\?$"), m => $"Supprimer le profil « {m.Groups["p"]} » ?"),
        (Re(@"^Profil „(?<p>.+)“ importiert(?<r>.*)$"), m => $"Profil « {m.Groups["p"]} » importé" + m.Groups["r"].Value.Replace("aktiv bei:", "actif avec :")),
        (Re(@"^⬇ Neue Version (?<v>.+) herunterladen …$"), m => $"⬇ Télécharger la nouvelle version {m.Groups["v"]} …"),
        (Re(@"^Version (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Herunterladen\.$"),
            m => $"La version {m.Groups["v"]} est disponible (installée : {m.Groups["i"]}). Cliquez pour télécharger."),
        (Re(@"^Version (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Installieren\.$"),
            m => $"La version {m.Groups["v"]} est disponible (installée : {m.Groups["i"]}). Cliquez pour installer."),
        (Re(@"^⬇ Auf Version (?<v>.+) aktualisieren …$"), m => $"⬇ Mettre à jour vers la version {m.Groups["v"]} …"),
        (Re(@"^Lade Version (?<v>.+) herunter …$"), m => $"Téléchargement de la version {m.Groups["v"]} …"),
        (Re(@"^HidHide (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Installieren\.$"),
            m => $"HidHide {m.Groups["v"]} est disponible (installée : {m.Groups["i"]}). Cliquez pour installer."),
        (Re(@"^Lade HidHide (?<v>.+) herunter …$"), m => $"Téléchargement de HidHide {m.Groups["v"]} …"),
        (Re(@"^(?<t>.+) · (?<r>\d+) Berichte/s$"), m => $"{T(m.Groups["t"].Value)} · {m.Groups["r"]} rapports/s"),
        (Re(@"^(?<p>\d+ %)(?<v>  \(.*\))?  ⚡ lädt$"), m => $"{m.Groups["p"]}{m.Groups["v"]}  ⚡ en charge"),
        (Re(@"^Speichern fehlgeschlagen: (?<e>.*)$"), m => $"Échec de l'enregistrement : {m.Groups["e"]}"),
        (Re(@"^Lesen fehlgeschlagen: (?<e>.*)$"), m => $"Échec de la lecture : {m.Groups["e"]}"),
        (Re(@"^amiibo konnte nicht gelesen werden: (?<e>.*)$"), m => $"Impossible de lire l'amiibo : {T(m.Groups["e"].Value)}"),
        (Re(@"^Gekoppelt: (?<k>.+)$"), m => $"Appairée : {m.Groups["k"]}"),
        (Re(@"^Gefunden: (?<k>.+) – kopple …$"), m => $"Trouvée : {m.Groups["k"]} – appairage …"),
        (Re(@"^amiibo erkannt \((?<u>.+)\) – lese …$"), m => $"amiibo détecté ({m.Groups["u"]}) – lecture …"),
        (Re(@"^(?<n>\d+) Minuten$"), m => $"{m.Groups["n"]} minutes"),
        (Re(@"^✓ (?<n>\d+) Schritte, Dauer (?<ms>\d+) ms$"), m => $"✓ {m.Groups["n"]} étapes, {m.Groups["ms"]} ms au total"),
        (Re(@"^Controller-Taste „(?<b>.+)“:\nJetzt die gewünschte Taste oder Tastenkombination drücken\.$"),
            m => $"Bouton de la manette « {T(m.Groups["b"].Value)} » :\nAppuyez maintenant sur la touche ou combinaison voulue."),
        (Re(@"^Solange „(?<b>.+)“ gehalten wird, wird diese Taste schnell wiederholt gedrückt\n\(Geschwindigkeit unter 5\. „Turbo“\):$"),
            m => $"Tant que « {T(m.Groups["b"].Value)} » est maintenu, ce bouton se répète rapidement\n(vitesse sous 5. « Turbo ») :"),
        (Re(@"^Ring-Con: (?<e>.*)$"), m => $"Ring-Con : {T(m.Groups["e"].Value)}"),
        (Re(@"^⌨  Taste: (?<k>.+)$"), m => $"⌨  Touche : {m.Groups["k"]}"),
        (Re(@"^🔁  Turbo: Taste (?<k>.+)$"), m => $"🔁  Turbo : touche {m.Groups["k"]}"),
        (Re(@"^🔁  Turbo: (?<k>.+)$"), m => $"🔁  Turbo : {T(m.Groups["k"].Value)}"),
        (Re(@"^⏯  Makro: (?<k>.+)$"), m => $"⏯  Macro : {m.Groups["k"]}"),
        (Re(@"^Tastatur: (?<k>.+)$"), m => $"Clavier : {m.Groups["k"]}"),
        (Re(@"^Gamepad: (?<k>.+)$"), m => $"Manette : {m.Groups["k"]}"),
        (Re(@"^(?<k>.+)  \(verbunden\)$"), m => $"{N(m, "k")}  (connectée)"),
        (Re(@"^Bluetooth nicht verfügbar: (?<e>.*)$"), m => $"Bluetooth indisponible : {m.Groups["e"]}"),
        (Re(@"^(?<k>.+) per USB ist von einem anderen Programm belegt \(z\. B\. Steam\)\.$"),
            m => $"{N(m, "k")} en USB est utilisé par un autre programme (p. ex. Steam)."),
        (Re(@"^Schon (?<n>\d+) Controller verbunden – (?<k>.+) wird nicht verwendet\.$"),
            m => $"{m.Groups["n"]} manettes déjà connectées – {N(m, "k")} n'est pas utilisée."),
        (Re(@"^(?<k>.+): schwache Bluetooth-Verbindung \((?<r>\d+) statt 33–60 Berichte/s\)\.$"),
            m => $"{N(m, "k")} : connexion Bluetooth faible ({m.Groups["r"]} au lieu de 33–60 rapports/s)."),
        (Re(@"^(?<k>.+) getrennt$"), m => $"{N(m, "k")} déconnectée"),
    ];
}
