using System.Text.RegularExpressions;

namespace Switch2Pro.Bridge;

/// <summary>Feste Texte Deutsch → Portugiesisch. Schlüssel bleiben die deutschen Originaltexte.</summary>
internal static partial class Tr
{
    private static readonly Dictionary<string, string> TextsPt = new(StringComparer.Ordinal)
    {
        // ---------- Fenster, Reiter, Abschnitte ----------
        ["Controller"] = "Comandos",
        // ---------- Status-Kopfzeile, Ansicht ----------
        ["bereit"] = "pronto",
        ["nicht verfügbar"] = "indisponível",
        ["Niedrigster Akku"] = "Bateria mais baixa",
        ["lädt"] = "a carregar",
        ["gemischt"] = "misto",
        ["Original-Controller"] = "Comandos originais",
        ["versteckt"] = "ocultos",
        ["sichtbar"] = "visíveis",
        ["HidHide fehlt"] = "HidHide em falta",
        ["Groß"] = "Grande",
        ["Kompakt"] = "Compacto",
        ["Einstellungen (optional)"] = "Definições (opcional)",
        ["1. Windows und Spiele sehen den Controller als …"] = "1. O Windows e os jogos veem o comando como …",
        ["2. Tasten A/B/X/Y"] = "2. Botões A/B/X/Y",
        ["3. Vibration, Sticks, Verbinden, Gyro-Maus"] = "3. Vibração, sticks, ligação, rato giroscópio",
        ["4. Joy-Con"] = "4. Joy-Con",
        ["4. Joy-Con und Wii"] = "4. Joy-Con e Wii",
        ["Wii-Fernbedienung: Zeiger (Sensorleiste) steuert die Maus"] = "Comando Wii: o ponteiro (barra de sensores) move o rato",
        ["Zeiger"] = "Ponteiro",
        ["kein Zeiger – Sensorleiste nicht im Blick"] = "sem ponteiro – barra de sensores fora de vista",
        ["5. Zielen, Sticks, Trigger, Turbo"] = "5. Mira, sticks, gatilhos, turbo",
        ["6. Tastenbelegung und Profile  (Taste → Gamepad, Tastatur, Maus, Gyro-Maus, Shift-Ebene)"] =
            "6. Atribuição de botões e perfis  (botão → gamepad, teclado, rato, rato giroscópio, camada Shift)",
        ["Xbox-360-Controller  (empfohlen – läuft mit fast allen Spielen)"] = "Comando Xbox 360  (recomendado – funciona com quase todos os jogos)",
        ["PlayStation DualShock 4  (mit Bewegungssteuerung/Gyro – für Steam && Emulatoren)"] =
            "PlayStation DualShock 4  (com controlo por movimento/giroscópio – para Steam e emuladores)",
        ["Xbox-Belegung  (nach Position: untere Taste = A)"] = "Esquema Xbox  (por posição: botão inferior = A)",
        ["Nintendo-Belegung  (nach Beschriftung: A bleibt A)"] = "Esquema Nintendo  (por rótulo: A continua A)",
        ["Vibration"] = "Vibração",
        ["Stärke:"] = "Intensidade:",
        ["Stick-Totzone (alle Controller):"] = "Zona morta do stick (todos os comandos):",
        ["Beim Verbinden kurz vibrieren"] = "Vibrar brevemente ao ligar",
        ["Meldung bei Verbinden"] = "Notificação de ligação",
        ["Wer meldet, wenn ein Controller verbunden oder getrennt wird."] = "Escolhe quem notifica quando um comando liga ou desliga.",
        ["„N-Connect“ zeigt den echten Controller-Namen und schaltet die Gerätemeldungen von Windows ab."] = "\"N-Connect\" mostra o nome real do comando e desativa as notificações de dispositivos do Windows.",
        ["N-Connect (empfohlen)"] = "N-Connect (recomendado)",
        ["N-Connect und Windows"] = "N-Connect e Windows",
        ["Keine"] = "Nenhuma",
        ["Gekoppelte Controller per Tastendruck verbinden (ohne SYNC)"] = "Ligar comandos emparelhados com um toque num botão (sem SYNC)",
        ["Automatisch mit Windows starten"] = "Iniciar automaticamente com o Windows",
        ["Gyro für Emulatoren bereitstellen (Cemuhook/DSU, Port 26760 – wirkt nach Neustart)"] =
            "Disponibilizar o giroscópio para emuladores (Cemuhook/DSU, porta 26760 – ativo após reiniciar)",
        ["Beim Start nach neuer Version suchen (GitHub)"] = "Procurar uma nova versão ao iniciar (GitHub)",
        ["Ohne Eingabe automatisch trennen nach:"] = "Desligar automaticamente sem ação após:",
        ["Gyro-Maus-Geschwindigkeit:"] = "Velocidade do rato giroscópio:",
        ["Sprache / Language:"] = "Idioma / Language:",
        ["Automatisch (wie Windows)"] = "Automático (como o Windows)",
        ["nie"] = "nunca",
        ["Zwei Joy-Con automatisch zu einem Controller zusammenfassen"] = "Combinar automaticamente dois Joy-Con num só comando",
        ["Gyro beim Paar vom:"] = "Giroscópio do par a partir de:",
        ["rechter Joy-Con (wie Switch)"] = "Joy-Con direito (como na Switch)",
        ["linker Joy-Con"] = "Joy-Con esquerdo",
        ["Joy-Con 2 als Maus, wenn er auf dem Tisch liegt"] = "Joy-Con 2 como rato quando está na mesa",
        ["Mausgeschwindigkeit:"] = "Velocidade do rato:",
        ["Maus: links/rechts umkehren"] = "Rato: inverter esquerda/direita",
        ["Maus: hoch/runter umkehren"] = "Rato: inverter cima/baixo",
        ["Wie an der Switch: SL + SR eine Sekunde halten löst einen Joy-Con aus dem Paar. L am linken und R am rechten einzelnen Joy-Con gleichzeitig drücken verbindet sie wieder zum Paar. Die Wahl wird je Joy-Con gemerkt (auch nach dem nächsten Verbinden). Im Mausmodus: R/L = Linksklick, ZR/ZL = Rechtsklick, Stick drücken = Mittelklick, Stick hoch/runter = Scrollen."] =
            "Como na Switch: manter SL + SR durante um segundo separa um Joy-Con do par. Premir L no esquerdo e R no direito em simultâneo volta a juntá-los. A escolha é memorizada por Joy-Con (também na próxima ligação). No modo rato: R/L = clique esquerdo, ZR/ZL = clique direito, premir o stick = clique do meio, stick para cima/baixo = deslocar.",
        ["Gyro als rechter Stick:"] = "Giroscópio como stick direito:",
        ["aus (nur per Taste „Gyro-Stick“)"] = "desativado (apenas por botão « stick giroscópio »)",
        ["immer"] = "sempre",
        ["beim Zielen (solange ZL / linker Trigger gedrückt)"] = "ao apontar (enquanto ZL / gatilho esquerdo está premido)",
        ["hoch/runter umkehren"] = "inverter cima/baixo",
        ["Empfindlichkeit:"] = "Sensibilidade:",
        ["Mindestausschlag:"] = "Deflexão mínima:",
        ["Stick-Kennlinie:"] = "Curva do stick:",
        ["Turbo (pro Sekunde):"] = "Turbo (por segundo):",
        ["Analoge Trigger (GameCube) – Totzone:"] = "Gatilhos analógicos (GameCube) – zona morta:",
        ["voll gedrückt ab:"] = "premido a fundo a partir de:",
        ["Profil:"] = "Perfil:",
        ["Neu …"] = "Novo …",
        ["Umbenennen …"] = "Mudar o nome …",
        ["Löschen"] = "Eliminar",
        ["Exportieren …"] = "Exportar …",
        ["Importieren …"] = "Importar …",
        ["Aktiv bei Programm:"] = "Ativo com o programa:",
        ["Programm wählen …"] = "Escolher programa …",
        ["Standard"] = "Predefinido",
        ["Standard gilt immer, wenn kein anderes Profil passt"] = "O predefinido aplica-se quando nenhum outro perfil se adequa",
        ["z. B. Cemu.exe, Ryujinx.exe"] = "p. ex. Cemu.exe, Ryujinx.exe",
        ["Ein eigenes Profil wird automatisch aktiv, solange eines seiner Programme im Vordergrund ist (sonst gilt „Standard“). Im Infobereich-Menü lässt sich ein Profil auch fest wählen."] =
            "Um perfil próprio fica ativo automaticamente enquanto um dos seus programas estiver em primeiro plano (senão aplica-se « Predefinido »). Um perfil também pode ser fixado no menu da área de notificação.",
        ["Controller:"] = "Comando:",
        ["Eigene Stick-Totzone für diesen Controller:"] = "Zona morta de stick própria para este comando:",
        ["Normale Belegung"] = "Atribuição normal",
        ["Shift-Ebene (gilt, solange eine Taste mit „Shift-Ebene“ gehalten wird)"] = "Camada Shift (aplica-se enquanto um botão « camada Shift » estiver premido)",
        ["Alles auf Standard"] = "Repor tudo",
        ["Schließen"] = "Fechar",
        ["wie normale Belegung"] = "como a atribuição normal",

        // ---------- Belegungsziele und Vorlagen ----------
        ["— keine Funktion —"] = "— sem função —",
        ["A (Xbox) / Kreuz (PS)"] = "A (Xbox) / Cruz (PS)",
        ["B (Xbox) / Kreis (PS)"] = "B (Xbox) / Círculo (PS)",
        ["X (Xbox) / Viereck (PS)"] = "X (Xbox) / Quadrado (PS)",
        ["Y (Xbox) / Dreieck (PS)"] = "Y (Xbox) / Triângulo (PS)",
        ["Ansicht (Back) / Share"] = "Ver (Back) / Share",
        ["Menü (Start) / Options"] = "Menu (Start) / Options",
        ["Xbox-Taste / PS-Taste"] = "Botão Xbox / botão PS",
        ["Linker Stick-Klick"] = "Clique do stick esquerdo",
        ["Rechter Stick-Klick"] = "Clique do stick direito",
        ["Steuerkreuz hoch"] = "D-pad para cima",
        ["Steuerkreuz runter"] = "D-pad para baixo",
        ["Steuerkreuz links"] = "D-pad para a esquerda",
        ["Steuerkreuz rechts"] = "D-pad para a direita",
        ["Touchpad-Klick (nur DualShock 4)"] = "Clique do touchpad (apenas DualShock 4)",
        ["🖱  Maus: Linksklick"] = "🖱  Rato: clique esquerdo",
        ["🖱  Maus: Rechtsklick"] = "🖱  Rato: clique direito",
        ["🖱  Maus: Mittelklick"] = "🖱  Rato: clique do meio",
        ["🎯  Gyro-Maus (solange gehalten)"] = "🎯  Rato giroscópio (enquanto premido)",
        ["🎯  Gyro-Maus ein/aus"] = "🎯  Rato giroscópio ligar/desligar",
        ["🎯  Gyro als rechter Stick (solange gehalten)"] = "🎯  Giroscópio como stick direito (enquanto premido)",
        ["🎯  Gyro als rechter Stick ein/aus"] = "🎯  Giroscópio como stick direito ligar/desligar",
        ["⇧  Shift-Ebene (solange gehalten)"] = "⇧  Camada Shift (enquanto premido)",
        ["🔁  Turbo / Dauerfeuer …"] = "🔁  Turbo / fogo rápido …",
        ["⏯  Makro (Tastenfolge) …"] = "⏯  Macro (sequência de botões) …",
        ["📷  Bildschirmfoto speichern (Win+Druck)"] = "📷  Guardar captura de ecrã (Win+Print)",
        ["📷  Bildschirmausschnitt (Win+Umschalt+S)"] = "📷  Captura parcial (Win+Shift+S)",
        ["⏺  Letzte 30 Sekunden aufnehmen (Win+Alt+G)"] = "⏺  Gravar os últimos 30 segundos (Win+Alt+G)",
        ["⏺  Aufnahme starten/stoppen (Win+Alt+R)"] = "⏺  Iniciar/parar gravação (Win+Alt+R)",
        ["🎮  Xbox Game Bar (Win+G)"] = "🎮  Xbox Game Bar (Win+G)",
        ["🔊  Lauter"] = "🔊  Aumentar volume",
        ["🔉  Leiser"] = "🔉  Diminuir volume",
        ["⏯  Wiedergabe/Pause"] = "⏯  Reproduzir/Pausa",
        ["⌨  Andere Taste / Tastenkombination aufnehmen …"] = "⌨  Registar outra tecla / combinação de teclas …",

        // ---------- Tastennamen ----------
        ["+ (Plus)"] = "+ (Plus)",
        ["− (Minus)"] = "− (Minus)",
        ["Aufnahme"] = "Captura",
        ["GL (Rücktaste links)"] = "GL (botão traseiro esquerdo)",
        ["GR (Rücktaste rechts)"] = "GR (botão traseiro direito)",
        ["Linker Stick drücken"] = "Premir stick esquerdo",
        ["Rechter Stick drücken"] = "Premir stick direito",
        ["Stick drücken"] = "Premir stick",
        ["A (groß, unten)"] = "A (grande, em baixo)",
        ["B (links)"] = "B (esquerda)",
        ["X (rechts)"] = "X (direita)",
        ["Y (oben)"] = "Y (em cima)",
        ["L (ganz durchgedrückt)"] = "L (premido a fundo)",
        ["R (ganz durchgedrückt)"] = "R (premido a fundo)",
        ["untere Taste (quer)"] = "botão inferior (na horizontal)",
        ["rechte Taste (quer)"] = "botão direito (na horizontal)",
        ["linke Taste (quer)"] = "botão esquerdo (na horizontal)",
        ["obere Taste (quer)"] = "botão superior (na horizontal)",
        ["1 (quer) / Classic Y"] = "1 (na horizontal) / Classic Y",
        ["2 (quer) / Classic B"] = "2 (na horizontal) / Classic B",
        ["B (Abzug) / Classic ZR"] = "B (gatilho) / Classic ZR",
        ["Kreuz (unten)"] = "Cruz (em baixo)",
        ["Kreis (rechts)"] = "Círculo (direita)",
        ["Viereck (links)"] = "Quadrado (esquerda)",
        ["Dreieck (oben)"] = "Triângulo (em cima)",
        ["PS-Taste"] = "Botão PS",
        ["Touchpad-Klick"] = "Clique do touchpad",
        ["Mikro stumm"] = "Microfone sem som",
        ["Fn links (Edge)"] = "Fn esquerdo (Edge)",
        ["Rücktaste links (Edge)"] = "Botão traseiro esquerdo (Edge)",
        ["Rücktaste rechts (Edge)"] = "Botão traseiro direito (Edge)",
        ["L3 (Stick drücken)"] = "L3 (premir o stick)",
        ["R3 (Stick drücken)"] = "R3 (premir o stick)",
        ["Ansicht/Zurück"] = "Ver/Voltar",
        ["Menü/Start"] = "Menu/Start",
        ["Xbox-Taste"] = "Botão Xbox",

        // ---------- Controller-Namen ----------
        ["Wii-Fernbedienung"] = "Comando Wii",
        ["Xbox-Controller"] = "Comando Xbox",
        ["Xbox-Controller (Microsoft)"] = "Comando Xbox (Microsoft)",
        ["XInput (USB, Bluetooth oder Xbox-Adapter)"] = "XInput (USB, Bluetooth ou adaptador Xbox)",

        // ---------- Übersicht / Karten ----------
        ["Trennen"] = "Desligar",
        ["Vibrieren"] = "Vibrar",
        ["Gyro kalibrieren"] = "Calibrar giroscópio",
        ["Ruhig liegen lassen …"] = "Deixar imóvel …",
        ["Kalibriert ✓"] = "Calibrado ✓",
        ["Hochkant halten"] = "Segurar na vertical",
        ["Quer halten"] = "Segurar na horizontal",
        ["Joy-Con trennen"] = "Separar Joy-Con",
        ["Zum Paar verbinden"] = "Juntar em par",
        ["Joy-Con trennen – beide werden einzelne Controller"] = "Separar Joy-Con – ambos passam a ser comandos individuais",
        ["Zum Paar verbinden – sucht einen freien Joy-Con"] = "Juntar em par – procura um Joy-Con livre",
        ["Doppelt angezeigt? Verstecken"] = "Aparece em duplicado? Ocultar",
        ["amiibo lesen"] = "Ler amiibo",
        ["Ring-Con ein"] = "Ativar Ring-Con",
        ["Ring-Con aus"] = "Desativar Ring-Con",
        ["Ring-Con wird gesucht …"] = "A procurar Ring-Con …",
        ["IR-Kamera"] = "Câmara IR",
        ["Akku"] = "Bateria",
        ["Verbindung"] = "Ligação",
        ["Adresse"] = "Endereço",
        ["Seriennummer"] = "Número de série",
        ["Griff"] = "Suporte",
        ["Maus"] = "Rato",
        ["Gedrückt"] = "Premido",
        ["unbekannt"] = "desconhecido",
        ["Charging Grip – GL/GR aktiv"] = "Charging Grip – GL/GR ativos",
        ["aktiv (liegt auf dem Tisch)"] = "ativo (pousado na mesa)",
        ["bereit – zum Benutzen auf den Tisch legen"] = "pronto – pouse-o na mesa para usar",
        ["Bewegungssensor: keine Daten"] = "Sensor de movimento: sem dados",
        ["quer halten: Steuerkreuz links,\n1 und 2 rechts"] = "na horizontal: d-pad à esquerda,\n1 e 2 à direita",

        // ---------- Tooltips ----------
        ["Verbindung trennen. Der Controller verbindet sich beim nächsten Tastendruck wieder."] =
            "Desligar. O comando volta a ligar-se ao próximo toque num botão.",
        ["Controller kurz vibrieren lassen – zeigt, welcher Controller dieser Spieler ist."] =
            "Faz o comando vibrar brevemente – mostra qual comando pertence a este jogador.",
        ["Controller ruhig auf den Tisch legen und klicken: misst den Gyro-Nullpunkt neu (gegen Abdriften)."] =
            "Pouse o comando na mesa e clique: mede novamente o ponto zero do giroscópio (contra a deriva).",
        ["Einzelnen Joy-Con quer (wie an der Switch) oder hochkant halten – wird je Joy-Con gemerkt. Hochkant gilt die Tastenbelegung von „Joy-Con-Paar“."] =
            "Segure o Joy-Con individual na horizontal (como na Switch) ou na vertical – memorizado por Joy-Con. Na vertical aplica-se a atribuição de « par de Joy-Con ».",
        ["Versteckt den per USB angeschlossenen Controller vor Spielen (HidHide), damit sie nur den virtuellen Xbox-Controller sehen."] =
            "Oculta dos jogos o comando ligado por USB (HidHide), para que vejam apenas o comando Xbox virtual.",
        ["amiibo mit dem NFC-Leser lesen und als Datei (.bin) speichern – z. B. für Emulatoren."] =
            "Lê um amiibo com o leitor NFC e guarda-o como ficheiro (.bin) – p. ex. para emuladores.",
        ["Ring-Con am rechten Joy-Con ein-/ausschalten: zusammendrücken = rechter Trigger, auseinanderziehen = linker Trigger. Beim Einschalten den Ring nicht berühren."] =
            "Ativa/desativa o Ring-Con do Joy-Con direito: apertar = gatilho direito, afastar = gatilho esquerdo. Não toque no anel ao ativar.",
        ["Live-Bild der IR-Kamera im rechten Joy-Con anzeigen."] = "Mostra a imagem em direto da câmara IR do Joy-Con direito.",
        ["Links = empfindlicher (kleine Drehung, großer Ausschlag), rechts = ruhiger."] = "Esquerda = mais sensível (pequena rotação, grande deflexão), direita = mais calmo.",
        ["Mindestausschlag des Sticks bei Bewegung – überwindet die Totzone des Spiels."] = "Deflexão mínima do stick em movimento – ultrapassa a zona morta do jogo.",
        ["Mitte = linear. Rechts = feiner um die Mitte (präzises Zielen), links = schneller."] = "Meio = linear. Direita = mais fino ao centro (mira precisa), esquerda = mais rápido.",
        ["So weit lässt sich ein analoger Trigger drücken, bevor er wirkt."] = "Até onde um gatilho analógico pode ser premido antes de atuar.",
        ["Ab hier gilt der Trigger als ganz gedrückt (100 = erst am Anschlag)."] = "A partir daqui o gatilho conta como premido a fundo (100 = só no batente).",
        ["Wie oft pro Sekunde Tasten mit „Turbo“ auslösen."] = "Quantas vezes por segundo os botões « turbo » disparam.",

        // ---------- Infobereich ----------
        ["ViGEmBus-Treiber fehlt"] = "Controlador ViGEmBus em falta",
        ["ViGEmBus herunterladen …"] = "Descarregar ViGEmBus …",
        ["Verbinde …"] = "A ligar …",
        ["Kein Controller – SYNC-Taste am Controller kurz drücken"] = "Sem comando – prima brevemente o botão SYNC do comando",
        ["Ausgabe als"] = "Saída como",
        ["Xbox-360-Controller (empfohlen)"] = "Comando Xbox 360 (recomendado)",
        ["DualShock 4 (mit Gyro für Steam/Emulatoren)"] = "DualShock 4 (com giroscópio para Steam/emuladores)",
        ["Tastenbelegung"] = "Atribuição de botões",
        ["Xbox-Belegung (untere Taste = A)"] = "Esquema Xbox (botão inferior = A)",
        ["Switch-2-Pro-Belegung (A bleibt A)"] = "Esquema Nintendo (A continua A)",
        ["Automatisch (nach Spiel/Programm)"] = "Automático (consoante o jogo/programa)",
        ["Mit Windows starten"] = "Iniciar com o Windows",
        ["Einstellungen …"] = "Definições …",
        ["Kurzanleitung"] = "Guia rápido",
        ["Protokoll öffnen"] = "Abrir registo",
        ["Beenden"] = "Sair",
        ["N-Connect: warte auf Controller (SYNC drücken)"] = "N-Connect: a aguardar um comando (prima SYNC)",
        ["N-Connect: ViGEmBus fehlt"] = "N-Connect: ViGEmBus em falta",
        ["Neue Version verfügbar"] = "Nova versão disponível",
        ["Einstellungen fehlerhaft"] = "Definições danificadas",
        ["settings.json konnte nicht gelesen werden – es gelten die Standardwerte."] = "Não foi possível ler settings.json – aplicam-se os valores predefinidos.",
        ["Ohne ViGEmBus kann kein virtueller Controller erzeugt werden. Bitte das Setup erneut ausführen oder ViGEmBus installieren (Rechtsklick auf das Symbol → ViGEmBus herunterladen)."] =
            "Sem ViGEmBus não é possível criar um comando virtual. Execute novamente a instalação ou instale o ViGEmBus (clique direito no ícone → Descarregar ViGEmBus).",

        // ---------- Dialoge ----------
        ["Tastatur-Taste festlegen"] = "Definir tecla do teclado",
        ["Übernehmen"] = "Aplicar",
        ["Abbrechen"] = "Cancelar",
        ["Ja"] = "Sim",
        ["Nein"] = "Não",
        ["Turbo / Dauerfeuer"] = "Turbo / fogo rápido",
        ["Tastatur-Taste aufnehmen …"] = "Registar tecla do teclado …",
        ["Makro (Tastenfolge)"] = "Macro (sequência de botões)",
        ["Ungültig – bitte Schreibweise prüfen (siehe oben)."] = "Inválido – verifique a sintaxe (ver acima).",
        ["Neues Profil"] = "Novo perfil",
        ["Name des Profils (z. B. der Spielname):"] = "Nome do perfil (p. ex. o nome do jogo):",
        ["Profil umbenennen"] = "Mudar o nome do perfil",
        ["Neuer Name:"] = "Novo nome:",
        ["Ein Profil mit diesem Namen gibt es schon."] = "Já existe um perfil com este nome.",
        ["Die Datei enthält kein gültiges Controller-Profil."] = "O ficheiro não contém um perfil de comando válido.",
        ["Alle Einstellungen und Tastenbelegungen auf Standard zurücksetzen?"] = "Repor todas as definições e atribuições de botões?",
        ["Suche …"] = "A procurar …",
        ["Kein Bluetooth-Adapter gefunden."] = "Nenhum adaptador Bluetooth encontrado.",
        ["IR-Kamera (Joy-Con R)"] = "Câmara IR (Joy-Con D)",
        ["Auflösung:"] = "Resolução:",
        ["40 × 30 (schnell)"] = "40 × 30 (rápida)",
        ["320 × 240 (langsam)"] = "320 × 240 (lenta)",
        ["Kamera startet …"] = "A iniciar a câmara …",
        ["läuft – Joy-Con auf eine Lichtquelle oder die Hand richten"] = "em funcionamento – aponte o Joy-Con para uma fonte de luz ou a mão",
        ["Kamera startet nicht (Details im Protokoll)"] = "A câmara não inicia (detalhes no registo)",
        ["Kein Ring-Con gefunden. Den rechten Joy-Con (Switch 1) fest in den Ring-Con schieben und erneut versuchen."] =
            "Nenhum Ring-Con encontrado. Insira bem o Joy-Con direito (Switch 1) no Ring-Con e tente novamente.",
        ["Kein amiibo erkannt. Bitte das amiibo flach an den NFC-Leser halten (Joy-Con: auf den rechten Stick, Pro Controller: auf das NFC-Logo) und erneut versuchen."] =
            "Nenhum amiibo detetado. Segure o amiibo sobre o leitor NFC (Joy-Con: sobre o stick direito; Pro Controller: sobre o logótipo NFC) e tente novamente.",
        ["NFC-Leser wird eingeschaltet …"] = "A ativar o leitor NFC …",
        ["amiibo an den Leser halten (rechter Stick des Joy-Con bzw. NFC-Logo des Pro Controllers) …"] =
            "Segure o amiibo sobre o leitor (stick direito do Joy-Con ou logótipo NFC do Pro Controller) …",
        ["amiibo speichern"] = "Guardar amiibo",
        ["Doppelte Controller verhindern"] = "Evitar comandos duplicados",
        ["Dafür wird das kostenlose Programm HidHide gebraucht (von den Machern von ViGEmBus).\n\nJetzt die Download-Seite öffnen? Nach der Installation hier erneut klicken."] =
            "É necessário o programa gratuito HidHide (dos criadores do ViGEmBus).\n\nAbrir agora a página de download? Após a instalação, clique aqui novamente.",
        ["HidHide konnte nicht eingerichtet werden (abgebrochen oder fehlgeschlagen). Details im Protokoll."] =
            "Não foi possível configurar o HidHide (cancelado ou falhou). Detalhes no registo.",
        ["Der Controller hat sich bewegt oder keine Bewegungsdaten geliefert.\nBitte flach auf den Tisch legen, nicht berühren und erneut versuchen."] =
            "O comando moveu-se ou não enviou dados de movimento.\nPouse-o na mesa sem tocar nele e tente novamente.",
        ["Spiel oder Programm wählen"] = "Escolher jogo ou programa",
        ["Profil exportieren"] = "Exportar perfil",
        ["Profil importieren"] = "Importar perfil",
        ["Verstanden"] = "Entendido",
        ["Einstellungen öffnen"] = "Abrir definições",
        ["Willkommen"] = "Bem-vindo",

        // ---------- Neues Hauptfenster (Navigation, Seiten, Zeilen) ----------
        ["Allgemein"] = "Geral",
        ["Sticks & Vibration"] = "Sticks e vibração",
        ["Gyro & Maus"] = "Giroscópio e rato",
        ["Joy-Con & Wii"] = "Joy-Con e Wii",
        ["Ein"] = "Sim",
        ["Aus"] = "Não",
        ["Verbundene Controller mit Live-Anzeige. Über „Einstellungen“ an einem Controller passt du genau diesen an."] =
            "Comandos ligados com visualização em direto. Com « Definições » num comando ajusta exatamente esse.",
        ["Jede Taste kann ein Gamepad-Knopf, eine Tastaturtaste, ein Mausklick, Turbo oder ein Makro sein. " +
         "Tipp: Drückst du eine Taste am Controller, wird ihre Zeile hervorgehoben."] =
            "Cada botão pode ser um botão de gamepad, uma tecla, um clique do rato, turbo ou uma macro. " +
            "Dica: prima um botão no comando para destacar a sua linha.",
        ["Profil"] = "Perfil",
        ["Neu"] = "Novo",
        ["Umbenennen, löschen, exportieren, importieren"] = "Mudar o nome, eliminar, exportar, importar",
        ["Ein eigenes Profil gilt automatisch, solange eines seiner Programme im Vordergrund ist – sonst „Standard“."] =
            "Um perfil próprio aplica-se automaticamente enquanto um dos seus programas estiver em primeiro plano – senão « Predefinido ».",
        ["Aktiv bei Programm"] = "Ativo com o programa",
        ["Programmdateien, bei denen dieses Profil gilt (mit Komma trennen)."] = "Ficheiros de programa para os quais este perfil se aplica (separar por vírgulas).",
        ["Standard gilt für alle Programme"] = "O predefinido aplica-se a todos os programas",
        ["Wählen …"] = "Escolher …",
        ["Bearbeiten"] = "Editar",
        ["Jeder Controller hat seine eigene Belegung."] = "Cada comando tem a sua própria atribuição.",
        ["Ebene"] = "Camada",
        ["Normal"] = "Normal",
        ["Shift-Ebene"] = "Camada Shift",
        ["Die Shift-Ebene gilt, solange eine Taste mit „Shift-Ebene“ gehalten wird."] = "A camada Shift aplica-se enquanto um botão definido como « camada Shift » estiver premido.",
        ["Tasten"] = "Botões",
        ["Standardwerte für alle Controller. Eigene Werte für einzelne Controller stellst du unten oder in der Übersicht ein."] =
            "Valores predefinidos para todos os comandos. Defina valores próprios por comando abaixo ou na vista geral.",
        ["Sticks"] = "Sticks",
        ["Totzone"] = "Zona morta",
        ["So weit lässt sich ein Stick bewegen, bevor er wirkt (gegen Abdriften)."] = "Até onde um stick pode mover-se antes de reagir (contra a deriva).",
        ["Kennlinie"] = "Curva de resposta",
        ["„linear“ = gleichmäßig. Höher = feiner um die Mitte (präzises Zielen), niedriger = schneller."] =
            "« linear » = uniforme. Mais alta = mais fino ao centro (mira precisa), mais baixa = mais rápido.",
        ["Analoge Trigger (GameCube)"] = "Gatilhos analógicos (GameCube)",
        ["So weit lässt sich ein Trigger drücken, bevor er wirkt."] = "Até onde um gatilho pode ser premido antes de reagir.",
        ["Voll gedrückt ab"] = "Premido a fundo a partir de",
        ["Ab hier gilt der Trigger als ganz gedrückt (100 % = erst am Anschlag)."] = "A partir daqui o gatilho conta como premido a fundo (100 % = só no batente).",
        ["Spiele dürfen den Controller vibrieren lassen."] = "Os jogos podem fazer o comando vibrar.",
        ["Stärke"] = "Intensidade",
        ["Turbo-Geschwindigkeit"] = "Velocidade do turbo",
        ["Wie oft pro Sekunde Tasten mit „Turbo“ auslösen."] = "Quantas vezes por segundo os botões « turbo » disparam.",
        ["Eigene Werte je Controller"] = "Valores próprios por comando",
        ["Werte nur für diesen Controller – ohne eigenen Wert gilt der allgemeine."] = "Valores apenas para este comando – sem valor próprio aplica-se o geral.",
        ["Bewegungssteuerung: Zielen per Gyro und den Controller als Maus nutzen."] = "Controlo por movimento: apontar com o giroscópio e usar o comando como rato.",
        ["Gyro als rechter Stick"] = "Giroscópio como stick direito",
        ["Modus"] = "Modo",
        ["Zum Zielen in Spielen ohne eigene Gyro-Steuerung. „Gyro-Stick“ kann auch einer Taste zugewiesen werden."] =
            "Para apontar em jogos sem controlo giroscópio próprio. « Stick giroscópio » também pode ser atribuído a um botão.",
        ["Aus (nur per Taste „Gyro-Stick“)"] = "Desativado (apenas por botão « stick giroscópio »)",
        ["Immer"] = "Sempre",
        ["Beim Zielen (solange ZL / LT gedrückt)"] = "Ao apontar (enquanto ZL / LT está premido)",
        ["Empfindlichkeit"] = "Sensibilidade",
        ["Drehgeschwindigkeit für vollen Stick-Ausschlag – kleiner = empfindlicher."] = "Velocidade de rotação para deflexão total do stick – mais baixa = mais sensível.",
        ["Mindestausschlag"] = "Deflexão mínima",
        ["Überwindet die Stick-Totzone des Spiels bei kleinen Bewegungen."] = "Ultrapassa a zona morta do stick do jogo em pequenos movimentos.",
        ["Hoch/runter umkehren"] = "Inverter cima/baixo",
        ["Links/rechts umkehren"] = "Inverter esquerda/direita",
        ["Gyro-Maus"] = "Rato giroscópio",
        ["Geschwindigkeit"] = "Velocidade",
        ["Mauszeiger per Bewegung – über eine Taste mit „Gyro-Maus“ (Tastenbelegung)."] = "Ponteiro do rato por movimento – através de um botão « rato giroscópio » (atribuição de botões).",
        ["Mausrichtung (Gyro-Maus und Joy-Con-Maus)"] = "Direção do rato (rato giroscópio e rato Joy-Con)",
        ["Gyro-Funktionen einer Taste zuweisen"] = "Atribuir funções de giroscópio a um botão",
        ["Gyro-Maus oder Gyro-Stick ein/aus bzw. solange gehalten"] = "Rato giroscópio ou stick giroscópio ligar/desligar ou enquanto premido",
        ["Joy-Con als Paar oder einzeln, Joy-Con 2 als Maus und Wii-Controller."] = "Joy-Con em par ou individuais, Joy-Con 2 como rato e comandos Wii.",
        ["Zu einem Controller zusammenfassen"] = "Combinar num só comando",
        ["Ein linker und ein rechter Joy-Con werden automatisch ein Paar."] = "Um Joy-Con esquerdo e um direito formam automaticamente um par.",
        ["Gyro beim Paar vom"] = "Giroscópio do par a partir de",
        ["Rechter Joy-Con (wie Switch)"] = "Joy-Con direito (como na Switch)",
        ["Linker Joy-Con"] = "Joy-Con esquerdo",
        ["Paar lösen oder verbinden"] = "Separar ou juntar um par",
        ["Einen Joy-Con quer halten und SL oder SR drücken löst ihn aus dem Paar. L am linken und R am rechten Joy-Con gleichzeitig drücken verbindet sie wieder. Die Wahl wird je Joy-Con gemerkt."] =
            "Segure um Joy-Con na horizontal e prima SL ou SR para o separar do par. Premir L no esquerdo e R no direito em simultâneo volta a juntá-los. A escolha é memorizada por Joy-Con.",
        ["Joy-Con 2 als Maus"] = "Joy-Con 2 como rato",
        ["Als Maus, wenn er auf dem Tisch liegt"] = "Como rato quando está na mesa",
        ["Joy-Con 2 auf die Seite legen und wie eine Maus schieben."] = "Pouse o Joy-Con 2 de lado e deslize-o como um rato.",
        ["Mausgeschwindigkeit"] = "Velocidade do rato",
        ["Tasten im Mausmodus"] = "Botões no modo rato",
        ["R/L = Linksklick, ZR/ZL = Rechtsklick, Stick drücken = Mittelklick, Stick hoch/runter = Scrollen."] =
            "R/L = clique esquerdo, ZR/ZL = clique direito, premir o stick = clique do meio, stick para cima/baixo = deslocar.",
        ["Zeiger steuert die Maus"] = "O ponteiro move o rato",
        ["Wii-Fernbedienung auf die Sensorleiste richten, um den Mauszeiger zu bewegen."] = "Aponte o comando Wii para a barra de sensores para mover o ponteiro.",
        ["Wie Spiele die Controller sehen, Verbindung, Darstellung und Programm."] = "Como os jogos veem os comandos, ligação, aspeto e programa.",
        ["Ausgabe"] = "Saída",
        ["Controller erscheint als"] = "O comando aparece como",
        ["Xbox 360 läuft mit fast allen Spielen. DualShock 4 bietet Bewegungssteuerung (Steam, Emulatoren)."] =
            "Xbox 360 funciona com quase todos os jogos. DualShock 4 oferece controlo por movimento (Steam, emuladores).",
        ["Xbox 360 läuft mit fast allen Spielen und Steam. DualShock 4 bietet zusätzlich Bewegungssteuerung (Steam, Emulatoren). Gilt für alle Controller ohne eigene Einstellung (Karte → Einstellungen → Tasten)."] =
            "Xbox 360 funciona com quase todos os jogos e Steam. DualShock 4 adiciona controlo por movimento (Steam, emuladores). Aplica-se a todos os comandos sem definição própria (cartão → Definições → Botões).",
        ["Original-Controller verstecken"] = "Ocultar comandos originais",
        ["Controller verbinden"] = "Ligar comandos",
        ["SYNC-Taste am Controller drücken – N-Connect findet und koppelt ihn selbst. Danach reicht künftig ein Tastendruck."] =
            "Prima o botão SYNC do comando – o N-Connect encontra-o e emparelha-o sozinho. Depois basta um toque.",
        ["So kommt der Controller in den Kopplungsmodus"] = "Como colocar o comando em modo de emparelhamento",
        ["Kurz die kleine SYNC-Taste drücken."] = "Prima brevemente o pequeno botão SYNC.",
        ["SYNC-Taste drücken, bis die Lichter laufen."] = "Prima o botão SYNC até as luzes correrem.",
        ["Batteriefach öffnen und die rote SYNC-Taste drücken."] = "Abra o compartimento das pilhas e prima o botão SYNC vermelho.",
        ["Die SYNC-Taste auf der Unterseite drücken."] = "Prima o botão SYNC na parte inferior.",
        ["PS + Teilen bzw. Create halten, bis die Lichtleiste schnell blinkt."] =
            "Mantenha PS + Share/Create premidos até a barra de luz piscar rapidamente.",
        ["Kopplungstaste oben halten, bis die Xbox-Taste blinkt."] = "Mantenha o botão de emparelhamento superior até o botão Xbox piscar.",
        ["Status"] = "Estado",
        ["Suche läuft …"] = "Procura em curso …",
        ["Suche läuft – jetzt SYNC drücken …"] = "Procura em curso – prima SYNC agora …",
        ["Weitere Controller? Einfach SYNC drücken."] = "Mais comandos? Basta premir SYNC.",
        ["Wartet auf einen Controller im Kopplungsmodus."] = "A aguardar um comando em modo de emparelhamento.",
        ["Suche beendet"] = "Procura terminada",
        ["Die Controller stehen in der Übersicht und verbinden sich künftig per Tastendruck."] =
            "Os comandos estão na vista geral e ligar-se-ão com um toque.",
        ["Kein Controller im Kopplungsmodus gefunden. SYNC-Taste drücken und „Erneut suchen“ klicken."] =
            "Nenhum comando em modo de emparelhamento encontrado. Prima SYNC e clique « Procurar novamente ».",
        ["Verbunden"] = "Ligado",
        ["Erneut suchen"] = "Procurar novamente",
        ["Fertig"] = "Concluir",
        ["Im Spiel"] = "No jogo",
        ["Dreht …"] = "A rodar …",
        ["Testdrehung (360°)"] = "Rotação de teste (360°)",
        ["Testdrehung"] = "Rotação de teste",
        ["aus"] = "desativado",
        ["Gyro-Beschleunigung"] = "Aceleração do giroscópio",
        ["Bei schneller Drehung"] = "Com rotação rápida",
        ["Langsame Bewegungen bleiben fein, schnelle drehen weiter (wie JoyShockMapper). Voll ab 120 °/s, unter 20 °/s normal. Gilt für Gyro-Stick und Gyro-Maus."] =
            "Movimentos lentos ficam precisos, os rápidos rodam mais (como o JoyShockMapper). Total a partir de 120 °/s, normal abaixo de 20 °/s. Aplica-se ao stick giroscópio e ao rato giroscópio.",
        ["Flick-Stick (Spiele mit Maussteuerung)"] = "Flick stick (jogos com controlo por rato)",
        ["Flick-Stick"] = "Flick stick",
        ["Rechten Stick in eine Richtung schieben = Kamera dreht sofort dorthin; am Rand drehen = Kamera dreht mit. Zielen dann per Gyro. Der rechte Stick geht nicht mehr ans Spiel."] =
            "Empurrar o stick direito numa direção = a câmara roda imediatamente para lá; rodando-o no rebordo = a câmara acompanha. Depois mira-se com o giroscópio. O stick direito deixa de ir para o jogo.",
        ["Mausbewegung je Umdrehung"] = "Movimento do rato por volta",
        ["Je Spiel einmal einstellen: „Testdrehung“ klicken, ins Spiel wechseln – nach 3 s dreht die Kamera einmal. Genau eine volle Drehung = richtig."] =
            "A ajustar uma vez por jogo: clique « Rotação de teste », mude para o jogo – após 3 s a câmara roda uma vez. Exatamente uma volta completa = correto.",
        ["Flick-Dauer"] = "Duração do flick",
        ["So lange dauert die Drehung beim Flick (0 = sofort)."] = "Quanto dura a rotação de um flick (0 = instantânea).",
        ["Gyro-Maus oder Gyro-Stick ein/aus bzw. solange gehalten, „Gyro anhalten“ (Ratchet: Controller zurückführen, ohne dass sich das Ziel bewegt)"] =
            "Rato giroscópio ou stick giroscópio ligar/desligar ou enquanto premido, « suspender giroscópio » (ratchet: trazer o comando de volta sem mover a mira)",
        ["✋  Gyro anhalten (solange gehalten, „Ratchet“)"] = "✋  Suspender giroscópio (enquanto premido, « ratchet »)",
        ["Spieler-LED und Lichtleiste vom Spiel"] = "LED do jogador e barra de luz do jogo",
        ["Die Spieler-LEDs zeigen den Xbox-Platz, den Windows vergibt. Bei DualShock 4 steuert die Lichtleiste des Spiels die HOME-LED (Switch 1 Pro Controller, rechter Joy-Con)."] =
            "Os LEDs de jogador indicam o lugar Xbox atribuído pelo Windows. No DualShock 4, a barra de luz do jogo controla o LED HOME (Pro Controller Switch 1, Joy-Con direito).",
        ["HidHide installieren …"] = "Instalar HidHide …",
        ["Empfohlen: Steam und viele Spiele kennen Switch-1-, NSO- und USB-Controller selbst und sähen sie sonst doppelt. Läuft nach der Installation ohne Rückfrage (sonst fragt Windows nach Adminrechten)."] =
            "Recomendado: o Steam e muitos jogos reconhecem por si comandos Switch 1, NSO e USB e veriam-nos duplicados. Após a instalação funciona sem perguntas (senão o Windows pede direitos de administrador).",
        ["Steam und viele Spiele sehen Switch-1-, NSO- und USB-Controller sonst doppelt. Dafür wird das kostenlose HidHide gebraucht (bei der N-Connect-Installation dabei, hier nachträglich)."] =
            "Senão, o Steam e muitos jogos veem comandos Switch 1, NSO e USB em duplicado. É preciso o gratuito HidHide (incluído na instalação do N-Connect, instalável aqui depois).",
        ["Erscheint als"] = "Aparece como",
        ["Wie allgemein"] = "Como em Geral",
        ["Nur für diesen Controller. Xbox 360 läuft überall; DualShock 4 bringt zusätzlich Gyro nach Steam und in Emulatoren. „Wie allgemein“ folgt der Seite „Allgemein“."] =
            "Apenas para este comando. Xbox 360 funciona em todo o lado; DualShock 4 adiciona giroscópio no Steam e emuladores. « Como em Geral » segue a página « Geral ».",
        ["Der echte Xbox-Controller – Spiele sehen ihn von Windows aus direkt. Belegungen hier wirken auf Sonderaktionen (Tastatur, Makros, Gyro), nicht auf den Controller selbst."] =
            "O comando Xbox verdadeiro – os jogos veem-no já diretamente do Windows. As atribuições aqui atuam nas ações especiais (teclado, macros, giroscópio), não no próprio comando.",
        ["Steam und manche Spiele sehen diesen Controller sonst doppelt. Abhilfe: HidHide installieren (Seite „Allgemein“ → „Original-Controller verstecken“)."] =
            "Senão, o Steam e alguns jogos veem este comando em duplicado. Solução: instalar o HidHide (página « Geral » → « Ocultar comandos originais »).",
        ["Original-Controller vor Spielen versteckt. Steam bitte einmal neu starten – danach sieht es nur noch den virtuellen Controller."] =
            "Comandos originais ocultados dos jogos. Reinicie o Steam uma vez – depois vê apenas o comando virtual.",
        ["Original-Controller vor Spielen versteckt – Steam und Spiele sehen nur noch den virtuellen Controller."] =
            "Comandos originais ocultados dos jogos – o Steam e os jogos passam a ver apenas o comando virtual.",
        ["Original-Controller nicht versteckt (Abfrage abgebrochen). Nachholen: Controller → Einstellungen → Extras → „Doppelt angezeigt?“."] =
            "Comandos originais não ocultados (pedido cancelado). Para mais tarde: comando → Definições → Extras → « Aparece em duplicado? ».",
        ["Tastenanordnung A/B/X/Y"] = "Disposição dos botões A/B/X/Y",
        ["Xbox: nach Position (untere Taste = A). Nintendo: nach Beschriftung (A bleibt A)."] = "Xbox: por posição (botão inferior = A). Nintendo: por rótulo (A continua A).",
        ["Verbinden"] = "Ligação",
        ["Per Tastendruck verbinden"] = "Ligar com um toque",
        ["Gekoppelte Controller verbinden sich ohne SYNC-Taste."] = "Os comandos emparelhados ligam-se sem o botão SYNC.",
        ["Ohne Eingabe trennen nach"] = "Desligar sem ação após",
        ["Spart Akku, wenn ein Controller liegen bleibt."] = "Poupa bateria quando um comando fica pousado.",
        ["N-Connect startet unsichtbar im Infobereich."] = "O N-Connect inicia discretamente na área de notificação.",
        ["Darstellung und Sprache"] = "Aspeto e idioma",
        ["Farbmodus"] = "Modo de cor",
        ["Mica-Effekt"] = "Efeito Mica",
        ["Durchscheinende Titelleiste (ab Windows 11)."] = "Barra de título translúcida (a partir do Windows 11).",
        ["Erweitert"] = "Avançado",
        ["Gyro für Emulatoren (DSU)"] = "Giroscópio para emuladores (DSU)",
        ["Cemuhook-Server auf Port 26760 – wirkt nach einem Neustart von N-Connect."] = "Servidor Cemuhook na porta 26760 – ativo após reiniciar o N-Connect.",
        ["Nach Updates suchen"] = "Procurar atualizações",
        ["Beim Start auf GitHub nach einer neuen Version suchen."] = "Procurar uma nova versão no GitHub ao iniciar.",
        ["Tastenbelegungen und Werte zurücksetzen. Gekoppelte Controller bleiben erhalten."] = "Repor atribuições de botões e valores. Os comandos emparelhados mantêm-se.",
        ["Zurücksetzen"] = "Repor",

        // ---------- Controller-Karte ----------
        ["Einstellungen"] = "Definições",
        ["Tastenbelegung und Einstellungen nur für diesen Controller"] = "Atribuição de botões e definições apenas para este comando",
        ["Feineinstellung"] = "Ajuste fino",
        ["Gyro"] = "Giroscópio",
        ["Extras"] = "Extras",
        ["Belegung für alle Spiele (Standard) oder ein eigenes Profil."] = "Atribuição para todos os jogos (predefinido) ou um perfil próprio.",
        ["Profile"] = "Perfis",
        ["Profile anlegen, umbenennen, exportieren …"] = "Criar, mudar o nome, exportar perfis …",
        ["Drück eine Taste am Controller – ihre Zeile leuchtet auf. ⌨ weist eine Tastaturtaste zu, ↺ setzt zurück."] =
            "Prima um botão no comando – a sua linha acende. ⌨ atribui uma tecla do teclado, ↺ repõe.",
        ["Tastatur-Taste zuweisen: klicken und die gewünschte Taste oder Kombination drücken."] = "Atribuir uma tecla do teclado: clique e prima a tecla ou combinação pretendida.",
        ["Zurück auf die Standardbelegung"] = "Voltar à atribuição predefinida",
        ["Ohne eigenen Wert gilt der allgemeine Wert der Seite „Sticks & Vibration“."] = "Sem valor próprio aplica-se o geral da página « Sticks e vibração ».",
        ["Stick-Totzone"] = "Zona morta do stick",
        ["Stick-Kennlinie"] = "Curva do stick",
        ["Trigger-Totzone"] = "Zona morta do gatilho",
        ["Trigger voll gedrückt ab"] = "Gatilho premido a fundo a partir de",
        ["Vibrationsstärke"] = "Intensidade da vibração",
        ["Gyro-Maus-Geschwindigkeit"] = "Velocidade do rato giroscópio",
        ["Eigenen Wert entfernen – es gilt wieder der allgemeine Wert"] = "Remover o valor próprio – volta a aplicar-se o geral",
        ["Kalibrieren"] = "Calibrar",
        ["Controller ruhig auf den Tisch legen und klicken: misst den Nullpunkt neu (gegen Abdriften)."] =
            "Pouse o comando na mesa e clique: mede novamente o ponto zero (contra a deriva).",
        ["Gyro als rechter Stick und Mausrichtung"] = "Giroscópio como stick direito e direção do rato",
        ["Gilt für alle Controller"] = "Aplica-se a todos os comandos",
        ["Paar"] = "Par",
        ["Joy-Con quer halten und SL oder SR drücken löst das Paar, L + R gleichzeitig verbindet es."] =
            "Segure um Joy-Con na horizontal e prima SL ou SR para separar o par; L + R em simultâneo junta-o.",
        ["Haltung"] = "Orientação",
        ["Quer"] = "Horizontal",
        ["Hochkant"] = "Vertical",
        ["Quer wie an der Switch oder hochkant – hochkant gilt die Belegung von „Joy-Con-Paar“."] =
            "Horizontal como na Switch ou vertical – na vertical aplica-se a atribuição de « par de Joy-Con ».",
        ["Mausmodus, Geschwindigkeit und Tasten"] = "Modo rato, velocidade e botões",
        ["Lesen …"] = "Ler …",
        ["Einschalten"] = "Ativar",
        ["Ausschalten"] = "Desativar",
        ["Wird gesucht …"] = "A procurar …",
        ["Öffnen"] = "Abrir",
        ["Verstecken"] = "Ocultar",
        ["amiibo an den NFC-Leser halten und als Datei (.bin) speichern – z. B. für Emulatoren."] =
            "Segure um amiibo sobre o leitor NFC e guarde-o como ficheiro (.bin) – p. ex. para emuladores.",
        ["Zusammendrücken = rechter Trigger, auseinanderziehen = linker Trigger. Beim Einschalten nicht berühren."] =
            "Apertar = gatilho direito, afastar = gatilho esquerdo. Não o toque ao ativar.",
        ["Live-Bild der Infrarotkamera im rechten Joy-Con."] = "Imagem em direto da câmara de infravermelhos do Joy-Con direito.",
        ["Doppelt angezeigt?"] = "Aparece em duplicado?",
        ["Versteckt den Original-Controller vor Steam und Spielen (HidHide) – sie sehen dann nur den virtuellen Controller."] =
            "Oculta o comando original do Steam e dos jogos (HidHide) – passam a ver apenas o comando virtual.",
        ["bereit (auf den Tisch legen)"] = "pronto (pouse-o na mesa)",
        ["amiibo-Abbild (*.bin)|*.bin"] = "Imagem amiibo (*.bin)|*.bin",
        ["Controller-Profil (*.ncprofile.json)|*.ncprofile.json|JSON (*.json)|*.json"] = "Perfil de comando (*.ncprofile.json)|*.ncprofile.json|JSON (*.json)|*.json",
        ["Programme (*.exe)|*.exe"] = "Programas (*.exe)|*.exe",
        ["Kein Controller verbunden\n\n" +
         "Switch-2-Controller: kurz die SYNC-Taste drücken – danach reicht ein beliebiger Tastendruck.\n" +
         "Switch-1-, NSO- und Wii-Controller: SYNC-Taste drücken – N-Connect koppelt sie selbst.\n" +
         "Oder hier gezielt suchen und koppeln:"] =
            "Nenhum comando ligado\n\n" +
            "Comandos Switch 2: prima brevemente o botão SYNC – depois basta qualquer toque.\n" +
            "Comandos Switch 1, NSO e Wii: prima o botão SYNC – o N-Connect emparelha-os sozinho.\n" +
            "Ou procure e emparelhe diretamente aqui:",
        ["Controller suchen …"] = "Procurar comandos …",
        ["Kein Controller verbunden"] = "Nenhum comando ligado",
        ["Switch-1-, NSO- und Wii-Controller suchen und koppeln (SYNC-Taste drücken)."] =
            "Procurar e emparelhar comandos Switch 1, NSO e Wii (prima o botão SYNC).",
        ["Neue Controller automatisch koppeln"] = "Emparelhar automaticamente novos comandos",
        ["Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive, Wii und PlayStation: einfach SYNC " +
         "drücken – kein Umweg über die Windows-Bluetooth-Einstellungen. Gesucht wird nur, solange niemand spielt."] =
            "Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive, Wii e PlayStation: basta premir SYNC – " +
            "sem passar pelas definições Bluetooth do Windows. A procura só acontece enquanto ninguém joga.",
        ["Gezielt suchen"] = "Procura direcionada",
        ["Sucht eine Minute lang nach Controllern im Kopplungsmodus."] = "Procura comandos em modo de emparelhamento durante um minuto.",
        ["Controller koppeln …"] = "Emparelhar comando …",
        ["Controller koppeln"] = "Emparelhar comando",
        ["Linken Joy-Con umbenennen …"] = "Mudar o nome do Joy-Con esquerdo …",
        ["Rechten Joy-Con umbenennen …"] = "Mudar o nome do Joy-Con direito …",
        ["Controller umbenennen"] = "Mudar o nome do comando",
        ["Spielerplatz"] = "Lugar do jogador",
        ["N-Connect aktualisieren"] = "Atualizar N-Connect",
        ["HidHide aktualisieren"] = "Atualizar HidHide",
        ["HidHide-Update verfügbar"] = "Atualização do HidHide disponível",
        ["HidHide aktuell halten"] = "Manter o HidHide atualizado",
        ["Beim Start nach einer neuen HidHide-Version suchen. Installiert wird nur nach Rückfrage (geprüfter Download vom Hersteller, Neustart nötig)."] =
            "Procurar uma nova versão do HidHide ao iniciar. Instala apenas após confirmação (download verificado do fabricante, reinício necessário).",
        ["Der Download hat nicht geklappt oder die Datei war fehlerhaft. Die Release-Seite im Browser öffnen?"] =
            "O download falhou ou o ficheiro estava defeituoso. Abrir a página da versão no navegador?",
        ["Alle Controller trennen"] = "Desligar todos os comandos",
        ["Sticks kalibrieren"] = "Calibrar sticks",
        ["Kalibrieren …"] = "Calibrar …",
        ["Gegen Drift oder zu kleinen Ausschlag: Mitte und Rand neu messen. Wird nur in N-Connect gespeichert, der Controller bleibt unverändert."] =
            "Contra a deriva ou o curso demasiado curto: medir novamente centro e rebordo. Guardado apenas no N-Connect, o comando fica inalterado.",
        ["Linker Stick"] = "Stick esquerdo",
        ["Rechter Stick"] = "Stick direito",
        ["Stick"] = "Stick",
        ["Stick (linker Joy-Con)"] = "Stick (Joy-Con esquerdo)",
        ["Stick (rechter Joy-Con)"] = "Stick (Joy-Con direito)",
        ["Neu messen"] = "Medir novamente",
        ["Werkswerte"] = "Valores de fábrica",
        ["Der Punkt zeigt, wo der Stick gerade steht. Steht er losgelassen nicht in der Mitte oder erreicht er den Kreis nicht, auf „Neu messen“ klicken."] =
            "O ponto indica onde está o stick. Se não estiver centrado ao soltar ou não alcançar o círculo, clique « Medir novamente ».",
        ["Gilt gerade: eigene Kalibrierung."] = "Atualmente em uso: calibração própria.",
        ["Gilt gerade: Werkswerte des Controllers."] = "Atualmente em uso: valores de fábrica do comando.",
        ["1/2 – Stick loslassen und den Controller ruhig halten …"] = "1/2 – solte o stick e segure o comando imóvel …",
        ["2/2 – Stick bis zum Anschlag drücken und langsam ein- bis zweimal im Kreis drehen."] =
            "2/2 – empurre o stick até ao fim e rode-o lentamente em círculo uma a duas vezes.",
        ["Fertig. „Übernehmen“ speichert die neue Kalibrierung für diesen Controller."] = "Concluído. « Aplicar » guarda a nova calibração para este comando.",
        ["Der Stick hat den Rand nicht erreicht. Bitte bis zum Anschlag drücken und erneut messen."] =
            "O stick não alcançou o rebordo. Empurre-o até ao fim e meça novamente.",
        ["Übernommen ✓ – gilt ab sofort."] = "Aplicado ✓ – ativo de imediato.",
        ["Werkswerte des Controllers gelten wieder."] = "Voltam a aplicar-se os valores de fábrica do comando.",
        ["Gyro einrichten"] = "Configurar o giroscópio",
        ["Einrichten …"] = "Configurar …",
        ["Zielen per Bewegung einrichten"] = "Configurar a mira por movimento",
        ["Schritt für Schritt: Nullpunkt, wann der Gyro zielt, Empfindlichkeit – mit Vorschau."] =
            "Passo a passo: ponto zero, quando o giroscópio mira, sensibilidade – com pré-visualização.",
        ["1  Nullpunkt"] = "1  Ponto zero",
        ["Controller flach auf den Tisch legen, nicht berühren – verhindert, dass das Ziel von selbst wandert."] =
            "Pouse o comando na mesa sem tocar nele – evita que a mira se desvie sozinha.",
        ["Nullpunkt messen"] = "Medir o ponto zero",
        ["Der Controller hat sich bewegt – bitte flach hinlegen und erneut versuchen."] = "O comando moveu-se – pouse-o e tente novamente.",
        ["Nullpunkt gemessen ✓"] = "Ponto zero medido ✓",
        ["2  Wann zielt der Gyro?"] = "2  Quando mira o giroscópio?",
        ["Nur per Taste"] = "Apenas por botão",
        ["Beim Zielen (ZL/LT)"] = "Ao apontar (ZL/LT)",
        ["„Beim Zielen“: nur solange ZL (linker Trigger) gehalten wird – wie in vielen Shootern."] =
            "« Ao apontar »: apenas enquanto ZL (gatilho esquerdo) está premido – como em muitos shooters.",
        ["3  Empfindlichkeit"] = "3  Sensibilidade",
        ["Voller Ausschlag ab"] = "Deflexão total a partir de",
        ["Kleinerer Wert bei „Voller Ausschlag ab“ = empfindlicher. „Mindestausschlag“ überwindet die Totzone des Spiels."] =
            "Um valor mais baixo em « Deflexão total a partir de » = mais sensível. « Deflexão mínima » ultrapassa a zona morta do jogo.",
        ["Mitte"] = "Centro",
        ["Vorschau: Fadenkreuz folgt dem Controller (unabhängig von Schritt 2)."] = "Pré-visualização: a mira segue o comando (independentemente do passo 2).",
        ["Keine Bewegungsdaten"] = "Sem dados de movimento",
        ["Controller gekoppelt"] = "Comando emparelhado",
        ["Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive: SYNC-Taste drücken, bis die Lichter laufen.\n" +
         "Wii-Fernbedienung: Batteriefach öffnen und die rote SYNC-Taste drücken.\n" +
         "Wii U Pro Controller: die SYNC-Taste auf der Unterseite drücken.\n" +
         "Danach verbindet sich der Controller künftig per Tastendruck."] =
            "Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive: prima o botão SYNC até as luzes correrem.\n" +
            "Comando Wii: abra o compartimento das pilhas e prima o botão SYNC vermelho.\n" +
            "Wii U Pro Controller: prima o botão SYNC na parte inferior.\n" +
            "Depois o comando liga-se com um toque.",
        ["Suche … SYNC-Taste drücken (Xbox: Kopplungstaste oben halten, PlayStation: PS + Teilen/Create halten)."] =
            "A procurar … prima o botão SYNC (Xbox: mantenha o botão de emparelhamento superior; PlayStation: mantenha PS + Share/Create).",
        ["Kein Controller im Kopplungsmodus gefunden. SYNC-Taste drücken und erneut versuchen."] =
            "Nenhum comando em modo de emparelhamento encontrado. Prima SYNC e tente novamente.",
        ["Darstellung:"] = "Aspeto:",
        ["Dunkel"] = "Escuro",
        ["Hell"] = "Claro",
        ["Wie Windows"] = "Como o Windows",
        ["Mica-Effekt in der Titelleiste (ab Windows 11)"] = "Efeito Mica na barra de título (a partir do Windows 11)",

        // ---------- Fehlerfälle und Hinweise ----------
        ["Bluetooth ist ausgeschaltet."] = "O Bluetooth está desligado.",
        ["Dieser Bluetooth-Adapter unterstützt kein Bluetooth LE."] = "Este adaptador Bluetooth não suporta Bluetooth LE.",
        ["Bluetooth-Suche konnte nicht starten."] = "Não foi possível iniciar a procura Bluetooth.",
        ["Bluetooth in den Windows-Einstellungen einschalten."] = "Ligue o Bluetooth nas definições do Windows.",
        ["Controller per USB funktionieren weiterhin."] = "Os comandos por USB continuam a funcionar.",
        ["Für Switch-2-Controller wird ein Adapter mit Bluetooth 4.0 oder neuer gebraucht."] = "Os comandos Switch 2 precisam de um adaptador com Bluetooth 4.0 ou mais recente.",
        ["Andere Controller und USB funktionieren weiterhin."] = "Os outros comandos e o USB continuam a funcionar.",
        ["Bluetooth-Adapter (z. B. USB-Stick) einstecken bzw. Bluetooth in Windows aktivieren."] =
            "Ligue um adaptador Bluetooth (p. ex. uma pen USB) ou ative o Bluetooth no Windows.",
        ["Bluetooth ist bereit – Controller können verbunden werden."] = "Bluetooth pronto – é possível ligar comandos.",
        ["Bluetooth-Einstellungen öffnen"] = "Abrir definições Bluetooth",
        ["ViGEmBus-Treiber fehlt – ohne ihn kann kein virtueller Controller erzeugt werden."] =
            "Controlador ViGEmBus em falta – sem ele não é possível criar um comando virtual.",
        ["Bitte das Setup erneut ausführen."] = "Execute novamente a instalação.",
        ["Das Programm schließen oder in Steam die Nintendo-Unterstützung abschalten."] =
            "Feche esse programa ou desative o suporte Nintendo no Steam.",
        ["Erst einen anderen trennen."] = "Desligue primeiro outro comando.",
        ["Tipp: Bluetooth-Stick per Verlängerung näher an den Controller, weg von USB-3-Anschlüssen und Funkkopfhörern."] =
            "Dica: aproxime a pen Bluetooth do comando com uma extensão, longe de portas USB 3 e auscultadores sem fios.",
        ["Controller mit dem PC gekoppelt – ab jetzt reicht ein Tastendruck."] = "Comando emparelhado com o PC – daqui em diante basta um toque.",
        ["Hinweis: Um ihn wieder an der Switch 2 zu nutzen, dort einmal kurz SYNC drücken."] =
            "Nota: para o voltar a usar na Switch 2, prima uma vez brevemente SYNC na consola.",
        ["Dieser Bluetooth-Adapter unterstützt kein Bluetooth LE"] = "Este adaptador Bluetooth não suporta Bluetooth LE",
        ["Erst IR-Kamera bzw. Ring-Con ausschalten (sie nutzen denselben Zusatzprozessor wie der NFC-Leser)."] =
            "Desative primeiro a câmara IR ou o Ring-Con (usam o mesmo coprocessador que o leitor NFC).",
        ["Erst die IR-Kamera schließen (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "Feche primeiro a câmara IR (o Ring-Con e a câmara IR usam o mesmo coprocessador).",
        ["Erst den Ring-Con ausschalten (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "Desative primeiro o Ring-Con (o Ring-Con e a câmara IR usam o mesmo coprocessador).",
        ["amiibo zu früh entfernt"] = "amiibo retirado demasiado cedo",
        ["MCU startet nicht"] = "o coprocessador não inicia",
        ["NFC-Modus nicht aktiv"] = "modo NFC inativo",
        ["Kopplung fehlgeschlagen – Details im Protokoll."] = "Emparelhamento falhou – detalhes no registo.",

        // ---------- Kopplungsdaten (Switch-SD-Karte, anderer PC) ----------
        ["Kopplungsdaten"] = "Dados de emparelhamento",
        ["Kopplungen übernehmen oder weitergeben"] = "Aproveitar ou partilhar emparelhamentos",
        ["Kopplungsdaten von der Switch übernehmen"] = "Aproveitar os dados de emparelhamento da Switch",
        ["Von der Switch-SD-Karte (Bluepick_RCM/hekate) oder von einem anderen PC übernehmen, oder für einen anderen PC exportieren."] =
            "Aproveitar do cartão SD da Switch (Bluepick_RCM/hekate) ou de outro PC, ou exportar para outro PC.",
        ["Bei Switch-SD-Karte nachfragen"] = "Perguntar quando um cartão SD da Switch é inserido",
        ["Steckt eine SD-Karte der Switch im PC (Kartenleser oder hekate „USB Tools“), bietet N-Connect die Übernahme an. Die Karte wird nur gelesen."] =
            "Quando um cartão SD da Switch está no PC (leitor de cartões ou hekate « USB Tools »), o N-Connect propõe a importação. O cartão é apenas lido.",
        ["Switch-SD-Karte erkannt"] = "Cartão SD da Switch detetado",
        ["Kopplungsdaten der Controller gefunden – klicken, um sie anzusehen und zu übernehmen."] =
            "Dados de emparelhamento de comandos encontrados – clique para os ver e importar.",
        ["Klicken, um Kopplungsdaten der Controller zu übernehmen."] = "Clique para importar os dados de emparelhamento dos comandos.",
        ["Controller-Kopplungen von der Switch-SD-Karte oder von einem anderen PC übernehmen – oder für einen anderen PC exportieren. Es werden nur Einstellungen von N-Connect geändert; Windows und der Bluetooth-Adapter bleiben unverändert."] =
            "Importe emparelhamentos de comandos do cartão SD da Switch ou de outro PC – ou exporte-os para outro PC. Apenas as definições do N-Connect são alteradas; o Windows e o adaptador Bluetooth ficam inalterados.",
        ["Spieler-Reihenfolge – Spieler 1 ist für Windows, Steam und Spiele der erste Controller. Mit ‹ › umsortieren."] =
            "Ordem dos jogadores – o jogador 1 é o primeiro comando para o Windows, Steam e jogos. Reordene com ‹ ›.",
        ["Von der Switch-SD-Karte"] = "Do cartão SD da Switch",
        ["Mit Bluepick_RCM oder hekate erstellte Kopplungsdaten (switchroot/joycon_mac.ini)"] =
            "Dados de emparelhamento criados com Bluepick_RCM ou hekate (switchroot/joycon_mac.ini)",
        ["Einlesen …"] = "Ler …",
        ["Von einem anderen PC"] = "De outro PC",
        ["Mit N-Connect exportierte Datei (*.ncpair)"] = "Ficheiro exportado pelo N-Connect (*.ncpair)",
        ["Datei öffnen …"] = "Abrir ficheiro …",
        ["Inhalt"] = "Conteúdo",
        ["Weitergeben und sichern"] = "Partilhar e guardar",
        ["Für einen anderen PC exportieren"] = "Exportar para outro PC",
        ["Bekannte Controller und Einstellungen je Controller, optional mit Passwort"] =
            "Comandos conhecidos e definições por comando, opcionalmente com palavra-passe",
        ["Sicherung wiederherstellen"] = "Restaurar uma cópia de segurança",
        ["Vor jedem „Übernehmen“ wird automatisch eine Sicherung angelegt"] = "Uma cópia de segurança é criada automaticamente antes de cada « Aplicar »",
        ["Wiederherstellen …"] = "Restaurar …",
        ["Bluetooth-Adapter dieses PCs"] = "Adaptador Bluetooth deste PC",
        ["wird ermittelt …"] = "a detetar …",
        ["nicht gefunden"] = "não encontrado",
        ["Quelle wählen: Switch-SD-Karte (mit Bluepick_RCM oder hekate erstellte Kopplungsdaten) oder eine Datei von einem anderen PC."] =
            "Escolha uma fonte: cartão SD da Switch (dados de emparelhamento criados com Bluepick_RCM ou hekate) ou um ficheiro de outro PC.",
        ["Keine Switch-SD-Karte gefunden. SD-Karte in den Kartenleser stecken oder die Switch per hekate („USB Tools“ → „SD Card“) als Laufwerk verbinden.\n\nOrdner selbst auswählen?"] =
            "Nenhum cartão SD da Switch encontrado. Insira o cartão SD num leitor ou ligue a Switch como unidade via hekate (« USB Tools » → « SD Card »).\n\nEscolher a pasta manualmente?",
        ["Stammordner der Switch-SD-Karte wählen"] = "Escolher a pasta raiz do cartão SD da Switch",
        ["Switch-SD-Karte:"] = "Cartão SD da Switch:",
        ["Auf der Karte liegen keine Kopplungsdaten (switchroot/joycon_mac.ini)."] = "O cartão não contém dados de emparelhamento (switchroot/joycon_mac.ini).",
        ["So erstellst du sie: Joy-Con an die Switch stecken, Bluepick_RCM starten und „Dump Joy-Con BT pairing → SD“ (oder FULL AUTO) wählen. Alternativ in hekate: Nyx → Konsole → „Dump Joy-Con BT“."] =
            "Para os criar: ligue os Joy-Con à Switch, inicie o Bluepick_RCM e escolha « Dump Joy-Con BT pairing → SD » (ou FULL AUTO). Alternativamente no hekate: Nyx → Console → « Dump Joy-Con BT ».",
        ["Gefunden wurde eine Bluepick-Sicherung des Bluetooth-Speichers (8000000000000050.bin). Sie ist ein Switch-Speicherabbild und kann hier nicht ausgewertet werden."] =
            "Foi encontrada uma cópia Bluepick da memória Bluetooth (8000000000000050.bin). É uma imagem de memória da Switch e não pode ser analisada aqui.",
        ["Bluetooth-Adresse der Switch:"] = "Endereço Bluetooth da Switch:",
        ["Gefundene Controller:"] = "Comandos encontrados:",
        ["mit der Switch gekoppelt"] = "emparelhado com a Switch",
        ["zuletzt mit einem anderen Gerät gekoppelt (nicht der Switch)"] = "último emparelhamento com outro dispositivo (não a Switch)",
        ["Joy-Con (L)"] = "Joy-Con (E)",
        ["Joy-Con (R)"] = "Joy-Con (D)",
        ["HORI-Controller (links)"] = "Comando HORI (esquerdo)",
        ["HORI-Controller (rechts)"] = "Comando HORI (direito)",
        ["Hinweis: Pro Controller stehen nur im Bluetooth-Speicher der Switch (8000000000000050.bin); dieses Speicherabbild kann N-Connect nicht auswerten."] =
            "Nota: os Pro Controller figuram apenas na memória Bluetooth da Switch (8000000000000050.bin); o N-Connect não consegue analisar esta imagem de memória.",
        ["Was diese Daten können – und was nicht:"] = "O que estes dados permitem – e o que não permitem:",
        ["Die Daten zeigen, welche Controller mit deiner Switch gekoppelt sind und an welche Bluetooth-Adresse sie gebunden sind."] =
            "Os dados mostram quais comandos estão emparelhados com a sua Switch e a que endereço Bluetooth estão ligados.",
        ["Ein Switch-1-Controller verbindet sich auf Tastendruck nur mit dem Gerät, dessen Adresse er gespeichert hat – hier mit der Switch. Der Bluetooth-Adapter des PCs hat eine andere Adresse, deshalb kann Windows diese Kopplung nicht einfach weiterverwenden."] =
            "Um comando Switch 1 só se religa com um toque ao dispositivo cujo endereço memorizou – aqui a Switch. O adaptador Bluetooth do PC tem outro endereço, por isso o Windows não pode reutilizar este emparelhamento.",
        ["Die Adresse des PC-Adapters zu ändern, unterstützt N-Connect bewusst nicht (herstellerabhängig, riskant und nicht vorgesehen)."] =
            "O N-Connect não suporta deliberadamente a alteração do endereço do adaptador do PC (depende do fabricante, arriscado e não previsto).",
        ["Windows bietet keinen offiziellen Weg, fremde Kopplungsschlüssel einzutragen: Sie liegen in einem Teil der Registrierung, auf den nur das System zugreifen darf. N-Connect ändert dort nichts."] =
            "O Windows não oferece forma oficial de adicionar chaves de emparelhamento externas: ficam numa parte do registo reservada ao sistema. O N-Connect não a altera.",
        ["So klappt der Wechsel am einfachsten: am PC den Controller einmal per SYNC-Taste in den Windows-Bluetooth-Einstellungen koppeln. Zurück an der Switch die Joy-Con an die Konsole stecken bzw. den Pro Controller per USB-Kabel anschließen – dann sind sie ohne Menü wieder mit der Switch gekoppelt."] =
            "A forma mais simples de trocar: no PC, emparelhe o comando uma vez com o botão SYNC nas definições Bluetooth do Windows. De volta à Switch, encaixe os Joy-Con na consola ou ligue o Pro Controller por cabo USB – ficam novamente emparelhados sem menu.",
        ["„Übernehmen“ merkt sich diese Controller in N-Connect (Liste bekannter Controller, Zuordnung zur Switch). Kopplungsschlüssel werden nicht gespeichert."] =
            "« Aplicar » memoriza estes comandos no N-Connect (lista de comandos conhecidos, associação à Switch). As chaves de emparelhamento não são guardadas.",
        ["N-Connect-Kopplungsdaten"] = "Dados de emparelhamento N-Connect",
        ["Kopplungsdaten von einem anderen PC öffnen"] = "Abrir dados de emparelhamento de outro PC",
        ["Die Datei ist zu groß."] = "O ficheiro é demasiado grande.",
        ["Keine Kopplungsdaten-Datei."] = "Não é um ficheiro de dados de emparelhamento.",
        ["Die Datei stammt von einer neueren N-Connect-Version."] = "O ficheiro provém de uma versão mais recente do N-Connect.",
        ["Die Datei ist mit einem Passwort geschützt."] = "O ficheiro está protegido por palavra-passe.",
        ["Falsches Passwort oder die Datei wurde verändert."] = "Palavra-passe incorreta ou ficheiro alterado.",
        ["Die Datei ist beschädigt."] = "O ficheiro está danificado.",
        ["Datei von:"] = "Ficheiro de:",
        ["Bluetooth-Adapter dort:"] = "Adaptador Bluetooth lá:",
        ["Bluetooth-Adapter hier:"] = "Adaptador Bluetooth aqui:",
        ["gekoppelt mit der Switch"] = "emparelhado com a Switch",
        ["gekoppelt mit dem anderen PC"] = "emparelhado com o outro PC",
        ["Weitere Einstellungen je Controller:"] = "Outras definições por comando:",
        ["Was du erwarten kannst:"] = "O que esperar:",
        ["Gleiche Adapter-Adresse (z. B. derselbe USB-Bluetooth-Stick umgesteckt): Switch-2-Controller verbinden sich hier auf Tastendruck wie am anderen PC."] =
            "Mesmo endereço do adaptador (p. ex. a mesma pen USB Bluetooth mudada): os comandos Switch 2 ligam-se aqui com um toque como no outro PC.",
        ["Switch-1-Controller (Pro Controller, Joy-Con) brauchen zusätzlich die Kopplung in Windows. Die kann N-Connect nicht übertragen – einmal per SYNC-Taste koppeln."] =
            "Os comandos Switch 1 (Pro Controller, Joy-Con) precisam ainda do emparelhamento no Windows. O N-Connect não o pode transferir – emparelhe uma vez com o botão SYNC.",
        ["Anderer Bluetooth-Adapter: Controller verbinden sich auf Tastendruck nur mit dem Gerät, mit dem sie zuletzt gekoppelt wurden. Hier einmal SYNC drücken – danach verbinden sie sich mit diesem PC (am anderen PC dann wieder per SYNC)."] =
            "Outro adaptador Bluetooth: os comandos só se religam com um toque ao dispositivo com que foram emparelhados por último. Prima SYNC uma vez aqui – depois ligam-se a este PC (no outro PC use SYNC novamente).",
        ["Tipp: Wer denselben USB-Bluetooth-Stick zwischen den PCs umsteckt, nimmt die Adresse mit – Switch-2-Controller verbinden sich dann an beiden PCs ohne SYNC."] =
            "Dica: quem muda a mesma pen USB Bluetooth entre PCs leva o endereço consigo – os comandos Switch 2 ligam-se em ambos os PCs sem SYNC.",
        ["Übernommen werden die Einstellungen je Controller (Joy-Con einzeln/hochkant, Gyro-Kalibrierung) und die Liste bekannter Controller."] =
            "São importadas as definições por comando (Joy-Con individual/vertical, calibração do giroscópio) e a lista de comandos conhecidos.",
        ["Die Datei enthält Kopplungsschlüssel. Windows bietet keinen offiziellen Weg, sie einzutragen – N-Connect übernimmt sie deshalb nicht."] =
            "O ficheiro contém chaves de emparelhamento. O Windows não oferece forma oficial de as adicionar – o N-Connect não as importa.",
        ["„Übernehmen“ ergänzt die Controller-Listen und Einstellungen von N-Connect (nichts wird gelöscht). Vorher wird eine Sicherung angelegt."] =
            "« Aplicar » acrescenta às listas de comandos e definições do N-Connect (nada é apagado). Antes é criada uma cópia de segurança.",
        ["Kopplungsdaten in N-Connect übernehmen? Vorher wird eine Sicherung der Einstellungen angelegt."] =
            "Importar os dados de emparelhamento para o N-Connect? Antes é criada uma cópia de segurança das definições.",
        ["Nichts zu ändern – diese Daten sind schon übernommen."] = "Nada a alterar – estes dados já foram importados.",
        ["Übernommen. Die Sicherung lässt sich hier über „Sicherung wiederherstellen“ zurückholen."] =
            "Concluído. A cópia de segurança pode ser restaurada aqui em « Restaurar uma cópia de segurança ».",
        ["Sicherung der Einstellungen"] = "Cópia de segurança das definições",
        ["Die Sicherung ist beschädigt und wurde nicht übernommen."] = "A cópia de segurança está danificada e não foi aplicada.",
        ["Alle Einstellungen durch diese Sicherung ersetzen?"] = "Substituir todas as definições por esta cópia de segurança?",
        ["Sicherung wiederhergestellt."] = "Cópia de segurança restaurada.",
        ["Kopplungsdaten für einen anderen PC speichern"] = "Guardar dados de emparelhamento para outro PC",
        ["Gespeichert. Die Datei am anderen PC in N-Connect unter „Joy-Con & Wii“ → „Kopplungsdaten“ → „Von einem anderen PC“ öffnen."] =
            "Guardado. No outro PC, abra o ficheiro no N-Connect em « Joy-Con e Wii » → « Dados de emparelhamento » → « De outro PC ».",
        ["Kopplungsdaten exportieren"] = "Exportar dados de emparelhamento",
        ["Passwort eingeben"] = "Introduzir palavra-passe",
        ["Passwort (optional). Ohne Passwort steht der Inhalt lesbar in der Datei. Mit Kopplungsschlüsseln ist ein Passwort Pflicht."] =
            "Palavra-passe (opcional). Sem palavra-passe o conteúdo fica legível no ficheiro. Com chaves de emparelhamento a palavra-passe é obrigatória.",
        ["Passwort"] = "Palavra-passe",
        ["Passwort wiederholen"] = "Repetir palavra-passe",
        ["Kopplungsschlüssel der Switch-Controller mitnehmen"] = "Incluir as chaves de emparelhamento dos comandos Switch",
        ["Kopplungsschlüssel mitnehmen (erst Switch-SD-Karte einlesen)"] = "Incluir as chaves de emparelhamento (ler primeiro um cartão SD da Switch)",
        ["Die Passwörter stimmen nicht überein."] = "As palavras-passe não coincidem.",
        ["Mit Schlüsseln: Passwort mit mindestens 8 Zeichen."] = "Com chaves: palavra-passe com pelo menos 8 caracteres.",
        ["Mindestens 8 Zeichen."] = "Pelo menos 8 caracteres.",
        ["Ohne Passwort."] = "Sem palavra-passe.",
    };

    /// <summary>Meldungen mit Platzhaltern (Portugiesisch).</summary>
    private static readonly (Regex Pattern, Func<Match, string> Replace)[] PatternsPt =
    [
        (Re(@"^Allgemeiner Wert \((?<v>.+)\) – Regler verschieben für einen eigenen$"), m => $"Valor geral ({m.Groups["v"]}) – mova o controlo para um valor próprio"),
        (Re(@"^Eigener Wert · allgemein: (?<v>.+)$"), m => $"Valor próprio · geral: {m.Groups["v"]}"),
        (Re(@"^Spieler (?<n>\d+)  ·  (?<k>.+?)(?<rest>(  ·  .*)?)$"), m => $"Jogador {m.Groups["n"]}  ·  {N(m, "k")}{T(m.Groups["rest"].Value)}"),
        (Re(@"^  ·  Gyro-Maus(?<r>.*)$"), m => "  ·  Rato giroscópio" + T(m.Groups["r"].Value)),
        (Re(@"^  ·  Gyro-Stick$"), _ => "  ·  Stick giroscópio"),
        (Re(@"^Spieler (?<n>\d+) · (?<k>.+?) (?<b>\d+ %.*)?$"), m => $"Jogador {m.Groups["n"]} · {N(m, "k")} {m.Groups["b"]}"),
        (Re(@"^(?<k>.+) verbunden \(Spieler (?<n>\d+)\)$"), m => $"{N(m, "k")} ligado (jogador {m.Groups["n"]})"),
        (Re(@"^Spieler (?<n>\d+) – tauschen mit (?<k>.+)$"), m => $"Jogador {m.Groups["n"]} – trocar com {N(m, "k")}"),
        (Re(@"^Spieler (?<n>\d+) – frei$"), m => $"Jogador {m.Groups["n"]} – livre"),
        (Re(@"^Spieler (?<n>\d+)$"), m => $"Jogador {m.Groups["n"]}"),
        (Re(@"^Xbox 360 · Platz (?<n>\d+)$"), m => $"Xbox 360 · lugar {m.Groups["n"]}"),
        (Re(@"^noch (?<n>\d+) s$"), m => $"mais {m.Groups["n"]} s"),
        (Re(@"^Fertig – (?<n>\d+) Controller verbunden$"), m => $"Concluído – {m.Groups["n"]} comando(s) ligado(s)"),
        (Re(@"^✓ (?<k>.+) verbunden – Spieler (?<n>\d+)$"), m => $"✓ {N(m, "k")} ligado – jogador {m.Groups["n"]}"),
        (Re(@"^Spieler (?<n>\d+)  ·  (?<v>.+)$"), m => $"Jogador {m.Groups["n"]}  ·  {m.Groups["v"]}"),
        (Re(@"^Gekoppelt: (?<k>.+) – verbindet gleich …$"), m => $"Emparelhado: {m.Groups["k"]} – a ligar …"),
        (Re(@"^Ins Spiel wechseln … (?<n>\d+)$"), m => $"Mudar para o jogo … {m.Groups["n"]}"),
        (Re(@"^(?<k>.+) ist jetzt Spieler (?<n>\d+)$"), m => $"{N(m, "k")} é agora o jogador {m.Groups["n"]}"),
        (Re(@"^Spieler (?<a>\d+) und (?<b>\d+) getauscht$"), m => $"Jogadores {m.Groups["a"]} e {m.Groups["b"]} trocados"),
        (Re(@"^Name für (?<k>.+) \(leer = Standardname\):$"), m => $"Nome para {N(m, "k")} (vazio = nome predefinido):"),
        (Re(@"^(?<k>.+) \(Joy-Con-Paar\)$"), m => $"{m.Groups["k"]} (par de Joy-Con)"),
        (Re(@"^Joy-Con zusammengefasst \(Spieler (?<n>\d+)\)$"), m => $"Joy-Con combinados (jogador {m.Groups["n"]})"),
        (Re(@"^Joy-Con getrennt – (?<k>.+) ist jetzt Spieler (?<n>\d+)$"), m => $"Joy-Con separado – {N(m, "k")} é agora o jogador {m.Groups["n"]}"),
        (Re(@"^Spieler (?<n>\d+): Akku (?<k>.+) fast leer \((?<p>\d+) %\) – bitte aufladen$"),
            m => $"Jogador {m.Groups["n"]}: bateria de {N(m, "k")} quase vazia ({m.Groups["p"]} %) – carregue"),
        (Re(@"^Spieler (?<n>\d+): nach (?<m>\d+) min ohne Eingabe getrennt$"),
            m => $"Jogador {m.Groups["n"]}: desligado após {m.Groups["m"]} min sem ação"),
        (Re(@"^Profil „(?<p>.+)“ aktiv$"), m => $"Perfil « {ProfileName(m.Groups["p"].Value)} » ativo"),
        (Re(@"^Profil: (?<p>.+)$"), m => $"Perfil: {ProfileName(m.Groups["p"].Value)}"),
        (Re(@"^Profil „(?<p>.+)“ löschen\?$"), m => $"Eliminar o perfil « {m.Groups["p"]} »?"),
        (Re(@"^Profil „(?<p>.+)“ importiert(?<r>.*)$"), m => $"Perfil « {m.Groups["p"]} » importado" + m.Groups["r"].Value.Replace("aktiv bei:", "ativo com:")),
        (Re(@"^⬇ Neue Version (?<v>.+) herunterladen …$"), m => $"⬇ Descarregar a nova versão {m.Groups["v"]} …"),
        (Re(@"^Version (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Herunterladen\.$"),
            m => $"A versão {m.Groups["v"]} está disponível (instalada: {m.Groups["i"]}). Clique para descarregar."),
        (Re(@"^Version (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Installieren\.$"),
            m => $"A versão {m.Groups["v"]} está disponível (instalada: {m.Groups["i"]}). Clique para instalar."),
        (Re(@"^⬇ Auf Version (?<v>.+) aktualisieren …$"), m => $"⬇ Atualizar para a versão {m.Groups["v"]} …"),
        (Re(@"^Lade Version (?<v>.+) herunter …$"), m => $"A descarregar a versão {m.Groups["v"]} …"),
        (Re(@"^HidHide (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Installieren\.$"),
            m => $"HidHide {m.Groups["v"]} está disponível (instalado: {m.Groups["i"]}). Clique para instalar."),
        (Re(@"^Lade HidHide (?<v>.+) herunter …$"), m => $"A descarregar o HidHide {m.Groups["v"]} …"),
        (Re(@"^(?<t>.+) · (?<r>\d+) Berichte/s$"), m => $"{T(m.Groups["t"].Value)} · {m.Groups["r"]} relatórios/s"),
        (Re(@"^(?<p>\d+ %)(?<v>  \(.*\))?  ⚡ lädt$"), m => $"{m.Groups["p"]}{m.Groups["v"]}  ⚡ a carregar"),
        (Re(@"^Speichern fehlgeschlagen: (?<e>.*)$"), m => $"Falha ao guardar: {m.Groups["e"]}"),
        (Re(@"^Lesen fehlgeschlagen: (?<e>.*)$"), m => $"Falha ao ler: {m.Groups["e"]}"),
        (Re(@"^amiibo konnte nicht gelesen werden: (?<e>.*)$"), m => $"Não foi possível ler o amiibo: {T(m.Groups["e"].Value)}"),
        (Re(@"^Gekoppelt: (?<k>.+)$"), m => $"Emparelhado: {m.Groups["k"]}"),
        (Re(@"^Gefunden: (?<k>.+) – kopple …$"), m => $"Encontrado: {m.Groups["k"]} – a emparelhar …"),
        (Re(@"^amiibo erkannt \((?<u>.+)\) – lese …$"), m => $"amiibo detetado ({m.Groups["u"]}) – a ler …"),
        (Re(@"^(?<n>\d+) Minuten$"), m => $"{m.Groups["n"]} minutos"),
        (Re(@"^✓ (?<n>\d+) Schritte, Dauer (?<ms>\d+) ms$"), m => $"✓ {m.Groups["n"]} passos, {m.Groups["ms"]} ms no total"),
        (Re(@"^Controller-Taste „(?<b>.+)“:\nJetzt die gewünschte Taste oder Tastenkombination drücken\.$"),
            m => $"Botão do comando « {T(m.Groups["b"].Value)} »:\nPrima agora a tecla ou combinação pretendida."),
        (Re(@"^Solange „(?<b>.+)“ gehalten wird, wird diese Taste schnell wiederholt gedrückt\n\(Geschwindigkeit unter 5\. „Turbo“\):$"),
            m => $"Enquanto « {T(m.Groups["b"].Value)} » estiver premido, este botão repete-se rapidamente\n(velocidade em 5. « Turbo »):"),
        (Re(@"^Ring-Con: (?<e>.*)$"), m => $"Ring-Con: {T(m.Groups["e"].Value)}"),
        (Re(@"^⌨  Taste: (?<k>.+)$"), m => $"⌨  Tecla: {m.Groups["k"]}"),
        (Re(@"^🔁  Turbo: Taste (?<k>.+)$"), m => $"🔁  Turbo: tecla {m.Groups["k"]}"),
        (Re(@"^🔁  Turbo: (?<k>.+)$"), m => $"🔁  Turbo: {T(m.Groups["k"].Value)}"),
        (Re(@"^⏯  Makro: (?<k>.+)$"), m => $"⏯  Macro: {m.Groups["k"]}"),
        (Re(@"^Tastatur: (?<k>.+)$"), m => $"Teclado: {m.Groups["k"]}"),
        (Re(@"^Gamepad: (?<k>.+)$"), m => $"Gamepad: {m.Groups["k"]}"),
        (Re(@"^(?<k>.+)  \(verbunden\)$"), m => $"{N(m, "k")}  (ligado)"),
        (Re(@"^Bluetooth nicht verfügbar: (?<e>.*)$"), m => $"Bluetooth indisponível: {m.Groups["e"]}"),
        (Re(@"^(?<k>.+) per USB ist von einem anderen Programm belegt \(z\. B\. Steam\)\.$"),
            m => $"{N(m, "k")} por USB está ocupado por outro programa (p. ex. Steam)."),
        (Re(@"^Schon (?<n>\d+) Controller verbunden – (?<k>.+) wird nicht verwendet\.$"),
            m => $"Já existem {m.Groups["n"]} comandos ligados – {N(m, "k")} não é usado."),
        (Re(@"^(?<k>.+): schwache Bluetooth-Verbindung \((?<r>\d+) statt 33–60 Berichte/s\)\.$"),
            m => $"{N(m, "k")}: ligação Bluetooth fraca ({m.Groups["r"]} em vez de 33–60 relatórios/s)."),
        (Re(@"^(?<k>.+) getrennt$"), m => $"{N(m, "k")} desligado"),
    ];
}
