using System.Text.RegularExpressions;

namespace Switch2Pro.Bridge;

/// <summary>Feste Texte Deutsch → Chinesisch (vereinfacht). Schlüssel bleiben die deutschen Originaltexte.</summary>
internal static partial class Tr
{
    private static readonly Dictionary<string, string> TextsZh = new(StringComparer.Ordinal)
    {
        // ---------- Fenster, Reiter, Abschnitte ----------
        ["Controller"] = "控制器",
        // ---------- Status-Kopfzeile, Ansicht ----------
        ["bereit"] = "就绪",
        ["nicht verfügbar"] = "不可用",
        ["Niedrigster Akku"] = "最低电量",
        ["lädt"] = "充电中",
        ["gemischt"] = "混合",
        ["Original-Controller"] = "原始控制器",
        ["versteckt"] = "已隐藏",
        ["sichtbar"] = "可见",
        ["HidHide fehlt"] = "缺少 HidHide",
        ["Groß"] = "大",
        ["Kompakt"] = "紧凑",
        ["Einstellungen (optional)"] = "设置（可选）",
        ["1. Windows und Spiele sehen den Controller als …"] = "1. Windows 和游戏将控制器识别为 …",
        ["2. Tasten A/B/X/Y"] = "2. 按键 A/B/X/Y",
        ["3. Vibration, Sticks, Verbinden, Gyro-Maus"] = "3. 振动、摇杆、连接、陀螺仪鼠标",
        ["4. Joy-Con"] = "4. Joy-Con",
        ["4. Joy-Con und Wii"] = "4. Joy-Con 和 Wii",
        ["Wii-Fernbedienung: Zeiger (Sensorleiste) steuert die Maus"] = "Wii 遥控器：指针（感应条）控制鼠标",
        ["Zeiger"] = "指针",
        ["kein Zeiger – Sensorleiste nicht im Blick"] = "无指针 – 感应条不在视野内",
        ["5. Zielen, Sticks, Trigger, Turbo"] = "5. 瞄准、摇杆、扳机、连发",
        ["6. Tastenbelegung und Profile  (Taste → Gamepad, Tastatur, Maus, Gyro-Maus, Shift-Ebene)"] =
            "6. 按键映射和配置文件（按键 → 手柄、键盘、鼠标、陀螺仪鼠标、Shift 层）",
        ["Xbox-360-Controller  (empfohlen – läuft mit fast allen Spielen)"] = "Xbox 360 控制器（推荐 – 兼容几乎所有游戏）",
        ["PlayStation DualShock 4  (mit Bewegungssteuerung/Gyro – für Steam && Emulatoren)"] =
            "PlayStation DualShock 4（带体感/陀螺仪 – 适用于 Steam 和模拟器）",
        ["Xbox-Belegung  (nach Position: untere Taste = A)"] = "Xbox 布局（按位置：下方按键 = A）",
        ["Nintendo-Belegung  (nach Beschriftung: A bleibt A)"] = "Nintendo 布局（按标识：A 仍是 A）",
        ["Vibration"] = "振动",
        ["Stärke:"] = "强度：",
        ["Stick-Totzone (alle Controller):"] = "摇杆死区（所有控制器）：",
        ["Beim Verbinden kurz vibrieren"] = "连接时短暂振动",
        ["Meldung bei Verbinden"] = "连接通知",
        ["Wer meldet, wenn ein Controller verbunden oder getrennt wird."] = "选择在控制器连接或断开时由谁通知。",
        ["„N-Connect“ zeigt den echten Controller-Namen und schaltet die Gerätemeldungen von Windows ab."] = "\"N-Connect\" 显示真实的控制器名称，并关闭 Windows 设备通知。",
        ["N-Connect (empfohlen)"] = "N-Connect（推荐）",
        ["N-Connect und Windows"] = "N-Connect 和 Windows",
        ["Keine"] = "无",
        ["Gekoppelte Controller per Tastendruck verbinden (ohne SYNC)"] = "已配对的控制器按任意键连接（无需 SYNC）",
        ["Automatisch mit Windows starten"] = "随 Windows 自动启动",
        ["Gyro für Emulatoren bereitstellen (Cemuhook/DSU, Port 26760 – wirkt nach Neustart)"] =
            "为模拟器提供陀螺仪（Cemuhook/DSU，端口 26760 – 重启后生效）",
        ["Beim Start nach neuer Version suchen (GitHub)"] = "启动时检查新版本（GitHub）",
        ["Ohne Eingabe automatisch trennen nach:"] = "无操作后自动断开：",
        ["Gyro-Maus-Geschwindigkeit:"] = "陀螺仪鼠标速度：",
        ["Sprache / Language:"] = "语言 / Language：",
        ["Automatisch (wie Windows)"] = "自动（与 Windows 一致）",
        ["nie"] = "从不",
        ["Zwei Joy-Con automatisch zu einem Controller zusammenfassen"] = "自动将两个 Joy-Con 合并为一个控制器",
        ["Gyro beim Paar vom:"] = "组合手柄的陀螺仪来自：",
        ["rechter Joy-Con (wie Switch)"] = "右 Joy-Con（同 Switch）",
        ["linker Joy-Con"] = "左 Joy-Con",
        ["Joy-Con 2 als Maus, wenn er auf dem Tisch liegt"] = "Joy-Con 2 平放在桌面时作为鼠标",
        ["Mausgeschwindigkeit:"] = "鼠标速度：",
        ["Maus: links/rechts umkehren"] = "鼠标：左右反转",
        ["Maus: hoch/runter umkehren"] = "鼠标：上下反转",
        ["Wie an der Switch: SL + SR eine Sekunde halten löst einen Joy-Con aus dem Paar. L am linken und R am rechten einzelnen Joy-Con gleichzeitig drücken verbindet sie wieder zum Paar. Die Wahl wird je Joy-Con gemerkt (auch nach dem nächsten Verbinden). Im Mausmodus: R/L = Linksklick, ZR/ZL = Rechtsklick, Stick drücken = Mittelklick, Stick hoch/runter = Scrollen."] =
            "与 Switch 相同：按住 SL + SR 一秒可将 Joy-Con 从组合中分离。同时按下左 Joy-Con 的 L 和右 Joy-Con 的 R 可重新组合。每个 Joy-Con 会记住该选择（下次连接同样有效）。鼠标模式：R/L = 左键，ZR/ZL = 右键，按下摇杆 = 中键，摇杆上下 = 滚动。",
        ["Gyro als rechter Stick:"] = "陀螺仪作为右摇杆：",
        ["aus (nur per Taste „Gyro-Stick“)"] = "关闭（仅通过“陀螺仪摇杆”按键）",
        ["immer"] = "始终",
        ["beim Zielen (solange ZL / linker Trigger gedrückt)"] = "瞄准时（按住 ZL / 左扳机时）",
        ["hoch/runter umkehren"] = "上下反转",
        ["Empfindlichkeit:"] = "灵敏度：",
        ["Mindestausschlag:"] = "最小输出：",
        ["Stick-Kennlinie:"] = "摇杆曲线：",
        ["Turbo (pro Sekunde):"] = "连发（每秒）：",
        ["Analoge Trigger (GameCube) – Totzone:"] = "模拟扳机（GameCube）– 死区：",
        ["voll gedrückt ab:"] = "完全按下起始点：",
        ["Profil:"] = "配置文件：",
        ["Neu …"] = "新建 …",
        ["Umbenennen …"] = "重命名 …",
        ["Löschen"] = "删除",
        ["Exportieren …"] = "导出 …",
        ["Importieren …"] = "导入 …",
        ["Aktiv bei Programm:"] = "在此程序运行时激活：",
        ["Programm wählen …"] = "选择程序 …",
        ["Standard"] = "默认",
        ["Standard gilt immer, wenn kein anderes Profil passt"] = "当没有其他配置文件匹配时使用默认",
        ["z. B. Cemu.exe, Ryujinx.exe"] = "例如 Cemu.exe、Ryujinx.exe",
        ["Ein eigenes Profil wird automatisch aktiv, solange eines seiner Programme im Vordergrund ist (sonst gilt „Standard“). Im Infobereich-Menü lässt sich ein Profil auch fest wählen."] =
            "当专属配置文件的程序位于前台时会自动激活（否则使用“默认”）。也可以在通知区域菜单中固定选择一个配置文件。",
        ["Controller:"] = "控制器：",
        ["Eigene Stick-Totzone für diesen Controller:"] = "此控制器专属摇杆死区：",
        ["Normale Belegung"] = "常规映射",
        ["Shift-Ebene (gilt, solange eine Taste mit „Shift-Ebene“ gehalten wird)"] = "Shift 层（按住设为“Shift 层”的按键时生效）",
        ["Alles auf Standard"] = "全部重置",
        ["Schließen"] = "关闭",
        ["wie normale Belegung"] = "同常规映射",

        // ---------- Belegungsziele und Vorlagen ----------
        ["— keine Funktion —"] = "— 无功能 —",
        ["A (Xbox) / Kreuz (PS)"] = "A (Xbox) / ✕ (PS)",
        ["B (Xbox) / Kreis (PS)"] = "B (Xbox) / ○ (PS)",
        ["X (Xbox) / Viereck (PS)"] = "X (Xbox) / □ (PS)",
        ["Y (Xbox) / Dreieck (PS)"] = "Y (Xbox) / △ (PS)",
        ["Ansicht (Back) / Share"] = "视图 (Back) / Share",
        ["Menü (Start) / Options"] = "菜单 (Start) / Options",
        ["Xbox-Taste / PS-Taste"] = "Xbox 键 / PS 键",
        ["Linker Stick-Klick"] = "左摇杆按下",
        ["Rechter Stick-Klick"] = "右摇杆按下",
        ["Steuerkreuz hoch"] = "十字键上",
        ["Steuerkreuz runter"] = "十字键下",
        ["Steuerkreuz links"] = "十字键左",
        ["Steuerkreuz rechts"] = "十字键右",
        ["Touchpad-Klick (nur DualShock 4)"] = "触摸板按下（仅 DualShock 4）",
        ["🖱  Maus: Linksklick"] = "🖱  鼠标：左键",
        ["🖱  Maus: Rechtsklick"] = "🖱  鼠标：右键",
        ["🖱  Maus: Mittelklick"] = "🖱  鼠标：中键",
        ["🎯  Gyro-Maus (solange gehalten)"] = "🎯  陀螺仪鼠标（按住时）",
        ["🎯  Gyro-Maus ein/aus"] = "🎯  陀螺仪鼠标开/关",
        ["🎯  Gyro als rechter Stick (solange gehalten)"] = "🎯  陀螺仪作右摇杆（按住时）",
        ["🎯  Gyro als rechter Stick ein/aus"] = "🎯  陀螺仪作右摇杆 开/关",
        ["⇧  Shift-Ebene (solange gehalten)"] = "⇧  Shift 层（按住时）",
        ["🔁  Turbo / Dauerfeuer …"] = "🔁  连发 / 自动连击 …",
        ["⏯  Makro (Tastenfolge) …"] = "⏯  宏（按键序列）…",
        ["📷  Bildschirmfoto speichern (Win+Druck)"] = "📷  保存截图（Win+Print）",
        ["📷  Bildschirmausschnitt (Win+Umschalt+S)"] = "📷  区域截图（Win+Shift+S）",
        ["⏺  Letzte 30 Sekunden aufnehmen (Win+Alt+G)"] = "⏺  录制最近 30 秒（Win+Alt+G）",
        ["⏺  Aufnahme starten/stoppen (Win+Alt+R)"] = "⏺  开始/停止录制（Win+Alt+R）",
        ["🎮  Xbox Game Bar (Win+G)"] = "🎮  Xbox Game Bar（Win+G）",
        ["🔊  Lauter"] = "🔊  音量增大",
        ["🔉  Leiser"] = "🔉  音量减小",
        ["⏯  Wiedergabe/Pause"] = "⏯  播放/暂停",
        ["⌨  Andere Taste / Tastenkombination aufnehmen …"] = "⌨  录制其他按键 / 组合键 …",

        // ---------- Tastennamen ----------
        ["+ (Plus)"] = "+（加号）",
        ["− (Minus)"] = "−（减号）",
        ["Aufnahme"] = "截图",
        ["GL (Rücktaste links)"] = "GL（左背键）",
        ["GR (Rücktaste rechts)"] = "GR（右背键）",
        ["Linker Stick drücken"] = "按下左摇杆",
        ["Rechter Stick drücken"] = "按下右摇杆",
        ["Stick drücken"] = "按下摇杆",
        ["A (groß, unten)"] = "A（大键，下方）",
        ["B (links)"] = "B（左）",
        ["X (rechts)"] = "X（右）",
        ["Y (oben)"] = "Y（上）",
        ["L (ganz durchgedrückt)"] = "L（完全按下）",
        ["R (ganz durchgedrückt)"] = "R（完全按下）",
        ["untere Taste (quer)"] = "下按键（横握）",
        ["rechte Taste (quer)"] = "右按键（横握）",
        ["linke Taste (quer)"] = "左按键（横握）",
        ["obere Taste (quer)"] = "上按键（横握）",
        ["1 (quer) / Classic Y"] = "1（横握）/ Classic Y",
        ["2 (quer) / Classic B"] = "2（横握）/ Classic B",
        ["B (Abzug) / Classic ZR"] = "B（扳机）/ Classic ZR",
        ["Kreuz (unten)"] = "✕（下）",
        ["Kreis (rechts)"] = "○（右）",
        ["Viereck (links)"] = "□（左）",
        ["Dreieck (oben)"] = "△（上）",
        ["PS-Taste"] = "PS 键",
        ["Touchpad-Klick"] = "触摸板按下",
        ["Mikro stumm"] = "麦克风静音",
        ["Fn links (Edge)"] = "Fn 左（Edge）",
        ["Rücktaste links (Edge)"] = "左背键（Edge）",
        ["Rücktaste rechts (Edge)"] = "右背键（Edge）",
        ["L3 (Stick drücken)"] = "L3（按下摇杆）",
        ["R3 (Stick drücken)"] = "R3（按下摇杆）",
        ["Ansicht/Zurück"] = "视图/返回",
        ["Menü/Start"] = "菜单/开始",
        ["Xbox-Taste"] = "Xbox 键",

        // ---------- Controller-Namen ----------
        ["Wii-Fernbedienung"] = "Wii 遥控器",
        ["Xbox-Controller"] = "Xbox 控制器",
        ["Xbox-Controller (Microsoft)"] = "Xbox 控制器（Microsoft）",
        ["XInput (USB, Bluetooth oder Xbox-Adapter)"] = "XInput（USB、蓝牙或 Xbox 适配器）",

        // ---------- Übersicht / Karten ----------
        ["Trennen"] = "断开",
        ["Vibrieren"] = "振动",
        ["Gyro kalibrieren"] = "校准陀螺仪",
        ["Ruhig liegen lassen …"] = "请静置 …",
        ["Kalibriert ✓"] = "已校准 ✓",
        ["Hochkant halten"] = "竖直握持",
        ["Quer halten"] = "水平握持",
        ["Joy-Con trennen"] = "分离 Joy-Con",
        ["Zum Paar verbinden"] = "合并为组合",
        ["Joy-Con trennen – beide werden einzelne Controller"] = "拆分 Joy-Con – 两者都成为独立控制器",
        ["Zum Paar verbinden – sucht einen freien Joy-Con"] = "合并为组合 – 寻找空闲的 Joy-Con",
        ["Doppelt angezeigt? Verstecken"] = "显示重复？隐藏",
        ["amiibo lesen"] = "读取 amiibo",
        ["Ring-Con ein"] = "开启 Ring-Con",
        ["Ring-Con aus"] = "关闭 Ring-Con",
        ["Ring-Con wird gesucht …"] = "正在搜索 Ring-Con …",
        ["IR-Kamera"] = "红外摄像头",
        ["Akku"] = "电池",
        ["Verbindung"] = "连接",
        ["Adresse"] = "地址",
        ["Seriennummer"] = "序列号",
        ["Griff"] = "握把",
        ["Maus"] = "鼠标",
        ["Gedrückt"] = "已按下",
        ["unbekannt"] = "未知",
        ["Charging Grip – GL/GR aktiv"] = "充电握把 – GL/GR 已启用",
        ["aktiv (liegt auf dem Tisch)"] = "已激活（平放在桌面上）",
        ["bereit – zum Benutzen auf den Tisch legen"] = "就绪 – 放到桌面上即可使用",
        ["Bewegungssensor: keine Daten"] = "运动传感器：无数据",
        ["quer halten: Steuerkreuz links,\n1 und 2 rechts"] = "横握：十字键在左，\n1 和 2 在右",

        // ---------- Tooltips ----------
        ["Verbindung trennen. Der Controller verbindet sich beim nächsten Tastendruck wieder."] =
            "断开连接。控制器下次按键时会重新连接。",
        ["Controller kurz vibrieren lassen – zeigt, welcher Controller dieser Spieler ist."] =
            "让控制器短暂振动 – 显示哪个控制器属于此玩家。",
        ["Controller ruhig auf den Tisch legen und klicken: misst den Gyro-Nullpunkt neu (gegen Abdriften)."] =
            "将控制器静置于桌面并点击：重新测量陀螺仪零点（防止漂移）。",
        ["Einzelnen Joy-Con quer (wie an der Switch) oder hochkant halten – wird je Joy-Con gemerkt. Hochkant gilt die Tastenbelegung von „Joy-Con-Paar“."] =
            "单个 Joy-Con 可横握（同 Switch）或竖握 – 每个 Joy-Con 会记住该设置。竖握时使用“Joy-Con 组合”的按键映射。",
        ["Versteckt den per USB angeschlossenen Controller vor Spielen (HidHide), damit sie nur den virtuellen Xbox-Controller sehen."] =
            "对游戏隐藏 USB 连接的控制器（HidHide），使其只能看到虚拟 Xbox 控制器。",
        ["amiibo mit dem NFC-Leser lesen und als Datei (.bin) speichern – z. B. für Emulatoren."] =
            "用 NFC 读取器读取 amiibo 并保存为文件（.bin）– 例如用于模拟器。",
        ["Ring-Con am rechten Joy-Con ein-/ausschalten: zusammendrücken = rechter Trigger, auseinanderziehen = linker Trigger. Beim Einschalten den Ring nicht berühren."] =
            "开关右 Joy-Con 的 Ring-Con：挤压 = 右扳机，拉伸 = 左扳机。开启时请勿触碰圆环。",
        ["Live-Bild der IR-Kamera im rechten Joy-Con anzeigen."] = "显示右 Joy-Con 红外摄像头的实时画面。",
        ["Links = empfindlicher (kleine Drehung, großer Ausschlag), rechts = ruhiger."] = "左 = 更灵敏（小转动大输出），右 = 更平稳。",
        ["Mindestausschlag des Sticks bei Bewegung – überwindet die Totzone des Spiels."] = "移动时摇杆的最小输出 – 克服游戏的死区。",
        ["Mitte = linear. Rechts = feiner um die Mitte (präzises Zielen), links = schneller."] = "中间 = 线性。右 = 中心附近更细腻（精准瞄准），左 = 更快。",
        ["So weit lässt sich ein analoger Trigger drücken, bevor er wirkt."] = "模拟扳机生效前可以按下的行程。",
        ["Ab hier gilt der Trigger als ganz gedrückt (100 = erst am Anschlag)."] = "从此处起扳机视为完全按下（100 = 按到底才算）。",
        ["Wie oft pro Sekunde Tasten mit „Turbo“ auslösen."] = "“连发”按键每秒触发次数。",

        // ---------- Infobereich ----------
        ["ViGEmBus-Treiber fehlt"] = "缺少 ViGEmBus 驱动",
        ["ViGEmBus herunterladen …"] = "下载 ViGEmBus …",
        ["Verbinde …"] = "连接中 …",
        ["Kein Controller – SYNC-Taste am Controller kurz drücken"] = "无控制器 – 短按控制器上的 SYNC 键",
        ["Ausgabe als"] = "输出为",
        ["Xbox-360-Controller (empfohlen)"] = "Xbox 360 控制器（推荐）",
        ["DualShock 4 (mit Gyro für Steam/Emulatoren)"] = "DualShock 4（带陀螺仪，适用于 Steam/模拟器）",
        ["Tastenbelegung"] = "按键映射",
        ["Xbox-Belegung (untere Taste = A)"] = "Xbox 布局（下方按键 = A）",
        ["Switch-2-Pro-Belegung (A bleibt A)"] = "Nintendo 布局（A 仍是 A）",
        ["Automatisch (nach Spiel/Programm)"] = "自动（按游戏/程序）",
        ["Mit Windows starten"] = "随 Windows 启动",
        ["Einstellungen …"] = "设置 …",
        ["Kurzanleitung"] = "快速指南",
        ["Protokoll öffnen"] = "打开日志",
        ["Beenden"] = "退出",
        ["N-Connect: warte auf Controller (SYNC drücken)"] = "N-Connect：等待控制器（请按 SYNC）",
        ["N-Connect: ViGEmBus fehlt"] = "N-Connect：缺少 ViGEmBus",
        ["Neue Version verfügbar"] = "有新版本可用",
        ["Einstellungen fehlerhaft"] = "设置损坏",
        ["settings.json konnte nicht gelesen werden – es gelten die Standardwerte."] = "无法读取 settings.json – 使用默认值。",
        ["Ohne ViGEmBus kann kein virtueller Controller erzeugt werden. Bitte das Setup erneut ausführen oder ViGEmBus installieren (Rechtsklick auf das Symbol → ViGEmBus herunterladen)."] =
            "没有 ViGEmBus 就无法创建虚拟控制器。请重新运行安装程序或安装 ViGEmBus（右键点击图标 → 下载 ViGEmBus）。",

        // ---------- Dialoge ----------
        ["Tastatur-Taste festlegen"] = "设置键盘按键",
        ["Übernehmen"] = "应用",
        ["Abbrechen"] = "取消",
        ["Ja"] = "是",
        ["Nein"] = "否",
        ["Turbo / Dauerfeuer"] = "连发 / 自动连击",
        ["Tastatur-Taste aufnehmen …"] = "录制键盘按键 …",
        ["Makro (Tastenfolge)"] = "宏（按键序列）",
        ["Ungültig – bitte Schreibweise prüfen (siehe oben)."] = "无效 – 请检查语法（见上文）。",
        ["Neues Profil"] = "新配置文件",
        ["Name des Profils (z. B. der Spielname):"] = "配置文件名称（例如游戏名）：",
        ["Profil umbenennen"] = "重命名配置文件",
        ["Neuer Name:"] = "新名称：",
        ["Ein Profil mit diesem Namen gibt es schon."] = "已存在同名配置文件。",
        ["Die Datei enthält kein gültiges Controller-Profil."] = "该文件不包含有效的控制器配置文件。",
        ["Alle Einstellungen und Tastenbelegungen auf Standard zurücksetzen?"] = "将所有设置和按键映射重置为默认？",
        ["Suche …"] = "搜索中 …",
        ["Kein Bluetooth-Adapter gefunden."] = "未找到蓝牙适配器。",
        ["IR-Kamera (Joy-Con R)"] = "红外摄像头（Joy-Con 右）",
        ["Auflösung:"] = "分辨率：",
        ["40 × 30 (schnell)"] = "40 × 30（快速）",
        ["320 × 240 (langsam)"] = "320 × 240（慢速）",
        ["Kamera startet …"] = "摄像头启动中 …",
        ["läuft – Joy-Con auf eine Lichtquelle oder die Hand richten"] = "运行中 – 将 Joy-Con 对准光源或手部",
        ["Kamera startet nicht (Details im Protokoll)"] = "摄像头无法启动（详见日志）",
        ["Kein Ring-Con gefunden. Den rechten Joy-Con (Switch 1) fest in den Ring-Con schieben und erneut versuchen."] =
            "未找到 Ring-Con。请将右 Joy-Con（Switch 1）牢固插入 Ring-Con 后重试。",
        ["Kein amiibo erkannt. Bitte das amiibo flach an den NFC-Leser halten (Joy-Con: auf den rechten Stick, Pro Controller: auf das NFC-Logo) und erneut versuchen."] =
            "未识别到 amiibo。请将 amiibo 平贴在 NFC 读取器上（Joy-Con：右摇杆；Pro 手柄：NFC 标志）后重试。",
        ["NFC-Leser wird eingeschaltet …"] = "正在开启 NFC 读取器 …",
        ["amiibo an den Leser halten (rechter Stick des Joy-Con bzw. NFC-Logo des Pro Controllers) …"] =
            "请将 amiibo 靠近读取器（Joy-Con 右摇杆或 Pro 手柄的 NFC 标志）…",
        ["amiibo speichern"] = "保存 amiibo",
        ["Doppelte Controller verhindern"] = "防止控制器重复",
        ["Dafür wird das kostenlose Programm HidHide gebraucht (von den Machern von ViGEmBus).\n\nJetzt die Download-Seite öffnen? Nach der Installation hier erneut klicken."] =
            "这需要免费的 HidHide 程序（ViGEmBus 开发者出品）。\n\n现在打开下载页面？安装完成后再次点击此处。",
        ["HidHide konnte nicht eingerichtet werden (abgebrochen oder fehlgeschlagen). Details im Protokoll."] =
            "HidHide 配置失败（已取消或出错）。详见日志。",
        ["Der Controller hat sich bewegt oder keine Bewegungsdaten geliefert.\nBitte flach auf den Tisch legen, nicht berühren und erneut versuchen."] =
            "控制器发生移动或未提供运动数据。\n请将其平放在桌面上，不要触碰，然后重试。",
        ["Spiel oder Programm wählen"] = "选择游戏或程序",
        ["Profil exportieren"] = "导出配置文件",
        ["Profil importieren"] = "导入配置文件",
        ["Verstanden"] = "知道了",
        ["Einstellungen öffnen"] = "打开设置",
        ["Willkommen"] = "欢迎",

        // ---------- Neues Hauptfenster (Navigation, Seiten, Zeilen) ----------
        ["Allgemein"] = "常规",
        ["Sticks & Vibration"] = "摇杆与振动",
        ["Gyro & Maus"] = "陀螺仪与鼠标",
        ["Joy-Con & Wii"] = "Joy-Con 与 Wii",
        ["Ein"] = "开",
        ["Aus"] = "关",
        ["Verbundene Controller mit Live-Anzeige. Über „Einstellungen“ an einem Controller passt du genau diesen an."] =
            "已连接控制器的实时显示。通过控制器上的“设置”可单独调整该控制器。",
        ["Jede Taste kann ein Gamepad-Knopf, eine Tastaturtaste, ein Mausklick, Turbo oder ein Makro sein. " +
         "Tipp: Drückst du eine Taste am Controller, wird ihre Zeile hervorgehoben."] =
            "每个按键可以是手柄按钮、键盘按键、鼠标点击、连发或宏。" +
            "提示：按下控制器上的按键，对应行会高亮显示。",
        ["Profil"] = "配置文件",
        ["Neu"] = "新建",
        ["Umbenennen, löschen, exportieren, importieren"] = "重命名、删除、导出、导入",
        ["Ein eigenes Profil gilt automatisch, solange eines seiner Programme im Vordergrund ist – sonst „Standard“."] =
            "当专属配置文件的程序位于前台时自动生效 – 否则使用“默认”。",
        ["Aktiv bei Programm"] = "在此程序运行时激活",
        ["Programmdateien, bei denen dieses Profil gilt (mit Komma trennen)."] = "此配置文件适用的程序文件（用逗号分隔）。",
        ["Standard gilt für alle Programme"] = "默认适用于所有程序",
        ["Wählen …"] = "选择 …",
        ["Bearbeiten"] = "编辑",
        ["Jeder Controller hat seine eigene Belegung."] = "每个控制器都有自己的映射。",
        ["Ebene"] = "层",
        ["Normal"] = "常规",
        ["Shift-Ebene"] = "Shift 层",
        ["Die Shift-Ebene gilt, solange eine Taste mit „Shift-Ebene“ gehalten wird."] = "按住设为“Shift 层”的按键时，Shift 层生效。",
        ["Tasten"] = "按键",
        ["Standardwerte für alle Controller. Eigene Werte für einzelne Controller stellst du unten oder in der Übersicht ein."] =
            "所有控制器的默认值。单个控制器的专属值可在下方或概览中设置。",
        ["Sticks"] = "摇杆",
        ["Totzone"] = "死区",
        ["So weit lässt sich ein Stick bewegen, bevor er wirkt (gegen Abdriften)."] = "摇杆在生效前可以移动的幅度（防止漂移）。",
        ["Kennlinie"] = "响应曲线",
        ["„linear“ = gleichmäßig. Höher = feiner um die Mitte (präzises Zielen), niedriger = schneller."] =
            "“线性”= 均匀。更高 = 中心附近更细腻（精准瞄准），更低 = 更快。",
        ["Analoge Trigger (GameCube)"] = "模拟扳机（GameCube）",
        ["So weit lässt sich ein Trigger drücken, bevor er wirkt."] = "扳机在生效前可以按下的行程。",
        ["Voll gedrückt ab"] = "完全按下起始点",
        ["Ab hier gilt der Trigger als ganz gedrückt (100 % = erst am Anschlag)."] = "从此处起扳机视为完全按下（100 % = 按到底才算）。",
        ["Spiele dürfen den Controller vibrieren lassen."] = "允许游戏让控制器振动。",
        ["Stärke"] = "强度",
        ["Turbo-Geschwindigkeit"] = "连发速度",
        ["Wie oft pro Sekunde Tasten mit „Turbo“ auslösen."] = "“连发”按键每秒触发次数。",
        ["Eigene Werte je Controller"] = "每个控制器的专属值",
        ["Werte nur für diesen Controller – ohne eigenen Wert gilt der allgemeine."] = "仅此控制器的值 – 无专属值时使用通用值。",
        ["Bewegungssteuerung: Zielen per Gyro und den Controller als Maus nutzen."] = "体感控制：用陀螺仪瞄准并将控制器用作鼠标。",
        ["Gyro als rechter Stick"] = "陀螺仪作右摇杆",
        ["Modus"] = "模式",
        ["Zum Zielen in Spielen ohne eigene Gyro-Steuerung. „Gyro-Stick“ kann auch einer Taste zugewiesen werden."] =
            "用于在没有陀螺仪支持的游戏中瞄准。“陀螺仪摇杆”也可以分配给某个按键。",
        ["Aus (nur per Taste „Gyro-Stick“)"] = "关闭（仅通过“陀螺仪摇杆”按键）",
        ["Immer"] = "始终",
        ["Beim Zielen (solange ZL / LT gedrückt)"] = "瞄准时（按住 ZL / LT 时）",
        ["Empfindlichkeit"] = "灵敏度",
        ["Drehgeschwindigkeit für vollen Stick-Ausschlag – kleiner = empfindlicher."] = "摇杆满输出所需的转动速度 – 越小越灵敏。",
        ["Mindestausschlag"] = "最小输出",
        ["Überwindet die Stick-Totzone des Spiels bei kleinen Bewegungen."] = "在小幅度移动时克服游戏的摇杆死区。",
        ["Hoch/runter umkehren"] = "上下反转",
        ["Links/rechts umkehren"] = "左右反转",
        ["Gyro-Maus"] = "陀螺仪鼠标",
        ["Geschwindigkeit"] = "速度",
        ["Mauszeiger per Bewegung – über eine Taste mit „Gyro-Maus“ (Tastenbelegung)."] = "通过移动控制鼠标指针 – 需“陀螺仪鼠标”按键（按键映射）。",
        ["Mausrichtung (Gyro-Maus und Joy-Con-Maus)"] = "鼠标方向（陀螺仪鼠标和 Joy-Con 鼠标）",
        ["Gyro-Funktionen einer Taste zuweisen"] = "将陀螺仪功能分配给按键",
        ["Gyro-Maus oder Gyro-Stick ein/aus bzw. solange gehalten"] = "陀螺仪鼠标或陀螺仪摇杆开/关，或按住时启用",
        ["Joy-Con als Paar oder einzeln, Joy-Con 2 als Maus und Wii-Controller."] = "Joy-Con 组合或单个使用、Joy-Con 2 作鼠标以及 Wii 控制器。",
        ["Zu einem Controller zusammenfassen"] = "合并为一个控制器",
        ["Ein linker und ein rechter Joy-Con werden automatisch ein Paar."] = "左右 Joy-Con 自动组合成一对。",
        ["Gyro beim Paar vom"] = "组合手柄的陀螺仪来自",
        ["Rechter Joy-Con (wie Switch)"] = "右 Joy-Con（同 Switch）",
        ["Linker Joy-Con"] = "左 Joy-Con",
        ["Paar lösen oder verbinden"] = "分离或合并组合",
        ["Einen Joy-Con quer halten und SL oder SR drücken löst ihn aus dem Paar. L am linken und R am rechten Joy-Con gleichzeitig drücken verbindet sie wieder. Die Wahl wird je Joy-Con gemerkt."] =
            "横握 Joy-Con 并按 SL 或 SR 可将其从组合中分离。同时按左 Joy-Con 的 L 和右 Joy-Con 的 R 可重新组合。每个 Joy-Con 会记住该选择。",
        ["Joy-Con 2 als Maus"] = "Joy-Con 2 作鼠标",
        ["Als Maus, wenn er auf dem Tisch liegt"] = "平放在桌面时作为鼠标",
        ["Joy-Con 2 auf die Seite legen und wie eine Maus schieben."] = "将 Joy-Con 2 侧放并像鼠标一样滑动。",
        ["Mausgeschwindigkeit"] = "鼠标速度",
        ["Tasten im Mausmodus"] = "鼠标模式下的按键",
        ["R/L = Linksklick, ZR/ZL = Rechtsklick, Stick drücken = Mittelklick, Stick hoch/runter = Scrollen."] =
            "R/L = 左键，ZR/ZL = 右键，按下摇杆 = 中键，摇杆上下 = 滚动。",
        ["Zeiger steuert die Maus"] = "指针控制鼠标",
        ["Wii-Fernbedienung auf die Sensorleiste richten, um den Mauszeiger zu bewegen."] = "将 Wii 遥控器对准感应条以移动鼠标指针。",
        ["Wie Spiele die Controller sehen, Verbindung, Darstellung und Programm."] = "游戏如何识别控制器、连接、外观与程序设置。",
        ["Ausgabe"] = "输出",
        ["Controller erscheint als"] = "控制器显示为",
        ["Xbox 360 läuft mit fast allen Spielen. DualShock 4 bietet Bewegungssteuerung (Steam, Emulatoren)."] =
            "Xbox 360 兼容几乎所有游戏。DualShock 4 提供体感控制（Steam、模拟器）。",
        ["Xbox 360 läuft mit fast allen Spielen und Steam. DualShock 4 bietet zusätzlich Bewegungssteuerung (Steam, Emulatoren). Gilt für alle Controller ohne eigene Einstellung (Karte → Einstellungen → Tasten)."] =
            "Xbox 360 兼容几乎所有游戏和 Steam。DualShock 4 额外提供体感控制（Steam、模拟器）。适用于所有无单独设置的控制器（卡片 → 设置 → 按键）。",
        ["Original-Controller verstecken"] = "隐藏原始控制器",
        ["Controller verbinden"] = "连接控制器",
        ["SYNC-Taste am Controller drücken – N-Connect findet und koppelt ihn selbst. Danach reicht künftig ein Tastendruck."] =
            "按控制器上的 SYNC 键 – N-Connect 会自动找到并配对。以后只需按任意键即可连接。",
        ["So kommt der Controller in den Kopplungsmodus"] = "如何让控制器进入配对模式",
        ["Kurz die kleine SYNC-Taste drücken."] = "短按小的 SYNC 键。",
        ["SYNC-Taste drücken, bis die Lichter laufen."] = "按 SYNC 键直到指示灯滚动。",
        ["Batteriefach öffnen und die rote SYNC-Taste drücken."] = "打开电池仓并按红色 SYNC 键。",
        ["Die SYNC-Taste auf der Unterseite drücken."] = "按底部的 SYNC 键。",
        ["PS + Teilen bzw. Create halten, bis die Lichtleiste schnell blinkt."] =
            "按住 PS + Share/Create 直到灯条快速闪烁。",
        ["Kopplungstaste oben halten, bis die Xbox-Taste blinkt."] = "按住顶部配对键直到 Xbox 键闪烁。",
        ["Status"] = "状态",
        ["Suche läuft …"] = "搜索中 …",
        ["Suche läuft – jetzt SYNC drücken …"] = "正在搜索 – 现在按 SYNC …",
        ["Weitere Controller? Einfach SYNC drücken."] = "更多控制器？直接按 SYNC。",
        ["Wartet auf einen Controller im Kopplungsmodus."] = "等待处于配对模式的控制器。",
        ["Suche beendet"] = "搜索结束",
        ["Die Controller stehen in der Übersicht und verbinden sich künftig per Tastendruck."] =
            "控制器已显示在概览中，今后按任意键即可连接。",
        ["Kein Controller im Kopplungsmodus gefunden. SYNC-Taste drücken und „Erneut suchen“ klicken."] =
            "未找到处于配对模式的控制器。请按 SYNC 并点击“重新搜索”。",
        ["Verbunden"] = "已连接",
        ["Erneut suchen"] = "重新搜索",
        ["Fertig"] = "完成",
        ["Im Spiel"] = "游戏中",
        ["Dreht …"] = "旋转中 …",
        ["Testdrehung (360°)"] = "测试旋转（360°）",
        ["Testdrehung"] = "测试旋转",
        ["aus"] = "关",
        ["Gyro-Beschleunigung"] = "陀螺仪加速",
        ["Bei schneller Drehung"] = "快速转动时",
        ["Langsame Bewegungen bleiben fein, schnelle drehen weiter (wie JoyShockMapper). Voll ab 120 °/s, unter 20 °/s normal. Gilt für Gyro-Stick und Gyro-Maus."] =
            "慢速移动保持细腻，快速转动幅度更大（类似 JoyShockMapper）。120 °/s 以上为全速，低于 20 °/s 为正常。适用于陀螺仪摇杆和陀螺仪鼠标。",
        ["Flick-Stick (Spiele mit Maussteuerung)"] = "Flick Stick（鼠标控制的游戏）",
        ["Flick-Stick"] = "Flick Stick",
        ["Rechten Stick in eine Richtung schieben = Kamera dreht sofort dorthin; am Rand drehen = Kamera dreht mit. Zielen dann per Gyro. Der rechte Stick geht nicht mehr ans Spiel."] =
            "将右摇杆推向某方向 = 镜头立即转向该方向；沿边缘转动 = 镜头跟随旋转。之后用陀螺仪瞄准。右摇杆不再传给游戏。",
        ["Mausbewegung je Umdrehung"] = "每圈的鼠标移动量",
        ["Je Spiel einmal einstellen: „Testdrehung“ klicken, ins Spiel wechseln – nach 3 s dreht die Kamera einmal. Genau eine volle Drehung = richtig."] =
            "每个游戏设置一次：点击“测试旋转”，切换到游戏 – 3 秒后镜头旋转一圈。恰好一整圈即为正确。",
        ["Flick-Dauer"] = "Flick 时长",
        ["So lange dauert die Drehung beim Flick (0 = sofort)."] = "Flick 转动所需时间（0 = 立即）。",
        ["Gyro-Maus oder Gyro-Stick ein/aus bzw. solange gehalten, „Gyro anhalten“ (Ratchet: Controller zurückführen, ohne dass sich das Ziel bewegt)"] =
            "陀螺仪鼠标或陀螺仪摇杆开/关或按住时启用，“暂停陀螺仪”（Ratchet：回正控制器而不移动准星）",
        ["✋  Gyro anhalten (solange gehalten, „Ratchet“)"] = "✋  暂停陀螺仪（按住时，“Ratchet”）",
        ["Spieler-LED und Lichtleiste vom Spiel"] = "玩家 LED 和游戏灯条",
        ["Die Spieler-LEDs zeigen den Xbox-Platz, den Windows vergibt. Bei DualShock 4 steuert die Lichtleiste des Spiels die HOME-LED (Switch 1 Pro Controller, rechter Joy-Con)."] =
            "玩家 LED 显示 Windows 分配的 Xbox 位置。DualShock 4 的游戏灯条控制 HOME LED（Switch 1 Pro 手柄、右 Joy-Con）。",
        ["HidHide installieren …"] = "安装 HidHide …",
        ["Empfohlen: Steam und viele Spiele kennen Switch-1-, NSO- und USB-Controller selbst und sähen sie sonst doppelt. Läuft nach der Installation ohne Rückfrage (sonst fragt Windows nach Adminrechten)."] =
            "推荐：Steam 和许多游戏本身能识别 Switch 1、NSO 和 USB 控制器，否则会显示重复。安装后无需确认即可运行（否则 Windows 会要求管理员权限）。",
        ["Steam und viele Spiele sehen Switch-1-, NSO- und USB-Controller sonst doppelt. Dafür wird das kostenlose HidHide gebraucht (bei der N-Connect-Installation dabei, hier nachträglich)."] =
            "否则 Steam 和许多游戏会重复显示 Switch 1、NSO 和 USB 控制器。这需要免费的 HidHide（随 N-Connect 安装包附带，可在此补装）。",
        ["Erscheint als"] = "显示为",
        ["Wie allgemein"] = "同常规设置",
        ["Nur für diesen Controller. Xbox 360 läuft überall; DualShock 4 bringt zusätzlich Gyro nach Steam und in Emulatoren. „Wie allgemein“ folgt der Seite „Allgemein“."] =
            "仅此控制器。Xbox 360 各处通用；DualShock 4 为 Steam 和模拟器额外提供陀螺仪。“同常规设置”遵循“常规”页面。",
        ["Der echte Xbox-Controller – Spiele sehen ihn von Windows aus direkt. Belegungen hier wirken auf Sonderaktionen (Tastatur, Makros, Gyro), nicht auf den Controller selbst."] =
            "原生 Xbox 控制器 – 游戏通过 Windows 直接识别。此处的映射作用于特殊操作（键盘、宏、陀螺仪），不影响控制器本身。",
        ["Steam und manche Spiele sehen diesen Controller sonst doppelt. Abhilfe: HidHide installieren (Seite „Allgemein“ → „Original-Controller verstecken“)."] =
            "否则 Steam 和部分游戏会重复显示此控制器。解决方法：安装 HidHide（“常规”页面 →“隐藏原始控制器”）。",
        ["Original-Controller vor Spielen versteckt. Steam bitte einmal neu starten – danach sieht es nur noch den virtuellen Controller."] =
            "已对游戏隐藏原始控制器。请重启 Steam 一次 – 之后它只能看到虚拟控制器。",
        ["Original-Controller vor Spielen versteckt – Steam und Spiele sehen nur noch den virtuellen Controller."] =
            "已对游戏隐藏原始控制器 – Steam 和游戏只能看到虚拟控制器。",
        ["Original-Controller nicht versteckt (Abfrage abgebrochen). Nachholen: Controller → Einstellungen → Extras → „Doppelt angezeigt?“."] =
            "未隐藏原始控制器（已取消询问）。后续操作：控制器 → 设置 → 其他 →“显示重复？”。",
        ["Tastenanordnung A/B/X/Y"] = "按键布局 A/B/X/Y",
        ["Xbox: nach Position (untere Taste = A). Nintendo: nach Beschriftung (A bleibt A)."] = "Xbox：按位置（下方按键 = A）。Nintendo：按标识（A 仍是 A）。",
        ["Verbinden"] = "连接",
        ["Per Tastendruck verbinden"] = "按键即连",
        ["Gekoppelte Controller verbinden sich ohne SYNC-Taste."] = "已配对的控制器无需 SYNC 键即可连接。",
        ["Ohne Eingabe trennen nach"] = "无操作后断开",
        ["Spart Akku, wenn ein Controller liegen bleibt."] = "控制器闲置时节省电量。",
        ["N-Connect startet unsichtbar im Infobereich."] = "N-Connect 在通知区域静默启动。",
        ["Darstellung und Sprache"] = "外观与语言",
        ["Farbmodus"] = "颜色模式",
        ["Mica-Effekt"] = "云母效果",
        ["Durchscheinende Titelleiste (ab Windows 11)."] = "半透明标题栏（Windows 11 及以上）。",
        ["Erweitert"] = "高级",
        ["Gyro für Emulatoren (DSU)"] = "模拟器陀螺仪（DSU）",
        ["Cemuhook-Server auf Port 26760 – wirkt nach einem Neustart von N-Connect."] = "端口 26760 的 Cemuhook 服务器 – 重启 N-Connect 后生效。",
        ["Nach Updates suchen"] = "检查更新",
        ["Beim Start auf GitHub nach einer neuen Version suchen."] = "启动时在 GitHub 上检查新版本。",
        ["Tastenbelegungen und Werte zurücksetzen. Gekoppelte Controller bleiben erhalten."] = "重置按键映射和各项数值。已配对的控制器保留。",
        ["Zurücksetzen"] = "重置",

        // ---------- Controller-Karte ----------
        ["Einstellungen"] = "设置",
        ["Tastenbelegung und Einstellungen nur für diesen Controller"] = "仅此控制器的按键映射和设置",
        ["Feineinstellung"] = "微调",
        ["Gyro"] = "陀螺仪",
        ["Extras"] = "其他",
        ["Belegung für alle Spiele (Standard) oder ein eigenes Profil."] = "所有游戏的映射（默认）或专属配置文件。",
        ["Profile"] = "配置文件",
        ["Profile anlegen, umbenennen, exportieren …"] = "创建、重命名、导出配置文件 …",
        ["Drück eine Taste am Controller – ihre Zeile leuchtet auf. ⌨ weist eine Tastaturtaste zu, ↺ setzt zurück."] =
            "按下控制器上的按键 – 对应行会高亮。⌨ 分配键盘按键，↺ 重置。",
        ["Tastatur-Taste zuweisen: klicken und die gewünschte Taste oder Kombination drücken."] = "分配键盘按键：点击后按下所需按键或组合键。",
        ["Zurück auf die Standardbelegung"] = "恢复默认映射",
        ["Ohne eigenen Wert gilt der allgemeine Wert der Seite „Sticks & Vibration“."] = "无专属值时使用“摇杆与振动”页面的通用值。",
        ["Stick-Totzone"] = "摇杆死区",
        ["Stick-Kennlinie"] = "摇杆曲线",
        ["Trigger-Totzone"] = "扳机死区",
        ["Trigger voll gedrückt ab"] = "扳机完全按下起始点",
        ["Vibrationsstärke"] = "振动强度",
        ["Gyro-Maus-Geschwindigkeit"] = "陀螺仪鼠标速度",
        ["Eigenen Wert entfernen – es gilt wieder der allgemeine Wert"] = "移除专属值 – 恢复使用通用值",
        ["Kalibrieren"] = "校准",
        ["Controller ruhig auf den Tisch legen und klicken: misst den Nullpunkt neu (gegen Abdriften)."] =
            "将控制器静置于桌面并点击：重新测量零点（防止漂移）。",
        ["Gyro als rechter Stick und Mausrichtung"] = "陀螺仪作右摇杆与鼠标方向",
        ["Gilt für alle Controller"] = "适用于所有控制器",
        ["Paar"] = "组合",
        ["Joy-Con quer halten und SL oder SR drücken löst das Paar, L + R gleichzeitig verbindet es."] =
            "横握 Joy-Con 并按 SL 或 SR 可分离组合，同时按 L + R 可重新组合。",
        ["Haltung"] = "握持方式",
        ["Quer"] = "横握",
        ["Hochkant"] = "竖握",
        ["Quer wie an der Switch oder hochkant – hochkant gilt die Belegung von „Joy-Con-Paar“."] =
            "横握（同 Switch）或竖握 – 竖握时使用“Joy-Con 组合”的映射。",
        ["Mausmodus, Geschwindigkeit und Tasten"] = "鼠标模式、速度和按键",
        ["Lesen …"] = "读取 …",
        ["Einschalten"] = "开启",
        ["Ausschalten"] = "关闭",
        ["Wird gesucht …"] = "搜索中 …",
        ["Öffnen"] = "打开",
        ["Verstecken"] = "隐藏",
        ["amiibo an den NFC-Leser halten und als Datei (.bin) speichern – z. B. für Emulatoren."] =
            "将 amiibo 贴近 NFC 读取器并保存为文件（.bin）– 例如用于模拟器。",
        ["Zusammendrücken = rechter Trigger, auseinanderziehen = linker Trigger. Beim Einschalten nicht berühren."] =
            "挤压 = 右扳机，拉伸 = 左扳机。开启时请勿触碰。",
        ["Live-Bild der Infrarotkamera im rechten Joy-Con."] = "右 Joy-Con 红外摄像头的实时画面。",
        ["Doppelt angezeigt?"] = "显示重复？",
        ["Versteckt den Original-Controller vor Steam und Spielen (HidHide) – sie sehen dann nur den virtuellen Controller."] =
            "对 Steam 和游戏隐藏原始控制器（HidHide）– 它们只能看到虚拟控制器。",
        ["bereit (auf den Tisch legen)"] = "就绪（放到桌面上）",
        ["amiibo-Abbild (*.bin)|*.bin"] = "amiibo 镜像 (*.bin)|*.bin",
        ["Controller-Profil (*.ncprofile.json)|*.ncprofile.json|JSON (*.json)|*.json"] = "控制器配置文件 (*.ncprofile.json)|*.ncprofile.json|JSON (*.json)|*.json",
        ["Programme (*.exe)|*.exe"] = "程序 (*.exe)|*.exe",
        ["Kein Controller verbunden\n\n" +
         "Switch-2-Controller: kurz die SYNC-Taste drücken – danach reicht ein beliebiger Tastendruck.\n" +
         "Switch-1-, NSO- und Wii-Controller: SYNC-Taste drücken – N-Connect koppelt sie selbst.\n" +
         "Oder hier gezielt suchen und koppeln:"] =
            "未连接控制器\n\n" +
            "Switch 2 控制器：短按 SYNC 键 – 之后按任意键即可。\n" +
            "Switch 1、NSO 和 Wii 控制器：按 SYNC 键 – N-Connect 自动配对。\n" +
            "或在此定向搜索并配对：",
        ["Controller suchen …"] = "搜索控制器 …",
        ["Kein Controller verbunden"] = "未连接控制器",
        ["Switch-1-, NSO- und Wii-Controller suchen und koppeln (SYNC-Taste drücken)."] =
            "搜索并配对 Switch 1、NSO 和 Wii 控制器（按 SYNC 键）。",
        ["Neue Controller automatisch koppeln"] = "自动配对新的控制器",
        ["Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive, Wii und PlayStation: einfach SYNC " +
         "drücken – kein Umweg über die Windows-Bluetooth-Einstellungen. Gesucht wird nur, solange niemand spielt."] =
            "Joy-Con、Pro 手柄、NES/SNES/N64/Mega Drive、Wii 和 PlayStation：直接按 SYNC – " +
            "无需经过 Windows 蓝牙设置。仅在无人游戏时进行搜索。",
        ["Gezielt suchen"] = "定向搜索",
        ["Sucht eine Minute lang nach Controllern im Kopplungsmodus."] = "搜索处于配对模式的控制器一分钟。",
        ["Controller koppeln …"] = "配对控制器 …",
        ["Controller koppeln"] = "配对控制器",
        ["Linken Joy-Con umbenennen …"] = "重命名左 Joy-Con …",
        ["Rechten Joy-Con umbenennen …"] = "重命名右 Joy-Con …",
        ["Controller umbenennen"] = "重命名控制器",
        ["Spielerplatz"] = "玩家位置",
        ["N-Connect aktualisieren"] = "更新 N-Connect",
        ["HidHide aktualisieren"] = "更新 HidHide",
        ["HidHide-Update verfügbar"] = "有 HidHide 更新可用",
        ["HidHide aktuell halten"] = "保持 HidHide 最新",
        ["Beim Start nach einer neuen HidHide-Version suchen. Installiert wird nur nach Rückfrage (geprüfter Download vom Hersteller, Neustart nötig)."] =
            "启动时检查 HidHide 新版本。仅经确认后安装（厂商验证下载，需要重启）。",
        ["Der Download hat nicht geklappt oder die Datei war fehlerhaft. Die Release-Seite im Browser öffnen?"] =
            "下载失败或文件损坏。在浏览器中打开发布页面？",
        ["Alle Controller trennen"] = "断开所有控制器",
        ["Sticks kalibrieren"] = "校准摇杆",
        ["Kalibrieren …"] = "校准 …",
        ["Gegen Drift oder zu kleinen Ausschlag: Mitte und Rand neu messen. Wird nur in N-Connect gespeichert, der Controller bleibt unverändert."] =
            "针对漂移或行程过小：重新测量中心和边缘。仅保存在 N-Connect 中，控制器本身不变。",
        ["Linker Stick"] = "左摇杆",
        ["Rechter Stick"] = "右摇杆",
        ["Stick"] = "摇杆",
        ["Stick (linker Joy-Con)"] = "摇杆（左 Joy-Con）",
        ["Stick (rechter Joy-Con)"] = "摇杆（右 Joy-Con）",
        ["Neu messen"] = "重新测量",
        ["Werkswerte"] = "出厂值",
        ["Der Punkt zeigt, wo der Stick gerade steht. Steht er losgelassen nicht in der Mitte oder erreicht er den Kreis nicht, auf „Neu messen“ klicken."] =
            "圆点显示摇杆当前位置。如果松开后不在中心或无法到达圆圈，请点击“重新测量”。",
        ["Gilt gerade: eigene Kalibrierung."] = "当前使用：自定义校准。",
        ["Gilt gerade: Werkswerte des Controllers."] = "当前使用：控制器出厂值。",
        ["1/2 – Stick loslassen und den Controller ruhig halten …"] = "1/2 – 松开摇杆并保持控制器静止 …",
        ["2/2 – Stick bis zum Anschlag drücken und langsam ein- bis zweimal im Kreis drehen."] =
            "2/2 – 将摇杆推到底并缓慢绕圈一到两圈。",
        ["Fertig. „Übernehmen“ speichert die neue Kalibrierung für diesen Controller."] = "完成。“应用”将为此控制器保存新校准。",
        ["Der Stick hat den Rand nicht erreicht. Bitte bis zum Anschlag drücken und erneut messen."] =
            "摇杆未到达边缘。请推到底后重新测量。",
        ["Übernommen ✓ – gilt ab sofort."] = "已应用 ✓ – 立即生效。",
        ["Werkswerte des Controllers gelten wieder."] = "恢复使用控制器出厂值。",
        ["Gyro einrichten"] = "设置陀螺仪",
        ["Einrichten …"] = "设置 …",
        ["Zielen per Bewegung einrichten"] = "设置体感瞄准",
        ["Schritt für Schritt: Nullpunkt, wann der Gyro zielt, Empfindlichkeit – mit Vorschau."] =
            "一步步来：零点、陀螺仪何时瞄准、灵敏度 – 带预览。",
        ["1  Nullpunkt"] = "1  零点",
        ["Controller flach auf den Tisch legen, nicht berühren – verhindert, dass das Ziel von selbst wandert."] =
            "将控制器平放在桌面上，不要触碰 – 防止准星自行漂移。",
        ["Nullpunkt messen"] = "测量零点",
        ["Der Controller hat sich bewegt – bitte flach hinlegen und erneut versuchen."] = "控制器发生移动 – 请平放后重试。",
        ["Nullpunkt gemessen ✓"] = "零点已测量 ✓",
        ["2  Wann zielt der Gyro?"] = "2  陀螺仪何时瞄准？",
        ["Nur per Taste"] = "仅按键",
        ["Beim Zielen (ZL/LT)"] = "瞄准时（ZL/LT）",
        ["„Beim Zielen“: nur solange ZL (linker Trigger) gehalten wird – wie in vielen Shootern."] =
            "“瞄准时”：仅在按住 ZL（左扳机）时 – 与许多射击游戏相同。",
        ["3  Empfindlichkeit"] = "3  灵敏度",
        ["Voller Ausschlag ab"] = "满输出起始点",
        ["Kleinerer Wert bei „Voller Ausschlag ab“ = empfindlicher. „Mindestausschlag“ überwindet die Totzone des Spiels."] =
            "“满输出起始点”数值越小越灵敏。“最小输出”克服游戏死区。",
        ["Mitte"] = "中心",
        ["Vorschau: Fadenkreuz folgt dem Controller (unabhängig von Schritt 2)."] = "预览：准星跟随控制器（独立于第 2 步）。",
        ["Keine Bewegungsdaten"] = "无运动数据",
        ["Controller gekoppelt"] = "控制器已配对",
        ["Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive: SYNC-Taste drücken, bis die Lichter laufen.\n" +
         "Wii-Fernbedienung: Batteriefach öffnen und die rote SYNC-Taste drücken.\n" +
         "Wii U Pro Controller: die SYNC-Taste auf der Unterseite drücken.\n" +
         "Danach verbindet sich der Controller künftig per Tastendruck."] =
            "Joy-Con、Pro 手柄、NES/SNES/N64/Mega Drive：按 SYNC 键直到指示灯滚动。\n" +
            "Wii 遥控器：打开电池仓并按红色 SYNC 键。\n" +
            "Wii U Pro 手柄：按底部的 SYNC 键。\n" +
            "之后控制器按任意键即可连接。",
        ["Suche … SYNC-Taste drücken (Xbox: Kopplungstaste oben halten, PlayStation: PS + Teilen/Create halten)."] =
            "搜索中 … 请按 SYNC 键（Xbox：按住顶部配对键；PlayStation：按住 PS + Share/Create）。",
        ["Kein Controller im Kopplungsmodus gefunden. SYNC-Taste drücken und erneut versuchen."] =
            "未找到处于配对模式的控制器。请按 SYNC 后重试。",
        ["Darstellung:"] = "外观：",
        ["Dunkel"] = "深色",
        ["Hell"] = "浅色",
        ["Wie Windows"] = "与 Windows 一致",
        ["Mica-Effekt in der Titelleiste (ab Windows 11)"] = "标题栏云母效果（Windows 11 及以上）",

        // ---------- Fehlerfälle und Hinweise ----------
        ["Bluetooth ist ausgeschaltet."] = "蓝牙已关闭。",
        ["Dieser Bluetooth-Adapter unterstützt kein Bluetooth LE."] = "此蓝牙适配器不支持低功耗蓝牙（BLE）。",
        ["Bluetooth-Suche konnte nicht starten."] = "无法启动蓝牙搜索。",
        ["Bluetooth in den Windows-Einstellungen einschalten."] = "请在 Windows 设置中开启蓝牙。",
        ["Controller per USB funktionieren weiterhin."] = "USB 连接的控制器仍可正常使用。",
        ["Für Switch-2-Controller wird ein Adapter mit Bluetooth 4.0 oder neuer gebraucht."] = "Switch 2 控制器需要蓝牙 4.0 或更高版本的适配器。",
        ["Andere Controller und USB funktionieren weiterhin."] = "其他控制器和 USB 仍可正常使用。",
        ["Bluetooth-Adapter (z. B. USB-Stick) einstecken bzw. Bluetooth in Windows aktivieren."] =
            "请插入蓝牙适配器（如 USB 适配器）或在 Windows 中启用蓝牙。",
        ["Bluetooth ist bereit – Controller können verbunden werden."] = "蓝牙已就绪 – 可以连接控制器。",
        ["Bluetooth-Einstellungen öffnen"] = "打开蓝牙设置",
        ["ViGEmBus-Treiber fehlt – ohne ihn kann kein virtueller Controller erzeugt werden."] =
            "缺少 ViGEmBus 驱动 – 没有它无法创建虚拟控制器。",
        ["Bitte das Setup erneut ausführen."] = "请重新运行安装程序。",
        ["Das Programm schließen oder in Steam die Nintendo-Unterstützung abschalten."] =
            "请关闭该程序或在 Steam 中禁用 Nintendo 支持。",
        ["Erst einen anderen trennen."] = "请先断开另一个控制器。",
        ["Tipp: Bluetooth-Stick per Verlängerung näher an den Controller, weg von USB-3-Anschlüssen und Funkkopfhörern."] =
            "提示：用延长线让蓝牙适配器更靠近控制器，远离 USB 3 接口和无线耳机。",
        ["Controller mit dem PC gekoppelt – ab jetzt reicht ein Tastendruck."] = "控制器已与电脑配对 – 以后按任意键即可连接。",
        ["Hinweis: Um ihn wieder an der Switch 2 zu nutzen, dort einmal kurz SYNC drücken."] =
            "提示：如需在 Switch 2 上再次使用，请在主机上短按一次 SYNC。",
        ["Dieser Bluetooth-Adapter unterstützt kein Bluetooth LE"] = "此蓝牙适配器不支持低功耗蓝牙（BLE）",
        ["Erst IR-Kamera bzw. Ring-Con ausschalten (sie nutzen denselben Zusatzprozessor wie der NFC-Leser)."] =
            "请先关闭红外摄像头或 Ring-Con（它们与 NFC 读取器共用同一协处理器）。",
        ["Erst die IR-Kamera schließen (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "请先关闭红外摄像头（Ring-Con 和红外摄像头共用同一协处理器）。",
        ["Erst den Ring-Con ausschalten (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "请先关闭 Ring-Con（Ring-Con 和红外摄像头共用同一协处理器）。",
        ["amiibo zu früh entfernt"] = "amiibo 移开过早",
        ["MCU startet nicht"] = "协处理器无法启动",
        ["NFC-Modus nicht aktiv"] = "NFC 模式未激活",
        ["Kopplung fehlgeschlagen – Details im Protokoll."] = "配对失败 – 详见日志。",

        // ---------- Kopplungsdaten (Switch-SD-Karte, anderer PC) ----------
        ["Kopplungsdaten"] = "配对数据",
        ["Kopplungen übernehmen oder weitergeben"] = "导入或分享配对信息",
        ["Kopplungsdaten von der Switch übernehmen"] = "从 Switch 导入配对数据",
        ["Von der Switch-SD-Karte (Bluepick_RCM/hekate) oder von einem anderen PC übernehmen, oder für einen anderen PC exportieren."] =
            "从 Switch 的 SD 卡（Bluepick_RCM/hekate）或另一台电脑导入，或为另一台电脑导出。",
        ["Bei Switch-SD-Karte nachfragen"] = "检测到 Switch SD 卡时询问",
        ["Steckt eine SD-Karte der Switch im PC (Kartenleser oder hekate „USB Tools“), bietet N-Connect die Übernahme an. Die Karte wird nur gelesen."] =
            "当 Switch 的 SD 卡插入电脑时（读卡器或 hekate“USB Tools”），N-Connect 会提供导入选项。存储卡仅被读取。",
        ["Switch-SD-Karte erkannt"] = "检测到 Switch SD 卡",
        ["Kopplungsdaten der Controller gefunden – klicken, um sie anzusehen und zu übernehmen."] =
            "找到控制器配对数据 – 点击查看并导入。",
        ["Klicken, um Kopplungsdaten der Controller zu übernehmen."] = "点击以导入控制器配对数据。",
        ["Controller-Kopplungen von der Switch-SD-Karte oder von einem anderen PC übernehmen – oder für einen anderen PC exportieren. Es werden nur Einstellungen von N-Connect geändert; Windows und der Bluetooth-Adapter bleiben unverändert."] =
            "从 Switch 的 SD 卡或另一台电脑导入控制器配对信息 – 或为另一台电脑导出。仅更改 N-Connect 的设置；Windows 和蓝牙适配器保持不变。",
        ["Spieler-Reihenfolge – Spieler 1 ist für Windows, Steam und Spiele der erste Controller. Mit ‹ › umsortieren."] =
            "玩家顺序 – 玩家 1 是 Windows、Steam 和游戏中的第一个控制器。用 ‹ › 调整顺序。",
        ["Von der Switch-SD-Karte"] = "从 Switch 的 SD 卡",
        ["Mit Bluepick_RCM oder hekate erstellte Kopplungsdaten (switchroot/joycon_mac.ini)"] =
            "由 Bluepick_RCM 或 hekate 创建的配对数据（switchroot/joycon_mac.ini）",
        ["Einlesen …"] = "读取 …",
        ["Von einem anderen PC"] = "从另一台电脑",
        ["Mit N-Connect exportierte Datei (*.ncpair)"] = "N-Connect 导出的文件（*.ncpair）",
        ["Datei öffnen …"] = "打开文件 …",
        ["Inhalt"] = "内容",
        ["Weitergeben und sichern"] = "分享与备份",
        ["Für einen anderen PC exportieren"] = "为另一台电脑导出",
        ["Bekannte Controller und Einstellungen je Controller, optional mit Passwort"] =
            "已知控制器及每个控制器的设置，可选密码保护",
        ["Sicherung wiederherstellen"] = "恢复备份",
        ["Vor jedem „Übernehmen“ wird automatisch eine Sicherung angelegt"] = "每次“应用”前自动创建备份",
        ["Wiederherstellen …"] = "恢复 …",
        ["Bluetooth-Adapter dieses PCs"] = "此电脑的蓝牙适配器",
        ["wird ermittelt …"] = "正在检测 …",
        ["nicht gefunden"] = "未找到",
        ["Quelle wählen: Switch-SD-Karte (mit Bluepick_RCM oder hekate erstellte Kopplungsdaten) oder eine Datei von einem anderen PC."] =
            "选择来源：Switch 的 SD 卡（由 Bluepick_RCM 或 hekate 创建的配对数据）或来自另一台电脑的文件。",
        ["Keine Switch-SD-Karte gefunden. SD-Karte in den Kartenleser stecken oder die Switch per hekate („USB Tools“ → „SD Card“) als Laufwerk verbinden.\n\nOrdner selbst auswählen?"] =
            "未找到 Switch SD 卡。请将 SD 卡插入读卡器，或通过 hekate（“USB Tools”→“SD Card”）将 Switch 作为驱动器连接。\n\n手动选择文件夹？",
        ["Stammordner der Switch-SD-Karte wählen"] = "选择 Switch SD 卡的根目录",
        ["Switch-SD-Karte:"] = "Switch SD 卡：",
        ["Auf der Karte liegen keine Kopplungsdaten (switchroot/joycon_mac.ini)."] = "卡上没有配对数据（switchroot/joycon_mac.ini）。",
        ["So erstellst du sie: Joy-Con an die Switch stecken, Bluepick_RCM starten und „Dump Joy-Con BT pairing → SD“ (oder FULL AUTO) wählen. Alternativ in hekate: Nyx → Konsole → „Dump Joy-Con BT“."] =
            "创建方法：将 Joy-Con 插到 Switch 上，启动 Bluepick_RCM 并选择“Dump Joy-Con BT pairing → SD”（或 FULL AUTO）。或者在 hekate 中：Nyx → Console →“Dump Joy-Con BT”。",
        ["Gefunden wurde eine Bluepick-Sicherung des Bluetooth-Speichers (8000000000000050.bin). Sie ist ein Switch-Speicherabbild und kann hier nicht ausgewertet werden."] =
            "找到 Bluepick 的蓝牙存储备份（8000000000000050.bin）。这是 Switch 的内存镜像，无法在此解析。",
        ["Bluetooth-Adresse der Switch:"] = "Switch 的蓝牙地址：",
        ["Gefundene Controller:"] = "找到的控制器：",
        ["mit der Switch gekoppelt"] = "已与 Switch 配对",
        ["zuletzt mit einem anderen Gerät gekoppelt (nicht der Switch)"] = "最后与其他设备配对（非 Switch）",
        ["Joy-Con (L)"] = "Joy-Con（左）",
        ["Joy-Con (R)"] = "Joy-Con（右）",
        ["HORI-Controller (links)"] = "HORI 控制器（左）",
        ["HORI-Controller (rechts)"] = "HORI 控制器（右）",
        ["Hinweis: Pro Controller stehen nur im Bluetooth-Speicher der Switch (8000000000000050.bin); dieses Speicherabbild kann N-Connect nicht auswerten."] =
            "注意：Pro 手柄仅记录在 Switch 的蓝牙存储中（8000000000000050.bin）；N-Connect 无法解析此内存镜像。",
        ["Was diese Daten können – und was nicht:"] = "这些数据能做什么 – 不能做什么：",
        ["Die Daten zeigen, welche Controller mit deiner Switch gekoppelt sind und an welche Bluetooth-Adresse sie gebunden sind."] =
            "数据显示哪些控制器与你的 Switch 配对，以及它们绑定的蓝牙地址。",
        ["Ein Switch-1-Controller verbindet sich auf Tastendruck nur mit dem Gerät, dessen Adresse er gespeichert hat – hier mit der Switch. Der Bluetooth-Adapter des PCs hat eine andere Adresse, deshalb kann Windows diese Kopplung nicht einfach weiterverwenden."] =
            "Switch 1 控制器按键连接时只会连接它记住地址的设备 – 此处是 Switch。电脑的蓝牙适配器有不同地址，因此 Windows 无法直接复用这个配对。",
        ["Die Adresse des PC-Adapters zu ändern, unterstützt N-Connect bewusst nicht (herstellerabhängig, riskant und nicht vorgesehen)."] =
            "N-Connect 有意不支持修改电脑适配器地址（因厂商而异、有风险且非预期用途）。",
        ["Windows bietet keinen offiziellen Weg, fremde Kopplungsschlüssel einzutragen: Sie liegen in einem Teil der Registrierung, auf den nur das System zugreifen darf. N-Connect ändert dort nichts."] =
            "Windows 没有官方途径写入外来的配对密钥：它们存储在注册表中仅系统可访问的部分。N-Connect 不会修改那里。",
        ["So klappt der Wechsel am einfachsten: am PC den Controller einmal per SYNC-Taste in den Windows-Bluetooth-Einstellungen koppeln. Zurück an der Switch die Joy-Con an die Konsole stecken bzw. den Pro Controller per USB-Kabel anschließen – dann sind sie ohne Menü wieder mit der Switch gekoppelt."] =
            "最简单的切换方法：在电脑上通过 Windows 蓝牙设置用 SYNC 键配对一次控制器。回到 Switch 时，将 Joy-Con 插入主机或用 USB 线连接 Pro 手柄 – 无需菜单即可重新与 Switch 配对。",
        ["„Übernehmen“ merkt sich diese Controller in N-Connect (Liste bekannter Controller, Zuordnung zur Switch). Kopplungsschlüssel werden nicht gespeichert."] =
            "“应用”会将这些控制器记入 N-Connect（已知控制器列表、与 Switch 的关联）。配对密钥不会被保存。",
        ["N-Connect-Kopplungsdaten"] = "N-Connect 配对数据",
        ["Kopplungsdaten von einem anderen PC öffnen"] = "打开来自另一台电脑的配对数据",
        ["Die Datei ist zu groß."] = "文件过大。",
        ["Keine Kopplungsdaten-Datei."] = "不是配对数据文件。",
        ["Die Datei stammt von einer neueren N-Connect-Version."] = "该文件由更新版本的 N-Connect 创建。",
        ["Die Datei ist mit einem Passwort geschützt."] = "该文件受密码保护。",
        ["Falsches Passwort oder die Datei wurde verändert."] = "密码错误或文件已被修改。",
        ["Die Datei ist beschädigt."] = "文件已损坏。",
        ["Datei von:"] = "文件来源：",
        ["Bluetooth-Adapter dort:"] = "对方的蓝牙适配器：",
        ["Bluetooth-Adapter hier:"] = "此处的蓝牙适配器：",
        ["gekoppelt mit der Switch"] = "已与 Switch 配对",
        ["gekoppelt mit dem anderen PC"] = "已与另一台电脑配对",
        ["Weitere Einstellungen je Controller:"] = "每个控制器的其他设置：",
        ["Was du erwarten kannst:"] = "预期效果：",
        ["Gleiche Adapter-Adresse (z. B. derselbe USB-Bluetooth-Stick umgesteckt): Switch-2-Controller verbinden sich hier auf Tastendruck wie am anderen PC."] =
            "相同适配器地址（例如同一个 USB 蓝牙适配器换插到这台电脑）：Switch 2 控制器在此按键即连，与在另一台电脑上一样。",
        ["Switch-1-Controller (Pro Controller, Joy-Con) brauchen zusätzlich die Kopplung in Windows. Die kann N-Connect nicht übertragen – einmal per SYNC-Taste koppeln."] =
            "Switch 1 控制器（Pro 手柄、Joy-Con）还需要在 Windows 中配对。N-Connect 无法传输 – 请用 SYNC 键配对一次。",
        ["Anderer Bluetooth-Adapter: Controller verbinden sich auf Tastendruck nur mit dem Gerät, mit dem sie zuletzt gekoppelt wurden. Hier einmal SYNC drücken – danach verbinden sie sich mit diesem PC (am anderen PC dann wieder per SYNC)."] =
            "不同的蓝牙适配器：控制器按键连接时只会连接最后配对的设备。在此按一次 SYNC – 之后它们会连接这台电脑（在另一台电脑上则需再次按 SYNC）。",
        ["Tipp: Wer denselben USB-Bluetooth-Stick zwischen den PCs umsteckt, nimmt die Adresse mit – Switch-2-Controller verbinden sich dann an beiden PCs ohne SYNC."] =
            "提示：在电脑间换插同一个 USB 蓝牙适配器会带走地址 – Switch 2 控制器在两台电脑上都能免 SYNC 连接。",
        ["Übernommen werden die Einstellungen je Controller (Joy-Con einzeln/hochkant, Gyro-Kalibrierung) und die Liste bekannter Controller."] =
            "导入的内容为每个控制器的设置（Joy-Con 单个/竖握、陀螺仪校准）和已知控制器列表。",
        ["Die Datei enthält Kopplungsschlüssel. Windows bietet keinen offiziellen Weg, sie einzutragen – N-Connect übernimmt sie deshalb nicht."] =
            "该文件包含配对密钥。Windows 没有官方途径写入 – 因此 N-Connect 不会导入它们。",
        ["„Übernehmen“ ergänzt die Controller-Listen und Einstellungen von N-Connect (nichts wird gelöscht). Vorher wird eine Sicherung angelegt."] =
            "“应用”会补充 N-Connect 的控制器列表和设置（不会删除任何内容）。此前会创建备份。",
        ["Kopplungsdaten in N-Connect übernehmen? Vorher wird eine Sicherung der Einstellungen angelegt."] =
            "将配对数据导入 N-Connect？此前会创建设置备份。",
        ["Nichts zu ändern – diese Daten sind schon übernommen."] = "无需更改 – 这些数据已导入。",
        ["Übernommen. Die Sicherung lässt sich hier über „Sicherung wiederherstellen“ zurückholen."] =
            "已导入。可通过此处的“恢复备份”还原。",
        ["Sicherung der Einstellungen"] = "设置备份",
        ["Die Sicherung ist beschädigt und wurde nicht übernommen."] = "备份已损坏，未被应用。",
        ["Alle Einstellungen durch diese Sicherung ersetzen?"] = "用此备份替换所有设置？",
        ["Sicherung wiederhergestellt."] = "备份已恢复。",
        ["Kopplungsdaten für einen anderen PC speichern"] = "为另一台电脑保存配对数据",
        ["Gespeichert. Die Datei am anderen PC in N-Connect unter „Joy-Con & Wii“ → „Kopplungsdaten“ → „Von einem anderen PC“ öffnen."] =
            "已保存。在另一台电脑的 N-Connect 中，于“Joy-Con 与 Wii”→“配对数据”→“从另一台电脑”打开该文件。",
        ["Kopplungsdaten exportieren"] = "导出配对数据",
        ["Passwort eingeben"] = "输入密码",
        ["Passwort (optional). Ohne Passwort steht der Inhalt lesbar in der Datei. Mit Kopplungsschlüsseln ist ein Passwort Pflicht."] =
            "密码（可选）。不设密码时文件内容以明文保存。包含配对密钥时必须设置密码。",
        ["Passwort"] = "密码",
        ["Passwort wiederholen"] = "重复密码",
        ["Kopplungsschlüssel der Switch-Controller mitnehmen"] = "包含 Switch 控制器的配对密钥",
        ["Kopplungsschlüssel mitnehmen (erst Switch-SD-Karte einlesen)"] = "包含配对密钥（请先读取 Switch SD 卡）",
        ["Die Passwörter stimmen nicht überein."] = "两次输入的密码不一致。",
        ["Mit Schlüsseln: Passwort mit mindestens 8 Zeichen."] = "包含密钥时：密码至少 8 个字符。",
        ["Mindestens 8 Zeichen."] = "至少 8 个字符。",
        ["Ohne Passwort."] = "无密码。",
    };

    /// <summary>Meldungen mit Platzhaltern (Chinesisch).</summary>
    private static readonly (Regex Pattern, Func<Match, string> Replace)[] PatternsZh =
    [
        (Re(@"^Allgemeiner Wert \((?<v>.+)\) – Regler verschieben für einen eigenen$"), m => $"通用值（{m.Groups["v"]}）– 移动滑块以设置专属值"),
        (Re(@"^Eigener Wert · allgemein: (?<v>.+)$"), m => $"专属值 · 通用：{m.Groups["v"]}"),
        (Re(@"^Spieler (?<n>\d+)  ·  (?<k>.+?)(?<rest>(  ·  .*)?)$"), m => $"玩家 {m.Groups["n"]}  ·  {N(m, "k")}{T(m.Groups["rest"].Value)}"),
        (Re(@"^  ·  Gyro-Maus(?<r>.*)$"), m => "  ·  陀螺仪鼠标" + T(m.Groups["r"].Value)),
        (Re(@"^  ·  Gyro-Stick$"), _ => "  ·  陀螺仪摇杆"),
        (Re(@"^Spieler (?<n>\d+) · (?<k>.+?) (?<b>\d+ %.*)?$"), m => $"玩家 {m.Groups["n"]} · {N(m, "k")} {m.Groups["b"]}"),
        (Re(@"^(?<k>.+) verbunden \(Spieler (?<n>\d+)\)$"), m => $"{N(m, "k")} 已连接（玩家 {m.Groups["n"]}）"),
        (Re(@"^Spieler (?<n>\d+) – tauschen mit (?<k>.+)$"), m => $"玩家 {m.Groups["n"]} – 与 {N(m, "k")} 交换"),
        (Re(@"^Spieler (?<n>\d+) – frei$"), m => $"玩家 {m.Groups["n"]} – 空闲"),
        (Re(@"^Spieler (?<n>\d+)$"), m => $"玩家 {m.Groups["n"]}"),
        (Re(@"^Xbox 360 · Platz (?<n>\d+)$"), m => $"Xbox 360 · 位置 {m.Groups["n"]}"),
        (Re(@"^noch (?<n>\d+) s$"), m => $"剩余 {m.Groups["n"]} 秒"),
        (Re(@"^Fertig – (?<n>\d+) Controller verbunden$"), m => $"完成 – 已连接 {m.Groups["n"]} 个控制器"),
        (Re(@"^✓ (?<k>.+) verbunden – Spieler (?<n>\d+)$"), m => $"✓ {N(m, "k")} 已连接 – 玩家 {m.Groups["n"]}"),
        (Re(@"^Spieler (?<n>\d+)  ·  (?<v>.+)$"), m => $"玩家 {m.Groups["n"]}  ·  {m.Groups["v"]}"),
        (Re(@"^Gekoppelt: (?<k>.+) – verbindet gleich …$"), m => $"已配对：{m.Groups["k"]} – 即将连接 …"),
        (Re(@"^Ins Spiel wechseln … (?<n>\d+)$"), m => $"切换到游戏 … {m.Groups["n"]}"),
        (Re(@"^(?<k>.+) ist jetzt Spieler (?<n>\d+)$"), m => $"{N(m, "k")} 现在是玩家 {m.Groups["n"]}"),
        (Re(@"^Spieler (?<a>\d+) und (?<b>\d+) getauscht$"), m => $"玩家 {m.Groups["a"]} 和 {m.Groups["b"]} 已交换"),
        (Re(@"^Name für (?<k>.+) \(leer = Standardname\):$"), m => $"{N(m, "k")} 的名称（留空 = 默认名）："),
        (Re(@"^(?<k>.+) \(Joy-Con-Paar\)$"), m => $"{m.Groups["k"]}（Joy-Con 组合）"),
        (Re(@"^Joy-Con zusammengefasst \(Spieler (?<n>\d+)\)$"), m => $"Joy-Con 已组合（玩家 {m.Groups["n"]}）"),
        (Re(@"^Joy-Con getrennt – (?<k>.+) ist jetzt Spieler (?<n>\d+)$"), m => $"Joy-Con 已分离 – {N(m, "k")} 现在是玩家 {m.Groups["n"]}"),
        (Re(@"^Spieler (?<n>\d+): Akku (?<k>.+) fast leer \((?<p>\d+) %\) – bitte aufladen$"),
            m => $"玩家 {m.Groups["n"]}：{N(m, "k")} 电量不足（{m.Groups["p"]} %）– 请充电"),
        (Re(@"^Spieler (?<n>\d+): nach (?<m>\d+) min ohne Eingabe getrennt$"),
            m => $"玩家 {m.Groups["n"]}：{m.Groups["m"]} 分钟无操作后已断开"),
        (Re(@"^Profil „(?<p>.+)“ aktiv$"), m => $"配置文件“{ProfileName(m.Groups["p"].Value)}”已激活"),
        (Re(@"^Profil: (?<p>.+)$"), m => $"配置文件：{ProfileName(m.Groups["p"].Value)}"),
        (Re(@"^Profil „(?<p>.+)“ löschen\?$"), m => $"删除配置文件“{m.Groups["p"]}”？"),
        (Re(@"^Profil „(?<p>.+)“ importiert(?<r>.*)$"), m => $"配置文件“{m.Groups["p"]}”已导入" + m.Groups["r"].Value.Replace("aktiv bei:", "激活于：")),
        (Re(@"^⬇ Neue Version (?<v>.+) herunterladen …$"), m => $"⬇ 下载新版本 {m.Groups["v"]} …"),
        (Re(@"^Version (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Herunterladen\.$"),
            m => $"版本 {m.Groups["v"]} 已发布（当前安装：{m.Groups["i"]}）。点击下载。"),
        (Re(@"^Version (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Installieren\.$"),
            m => $"版本 {m.Groups["v"]} 已发布（当前安装：{m.Groups["i"]}）。点击安装。"),
        (Re(@"^⬇ Auf Version (?<v>.+) aktualisieren …$"), m => $"⬇ 更新到版本 {m.Groups["v"]} …"),
        (Re(@"^Lade Version (?<v>.+) herunter …$"), m => $"正在下载版本 {m.Groups["v"]} …"),
        (Re(@"^HidHide (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Installieren\.$"),
            m => $"HidHide {m.Groups["v"]} 已发布（当前安装：{m.Groups["i"]}）。点击安装。"),
        (Re(@"^Lade HidHide (?<v>.+) herunter …$"), m => $"正在下载 HidHide {m.Groups["v"]} …"),
        (Re(@"^(?<t>.+) · (?<r>\d+) Berichte/s$"), m => $"{T(m.Groups["t"].Value)} · {m.Groups["r"]} 报告/秒"),
        (Re(@"^(?<p>\d+ %)(?<v>  \(.*\))?  ⚡ lädt$"), m => $"{m.Groups["p"]}{m.Groups["v"]}  ⚡ 充电中"),
        (Re(@"^Speichern fehlgeschlagen: (?<e>.*)$"), m => $"保存失败：{m.Groups["e"]}"),
        (Re(@"^Lesen fehlgeschlagen: (?<e>.*)$"), m => $"读取失败：{m.Groups["e"]}"),
        (Re(@"^amiibo konnte nicht gelesen werden: (?<e>.*)$"), m => $"无法读取 amiibo：{T(m.Groups["e"].Value)}"),
        (Re(@"^Gekoppelt: (?<k>.+)$"), m => $"已配对：{m.Groups["k"]}"),
        (Re(@"^Gefunden: (?<k>.+) – kopple …$"), m => $"找到：{m.Groups["k"]} – 配对中 …"),
        (Re(@"^amiibo erkannt \((?<u>.+)\) – lese …$"), m => $"识别到 amiibo（{m.Groups["u"]}）– 读取中 …"),
        (Re(@"^(?<n>\d+) Minuten$"), m => $"{m.Groups["n"]} 分钟"),
        (Re(@"^✓ (?<n>\d+) Schritte, Dauer (?<ms>\d+) ms$"), m => $"✓ {m.Groups["n"]} 步，共 {m.Groups["ms"]} 毫秒"),
        (Re(@"^Controller-Taste „(?<b>.+)“:\nJetzt die gewünschte Taste oder Tastenkombination drücken\.$"),
            m => $"控制器按键“{T(m.Groups["b"].Value)}”：\n现在请按下所需的按键或组合键。"),
        (Re(@"^Solange „(?<b>.+)“ gehalten wird, wird diese Taste schnell wiederholt gedrückt\n\(Geschwindigkeit unter 5\. „Turbo“\):$"),
            m => $"按住“{T(m.Groups["b"].Value)}”时，此按键将快速重复触发\n（速度见第 5 项“连发”）："),
        (Re(@"^Ring-Con: (?<e>.*)$"), m => $"Ring-Con：{T(m.Groups["e"].Value)}"),
        (Re(@"^⌨  Taste: (?<k>.+)$"), m => $"⌨  按键：{m.Groups["k"]}"),
        (Re(@"^🔁  Turbo: Taste (?<k>.+)$"), m => $"🔁  连发：按键 {m.Groups["k"]}"),
        (Re(@"^🔁  Turbo: (?<k>.+)$"), m => $"🔁  连发：{T(m.Groups["k"].Value)}"),
        (Re(@"^⏯  Makro: (?<k>.+)$"), m => $"⏯  宏：{m.Groups["k"]}"),
        (Re(@"^Tastatur: (?<k>.+)$"), m => $"键盘：{m.Groups["k"]}"),
        (Re(@"^Gamepad: (?<k>.+)$"), m => $"手柄：{m.Groups["k"]}"),
        (Re(@"^(?<k>.+)  \(verbunden\)$"), m => $"{N(m, "k")}（已连接）"),
        (Re(@"^Bluetooth nicht verfügbar: (?<e>.*)$"), m => $"蓝牙不可用：{m.Groups["e"]}"),
        (Re(@"^(?<k>.+) per USB ist von einem anderen Programm belegt \(z\. B\. Steam\)\.$"),
            m => $"{N(m, "k")} 的 USB 被其他程序占用（例如 Steam）。"),
        (Re(@"^Schon (?<n>\d+) Controller verbunden – (?<k>.+) wird nicht verwendet\.$"),
            m => $"已连接 {m.Groups["n"]} 个控制器 – {N(m, "k")} 不会被使用。"),
        (Re(@"^(?<k>.+): schwache Bluetooth-Verbindung \((?<r>\d+) statt 33–60 Berichte/s\)\.$"),
            m => $"{N(m, "k")}：蓝牙连接较弱（{m.Groups["r"]} 报告/秒，正常为 33–60）。"),
        (Re(@"^(?<k>.+) getrennt$"), m => $"{N(m, "k")} 已断开"),
    ];
}
