using System.Text.RegularExpressions;

namespace Switch2Pro.Bridge;

/// <summary>Feste Texte Deutsch → Russisch. Schlüssel bleiben die deutschen Originaltexte.</summary>
internal static partial class Tr
{
    private static readonly Dictionary<string, string> TextsRu = new(StringComparer.Ordinal)
    {
        // ---------- Fenster, Reiter, Abschnitte ----------
        ["Controller"] = "Контроллеры",
        ["Einstellungen (optional)"] = "Настройки (необязательно)",
        ["1. Windows und Spiele sehen den Controller als …"] = "1. Windows и игры видят контроллер как …",
        ["2. Tasten A/B/X/Y"] = "2. Кнопки A/B/X/Y",
        ["3. Vibration, Sticks, Verbinden, Gyro-Maus"] = "3. Вибрация, стики, подключение, гиромышь",
        ["4. Joy-Con"] = "4. Joy-Con",
        ["4. Joy-Con und Wii"] = "4. Joy-Con и Wii",
        ["Wii-Fernbedienung: Zeiger (Sensorleiste) steuert die Maus"] = "Пульт Wii: указатель (сенсорная планка) управляет мышью",
        ["Zeiger"] = "Указатель",
        ["kein Zeiger – Sensorleiste nicht im Blick"] = "нет указателя – сенсорная планка не в поле зрения",
        ["5. Zielen, Sticks, Trigger, Turbo"] = "5. Прицеливание, стики, триггеры, турбо",
        ["6. Tastenbelegung und Profile  (Taste → Gamepad, Tastatur, Maus, Gyro-Maus, Shift-Ebene)"] =
            "6. Назначение кнопок и профили  (кнопка → геймпад, клавиатура, мышь, гиромышь, слой Shift)",
        ["Xbox-360-Controller  (empfohlen – läuft mit fast allen Spielen)"] = "Контроллер Xbox 360  (рекомендуется – работает почти со всеми играми)",
        ["PlayStation DualShock 4  (mit Bewegungssteuerung/Gyro – für Steam && Emulatoren)"] =
            "PlayStation DualShock 4  (с гироскопом – для Steam и эмуляторов)",
        ["Xbox-Belegung  (nach Position: untere Taste = A)"] = "Раскладка Xbox  (по положению: нижняя кнопка = A)",
        ["Nintendo-Belegung  (nach Beschriftung: A bleibt A)"] = "Раскладка Nintendo  (по надписи: A остаётся A)",
        ["Vibration"] = "Вибрация",
        ["Stärke:"] = "Сила:",
        ["Stick-Totzone (alle Controller):"] = "Мёртвая зона стика (все контроллеры):",
        ["Beim Verbinden kurz vibrieren"] = "Краткая вибрация при подключении",
        ["Meldung bei Verbinden"] = "Уведомление о подключении",
        ["Wer meldet, wenn ein Controller verbunden oder getrennt wird."] = "Выберите, кто уведомляет при подключении или отключении контроллера.",
        ["„N-Connect“ zeigt den echten Controller-Namen und schaltet die Gerätemeldungen von Windows ab."] = "\"N-Connect\" показывает настоящее имя контроллера и отключает уведомления устройств Windows.",
        ["N-Connect (empfohlen)"] = "N-Connect (рекомендуется)",
        ["N-Connect und Windows"] = "N-Connect и Windows",
        ["Keine"] = "Нет",
        ["Gekoppelte Controller per Tastendruck verbinden (ohne SYNC)"] = "Подключать сопряжённые контроллеры нажатием кнопки (без SYNC)",
        ["Automatisch mit Windows starten"] = "Запускать автоматически с Windows",
        ["Gyro für Emulatoren bereitstellen (Cemuhook/DSU, Port 26760 – wirkt nach Neustart)"] =
            "Предоставлять гироскоп эмуляторам (Cemuhook/DSU, порт 26760 – действует после перезапуска)",
        ["Beim Start nach neuer Version suchen (GitHub)"] = "Искать новую версию при запуске (GitHub)",
        ["Ohne Eingabe automatisch trennen nach:"] = "Автоматически отключать без действий через:",
        ["Gyro-Maus-Geschwindigkeit:"] = "Скорость гиромыши:",
        ["Sprache / Language:"] = "Язык / Language:",
        ["Automatisch (wie Windows)"] = "Автоматически (как в Windows)",
        ["nie"] = "никогда",
        ["Zwei Joy-Con automatisch zu einem Controller zusammenfassen"] = "Автоматически объединять два Joy-Con в один контроллер",
        ["Gyro beim Paar vom:"] = "Гироскоп пары от:",
        ["rechter Joy-Con (wie Switch)"] = "правый Joy-Con (как на Switch)",
        ["linker Joy-Con"] = "левый Joy-Con",
        ["Joy-Con 2 als Maus, wenn er auf dem Tisch liegt"] = "Joy-Con 2 как мышь, когда лежит на столе",
        ["Mausgeschwindigkeit:"] = "Скорость мыши:",
        ["Maus: links/rechts umkehren"] = "Мышь: инвертировать влево/вправо",
        ["Maus: hoch/runter umkehren"] = "Мышь: инвертировать вверх/вниз",
        ["Wie an der Switch: SL + SR eine Sekunde halten löst einen Joy-Con aus dem Paar. L am linken und R am rechten einzelnen Joy-Con gleichzeitig drücken verbindet sie wieder zum Paar. Die Wahl wird je Joy-Con gemerkt (auch nach dem nächsten Verbinden). Im Mausmodus: R/L = Linksklick, ZR/ZL = Rechtsklick, Stick drücken = Mittelklick, Stick hoch/runter = Scrollen."] =
            "Как на Switch: удержание SL + SR секунду отсоединяет Joy-Con от пары. Одновременное нажатие L на левом и R на правом отдельном Joy-Con снова объединяет их. Выбор запоминается для каждого Joy-Con (в том числе при следующем подключении). В режиме мыши: R/L = левая кнопка, ZR/ZL = правая кнопка, нажатие стика = средняя кнопка, стик вверх/вниз = прокрутка.",
        ["Gyro als rechter Stick:"] = "Гироскоп как правый стик:",
        ["aus (nur per Taste „Gyro-Stick“)"] = "выкл. (только кнопкой «гиростик»)",
        ["immer"] = "всегда",
        ["beim Zielen (solange ZL / linker Trigger gedrückt)"] = "при прицеливании (пока нажат ZL / левый триггер)",
        ["hoch/runter umkehren"] = "инвертировать вверх/вниз",
        ["Empfindlichkeit:"] = "Чувствительность:",
        ["Mindestausschlag:"] = "Минимальное отклонение:",
        ["Stick-Kennlinie:"] = "Характеристика стика:",
        ["Turbo (pro Sekunde):"] = "Турбо (в секунду):",
        ["Analoge Trigger (GameCube) – Totzone:"] = "Аналоговые триггеры (GameCube) – мёртвая зона:",
        ["voll gedrückt ab:"] = "полностью нажат с:",
        ["Profil:"] = "Профиль:",
        ["Neu …"] = "Создать …",
        ["Umbenennen …"] = "Переименовать …",
        ["Löschen"] = "Удалить",
        ["Exportieren …"] = "Экспорт …",
        ["Importieren …"] = "Импорт …",
        ["Aktiv bei Programm:"] = "Активен при программе:",
        ["Programm wählen …"] = "Выбрать программу …",
        ["Standard"] = "По умолчанию",
        ["Standard gilt immer, wenn kein anderes Profil passt"] = "По умолчанию применяется, когда не подходит другой профиль",
        ["z. B. Cemu.exe, Ryujinx.exe"] = "напр. Cemu.exe, Ryujinx.exe",
        ["Ein eigenes Profil wird automatisch aktiv, solange eines seiner Programme im Vordergrund ist (sonst gilt „Standard“). Im Infobereich-Menü lässt sich ein Profil auch fest wählen."] =
            "Собственный профиль активируется автоматически, пока одна из его программ на переднем плане (иначе действует «По умолчанию»). Профиль также можно закрепить в меню области уведомлений.",
        ["Controller:"] = "Контроллер:",
        ["Eigene Stick-Totzone für diesen Controller:"] = "Собственная мёртвая зона стика для этого контроллера:",
        ["Normale Belegung"] = "Обычное назначение",
        ["Shift-Ebene (gilt, solange eine Taste mit „Shift-Ebene“ gehalten wird)"] = "Слой Shift (действует, пока удерживается кнопка «слой Shift»)",
        ["Alles auf Standard"] = "Сбросить всё",
        ["Schließen"] = "Закрыть",
        ["wie normale Belegung"] = "как обычное назначение",

        // ---------- Belegungsziele und Vorlagen ----------
        ["— keine Funktion —"] = "— без функции —",
        ["A (Xbox) / Kreuz (PS)"] = "A (Xbox) / Крест (PS)",
        ["B (Xbox) / Kreis (PS)"] = "B (Xbox) / Круг (PS)",
        ["X (Xbox) / Viereck (PS)"] = "X (Xbox) / Квадрат (PS)",
        ["Y (Xbox) / Dreieck (PS)"] = "Y (Xbox) / Треугольник (PS)",
        ["Ansicht (Back) / Share"] = "Просмотр (Back) / Share",
        ["Menü (Start) / Options"] = "Меню (Start) / Options",
        ["Xbox-Taste / PS-Taste"] = "Кнопка Xbox / кнопка PS",
        ["Linker Stick-Klick"] = "Нажатие левого стика",
        ["Rechter Stick-Klick"] = "Нажатие правого стика",
        ["Steuerkreuz hoch"] = "Крестовина вверх",
        ["Steuerkreuz runter"] = "Крестовина вниз",
        ["Steuerkreuz links"] = "Крестовина влево",
        ["Steuerkreuz rechts"] = "Крестовина вправо",
        ["Touchpad-Klick (nur DualShock 4)"] = "Нажатие тачпада (только DualShock 4)",
        ["🖱  Maus: Linksklick"] = "🖱  Мышь: левая кнопка",
        ["🖱  Maus: Rechtsklick"] = "🖱  Мышь: правая кнопка",
        ["🖱  Maus: Mittelklick"] = "🖱  Мышь: средняя кнопка",
        ["🎯  Gyro-Maus (solange gehalten)"] = "🎯  Гиромышь (пока удерживается)",
        ["🎯  Gyro-Maus ein/aus"] = "🎯  Гиромышь вкл./выкл.",
        ["🎯  Gyro als rechter Stick (solange gehalten)"] = "🎯  Гироскоп как правый стик (пока удерживается)",
        ["🎯  Gyro als rechter Stick ein/aus"] = "🎯  Гироскоп как правый стик вкл./выкл.",
        ["⇧  Shift-Ebene (solange gehalten)"] = "⇧  Слой Shift (пока удерживается)",
        ["🔁  Turbo / Dauerfeuer …"] = "🔁  Турбо / автоген …",
        ["⏯  Makro (Tastenfolge) …"] = "⏯  Макрос (последовательность кнопок) …",
        ["📷  Bildschirmfoto speichern (Win+Druck)"] = "📷  Сохранить снимок экрана (Win+Print)",
        ["📷  Bildschirmausschnitt (Win+Umschalt+S)"] = "📷  Фрагмент экрана (Win+Shift+S)",
        ["⏺  Letzte 30 Sekunden aufnehmen (Win+Alt+G)"] = "⏺  Записать последние 30 секунд (Win+Alt+G)",
        ["⏺  Aufnahme starten/stoppen (Win+Alt+R)"] = "⏺  Начать/остановить запись (Win+Alt+R)",
        ["🎮  Xbox Game Bar (Win+G)"] = "🎮  Xbox Game Bar (Win+G)",
        ["🔊  Lauter"] = "🔊  Громче",
        ["🔉  Leiser"] = "🔉  Тише",
        ["⏯  Wiedergabe/Pause"] = "⏯  Воспроизведение/Пауза",
        ["⌨  Andere Taste / Tastenkombination aufnehmen …"] = "⌨  Записать другую клавишу / сочетание клавиш …",

        // ---------- Tastennamen ----------
        ["+ (Plus)"] = "+ (Plus)",
        ["− (Minus)"] = "− (Minus)",
        ["Aufnahme"] = "Снимок",
        ["GL (Rücktaste links)"] = "GL (задняя кнопка слева)",
        ["GR (Rücktaste rechts)"] = "GR (задняя кнопка справа)",
        ["Linker Stick drücken"] = "Нажать левый стик",
        ["Rechter Stick drücken"] = "Нажать правый стик",
        ["Stick drücken"] = "Нажать стик",
        ["A (groß, unten)"] = "A (большая, внизу)",
        ["B (links)"] = "B (слева)",
        ["X (rechts)"] = "X (справа)",
        ["Y (oben)"] = "Y (сверху)",
        ["L (ganz durchgedrückt)"] = "L (нажат до конца)",
        ["R (ganz durchgedrückt)"] = "R (нажат до конца)",
        ["untere Taste (quer)"] = "нижняя кнопка (горизонтально)",
        ["rechte Taste (quer)"] = "правая кнопка (горизонтально)",
        ["linke Taste (quer)"] = "левая кнопка (горизонтально)",
        ["obere Taste (quer)"] = "верхняя кнопка (горизонтально)",
        ["1 (quer) / Classic Y"] = "1 (горизонтально) / Classic Y",
        ["2 (quer) / Classic B"] = "2 (горизонтально) / Classic B",
        ["B (Abzug) / Classic ZR"] = "B (курок) / Classic ZR",
        ["Kreuz (unten)"] = "Крест (внизу)",
        ["Kreis (rechts)"] = "Круг (справа)",
        ["Viereck (links)"] = "Квадрат (слева)",
        ["Dreieck (oben)"] = "Треугольник (сверху)",
        ["PS-Taste"] = "Кнопка PS",
        ["Touchpad-Klick"] = "Нажатие тачпада",
        ["Mikro stumm"] = "Отключить микрофон",
        ["Fn links (Edge)"] = "Fn слева (Edge)",
        ["Rücktaste links (Edge)"] = "Задняя кнопка слева (Edge)",
        ["Rücktaste rechts (Edge)"] = "Задняя кнопка справа (Edge)",
        ["L3 (Stick drücken)"] = "L3 (нажать стик)",
        ["R3 (Stick drücken)"] = "R3 (нажать стик)",
        ["Ansicht/Zurück"] = "Просмотр/Назад",
        ["Menü/Start"] = "Меню/Start",
        ["Xbox-Taste"] = "Кнопка Xbox",

        // ---------- Controller-Namen ----------
        ["Wii-Fernbedienung"] = "Пульт Wii",
        ["Xbox-Controller"] = "Контроллер Xbox",
        ["Xbox-Controller (Microsoft)"] = "Контроллер Xbox (Microsoft)",
        ["XInput (USB, Bluetooth oder Xbox-Adapter)"] = "XInput (USB, Bluetooth или адаптер Xbox)",

        // ---------- Übersicht / Karten ----------
        ["Trennen"] = "Отключить",
        ["Vibrieren"] = "Вибрация",
        ["Gyro kalibrieren"] = "Калибровать гироскоп",
        ["Ruhig liegen lassen …"] = "Положить неподвижно …",
        ["Kalibriert ✓"] = "Откалибровано ✓",
        ["Hochkant halten"] = "Держать вертикально",
        ["Quer halten"] = "Держать горизонтально",
        ["Joy-Con trennen"] = "Разъединить Joy-Con",
        ["Zum Paar verbinden"] = "Объединить в пару",
        ["Joy-Con trennen – beide werden einzelne Controller"] = "Разделить Joy-Con – оба станут отдельными контроллерами",
        ["Zum Paar verbinden – sucht einen freien Joy-Con"] = "Объединить в пару – ищет свободный Joy-Con",
        ["Doppelt angezeigt? Verstecken"] = "Отображается дважды? Скрыть",
        ["amiibo lesen"] = "Считать amiibo",
        ["Ring-Con ein"] = "Включить Ring-Con",
        ["Ring-Con aus"] = "Выключить Ring-Con",
        ["Ring-Con wird gesucht …"] = "Поиск Ring-Con …",
        ["IR-Kamera"] = "ИК-камера",
        ["Akku"] = "Батарея",
        ["Verbindung"] = "Соединение",
        ["Adresse"] = "Адрес",
        ["Seriennummer"] = "Серийный номер",
        ["Griff"] = "Держатель",
        ["Maus"] = "Мышь",
        ["Gedrückt"] = "Нажато",
        ["unbekannt"] = "неизвестно",
        ["Charging Grip – GL/GR aktiv"] = "Charging Grip – GL/GR активны",
        ["aktiv (liegt auf dem Tisch)"] = "активно (лежит на столе)",
        ["bereit – zum Benutzen auf den Tisch legen"] = "готово – положите на стол для использования",
        ["Bewegungssensor: keine Daten"] = "Датчик движения: нет данных",
        ["quer halten: Steuerkreuz links,\n1 und 2 rechts"] = "горизонтально: крестовина слева,\n1 и 2 справа",

        // ---------- Tooltips ----------
        ["Verbindung trennen. Der Controller verbindet sich beim nächsten Tastendruck wieder."] =
            "Отключить. Контроллер подключится снова при следующем нажатии кнопки.",
        ["Controller kurz vibrieren lassen – zeigt, welcher Controller dieser Spieler ist."] =
            "Краткая вибрация контроллера – показывает, какой контроллер принадлежит этому игроку.",
        ["Controller ruhig auf den Tisch legen und klicken: misst den Gyro-Nullpunkt neu (gegen Abdriften)."] =
            "Положите контроллер на стол и нажмите: заново измеряет нулевую точку гироскопа (против дрейфа).",
        ["Einzelnen Joy-Con quer (wie an der Switch) oder hochkant halten – wird je Joy-Con gemerkt. Hochkant gilt die Tastenbelegung von „Joy-Con-Paar“."] =
            "Держите отдельный Joy-Con горизонтально (как на Switch) или вертикально – запоминается для каждого Joy-Con. Вертикально действует назначение «пара Joy-Con».",
        ["Versteckt den per USB angeschlossenen Controller vor Spielen (HidHide), damit sie nur den virtuellen Xbox-Controller sehen."] =
            "Скрывает от игр контроллер, подключённый по USB (HidHide), чтобы они видели только виртуальный контроллер Xbox.",
        ["amiibo mit dem NFC-Leser lesen und als Datei (.bin) speichern – z. B. für Emulatoren."] =
            "Считывает amiibo через NFC-считыватель и сохраняет в файл (.bin) – например, для эмуляторов.",
        ["Ring-Con am rechten Joy-Con ein-/ausschalten: zusammendrücken = rechter Trigger, auseinanderziehen = linker Trigger. Beim Einschalten den Ring nicht berühren."] =
            "Включает/выключает Ring-Con правого Joy-Con: сжатие = правый триггер, растяжение = левый триггер. Не касайтесь кольца при включении.",
        ["Live-Bild der IR-Kamera im rechten Joy-Con anzeigen."] = "Показывает живое изображение ИК-камеры правого Joy-Con.",
        ["Links = empfindlicher (kleine Drehung, großer Ausschlag), rechts = ruhiger."] = "Влево = чувствительнее (маленький поворот, большое отклонение), вправо = спокойнее.",
        ["Mindestausschlag des Sticks bei Bewegung – überwindet die Totzone des Spiels."] = "Минимальное отклонение стика при движении – преодолевает мёртвую зону игры.",
        ["Mitte = linear. Rechts = feiner um die Mitte (präzises Zielen), links = schneller."] = "Середина = линейно. Вправо = точнее у центра (точное прицеливание), влево = быстрее.",
        ["So weit lässt sich ein analoger Trigger drücken, bevor er wirkt."] = "Насколько можно нажать аналоговый триггер до срабатывания.",
        ["Ab hier gilt der Trigger als ganz gedrückt (100 = erst am Anschlag)."] = "Отсюда триггер считается полностью нажатым (100 = только в упоре).",
        ["Wie oft pro Sekunde Tasten mit „Turbo“ auslösen."] = "Сколько раз в секунду срабатывают кнопки «турбо».",

        // ---------- Infobereich ----------
        ["ViGEmBus-Treiber fehlt"] = "Драйвер ViGEmBus отсутствует",
        ["ViGEmBus herunterladen …"] = "Скачать ViGEmBus …",
        ["Verbinde …"] = "Подключение …",
        ["Kein Controller – SYNC-Taste am Controller kurz drücken"] = "Нет контроллера – кратко нажмите кнопку SYNC на контроллере",
        ["Ausgabe als"] = "Вывод как",
        ["Xbox-360-Controller (empfohlen)"] = "Контроллер Xbox 360 (рекомендуется)",
        ["DualShock 4 (mit Gyro für Steam/Emulatoren)"] = "DualShock 4 (с гироскопом для Steam/эмуляторов)",
        ["Tastenbelegung"] = "Назначение кнопок",
        ["Xbox-Belegung (untere Taste = A)"] = "Раскладка Xbox (нижняя кнопка = A)",
        ["Switch-2-Pro-Belegung (A bleibt A)"] = "Раскладка Nintendo (A остаётся A)",
        ["Automatisch (nach Spiel/Programm)"] = "Автоматически (по игре/программе)",
        ["Mit Windows starten"] = "Запускать с Windows",
        ["Einstellungen …"] = "Настройки …",
        ["Kurzanleitung"] = "Краткое руководство",
        ["Protokoll öffnen"] = "Открыть журнал",
        ["Beenden"] = "Выход",
        ["N-Connect: warte auf Controller (SYNC drücken)"] = "N-Connect: ожидание контроллера (нажмите SYNC)",
        ["N-Connect: ViGEmBus fehlt"] = "N-Connect: ViGEmBus отсутствует",
        ["Neue Version verfügbar"] = "Доступна новая версия",
        ["Einstellungen fehlerhaft"] = "Настройки повреждены",
        ["settings.json konnte nicht gelesen werden – es gelten die Standardwerte."] = "Не удалось прочитать settings.json – действуют значения по умолчанию.",
        ["Ohne ViGEmBus kann kein virtueller Controller erzeugt werden. Bitte das Setup erneut ausführen oder ViGEmBus installieren (Rechtsklick auf das Symbol → ViGEmBus herunterladen)."] =
            "Без ViGEmBus невозможно создать виртуальный контроллер. Запустите установку заново или установите ViGEmBus (правый клик по значку → Скачать ViGEmBus).",

        // ---------- Dialoge ----------
        ["Tastatur-Taste festlegen"] = "Задать клавишу клавиатуры",
        ["Übernehmen"] = "Применить",
        ["Abbrechen"] = "Отмена",
        ["Ja"] = "Да",
        ["Nein"] = "Нет",
        ["Turbo / Dauerfeuer"] = "Турбо / автоген",
        ["Tastatur-Taste aufnehmen …"] = "Записать клавишу клавиатуры …",
        ["Makro (Tastenfolge)"] = "Макрос (последовательность кнопок)",
        ["Ungültig – bitte Schreibweise prüfen (siehe oben)."] = "Недопустимо – проверьте синтаксис (см. выше).",
        ["Neues Profil"] = "Новый профиль",
        ["Name des Profils (z. B. der Spielname):"] = "Имя профиля (например, название игры):",
        ["Profil umbenennen"] = "Переименовать профиль",
        ["Neuer Name:"] = "Новое имя:",
        ["Ein Profil mit diesem Namen gibt es schon."] = "Профиль с таким именем уже существует.",
        ["Die Datei enthält kein gültiges Controller-Profil."] = "Файл не содержит корректного профиля контроллера.",
        ["Alle Einstellungen und Tastenbelegungen auf Standard zurücksetzen?"] = "Сбросить все настройки и назначения кнопок?",
        ["Suche …"] = "Поиск …",
        ["Kein Bluetooth-Adapter gefunden."] = "Bluetooth-адаптер не найден.",
        ["IR-Kamera (Joy-Con R)"] = "ИК-камера (Joy-Con П)",
        ["Auflösung:"] = "Разрешение:",
        ["40 × 30 (schnell)"] = "40 × 30 (быстро)",
        ["320 × 240 (langsam)"] = "320 × 240 (медленно)",
        ["Kamera startet …"] = "Запуск камеры …",
        ["läuft – Joy-Con auf eine Lichtquelle oder die Hand richten"] = "работает – направьте Joy-Con на источник света или руку",
        ["Kamera startet nicht (Details im Protokoll)"] = "Камера не запускается (подробности в журнале)",
        ["Kein Ring-Con gefunden. Den rechten Joy-Con (Switch 1) fest in den Ring-Con schieben und erneut versuchen."] =
            "Ring-Con не найден. Плотно вставьте правый Joy-Con (Switch 1) в Ring-Con и повторите.",
        ["Kein amiibo erkannt. Bitte das amiibo flach an den NFC-Leser halten (Joy-Con: auf den rechten Stick, Pro Controller: auf das NFC-Logo) und erneut versuchen."] =
            "amiibo не обнаружен. Приложите amiibo плоско к NFC-считывателю (Joy-Con: к правому стику; Pro Controller: к логотипу NFC) и повторите.",
        ["NFC-Leser wird eingeschaltet …"] = "Включение NFC-считывателя …",
        ["amiibo an den Leser halten (rechter Stick des Joy-Con bzw. NFC-Logo des Pro Controllers) …"] =
            "Приложите amiibo к считывателю (правый стик Joy-Con или логотип NFC Pro Controller) …",
        ["amiibo speichern"] = "Сохранить amiibo",
        ["Doppelte Controller verhindern"] = "Предотвратить дублирование контроллеров",
        ["Dafür wird das kostenlose Programm HidHide gebraucht (von den Machern von ViGEmBus).\n\nJetzt die Download-Seite öffnen? Nach der Installation hier erneut klicken."] =
            "Для этого нужна бесплатная программа HidHide (от создателей ViGEmBus).\n\nОткрыть страницу загрузки? После установки нажмите здесь снова.",
        ["HidHide konnte nicht eingerichtet werden (abgebrochen oder fehlgeschlagen). Details im Protokoll."] =
            "Не удалось настроить HidHide (отменено или ошибка). Подробности в журнале.",
        ["Der Controller hat sich bewegt oder keine Bewegungsdaten geliefert.\nBitte flach auf den Tisch legen, nicht berühren und erneut versuchen."] =
            "Контроллер двигался или не передал данные о движении.\nПоложите его плоско на стол, не касайтесь и повторите.",
        ["Spiel oder Programm wählen"] = "Выбрать игру или программу",
        ["Profil exportieren"] = "Экспортировать профиль",
        ["Profil importieren"] = "Импортировать профиль",
        ["Verstanden"] = "Понятно",
        ["Einstellungen öffnen"] = "Открыть настройки",
        ["Willkommen"] = "Добро пожаловать",

        // ---------- Neues Hauptfenster (Navigation, Seiten, Zeilen) ----------
        ["Allgemein"] = "Общие",
        ["Sticks & Vibration"] = "Стики и вибрация",
        ["Gyro & Maus"] = "Гироскоп и мышь",
        ["Joy-Con & Wii"] = "Joy-Con и Wii",
        ["Ein"] = "Вкл.",
        ["Aus"] = "Выкл.",
        ["Verbundene Controller mit Live-Anzeige. Über „Einstellungen“ an einem Controller passt du genau diesen an."] =
            "Подключённые контроллеры с живым отображением. Через «Настройки» у контроллера вы настраиваете именно его.",
        ["Jede Taste kann ein Gamepad-Knopf, eine Tastaturtaste, ein Mausklick, Turbo oder ein Makro sein. " +
         "Tipp: Drückst du eine Taste am Controller, wird ihre Zeile hervorgehoben."] =
            "Каждая кнопка может быть кнопкой геймпада, клавишей, щелчком мыши, турбо или макросом. " +
            "Совет: нажмите кнопку на контроллере, чтобы подсветить её строку.",
        ["Profil"] = "Профиль",
        ["Neu"] = "Создать",
        ["Umbenennen, löschen, exportieren, importieren"] = "Переименовать, удалить, экспортировать, импортировать",
        ["Ein eigenes Profil gilt automatisch, solange eines seiner Programme im Vordergrund ist – sonst „Standard“."] =
            "Собственный профиль действует автоматически, пока одна из его программ на переднем плане – иначе «По умолчанию».",
        ["Aktiv bei Programm"] = "Активен при программе",
        ["Programmdateien, bei denen dieses Profil gilt (mit Komma trennen)."] = "Файлы программ, для которых действует этот профиль (через запятую).",
        ["Standard gilt für alle Programme"] = "По умолчанию действует для всех программ",
        ["Wählen …"] = "Выбрать …",
        ["Bearbeiten"] = "Изменить",
        ["Jeder Controller hat seine eigene Belegung."] = "У каждого контроллера своё назначение.",
        ["Ebene"] = "Слой",
        ["Normal"] = "Обычный",
        ["Shift-Ebene"] = "Слой Shift",
        ["Die Shift-Ebene gilt, solange eine Taste mit „Shift-Ebene“ gehalten wird."] = "Слой Shift действует, пока удерживается кнопка со значением «слой Shift».",
        ["Tasten"] = "Кнопки",
        ["Standardwerte für alle Controller. Eigene Werte für einzelne Controller stellst du unten oder in der Übersicht ein."] =
            "Значения по умолчанию для всех контроллеров. Собственные значения для отдельных контроллеров задаются ниже или в обзоре.",
        ["Sticks"] = "Стики",
        ["Totzone"] = "Мёртвая зона",
        ["So weit lässt sich ein Stick bewegen, bevor er wirkt (gegen Abdriften)."] = "Насколько стик может двигаться до срабатывания (против дрейфа).",
        ["Kennlinie"] = "Характеристика",
        ["„linear“ = gleichmäßig. Höher = feiner um die Mitte (präzises Zielen), niedriger = schneller."] =
            "«линейная» = равномерно. Выше = точнее у центра (точное прицеливание), ниже = быстрее.",
        ["Analoge Trigger (GameCube)"] = "Аналоговые триггеры (GameCube)",
        ["So weit lässt sich ein Trigger drücken, bevor er wirkt."] = "Насколько можно нажать триггер до срабатывания.",
        ["Voll gedrückt ab"] = "Полностью нажат с",
        ["Ab hier gilt der Trigger als ganz gedrückt (100 % = erst am Anschlag)."] = "Отсюда триггер считается полностью нажатым (100 % = только в упоре).",
        ["Spiele dürfen den Controller vibrieren lassen."] = "Игры могут вибрировать контроллером.",
        ["Stärke"] = "Сила",
        ["Turbo-Geschwindigkeit"] = "Скорость турбо",
        ["Wie oft pro Sekunde Tasten mit „Turbo“ auslösen."] = "Сколько раз в секунду срабатывают кнопки «турбо».",
        ["Eigene Werte je Controller"] = "Собственные значения для контроллера",
        ["Werte nur für diesen Controller – ohne eigenen Wert gilt der allgemeine."] = "Значения только для этого контроллера – без собственного значения действует общее.",
        ["Bewegungssteuerung: Zielen per Gyro und den Controller als Maus nutzen."] = "Управление движением: прицеливание гироскопом и использование контроллера как мыши.",
        ["Gyro als rechter Stick"] = "Гироскоп как правый стик",
        ["Modus"] = "Режим",
        ["Zum Zielen in Spielen ohne eigene Gyro-Steuerung. „Gyro-Stick“ kann auch einer Taste zugewiesen werden."] =
            "Для прицеливания в играх без собственного гироскопа. «Гиростик» также можно назначить на кнопку.",
        ["Aus (nur per Taste „Gyro-Stick“)"] = "Выкл. (только кнопкой «гиростик»)",
        ["Immer"] = "Всегда",
        ["Beim Zielen (solange ZL / LT gedrückt)"] = "При прицеливании (пока нажат ZL / LT)",
        ["Empfindlichkeit"] = "Чувствительность",
        ["Drehgeschwindigkeit für vollen Stick-Ausschlag – kleiner = empfindlicher."] = "Скорость поворота для полного отклонения стика – меньше = чувствительнее.",
        ["Mindestausschlag"] = "Минимальное отклонение",
        ["Überwindet die Stick-Totzone des Spiels bei kleinen Bewegungen."] = "Преодолевает мёртвую зону стика игры при малых движениях.",
        ["Hoch/runter umkehren"] = "Инвертировать вверх/вниз",
        ["Links/rechts umkehren"] = "Инвертировать влево/вправо",
        ["Gyro-Maus"] = "Гиромышь",
        ["Geschwindigkeit"] = "Скорость",
        ["Mauszeiger per Bewegung – über eine Taste mit „Gyro-Maus“ (Tastenbelegung)."] = "Указатель мыши движением – через кнопку «гиромышь» (назначение кнопок).",
        ["Mausrichtung (Gyro-Maus und Joy-Con-Maus)"] = "Направление мыши (гиромышь и мышь Joy-Con)",
        ["Gyro-Funktionen einer Taste zuweisen"] = "Назначить функции гироскопа на кнопку",
        ["Gyro-Maus oder Gyro-Stick ein/aus bzw. solange gehalten"] = "Гиромышь или гиростик вкл./выкл. или пока удерживается",
        ["Joy-Con als Paar oder einzeln, Joy-Con 2 als Maus und Wii-Controller."] = "Joy-Con в паре или поодиночке, Joy-Con 2 как мышь и контроллеры Wii.",
        ["Zu einem Controller zusammenfassen"] = "Объединить в один контроллер",
        ["Ein linker und ein rechter Joy-Con werden automatisch ein Paar."] = "Левый и правый Joy-Con автоматически образуют пару.",
        ["Gyro beim Paar vom"] = "Гироскоп пары от",
        ["Rechter Joy-Con (wie Switch)"] = "Правый Joy-Con (как на Switch)",
        ["Linker Joy-Con"] = "Левый Joy-Con",
        ["Paar lösen oder verbinden"] = "Разъединить или объединить пару",
        ["Einen Joy-Con quer halten und SL oder SR drücken löst ihn aus dem Paar. L am linken und R am rechten Joy-Con gleichzeitig drücken verbindet sie wieder. Die Wahl wird je Joy-Con gemerkt."] =
            "Держите Joy-Con горизонтально и нажмите SL или SR, чтобы отсоединить его от пары. Одновременное нажатие L на левом и R на правом снова объединяет их. Выбор запоминается для каждого Joy-Con.",
        ["Joy-Con 2 als Maus"] = "Joy-Con 2 как мышь",
        ["Als Maus, wenn er auf dem Tisch liegt"] = "Как мышь, когда лежит на столе",
        ["Joy-Con 2 auf die Seite legen und wie eine Maus schieben."] = "Положите Joy-Con 2 на бок и двигайте как мышь.",
        ["Mausgeschwindigkeit"] = "Скорость мыши",
        ["Tasten im Mausmodus"] = "Кнопки в режиме мыши",
        ["R/L = Linksklick, ZR/ZL = Rechtsklick, Stick drücken = Mittelklick, Stick hoch/runter = Scrollen."] =
            "R/L = левая кнопка, ZR/ZL = правая кнопка, нажатие стика = средняя кнопка, стик вверх/вниз = прокрутка.",
        ["Zeiger steuert die Maus"] = "Указатель управляет мышью",
        ["Wii-Fernbedienung auf die Sensorleiste richten, um den Mauszeiger zu bewegen."] = "Направьте пульт Wii на сенсорную планку, чтобы двигать указатель.",
        ["Wie Spiele die Controller sehen, Verbindung, Darstellung und Programm."] = "Как игры видят контроллеры, подключение, оформление и программа.",
        ["Ausgabe"] = "Вывод",
        ["Controller erscheint als"] = "Контроллер отображается как",
        ["Xbox 360 läuft mit fast allen Spielen. DualShock 4 bietet Bewegungssteuerung (Steam, Emulatoren)."] =
            "Xbox 360 работает почти со всеми играми. DualShock 4 предлагает управление движением (Steam, эмуляторы).",
        ["Xbox 360 läuft mit fast allen Spielen und Steam. DualShock 4 bietet zusätzlich Bewegungssteuerung (Steam, Emulatoren). Gilt für alle Controller ohne eigene Einstellung (Karte → Einstellungen → Tasten)."] =
            "Xbox 360 работает почти со всеми играми и Steam. DualShock 4 добавляет управление движением (Steam, эмуляторы). Действует для всех контроллеров без собственной настройки (карточка → Настройки → Кнопки).",
        ["Original-Controller verstecken"] = "Скрыть оригинальные контроллеры",
        ["Controller verbinden"] = "Подключить контроллеры",
        ["SYNC-Taste am Controller drücken – N-Connect findet und koppelt ihn selbst. Danach reicht künftig ein Tastendruck."] =
            "Нажмите кнопку SYNC на контроллере – N-Connect найдёт и сопряжёт его сам. Далее достаточно одного нажатия.",
        ["So kommt der Controller in den Kopplungsmodus"] = "Как перевести контроллер в режим сопряжения",
        ["Kurz die kleine SYNC-Taste drücken."] = "Кратко нажмите маленькую кнопку SYNC.",
        ["SYNC-Taste drücken, bis die Lichter laufen."] = "Нажмите кнопку SYNC, пока огни не побегут.",
        ["Batteriefach öffnen und die rote SYNC-Taste drücken."] = "Откройте отсек батарей и нажмите красную кнопку SYNC.",
        ["Die SYNC-Taste auf der Unterseite drücken."] = "Нажмите кнопку SYNC на нижней стороне.",
        ["PS + Teilen bzw. Create halten, bis die Lichtleiste schnell blinkt."] =
            "Удерживайте PS + Share/Create, пока световая полоса не начнёт быстро мигать.",
        ["Kopplungstaste oben halten, bis die Xbox-Taste blinkt."] = "Удерживайте кнопку сопряжения сверху, пока кнопка Xbox не замигает.",
        ["Status"] = "Статус",
        ["Suche läuft …"] = "Идёт поиск …",
        ["Suche läuft – jetzt SYNC drücken …"] = "Идёт поиск – нажмите SYNC сейчас …",
        ["Weitere Controller? Einfach SYNC drücken."] = "Ещё контроллеры? Просто нажмите SYNC.",
        ["Wartet auf einen Controller im Kopplungsmodus."] = "Ожидание контроллера в режиме сопряжения.",
        ["Suche beendet"] = "Поиск завершён",
        ["Die Controller stehen in der Übersicht und verbinden sich künftig per Tastendruck."] =
            "Контроллеры в обзоре и будут подключаться одним нажатием.",
        ["Kein Controller im Kopplungsmodus gefunden. SYNC-Taste drücken und „Erneut suchen“ klicken."] =
            "Контроллер в режиме сопряжения не найден. Нажмите SYNC и выберите «Искать снова».",
        ["Verbunden"] = "Подключено",
        ["Erneut suchen"] = "Искать снова",
        ["Fertig"] = "Готово",
        ["Im Spiel"] = "В игре",
        ["Dreht …"] = "Вращение …",
        ["Testdrehung (360°)"] = "Тестовый поворот (360°)",
        ["Testdrehung"] = "Тестовый поворот",
        ["aus"] = "выкл.",
        ["Gyro-Beschleunigung"] = "Ускорение гироскопа",
        ["Bei schneller Drehung"] = "При быстром повороте",
        ["Langsame Bewegungen bleiben fein, schnelle drehen weiter (wie JoyShockMapper). Voll ab 120 °/s, unter 20 °/s normal. Gilt für Gyro-Stick und Gyro-Maus."] =
            "Медленные движения остаются точными, быстрые поворачивают дальше (как JoyShockMapper). Полное от 120 °/с, обычное ниже 20 °/с. Действует для гиростика и гиромыши.",
        ["Flick-Stick (Spiele mit Maussteuerung)"] = "Flick-стик (игры с управлением мышью)",
        ["Flick-Stick"] = "Flick-стик",
        ["Rechten Stick in eine Richtung schieben = Kamera dreht sofort dorthin; am Rand drehen = Kamera dreht mit. Zielen dann per Gyro. Der rechte Stick geht nicht mehr ans Spiel."] =
            "Отклонить правый стик в направлении = камера мгновенно поворачивается туда; вращать по краю = камера следует. Затем прицеливаться гироскопом. Правый стик больше не передаётся игре.",
        ["Mausbewegung je Umdrehung"] = "Движение мыши за оборот",
        ["Je Spiel einmal einstellen: „Testdrehung“ klicken, ins Spiel wechseln – nach 3 s dreht die Kamera einmal. Genau eine volle Drehung = richtig."] =
            "Настраивается один раз для каждой игры: нажмите «Тестовый поворот», переключитесь в игру – через 3 с камера повернётся один раз. Ровно один полный оборот = правильно.",
        ["Flick-Dauer"] = "Длительность flick",
        ["So lange dauert die Drehung beim Flick (0 = sofort)."] = "Как долго длится поворот при flick (0 = мгновенно).",
        ["Gyro-Maus oder Gyro-Stick ein/aus bzw. solange gehalten, „Gyro anhalten“ (Ratchet: Controller zurückführen, ohne dass sich das Ziel bewegt)"] =
            "Гиромышь или гиростик вкл./выкл. или пока удерживается, «приостановить гироскоп» (ratchet: вернуть контроллер, не двигая прицел)",
        ["✋  Gyro anhalten (solange gehalten, „Ratchet“)"] = "✋  Приостановить гироскоп (пока удерживается, «ratchet»)",
        ["Spieler-LED und Lichtleiste vom Spiel"] = "LED игрока и световая полоса от игры",
        ["Die Spieler-LEDs zeigen den Xbox-Platz, den Windows vergibt. Bei DualShock 4 steuert die Lichtleiste des Spiels die HOME-LED (Switch 1 Pro Controller, rechter Joy-Con)."] =
            "LED игрока показывают место Xbox, назначенное Windows. У DualShock 4 световая полоса игры управляет LED HOME (Pro Controller Switch 1, правый Joy-Con).",
        ["HidHide installieren …"] = "Установить HidHide …",
        ["Empfohlen: Steam und viele Spiele kennen Switch-1-, NSO- und USB-Controller selbst und sähen sie sonst doppelt. Läuft nach der Installation ohne Rückfrage (sonst fragt Windows nach Adminrechten)."] =
            "Рекомендуется: Steam и многие игры сами распознают контроллеры Switch 1, NSO и USB и видели бы их дважды. После установки работает без запросов (иначе Windows запрашивает права администратора).",
        ["Steam und viele Spiele sehen Switch-1-, NSO- und USB-Controller sonst doppelt. Dafür wird das kostenlose HidHide gebraucht (bei der N-Connect-Installation dabei, hier nachträglich)."] =
            "Иначе Steam и многие игры видят контроллеры Switch 1, NSO и USB дважды. Для этого нужен бесплатный HidHide (входит в установку N-Connect, устанавливается здесь позже).",
        ["Erscheint als"] = "Отображается как",
        ["Wie allgemein"] = "Как в Общие",
        ["Nur für diesen Controller. Xbox 360 läuft überall; DualShock 4 bringt zusätzlich Gyro nach Steam und in Emulatoren. „Wie allgemein“ folgt der Seite „Allgemein“."] =
            "Только для этого контроллера. Xbox 360 работает везде; DualShock 4 добавляет гироскоп в Steam и эмуляторы. «Как в Общие» следует странице «Общие».",
        ["Der echte Xbox-Controller – Spiele sehen ihn von Windows aus direkt. Belegungen hier wirken auf Sonderaktionen (Tastatur, Makros, Gyro), nicht auf den Controller selbst."] =
            "Настоящий контроллер Xbox – игры видят его напрямую из Windows. Назначения здесь действуют на особые действия (клавиатура, макросы, гироскоп), а не на сам контроллер.",
        ["Steam und manche Spiele sehen diesen Controller sonst doppelt. Abhilfe: HidHide installieren (Seite „Allgemein“ → „Original-Controller verstecken“)."] =
            "Иначе Steam и некоторые игры видят этот контроллер дважды. Решение: установите HidHide (страница «Общие» → «Скрыть оригинальные контроллеры»).",
        ["Original-Controller vor Spielen versteckt. Steam bitte einmal neu starten – danach sieht es nur noch den virtuellen Controller."] =
            "Оригинальные контроллеры скрыты от игр. Перезапустите Steam один раз – далее он видит только виртуальный контроллер.",
        ["Original-Controller vor Spielen versteckt – Steam und Spiele sehen nur noch den virtuellen Controller."] =
            "Оригинальные контроллеры скрыты от игр – Steam и игры теперь видят только виртуальный контроллер.",
        ["Original-Controller nicht versteckt (Abfrage abgebrochen). Nachholen: Controller → Einstellungen → Extras → „Doppelt angezeigt?“."] =
            "Оригинальные контроллеры не скрыты (запрос отменён). Позже: контроллер → Настройки → Дополнительно → «Отображается дважды?».",
        ["Tastenanordnung A/B/X/Y"] = "Раскладка кнопок A/B/X/Y",
        ["Xbox: nach Position (untere Taste = A). Nintendo: nach Beschriftung (A bleibt A)."] = "Xbox: по положению (нижняя кнопка = A). Nintendo: по надписи (A остаётся A).",
        ["Verbinden"] = "Подключение",
        ["Per Tastendruck verbinden"] = "Подключать одним нажатием",
        ["Gekoppelte Controller verbinden sich ohne SYNC-Taste."] = "Сопряжённые контроллеры подключаются без кнопки SYNC.",
        ["Ohne Eingabe trennen nach"] = "Отключать без действий через",
        ["Spart Akku, wenn ein Controller liegen bleibt."] = "Экономит батарею, когда контроллер лежит без дела.",
        ["N-Connect startet unsichtbar im Infobereich."] = "N-Connect запускается незаметно в области уведомлений.",
        ["Darstellung und Sprache"] = "Оформление и язык",
        ["Farbmodus"] = "Цветовой режим",
        ["Mica-Effekt"] = "Эффект Mica",
        ["Durchscheinende Titelleiste (ab Windows 11)."] = "Полупрозрачная строка заголовка (начиная с Windows 11).",
        ["Erweitert"] = "Дополнительно",
        ["Gyro für Emulatoren (DSU)"] = "Гироскоп для эмуляторов (DSU)",
        ["Cemuhook-Server auf Port 26760 – wirkt nach einem Neustart von N-Connect."] = "Сервер Cemuhook на порту 26760 – действует после перезапуска N-Connect.",
        ["Nach Updates suchen"] = "Искать обновления",
        ["Beim Start auf GitHub nach einer neuen Version suchen."] = "Искать новую версию на GitHub при запуске.",
        ["Tastenbelegungen und Werte zurücksetzen. Gekoppelte Controller bleiben erhalten."] = "Сбросить назначения кнопок и значения. Сопряжённые контроллеры сохраняются.",
        ["Zurücksetzen"] = "Сбросить",

        // ---------- Controller-Karte ----------
        ["Einstellungen"] = "Настройки",
        ["Tastenbelegung und Einstellungen nur für diesen Controller"] = "Назначение кнопок и настройки только для этого контроллера",
        ["Feineinstellung"] = "Точная настройка",
        ["Gyro"] = "Гироскоп",
        ["Extras"] = "Дополнительно",
        ["Belegung für alle Spiele (Standard) oder ein eigenes Profil."] = "Назначение для всех игр (по умолчанию) или собственный профиль.",
        ["Profile"] = "Профили",
        ["Profile anlegen, umbenennen, exportieren …"] = "Создавать, переименовывать, экспортировать профили …",
        ["Drück eine Taste am Controller – ihre Zeile leuchtet auf. ⌨ weist eine Tastaturtaste zu, ↺ setzt zurück."] =
            "Нажмите кнопку на контроллере – её строка подсветится. ⌨ назначает клавишу клавиатуры, ↺ сбрасывает.",
        ["Tastatur-Taste zuweisen: klicken und die gewünschte Taste oder Kombination drücken."] = "Назначить клавишу: нажмите и нажмите нужную клавишу или сочетание.",
        ["Zurück auf die Standardbelegung"] = "Вернуться к назначению по умолчанию",
        ["Ohne eigenen Wert gilt der allgemeine Wert der Seite „Sticks & Vibration“."] = "Без собственного значения действует общее со страницы «Стики и вибрация».",
        ["Stick-Totzone"] = "Мёртвая зона стика",
        ["Stick-Kennlinie"] = "Характеристика стика",
        ["Trigger-Totzone"] = "Мёртвая зона триггера",
        ["Trigger voll gedrückt ab"] = "Триггер полностью нажат с",
        ["Vibrationsstärke"] = "Сила вибрации",
        ["Gyro-Maus-Geschwindigkeit"] = "Скорость гиромыши",
        ["Eigenen Wert entfernen – es gilt wieder der allgemeine Wert"] = "Удалить собственное значение – снова действует общее",
        ["Kalibrieren"] = "Калибровать",
        ["Controller ruhig auf den Tisch legen und klicken: misst den Nullpunkt neu (gegen Abdriften)."] =
            "Положите контроллер на стол и нажмите: заново измеряет нулевую точку (против дрейфа).",
        ["Gyro als rechter Stick und Mausrichtung"] = "Гироскоп как правый стик и направление мыши",
        ["Gilt für alle Controller"] = "Действует для всех контроллеров",
        ["Paar"] = "Пара",
        ["Joy-Con quer halten und SL oder SR drücken löst das Paar, L + R gleichzeitig verbindet es."] =
            "Держите Joy-Con горизонтально и нажмите SL или SR, чтобы разъединить пару; L + R одновременно объединяет её.",
        ["Haltung"] = "Положение",
        ["Quer"] = "Горизонтально",
        ["Hochkant"] = "Вертикально",
        ["Quer wie an der Switch oder hochkant – hochkant gilt die Belegung von „Joy-Con-Paar“."] =
            "Горизонтально как на Switch или вертикально – вертикально действует назначение «пара Joy-Con».",
        ["Mausmodus, Geschwindigkeit und Tasten"] = "Режим мыши, скорость и кнопки",
        ["Lesen …"] = "Считать …",
        ["Einschalten"] = "Включить",
        ["Ausschalten"] = "Выключить",
        ["Wird gesucht …"] = "Поиск …",
        ["Öffnen"] = "Открыть",
        ["Verstecken"] = "Скрыть",
        ["amiibo an den NFC-Leser halten und als Datei (.bin) speichern – z. B. für Emulatoren."] =
            "Приложите amiibo к NFC-считывателю и сохраните как файл (.bin) – например, для эмуляторов.",
        ["Zusammendrücken = rechter Trigger, auseinanderziehen = linker Trigger. Beim Einschalten nicht berühren."] =
            "Сжатие = правый триггер, растяжение = левый триггер. Не касайтесь при включении.",
        ["Live-Bild der Infrarotkamera im rechten Joy-Con."] = "Живое изображение инфракрасной камеры правого Joy-Con.",
        ["Doppelt angezeigt?"] = "Отображается дважды?",
        ["Versteckt den Original-Controller vor Steam und Spielen (HidHide) – sie sehen dann nur den virtuellen Controller."] =
            "Скрывает оригинальный контроллер от Steam и игр (HidHide) – они видят только виртуальный контроллер.",
        ["bereit (auf den Tisch legen)"] = "готово (положите на стол)",
        ["amiibo-Abbild (*.bin)|*.bin"] = "Образ amiibo (*.bin)|*.bin",
        ["Controller-Profil (*.ncprofile.json)|*.ncprofile.json|JSON (*.json)|*.json"] = "Профиль контроллера (*.ncprofile.json)|*.ncprofile.json|JSON (*.json)|*.json",
        ["Programme (*.exe)|*.exe"] = "Программы (*.exe)|*.exe",
        ["Kein Controller verbunden\n\n" +
         "Switch-2-Controller: kurz die SYNC-Taste drücken – danach reicht ein beliebiger Tastendruck.\n" +
         "Switch-1-, NSO- und Wii-Controller: SYNC-Taste drücken – N-Connect koppelt sie selbst.\n" +
         "Oder hier gezielt suchen und koppeln:"] =
            "Контроллер не подключён\n\n" +
            "Контроллеры Switch 2: кратко нажмите кнопку SYNC – затем достаточно любого нажатия.\n" +
            "Контроллеры Switch 1, NSO и Wii: нажмите кнопку SYNC – N-Connect сопрягает их сам.\n" +
            "Или ищите и сопрягайте прямо здесь:",
        ["Controller suchen …"] = "Найти контроллеры …",
        ["Switch-1-, NSO- und Wii-Controller suchen und koppeln (SYNC-Taste drücken)."] =
            "Найти и сопрячь контроллеры Switch 1, NSO и Wii (нажмите кнопку SYNC).",
        ["Neue Controller automatisch koppeln"] = "Автоматически сопрягать новые контроллеры",
        ["Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive, Wii und PlayStation: einfach SYNC " +
         "drücken – kein Umweg über die Windows-Bluetooth-Einstellungen. Gesucht wird nur, solange niemand spielt."] =
            "Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive, Wii и PlayStation: просто нажмите SYNC – " +
            "без обхода через настройки Bluetooth Windows. Поиск ведётся только пока никто не играет.",
        ["Gezielt suchen"] = "Целенаправленный поиск",
        ["Sucht eine Minute lang nach Controllern im Kopplungsmodus."] = "Ищет контроллеры в режиме сопряжения в течение минуты.",
        ["Controller koppeln …"] = "Сопрячь контроллер …",
        ["Controller koppeln"] = "Сопрячь контроллер",
        ["Linken Joy-Con umbenennen …"] = "Переименовать левый Joy-Con …",
        ["Rechten Joy-Con umbenennen …"] = "Переименовать правый Joy-Con …",
        ["Controller umbenennen"] = "Переименовать контроллер",
        ["Spielerplatz"] = "Место игрока",
        ["N-Connect aktualisieren"] = "Обновить N-Connect",
        ["HidHide aktualisieren"] = "Обновить HidHide",
        ["HidHide-Update verfügbar"] = "Доступно обновление HidHide",
        ["HidHide aktuell halten"] = "Поддерживать HidHide актуальным",
        ["Beim Start nach einer neuen HidHide-Version suchen. Installiert wird nur nach Rückfrage (geprüfter Download vom Hersteller, Neustart nötig)."] =
            "Искать новую версию HidHide при запуске. Установка только после подтверждения (проверенная загрузка от производителя, требуется перезагрузка).",
        ["Der Download hat nicht geklappt oder die Datei war fehlerhaft. Die Release-Seite im Browser öffnen?"] =
            "Загрузка не удалась или файл был повреждён. Открыть страницу выпуска в браузере?",
        ["Alle Controller trennen"] = "Отключить все контроллеры",
        ["Sticks kalibrieren"] = "Калибровать стики",
        ["Kalibrieren …"] = "Калибровать …",
        ["Gegen Drift oder zu kleinen Ausschlag: Mitte und Rand neu messen. Wird nur in N-Connect gespeichert, der Controller bleibt unverändert."] =
            "Против дрейфа или слишком малого хода: измерить заново центр и край. Сохраняется только в N-Connect, контроллер не изменяется.",
        ["Linker Stick"] = "Левый стик",
        ["Rechter Stick"] = "Правый стик",
        ["Stick"] = "Стик",
        ["Stick (linker Joy-Con)"] = "Стик (левый Joy-Con)",
        ["Stick (rechter Joy-Con)"] = "Стик (правый Joy-Con)",
        ["Neu messen"] = "Измерить заново",
        ["Werkswerte"] = "Заводские значения",
        ["Der Punkt zeigt, wo der Stick gerade steht. Steht er losgelassen nicht in der Mitte oder erreicht er den Kreis nicht, auf „Neu messen“ klicken."] =
            "Точка показывает, где находится стик. Если отпущенный он не в центре или не достигает круга, нажмите «Измерить заново».",
        ["Gilt gerade: eigene Kalibrierung."] = "Сейчас используется: собственная калибровка.",
        ["Gilt gerade: Werkswerte des Controllers."] = "Сейчас используются: заводские значения контроллера.",
        ["1/2 – Stick loslassen und den Controller ruhig halten …"] = "1/2 – отпустите стик и держите контроллер неподвижно …",
        ["2/2 – Stick bis zum Anschlag drücken und langsam ein- bis zweimal im Kreis drehen."] =
            "2/2 – нажмите стик до упора и медленно вращайте по кругу один-два раза.",
        ["Fertig. „Übernehmen“ speichert die neue Kalibrierung für diesen Controller."] = "Готово. «Применить» сохраняет новую калибровку для этого контроллера.",
        ["Der Stick hat den Rand nicht erreicht. Bitte bis zum Anschlag drücken und erneut messen."] =
            "Стик не достиг края. Нажмите его до упора и измерьте заново.",
        ["Übernommen ✓ – gilt ab sofort."] = "Применено ✓ – действует сразу.",
        ["Werkswerte des Controllers gelten wieder."] = "Снова действуют заводские значения контроллера.",
        ["Gyro einrichten"] = "Настроить гироскоп",
        ["Einrichten …"] = "Настроить …",
        ["Zielen per Bewegung einrichten"] = "Настроить прицеливание движением",
        ["Schritt für Schritt: Nullpunkt, wann der Gyro zielt, Empfindlichkeit – mit Vorschau."] =
            "Шаг за шагом: нулевая точка, когда гироскоп прицеливается, чувствительность – с предпросмотром.",
        ["1  Nullpunkt"] = "1  Нулевая точка",
        ["Controller flach auf den Tisch legen, nicht berühren – verhindert, dass das Ziel von selbst wandert."] =
            "Положите контроллер плоско на стол, не касаясь – предотвращает самопроизвольный дрейф прицела.",
        ["Nullpunkt messen"] = "Измерить нулевую точку",
        ["Der Controller hat sich bewegt – bitte flach hinlegen und erneut versuchen."] = "Контроллер двигался – положите его плоско и повторите.",
        ["Nullpunkt gemessen ✓"] = "Нулевая точка измерена ✓",
        ["2  Wann zielt der Gyro?"] = "2  Когда гироскоп прицеливается?",
        ["Nur per Taste"] = "Только кнопкой",
        ["Beim Zielen (ZL/LT)"] = "При прицеливании (ZL/LT)",
        ["„Beim Zielen“: nur solange ZL (linker Trigger) gehalten wird – wie in vielen Shootern."] =
            "«При прицеливании»: только пока удерживается ZL (левый триггер) – как во многих шутерах.",
        ["3  Empfindlichkeit"] = "3  Чувствительность",
        ["Voller Ausschlag ab"] = "Полное отклонение с",
        ["Kleinerer Wert bei „Voller Ausschlag ab“ = empfindlicher. „Mindestausschlag“ überwindet die Totzone des Spiels."] =
            "Меньшее значение у «Полное отклонение с» = чувствительнее. «Минимальное отклонение» преодолевает мёртвую зону игры.",
        ["Mitte"] = "Центр",
        ["Vorschau: Fadenkreuz folgt dem Controller (unabhängig von Schritt 2)."] = "Предпросмотр: прицел следует за контроллером (независимо от шага 2).",
        ["Keine Bewegungsdaten"] = "Нет данных о движении",
        ["Controller gekoppelt"] = "Контроллер сопряжён",
        ["Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive: SYNC-Taste drücken, bis die Lichter laufen.\n" +
         "Wii-Fernbedienung: Batteriefach öffnen und die rote SYNC-Taste drücken.\n" +
         "Wii U Pro Controller: die SYNC-Taste auf der Unterseite drücken.\n" +
         "Danach verbindet sich der Controller künftig per Tastendruck."] =
            "Joy-Con, Pro Controller, NES/SNES/N64/Mega Drive: нажмите кнопку SYNC, пока огни не побегут.\n" +
            "Пульт Wii: откройте отсек батарей и нажмите красную кнопку SYNC.\n" +
            "Wii U Pro Controller: нажмите кнопку SYNC на нижней стороне.\n" +
            "Затем контроллер подключается одним нажатием.",
        ["Suche … SYNC-Taste drücken (Xbox: Kopplungstaste oben halten, PlayStation: PS + Teilen/Create halten)."] =
            "Поиск … нажмите кнопку SYNC (Xbox: удерживайте кнопку сопряжения сверху; PlayStation: удерживайте PS + Share/Create).",
        ["Kein Controller im Kopplungsmodus gefunden. SYNC-Taste drücken und erneut versuchen."] =
            "Контроллер в режиме сопряжения не найден. Нажмите SYNC и повторите.",
        ["Darstellung:"] = "Оформление:",
        ["Dunkel"] = "Тёмная",
        ["Hell"] = "Светлая",
        ["Wie Windows"] = "Как в Windows",
        ["Mica-Effekt in der Titelleiste (ab Windows 11)"] = "Эффект Mica в строке заголовка (начиная с Windows 11)",

        // ---------- Fehlerfälle und Hinweise ----------
        ["Bluetooth ist ausgeschaltet."] = "Bluetooth выключен.",
        ["Dieser Bluetooth-Adapter unterstützt kein Bluetooth LE."] = "Этот Bluetooth-адаптер не поддерживает Bluetooth LE.",
        ["Bluetooth-Suche konnte nicht starten."] = "Не удалось начать поиск Bluetooth.",
        ["Bluetooth in den Windows-Einstellungen einschalten."] = "Включите Bluetooth в настройках Windows.",
        ["Controller per USB funktionieren weiterhin."] = "Контроллеры по USB продолжают работать.",
        ["Für Switch-2-Controller wird ein Adapter mit Bluetooth 4.0 oder neuer gebraucht."] = "Для контроллеров Switch 2 нужен адаптер с Bluetooth 4.0 или новее.",
        ["Andere Controller und USB funktionieren weiterhin."] = "Другие контроллеры и USB продолжают работать.",
        ["Bluetooth-Adapter (z. B. USB-Stick) einstecken bzw. Bluetooth in Windows aktivieren."] =
            "Подключите Bluetooth-адаптер (например, USB-брелок) или включите Bluetooth в Windows.",
        ["Bluetooth ist bereit – Controller können verbunden werden."] = "Bluetooth готов – можно подключать контроллеры.",
        ["Bluetooth-Einstellungen öffnen"] = "Открыть настройки Bluetooth",
        ["ViGEmBus-Treiber fehlt – ohne ihn kann kein virtueller Controller erzeugt werden."] =
            "Драйвер ViGEmBus отсутствует – без него нельзя создать виртуальный контроллер.",
        ["Bitte das Setup erneut ausführen."] = "Запустите установку заново.",
        ["Das Programm schließen oder in Steam die Nintendo-Unterstützung abschalten."] =
            "Закройте эту программу или отключите поддержку Nintendo в Steam.",
        ["Erst einen anderen trennen."] = "Сначала отключите другой.",
        ["Tipp: Bluetooth-Stick per Verlängerung näher an den Controller, weg von USB-3-Anschlüssen und Funkkopfhörern."] =
            "Совет: приблизьте Bluetooth-брелок к контроллеру удлинителем, подальше от портов USB 3 и беспроводных наушников.",
        ["Controller mit dem PC gekoppelt – ab jetzt reicht ein Tastendruck."] = "Контроллер сопряжён с ПК – теперь достаточно одного нажатия.",
        ["Hinweis: Um ihn wieder an der Switch 2 zu nutzen, dort einmal kurz SYNC drücken."] =
            "Примечание: чтобы снова использовать его на Switch 2, нажмите там один раз кратко SYNC.",
        ["Dieser Bluetooth-Adapter unterstützt kein Bluetooth LE"] = "Этот Bluetooth-адаптер не поддерживает Bluetooth LE",
        ["Erst IR-Kamera bzw. Ring-Con ausschalten (sie nutzen denselben Zusatzprozessor wie der NFC-Leser)."] =
            "Сначала выключите ИК-камеру или Ring-Con (они используют тот же сопроцессор, что и NFC-считыватель).",
        ["Erst die IR-Kamera schließen (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "Сначала закройте ИК-камеру (Ring-Con и ИК-камера используют один сопроцессор).",
        ["Erst den Ring-Con ausschalten (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "Сначала выключите Ring-Con (Ring-Con и ИК-камера используют один сопроцессор).",
        ["amiibo zu früh entfernt"] = "amiibo убран слишком рано",
        ["MCU startet nicht"] = "сопроцессор не запускается",
        ["NFC-Modus nicht aktiv"] = "режим NFC неактивен",
        ["Kopplung fehlgeschlagen – Details im Protokoll."] = "Сопряжение не удалось – подробности в журнале.",

        // ---------- Kopplungsdaten (Switch-SD-Karte, anderer PC) ----------
        ["Kopplungsdaten"] = "Данные сопряжения",
        ["Kopplungen übernehmen oder weitergeben"] = "Перенести или передать сопряжения",
        ["Kopplungsdaten von der Switch übernehmen"] = "Перенести данные сопряжения со Switch",
        ["Von der Switch-SD-Karte (Bluepick_RCM/hekate) oder von einem anderen PC übernehmen, oder für einen anderen PC exportieren."] =
            "Перенести с SD-карты Switch (Bluepick_RCM/hekate) или с другого ПК, либо экспортировать для другого ПК.",
        ["Bei Switch-SD-Karte nachfragen"] = "Спрашивать при SD-карте Switch",
        ["Steckt eine SD-Karte der Switch im PC (Kartenleser oder hekate „USB Tools“), bietet N-Connect die Übernahme an. Die Karte wird nur gelesen."] =
            "Если SD-карта Switch находится в ПК (картридер или hekate «USB Tools»), N-Connect предлагает перенос. Карта только читается.",
        ["Switch-SD-Karte erkannt"] = "Обнаружена SD-карта Switch",
        ["Kopplungsdaten der Controller gefunden – klicken, um sie anzusehen und zu übernehmen."] =
            "Найдены данные сопряжения контроллеров – нажмите, чтобы просмотреть и перенести.",
        ["Klicken, um Kopplungsdaten der Controller zu übernehmen."] = "Нажмите, чтобы перенести данные сопряжения контроллеров.",
        ["Controller-Kopplungen von der Switch-SD-Karte oder von einem anderen PC übernehmen – oder für einen anderen PC exportieren. Es werden nur Einstellungen von N-Connect geändert; Windows und der Bluetooth-Adapter bleiben unverändert."] =
            "Переносите сопряжения контроллеров с SD-карты Switch или с другого ПК – или экспортируйте их для другого ПК. Изменяются только настройки N-Connect; Windows и Bluetooth-адаптер остаются без изменений.",
        ["Spieler-Reihenfolge – Spieler 1 ist für Windows, Steam und Spiele der erste Controller. Mit ‹ › umsortieren."] =
            "Порядок игроков – игрок 1 является первым контроллером для Windows, Steam и игр. Меняйте порядок с помощью ‹ ›.",
        ["Von der Switch-SD-Karte"] = "С SD-карты Switch",
        ["Mit Bluepick_RCM oder hekate erstellte Kopplungsdaten (switchroot/joycon_mac.ini)"] =
            "Данные сопряжения, созданные Bluepick_RCM или hekate (switchroot/joycon_mac.ini)",
        ["Einlesen …"] = "Считать …",
        ["Von einem anderen PC"] = "С другого ПК",
        ["Mit N-Connect exportierte Datei (*.ncpair)"] = "Файл, экспортированный N-Connect (*.ncpair)",
        ["Datei öffnen …"] = "Открыть файл …",
        ["Inhalt"] = "Содержимое",
        ["Weitergeben und sichern"] = "Передать и защитить",
        ["Für einen anderen PC exportieren"] = "Экспортировать для другого ПК",
        ["Bekannte Controller und Einstellungen je Controller, optional mit Passwort"] =
            "Известные контроллеры и настройки для контроллера, при желании с паролем",
        ["Sicherung wiederherstellen"] = "Восстановить резервную копию",
        ["Vor jedem „Übernehmen“ wird automatisch eine Sicherung angelegt"] = "Перед каждым «Применить» автоматически создаётся резервная копия",
        ["Wiederherstellen …"] = "Восстановить …",
        ["Bluetooth-Adapter dieses PCs"] = "Bluetooth-адаптер этого ПК",
        ["wird ermittelt …"] = "определяется …",
        ["nicht gefunden"] = "не найден",
        ["Quelle wählen: Switch-SD-Karte (mit Bluepick_RCM oder hekate erstellte Kopplungsdaten) oder eine Datei von einem anderen PC."] =
            "Выберите источник: SD-карта Switch (данные сопряжения, созданные Bluepick_RCM или hekate) или файл с другого ПК.",
        ["Keine Switch-SD-Karte gefunden. SD-Karte in den Kartenleser stecken oder die Switch per hekate („USB Tools“ → „SD Card“) als Laufwerk verbinden.\n\nOrdner selbst auswählen?"] =
            "SD-карта Switch не найдена. Вставьте SD-карту в картридер или подключите Switch как диск через hekate («USB Tools» → «SD Card»).\n\nВыбрать папку вручную?",
        ["Stammordner der Switch-SD-Karte wählen"] = "Выберите корневую папку SD-карты Switch",
        ["Switch-SD-Karte:"] = "SD-карта Switch:",
        ["Auf der Karte liegen keine Kopplungsdaten (switchroot/joycon_mac.ini)."] = "На карте нет данных сопряжения (switchroot/joycon_mac.ini).",
        ["So erstellst du sie: Joy-Con an die Switch stecken, Bluepick_RCM starten und „Dump Joy-Con BT pairing → SD“ (oder FULL AUTO) wählen. Alternativ in hekate: Nyx → Konsole → „Dump Joy-Con BT“."] =
            "Чтобы их создать: подключите Joy-Con к Switch, запустите Bluepick_RCM и выберите «Dump Joy-Con BT pairing → SD» (или FULL AUTO). Либо в hekate: Nyx → Console → «Dump Joy-Con BT».",
        ["Gefunden wurde eine Bluepick-Sicherung des Bluetooth-Speichers (8000000000000050.bin). Sie ist ein Switch-Speicherabbild und kann hier nicht ausgewertet werden."] =
            "Найдена резервная копия Bluepick памяти Bluetooth (8000000000000050.bin). Это образ памяти Switch, и здесь он не может быть прочитан.",
        ["Bluetooth-Adresse der Switch:"] = "Bluetooth-адрес Switch:",
        ["Gefundene Controller:"] = "Найденные контроллеры:",
        ["mit der Switch gekoppelt"] = "сопряжён со Switch",
        ["zuletzt mit einem anderen Gerät gekoppelt (nicht der Switch)"] = "последний раз сопряжён с другим устройством (не со Switch)",
        ["Joy-Con (L)"] = "Joy-Con (Л)",
        ["Joy-Con (R)"] = "Joy-Con (П)",
        ["HORI-Controller (links)"] = "Контроллер HORI (левый)",
        ["HORI-Controller (rechts)"] = "Контроллер HORI (правый)",
        ["Hinweis: Pro Controller stehen nur im Bluetooth-Speicher der Switch (8000000000000050.bin); dieses Speicherabbild kann N-Connect nicht auswerten."] =
            "Примечание: Pro Controller указаны только в памяти Bluetooth Switch (8000000000000050.bin); N-Connect не может прочитать этот образ памяти.",
        ["Was diese Daten können – und was nicht:"] = "Что позволяют эти данные – а что нет:",
        ["Die Daten zeigen, welche Controller mit deiner Switch gekoppelt sind und an welche Bluetooth-Adresse sie gebunden sind."] =
            "Данные показывают, какие контроллеры сопряжены с вашей Switch и к какому Bluetooth-адресу они привязаны.",
        ["Ein Switch-1-Controller verbindet sich auf Tastendruck nur mit dem Gerät, dessen Adresse er gespeichert hat – hier mit der Switch. Der Bluetooth-Adapter des PCs hat eine andere Adresse, deshalb kann Windows diese Kopplung nicht einfach weiterverwenden."] =
            "Контроллер Switch 1 подключается одним нажатием только к устройству, чей адрес он запомнил – здесь к Switch. Bluetooth-адаптер ПК имеет другой адрес, поэтому Windows не может просто переиспользовать это сопряжение.",
        ["Die Adresse des PC-Adapters zu ändern, unterstützt N-Connect bewusst nicht (herstellerabhängig, riskant und nicht vorgesehen)."] =
            "N-Connect сознательно не поддерживает изменение адреса адаптера ПК (зависит от производителя, рискованно и не предусмотрено).",
        ["Windows bietet keinen offiziellen Weg, fremde Kopplungsschlüssel einzutragen: Sie liegen in einem Teil der Registrierung, auf den nur das System zugreifen darf. N-Connect ändert dort nichts."] =
            "Windows не предлагает официального способа добавления чужих ключей сопряжения: они находятся в части реестра, доступной только системе. N-Connect там ничего не меняет.",
        ["So klappt der Wechsel am einfachsten: am PC den Controller einmal per SYNC-Taste in den Windows-Bluetooth-Einstellungen koppeln. Zurück an der Switch die Joy-Con an die Konsole stecken bzw. den Pro Controller per USB-Kabel anschließen – dann sind sie ohne Menü wieder mit der Switch gekoppelt."] =
            "Проще всего переключаться так: на ПК сопрягите контроллер один раз кнопкой SYNC в настройках Bluetooth Windows. Вернувшись к Switch, вставьте Joy-Con в консоль или подключите Pro Controller кабелем USB – они снова будут сопряжены без меню.",
        ["„Übernehmen“ merkt sich diese Controller in N-Connect (Liste bekannter Controller, Zuordnung zur Switch). Kopplungsschlüssel werden nicht gespeichert."] =
            "«Применить» запоминает эти контроллеры в N-Connect (список известных контроллеров, привязка к Switch). Ключи сопряжения не сохраняются.",
        ["N-Connect-Kopplungsdaten"] = "Данные сопряжения N-Connect",
        ["Kopplungsdaten von einem anderen PC öffnen"] = "Открыть данные сопряжения с другого ПК",
        ["Die Datei ist zu groß."] = "Файл слишком большой.",
        ["Keine Kopplungsdaten-Datei."] = "Это не файл данных сопряжения.",
        ["Die Datei stammt von einer neueren N-Connect-Version."] = "Файл создан более новой версией N-Connect.",
        ["Die Datei ist mit einem Passwort geschützt."] = "Файл защищён паролем.",
        ["Falsches Passwort oder die Datei wurde verändert."] = "Неверный пароль или файл был изменён.",
        ["Die Datei ist beschädigt."] = "Файл повреждён.",
        ["Datei von:"] = "Файл от:",
        ["Bluetooth-Adapter dort:"] = "Bluetooth-адаптер там:",
        ["Bluetooth-Adapter hier:"] = "Bluetooth-адаптер здесь:",
        ["gekoppelt mit der Switch"] = "сопряжён со Switch",
        ["gekoppelt mit dem anderen PC"] = "сопряжён с другим ПК",
        ["Weitere Einstellungen je Controller:"] = "Другие настройки для контроллера:",
        ["Was du erwarten kannst:"] = "Чего ожидать:",
        ["Gleiche Adapter-Adresse (z. B. derselbe USB-Bluetooth-Stick umgesteckt): Switch-2-Controller verbinden sich hier auf Tastendruck wie am anderen PC."] =
            "Тот же адрес адаптера (например, тот же USB-брелок Bluetooth переставлен): контроллеры Switch 2 подключаются здесь одним нажатием, как на другом ПК.",
        ["Switch-1-Controller (Pro Controller, Joy-Con) brauchen zusätzlich die Kopplung in Windows. Die kann N-Connect nicht übertragen – einmal per SYNC-Taste koppeln."] =
            "Контроллерам Switch 1 (Pro Controller, Joy-Con) дополнительно нужно сопряжение в Windows. N-Connect не может его передать – сопрягите один раз кнопкой SYNC.",
        ["Anderer Bluetooth-Adapter: Controller verbinden sich auf Tastendruck nur mit dem Gerät, mit dem sie zuletzt gekoppelt wurden. Hier einmal SYNC drücken – danach verbinden sie sich mit diesem PC (am anderen PC dann wieder per SYNC)."] =
            "Другой Bluetooth-адаптер: контроллеры подключаются одним нажатием только к устройству, с которым были сопряжены последний раз. Нажмите SYNC здесь один раз – затем они подключаются к этому ПК (на другом ПК снова через SYNC).",
        ["Tipp: Wer denselben USB-Bluetooth-Stick zwischen den PCs umsteckt, nimmt die Adresse mit – Switch-2-Controller verbinden sich dann an beiden PCs ohne SYNC."] =
            "Совет: кто переставляет один и тот же USB-брелок Bluetooth между ПК, переносит адрес с собой – контроллеры Switch 2 тогда подключаются на обоих ПК без SYNC.",
        ["Übernommen werden die Einstellungen je Controller (Joy-Con einzeln/hochkant, Gyro-Kalibrierung) und die Liste bekannter Controller."] =
            "Переносятся настройки для контроллера (Joy-Con отдельно/вертикально, калибровка гироскопа) и список известных контроллеров.",
        ["Die Datei enthält Kopplungsschlüssel. Windows bietet keinen offiziellen Weg, sie einzutragen – N-Connect übernimmt sie deshalb nicht."] =
            "Файл содержит ключи сопряжения. Windows не предлагает официального способа их добавления – поэтому N-Connect их не переносит.",
        ["„Übernehmen“ ergänzt die Controller-Listen und Einstellungen von N-Connect (nichts wird gelöscht). Vorher wird eine Sicherung angelegt."] =
            "«Применить» дополняет списки контроллеров и настройки N-Connect (ничего не удаляется). Перед этим создаётся резервная копия.",
        ["Kopplungsdaten in N-Connect übernehmen? Vorher wird eine Sicherung der Einstellungen angelegt."] =
            "Перенести данные сопряжения в N-Connect? Перед этим будет создана резервная копия настроек.",
        ["Nichts zu ändern – diese Daten sind schon übernommen."] = "Ничего менять не нужно – эти данные уже перенесены.",
        ["Übernommen. Die Sicherung lässt sich hier über „Sicherung wiederherstellen“ zurückholen."] =
            "Готово. Резервную копию можно восстановить здесь через «Восстановить резервную копию».",
        ["Sicherung der Einstellungen"] = "Резервная копия настроек",
        ["Die Sicherung ist beschädigt und wurde nicht übernommen."] = "Резервная копия повреждена и не была применена.",
        ["Alle Einstellungen durch diese Sicherung ersetzen?"] = "Заменить все настройки этой резервной копией?",
        ["Sicherung wiederhergestellt."] = "Резервная копия восстановлена.",
        ["Kopplungsdaten für einen anderen PC speichern"] = "Сохранить данные сопряжения для другого ПК",
        ["Gespeichert. Die Datei am anderen PC in N-Connect unter „Joy-Con & Wii“ → „Kopplungsdaten“ → „Von einem anderen PC“ öffnen."] =
            "Сохранено. На другом ПК откройте файл в N-Connect в разделе «Joy-Con и Wii» → «Данные сопряжения» → «С другого ПК».",
        ["Kopplungsdaten exportieren"] = "Экспортировать данные сопряжения",
        ["Passwort eingeben"] = "Введите пароль",
        ["Passwort (optional). Ohne Passwort steht der Inhalt lesbar in der Datei. Mit Kopplungsschlüsseln ist ein Passwort Pflicht."] =
            "Пароль (необязательно). Без пароля содержимое читаемо в файле. С ключами сопряжения пароль обязателен.",
        ["Passwort"] = "Пароль",
        ["Passwort wiederholen"] = "Повторите пароль",
        ["Kopplungsschlüssel der Switch-Controller mitnehmen"] = "Включить ключи сопряжения контроллеров Switch",
        ["Kopplungsschlüssel mitnehmen (erst Switch-SD-Karte einlesen)"] = "Включить ключи сопряжения (сначала считайте SD-карту Switch)",
        ["Die Passwörter stimmen nicht überein."] = "Пароли не совпадают.",
        ["Mit Schlüsseln: Passwort mit mindestens 8 Zeichen."] = "С ключами: пароль не менее 8 символов.",
        ["Mindestens 8 Zeichen."] = "Не менее 8 символов.",
        ["Ohne Passwort."] = "Без пароля.",
    };

    /// <summary>Meldungen mit Platzhaltern (Russisch).</summary>
    private static readonly (Regex Pattern, Func<Match, string> Replace)[] PatternsRu =
    [
        (Re(@"^Allgemeiner Wert \((?<v>.+)\) – Regler verschieben für einen eigenen$"), m => $"Общее значение ({m.Groups["v"]}) – сдвиньте ползунок для собственного"),
        (Re(@"^Eigener Wert · allgemein: (?<v>.+)$"), m => $"Собственное значение · общее: {m.Groups["v"]}"),
        (Re(@"^Spieler (?<n>\d+)  ·  (?<k>.+?)(?<rest>(  ·  .*)?)$"), m => $"Игрок {m.Groups["n"]}  ·  {N(m, "k")}{T(m.Groups["rest"].Value)}"),
        (Re(@"^  ·  Gyro-Maus(?<r>.*)$"), m => "  ·  Гиромышь" + T(m.Groups["r"].Value)),
        (Re(@"^  ·  Gyro-Stick$"), _ => "  ·  Гиростик"),
        (Re(@"^Spieler (?<n>\d+) · (?<k>.+?) (?<b>\d+ %.*)?$"), m => $"Игрок {m.Groups["n"]} · {N(m, "k")} {m.Groups["b"]}"),
        (Re(@"^(?<k>.+) verbunden \(Spieler (?<n>\d+)\)$"), m => $"{N(m, "k")} подключён (игрок {m.Groups["n"]})"),
        (Re(@"^Spieler (?<n>\d+) – tauschen mit (?<k>.+)$"), m => $"Игрок {m.Groups["n"]} – поменять с {N(m, "k")}"),
        (Re(@"^Spieler (?<n>\d+) – frei$"), m => $"Игрок {m.Groups["n"]} – свободно"),
        (Re(@"^Spieler (?<n>\d+)$"), m => $"Игрок {m.Groups["n"]}"),
        (Re(@"^Xbox 360 · Platz (?<n>\d+)$"), m => $"Xbox 360 · место {m.Groups["n"]}"),
        (Re(@"^noch (?<n>\d+) s$"), m => $"ещё {m.Groups["n"]} с"),
        (Re(@"^Fertig – (?<n>\d+) Controller verbunden$"), m => $"Готово – подключено контроллеров: {m.Groups["n"]}"),
        (Re(@"^✓ (?<k>.+) verbunden – Spieler (?<n>\d+)$"), m => $"✓ {N(m, "k")} подключён – игрок {m.Groups["n"]}"),
        (Re(@"^Spieler (?<n>\d+)  ·  (?<v>.+)$"), m => $"Игрок {m.Groups["n"]}  ·  {m.Groups["v"]}"),
        (Re(@"^Gekoppelt: (?<k>.+) – verbindet gleich …$"), m => $"Сопряжён: {m.Groups["k"]} – подключение …"),
        (Re(@"^Ins Spiel wechseln … (?<n>\d+)$"), m => $"Переключитесь в игру … {m.Groups["n"]}"),
        (Re(@"^(?<k>.+) ist jetzt Spieler (?<n>\d+)$"), m => $"{N(m, "k")} теперь игрок {m.Groups["n"]}"),
        (Re(@"^Spieler (?<a>\d+) und (?<b>\d+) getauscht$"), m => $"Игроки {m.Groups["a"]} и {m.Groups["b"]} поменяны"),
        (Re(@"^Name für (?<k>.+) \(leer = Standardname\):$"), m => $"Имя для {N(m, "k")} (пусто = имя по умолчанию):"),
        (Re(@"^(?<k>.+) \(Joy-Con-Paar\)$"), m => $"{m.Groups["k"]} (пара Joy-Con)"),
        (Re(@"^Joy-Con zusammengefasst \(Spieler (?<n>\d+)\)$"), m => $"Joy-Con объединены (игрок {m.Groups["n"]})"),
        (Re(@"^Joy-Con getrennt – (?<k>.+) ist jetzt Spieler (?<n>\d+)$"), m => $"Joy-Con разъединён – {N(m, "k")} теперь игрок {m.Groups["n"]}"),
        (Re(@"^Spieler (?<n>\d+): Akku (?<k>.+) fast leer \((?<p>\d+) %\) – bitte aufladen$"),
            m => $"Игрок {m.Groups["n"]}: батарея {N(m, "k")} почти пуста ({m.Groups["p"]} %) – зарядите"),
        (Re(@"^Spieler (?<n>\d+): nach (?<m>\d+) min ohne Eingabe getrennt$"),
            m => $"Игрок {m.Groups["n"]}: отключён через {m.Groups["m"]} мин без действий"),
        (Re(@"^Profil „(?<p>.+)“ aktiv$"), m => $"Профиль «{ProfileName(m.Groups["p"].Value)}» активен"),
        (Re(@"^Profil: (?<p>.+)$"), m => $"Профиль: {ProfileName(m.Groups["p"].Value)}"),
        (Re(@"^Profil „(?<p>.+)“ löschen\?$"), m => $"Удалить профиль «{m.Groups["p"]}»?"),
        (Re(@"^Profil „(?<p>.+)“ importiert(?<r>.*)$"), m => $"Профиль «{m.Groups["p"]}» импортирован" + m.Groups["r"].Value.Replace("aktiv bei:", "активен при:")),
        (Re(@"^⬇ Neue Version (?<v>.+) herunterladen …$"), m => $"⬇ Скачать новую версию {m.Groups["v"]} …"),
        (Re(@"^Version (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Herunterladen\.$"),
            m => $"Версия {m.Groups["v"]} вышла (установлена: {m.Groups["i"]}). Нажмите для загрузки."),
        (Re(@"^Version (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Installieren\.$"),
            m => $"Версия {m.Groups["v"]} вышла (установлена: {m.Groups["i"]}). Нажмите для установки."),
        (Re(@"^⬇ Auf Version (?<v>.+) aktualisieren …$"), m => $"⬇ Обновить до версии {m.Groups["v"]} …"),
        (Re(@"^Lade Version (?<v>.+) herunter …$"), m => $"Загрузка версии {m.Groups["v"]} …"),
        (Re(@"^HidHide (?<v>.+) ist erschienen \(installiert: (?<i>.+)\)\. Klicken zum Installieren\.$"),
            m => $"HidHide {m.Groups["v"]} вышел (установлен: {m.Groups["i"]}). Нажмите для установки."),
        (Re(@"^Lade HidHide (?<v>.+) herunter …$"), m => $"Загрузка HidHide {m.Groups["v"]} …"),
        (Re(@"^(?<t>.+) · (?<r>\d+) Berichte/s$"), m => $"{T(m.Groups["t"].Value)} · {m.Groups["r"]} отчётов/с"),
        (Re(@"^(?<p>\d+ %)(?<v>  \(.*\))?  ⚡ lädt$"), m => $"{m.Groups["p"]}{m.Groups["v"]}  ⚡ заряжается"),
        (Re(@"^Speichern fehlgeschlagen: (?<e>.*)$"), m => $"Не удалось сохранить: {m.Groups["e"]}"),
        (Re(@"^Lesen fehlgeschlagen: (?<e>.*)$"), m => $"Не удалось прочитать: {m.Groups["e"]}"),
        (Re(@"^amiibo konnte nicht gelesen werden: (?<e>.*)$"), m => $"Не удалось прочитать amiibo: {T(m.Groups["e"].Value)}"),
        (Re(@"^Gekoppelt: (?<k>.+)$"), m => $"Сопряжён: {m.Groups["k"]}"),
        (Re(@"^Gefunden: (?<k>.+) – kopple …$"), m => $"Найден: {m.Groups["k"]} – сопряжение …"),
        (Re(@"^amiibo erkannt \((?<u>.+)\) – lese …$"), m => $"amiibo обнаружен ({m.Groups["u"]}) – чтение …"),
        (Re(@"^(?<n>\d+) Minuten$"), m => $"{m.Groups["n"]} минут"),
        (Re(@"^✓ (?<n>\d+) Schritte, Dauer (?<ms>\d+) ms$"), m => $"✓ шагов: {m.Groups["n"]}, всего {m.Groups["ms"]} мс"),
        (Re(@"^Controller-Taste „(?<b>.+)“:\nJetzt die gewünschte Taste oder Tastenkombination drücken\.$"),
            m => $"Кнопка контроллера «{T(m.Groups["b"].Value)}»:\nТеперь нажмите нужную клавишу или сочетание."),
        (Re(@"^Solange „(?<b>.+)“ gehalten wird, wird diese Taste schnell wiederholt gedrückt\n\(Geschwindigkeit unter 5\. „Turbo“\):$"),
            m => $"Пока удерживается «{T(m.Groups["b"].Value)}», эта кнопка быстро повторяется\n(скорость в п. 5 «Турбо»):"),
        (Re(@"^Ring-Con: (?<e>.*)$"), m => $"Ring-Con: {T(m.Groups["e"].Value)}"),
        (Re(@"^⌨  Taste: (?<k>.+)$"), m => $"⌨  Клавиша: {m.Groups["k"]}"),
        (Re(@"^🔁  Turbo: Taste (?<k>.+)$"), m => $"🔁  Турбо: клавиша {m.Groups["k"]}"),
        (Re(@"^🔁  Turbo: (?<k>.+)$"), m => $"🔁  Турбо: {T(m.Groups["k"].Value)}"),
        (Re(@"^⏯  Makro: (?<k>.+)$"), m => $"⏯  Макрос: {m.Groups["k"]}"),
        (Re(@"^Tastatur: (?<k>.+)$"), m => $"Клавиатура: {m.Groups["k"]}"),
        (Re(@"^Gamepad: (?<k>.+)$"), m => $"Геймпад: {m.Groups["k"]}"),
        (Re(@"^(?<k>.+)  \(verbunden\)$"), m => $"{N(m, "k")}  (подключён)"),
        (Re(@"^Bluetooth nicht verfügbar: (?<e>.*)$"), m => $"Bluetooth недоступен: {m.Groups["e"]}"),
        (Re(@"^(?<k>.+) per USB ist von einem anderen Programm belegt \(z\. B\. Steam\)\.$"),
            m => $"{N(m, "k")} по USB занят другой программой (напр. Steam)."),
        (Re(@"^Schon (?<n>\d+) Controller verbunden – (?<k>.+) wird nicht verwendet\.$"),
            m => $"Уже подключено контроллеров: {m.Groups["n"]} – {N(m, "k")} не используется."),
        (Re(@"^(?<k>.+): schwache Bluetooth-Verbindung \((?<r>\d+) statt 33–60 Berichte/s\)\.$"),
            m => $"{N(m, "k")}: слабое соединение Bluetooth ({m.Groups["r"]} вместо 33–60 отчётов/с)."),
        (Re(@"^(?<k>.+) getrennt$"), m => $"{N(m, "k")} отключён"),
    ];
}
