namespace Switch2Pro.Bridge;

/// <summary>Feste Texte Deutsch → Englisch.</summary>
internal static partial class Tr
{
    private static readonly Dictionary<string, string> Texts = new(StringComparer.Ordinal)
    {
        // ---------- Fenster, Reiter, Abschnitte ----------
        ["Nintendo Controller für Windows"] = "Nintendo Controller for Windows",
        ["Controller"] = "Controllers",
        ["Einstellungen (optional)"] = "Settings (optional)",
        ["1. Windows und Spiele sehen den Controller als …"] = "1. Windows and games see the controller as …",
        ["2. Tasten A/B/X/Y"] = "2. A/B/X/Y buttons",
        ["3. Vibration, Sticks, Verbinden, Gyro-Maus"] = "3. Vibration, sticks, connecting, gyro mouse",
        ["4. Joy-Con"] = "4. Joy-Con",
        ["4. Joy-Con und Wii"] = "4. Joy-Con and Wii",
        ["Wii-Fernbedienung: Zeiger (Sensorleiste) steuert die Maus"] = "Wii Remote: pointer (sensor bar) moves the mouse",
        ["Zeiger"] = "Pointer",
        ["kein Zeiger – Sensorleiste nicht im Blick"] = "no pointer – sensor bar not in view",
        ["MotionPlus"] = "MotionPlus",
        ["5. Zielen, Sticks, Trigger, Turbo"] = "5. Aiming, sticks, triggers, turbo",
        ["6. Tastenbelegung und Profile  (Taste → Gamepad, Tastatur, Maus, Gyro-Maus, Shift-Ebene)"] =
            "6. Button mapping and profiles  (button → gamepad, keyboard, mouse, gyro mouse, shift layer)",
        ["Xbox-360-Controller  (empfohlen – läuft mit fast allen Spielen)"] = "Xbox 360 controller  (recommended – works with almost all games)",
        ["PlayStation DualShock 4  (mit Bewegungssteuerung/Gyro – für Steam && Emulatoren)"] =
            "PlayStation DualShock 4  (with motion controls/gyro – for Steam && emulators)",
        ["Xbox-Belegung  (nach Position: untere Taste = A)"] = "Xbox layout  (by position: bottom button = A)",
        ["Nintendo-Belegung  (nach Beschriftung: A bleibt A)"] = "Nintendo layout  (by label: A stays A)",
        ["Vibration"] = "Vibration",
        ["Stärke:"] = "Strength:",
        ["Stick-Totzone (alle Controller):"] = "Stick deadzone (all controllers):",
        ["Beim Verbinden kurz vibrieren"] = "Vibrate briefly when connecting",
        ["Gekoppelte Controller per Tastendruck verbinden (ohne SYNC)"] = "Connect paired controllers with a button press (no SYNC)",
        ["Automatisch mit Windows starten"] = "Start automatically with Windows",
        ["Gyro für Emulatoren bereitstellen (Cemuhook/DSU, Port 26760 – wirkt nach Neustart)"] =
            "Provide gyro for emulators (Cemuhook/DSU, port 26760 – takes effect after restart)",
        ["Beim Start nach neuer Version suchen (GitHub)"] = "Check for a new version at startup (GitHub)",
        ["Ohne Eingabe automatisch trennen nach:"] = "Disconnect automatically without input after:",
        ["Gyro-Maus-Geschwindigkeit:"] = "Gyro mouse speed:",
        ["Sprache / Language:"] = "Language / Sprache:",
        ["Automatisch (wie Windows)"] = "Automatic (like Windows)",
        ["nie"] = "never",
        ["Zwei Joy-Con automatisch zu einem Controller zusammenfassen"] = "Combine two Joy-Cons into one controller automatically",
        ["Gyro beim Paar vom:"] = "Pair gyro from:",
        ["rechter Joy-Con (wie Switch)"] = "right Joy-Con (like Switch)",
        ["linker Joy-Con"] = "left Joy-Con",
        ["Joy-Con 2 als Maus, wenn er auf dem Tisch liegt"] = "Joy-Con 2 as a mouse when it stands on the table",
        ["Mausgeschwindigkeit:"] = "Mouse speed:",
        ["Maus: links/rechts umkehren"] = "Mouse: invert left/right",
        ["Maus: hoch/runter umkehren"] = "Mouse: invert up/down",
        ["Wie an der Switch: SL + SR eine Sekunde halten löst einen Joy-Con aus dem Paar. L am linken und R am rechten einzelnen Joy-Con gleichzeitig drücken verbindet sie wieder zum Paar. Die Wahl wird je Joy-Con gemerkt (auch nach dem nächsten Verbinden). Im Mausmodus: R/L = Linksklick, ZR/ZL = Rechtsklick, Stick drücken = Mittelklick, Stick hoch/runter = Scrollen."] =
            "Like on the Switch: holding SL + SR for a second splits a Joy-Con from the pair. Pressing L on the left and R on the right single Joy-Con at the same time pairs them again. The choice is remembered per Joy-Con (also for the next connection). In mouse mode: R/L = left click, ZR/ZL = right click, press stick = middle click, stick up/down = scroll.",
        ["Gyro als rechter Stick:"] = "Gyro as right stick:",
        ["aus (nur per Taste „Gyro-Stick“)"] = "off (only via a “gyro stick” button)",
        ["immer"] = "always",
        ["beim Zielen (solange ZL / linker Trigger gedrückt)"] = "while aiming (while ZL / left trigger is held)",
        ["hoch/runter umkehren"] = "invert up/down",
        ["Empfindlichkeit:"] = "Sensitivity:",
        ["Mindestausschlag:"] = "Minimum deflection:",
        ["Stick-Kennlinie:"] = "Stick curve:",
        ["Turbo (pro Sekunde):"] = "Turbo (per second):",
        ["Analoge Trigger (GameCube) – Totzone:"] = "Analog triggers (GameCube) – deadzone:",
        ["voll gedrückt ab:"] = "fully pressed at:",
        ["Profil:"] = "Profile:",
        ["Neu …"] = "New …",
        ["Umbenennen …"] = "Rename …",
        ["Löschen"] = "Delete",
        ["Exportieren …"] = "Export …",
        ["Importieren …"] = "Import …",
        ["Aktiv bei Programm:"] = "Active for program:",
        ["Programm wählen …"] = "Choose program …",
        ["Standard"] = "Default",
        ["Standard gilt immer, wenn kein anderes Profil passt"] = "Default applies whenever no other profile matches",
        ["z. B. Cemu.exe, Ryujinx.exe"] = "e.g. Cemu.exe, Ryujinx.exe",
        ["Ein eigenes Profil wird automatisch aktiv, solange eines seiner Programme im Vordergrund ist (sonst gilt „Standard“). Im Infobereich-Menü lässt sich ein Profil auch fest wählen."] =
            "A custom profile becomes active automatically while one of its programs is in the foreground (otherwise “Default” applies). A profile can also be fixed in the tray menu.",
        ["Controller:"] = "Controller:",
        ["Eigene Stick-Totzone für diesen Controller:"] = "Own stick deadzone for this controller:",
        ["Normale Belegung"] = "Normal mapping",
        ["Shift-Ebene (gilt, solange eine Taste mit „Shift-Ebene“ gehalten wird)"] = "Shift layer (applies while a button with “shift layer” is held)",
        ["Alles auf Standard"] = "Reset everything",
        ["Schließen"] = "Close",
        ["wie normale Belegung"] = "same as normal mapping",

        // ---------- Belegungsziele und Vorlagen ----------
        ["— keine Funktion —"] = "— no function —",
        ["A (Xbox) / Kreuz (PS)"] = "A (Xbox) / Cross (PS)",
        ["B (Xbox) / Kreis (PS)"] = "B (Xbox) / Circle (PS)",
        ["X (Xbox) / Viereck (PS)"] = "X (Xbox) / Square (PS)",
        ["Y (Xbox) / Dreieck (PS)"] = "Y (Xbox) / Triangle (PS)",
        ["Ansicht (Back) / Share"] = "View (Back) / Share",
        ["Menü (Start) / Options"] = "Menu (Start) / Options",
        ["Xbox-Taste / PS-Taste"] = "Xbox button / PS button",
        ["Linker Stick-Klick"] = "Left stick click",
        ["Rechter Stick-Klick"] = "Right stick click",
        ["Steuerkreuz hoch"] = "D-pad up",
        ["Steuerkreuz runter"] = "D-pad down",
        ["Steuerkreuz links"] = "D-pad left",
        ["Steuerkreuz rechts"] = "D-pad right",
        ["Touchpad-Klick (nur DualShock 4)"] = "Touchpad click (DualShock 4 only)",
        ["🖱  Maus: Linksklick"] = "🖱  Mouse: left click",
        ["🖱  Maus: Rechtsklick"] = "🖱  Mouse: right click",
        ["🖱  Maus: Mittelklick"] = "🖱  Mouse: middle click",
        ["🎯  Gyro-Maus (solange gehalten)"] = "🎯  Gyro mouse (while held)",
        ["🎯  Gyro-Maus ein/aus"] = "🎯  Gyro mouse on/off",
        ["🎯  Gyro als rechter Stick (solange gehalten)"] = "🎯  Gyro as right stick (while held)",
        ["🎯  Gyro als rechter Stick ein/aus"] = "🎯  Gyro as right stick on/off",
        ["⇧  Shift-Ebene (solange gehalten)"] = "⇧  Shift layer (while held)",
        ["🔁  Turbo / Dauerfeuer …"] = "🔁  Turbo / rapid fire …",
        ["⏯  Makro (Tastenfolge) …"] = "⏯  Macro (button sequence) …",
        ["📷  Bildschirmfoto speichern (Win+Druck)"] = "📷  Save screenshot (Win+PrtScn)",
        ["📷  Bildschirmausschnitt (Win+Umschalt+S)"] = "📷  Screen snip (Win+Shift+S)",
        ["⏺  Letzte 30 Sekunden aufnehmen (Win+Alt+G)"] = "⏺  Record last 30 seconds (Win+Alt+G)",
        ["⏺  Aufnahme starten/stoppen (Win+Alt+R)"] = "⏺  Start/stop recording (Win+Alt+R)",
        ["🎮  Xbox Game Bar (Win+G)"] = "🎮  Xbox Game Bar (Win+G)",
        ["🔊  Lauter"] = "🔊  Volume up",
        ["🔉  Leiser"] = "🔉  Volume down",
        ["⏯  Wiedergabe/Pause"] = "⏯  Play/pause",
        ["⌨  Andere Taste / Tastenkombination aufnehmen …"] = "⌨  Record another key / key combination …",

        // ---------- Tastennamen ----------
        ["+ (Plus)"] = "+ (Plus)",
        ["− (Minus)"] = "− (Minus)",
        ["Aufnahme"] = "Capture",
        ["GL (Rücktaste links)"] = "GL (left back button)",
        ["GR (Rücktaste rechts)"] = "GR (right back button)",
        ["Linker Stick drücken"] = "Press left stick",
        ["Rechter Stick drücken"] = "Press right stick",
        ["Stick drücken"] = "Press stick",
        ["A (groß, unten)"] = "A (large, bottom)",
        ["B (links)"] = "B (left)",
        ["X (rechts)"] = "X (right)",
        ["Y (oben)"] = "Y (top)",
        ["L (ganz durchgedrückt)"] = "L (fully pressed)",
        ["R (ganz durchgedrückt)"] = "R (fully pressed)",
        ["untere Taste (quer)"] = "bottom button (sideways)",
        ["rechte Taste (quer)"] = "right button (sideways)",
        ["linke Taste (quer)"] = "left button (sideways)",
        ["obere Taste (quer)"] = "top button (sideways)",
        ["1 (quer) / Classic Y"] = "1 (sideways) / Classic Y",
        ["2 (quer) / Classic B"] = "2 (sideways) / Classic B",
        ["B (Abzug) / Classic ZR"] = "B (trigger) / Classic ZR",

        // ---------- Controller-Namen ----------
        ["Wii-Fernbedienung"] = "Wii Remote",

        // ---------- Übersicht / Karten ----------
        ["Kein Controller verbunden\n\nSwitch-2-Controller: kurz die SYNC-Taste drücken – danach reicht ein beliebiger Tastendruck.\nSwitch-1- und NSO-Controller (NES, SNES, N64, Mega Drive): einmal in Windows unter „Bluetooth“ koppeln.\nWii-Fernbedienung / Wii U Pro: Rechtsklick auf das Symbol im Infobereich → „Wii-Controller koppeln …“."] =
            "No controller connected\n\nSwitch 2 controllers: press the SYNC button briefly – afterwards any button press is enough.\nSwitch 1 and NSO controllers (NES, SNES, N64, Mega Drive): pair once in Windows under “Bluetooth”.\nWii Remote / Wii U Pro: right-click the tray icon → “Pair Wii controller …”.",
        ["Trennen"] = "Disconnect",
        ["Vibrieren"] = "Vibrate",
        ["Gyro kalibrieren"] = "Calibrate gyro",
        ["Ruhig liegen lassen …"] = "Keep it still …",
        ["Kalibriert ✓"] = "Calibrated ✓",
        ["Hochkant halten"] = "Hold upright",
        ["Quer halten"] = "Hold sideways",
        ["Joy-Con trennen"] = "Split Joy-Cons",
        ["Zum Paar verbinden"] = "Combine into pair",
        ["Doppelt angezeigt? Verstecken"] = "Shown twice? Hide",
        ["amiibo lesen"] = "Read amiibo",
        ["Ring-Con ein"] = "Ring-Con on",
        ["Ring-Con aus"] = "Ring-Con off",
        ["Ring-Con wird gesucht …"] = "Looking for Ring-Con …",
        ["IR-Kamera"] = "IR camera",
        ["Akku"] = "Battery",
        ["Verbindung"] = "Connection",
        ["Adresse"] = "Address",
        ["Seriennummer"] = "Serial number",
        ["Firmware"] = "Firmware",
        ["Griff"] = "Grip",
        ["Maus"] = "Mouse",
        ["Gedrückt"] = "Pressed",
        ["unbekannt"] = "unknown",
        ["Charging Grip – GL/GR aktiv"] = "Charging Grip – GL/GR active",
        ["aktiv (liegt auf dem Tisch)"] = "active (on the table)",
        ["bereit – zum Benutzen auf den Tisch legen"] = "ready – stand it on the table to use",
        ["Bluetooth LE"] = "Bluetooth LE",
        ["Bluetooth"] = "Bluetooth",
        ["Bewegungssensor: keine Daten"] = "Motion sensor: no data",
        ["quer halten: Steuerkreuz links,\n1 und 2 rechts"] = "hold sideways: d-pad left,\n1 and 2 right",

        // ---------- Tooltips ----------
        ["Verbindung trennen. Der Controller verbindet sich beim nächsten Tastendruck wieder."] =
            "Disconnect. The controller reconnects with the next button press.",
        ["Controller kurz vibrieren lassen – zeigt, welcher Controller dieser Spieler ist."] =
            "Vibrate the controller briefly – shows which controller this player is.",
        ["Controller ruhig auf den Tisch legen und klicken: misst den Gyro-Nullpunkt neu (gegen Abdriften)."] =
            "Put the controller still on the table and click: measures the gyro zero point again (against drift).",
        ["Einzelnen Joy-Con quer (wie an der Switch) oder hochkant halten – wird je Joy-Con gemerkt. Hochkant gilt die Tastenbelegung von „Joy-Con-Paar“."] =
            "Hold a single Joy-Con sideways (like on the Switch) or upright – remembered per Joy-Con. Upright uses the “Joy-Con pair” mapping.",
        ["Versteckt den per USB angeschlossenen Controller vor Spielen (HidHide), damit sie nur den virtuellen Xbox-Controller sehen."] =
            "Hides the USB-connected controller from games (HidHide) so they only see the virtual Xbox controller.",
        ["amiibo mit dem NFC-Leser lesen und als Datei (.bin) speichern – z. B. für Emulatoren."] =
            "Read an amiibo with the NFC reader and save it as a file (.bin) – e.g. for emulators.",
        ["Ring-Con am rechten Joy-Con ein-/ausschalten: zusammendrücken = rechter Trigger, auseinanderziehen = linker Trigger. Beim Einschalten den Ring nicht berühren."] =
            "Turn the Ring-Con on the right Joy-Con on/off: squeeze = right trigger, pull = left trigger. Don't touch the ring while turning it on.",
        ["Live-Bild der IR-Kamera im rechten Joy-Con anzeigen."] = "Show the live image of the IR camera in the right Joy-Con.",
        ["Links = empfindlicher (kleine Drehung, großer Ausschlag), rechts = ruhiger."] = "Left = more sensitive (small turn, large deflection), right = calmer.",
        ["Mindestausschlag des Sticks bei Bewegung – überwindet die Totzone des Spiels."] = "Minimum stick deflection when moving – overcomes the game's deadzone.",
        ["Mitte = linear. Rechts = feiner um die Mitte (präzises Zielen), links = schneller."] = "Middle = linear. Right = finer around the center (precise aiming), left = faster.",
        ["So weit lässt sich ein analoger Trigger drücken, bevor er wirkt."] = "How far an analog trigger can be pressed before it takes effect.",
        ["Ab hier gilt der Trigger als ganz gedrückt (100 = erst am Anschlag)."] = "From here the trigger counts as fully pressed (100 = only at the end).",
        ["Wie oft pro Sekunde Tasten mit „Turbo“ auslösen."] = "How often per second buttons with “turbo” fire.",

        // ---------- Infobereich ----------
        ["ViGEmBus-Treiber fehlt"] = "ViGEmBus driver missing",
        ["ViGEmBus herunterladen …"] = "Download ViGEmBus …",
        ["Verbinde …"] = "Connecting …",
        ["Kein Controller – SYNC-Taste am Controller kurz drücken"] = "No controller – briefly press the SYNC button on the controller",
        ["Ausgabe als"] = "Output as",
        ["Xbox-360-Controller (empfohlen)"] = "Xbox 360 controller (recommended)",
        ["DualShock 4 (mit Gyro für Steam/Emulatoren)"] = "DualShock 4 (with gyro for Steam/emulators)",
        ["Tastenbelegung"] = "Button layout",
        ["Xbox-Belegung (untere Taste = A)"] = "Xbox layout (bottom button = A)",
        ["Switch-2-Pro-Belegung (A bleibt A)"] = "Nintendo layout (A stays A)",
        ["Automatisch (nach Spiel/Programm)"] = "Automatic (by game/program)",
        ["Mit Windows starten"] = "Start with Windows",
        ["Einstellungen …"] = "Settings …",
        ["Wii-Controller koppeln …"] = "Pair Wii controller …",
        ["Kurzanleitung"] = "Quick guide",
        ["Protokoll öffnen"] = "Open log",
        ["Beenden"] = "Exit",
        ["Nintendo Controller: warte auf Controller (SYNC drücken)"] = "Nintendo Controller: waiting for a controller (press SYNC)",
        ["Nintendo Controller: ViGEmBus fehlt"] = "Nintendo Controller: ViGEmBus missing",
        ["Neue Version verfügbar"] = "New version available",
        ["Einstellungen fehlerhaft"] = "Settings damaged",
        ["settings.json konnte nicht gelesen werden – es gelten die Standardwerte."] = "settings.json could not be read – defaults apply.",
        ["Ohne ViGEmBus kann kein virtueller Controller erzeugt werden. Bitte das Setup erneut ausführen oder ViGEmBus installieren (Rechtsklick auf das Symbol → ViGEmBus herunterladen)."] =
            "Without ViGEmBus no virtual controller can be created. Please run setup again or install ViGEmBus (right-click the icon → Download ViGEmBus).",

        // ---------- Dialoge ----------
        ["Tastatur-Taste festlegen"] = "Set keyboard key",
        ["Übernehmen"] = "Apply",
        ["Abbrechen"] = "Cancel",
        ["Turbo / Dauerfeuer"] = "Turbo / rapid fire",
        ["Tastatur-Taste aufnehmen …"] = "Record keyboard key …",
        ["Makro (Tastenfolge)"] = "Macro (button sequence)",
        ["Ungültig – bitte Schreibweise prüfen (siehe oben)."] = "Invalid – please check the notation (see above).",
        ["Neues Profil"] = "New profile",
        ["Name des Profils (z. B. der Spielname):"] = "Profile name (e.g. the game's name):",
        ["Profil umbenennen"] = "Rename profile",
        ["Neuer Name:"] = "New name:",
        ["Ein Profil mit diesem Namen gibt es schon."] = "A profile with this name already exists.",
        ["Die Datei enthält kein gültiges Controller-Profil."] = "The file does not contain a valid controller profile.",
        ["Alle Einstellungen und Tastenbelegungen auf Standard zurücksetzen?"] = "Reset all settings and button mappings to default?",
        ["Wii-Controller koppeln"] = "Pair Wii controller",
        ["Wii-Fernbedienung: Batteriefach öffnen und die rote SYNC-Taste drücken.\nWii U Pro Controller: die SYNC-Taste auf der Unterseite drücken.\nDanach verbindet sich der Controller künftig per Tastendruck."] =
            "Wii Remote: open the battery compartment and press the red SYNC button.\nWii U Pro Controller: press the SYNC button on the bottom.\nAfterwards the controller connects with a button press.",
        ["Suche …"] = "Searching …",
        ["Suche … rote SYNC-Taste der Fernbedienung (im Batteriefach) bzw. des Wii U Pro Controllers drücken."] =
            "Searching … press the red SYNC button of the remote (in the battery compartment) or of the Wii U Pro Controller.",
        ["Kein Bluetooth-Adapter gefunden."] = "No Bluetooth adapter found.",
        ["Kein Wii-Controller gefunden. SYNC-Taste drücken und erneut versuchen."] = "No Wii controller found. Press SYNC and try again.",
        ["IR-Kamera (Joy-Con R)"] = "IR camera (Joy-Con R)",
        ["Auflösung:"] = "Resolution:",
        ["40 × 30 (schnell)"] = "40 × 30 (fast)",
        ["320 × 240 (langsam)"] = "320 × 240 (slow)",
        ["Kamera startet …"] = "Camera starting …",
        ["läuft – Joy-Con auf eine Lichtquelle oder die Hand richten"] = "running – point the Joy-Con at a light source or your hand",
        ["Kamera startet nicht (Details im Protokoll)"] = "Camera does not start (details in the log)",
        ["Ring-Con"] = "Ring-Con",
        ["Kein Ring-Con gefunden. Den rechten Joy-Con (Switch 1) fest in den Ring-Con schieben und erneut versuchen."] =
            "No Ring-Con found. Slide the right Joy-Con (Switch 1) firmly into the Ring-Con and try again.",
        ["Kein amiibo erkannt. Bitte das amiibo flach an den NFC-Leser halten (Joy-Con: auf den rechten Stick, Pro Controller: auf das NFC-Logo) und erneut versuchen."] =
            "No amiibo detected. Hold the amiibo flat against the NFC reader (Joy-Con: on the right stick, Pro Controller: on the NFC logo) and try again.",
        ["NFC-Leser wird eingeschaltet …"] = "Turning on the NFC reader …",
        ["amiibo an den Leser halten (rechter Stick des Joy-Con bzw. NFC-Logo des Pro Controllers) …"] =
            "Hold the amiibo to the reader (right stick of the Joy-Con or NFC logo of the Pro Controller) …",
        ["amiibo speichern"] = "Save amiibo",
        ["Doppelte Controller verhindern"] = "Prevent duplicate controllers",
        ["Dafür wird das kostenlose Programm HidHide gebraucht (von den Machern von ViGEmBus).\n\nJetzt die Download-Seite öffnen? Nach der Installation hier erneut klicken."] =
            "This needs the free program HidHide (by the makers of ViGEmBus).\n\nOpen the download page now? Click here again after installing it.",
        ["HidHide konnte nicht eingerichtet werden (abgebrochen oder fehlgeschlagen). Details im Protokoll."] =
            "HidHide could not be set up (cancelled or failed). Details in the log.",
        ["Der Controller hat sich bewegt oder keine Bewegungsdaten geliefert.\nBitte flach auf den Tisch legen, nicht berühren und erneut versuchen."] =
            "The controller moved or did not deliver motion data.\nPlease put it flat on the table, don't touch it and try again.",
        ["Spiel oder Programm wählen"] = "Choose game or program",
        ["Profil exportieren"] = "Export profile",
        ["Profil importieren"] = "Import profile",
        ["Verstanden"] = "Got it",
        ["Einstellungen öffnen"] = "Open settings",
        ["Willkommen"] = "Welcome",
        ["Erst IR-Kamera bzw. Ring-Con ausschalten (sie nutzen denselben Zusatzprozessor wie der NFC-Leser)."] =
            "Turn off the IR camera or Ring-Con first (they use the same co-processor as the NFC reader).",
        ["Erst die IR-Kamera schließen (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "Close the IR camera first (Ring-Con and IR camera use the same co-processor).",
        ["Erst den Ring-Con ausschalten (Ring-Con und IR-Kamera nutzen denselben Zusatzprozessor)."] =
            "Turn off the Ring-Con first (Ring-Con and IR camera use the same co-processor).",
        ["amiibo zu früh entfernt"] = "amiibo removed too early",
        ["MCU startet nicht"] = "co-processor does not start",
        ["NFC-Modus nicht aktiv"] = "NFC mode not active",
        ["Kopplung fehlgeschlagen – Details im Protokoll."] = "Pairing failed – details in the log.",
    };
}
